statamic/cms

tests/TestCase.php

In our base test class, we have a couple of mocks that fake the version and nav being built.
In versions of Mockery prior to 1.5.1, this would add an assertion count, but we didn't care about it actually counting it, so we negated it.
For example:
```php
\Facades\Statamic\Version::shouldReceive('get')->andReturn('3.0.0-testing');
$this->addToAssertionCount(-1); // Dont want to assert this
```
In Mockery 1.5.1, they fixed it so that if you aren't actually counting the number of times the method is called, it doesn't consider it an assertion. https://github.com/mockery/mockery/pull/1180
So now our tests can go into the negative.
```
OK (1 test, -1 assertions)
```
We could bump the mockery requirement to 1.5.1 and remove the `$this->addToAssertionCount(-1)`, but it's a bit hairy with all the …

Fix negative assertion counts

---

tests/Extend/AddonTest.php
tests/FrontendTest.php
tests/Licensing/AddonLicenseTest.php
tests/Licensing/LicenseManagerTest.php
tests/Stache/FeatureTest.php

Because of an update to Mockery, we had to fix negative assertion counts in #6689. I noticed when running the suite, we are now getting all these risky test warnings for the same reason (see below). This PR fixes these warnings.
```
There were 15 risky tests:
1) Statamic\Testing\Extend\AddonTest::it_writes_file_contents
This test did not perform any assertions
/Users/jesseleite/Code/Wilderborn/cms/tests/Extend/AddonTest.php:145
2) Tests\Licensing\AddonLicenseTest::it_gets_the_addons_name
This test did not perform any assertions
/Users/jesseleite/Code/Wilderborn/cms/tests/Licensing/AddonLicenseTest.php:23
3) Tests\Licensing\AddonLicenseTest::it_gets_the_addons_version
This test did not perform any assertions
/Users/jesseleite/Code/Wilderborn/cms/tests/Licensing/AddonLicenseTest.php:29
4) …
```

Fix risky test warnings

---

src/Tags/Cache.php
tests/Tags/CacheTagTest.php

Fixes #4127. It also adds tests for the `Cache` tag class.
This will make sure that on multisite, a cache tag with scope="site" will cache its contents **per site**. When you do want to cache across all sites, you can use scope="global".

Fix cache tag with scope="site" on multisite

---

src/Policies/AssetFolderPolicy.php

Fixes #6696
The "move" and "rename" asset folder permissions weren't hooked up properly.
Also, the "delete" folder permission was only checking assets in that folder, not nested folders.

Fix asset folder permissions

---

resources/js/components/fieldtypes/DateFieldtype.vue

#6688 adjusted the prop passed to the date picker, but it should have left it alone when using ranged mode.

Fix date fieldtype in range mode

---

src/OAuth/Provider.php
tests/OAuth/ProviderTest.php

Fixes #3269.
For any conflicts in the data I've set the merge strategy to "Socialite wins".

Merge user data on new OAuth login for an existing user

---

src/Actions/Action.php
src/Http/Controllers/CP/ActionController.php

This PR will pre- and post-process action values.
If you were to add, for example, an `assets` field to an action, it wouldn't be preprocessed. ie. It wouldn't default to an empty array, and there'd be an error when you try to use the field.
Post-processing is also added. Again, if you were to submit an assets field with a max_files option of 1, you _should_ receive just the string. But you didn't, you got an array with a single item in it. Adding processing fixes it.
This would be a "breaking" change if you were relying on the incorrect behavior. However I'm just considering this a bug fix.
For simple fields, like text fields, which are mainly what's used within action modals, the lack of processing wouldn't make a difference, which is why this went unnoticed.
(Needed for #4832)

Fix action value processing

---

src/Tags/Vite.php

Closes https://github.com/statamic/ideas/issues/866
Adds the ability to set a custom build directory and hot file location via Laravel's Vite implementation. Requires [laravel/vite-plugin](https://github.com/laravel/vite-plugin/releases/tag/v0.6.0) >=0.6.
Example usage:
```antlers
{{ vite src="resources/css/tailwind.css|resources/js/site.js" directory="bundle" hot="storage/vite.hot" }}
```

Add custom build directory and hot file to Vite tag

---

src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Runtime/PrefixedFieldsTest.php

This PR fixes #6759 by modifying where handle prefixes are injected into the ConditionProcessor.
The following will now work as expected if a variable named `prefixed_title` exists:
```antlers
{{ scope handle_prefx="prefixed_" }}
{{# This will now properly check if the variable "prefixed_title" exists. #}}
{{ if title }}
{{ title }}
{{ /if }}
{{ /scope }}
```

Antlers: Fixes using prefixed variables in conditions

---

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue

Fixes https://github.com/statamic/cms/issues/6730
The issue seems to be that `replicatorPreview` is being read before `initializeAssets` is run, so `this.assets` is empty.
I'm no vue expert, but I thought `replicatorPreview`should react when `this.assets` changes, but that doesn't seem to be happening. There may be a better way to fix this, but emitting `replicator-preview-updated` at the end of `initializeAssets` seems to work.

Fix asset replicator preview

---

src/Modifiers/CoreModifiers.php
tests/Modifiers/KeyByTest.php

This adds a `key_by` modifier that basically calls keyBy on a collection.
A use case might be to target specific values of a numerically indexed array, like the `fields` loop in a form tag.
```antlers
{{ rekeyed = fields | key_by('handle') }}
<div class="foo-field">
{{ rekeyed:foo:display }}
</div>
<div class="bar-field">
{{ rekeyed:bar:display }}
</div>
```

Add key_by modifier

---

resources/js/components/fieldtypes/grid/Grid.vue
resources/js/components/fieldtypes/replicator/Replicator.vue

The replicator preview for grid and replicator fields isn't very useful/user friendly:
This PR implements a very simple alternative, just showing the count and field display name:
Not as fancy as maybe displaying values from a field in each row/set, which would be really nice, but I'm not sure if there's a simple way to do that.
When working on this I noticed that there are `getReplicatorPreviewText()` methods in the List, Assets and Grid fieldtypes. The one in grid was empty. I implemented this with a `replicatorPreview` computed property as per the docs. I'm not really sure what `getReplicatorPreviewText()` is for or even where it's called from?

Improve display of Grid and Replicator replicator preview

---

resources/js/components/fieldtypes/assets/AssetRow.vue
resources/js/components/fieldtypes/assets/AssetTile.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue

SVG assets just display their names in the replicator preview:
This PR fixes that:
I've also enabled the Set Alt option for SVGs. I thought it made sense as they can be used as regular images in an `img` tag, so alt text could be applicable.

Fix svg asset replicator preview and add Set Alt option

---

resources/sass/components/fieldtypes/bard.scss

Fixes https://github.com/statamic/cms/issues/6775
As mentioned in the issue this appears to be due to a Chrome bug. Based on the suggestion in a [comment I found](https://bugs.chromium.org/p/chromium/issues/detail?id=605119#c13) in a related bug report I've added ` position: relative; z-index: 0;` to the set element, which seems to fix it.

Fix shallow Bard set drag and drop ghost in Chrome

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/replicator/Set.vue
resources/sass/components/fieldtypes/bard.scss
resources/sass/components/fieldtypes/replicator.scss

When a Replicator or Bard field contains invalid data, for example a set that has no configuration or a node for an extension that isn’t enabled, the feedback in the CP can be a little mysterious:
- Replicator fields with an invalid set will render an empty item:
- Bard fields with an invalid set will render the raw json (because the `BardSet` component errors):
- Bard fields with invalid nodes/marks end up with a completely blank value.
This PR aims to improve this by fixing the `BardSet` error, checking for invalid data, and adding invalid states (a bit like the Entries and Assets fieldtypes have):
The idea was just to give a bit of a hint about what the problem is, but more details could be added or logged to the console. Tiptap already logs errors when it runs into invalid …

Improve handling of invalid Replicator and Bard field data

---

resources/sass/components/fieldtypes/bard.scss

Fixes https://github.com/statamic/cms/issues/6778
This is an tweak to the fix in https://github.com/statamic/cms/pull/6776, works exactly the same way but it only applies the `display: none` when the sort handle is being hovered, that way it has no impact on other things that could cause the set element to be active (like the popover options).

Fix Bard set menu options not working

---

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue

Fixes https://github.com/statamic/cms/issues/6786
For some reason checking `parent.constructor.name` like in the Bard check doesn't work, always comes back as `VueComponent` not `LinkFieldtype`. Which is why this is checking `config.type` instead.

Fix asset browse button inside link feldtype

---

resources/sass/components/assets.scss

Fixes https://github.com/statamic/cms/issues/6789
This reinstates the 6 column asset grid in the selector at the 2xl breakpoint.
Looks like the selector uses slightly fewer columns per breakpoint than the assets section does, so this follows that convention.
TBH I feel like the breakpoints/columns could be exactly the same as the asset section, there's just as much width available, but I'll leave that to your judgment.

Fix asset selector grid columns

---

.github/workflows/tests.yml
composer.json

Here's some tips about testing multiple versions:
1. You should add `laravel/framework` or one of the `illuminate/*` component to `require` section (already done).
2. The workflow then should only install the opposite requirements to `require-dev`. If you require the framework you should install one of the components using `7.x`, `8.x` or `9.x` constraint, or the opposite.

Fixes GitHub Action workflow to tests on multiple Laravel versions.

---

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue

Fixes https://github.com/statamic/cms/issues/6797
Sorry about this one, I somehow overlooked the fact that the parent component might not be another field 🤦‍♂️ .
Still can't get `parent.constructor.name` to give me anything other than `VueComponent`, so instead this is checking `parent.$options.name`, which gives the right value.
Don't know what's up with the tests, windows seems to be failing everything.

Fix assets fieldtype error

---

src/StarterKits/Exporter.php
src/StarterKits/Hook.php
src/StarterKits/Installer.php
tests/StarterKits/ExportTest.php
tests/StarterKits/HookTest.php
tests/StarterKits/InstallTest.php
tests/StarterKits/__fixtures__/StarterKitHook.php

This is similar to @ryanmitchell's [awesome PR](https://github.com/statamic/cms/pull/6757), except that with this PR, you won't have to manually export or configure the hook in your `starter-kit.yaml` file...
```yaml
export_paths:
- app/Hooks/SomeHook.php
after_install_hook: '\App\Hooks\SomeHook'
```
Instead of requiring the above yaml, it'll implicitly look for a `StarterKitPostInstall.php` class at the starter kit root, and run its `handle()` method...
```php
<?php
class StarterKitPostInstall
{
public function handle($console)
{
//
}
}
```
Also, since this approach isn't copying the script to user-land (it is being run directly from `vendor`), it doesn't need to be deleted/unlinked after.

Starter kit post-install hooks

---

src/Console/Commands/StarterKitInstall.php

See explanation in https://github.com/statamic/cli/pull/56
>We're also removing the 'temporary' comment on --cli-install, because the starter kit installer should never handle the creation of a super user when using this cli installer. It needs to be here [in the cli installer] anyway, for when installing statamic/statamic without a starter kit. Also, we have some windows-specific handling for super user creation in the CLI here.

Avoid prompt to make user when installing starter kit via statamic/cli

---

src/Updater/CoreChangelog.php
src/Version.php

I've a CI/CD GitLab Pipeline with Deployer for my own projects and all unnecessary files such as the composer.lock will get removed for deployment.
That's why I encountered the following exception in production:
`Undefined array key 0 {"userId":"<id>,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at vendor/statamic/cms/src/Updater/CoreChangelog.php:40)`
This exception gets thrown every time anyone uses the Control-Panel, and it wasn't possible to check the license with the outpost nor to view the changelog. In addition, there was a misleading error message in the Control-Panel:
`Error communicating with statamic.com`
It took me hours to find out, that the composer.lock is needed for Statamic to work properly. It would have helped me a lot if there was a better …

Throw exception if composer.lock is missing when finding Statamic version

---

src/Assets/Asset.php
src/Assets/AssetContainer.php
src/Assets/AssetContainerContents.php
tests/Assets/AssetContainerTest.php

Fixes #6821, a performance issue introduced by #6769. 
In order to sync the original state to get the focal point, it would read the meta file. We would only try to read it if the file existed though, but on remote filesystems like S3 this would still result in an API request. The bottleneck is cause by all these new API requests.
This PR fixes the issue by checking whether the meta file is in the already locally cached file listing. It avoids those API requests.
Here are some benchmarks of the average times over 5 requests for a few simple pages I threw together.
**Asset browser:**
Before:  1.23s
After: 202ms
**Frontend page:**
Before: 1.09s
After: 222ms
**Publish form:**
Before: 2.6s
After: 257ms

Fix asset meta bottleneck

---

resources/js/components/assets/Editor/Editor.vue

Fixes #2954.
The issue was that focal point setter assumes that `values` will be an object.
https://github.com/ncla/cms/blob/b28df0896d614383cd0a561359d9d885cb7c00e8/resources/js/components/assets/Editor/Editor.vue#L330-L334
As far as I understood, Vue's special $set is used to trigger reactivity in a component. When the blueprint has no fields, an array is set from the HTTP response. When blueprint has fields, the response value gives us an object.
https://github.com/ncla/cms/blob/b28df0896d614383cd0a561359d9d885cb7c00e8/resources/js/components/assets/Editor/Editor.vue#L295-L298
However because `values` is an array now, `this.$set(this.values, 'focus', point);` will not work because it assumes the property in an object. If you set 2nd argument to a number then it will be used as an array …

Fix focal point not saving when asset blueprint has no fields

---

src/GraphQL/Types/FieldType.php
tests/Feature/GraphQL/FormTest.php

This pull request closes statamic/ideas#873. It makes it so the defined width is returned in the GraphQL response when grabbing a form fields's config.

Return width from field when returned by GraphQL

---

src/StarterKits/Installer.php
tests/StarterKits/InstallTest.php

Let's say you have a starter kit like Peak that installs a new command like `statamic:peak:install-block` for the user, but you also want to run that command as a post-install hook...
```php
<?php
class StarterKitPostInstall
{
public function handle($console)
{
if ($console->confirm('Do you want to install premade blocks into your page builder?', false)) {
$console->call('statamic:peak:install-block');
}
}
}
```
Currently you'll get the following error...
This is because of the console kernel life-cycle:
1. User runs `starter-kit:install` in their terminal
2. Laravel registers all console commands
3. Laravel finds registered `starter-kit:install` command and runs its `handle()` method
4. Starter kit copies files (including new commands like `statamic:peak:install-block` in the above …

Register newly installed commands for use in `StarterKitPostInstall` hook

---

src/Console/Commands/StarterKitInstall.php
src/Console/Commands/StarterKitRunPostInstall.php
src/Console/Processes/TtyDetector.php
src/Providers/ConsoleServiceProvider.php
src/StarterKits/Installer.php
tests/Fakes/Composer/FakeComposer.php
tests/StarterKits/InstallTest.php
tests/StarterKits/RunPostInstallTest.php
tests/StarterKits/__fixtures__/cool-runnings-post-install-hook/StarterKitPostInstall.php

When working on https://github.com/statamic/cli/pull/56 for https://github.com/statamic/cms/pull/6792, we realized that asking the user for input doesn't work within a sub-process in Windows environments. This is due to the lack of TTY support in Windows, and thus is not supported by symfony/process in Windows environments.
To be clear, this only affects:
- Starter kits which contain post-install hooks
- Where those post-install hooks ask the end user for input
- Where the end user is running Windows
The solution we came up with is to cache friendly post-install instructions for statamic/cli to show at the end of the install process...
By having the user manually run the post-install hook, it can be run as a regular process, rather than as a sub-process (via symfony/process), which allows …

Handle starter-kit post-install for statamic/cli users in Windows

---

src/Fieldtypes/Bard.php

Fix Bard's "Save as HTML" setting label.

---

resources/js/components/terms/PublishForm.vue
resources/views/terms/edit.blade.php
src/Http/Controllers/CP/Taxonomies/TermsController.php

Entry publish forms have an Edit Blueprint option, but term publish forms don't.
This PR adds that.

Add Edit Blueprint option to term publish form

---

resources/lang/en/fieldtypes.php
src/Fieldtypes/Revealer.php

The revealer fieldtype supports an `input_label` option that allows you to customise the text in the button or beside the toggle, but there is no config field for it in the blueprint editor.
This PR adds that.

Add `input_label` field to revealer config

---

src/Fieldtypes/Date.php

When a format is specified for a Date field and the field is present on the list, it always throw a DateTime::__construct(): Failed to parse time string exception. Example I have created a date field with the format: "y-m" and when I add that field to the list then this is the thrown exception:
```
Could not parse '20-10': DateTime::__construct(): Failed to parse time string (20-10) at position 0 (2): Unexpected character {"userId":2,"exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Could not parse '20-10': DateTime::__construct(): Failed to parse time string (20-10) at position 0 (2): Unexpected character at /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:190) [stacktrace]
#0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(216): …
```

Update Date.php preProcessIndex to use format from config

---

src/StaticCaching/Cachers/FileCacher.php

While reviewing #6828 I noticed that there was a JS error complaining about an invalid query selector.
Doing `[attr=value]` is fine if `value` starts with a letter. But if it starts with a number, it'll fail.
e.g. `input[value=1bd3]` will throw an error.
The error only happens sometimes, which would be the luck of the draw depending on whether your CSRF token starts with a number.

Wrap nocache query selector values with quotes

---

src/Assets/Asset.php
src/Assets/PendingMeta.php
tests/Assets/AssetTest.php

Fixes #6846 
Reverts the hotfix added in #6835

Avoid loading asset meta data until necessary

---

src/StaticCaching/Cachers/AbstractCacher.php
src/StaticCaching/Cachers/ApplicationCacher.php
src/StaticCaching/Cachers/FileCacher.php
tests/StaticCaching/ApplicationCacherTest.php
tests/StaticCaching/FileCacherTest.php

Invalidate statically cached urls with query strings

---

src/StaticCaching/Middleware/Cache.php

Fixes #6725 and fixes #6543. 
If the response is not cached (because it is a 404 or a draft viewed in Live Preview) the placeholders are now still replaced with the actual content, to get valid output.

Fix nocache placeholder appearing in responses

---

src/Assets/AssetReferenceUpdater.php
tests/Listeners/UpdateAssetReferencesTest.php

Fix issue where AssetReferenceUpdater would fail if $bardPayload was `NULL`

---

src/API/Middleware/Cache.php
tests/API/CacherTest.php

Currently live previews don't show updated content if your preview target is using the Rest API and you have caching enabled. I've updated the REST API Cache middleware to work exactly like the GraphQL Cache middleware, which is to early exit when the statamic token is present on the request.

Update REST API Cache middleware to not cache requests with a live preview token

---

src/Http/Controllers/CP/Users/UsersController.php

Fixes #5913
If you have a search index named `users`, the control panel user listing will use that for searching. Otherwise, it'll fall back to doing a simple `where` on email and name like it currently does.

Use a users search index if it exists

---

src/Fieldtypes/Users.php

Fixes #6883 by ordering user fields by `name`

Order user fields by name

---

resources/js/components/inputs/Textarea.vue

This PR does remove autosize for textarea elements for example when opening and closing the live preview
When opening and closing the live preview, there are always problems with memory growth (depending on the size of the replicator fields etc).
This PR is only a small part of it, but does help to reduce the growth at least a little bit.

Destroy autosize for textarea elements on close

---

resources/js/components/inputs/relationship/RelationshipInput.vue

This PR does add a check if the inputs are sortable at all and remove the sortable element for example when opening and closing the live preview. I think we don't need to make the element sortable if the condition 'canReorder' doesn't apply, right?
When opening and closing the live preview, there are always problems with memory growth (depending on the size of the replicator fields etc). 
This PR is only a small part of it, but does help to reduce the growth at least a little bit.

Relationship-Input: Check if inputs are sortable and destroy on close

---

src/Taxonomies/Term.php

It's currently possible to [bind a custom](https://statamic.dev/extending/repositories#custom-data-classes) `Term` class, but a lot of the action is in the `LocalizedTerm` class. While you can bind a custom `Term` and then override the `in()` method, it would be simpler to just bind a custom `LocalizedTerm` class.
This PR adds that.

Support binding a custom `LocalizedTerm` class

---

src/Routing/Routable.php
tests/Data/Entries/EntryTest.php

Fixes #5757
The issue is that when the slug is generated, it calls a function, which generates the title, which needs the augmented data, which includes the slug, which calls that function, ... and there's the infinite loop.
By nulling out the closure, when the slug is retrieved anywhere _within_ that loop, it'll be null and won't get the recursion.
Then set the slug to the end result, so it can actually be used.
I threw this in here and it worked.
I'd like to add some tests and try some other things because this seemed suspiciously simple. There's probably more to it.

Prevent recursion when generating slug from autogenerated title

---

src/Auth/Protect/Protectors/Password/PasswordProtector.php

This pull request fixes #4968 by disabling password protection when in Live Preview. 
I opted for checking if the request has a `statamicToken` rather than checking if `live_preview` exists in the entry's supplement data.

Disable password protection when in live preview

---

src/Routing/Routable.php
tests/Data/Entries/EntryTest.php

Introduced by #6903.
[This "this isnt necessary" commit](https://github.com/statamic/cms/pull/6903/commits/e0476435c242f4055e1cec9340e70615ce70206e) was absolutely necessary.

Fix id being used for slug when creating entries

---

src/StaticCaching/Cachers/ApplicationCacher.php
src/StaticCaching/Cachers/FileCacher.php
tests/StaticCaching/ApplicationCacherTest.php
tests/StaticCaching/FileCacherTest.php

The fix introduced by #6866 would do a simple "starts with" check.
If you invalidate `/foo` it was invalidating any urls that start with `/foo`.
Invalidating `/foo` would invalidate `/foo`, `/foobar`, `/foo/bar`, `/foo?bar=baz`
It should have only invalidated the url itself (`/foo`) and any query string versions (`/foo?bar=baz`).
Also, if you invalidated the home page, it would essentially invalidate your whole site.
Invalidating `/` would invalidate everything, since all URLs start with `/`.
This PR makes the check stricter to only invalidate itself and any query string versions.

Fix overly aggressive static cache invalidation

---

src/StaticCaching/NoCache/Region.php

Fixes https://github.com/statamic/cms/issues/6923
The changes in Laravel 9.36 introduced a bunch of extra variables in the view context, some of which are Closures or objects that contain Closures (resolve, resolveComponentsUsing, forgetComponentsResolver, forgetFactory, flushCache). 
Additionally, if you render a component before calling `@nocache` a constructor variable is left behind that is a ReflectionMethod that also cant be serialized. This mostly becomes a problem with the change in https://github.com/statamic/cms/pull/6934, but I don't think that's really the fault of that change (it could also occur without that).
This PR adds those keys to the exclusion list.

Fix @nocache serialization errors

---

src/View/Antlers/Language/Parser/LanguageParser.php
tests/Antlers/Runtime/ArraysTest.php

This PR improves the array shorthand syntax and resolves an "Unexpected end of logic group" error that could appear if there was no whitespace before the final "]. "
The following templates will now "just work" without obnoxious space requirements 🙂🎉
```antlers
{{ keyword1 = 'dance' }}
{{ keyword2 = 'party' }}
{{ keywords = [$keyword1, $keyword2] }}
{{
things = ['one', 'two']
more_things = ['hello']
}}
```

Runtime: Improves array shorthand syntax

---

src/Contracts/Globals/GlobalSet.php
src/Globals/GlobalSet.php

Given following:
```php
Statamic\Facades\GlobalSet::findByHandle('global_set')?->inCurrentSite()?->get('field') ?? '';
```
PHPStan static analysis fails
This is because `Statamic\Facades\GlobalSet::findByHandle()` method has a return type of `Statamic\Contracts\Globals\GlobalSet | null`. The problem is `Statamic\Contracts\Globals\GlobalSet` is empty, hence PHPStan failure.
This PR adds the following to `Statamic\Contracts\Globals\GlobalSet` to mitigate this
```php
public function in($locale);
public function inSelectedSite();
public function inCurrentSite();
public function inDefaultSite();
```

Add GlobalSet Contract

---

.github/workflows/tests.yml
src/Http/Middleware/Localize.php
tests/Feature/GraphQL/AssetTest.php
tests/Feature/GraphQL/EntryTest.php
tests/Feature/GraphQL/Fieldtypes/DateFieldtypeTest.php
tests/Forms/SubmissionTest.php
tests/FrontendTest.php

In our `Localize` middleware that's used on frontend request, we set the PHP locale, Laravel app locale, and Carbon string format based on the configured site being requested.
When setting the Carbon format, it's a static property, so it will be persisted across tests. This was manifesting itself in #6894.
This PR resets the Carbon format (as well as the locales while we're at it) once the request finishes.
This PR also adjusts some tests that were affected by Carbon string formats and locales unintentionally set in other tests.
This PR installs the French locale in the GitHub test workflow. Setting a locale requires a real locale that exists on the server, so this ensures it'll be there. There's also some ugly code in the test to set the differing name across environments. You install …

Reset locale and carbon format in localize middleware

---

src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php

With PHP8.2 `utf8_encode` function will be deprecated ([source](https://www.php.net/manual/en/function.utf8-encode.php)). I refactored:
```php
utf8_encode($text)
```
to:
```php
mb_convert_encoding($text, 'UTF-8', mb_list_encodings())
```
to avoid problems with newer PHP versions.

Remove utf8_encode() function

---

resources/js/components/entries/PublishForm.vue
resources/js/components/terms/PublishForm.vue
resources/lang/en/messages.php

As discussed, this PR shows a confirmation modal before creating a localization for an entry. The origin for the new localization will default to the first site, however in the modal you can choose a different origin if you like. 
Feel free to update UI and text of course.

Show modal with origin selector before creating localization

---

src/View/Antlers/Language/Lexer/AntlersLexer.php
tests/Antlers/Runtime/ArithmeticTest.php

This PR resolves a papercut I discovered while working on something.
Attempting to do something like this will currently lead to an unexpected stack condition:
```antlers
{{ something = (array_variable | count) - 2; }}
```
There are currently ways of doing this using interpolated syntax, but the parenthesis version definitely feels more straight-forward/natural when using modifiers.
I suspect this was caused when adding support for hyphens in variable names, but haven't dug that deep to confirm since both will work with this PR 🙂

Antlers: Corrects subtracting from parenthesis

---

src/Modifiers/CoreModifiers.php
tests/Modifiers/RelativeTest.php

Carbon's `diffForHumans` expects the modifier argument to be an actual bool/int, not just a truthy value like the string `"true"`. Because of this passing true using the legacy syntax doesn't work as expected.
```antlers
{{ date | relative }}
{{ date | relative:true }}
{{ date | relative(true) }}
```
```html
Before:
14 minutes ago
14 minutes ago
14 minutes
After:
14 minutes ago
14 minutes
14 minutes
```
Something else that slightly confuses this is that `remove_modifiers` should be `true` to remove the extra words, as per [the comment](https://github.com/statamic/cms/blob/5082efc80f2bf22416c79649542ee501be7a9e34/src/Modifiers/CoreModifiers.php#L1942). However the docs actually say that you should use `false`. Doing a docs PR to correct that.

Fix relative modifier's `remove_modifiers` param

---

src/Modifiers/CoreModifiers.php
src/Support/Arr.php
tests/Modifiers/FirstTest.php
tests/Modifiers/LastTest.php

First modifier assumes the first index is 0, which returns nothing for associative arrays or arrays where the first index is not 0.

Get the actual first item of an array with the first modifier

---

src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php
tests/Antlers/Runtime/RecursiveNodesTest.php

This PR fixes #6967 by exiting the parent search early when it hits the closest `nav` tag.
Doing this will now work as expected:
```antlers
{{ nav handle="main" }}
{{ if depth == 1 }}
<div class="{{ if is_current || is_parent }}active{{ /if }}">
<a href="{{ url }}">First: {{ title }}</a>
{{ if children }}
<ul>
{{ *recursive children* }}
</ul>
{{ /if }}
</div>
{{ /if }}
{{ if depth == 2 }}
<li><a class="{{ if is_current }}active{{ /if }}" href="{{ url }}">First: {{ title }}</a></li>
{{ /if }}
{{ /nav }}
<hr />
{{ if true }}
{{ nav handle="main" }}
{{ if depth == 1 }}
<div>
<a href="{{ url }}">Second: {{ title }}</a>
{{ if children }}
<ul>
{{ *recursive children* }}
</ul>
{{ /if }}
</div>
{{ /if }}
{{ if depth == 2 }}
<li><a class="{{ if is_current }}active{{ /if }}" href="{{ url …
```

Runtime: Improves recursive parent search

---

src/StaticCaching/NoCache/BladeDirective.php
src/StaticCaching/ServiceProvider.php

Closes https://github.com/statamic/ideas/issues/862
The docs say "use the nocache directive just like you would use the include directive", but it doesn't quite work in the same way as `@include` currently. This PR makes two small changes to bring it in line:
Laravel's `@include` directive allows you to pass in an array of additional parameters as a second argument. This kind of half works at the moment (see the linked issue) but this adds proper support.
```blade
@nocache('mypartial', ['type' => 'list'])
```
At the moment variables defined in the view that calls `@nocache` are not included in the context, only ones that already exist in `$__data`. This has been changed to grab all variables using `get_defined_vars()`,  which is [exactly what Laravel …

Blade @nocache directive improvements

---

src/Console/Commands/AssetsMeta.php
tests/Console/Commands/AssetsMetaTest.php

Fixes #4595
The fix in the issue description works fine. It also affects `focus` being saved as it goes under `data` property too.
I thought that `generateMeta` method in `Asset` class already accounts for existing asset data and merges it together here:
https://github.com/ncla/cms/blob/3ed1e592b309f34379db07fb95af406b97fe87f8/src/Assets/Asset.php#L235-L253
But with line `$meta = ['data' => $this->data->all()];`, as far as I understood it is for use cases where you are creating `Asset` object manually? So as that is not the case here, we have to simply hydrate the asset, as `AssetRepository::save()` does not account for such situation.
It is an additional call to file system for generating meta. No matter how I look at it, the command will have to look up the meta file, unless we can pull …

Preserve asset data from fields when running statamic:assets:meta generation command

---

src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Runtime/NamedSlotsTest.php

This RP fixes #6986  by preventing the `local.DEBUG: Cannot loop over non-loopable variable:` logs from being created when using named slots.
Additionally, this PR will prevent these logs from occurring on the following things that are internally treated like tags by the `NodeProcessor`:
* slot
* push
* prepend
* stack
* once
The changes only prevent the logging from happening, and there are no changes to the actual execution/render behavior.

Antlers: prevent logging named slots with non-loopable debug warning

---

src/Http/Controllers/CP/Collections/CollectionsController.php

Continuation from #6983
The form worked fine except when you first open it, it would always default to the first option.
It wouldn't use the value from the collection. Now it does.

Fix collection form not populating the origin behavior value

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
src/Fieldtypes/Bard.php
src/Fieldtypes/Grid.php
src/Fieldtypes/Replicator.php
src/Fieldtypes/RowId.php
tests/Fieldtypes/BardTest.php
tests/Fieldtypes/GridTest.php
tests/Fieldtypes/ReplicatorTest.php

Fixes #6993
The reported issue was about Replicator, but it also happened in Bard and Grid.
Previously, we would use ids to keep track of reordering etc just in JS, and throw the IDs away when you save just so you wouldn't get them in your data.
Now that we update the form with fresh values since #6842, the fieldtype preprocessing would assign new IDs, the JS would get confused, and the newly added items would mismatch, cause a JS error, and not display.
There would be no data loss, it would just look like it.
This PR will keep the IDs in the data/yaml. It's the simplest solution we could find, and there's no harm to having `id` keys in there.
Todo:

Fix Replicator/Grid/Bard not displaying newly added items after saving

---

src/Entries/AugmentedEntry.php
src/Taxonomies/AugmentedTerm.php

Fixes #6332
This makes `parent` use shallow augmentation, just like you'd expect from any other "entries" fieldtypes. This prevents the recursive situation, since the parent would be shallow, and now missing the field that would trigger the recursion in the first place.
I also applied this treatment to `updated_by` which should have been shallow augmenting, like you'd get with regular "users" fields.
I'm not super happy with the "if in api" checks here, but it's not the end of the world.
For context, I avoided shallow augmenting _always_ because when using in Antlers etc, we want the whole object, not a shallow array.

Fix parent and updated_by fields not being shallow augmented in API, sometimes causing recursion.

---

src/Http/Controllers/CP/Collections/EntriesController.php

The "isRoot" should have been called on the corresponding page. Calling it on the entry determines if is the root localization. We needed to check if it's the root page in the tree.
Fixes #7026

Fix root page validation error logic

---

src/Http/Middleware/AddViewPaths.php
tests/Http/Middleware/AddViewPathsTest.php

Fixes statamic/ssg#116
Related statamic/ssg#119
This PR will reset the view paths and namespace hints after the request completes. This prevents them from leaking into other requests, for example in tests or in the SSG.
The tests are tweaked so that the assertion happens in the closure (simulating within the context of a request).
The middleware is also refactored so that the `handle` method is more readable.

Reset view paths after request

---

src/Auth/Eloquent/User.php

When using the Eloquent User Provider if you already have a casted last_login column (which is common) it will throw an error since it passes a Carbon object to createFromFormat(). Fix is to check if it's a Carbon object first and return it otherwise send it through createFromFormat().
Couldn't think of a useful test for this but if anyone has something in mind I'd love to include it.

Allow for last_login to be casted as Carbon object.

---

src/Modifiers/CoreModifiers.php
tests/Modifiers/ReverseTest.php

Needed to reverse the order of an assets field but the field returns a QueryBuilder value which isn't supported by the modifier. This PR adds support.

Support Query Builder values in reverse modifier

---

src/Http/Middleware/AddViewPaths.php
tests/Http/Middleware/AddViewPathsTest.php

Fixes test failures that started appearing in SEO Pro.
In #7030, the paths were looping over and doing `replaceNamespace` on a single path. This was stomping over existing paths if a namespace had multiple paths.
This PR passes an array to `replaceNamespace`, and adjusts the tests to handle the multiple path scenario.

Fix namespaced view paths not being reset correctly

---

src/Entries/Entry.php
tests/Routing/UrlBuilderTest.php

This PR adds support for custom date formats in route definitions for a dated collection, based on discussion in https://github.com/statamic/cms/discussions/6248.
When defining a route pattern on a dated collection, Statamic already supports `year`, `month`, and `day` variables for generating date-based routes like `/blog/2015/01/02/post`. However, other date formats are not currently possible, like unix timestamps, month names, single-digit months or days, etc.
This adds an additional `date` property to the entry route data array with the full entry date Carbon instance to enable any other date format you can specify in Antlers using the `format` modifier. (e.g. `/blog/{{ date format="U" }}`)

Support custom date formats in route definitions

---

src/Actions/RenameAssetFolder.php
src/Assets/Asset.php
src/Assets/AssetFolder.php
src/Http/Controllers/CP/Assets/FoldersController.php
tests/Assets/AssetFolderTest.php

A user recently pointed out that `'lowercase' => false` in `config/statamic/assets.php` only applied to asset filenames, not asset folder names. Folder names were always lowercased, but this should now match the user's configuration, as introduced in https://github.com/statamic/cms/pull/6031.

Fix lowercasing of asset folder names to match user's configuration

---

config/users.php
resources/js/components/users/Wizard.vue
resources/views/users/create.blade.php
src/Http/Controllers/CP/Users/UsersController.php

This PR makes a few improvements to the user creation wizard.
1. You can disable the option to send an email invitation.
```php
// config/statamic/users.php
'wizard_invitation' => false,
```
This will completely hide the last step where it asks if you want to send an email.
2. If you don't have permission to assign roles and groups (as per #6614) then that step will be hidden.
3. If you don't have group/role permissions, and you've disabled the invite, then you'd be left with a single step. In this case, the step navigation is hidden altogether.

Update User Wizard

---

src/Console/Commands/AssetsGeneratePresets.php

Allow the generate-presets command to continue upon error as described in issue https://github.com/statamic/cms/issues/6965
Closes #6965

Generate-Presets - catch exception on bad images so command can finish

---

config/assets.php
src/Listeners/GeneratePresetImageManipulations.php

We use asset generation presets a lot, however when you specify them all manipulations are generated for every assets on upload, even though we only require specific presets for certain outputs of images. So you end up with a filesystem full of generations that are never required.
It would be useful to be able to specify which presets are automatically generated (even on a collection/blueprint basis), but as a stop gap I've added a config that lets you opt out of generating them at all.
If there is a better way or approach let me know and I'll update the PR.

Add config option to control generating asset preset manipulations on upload

---

src/Entries/Entry.php

Only add the date to new localizations if the collection is dated. Fixes #7085, Fixes #2296.

Prevent adding date to non-dated collections

---

src/StaticCaching/Middleware/Cache.php

This fix will allow Inertia links to work without throwing a fatal error, as Inertia returns a JsonResponse.
There might be another way to control all this, since Inertia will send the header `x-inertia: true` which should affect the cached response so there's one for the normal rendered response and one for the json response.

Don't do replacements when not returning a simple response

---

resources/js/components/Permission.js
resources/js/components/fieldtypes/assets/Asset.js

In `Statamic.$permissions.has(permission)` it should check for super permissions rather than needing to also manually do `.has('super')`.
References #7100

Move JS super permission check

---

src/Providers/AddonServiceProvider.php

Now that fieldsets can be referenced (like views), we might need to override the namespace (like we can w/ views).
IMO, we should only have one `$namespace` property, but I didn't want to break the existing `$viewNamespace` property.
If you'd me to add code to do so, let me know.

Allow addons to set the fieldset namespace

---

src/Http/Controllers/CP/Users/UsersController.php

This pull request fixes an issue on the Users Listing Table when storing users in the database & using separate columns for first & last name.
1. Setup a Statamic site with users in the database (now that I think of it users could probably be flat-file for this issue too)
2. Make first & last names into separate columns, instead of one field as per the default
3. On the Users Listing Table, attempt to search for a user
4. See the error
Apologies for lack of test repository, I don't have any time to do that right now.
```"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'where clause' (SQL: select count(*) as aggregate from `users` where `email` like %dev% or `name` like %dev%)"```

Fix search on Users Listing Table when storing users in the database & using separate first/last name fields

---

resources/js/components/updater/Release.vue
resources/js/components/updater/Updater.vue
src/Updater/Changelog.php
src/Updater/Presenters/GithubReleasePresenter.php
tests/Composer/ChangelogTests.php

I've been noticing for a while that the updater page takes a long time to load. The same goes for the updater badge. Also the updater page doesn't show a loading indicator. This PR fixes / improves these issues.
Most of the loading time (several seconds each) was spent parsing the markdown in `GithubReleasePresenter@toHtml()` and determining if a version was a 'upgrade', 'current' or 'downgrade' version in `Changelog@parseReleaseType()`.
Changes:
* Parse markdown on the frontend
* Remember the release type, everything after the first 'downgrade' must be a downgrade too*
* Start loading the changelog in the Vue `created()` method instead of waiting for `mounted()`
* Fix a JS error that prevented the loading indicator from rendering
\* This assumes that the API returns the releases sorted, …

Improve loading speed for updater page

---

src/Console/Commands/StaticWarm.php

**Problem:**
Staging systems are often behind a HTTP basic authentication. Calling the current static warm command on a site behind HTTP basic authentication (e.g. from a CI job) produces a "401 Authorization Required" error.
**Solution:**
This pull request adds the possibility to pass the authentication credentials via the parameters `--u` (HTTP authentication user) and `--p` (HTTP authentication password) to the static warm command.

Add http auth to static warm

---

src/Fieldtypes/Link.php
src/Routing/ResolveRedirect.php
tests/Feature/GraphQL/Fieldtypes/LinkFieldtypeTest.php
tests/Fieldtypes/LinkTest.php
tests/Routing/ResolveRedirectTest.php

Fixes #3764 as suggested by @kesse. 
I added fallback to the original entry, in case the localization does not exist.

Use parent localization when resolving link

---

resources/js/components/entries/PublishForm.vue

Fixes #7141
Use a nullsafe operator since the error is because the `this.localizations.find()` returns null in both cases.
The `this.selectedOrigin` property is only used on the edit form, so we don't care if it's null on the create form.

Prevent error when creating entry while using multisite

---

src/Providers/AddonServiceProvider.php

When developing addon I discovered that the method "schedule" in AddonServiceProvider doesn't have type casting.
This matter was discussed in this thread:
Closes https://github.com/statamic/ideas/issues/912

Add Type Declaration to schedule method in AddonServiceProvider

---

src/Http/Controllers/CP/Collections/EntriesController.php

Fixes #7066.
Solved by getting the tree for an orderable collection too.
This is an alternative to #7133.

Fix invalid slug validation when using max_depth: 1

---

src/Fields/FieldTransformer.php

The localisation variable is always reset as true when updating blueprints. If you have a field that is not localizable and update the blueprint for any reason, the field is sent in the PATCH request with `localizable: false` which is then unset by this code. This means if the field has been localizable before then it can't be changed to non-localizable... this causes an issue as slugs are default localizable even when multisite is not enabled.
This code checks if multisite is enabled, and prevents the field from being unset. This fixes #7082, fixes #4471 and continues to allow the localizable field to be unset on single sites so their blueprints remain unchanged. On multi-sites, each blueprint will be updated the next time they are saved, and will explicitly say if fields are localizable …

Allows localization variable to be saved as false.

---

src/Tags/Partial.php
tests/Tags/PartialTagsTest.php

A DX improvement  so this:
```
{{ if subtitle }}
{{ partial:components/subtitle }}
{{ subtitle }}
{{ /partial:components/subtitle }}
{{ /if }}
```
```
{{ partial:components/subtitle :when="subtitle" }}
{{ subtitle }}
{{ /partial:components/subtitle }}
```
Also supports the converse `unless`

Add `when` and `unless` to `partial` tag

---

resources/js/components/fieldtypes/VideoFieldtype.vue

This pull request allows for YouTube Shorts to be previewed within the Video fieldtype, in the same way you can with a 'normal' YouTube video.
I had to make a change to the regex expression to allow for Shorts URLs to be previewed (credit to @JohnathonKoster for figuring out why the regex wasn't working in the first place 😅 )

Show YouTube Shorts in video fieldtype preview

---

src/View/Antlers/Language/Runtime/LiteralReplacementManager.php

This is to prevent deprecation messages on str_replace if the default value is "null" instead of an empty string

Set default value to empty string if null

---

src/Notifications/ActivateAccount.php

This PR enables to overwrite the greeting of the activation mail of the user.
Currently, you can invite the user via the control panel (cp/users/create). But I need to invite 30 users to my application and I want to personalize the invitation mail:

Overwrite greeting in activation mail

---

resources/views/extend/forms/fields/checkboxes.antlers.html
resources/views/extend/forms/fields/default.antlers.html
resources/views/extend/forms/fields/radio.antlers.html
resources/views/extend/forms/fields/select.antlers.html
resources/views/extend/forms/fields/text.antlers.html
resources/views/extend/forms/fields/textarea.antlers.html
resources/views/extend/forms/fields/toggle.antlers.html
src/Tags/Concerns/RendersForms.php
tests/Tags/Concerns/RendersFormsTest.php

This PR is related to #6400.
Up until now, front-end fields were only used for the "forms" feature where you only ever create items, not edit them. i.e. you only create submissions.
The fields that get rendered would only need to handle default values and old values.
Now with #6400, you'll need to render the fields but also be able to insert existing values.
This PR adds support for existing values.
- `value` is the smarter variable that'll account for the value itself, the previously submitted/old value, or default values.
- The `old`/`default` variables are no longer passed to the views, but stay there for backwards compatibility.
- A bunch of tests are added to make sure appropriate checkboxes are checked, options selected, fields filled, etc.

Handle edits within frontend fields

---

resources/views/extend/forms/fields/checkboxes.antlers.html
tests/Tags/Concerns/RendersFormsTest.php

Continuation of #7178
Previously, if you uncheck all the boxes in a `checkboxes` field on the frontend, it would act like the field wasn't submitted at all, so the previous value would be used.
This PR adds a hidden field with an empty value. So if you uncheck all the options, an empty value still gets submitted, so the value will be updated to nothing, as expected.
Added a test to ensure that the hidden field is in the html.
Add equivalent test for toggle field while we're at it, which relies on the same behavior.
Again, this only matters for #6400 since at the moment front-end fields are only used for forms, which are create-only at the moment.

Fix handling for empty checkboxes fieldtype on front-end

---

composer.json

Other packages are starting to require v6 of symfony components (including laravel). Ran into an issue when installing into an existing application.
[No major BC breaks listed](https://github.com/symfony/var-exporter/blob/6.2/CHANGELOG.md) so with unit tests passing this should be safe to upgrade.

allow version ^6.0 of symfony/var-exporter

---

src/CP/Utilities/UtilityRepository.php
src/Http/Controllers/CP/Utilities/UpdateSearchController.php

Fixes #7209
Currently authorization only removed the items from the navs. This PR adds it to the routes themselves to make them inaccessible.
Aside: I also noticed that the search page no longer uses the controller method so I removed that.

Fix utility route authorization

---

src/Providers/CacheServiceProvider.php

Laravel has a `$filePermission` parameter on `Illuminate\Cache\FileStore` [see here](https://github.com/laravel/framework/blob/1c10e4ff6dfca0761a6822eae2146a02edffde89/src/Illuminate/Cache/FileStore.php#L46), which allows allows a developer to control the filesystem permissions assigned to files created by Laravel within the cache.
Helpfully, this parameter can be set in `config/cache.php` and is used with configuring the cache [see here](https://github.com/laravel/framework/blob/1c10e4ff6dfca0761a6822eae2146a02edffde89/src/Illuminate/Cache/CacheManager.php#L158).
Statamic extends/overrides this driver but fails to honour the permission specified in config (and does this using a private method in the service provider, making it impossible to fix locally by extending the provider). 
This …

Ensure CacheServiceProvider honours 'permission'

---

src/Console/Commands/SupportDetails.php
src/Providers/AppServiceProvider.php

Adds additional details about whether the Stache Watcher is enabled and which Static Caching strategy is bein used to the output of the `php please support:details` command. Works with the new `artisan about` command (Laravel 9+) and prior versions.
Before:
```
Statamic
Addons: 0
Antlers: regex
Version: 3.3.x-dev PRO
```
After:
```
Statamic
Addons: 0
Antlers: regex
Stache Watcher: Disabled
Static Caching: None
Version: 3.3.x-dev PRO
```

Improve support:details command with information about Stache and Static Caching

---

.github/workflows/pull-requests.yml

We often like to make small (or sometimes not so small) modifications to PRs without needing to ask the submitter to make it themselves. It's easier that way.
If a PR is opened from an account where we don't have maintainer permissions, we can't make those edits, and it's very frustrating. Typically it's when the fork is on an organization account.
This PR adds a GitHub action workflow that will close the PR and leave a comment asking the user to resubmit it from an account with appropriate permissions enabled.
It's basically a copy of what Laravel does. See laravel/framework#41839

GitHub workflow for when PRs arent editable

---

resources/js/components/fieldtypes/ColorFieldtype.vue

The color picker closes when you hit Clear but not when you hit Save, which is kind of odd and means you then have to click again (outside the picker) or hit Escape to close it.
The PR hides the picker when you hit Save.

Close color picker on save

---

src/Search/Searchables.php
tests/Search/SearchablesTest.php

If you specify a search transformer as a closure... eg:
```
'transformers' => [
'title' => function ($value) {
return strtoupper($value);
},
],
```
and run `php artisan config:cache` then you are given a serialisation error.
@jacksleight has a great workaround here: https://github.com/statamic/ideas/issues/721#issuecomment-1334039830 but its not the immediate thing you reach for.
This PR allows you to specify a class to handle the transform, allowing serialisation to work, e.g.
```
'transformers' => [
'title' => \App\Transformers\MyTransformer::class,
],
```
Within the class we look for a `handle()` method and pass the `$field` and current `$value` to it. The developer can then return whatever they want to be added to the index.

Allow searchables transformers to be a class to prevent serialisation error

---

config/git.php
src/Events/Concerns/ListensForContentEvents.php
src/Events/DefaultPreferencesSaved.php
src/Git/Git.php
src/Preferences/DefaultPreferences.php
src/Providers/ExtensionServiceProvider.php
src/UpdateScripts/AddDefaultPreferencesToGitConfig.php
tests/Git/GitEventTest.php

When we added default preferences in https://github.com/statamic/cms/pull/6642, I never thought to track changes to the `resources/preferences.yaml` file as a git path for our git integration feature. This PR adds/fixes this for new apps.

Fix default preferences not being tracked with git integration

---

resources/js/components/assets/Browser/Thumbnail.vue
resources/js/components/fieldtypes/assets/AssetRow.vue
resources/sass/core/utilities.scss
src/Fieldtypes/Assets/Assets.php

Fixes https://github.com/statamic/cms/issues/7192
Fixes https://github.com/statamic/cms/issues/7024
This PR fixes a couple of issues with asset thumbnails/file-icons.
The size has been changed from `thumbnail` to `small`, as `thumbnail` seems to return the full-size image.
I've found various mentions of Safari bugs around flexbox and children with percentage based max-height values, and that certainly seems to be what's causing this. Since both of the places where `<asset-thumbnail>` is used set `h-8` on the parent, changing the `max-h-full` to `max-h-8` doesn't affect the layout but does avoid the Safari bug(s).
I also removed the duplicate `rounded` class.
Icons were set to `w-full`, but that's `3xs` in an entry listing, leaving empty space either side:
Giving them `w-8` instead fixes …

Fix asset thumbnails/file-icons in entry listings and assets field

---

src/Fieldtypes/Collections.php
src/Fieldtypes/Taxonomies.php

This pull request closes #6908 by ordering the list of collections/taxonomies alphabetically by name.

Order results by name (Collection & Taxonomy fieldtypes)

---

config/static_caching.php
src/Console/Commands/StaticWarm.php

Having a big site with lots of entries, in my case 1000+, the cache warming using queue would fill the "default" queue making other more important jobs be really delayed. Adding this change would allow us to put the StaticWarm job on a separate queue and allows us to process the queue on a separate queue worker.
By changing `config/statamic/stache.php` and setting the key `warm_queue_name` to something else, jobs added to the warm queue with use this queue instead.
This will also fallback on default (current) behaviour so it should not be breaking anything.

Ability to use separate queue for Static Cache warm

---

resources/js/components/structures/PageTree.vue

Lots of people have requested a setting to turn this off, and it seems like such a trivial, niche thing to make a setting for. Let's just get rid of it. I originally intended to have lots of sound effects but it never really seemed worth the effort.

Remove sound effects on Nav drag & drop interactions

---

resources/js/app.js

Simple fix for a console error when there are no inputs on a CP view (such as the Dashboard).
```
Uncaught TypeError: can't access property "focus", e[0] is undefined
fixAutofocus app.js:254
setTimeout handler*fixAutofocus app.js:243
mounted app.js:195
VueJS 7
start Statamic.js:87
<anonymous> dashboard:438
app.js:254:22
```
When the input list is empty (such as the Dashboard), the `inputs` list has nothing at index 0. This tweak just runs the focus command if the `inputs` NodeList has a length (see [#7242](https://github.com/statamic/cms/pull/7242)).

Fix focus console error when there are no inputs

---

src/Actions/DuplicateEntry.php
tests/Actions/DuplicateEntryTest.php

This pull request fixes #7166 by only setting slugs on duplicated entries if the collection has the 'Requires Slugs' toggle enabled.
Previously, it would generate filenames like `1.md` when you duplicate entries on a collection where the setting wasn't enabled. 
This was happening because of [the code that generates the title & slug](https://github.com/statamic/cms/blob/3.3/src/Actions/DuplicateEntry.php#L80) for the duplicated entry... in normal cases you'd get `the-slug-1.md` but because there was no slug, it just generated the number.

Fix Duplicator not respecting collections without slugs

---

resources/js/components/users/ChangePassword.vue
resources/lang/cs/validation.php
resources/lang/da/validation.php
resources/lang/de_CH/validation.php
resources/lang/en/validation.php
resources/lang/es/validation.php
resources/lang/fr/validation.php
resources/lang/id/validation.php
resources/lang/it/validation.php
resources/lang/ms/validation.php
resources/lang/nb/validation.php
resources/lang/nl/validation.php
resources/lang/pl/validation.php
resources/lang/pt/validation.php
resources/lang/pt_BR/validation.php
resources/lang/ru/validation.php
resources/lang/sl/validation.php
resources/lang/sv/validation.php
resources/lang/zh_CN/validation.php
resources/lang/zh_TW/validation.php
src/Http/Controllers/CP/Users/PasswordController.php

This adds a "current password" field to the popover for changing your own password within the CP. This provides more security as well as avoiding confusion as to whether the password field is the current password or new password field, as described in #7277.
Replaces #7277

Require password to change password in CP

---

src/View/Antlers/Language/Parser/LanguageParser.php
tests/Antlers/Runtime/ConditionLogicTest.php

This PR makes it easier to utilize the `switch` operator by relaxing the parsing:
After this change, the following will now "just work":
```antlers
{{
switch (
(['doc', 'docx'] | in_array(filetype)) => 'word.svg',
() => 'default.svg'
)
}}
```
Currently it will produce a parsing error.

Antlers: improve switch operator parsing

---

src/Fieldtypes/Yaml.php

Like on line 53, these two ocurrences need to be uppercase.
Otherwise we were getting: 
```
Class "Statamic\Facades\Yaml" not found {"userId":"52b99608-2348-4081-998d-edea911298e9","exception":"[object] (Error(code: 0): Class \"Statamic\\Facades\\Yaml\" not found at /home/spnefro/public_html/vendor/statamic/cms/src/Fieldtypes/
```

Use proper YAML facade casing

---

src/Actions/Action.php
src/Actions/ActionRepository.php
src/Actions/RenameAsset.php
src/Http/Controllers/CP/ActionController.php

Closes statamic/ideas#881
Required for #6040 so the `files` fieldtype can pass along the respective `container` depending on what asset you're reuploading.
This also closes statamic/ideas#337 which is a perfect use case for this feature addition.

Pass items into actions

---

src/Search/Searchables.php
tests/Search/SearchablesTest.php

Hi
Currently, indexing a Bard field which is not saved as HTML is quite hard because the value will be passed as structured array and not as rendered HTML.
Until https://github.com/statamic/cms/pull/6318 will be merged, I solved it by just passing the searchable as additional parameter into all transformer calls (closure and the new instances handle methods).
By doing this, we can index a Bard field easily by just additionally getting the augmented value if needed.
Example:
```php
class ContentTransformer
{
public function handle($value, $field, $searchable)
{
if (! $value) {
return null;
}
$augmentedValue = $searchable->augmentedValue('content');
return $this->extractTextFromHtml($augmentedValue);
}
}
```
I think this really empowers the indexing in other cases together with the new …

Pass searchable into search transformers to empower indexing

---

resources/js/components/fieldtypes/RevealerFieldtype.vue

Fixes https://github.com/statamic/cms/issues/7306
I assume this was caused by https://github.com/statamic/cms/pull/6842, as after update the revealer field is no longer `true` so the conditional fields get hidden again.
This PR fixes it by watching for a new `false` value and re-calling `buttonReveal()` if the current value is `true`. I suspect there might a better way to fix this within the publish container itself, rather than updating and the immediately reverting the value, but that's a bit beyond me.

Fix revealer fields disappearing on save

---

resources/js/components/fieldtypes/ListFieldtype.vue

This PR is a small UX enhancement that will create multiple new items when pasting multiple lines into the list fieldtype:
https://user-images.githubusercontent.com/126740/211869797-0d8dffaf-1cb0-462b-8d29-a82865fb79d8.mp4
Will only kick in when pasting into the new item, and the new item is blank, and the pasted value contains line breaks.

Create multiple list items when pasting multiple lines

---

src/CP/Navigation/NavBuilder.php
tests/CP/Navigation/NavPreferencesTest.php
tests/CP/Navigation/NavTest.php

Hide empty section headings from CP nav sidebar when section contains no items. 
For example, maybe a user drags the last item out of a section, then there's no use showing it in the final rendered nav. (But still show the section in the nav preferences UI, so that the user can re-add items back into that core / addon extended section.)

Hide empty sections in final rendering of CP nav

---

src/View/Antlers/Language/Runtime/GlobalRuntimeState.php
src/View/Antlers/Language/Runtime/NodeProcessor.php

This PR fixes #7360 by resolving a memory leak that occurs when the Runtime parser is repeatedly called within the same process.

Antlers: Corrects memory leak

---

src/View/Antlers/Language/Runtime/NodeProcessor.php

This PR fixes #7366 by resetting more data between parser invocations within the same process. This PR expands on the concept from #7361 and utilizes the garbage collection flag to ensure that previous assignments, interpolation cache, locked data, etc. is also cleared from memory.
In the linked issue, the randomized behavior will happen if the blog post page is generated first, leaving its assignment in memory before the index page is generated.

Antlers: Cleanup additional data between Runtime parser invocations

---

src/Auth/UserRepository.php
tests/Auth/UserContractTests.php
tests/Tags/User/ProfileFormTest.php

- Fixes #7359
- When doing this PR, I found that `roles` and `groups` fields were showing on the profile edit form of a fresh statamic/statamic install, even with pro disabled. These being pro features, it should be safe to remove these fields if pro is disabled.
- References https://github.com/statamic/docs/pull/986

Fix user blueprint fallback defaults

---

src/View/Antlers/Language/Runtime/GlobalRuntimeState.php
src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Runtime/ParserIsolationTest.php

This PR resolves an additional issue related to #7366  (this comment: https://github.com/statamic/cms/issues/7366#issuecomment-1399021786)
This PR subtly adjusts the garbage collection logic to enforce a clean variable state when transitioning between requests. If garbage collection is required, any held locks on the current processor instance are forcefully removed. Each time the `setData` method is called, the processor will reset its internal state and rely on the merging data behavior elsewhere.
A new test has also been included that will catch this going forward, and will fail if the changes are reverted 👍

Antlers: Resolves an issue where assignments can leak under some circumstances

---

src/Auth/SetLastLoginTimestamp.php

A different approach than #4823.
Instead of checking the user model that we are logging in, check the guard that is being used to ensure it's one of the ones defined for Statamic to use. The User::fromUser method already carries out the other checks needed, so defer to it and just check if we get a value for $user returned.
Fixes: #4030

Eloquent user login timestamps - change approach to check guard being used

---

src/Fieldtypes/Terms.php

When adding taxonomy terms to a navigation entry, solving the augmentation will result in a `null` error call as `Statamic\Structures\Page` doesn't have a collection

Ensure taxonomies parent has a proper collection when resolving augmentation

---

resources/views/nav/index.blade.php
resources/views/preferences/index.blade.php

When using Eloquent users, we don't want to call preference-related methods on the Eloquent model directly, but rather on the Statamic user instance.
Fixes #7423

Fix preferences listing errors when using Eloquent users

---

src/Fieldtypes/Bard.php
tests/Fieldtypes/BardTest.php

Fixes #7421
Rather than needing to update any content, this will adjust the `snake_case` types to `camelCase`, as per the tiptap v1/v2 upgrade guide.
If you open an entry in the cp and hit save, all the types will be updated in that entry.

Fix Bard backwards compatibility

---

resources/lang/nl.json

The translation was a bit off. 'Item uitlijnen' is the translation of 'align item' and not of 'alias item'. 
Still thanks to @oakeddev for the translations!

Updated Dutch translation

---

resources/js/components/entries/PublishForm.vue
resources/js/components/publish/HasHiddenFields.js
resources/js/components/publish/Values.js

Fixes #7441
The issue said 3.4, but it was actually introduced in 3.3.66. I'll fix it separately for 3.4 too, though.
This PR:
- Fixes the error that prevented the redirect. It had to do with merging undefined response values since we don't get those on the create form.
- The save action would swallow any errors, making it look like there wasn't a problem. It'll now log the error.
- Added a name to the Values class, purely to make stack traces easier to read. An instance of Values would show up as `_default`. Now it says `Values`.

Fix create entry form not redirecting on save

---

resources/js/components/assets/Browser/Browser.vue
resources/js/components/assets/Selector.vue
resources/js/components/fieldtypes/bard/LinkToolbar.vue

Auto-focus search input when opening selectors in Bard link or standalone link fieldtype

---

src/Fieldtypes/Bard.php
tests/Fieldtypes/BardTest.php

Run into a small issue with https://github.com/statamic/cms/pull/7433 and custom Bard extensions.
If your extension has a `type` _attribute_ it is also converted to camel case, even though only the node names need to be converted. This isn't a problem for the `type` values within set attributes as sets are skipped in the loop.
This PR fixes that by instead of just skipping sets it now skips all `attrs` arrays.

Fix custom Bard extension type attributes

---

src/Fields/Values.php
src/GraphQL/Types/GridItemType.php
src/GraphQL/Types/ReplicatorSetType.php
tests/Feature/GraphQL/Fieldtypes/BardFieldtypeTest.php
tests/Feature/GraphQL/Fieldtypes/GridFieldtypeTest.php
tests/Feature/GraphQL/Fieldtypes/ReplicatorFieldtypeTest.php

This fixes an issue where nested fields (fields inside replicator, grid, bard) get resolved too early.
e.g. If you have a markdown field, you're able to ask for it as markdown.
```graphql
description(format: "markdown") // returns markdown
```
But if you were asking for a markdown field inside a replicator set, it would have resolved to html within the set, and by the time it got to the markdown field, it wouldn't be able to give you raw markdown.
```graphql
... on Set_Replicator_MySet {
description(format: "markdown") // returns html
}
```
This fixes it by using the corresponding field's resolver, instead of doing it within the set.
Todo:

Fix GraphQL nested fields

---

src/Query/EloquentQueryBuilder.php

As noted over in https://github.com/statamic/eloquent-driver/issues/110
The call to get the schema can result in lots of duplicate queries - so let's store the result of the call. As Eloquent Query Builders are singletons this approach should be ok - if I've misunderstood that then I can update it to `Blink` them instead.

Cache result of schema call to avoid duplication

---

.github/workflows/tests.yml
composer.json

This drops support for PHP 7.4 and Laravel 8.
At the moment, Laravel 9 is the only supported version on the master (4.x) branch.
Laravel 10 support is planned for 4.0 but will be added in a separate PR.

[4.x] Drop support for PHP 7 and Laravel 8

---

src/Search/Comb/Comb.php

This addresses the attempted access of an undefined array key when a search index is empty. An Exception with the message "Empty haystack." will now be thrown rather than the more cryptic message "Undefined array key 0".

Preventing access of undefined array key

---

src/Http/Controllers/CP/Assets/BrowserController.php
src/Http/Controllers/CP/Collections/EntriesController.php
src/Http/Controllers/CP/Taxonomies/TermsController.php
src/Search/PlainResult.php
src/Search/QueryBuilder.php
src/Search/Result.php

- A couple of issues occur because a regular `Collection` is returned from the search query builder but should be a `DataCollection` like it was in 3.3. This prevented supplementing from working in the `search:results` tag. Additionally, supplementing wasn't being performed correctly in the Result classes.
Fixes #7475
- When using search indexes in collections, taxonomies, or asset containers, and performing a search in the CP, you'd run into errors due to passing Result classes to our resource, but they were expecting Entry/Term/Asset instances. We now map back to those classes appropriately.
Fixes #7474
- Added a `get` method to the Result class, which was being used by `DataCollection@multisort` method which fixes an error when using the `sort` param on the `search:results` tag.

Fix search issues

---

resources/js/components/Popover.vue

The menu was rendered offscreen. This fix makes sure the position for the menu is recalculated before showing it.
Fixes #7457
Fixes #7427

Update popover position when opening it

---

src/Providers/BardServiceProvider.php

Currently the Underline mark does not get registered in Bard.
This causes the underline setting not to output any HTML tags.
This PR adds the underline mark to the `BardServiceProvider` so the HTML tags get rendered correctly.

Fix underline in Bard not outputting any HTML tags

---

src/Stache/Indexes/Index.php
src/Stache/Stores/ContainerAssetsStore.php

This one came from a support email, though we found it's very much related to #5501, among a few other issues.
Closes #5501
References #2993
References #6592
If you upload an asset to an entry and try to get the asset value in a long-running queue worker, it'll find the asset just fine the first time, but not if you upload a new image and try to get the new asset a second time. This is mostly because the stache index is built/loaded only once per request, which breaks down in queue worker scenarios without a typical request lifecycle.
1. Create an `EntrySaved` listener that dumps rendered html to log/ray/etc...
```php
public function handle($event)
{
$this->entry = $event->entry;
$html = (new \Statamic\View\View)
->template('articles/show') …
```

Fix queue worker state issues around assets and stache indexes

---

src/Data/StoresScopedComputedFieldCallbacks.php
tests/Data/StoresScopedComputedFieldCallbacksTest.php

This PR makes a small tweak that allows adding the same computed values to multiple collections at once. So instead of:
```php
$callback = function ($entry, $value) {
//
};
Collection::computed('pages', 'extract', $callback);
Collection::computed('articles', 'extract', $callback);
```
You can just do:
```php
Collection::computed(['pages', 'articles'], 'extract', function ($entry, $value) {
//
});
```

Support adding computed values to multiple collections at once

---

src/Query/Builder.php
src/Query/EloquentQueryBuilder.php
tests/Data/Assets/AssetQueryBuilderTest.php
tests/Data/Entries/EntryQueryBuilderTest.php
tests/Data/Taxonomies/TermQueryBuilderTest.php
tests/Search/QueryBuilderTest.php

Fixes #7460. Both in `Statamic\Query\Builder` and `Statamic\Query\EloquentQueryBuilder`.

Fix `orWhereJsonLength()` method in the QueryBuilders

---

src/StaticCaching/NoCache/Controller.php
src/StaticCaching/ServiceProvider.php
tests/StaticCaching/NoCacheSessionTest.php

Use the `ignore_query_string` setting when handling `nocache` Sessions

---

src/StaticCaching/NoCache/Controller.php
src/StaticCaching/NoCache/Session.php
tests/StaticCaching/FileCacherTest.php
tests/StaticCaching/NoCacheSessionTest.php

Fixes #7465.
Static Caching gets the URI from the current request using `Illuminate\Http\Request@getUri()`. This method sorts the query parameters alphabetically under the hood, see  [Request::getUri() returns parameters in wrong order #30844](https://github.com/laravel/framework/issues/30844). So for example `/?foo=bar&bar=baz` will become `/?bar=baz&foo=bar`.
The issue happens because `Statamic\StaticCaching\NoCache\Controller` just takes the posted URL as is, without normalizing the query string. So the URL won't match the URL for the saved Session because the order of the parameters differ.
This PR normalizes the query string in the `Controller` too.

Make the `nocache` tag work well with multiple query parameters

---

src/Tags/Vite.php

The Vite::asset (https://laravel.com/docs/9.x/vite#blade-processing-static-assets) method wasn't made available yet in Statamic Antlers.
I have extended the Vite Tag with a asset attribute to have the ability to load assets now.
Example usage: 
```html
{{ vite src="resources/css/app.scss" }}
{{ vite src="resources/js/site.js" }}
```

Adding support for the Vite::asset method

---

resources/js/components/assets/Uploader.vue
resources/js/components/assets/upload.ts

We're removing jQuery in an upcoming PR. This is one of the largest parts of our codebase that still uses jQuery.
This PR replaces `dmuploader` with `upload`.
At the moment there is a local version of the `upload` package until https://github.com/mat-sz/upload/pull/7 is merged and released. I'm assuming it will be accepted because it's such a tiny change. When it's released, `upload.ts` can be deleted, `upload` can be required in `package.json`, and the import will change to point to the npm package.
Also, intentionally not removing `dm-file-uploder` from `package.json` in this PR. I'll do it in #7504. I'm sure there would be a merge conflict in package-lock.json.

[4.x] Replace dmuploader jQuery plugin in Uploader

---

resources/views/updater/index.blade.php

Links to a relative URL of `updates` which of course leads nowhere. Replacing with `Statamic::docsUrl('updating')`

Fix docs URL on Updater page

---

src/Tags/Taxonomy/Taxonomy.php

As mentioned [here](https://github.com/statamic/cms/discussions/7515) there are issues using paginate and the taxonomy tag, which is due to it calling map on a paginator instead of a collection.
Looking at the code, the map is actually no longer needed as the `querySite` function in `Tags\Taxonomy\Terms.php` already handles the site limiting.

Remove redundant code in Taxonomy tag

---

package-lock.json
package.json
resources/css/components/fieldtypes/assets.css
resources/css/components/fieldtypes/datetime.css
resources/css/components/publish.css
resources/js/bootstrap/components.js
resources/js/bootstrap/globals.js
resources/js/components/assets/Folder/Folder.vue
resources/js/components/blueprints/RegularField.vue
resources/js/components/blueprints/Section.vue
resources/js/components/fields/ImportSettings.vue
resources/js/components/fieldtypes/DateFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/fieldtypes/grid/StackedRow.vue
resources/js/components/fieldtypes/replicator/Field.vue
resources/js/components/nav/ItemEditor.vue
resources/js/components/nav/SectionEditor.vue
resources/js/components/publish/Field.vue
resources/js/components/publish/Fields.vue
resources/js/components/publish/FieldsContainer.vue
resources/js/components/roles/PublishForm.vue
resources/js/components/user-groups/PublishForm.vue
src/Support/Str.php
tailwind.config.js
tests/Support/StrTest.php

This PR adds Tailwind's new Container Queries plugin and allows us to remove a number of `ElementContainer` components that use a JavaScript resize watcher to make CSS layout adjustments. This should decrease memory usage in the CP and give us more control of fieldtype styles that can find themselves in all sorts of odd sizes and spaces.
The `<fields-container>` component is now deprecated and you may replace any instance of it with a simple `<div class="publish-fields @container">` HTML element.

[4.x] Container Queries

---

src/CP/Navigation/NavBuilder.php
tests/CP/Navigation/NavTest.php

If you remove all top level nav items (ie. `Dashboard`) using the PHP API...
```php
\Statamic\Facades\CP\Nav::extend(function ($nav) {
$nav->remove('Top Level', 'Dashboard');
});
```
It completely borks the CP Nav preferences builder GUI, and assumes that the first section should be considered top level items...
This PR fixes that...

Fix CP Nav preferences builder when top level section is empty

---

resources/js/components/fieldtypes/ArrayFieldtype.vue

The dynamic mode array fieldtype will let you add and remove items when it's set to read only.
This PR fixes that by hiding the add and remove buttons.
Before:
After:

Fix read only dynamic mode array fieldtype

---

src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Runtime/LoopTest.php

Replaces #7583
It turns out the issue in #5828 wasn't that the modifier was being called multiple times. It had more to do with the modified `value` not being used on subsequent iterations.
I wrote this test while on the commit where the original test was added, and confirmed that it broke without the original fix, and passed when adding it. That fix has since been refactored, and now still passes.
The replaced test is also simplified just so there's less to grok.
Also removed some leftover stuff that was introduced along at the same time as the test, but is no longer used.

Refactor randomness out of test

---

src/Stache/Stores/CollectionEntriesStore.php

This fixes an issue where if you give an entry a slug that starts with the file extension, it will wipe out the slug.
It only happens in dated collections.
For example, if you have a slug of `foo` it would save `2023-02-22.foo.md`.
But if you have a slug of `mdfoo` it would save `2023-02-22.md`.
This is because it was looking for `.md` in the string and getting everything before it, which was just the date.
This is fixed by doing `Str::beforeLast` instead of just `before` so it finds the final `.md`.

Fix save issue when slug starts with extension

---

tests/Tags/CacheTagTest.php

Since Laravel 10.1.4, faking a facade twice can have a different outcome.
We should not have been doing this anyway. See https://github.com/laravel/framework/pull/46188 for context.
The test should probably be rewritten to perform all the assertions at the end, but this will do for now.

[4.x] Fix test failure from double faking Event

---

.github/workflows/tests.yml

For whatever reason, the "setup php" step takes over 3-4 minutes when using php 8.2. But for 8.1 it's only ~1 minute.
The PHP version doesn't _really_ matter. We're testing 8.2 elsewhere.

[4.x] Test Windows using PHP 8.1

---

routes/api.php
routes/cp.php
routes/glide.php
routes/routes.php
routes/web.php
src/Providers/AddonServiceProvider.php

Previously, if you were to push routes to cp, web, or actions, it would assume you wanted them in a certain namespace. Now you're on your own.
For example:
```php
use App\Http\Controllers\ExampleController;
Statamic::pushCpRoutes(function () {
Route::get('alfa', 'ExampleController@method');
// before: Statamic\Http\Controllers\CP\ExampleController@method
// after: ExampleController@method
Route::get('bravo', ExampleController::class);
// before: Statamic\Http\Controllers\App\Http\Controllers\ExampleController@__invoke
// after: App\Http\Controllers\ExampleController@__invoke
Route::get('charlie', [ExampleController::class, 'method']);
// before: App\Http\Controllers\ExampleController@method
// after: App\Http\Controllers\ExampleController@method
// This array syntax worked fine before. …
```

[4.x] Routing

---

src/View/Antlers/Language/Nodes/Paths/VariableReference.php
src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Sandbox/VariableAssignmentTest.php

This PR fixes #7595 by pushing the updated state of the array back up through the scope. Currently it will push an internal variable similar to `the_array.0` (based on the nested path) when attempting updates, which leads to interesting results.
The following will now work correctly:
```antlers
{{ the_array = ['One', 10, 30, 40, 50, 60]; }}
Value: {{ the_array.0 }}
{{ the_array.0 = 'Two'; }}
{{ the_array.1 *= 5; }}
{{ the_array.2 -= 5; }}
{{ the_array.3 %= 2; }}
{{ the_array.4 /= 5; }}
{{ the_array.5 += 10; }}
Value: {{ the_array.0 }}
{{ loop from="0" to="3" }}{{ index }}{{ /loop }}
Value0: {{ the_array.0 }}
Value1: {{ the_array.1 }}
Value2: {{ the_array.2 }}
Value3: {{ the_array.3 }}
Value4: {{ the_array.4 }}
Value5: {{ the_array.5 }}
```

Antlers: Corrects updating nested value changes being lost after calling tags

---

src/View/Antlers/Language/Runtime/PathDataManager.php
tests/Antlers/Runtime/ArraysTest.php

This PR closes #7593 by allowing the creation of new nested array elements:
```antlers
{{ the_array = ['One', 'Two']; }}
{{ the_array.2 = 'Three'; }}
{{ the_array }}
{{ value }}
{{ /the_array }}
```
will now output `One Two Three`. Current behavior is that the `{{ the_array.2 = 'Three'; }}` will just clobber all of the existing data. Still on the fence about the idea, but also figured it shouldn't get rid of all existing data, either.
The following syntax is still not supported:
```antlers
{{ the_array[] = 'Three'; }}
```

Antlers: Allow creation of new array elements

---

src/View/Antlers/Language/Nodes/AntlersNode.php
tests/Antlers/Runtime/ParametersTest.php

This PR fixes #7560 by adding an additional check when it decides if it should resolve parameter values using the normal data manager, or pass it off to a full Antlers parser instance.
The following will now Just Work ™️
```antlers
{{ tag_name :parameter="[1234]" }}
```

Allows single array value inside parameters

---

resources/js/components/revision-history/History.vue
resources/js/components/revision-history/Revision.vue

The revison history panel uses the relative `date.fromNow()` method to display the revision time, but for revisions older than today this is always something like "25 days ago", so they're all the same.
This PR changes it so that revisions older than today show the actual time, which is a little more informative.
From this:
To this:

Display actual time in past revision history

---

src/View/View.php

We have `current_template`. This adds `current_layout`.
(`template` and `layout` are only available if the entry has them in their data. `current_template` was explicitly added.)
From #7615

Add current_layout variable

---

src/Providers/AddonServiceProvider.php

This pull request fixes an issue where CSS/JS assets wouldn't be auto-published by Statamic when running the `php artisan statamic:install` command if the assets were configured using Vite.
Vite was introduced in #6869.
I've just ran into this issue after tagging a release for one of my addons with Vite & installing it into a fresh site. I can workaround it for now by overriding the method.

Also auto-publish assets when using Vite

---

resources/js/components/inputs/relationship/SelectField.vue

Fixes #7631
This just selects the id and title columns. The only ones needed for this fieldtype mode.

Improve performance of relationship select field

---

resources/css/components/blueprints.css
resources/css/components/column-picker.css
resources/css/components/fieldtypes/table.css
resources/css/components/items.css
resources/css/elements/tables.css
resources/js/components/blueprints/RegularField.vue
resources/js/components/blueprints/Sections.vue
resources/js/components/data-list/ColumnPicker.vue
resources/js/components/data-list/Table.vue
resources/js/components/fieldtypes/TableFieldtype.vue
resources/js/components/fieldtypes/grid/Stacked.vue
resources/js/components/fieldtypes/grid/StackedRow.vue
resources/js/components/fieldtypes/grid/Table.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
resources/js/components/fieldtypes/replicator/Set.vue
resources/js/components/inputs/relationship/RelationshipInput.vue
resources/js/components/sortable/SortableList.vue

Fix some issues where drag mirrors wouldn't be positioned correctly, since #7557 causes `.@container` classes to create new stacking contexts. Items with `position: fixed` inside one of these become relative to the container rather than the `body` (e.g. drag mirrors).
Also makes minor fixes to grid in stacked mode looking/acting more like replicator.

[4.x] Draggable fixes

---

resources/views/layout.blade.php

`vue-js-popover` was removed in #7637 but I forgot to remove this element along with it.

[4.x] Remove tooltip element

---

src/Assets/AssetContainer.php

Collection, taxonomy and blueprint objects can all be cast to a string, returning their handles.
This PR adds the same to asset containers.

Implement `AssetContainer::__toString()`

---

src/Fieldtypes/Bard/Augmentor.php

Added in #7279, the IDs that get added to Bard/Replicator would be output on the frontend.
However, if you just upgraded from 3.3, for example, and your Bard set didn't have an ID, you'd get an error "undefined array key id".
This PR will fall back to null if the id is missing. This behavior was already in place for Replicator.

Handle missing Bard set id

---

resources/js/components/entries/PublishForm.vue
resources/js/components/terms/PublishForm.vue

Until there's a proper fix for #5550, we'll hide the live preview button on the create forms.
Closes #5550

Hide live preview button on create form

---

src/Stache/Stores/CollectionEntriesStore.php

This fixes an issue  
```
Call to a member function hasStructure() on null {"exception":"[object] (Error(code: 0): Call to
a member function hasStructure() on null at /usr/share/nginx/html/releases/149/vendor/statamic/cms/src/Stache/Stores/CollectionEntries
Store.php:138)
```

skip removeEntryFromStructure if no collection has been found

---

src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Runtime/ArraysTest.php

This PR corrects an issue that occurs when arrays are the _first_ thing inside the Antlers tag while chaining modifiers. These changes allow for the following example in the documentation to Just Work™️:
```antlers
{{ [1, 2, 3] | type_of }}     -> array
```

Antlers: Corrects oversight with arrays appearing in the "tag name spot"

---

src/Support/Arr.php
tests/Modifiers/ScopeTest.php

This PR fixes #7575 by resolving `Value` objects inside the `addScope` method.
The PR https://github.com/statamic/cms/pull/7436/files adjusted how the results of tag assignments are augmented. Overall, I think the changes in that PR make sense since it leaves things like `Value` alone until the last possible minute, which is more inline with other variable behavior.
This PR adds a check to the `addScope` method to resolve the values of `Value` objects, so things like this will now work (in a real setup these would come from entries/relationship fieldtypes):
```php
<?php
use Statamic\Support\Arr;
use Statamic\Fields\Value;
$arr = [
new Value(['title' => 'One' ]),
new Value(['title' => 'Two' ]),
];
Arr::addScope($arr, 'article');
```

Scope modifier resolve values value

---

src/Search/Comb/Comb.php
tests/Search/CombTest.php

This PR fixes #7163 to allow for search strings containing `+`. The changes in this PR remove the manual regex escaping, and instead uses `preg_quote` function with the `#` delimiter set.

Search: Allows for search queries containing "+"

---

package-lock.json
package.json
resources/css/components/popover.css
resources/js/components/DropdownList.vue
resources/js/components/FavoriteCreator.vue
resources/js/components/Popover.vue
resources/js/components/assets/Browser/Browser.vue
resources/js/components/collections/Listing.vue
resources/js/components/data-list/ColumnPicker.vue
resources/js/components/data-list/FieldFilter.vue
resources/js/components/data-list/Filters.vue
resources/js/components/entries/Listing.vue
resources/js/components/taxonomies/Listing.vue
resources/js/components/terms/Listing.vue
resources/js/components/users/Listing.vue

Continuation of #7637
- Swap `@popperjs/core` for `@floating-ui/dom` (Popper.js was renamed to Floating UI)
- The "scroll" feature is now automatically on via the `autoUpdate` feature of floating-ui. There's not really a situation where you wouldn't want it on. If you scroll, the open popover should maintain its appropriate position.
- Popover now portals its contents to the end of the page, within the "stacks on stacks" flow. This way it will appear on top of other things appropriately and fixes any clipping issues.
- Remove the `scroll` prop from `DropdownList` and `Popover`. They were kinda combined but didn't make sense for them to be.
- Remove the `strategy` prop. Now that we're portalling to the end of the page, the strategy is irrelevant. The default strategy (absolute) will always …

[4.x] Popper to Floating UI

---

resources/js/components/fieldtypes/ListFieldtype.vue
resources/js/components/inputs/relationship/SelectField.vue
resources/js/components/sortable/SortableList.vue

The `SortableList` component has changed the default delay from 200ms to 0. This makes interactions feel much snappier.
The `delay` was initially added to prevent unintentional drags. For example, if the thing you are sorting is also clickable, sometimes your mouse isn't 100% still when you click, making it consider it a drag. If you want to handle this situation, you can set the prop to what you need.
However, you should probably use the new `distance` prop instead of delay. This will consider it a drag after you've moved the mouse that many pixels. It's a better interaction than delay, which is needing to hold down the mouse for that long before it's considered a drag.
The relationship fieldtype's select mode lets you drag the options. This PR changes the delay to distance. As mentioned …

[4.x] Sortable list tweaks

---

resources/css/components/fieldtypes/replicator.css
resources/js/components/Slugify.vue
resources/js/components/blueprints/Fields.vue
resources/js/components/blueprints/Tabs.vue
resources/js/components/entries/Listing.vue
resources/js/components/fields/FieldtypeSelector.vue
resources/js/components/fields/Settings.vue
resources/js/components/fieldsets/EditForm.vue
resources/js/components/fieldtypes/replicator/AddSetButton.vue
src/Http/Controllers/CP/Fields/FieldsController.php
src/Http/Resources/CP/Entries/ListedEntry.php

A handful of fixes.
- Fix fields not being draggable when opening a bard/replicator. 
Closes #7800 
- Fix weird padding around the title field for the fieldset builder.
- Fix fields not being draggable in the fieldset builder.
- Fix fieldset builder field widths not kicking in when using something other than 100%.
- Make the slugify component slugify immediately. e.g. if the source has a value, it'll immediately set the slug. Previously it would wait for you to do a keystroke in the source field.
- Fix double slugification logic in the field settings form, causing the handle to stop slugifying after a moment. The handle field uses the slug fieldtype now, so let the fieldtype do its job.
Closes #7783 
- Add the regenerate button to handle field in the field settings form. It was made …

[4.x] Fixes

---

resources/js/components/Popover.vue
resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/bard/FloatingMenu.js
resources/js/components/fieldtypes/bard/FloatingMenuPlugin.js
resources/js/components/fieldtypes/replicator/SetPicker.vue

Fixes #7810 
Uses a local customized version of the FloatingMenu tiptap plugin, so we can have more control over the position of the button. This doesn't require tippy, it simply sets the coordinates of the button.

[4.x] Bard set picker fixes

---

resources/js/components/fieldtypes/TagsFieldtype.vue

Since #7755 if you have a clickable thing _inside_ a draggable thing, you'll need to give the draggable thing a distance otherwise it'll think you're trying to drag it.
This adds a little distance so you can click the x on the tag.
Fixes #7814

[4.x] Fix taggable fieldtype not being deletable

---

resources/css/elements/tables.css
resources/js/components/data-list/BulkActions.vue
src/Http/Controllers/CP/Collections/CollectionsController.php

- Fixes the 'select all' checkbox not appearing over the bulk actions bar.
- Fixes inverted gradients on selected rows.
- Puts the status column at the end instead of the start by default. Closes #7834

[4.x] UI fixes

---

resources/js/components/fieldtypes/IconFieldtype.vue
resources/js/components/fieldtypes/SelectFieldtype.vue

- Uses floating-ui instead of popper in icon fieldtype, continuation of #7841. We don't explicitly require popper-js anymore.
- Position the regular `select` fieldtype the same way, since it would have the same problem.

[4.x] Use floating ui to position select options

---

src/Fieldtypes/Bard.php
src/Fieldtypes/Bard/Augmentor.php
src/Fieldtypes/Replicator.php
src/Fieldtypes/Sets.php
tests/Fieldtypes/BardTest.php
tests/Fieldtypes/ReplicatorTest.php

Fixes #7768 
Improves the "preloading" test to test for more things, in both Bard and Replicator.
Improves the test to handle old and new set configs.

[4.x] Fix replicator

---

resources/css/components/global-header.css
resources/js/components/GlobalSiteSelector.vue

Looks like some broad styling changes to vue-select also applied here. It gave it unintended sizing and background colors.

[4.x] Fix global site selector styles

---

resources/js/components/Slugify.vue
resources/js/components/fieldtypes/ColorFieldtype.vue

There were a couple of fieldtypes unintentionally causing the "are you sure you want to leave" dialog because they updated data.
- Color fieldtype was setting the value on mount. Adjusted it so it sets it within the data. The default value fallback is already handled in PHP.
- The slug syncing immediately was incorrect behavior introduced in #7806 in order to fix #7783. I've reverted this behavior, and 7783 remains fixed. (Although you don't see a handle until you edit the display. Can address that separately.)

[4.x] Fix unnecessary navigate-away dialog

---

resources/js/components/Popover.vue
resources/js/components/fieldtypes/replicator/SetPicker.vue

Fixes #7861
Caused by #7844. Stopping propogation on popovers caused v-on-clickaway to not work when you clicked another popover trigger button.
Funnily, I told Jack not to bother adding a prop in #7844 because you'll probably want propagation stopped most of the time. Well we've found one case where we need it, so here's the prop.

[4.x] Fix Replicator set pickers not closing when opening a second one

---

resources/css/components/publish.css
resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/grid/StackedRow.vue
resources/js/components/fieldtypes/replicator/Set.vue
resources/js/components/publish/Fields.vue
resources/js/components/publish/Sections.vue

References https://github.com/statamic/cms/issues/7866
- Fixes the responsive padding in section headers
- Fixes field width breakpoints within nested containers, like in replicator, bard, and grid.
e.g. At what point they become 100%. Previously they would only become 100% based on the top level section. But since a replicator set, for example, would have additional side padding, the fields would be smaller. Now they will become 100% at a more expected point.
- Fixes nested fields immediately becoming 100% and sometimes overflowing when you started to drag a replicator or grid (stacked) row.

[4.x] Fix some container related padding issues

---

src/Fields/Section.php
tests/Fields/SectionTest.php

I found myself wanting to get the `fields` of a section. So I added a method for it. I also used the existing methods for `display` and `instructions` in the `toPublishArray` method. And added return types.

[4.x] Make it possible to get the fields of a section

---

resources/js/components/blueprints/Sections.vue

Continues from #7799
While #7799 fixed the dragging when editing a fieldset, it was still a little broken when in the blueprint builder.
If you open a bard field, close it, instead of it being a bit derpy, now the dragging just doesn't work at all.
This PR makes it work.
What seemed to happen was that setting the variable outside the component would make it reused across components. So when you open the blueprint builder, it sets the sortableFields, then you open the bard settings, it would see the variable, destroy it, and recreate a new sortable instance. Then when you closed the settings, dragging wouldn't work because it had been destroyed.
As a little bonus, this cleans up the sortable instances when the component is destroyed.

Fix field dragging in blueprints

---

package.json
resources/css/components/blueprints.css
resources/js/components/blueprints/Tabs.vue
resources/js/components/fieldtypes/FieldDisplayFieldtype.vue
resources/js/components/fieldtypes/SlugFieldtype.vue
src/Http/Controllers/CP/Fields/FieldsController.php

- Delete build directory before running dev. This prevents the annoying situation where you might have compiled production assets from testing earlier on, and you haven't run `npm run dev` yet, and you're wondering why your assets are outdated. Because the now out-of-date production assets are being used.
- Slug fieldtype will immediately update if it's required and empty. See #7857
- 
- Remove swap animations from blueprint fields and sections. When fields are side by side (e.g. if you make the fields not full width) they still animate vertically, which is really weird. Now it just feels snappier anyway.
- Fix fields not being draggable after opening a bard/replicator field settings. Same as #7870 
- Fix border around padding in blueprint field when dragging. Notice how the shadow goes …

[4.x] Misc fixes

---

resources/js/components/assets/Editor/FocalPointPreviewFrame.vue

Focal Point Editor: Correctly set bg for images with ( ) in their name

---

src/OAuth/Provider.php

This fixes #7882 by merging user data attributes when the user is found via an OAuth ID.

Merge user attributes if found by oauth id or email

---

src/OAuth/Provider.php

Prompted by #7883, this passes along the existing user (if one exists) to the `withUserData` callback, so within your callback you can more provide data appropriate to first vs. subsequent logins. See #3269
```php
OAuth::provider('github')
->withUserData(fn ($socialiteUser, $statamicUser) => [
'name' => $socialiteUser->getName(),
'created_at' => optional($statamicUser)->created_at ?? now()->format('Y-m-d'),
]);
```
Also makes the methods fluent so you can combine both methods in your service provider if you want.
```diff
-OAuth::provider('github')->withUserData(...);
-OAuth::provider('github')->withUser(...);
+OAuth::provider('github')
+  ->withUserData(...)
+  ->withUser(...)
```

Pass existing user into OAuth callback

---

resources/css/components/column-picker.css
resources/css/components/modal.css
resources/js/components/Modal.vue
resources/js/components/data-list/ColumnPicker.vue

Closes https://github.com/statamic/cms/issues/7897
- Moves the UI into a modal
- Sorts available columns alphabetically
- The `draggable` prop on the `modal` component can accept more than booleans.

[4.x] Move Column Customizer into a Modal for better long list management

---

resources/js/components/blueprints/Section.vue

- Fix handle not being synced with display field. Fixes #7891
- Select the display field instead of just focusing.

[4.x] Fix set handle not synced with display

---

src/Query/OrderBy.php

On the current version doing the following query will be silently ignored:
```php
Entry::query()->where('collection', 'news')->orderBy('date', 'DESC')->get()
Entry::query()->where('collection', 'news')->orderBy('date', 'something_invalid')->get()
```
This pull request add some validation to alert developers when a wrong value is passed to the query builder `orderBy` method.
This replicate Laravel's behavior: https://github.com/laravel/framework/blob/a24b75e81812f3d01e20182227a29b284eb712ce/src/Illuminate/Database/Query/Builder.php#L2295

Validate query builder orderBy arguments

---

resources/js/components/entries/PublishForm.vue

When switching between localized entries, the Save Button on the publish form is using the wrong `Save & Unpublish` or `Save Draft` label. This PR sets the correct initial published state of the localized entry, when switching between locales.
_Fixes the following issues:_

Fix save button label when switching between localized entries

---

resources/css/components/focal-point.css
resources/js/components/assets/Editor/Editor.vue
resources/js/components/assets/Editor/FocalPointEditor.vue

- Fix offset issue. Using `e.pageY` included scroll position. `e.clientY` doesn't. Something must have changed in our portals etc. Closes #7929
- Move portal inside focal point component. It's not needed around the actions since they are all just their own portals.
- Simplify css. fixed and z-index not necessary.

[4.x] Focal point editor fixes

---

resources/js/components/entries/Widget.vue
resources/views/widgets/collection.blade.php
src/Widgets/Collection.php

Closes https://github.com/statamic/ideas/issues/961
I called the Vue prop `additionalColumns` because `columns` conflicts with the listing mixin.

Support additional columns in collection widget

---

resources/css/components/fieldtypes/datetime.css
resources/js/components/fieldtypes/DateFieldtype.vue
resources/js/components/fieldtypes/date/Picker.js
resources/js/components/fieldtypes/date/RangeInline.vue
resources/js/components/fieldtypes/date/RangePopover.vue
resources/js/components/fieldtypes/date/SingleInline.vue
resources/js/components/fieldtypes/date/SinglePopover.vue

Fixes #7964
This PR basically swaps out v-calendar's built in popover logic for our own, which already handles portaling and stacking contexts.
- Split the UI logic into sub components. (Single w/popover, single inline, range w/popovers, range inline)
- Rather than using v-calendar's popover mode, they are all technically inline modes, but when we want popovers, we wrap it with our own popovers.
- The date pickers are always on the page, so the inputs can be hooked up to them and use their very helpful built in logic. e.g. if you type an incorrect date like 2023-1-3 it'll change it to 2023-01-03.
- When the popovers are closed, the date picker needs to still be there (but hidden) so the input field continues to work.
- When the popovers are open, the date picker gets portalled into the …

[4.x] Date fieldtype improvements

---

resources/js/components/Popover.vue
resources/js/components/assets/Browser/Browser.vue
resources/js/components/data-list/Filters.vue
resources/js/components/fieldtypes/replicator/SetPicker.vue

First, a background. 😂 
- In #7844, we disabled propagation of clicks on the popover trigger element to fix #7840.
- Stopping propagation like this prevented v-on-clickaway from working, which caused the following issues:
- #7861.
- Fixed in #7862 by adding a prop.
- #7898
- Fixed in #7907 by using that prop.
- If you have a dropdown list open, and you open a second, the first one stays open. (This PR fixes that)
So, this PR reverts stopping propagation since it caused more problems.
Instead, this fixes the original #7840 issue in a different way. Rather than the entire asset tile be clickable (including the twirldown), just wrap the clickable bits in a new div, attach the handlers to that, and let the twirldown sit on top.
Visually:
```
Tile (click handlers here)
Dropdown
Image
Filename …
```

[4.x] Revert stopping propagation of Popover clicks

---

resources/js/components/fieldtypes/SelectFieldtype.vue
resources/js/components/inputs/relationship/SelectField.vue

Fixes #7958
Flips the options on the select field when they'd appear out of the screen. (In the select fieldtype and relationship field in select mode.)

[4.x] Fix select field option positioning

---

composer.json
src/StaticCaching/Middleware/Cache.php

Fixes #7033
I wasn't quite able to reproduce the html stomping over the top of each other exactly like in the issue however I was able to reproduce a race condition.
Using Spatie's fork package, I did a handful of requests to the same page, and then invalidated that page somewhere in the middle of them. They happen at the same time, which simulates a race condition.
1. request (loads the cached page) ✅
2. request (loads the cached page) ✅
3. invalidate the page (e.g. like a client hitting save) ✅
4. request (notices the page isn't cached, so it loads a fresh page) ✅
5. request (also notices the page isn't cached, so loads a fresh page, again) ❌
Request 4 is what you'd expect. The page has just been invalidated so you should see a fresh version. This request should also cache the page. …

Add a lock to the static caching middleware

---

resources/css/components/fieldtypes/bard.css
resources/js/components/fieldtypes/bard/BardFieldtype.vue

This is a simpler (and cut-down) alternative to https://github.com/statamic/cms/pull/7926. It doesn’t introduce a decorator plugin or restructure the CSS in any significant way.
What this does do is move the Bard content styling to a new `bard-content` class, separate from the `ProseMirror` class. This allows custom Bard nodes that contain text content to use all the built-in styles by simply applying that class, without also inheriting all the container styling that comes with the `ProseMirror` class.
Would be really handy and allow me to simplify a bunch of custom stuff 🙂 .
Targets master.

Move Bard content styling to dedicated class name

---

src/Http/Controllers/CP/Fields/ManagesBlueprints.php

Make sure the blueprint sections will parse when the sections contain no fields.
Fixes #7993

[4.x] Fix blueprint error when section is missing fields

---

.github/workflows/pr-title.yml

PR titles should have the version line as the prefix.
Opening this because I missed manually renaming one before merging. Now the git log makes me sad. 😢 
The regex just allows `[n.x]` and won't bother with the rule on 3.x. We'll just prefix on 4.x onwards.

[4.x] Enforce PR title format

---

resources/js/components/navigation/View.vue
resources/js/components/publish/Field.vue
resources/js/components/structures/PageEditor.vue

Add support for multiple sections in nav items. Closes #7968 
If your blueprint has a `title` and/or `url` field, they'll remain where you placed them.
If they're missing, they'll get prepended to the first section.
This is the same behavior as before, except before we only assumed a single section.
This also makes the field area scrollable, but the header and footer with the buttons stay fixed.
It looks okay here but potentially a little weird on a full size page with only a couple of fields. 🤔  Maybe I should scrap the buttons-at-the-bottom change. I was trying to copy the asset editor.
(Also fixes some icons)

[4.x] Fix nav item editor

---

resources/js/components/Popover.vue

Fixes #7998
The double event caused two sets of keybindings to be registered in [SetPicker](https://github.com/statamic/cms/blob/d5808454ed7bc8d1e0d090317d2c8164cbb34a5f/resources/js/components/fieldtypes/replicator/SetPicker.vue#L180).
When closing the picker, only one set of keybindings were unbound. The second one remained, so when you hit enter within Bard, it was as if you were selecting from the set picker again.

[4.x] Fix double popover opened event

---

src/Actions/CopyAssetUrl.php

Only show Copy Asset URL action for public containers

---

src/Fieldtypes/Replicator.php
tests/Fieldtypes/BardTest.php
tests/Fieldtypes/ReplicatorTest.php

- Adjust tests to handle a value with no corresponding set
- Apply fix for replicator. It already worked in bard.
Fixes #8008

[4.x] Fix replicator error when value references a non-configured set

---

resources/lang/en/fieldtypes.php
src/Fieldtypes/Assets/Assets.php

Closes: https://github.com/statamic/ideas/issues/980
This PR adds support for `min_files` on the asset field type.
Ideally it would require you to enter a lower value than max_fields (if present), but I couldn't see any way to add validation rules to config fields.
(I also removed a variable declaration on max_files that wasnt being used)

Support `min_files` on asset field type

---

src/Http/Controllers/CP/Users/UsersController.php

Fixes small bug introduced by #7716, where if you edit your own super user in the CP, it would lose `super: true` and you'd get kicked out.

[4.x] Fix losing super when editing self user in cp

---

resources/js/components/PortalTargets.vue

Backport of 6dff4fc5427b126b7c20262d3280021da3706ba5 in #8033
Fixes #7989

Fix iOS scroll in stacks

---

resources/js/components/fieldtypes/date/RangePopover.vue
resources/js/components/fieldtypes/date/SinglePopover.vue

- Use portal-target change as the hook for updating the picker.
- Prevent error when clearing out range field.
- Let escape key close the popovers.
Fixes #8026
Context:
#8004 broke it, which meant that the date field components were relying on that first event, not the one after transition end. 
When resetPicker was called, there was no picker in the dom yet, so refs were empty. Changing to the portal-target changed event luckily allowed us to reset the picker when it will definitely be there.

[4.x] Fix date field issues

---

resources/js/components/fieldtypes/ArrayFieldtype.vue

Fixes #8039
It removes the drag mirror just like other table-based fieldtypes. We just missed the array fieldtype.

[4.x] Remove array fieldtype mirror

---

resources/js/components/blueprints/Tabs.vue
src/Fieldtypes/Sets.php
tests/Fieldtypes/ReplicatorTest.php
tests/Fieldtypes/SetsTest.php

- Prevent the sets fieldtype from adding a group when empty. This fixes #8042.
- Added tests for the sets fieldtype to cover this issue, plus more just because.
- I started writing more replicator tests thinking that's where the issue was, so I'm including those anyway. Doesn't hurt to have more coverage.
- Bring back the add tab button that I incorrectly removed in 4bebfde38b9332f7a3572beeb652e7967dd40f8f. Now that it's possible to have no tabs again, you need the button to add one.

[4.x] Replicator and Bard sets fieldtype improvements and fixes

---

src/Console/Commands/stubs/auth/statamic_auth_tables.php.stub

In Laravel 10, the `password_resets` table was renamed to `password_reset_tokens`. This does the same for `password_activations`.
This only affects newly generated migrations.

[4.x] Update password activation table name

---

resources/js/components/data-list/Filters.vue
resources/js/components/fieldtypes/date/RangeInline.vue
resources/js/components/fieldtypes/date/SingleInline.vue
src/Query/Scopes/Filters/Fields/Date.php

Fixes #8055
The actual issue is that when you clicked a date in the datepicker, since it's not "inside" the filter popover due to it being portaled away, it would think you're clicking away from the filter popover, and close it before the date has a chance to register. (Or something along those lines. :smile:)
The real fix is something along the lines of tweaking the clickawayClose logic to ignore clicks inside nested popovers. But it's a bit complicated since they're not actually nested in the DOM.
- Fix full width inline date pickers. The missing w-full class would prevent the calendars from stretching the full width, even when used as a regular publish field.
- Use an inline date picker in the filter to workaround the popover issue.
- make the min width of the field filter popover just …

[4.x] Fix date filter

---

resources/js/components/blueprints/Tabs.vue

Fixes #8063 
This fixes the issue by reinitializing the sortable when the tabs are changed.
[Same technique as used in v3](https://github.com/statamic/cms/blob/70f91a03adb2119e2d3b366d2c85916fd11d8a72/resources/js/components/blueprints/Sections.vue#L95) but accidentally left out during the blueprint revamp.

[4.x] Fix fields not being droppable onto new sections

---

resources/js/components/fieldtypes/VideoFieldtype.vue

Related to: https://github.com/statamic/cms/pull/6413
Fixes: https://github.com/statamic/cms/issues/8053
Vimeo unlisted urls are shared in the format: https://vimeo.com/x/y but when embedded need to be https://player.vimeo.com/x?h=y
This PR makes that happen.

Fix vimeo unlisted videos in video fieldtype

---

src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Sandbox/VariableAssignmentTest.php

This PR fixes #7796 by processing assignments when leaving an associative array/map tag pair.
The issue mentions the `{{ user }} {{ /user }}` pair, but upon further investigation you can trigger this behavior with any associative array.

Antlers: Processes assignments from within associative arrays/maps.

---

src/View/Antlers/Language/Runtime/ConditionProcessor.php
src/View/Antlers/Language/Runtime/LiteralReplacementManager.php
src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Runtime/YieldTest.php

This PR allows users to check if a section has been defined inside a condition (behavior outlined in #1193).
This check only works _after_ the `section` tag has been used, and is not "lazy". The following will now work:
In a template:
```antlers
{{ section:sidebar }}
<h2>Sidebar: {{ title }}</h2>
{{ /section:sidebar }}
````
In the layout:
```antlers
{{ if {yield:sidebar} }}
Do something only if the sidebar section has been registered.
{{ /if }}
```

Adds support for checking if section names exist

---

src/View/Antlers/Language/Runtime/ConditionProcessor.php
tests/Antlers/Runtime/YieldTest.php

This PR resolves #8066 by fixing a state leak when a condition contains an `else` clause that is evaluated.
For example, if you had the following template:
```antlers
{{ if false }}
{{# It doesn't matter whats inside here #}}
{{ else }}
Else Statement.
{{ /if }}
{{ section:seo_body }}Content{{ section:seo_body }}
{{ yield:seo_body }}
```
The site would return `1`. However, if you changed the condition to `true` so the `else` block is not hit, the bugged behavior will go away.

Antlers: Prevent `isConditionProcessor` from leaking on else branches

---

resources/css/components/fieldtypes/bard.css

This PR removes the flexbox which caused unnessary spacing and broke the gap cursor. It didn't seem to be necessary, since everything still works without it. Fixes #8069
This also removes an unnecessary min-height reset now that the selector applying the min-height in the first place is more specific since #7938.

[4.x] Fix missing gap cursor in Bard fullscreen mode

---

resources/css/components/stacks.css

Reverts the change in #8073, which caused #8082, as well as popovers not being visibile within stacks.
This resets the stacking context on _all_ of the top level portal targets rather than just on stacks.
Resetting on just the stack caused it to sit above other portal targets, like popovers.
This continues to fix #8082.
Fixes #8082.
Fixes dropdown lists / popovers not being visible.

[4.x] Use different approach to reset stack stacking context

---

resources/js/components/data-list/ColumnPicker.vue
resources/js/components/field-validation/Builder.vue
resources/js/components/fieldtypes/SelectFieldtype.vue
resources/js/components/fieldtypes/TagsFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/inputs/relationship/SelectField.vue

- Fixes issue where you can't remove a validation rule. Added distance prop otherwise it'll think you're dragging when you try to click the x.
- Makes all the "taggable" fields behave the same. No drag mirror, semi-transparent dashed border source.
- Lets the `select` fieldtype's options be sortable.
- Makes the sortable distances all use 5px instead of 10px all over the place.

[4.x] Sortable consistency

---

resources/css/cp.css

The last statement was removed in #8094. Now it's empty and Vite complains about that.

[4.x] Remove empty css file

---

resources/js/components/live-preview/UpdatesIframe.js

The normal live preview refresh uses a random string in the URL to prevent caching on each update, but if you're using the post message method and the fetch API to grab the updated page you don't currently have access to the URL with the new random string in it.
You can generate your own version, but since Statamic is already generating one it would be handy if you could just use that.
This PR includes the updated live preview URL in the post message data, so that your frontend code can use it, something like:
```js
window.addEventListener('message', async (event) => {
if (event.data.name === 'statamic.preview.updated') {
const text = await fetch(event.data.url).then((res) => res.text());
// ...
}
});
```

[4.x] Include URL in Live Preview post message

---

resources/js/components/fieldtypes/IconFieldtype.vue
resources/js/components/fieldtypes/LinkFieldtype.vue
resources/js/components/fieldtypes/SelectFieldtype.vue
resources/js/components/fieldtypes/TemplateFieldtype.vue
resources/js/components/inputs/relationship/SelectField.vue
resources/js/mixins/PositionsSelectOptions.js

- Move positioning logic to a mixin
- Apply to link fieldtype. Fixes #8123

[4.x] Fix link fieldtype's options appearing behind things.

---

resources/js/components/fieldtypes/bard/BardButtonsSettingFieldtype.vue

When you import a Bard field from a fieldset the `buttons` list is always saved as an override, even if it hasn't been changed from the default list in the source field. This means changes to the source field's buttons are never reflected in the imported fields even when no override was intended.
This happens because the `buttons` watcher is triggered during `initButtons()` and that always updates `data`. This PR fixes that by checking if the list of buttons are actually different before updating `data`.

[4.x] Fix imported Bard button config override

---

resources/js/components/Avatar.vue

Closes statamic/collaboration#81
When an avatar URL ends up with a 404 or some other type of error, fall back to using the initials rather than a broken image.

[4.x] Invalid Avatar URL falls back to initials

---

src/Fieldtypes/Icon.php

When using the icon fieldtype and you don't select your own custom directory, it's supposed to show the `regular` set of Statamic CP icons.
When the icon fieldtype was introduced, they were in a `default` directory. The default icons were moved to `regular` in #7854 but we didn't update this line.
This fixes the icon fieldtype showing nothing if you were to use the uncustomized config. (It still doesn't let you use them on the frontend.)

[4.x] Fix icon fieldtype default

---

resources/js/components/fields/FieldtypeSelector.vue
resources/js/components/fields/Settings.vue
resources/lang/ru.json

This addresses #8134 
Remove "Fieldtype" suffix in fieldtype settings header to simplify translation.
Use translation with placeholder rather than concatenation.
e.g. Some languages would say "Markdown field" and some say an equivalent of "Field Markdown". By using a single translation, it can be adjusted appropriately, as with the included Russian translation in this PR.

[4.x] Adjust a couple of fieldtype translations

---

resources/js/components/fieldtypes/ColorFieldtype.vue

When adding a pure white color swatch, it has no border or shadow and is indistinguishable from the white background of the popover. A border has been added in line with the surrounding styles

[4.x] Add border to colour option in ColorFieldtype.vue

---

src/StarterKits/Exporter.php

The $exportPath variable isnt defined as its scoped to $this

[4.x] Update error display in starter kit export

---

src/Exceptions/NotFoundHttpException.php
tests/FrontendTest.php

When working on tests for https://github.com/statamic/seo-pro/pull/268, we noticed that though 404 status codes were in the view context, they weren't being properly hydrated to `View\Cascade` (which we use in the SEO Pro blade directive specifically when rendering blade components). This PR fixes that.

[4.x] Fix 404 response status view cascade hydration

---

resources/js/components/CodeBlock.vue

[4.x] Fix path for SVG copy icon in the Updater popover

---

resources/js/components/blueprints/Builder.vue
resources/js/components/blueprints/Section.vue
resources/js/components/blueprints/SuggestsConditionalFields.js
resources/js/components/field-conditions/Builder.vue
resources/js/components/fieldsets/EditForm.vue
resources/js/components/fieldtypes/replicator/SetsFieldtype.vue
resources/lang/en/messages.php

- Makes fields from the entire blueprint available in the suggestions.
- Fixes #8155
- Fixes #6151
- Allows fields from imported fieldsets (recursively!) to appear in that dropdown.
- Wire up field suggestions in the fieldset editor.
- Fixes #841
- In some cases, you don't get *all* the available fields in the dropdown. For example, if you're in the fieldset editor, it only knows about fields in that fieldset. But you're still able to type fields in the blueprint, or other potential fieldsets. Added an instructional line explaining you can type any field handle.

[4.x] Fix suggestable condition fields

---

resources/css/components/fieldtypes/replicator.css
resources/js/components/fieldtypes/replicator/AddSetButton.vue
resources/js/components/fieldtypes/replicator/Replicator.vue

Fixes #8138
This PR maintains the spacing between replicator sets by keeping the divs there with a fixed size. The button inside those divs will disappear conditionally instead. When the button is hidden, the div will stick around as a sizer.

[4.x] Fix margins disappearing in Replicator when hitting max items

---

resources/js/components/fieldtypes/grid/Stacked.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
resources/lang/en/fieldtypes.php
src/Fieldtypes/Replicator.php

- Add fullscreen option to Replicator.
- Hook up fullscreen option to button in Grid stacked mode.
Fixes #8137

[4.x] Fix fullscreen mode buttons in Grid and Replicator

---

src/Fieldtypes/Date.php
src/Validation/DateFieldtype.php
tests/Fieldtypes/DateTest.php

Fixes #8172
In #7753 we made the date fieldtype submit arrays containing date and time. This broke validation that expected the date to be a... date.
Now the array will be converted back to dates for validation.

[4.x] Fix date validation

---

src/Console/Commands/MakeFieldtype.php
src/Console/Commands/stubs/addon/package.json.stub
src/Console/Commands/stubs/addon/vite.config.js.stub
src/Console/Commands/stubs/addon/webpack.mix.js.stub
tests/Console/Commands/MakeAddonTest.php

When using make:fieldtype, it will now use Vite instead of Mix.

[4.x] New addons use Vite

---

resources/js/components/Bard.js

This PR exports @tiptap/vue-2 so it can be used in custom Bard extensions.

[4.x] Export tiptap/vue-2

---

resources/views/forms/automagic-email.antlers.html

This simple PR ensures that the automagic form mails respect line breaks of textarea fields. Hacked on it with @jesseleite on the way back home from Flat Camp.

[4.x] Respect line breaks in automagic form mails

---

src/View/Cascade.php

Hi there,
I hope this message finds you well. I have been working with Statamic extensively and have noticed that in large websites with numerous global sets, the hydration of all these global sets to a view can result in unnecessary performance overhead.
This way I can bind my extended version of Cascade class and extend the hydrateGlobals method where I can exclude some globals that I don't need in the view!
I believe this enhancement will greatly benefit users working with large Statamic websites that utilize the Control Panel extensively. It aligns with the goal of optimizing performance without compromising functionality.
Thank you!

[4.x] Change hydrate methods from private to protected

---

resources/js/components/fieldtypes/MarkdownFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/fieldtypes/bard/Image.vue
resources/js/components/fieldtypes/bard/LinkToolbar.vue
routes/cp.php

This pull request fixes #8208 by changing the `assets-fieldtype` route to use a POST request, rather than a GET route as the URL gets too long for browsers like Safari when you have lots of assets selected.
A similar issue was fixed a while back using the same solution: #4484

[4.x] Fix asset selection request query length

---

src/CP/Utilities/Utility.php
src/CP/Utilities/UtilityRepository.php
src/Facades/Utility.php
src/Http/Controllers/CP/Utilities/UtilitiesController.php

Fixes inconsistency with how underscores are handled in utility slugs.
Also added a missing facade typehint.

[4.x] Fix utility handle to slug conversion

---

src/Fieldtypes/AssetFolder.php

This pull request implements searching on the Asset Folder fieldtype, used when setting a folder on an Asset field in a blueprint.
In the stack, the search bar would appear but actually trying to use it wouldn't work. This PR implements the logic to make search working.
There's no related issue for this one, just something I noticed when working on a site.

[4.x] Fix searching with asset folder fieldtype

---

resources/js/components/SvgIcon.vue
resources/js/components/blueprints/RegularField.vue
resources/js/components/fields/FieldtypeSelector.vue
resources/js/components/fields/Settings.vue

This pull request attempts to fix #8129.
The issue was that SVG fieldtype icons weren't being shown in the blueprint/fieldset builders, it would simply fallback to the generic fieldtype icon.
This was happening due to the `SvgIcon` component expecting the `name` prop to be the path to an icon, rather than an SVG string.
I'm not 100% happy with this fix so feel free to close & tackle another way if you have another idea. 
Essentially, I've added a check into the `SvgIcon` component to check if the `name` prop (which could maybe become `icon`?) contains `<svg` & if it does, it'll use the SVG string as the icon, otherwise it'll fallback.
However, I also had to make changes to the `RegularField` and `FieldtypeSelector` components to check the same thing to `light/` is only prepended to the …

[4.x] Fix custom fieldtype SVGs

---

src/Auth/UserTags.php

Fixes: https://github.com/statamic/cms/issues/8217
This PR fixes the user:can tag in blade calls, eg `Statamic::tag('user:can')... ` by checking for the presence of $this->parser as suggested by Jason.

[4.x] Fix `user:can` tag in blade

---

resources/js/components/DropdownList.vue
resources/js/components/assets/Browser/Browser.vue

Show the dropdown trigger if its opened by tracking the state using events (which should probably have been there anyway).
Replaces #8230

[4.x] Fix asset grid button visibility

---

src/Modifiers/CoreModifiers.php
tests/Modifiers/ClassesTest.php

This PR adds a new `classes` modifier that wraps Laravel's `Arr::toCssClasses` helper method.
Which lets us write the following:
```antlers
<div class="something {{ ['danger' => isDanger, 'success' => otherValue] | classes }}">
</div>
```

[4.x] Adds a new classes modifier

---

src/Fields/Fields.php
src/Http/Controllers/CP/Users/UsersController.php
src/Http/Controllers/UserController.php

This PR updates the Validator class validate() method to allow passing a parameter for `replacements`.
It also ensures that user id is passed as a replacement value when editing through the CP or through a profile form update.
Fixes: #8085

[4.x] Ensure to pass replacements so `unique_user_value works` as expected

---

src/Modifiers/CoreModifiers.php
tests/Modifiers/EmbedUrlTest.php

This PR fixes #8249 by adding support for the start time parameter to full YouTube links, such as this one:
```
https://www.youtube.com/watch?v=hyJ7CBs_2RQ&t=2
```
After the changes in the PR, the generated embed URL will now become:
```
https://www.youtube-nocookie.com/embed/hyJ7CBs_2RQ?start=2
```

[4.x] Adds support for start time to full YouTube links when using the embed_url modifier

---

src/Http/Controllers/CP/Users/UsersController.php

Since previous updates change searching to return a search document rather than the specific result, searching for users in the CP while having a search index of `users` has been broken.
This PR maps the search result back to a user entity.
Fixes: #7680

[4.x] Fix searching users when a search index is present

---

src/Entries/Collection.php
tests/Data/Entries/CollectionTest.php

This PR adds `customSortField` and `customSortDirection` getter methods to the collection class.
It's needed by the Eloquent driver.
These methods will get the explicitly defined sort field/direction values. The regular `sortField` and `sortDirection` methods have logic in them to handle fallbacks. The Eloquent driver needs the actual explicit values without the fallbacks.
statamic/eloquent-driver#161

[4.x] Add custom sort field methods to Collection

---

src/Data/ContainsComputedData.php
src/Data/HasOrigin.php
src/Entries/AugmentedEntry.php
tests/Data/Entries/AugmentedEntryTest.php
tests/Data/Entries/EntryTest.php
tests/Data/Structures/AugmentedPageTest.php

I’ve noticed that when using computed values the same callbacks are being called 17 times during a single page load, which is unexpected and seems unnecessary. I know the docs recommend caching computed values when using external APIs or performing other expensive tasks, but even when doing something simple calling the same function that many times isn’t ideal.
This is happening because:
* `AugmentedEntry::keys()` calls `$this->data->values()` which results in all computed callbacks being called
* `AbstractAugmented::get()` calls `$this->keys()` every time a [data method value is fetched](https://github.com/statamic/cms/blob/4.x/src/Data/AbstractAugmented.php#L59)
This results in all computed callbacks being called every time any data method value is fetched.
This PR aims to fix this by …

[4.x] Reduce computed value callback calls

---

src/View/Antlers/Language/Runtime/NodeProcessor.php

This PR re-introduces an old friend to the Antlers Runtime: The timeline information for tags within the Debug Bar.
In addition to bringing back the time it takes to execute your tags, it will also include file and line number information when available:

[4.x] Adds Debug Bar Support to Antlers Runtime

---

src/View/Antlers/Language/Runtime/ConditionProcessor.php
src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Sandbox/ConditionalsTest.php

This PR resolves #8325 by relaxing the general comparisons. The root cause of the problem described in the linked issue is that eventually a comparison like `1 === true` would be performed, which returns `false`.
This internal comparison is now a loose comparison, and the logic surrounding numeric values is now consistent with regular PHP.

[4.x] Antlers: relaxes generic comparisons

---

resources/views/auth/login.blade.php

Fixes #8329
Currently the link is hidden when OAuth is enabled. This PR flips the logic so that it is hidden when the email login is disabled.

[4.x] Forgot password link is available with OAuth

---

resources/js/components/data-list/Table.vue
src/Http/Resources/CP/Users/Users.php

This PR makes two small tweaks to the users listing/sorting:
1. Enables sorting by last login (this seems to work fine as far as I can tell and would be a useful addition)
2. Hides the sort arrows that appear on hover for un-sortable columns like roles (this was confusing a client)

[4.x] Enable sorting by last login, hide un-sortable arrows

---

src/Assets/Asset.php
src/Http/Resources/CP/Assets/Asset.php

This PR simplifies the AssetResource by moving the logic into the asset class itself.
This is really helpful if you need to manipulate the download url for assets.

[4.x] Move downloadUrl logic into Asset class

---

src/View/Debugbar/AntlersProfiler/PerformanceTracer.php

Fixes a division by zero error that can happen if something fails early and causes the total execution time to be `0`.
This bug causes exceptions within tags/modifiers to become less visible/harder to track down.

[4.x] Antlers profiler: fixes division by zero

---

src/View/Debugbar/AntlersProfiler/PerformanceTracer.php

Prevents comments from making their way into the profiler's logic, which will cause issues as they will not have a `$name` property.

[4.x] Prevent processing Antlers comments within the profiler

---

src/Tags/UserGroups.php
tests/Tags/UserGroupsTagTest.php

I noticed when helping someone on Discord that Erin had added support for passing an array of roles to `user_roles`, so we should allow the same for `user_groups`.
Ref: https://github.com/statamic/cms/pull/7328

[4.x] Allow arrays to be passed to `user_groups` tag

---

src/Modifiers/CoreModifiers.php

This is a handy modifier to have access to within Antlers to help determine if a link is external - and if so, can conditionally add `target="_blank"` to an anchor, such as:
```antlers
<a href="{{ link }}" {{ if link | is_url_external }} target="_blank" {{ /if }}>{{ label }}</a>
```
If this is something that is of use, happy to do a PR for docs to update those too.

[4.x] Adds is_external_url modifer

---

src/Providers/ViewServiceProvider.php

This allows you to add `'debugbar' => false` to your `config/statamic/antlers.php` file to disable it. It's enabled by default.
Looks like there could be an issue sometimes that breaks debugbar (#8352), so this setting would at least let you disable the Antlers part so the rest of Debugbar can continue working.

[4.x] Add setting to disable Antlers profiler

---

src/Fieldtypes/Bard/LinkMark.php

Hello everyone,
I'd like to address an issue through a brief user story.
Imagine you're working on the multisite configuration control panel, and your task is to create a new entry. You start by adding content to the 'en-de' site. Within that content, you include a Link Mark that points to another entry within the 'en-de' site.
Now, let's say you localize the content for the 'en-us' site and inherit the content. The problem arises when the link still directs users to the 'en-de' site, instead of switching to the corresponding 'en-us' site. This behavior seems counterintuitive since visitors expect a seamless transition to the appropriate locale by simply clicking on a link.
To improve this, I propose implementing a mechanism that attempts to locate and resolve the entry in the correct …

[4.x] Fix LinkMark to resolve entries in correct locale

---

src/View/Debugbar/AntlersProfiler/PerformanceCollector.php
src/View/Debugbar/AntlersProfiler/PerformanceObject.php
src/View/Debugbar/AntlersProfiler/PerformanceTracer.php
src/View/Debugbar/AntlersProfiler/resources/widget.js

Fixes #8352 
This PR makes the following changes:
* Removes all unescaped content to reduce the amount of data, and to prevent issues with json encoding
* Begins filtering node samples when the sample count exceeds 1,000 (these samples power the graph)
* Dramatically reduces the amount of data sent to the client that is required to power the current views/reporting

[4.x] Antlers Profiler: Refactors & reduces client-side data

---

src/Extensions/FileStore.php

Laravel 10.14.0 changed the visibility of the `path` method to public.
We had an overridden that method, but it was protected. The difference in visibilities caused an error.
This PR changes the visibility to match.
Fixes #8364

[4.x] Change visibility of FileStore path method

---

.github/workflows/pint-fix.yml
src/Statamic.php

See #8310
The "fix" workflow requires a personal access token. On forks, they wouldn't have that token, and I definitely don't want to require it. At the moment on forks you get a "workflow failed" error/email because of the missing token.
This will prevent the job from running in the workflow.
There's no way at the moment to have a workflow be ignored completely on a fork.

[4.x] Avoid Pint fixing on forks

---

src/Http/Controllers/CP/Auth/LoginController.php

[This PR](https://github.com/statamic/cms/pull/4625) moved the emailLoginEnabled check into an OAuth only situation. If you don't have OAuth enabled, you only have email, and [this bit here](https://github.com/statamic/cms/blob/4.x/resources/views/auth/login.blade.php#L61-L67) will never render.

[4.x] Bring back the password reset for non-OAuth sites

---

composer.json
src/Tags/Svg.php
tests/Tags/SvgTagTest.php

This PR adds a `sanitize` param to the `svg` tag battle potential XSS issues.
It uses https://github.com/darylldoyle/svg-sanitizer which is a PHP implementation of the popular DOMPurify library. https://github.com/cure53/DOMPurify
The svg tag will now let you add `sanitize="true"` and will trigger the sanitization.
``` antlers
{{ svg src="..." sanitize="true" }}
```
```xml
<svg><path onclick="foo">...</path><script>alert('foo')</script></svg>
```
```xml
<svg><path>....</path></svg>
```
You may specify additional attributes or tags to be allowed through the sanitizer:
```antlers
{{ svg src="..." sanitize="true" allow_attrs="onclick|onload" allow_tags="mesh|foreignObject" }}
```
We are leaving it as opt-in otherwise it would be a breaking change. In Statamic 5 we will make it sanitize by …

[4.x] SVG tag sanitization

---

resources/js/components/live-preview/LivePreview.vue

This PR resolves https://github.com/statamic/cms/issues/8224 by:
- reset the styles attribute if no preview device was found (responsive mode)

[4.x] Reset Live-Preview viewport size back to responsive

---

src/Fieldtypes/Entries.php

In #8253 we introduced the ability for the entries fieldtype to use the appropriate search index. If the search query builder is used, it returned `Result` instances which needed to be mapped over. The way the code was written was only applicable to when it was a paginator. For the `select` mode, you don't get a paginator, and you ran into the error.
This PR changes it to map those result instances in a more compatible way.
Fixes #8411

[4.x] Fix mapping of search results in entries fieldtype

---

resources/lang/zh_CN.json

订购清单 means shopping list, and 有序列表 is for ordered list

[4.x] Fix a typo in zh_CN.json

---

src/Http/Controllers/API/CollectionEntriesController.php
src/Tags/Collection/Entries.php
src/Tags/Concerns/QueriesTaxonomyTerms.php
tests/API/APITest.php
tests/Tags/Collection/EntriesTest.php

(In the [REST API docs for filtering](https://statamic.dev/rest-api#filtering), you're told you can use all the same conditions "available to the collection tag"...
If you follow that link through to [Taxonomy Conditions](https://statamic.dev/conditions#taxonomy-conditions), you're told that you can use the following "query modifiers"...
We noticed through a customer email that the REST API's taxonomy filtering was inconsistent with the collection's taxonomy filtering, despite being documented that way. This PR aims to fix these inconsistencies.
- You can see in the implementation that we support `in` and `not_in` aliases, for the purpose of backwards compatibility with [#6615](https://github.com/statamic/cms/pull/6615), despite that functionality never being mentioned directly in the …

[4.x] Fix taxonomy term filtering inconsistencies between Tag and API

---

src/Licensing/Outpost.php
tests/Licensing/OutpostTest.php

Users are reporting 500 errors when trying to visit /cp due to a recent curl bug introduced on July 19th(?). This PR improves exception handling in Outpost class to more gracefully handle errors like this.
References: https://github.com/statamic/cms/discussions/8471

[4.x] Fix error handling for recent curl bug

---

src/StaticCaching/Middleware/Cache.php
src/StaticCaching/NoCache/RegionNotFound.php
src/StaticCaching/NoCache/Session.php

Fixes #6781
This PR introduces adds error handling to the replacement step when serving a statically cache page.
When attempting to replace a region, and the region isn't in the cache for whatever reason, instead of throwing an error it will now just regenerate the page as if it was uncached.
The reason for the region not being in the cache is still a bit of a mystery. Maybe a race condition? Not sure.

[4.x] Handle nocache tag error

---

resources/views/updater/index.blade.php

This pull request fixes a small thing I just noticed... when you're on a site with no addons or no unlisted addons, the sections still show on the Updater page but they're just empty.
This PR just hides the sections if there's no addons/unlisted addons to show in the list.

[4.x] Hide heading when there are no unlisted addons

---

resources/js/components/terms/PublishForm.vue

The taxonomy term publish form should use the live preview URL provided on the localisation rather than using its own hard coded url. It should also use the showLivePreviewButton() function to determine whether to show the button or not.
This allows devs to bind their own version of LocalizedTerm and change the live preview target if required.
Fixes #8443

[4.x] Use term live preview url instead of hard coded URL

---

src/GraphQL/Queries/EntriesQuery.php
tests/Feature/GraphQL/EntriesTest.php

adds the `site` argument to the `entries` GraphQL query,
as suggested here: https://github.com/statamic/ideas/issues/1016

[4.x] Support querying entries in a specific site in GraphQL

---

resources/css/components/fieldtypes/bard.css
resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/lang/en/fieldtypes.php
src/Fieldtypes/Bard.php

This PR adds a "Show Word Count" option to the Bard fieldtype.  If enabled, the word count is displayed at the bottom of the Bard field, between the reading time and character limit.

[4.x] Add "Show Word Count" option to the Bard fieldtype

---

resources/js/components/collections/View.vue
resources/views/collections/show.blade.php
src/Http/Controllers/CP/Collections/CollectionsController.php

Fixes #8473
The url was hard coded to the first site. This PR passes in URLs for each site in PHP and uses them based on which site you have selected in JS.

[4.x] Use site in create entry button on collection tree view

---

src/Fieldtypes/Date.php
tests/Fieldtypes/DateTest.php

Fixes #8187
This is a follow up for #8205 which not completely fixed the issue. 
If a ranged date was not shown, it tried to access an array on null, causing an error on save.

[4.x] Fix ranged date validation

---

src/Contracts/Forms/Submission.php

This pull request fixes an incorrect doctype in the `Submission` contract, where it was saying the return type for the `data` method was an array but it's actually a `Collection` now.
Fixes #8375

[4.x] Fix incorrect doctype in `Submission` contract

---

src/Assets/Uploader.php

This pull request fixes an issue where GIFs would be processed on file upload (if the asset container had a `source_preset` set) and would become static.
Meaning cool GIFs like this:
Would turn into this: 😞 
---
Related: studio1902/statamic-peak#321

[4.x] Ignore processing GIFs on file upload

---

src/Auth/User.php

Fixes https://github.com/statamic/cms/issues/8454 by implementing `ContainsQueryableValues` on the base User class.

[4.x] Implement `ContainsQueryableValues` on users

---

src/Fieldtypes/Users.php

This pull request fixes an issue where you couldn't have separate first & last name columns for users in the database when using the User fieldtype. The fieldtype would error out due to no `name` field existing for the `->orderBy('name')` part of the query.
Fixes #8353.

[4.x] Handle separate first & last name fields in User fieldtype

---

src/Http/Controllers/CP/PreviewController.php

Revised version of https://github.com/statamic/cms/pull/8474 (as suggested by @jasonvarga [here](https://github.com/statamic/cms/pull/8474#issuecomment-1648493499))
This pull request allows the preview target to be a relative URL. The URL can be either hardcoded or by using `{url}`.
E.g.
```yaml
preview_targets:
-
label: 'Custom Target'
url: '/cp/custom-preview-target'
refresh: true
-
label: 'URL'
url: '{url}'
refresh: true
````

[4.x] Allow relative urls as preview targets

---

src/Query/Builder.php

@duncanmcclean found a great bug that I'm not sure how we didn't catch before.
```
$query->where('field', 'LIKE', '%y%')
```
was failing as there is no matching operator due to it expecting a lowercase like.
It does raise the question as to whether we should throw an error when there is no matching operator?

[4.x] Force lowercase on operator in query builder

---

resources/lang/en/fieldtypes.php
src/Forms/Fieldtype.php

Replaces https://github.com/statamic/cms/pull/8494 and actually works this time.
This time I've passed the items as a DataCollection into the ItemQueryBuilder which allows querying of the data. Along the way I noticed searching wasn't enabled, even though in Stack view there is a search field, so I hooked that up too. Not sure most people have enough forms to justify searching, but better for the search input to work than not.
I've also done all the usual checks for pagination etc that other relationship fields also do.
Closes https://github.com/statamic/ideas/issues/841

[4.x] Add `query_scopes` and searching to the form fieldtype

---

src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Sandbox/VariableAssignmentTest.php

This PR resolves #8360 (variable name collisions when using the `as="something"` tag parameter) by:
1. Adjusting the scope merging behavior when handling variable assignments and tag scope (ensures tag results are given priority)
2. Adjusting the post-tag execution phase to manage variable assignments when there are name collisions (to prevent unanticipated behavior)
If the tag results have not changed after the tag's content has been parsed, the original value of the colliding variable name is restored. If someone manually changes the variable *again* inside the tag, it is processed like any other normal assignment.

[4.x] Handles variable name collisions when using the "as" tag param

---

resources/js/components/UpdatesBadge.vue

Currently when the "updater/count" route returns anything, it is added to the badge - even if the response is not a number (meaning you can get some weird badge appearances).
Working on two factor challenges for the CP and if the challenge is due to be triggered, it can result in HTML being returned as part of this call, making the badge appear as a a huge slab of HTML.
This update updates the UpdatesBadge component to only update the internal `count` when the response is able to be parsed as a number. Otherwise, it will be set to zero (i.e. hide the badge).

[4.x] Tweak the UpdatesBadge component to only update the count when the response is a number

---

src/Fieldtypes/Users.php
src/Http/Controllers/CP/Users/UsersController.php

Following on from the comments here https://github.com/statamic/cms/issues/8353#issuecomment-1662522741
Apply word by word searching to the user list in the CP when its a first_name, last_name set up in the blueprint
Match the same logic from the main CP listing to the user field type.
Closes #8353

[4.x] Match user searching in users list and user field type

---

src/Fieldtypes/Bard.php

Fixes an issue where legacy data might be recognized as legacy if you use the new set grouping config style.

[4.x] Improve Bard legacy content handling

---

resources/js/components/fieldtypes/FieldDisplayFieldtype.vue
resources/js/components/fieldtypes/Fieldtype.vue
resources/js/components/fieldtypes/SelectFieldtype.vue
resources/js/components/fieldtypes/SlugFieldtype.vue
resources/js/components/fieldtypes/ToggleFieldtype.vue
resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue
resources/js/components/fieldtypes/replicator/Field.vue
resources/js/components/publish/Field.vue

Fields inside Bard, Replicator, and other nestable fieldtypes were creating duplicate HTML IDs which caused issued with the wrong input being focused.
This PR addresses that by prefixing field IDs with `fieldPathPrefix` if set.
It also sets the `fieldId` on a number of fieldtypes that didn't have it set, which allows the fields to be focused by clicking on their respective labels.
Closes #6616.

[4.x] Improve nested field ids and focus behavior of some fieldtypes

---

src/Assets/AugmentedAsset.php

Fixes: https://github.com/statamic/cms/issues/8546 by adding `is_svg` to the variables provided by Augmented Asset

[4.x] Add is_svg to augmented assets

---

src/Globals/Variables.php
src/Stache/Stores/GlobalsStore.php

#8343 introduced the ability for the global variables to be in a different store/repository from the global sets themselves.
This PR addresses an oversight that when you have a single site, and different directories configured, that the variables won't be found since they're stored in the global set's file. Rather than actually "fix" it, this will just throw an exception if you configure them to have different directories. The previous PR was more geared towards usage with the Eloquent driver, which will still be possible. 
In Statamic v5 we may consider just _always_ having the global variables live in their own files (like you get when using multisite).
(This PR also adjusts the path to point to the global variables store directory, even though the exception enforces it's the same as …

[4.x] Prevent using different globals and variables directories

---

src/Http/Resources/API/GlobalSetResource.php

This resolves: https://github.com/statamic/cms/issues/8462
Calling the REST API for globals resolves any given relationship, so it behaves the same as other API endpoints (entries, …).
**This is a breaking change** since it changes the behaviour of the public facing API of Statamic.

[4.x] REST API Globals return resolved relations

---

src/Http/Controllers/CP/Globals/GlobalVariablesController.php
tests/Feature/Globals/UpdateGlobalVariablesTest.php

Fixes #8559
Replaces #8561
Prior to #8343 when you save global variables in the CP, the GlobalSetSaved (etc) events would be dispatched. That PR made it so that when you save the variables, only the variable events got dispatched - logically. But that was a breaking change.
This PR makes it so that when you save the variables form, it'll still save the global set and dispatch the original events. This fixes the breaking change.

[4.x] Fix globals save event

---

src/Http/Controllers/CP/Fields/FieldsController.php

Closes #8575
The `views` variable is used in the cascade to keep track of any view specific variables - stuff you put the in the front-matter of a view file.

[4.x] Make the views field handle reserved

---

src/CP/Utilities/CoreUtilities.php

Run `pint` with the newer version. It now extracts function imports.

[4.x] Pint updates

---

resources/views/partials/global-header.blade.php

I'm sorry, I realize this is an obnoxiously-small PR, but my eye cannot unsee this misaligned icon. 😅 One-word patch, changing from an `md:block` to `md:flex`.

[4.x] Fix alignment of menu icon in global-header.blade.php

---

resources/js/components/assets/Uploader.vue

Uploading asynchronously appears to cause a race condition. Technically its still there, e.g. if someone else uploads at the same time as you, but this helps.
Fixes #8587

[4.x] Make uploader synchronous

---

resources/views/auth/login.blade.php

When using Oauth, there's some hard coded text in the form that our client has been complaining about ;) There's already translations of `or` in translation files, so it'd be a shame not to use them.

[4.x] replace hard coded text with i18n

---

src/Entries/Entry.php
src/Entries/InitiatorStack.php
src/Events/EntrySaved.php
tests/Data/Entries/EntryTest.php
tests/Search/UpdateItemIndexesTest.php

See https://github.com/statamic/cms/discussions/8588
This PR adds an `isInitial()` method on the `EntrySaved` event.
When you save an entry, if it has any localizations, they'll also get saved since #8505.
Depending on the use, you might only care about the one that was initially saved.
For example, if you wanted to send a notification when an entry is saved, you might not care that its localizations were also updated. But maybe you are updating some third party content, in which case you would care.
```php
Event::listen(function (EntrySaved $event) {
if ($event->isInitial()) {
$this->sendNotification();
} else {
// It's just a localization that happened to get saved. Don't send notification.
}
});
```

[4.x] Add a way to determine which entry saved event was the initiator

---

src/Events/EntrySaved.php

Continuation of #8605
I merged the PR before pushing up the method rename commit. Oops.
The method should be `isInitial()` as per the other PR description.

[4.x] Rename method

---

resources/js/mixins/PositionsSelectOptions.js

Fixes #8316
- Implemented the `autoUpdate()` function from the Floating UI library to ensure the dropdown list remains anchored to the select input, especially when its size changes due to filtering.
- Addressed the issue where the dropdown list would float above the select input on smaller screens or when the list becomes shorter.

[4.x] Ensure Dropdown List Remains Anchored on Resize

---

resources/js/components/fieldtypes/RevealerFieldtype.vue
resources/js/components/fieldtypes/bard/BardFieldtype.vue

I _think_ this fixes https://github.com/statamic/cms/issues/8615. Be great if anyone who's run into that can test.
The issue seems to be caused by a race condition when unsetting/setting the revealer fields in the store. When you move a set it will affect the field paths of multiple sets, so there will be multiple unset/set calls which could get mixed up. This defers the set calls to the next tick to ensure they run after everything has been unset (hopefully).

[4.x] Fix data loss when reordering sets with revealer fields

---

src/Data/DataReferenceUpdater.php
tests/Listeners/UpdateAssetReferencesTest.php
tests/Listeners/UpdateTermReferencesTest.php

Found a regression in 4.x where the newer style set groups in replicators and bards were not properly handled in our asset/term reference updater logic.
Fixes #8415

[4.x] Fix asset & term reference updaters when using new set groups blueprint config

---

src/Assets/AugmentedAsset.php
src/GraphQL/Types/AssetInterface.php
tests/Feature/GraphQL/AssetTest.php

Adds duration as a float field for `AssetInterface` when using GraphQL. Duration is available when working with an augmented asset so I think it makes sense to also make it available for GraphQL queries. We're currently using the `addField` method to add this on a site where it's needed.

[4.x] Add duration field to GraphQL AssetInterface

---

src/StarterKits/Installer.php

When you install starter kits more than once, the reticulating splines sleep step of 2 seconds can become a bit tiring. My proposal is to change it to 500000 microseconds which is .5 seconds. 
I didn't create an issue cuz this is so tiny. Feel free to close of course (as I can imagine this seems very picky).

[4.x] Reticulate Splines sleep for half a second

---

src/Facades/Endpoint/URL.php
tests/Facades/UrlTest.php

Closes https://github.com/statamic/cms/issues/8180
In some cases, if for example working with a proxy or common if using Docker, you might need to force a scheme via:
`\Illuminate\Support\Facades\URL::forceScheme('https');`
In that case, it might happen that the live preview can't be shown, as the page has been loaded via `https`, but the live preview will be requested via `http`. This is a common cors problem.
The issue starts it's journey right here:
https://github.com/statamic/cms/blob/9f324a57aba71fad79049012da138684da29210a/src/Http/Controllers/CP/PreviewController.php#L44
The Statamic URL Facade uses the request to determine the root url:
https://github.com/statamic/cms/blob/9f324a57aba71fad79049012da138684da29210a/src/Facades/Endpoint/URL.php#L245
If calling `root` directly on the …

[4.x] Use Laravel url helper instead to get the site url

---

resources/js/bootstrap/fieldtypes.js
resources/js/bootstrap/mixins.js

This PR registers/exports some Vue components related to sets and field conditions, so they can be used by addons. They are:
* The `<set-picker>` component
* The `<set-field>` component
* The `FieldConditions` mixin

[4.x] Register/export set and field related components

---

config/forms.php
src/Forms/Exporters/CsvExporter.php

This PR adds a config setting `statamic.forms.csv_use_handles_for_headings` which when false uses the fields `display` value instead of the `handle` when exporting CSV submissions.

[4.x] Add config setting so CSV submission export can use field `display` instead of `handle`

---

src/Contracts/Structures/CollectionTree.php
src/Contracts/Structures/NavTree.php
src/Stache/Repositories/CollectionTreeRepository.php
src/Stache/Repositories/NavTreeRepository.php
src/Structures/CollectionStructure.php
src/Structures/CollectionTree.php
src/Structures/Nav.php
src/Structures/NavTree.php

As reported over in https://github.com/statamic/eloquent-driver/issues/198 if you have a split config of file based collections and eloquent collection trees then creating a new collection (tree) throws an error. I've worked around this [here](https://github.com/statamic/eloquent-driver/pull/199) but it's not the ideal solution.
Instead we should have a contract for `CollectionTree` and bind it to the repository in the same pattern used elsewhere. Would you consider this a breaking change? Im not sure.
While we're at it, we should do the same for `NavTree` as the same issue will exist there.

[4.x] Create CollectionTree and NavTree contracts and bindings

---

src/Fieldtypes/Date.php
tests/Fieldtypes/DateTest.php

The Date Fieldtype is flexible and you can decide the format, in which you want to save dates.
In some edge cases, the end format won't represent the end of the day, as some formats to save seconds by default, which might lead to unexpected results.
This PR does set the datetime to the end of the day, before converting it to the end of day. 
In our cases it's important, as we work with a Unix timestamp (Format U). In that case, the start and end range are different, event if it's the same day. 
Example
```
// Format `y-m-d`
// start => 30.08.2023
// end => 30.08.2023
// Format `U` actual behaviour
// start => 1693346400 // hour: 0, minute: 0, seconds: 0
// end => 1693346400 // hour: 0, minute: 0, seconds: 0
// Format `U` with PR
// start => 1693346400 // hour: 0, minute: 0, seconds: 0
// …
```

[4.x] Set end range date to end of day

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

I noticed that when you have a Bard field inside a Bard field you get this error in the console on page load:
This is caused by the `document.querySelector()` call in the mounted method. It looks as though that can somehow fire before the label has actually been added to the DOM, resulting in the query returning null. This doesn't seem to happen for top-level Bards.
This PR fixes it by delaying that call until the next tick.

[4.x] Fix Bard inside Bard addEventListener error

---

resources/js/components/fieldtypes/ListFieldtype.vue

Focusing a list field type was causing an infinite loop and maximum call stack js error, highlighted by #8672.
The fix is to not focus inside editItem when called by a focus state.
I opted for this approach after I tried checking the element focus state using document.activeElement but I couldn't get it to work consistently.
Fixes: https://github.com/statamic/cms/issues/8672

[4.x] Fix list item focus infinite loop

---

resources/js/components/fieldtypes/replicator/SetPicker.vue

[4.x] Make the set picker an odd height so you'll see overflowing items better.

---

src/Forms/Fieldtype.php

Closes #3809
Works fine with 1, more, or no max_items, as one would expect.

[4.x] Stop forcing max_items: 1 on form fields

---

resources/js/components/inputs/relationship/Selector.vue

Closes https://github.com/statamic/cms/issues/8631
With this we could prevent the selection from being removed after filtering. Maybe this is also a solution for you?

[4.x] Prevent deletion of selection when filtering (Relationship-Fieldtype)

---

src/Fieldtypes/Text.php

Autocomplete is an excellent addition by Jeroen, this was actually on my todo list after we missed it on a recent project.
For some sites I also need to be able to set autocomplete='off' however, since otherwise the browser will automatically guess depending on the field name, which can be annoying.
Also added 'on' just to complete the spec, not sure what use cases there are for that one.

[4.x] Add 'on' and 'off' autocomplete values to text field

---

config/users.php
src/Http/Controllers/UserController.php
tests/Tags/User/RegisterFormTest.php

This PR adds a config `statamic.users.registration_form_honeypot_field` which when not null will be checked as a honeypot on the `user:register` submission.
Closes https://github.com/statamic/ideas/issues/1043

[4.x] Allow for a honeypot field on `user:register` tag

---

src/Tags/Cache.php
src/View/Antlers/Language/Runtime/GlobalRuntimeState.php
src/View/Antlers/Language/Runtime/LiteralReplacementManager.php
src/View/Antlers/Language/Runtime/NodeProcessor.php
src/View/Antlers/Language/Runtime/StackReplacementManager.php
src/View/Cascade.php
src/View/State/CachesOutput.php
src/View/State/StateManager.php
tests/Tags/CacheTagTest.php

This PR fixes #8399 by also caching the string results of `section` and `stack` tag calls when used inside `cache` tags.
It does this by checking if the tag implements a new `CachesOutput` interface (to help make the implementation a bit more generic - anyone wanting to leverage this feature can implement this on their own. Implementors would be responsible for implementing similar logic to the Core cache tag, however).
Cached section/stack content is stored as a new cache entry. The key of this is based off the existing cache key logic.

[4.x] Caches sections and stacks when used inside cache tags

---

src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Sandbox/VariableAssignmentTest.php

This PR replaces #7635  and fixes #7633 by introducing an internal concept of protected scopes. Protected scopes will not have their values pushed up the Cascade, and their values will not be pushed down into further partial/template scopes (there is no user-land way to influence what is considered a protected scope).
With these changes, manual updates to the `view` array will be tossed away once the current template/partial goes out of scope.
Partials/templates having the frontmatter merged in from parent templates/partials has not been changed.

[4.x] Antlers: Protections around updating view values 

---

resources/lang/en/messages.php
src/Http/Controllers/CP/Fields/FieldsController.php

Just noticed there's no toggle for `replicator_preview` in the Blueprint editor.
This PR adds it.

[4.x] Add replicator_preview toggle to Blueprint editor

---

src/Query/EloquentQueryBuilder.php

I've been trying to work out the best approach for issues like https://github.com/statamic/eloquent-driver/issues/137 and https://github.com/statamic/cms/issues/8227 which come from JSON fields being case sensitive in MySQL. 
The only approach I can find that is not database engine specific seems to be `LOWER()`-ing the fields, but that may not work for all languages, accents etc. 
For want of a better solution, we should run with it for now.
This will only fix ->where('x', 'like', 'y%') type queries, it wont affect straight ->where() or ->whereIn() etc
Fixes: https://github.com/statamic/cms/issues/8227 https://github.com/statamic/eloquent-driver/issues/137

[4.x] Make eloquent 'like' queries case insensitive

---

src/Stache/Query/Builder.php
tests/Data/Entries/EntryQueryBuilderTest.php

On query builder, when using the `whereMonth` method to check for equality in month, it currently only works with double-digit months.
This PR fixes the issue.
```PHP
// Before:
Entry::query()->whereMonth('date', 11)->get() // works
Entry::query()->whereMonth('date', 9)->get(); // does not work (does not provide the right result)
// After:
Entry::query()->whereMonth('date', 11)->get() // works
Entry::query()->whereMonth('date', 9)->get(); // works
```

[4.x] Fix single digit month not working on whereMonth

---

src/Query/Builder.php
tests/Data/Taxonomies/TermQueryBuilderTest.php

This pull request adds an `orderByDesc` method to the Statamic Query Builder, after I expected it to exist but it didn't (a method with the same name [exists in the Eloquent query builder](https://github.com/laravel/framework/blob/89171a265479075baf79a52ef06332a94f562ee5/src/Illuminate/Database/Query/Builder.php#L2338)).
`orderByDesc` simply uses the existing `orderBy` method under the hood. It's literally a really simple wrapper around it.
I've added a test to the `TermQueryBuilderTest` to cover it as that's the only test I could find that tests the existing `orderBy` method.

[4.x] Add `orderByDesc` method to the query builder

---

resources/js/components/users/Listing.vue

Fixes #8732 
It looks like a lot has changed, but the bulk of it is just indentation changes, due to wrapping `<data-list-table>` with a new `<div>`.

[4.x] Apply overflow styling to user listing

---

resources/js/components/revision-history/Preview.vue

With this PR, the title is a computed property and makes the title optional.
In our case we use custom revisions, we only load the needed data to show the listing below (no title required).
As soon as you click on a revision, the data of that revision will be loaded. The loaded data can first be available, after the component has been created. The title is expected though at creation time, which does lead to an error.
The simple solution below fixes it, as the title is not required at creation time.
We are using the following serverside workaround at the moment, which does work but feels a little to special :-)
```php
(new Revision())
->id($content['name'] ?? $entryId)
// More stuff
->attributes(['data' => ['title' => '']]); // As the frontend requires a title.
```

[4.x] make title in revision preview computed

---

tests/Tags/Concerns/RendersFormsTest.php
tests/Tags/Form/FormCreateTest.php
tests/Tags/User/ForgotPasswordFormTest.php
tests/Tags/User/LoginFormTest.php
tests/Tags/User/PasswordFormTest.php
tests/Tags/User/ProfileFormTest.php
tests/Tags/User/RegisterFormTest.php

Laravel 10.24.0 introduced some test failures due to another attribute being added to the csrf_field output.
See https://github.com/laravel/framework/pull/48371
This wasn't really a breaking change on their part. We should have just been asserting that csrf_field was output in html rather than checking the explicit html.

[4.x] Fix CSRF field related test failures

---

src/Stache/Repositories/TermRepository.php
tests/Feature/Taxonomies/TermEntriesTest.php

This may be too simplistic a fix, but to get the correct entry count raised in https://github.com/statamic/cms/issues/4493 we could just make sure we query by the default locale.
Fixes https://github.com/statamic/cms/issues/4493

[4.x] Use default slug to get taxonomy entries count

---

src/Query/EloquentQueryBuilder.php

I introduced a bug in https://github.com/statamic/cms/pull/8243/files see:
https://cdn.discordapp.com/attachments/1153390699161587823/1154476994873012255/image.png
The column needs wrapped so that each eloquent grammar can make it work for their appropriate underlying engine.
Sorry.

[4.x] Wrap eloquent builder like column

---

src/StaticCaching/Cachers/FileCacher.php

This PR makes Livewire 3 work with full-measure static caching. It's the equivalent of https://github.com/statamic/cms/pull/7894 which made Livewire 2 work with full-measure static caching.

[4.x] Fix static caching with Livewire 3

---

src/Actions/Impersonate.php

As [reported here](https://github.com/statamic/cms/issues/8761) impersonate is allowing you to impersonate yourself when eloquent users are used.
Lets fix this by checking for an id() match only.
Fixes: https://github.com/statamic/cms/issues/8761

[4.x] Impersonate should check on id() not full class

---

src/Entries/Entry.php

When creating alternate `preview_targets` in a setup where the site domain differs from the CMS (e.g. in headless mode) we need access to the absolute URL of the site in order to build a more complex preview structure besides the existing `permalink`, like for an overview page. In the current setup the page would need to be hardcoded:
```
preview_targets:
-
label: Entry
url: '{permalink}'
-
label: Overview
url: 'http://page.de{mount}'
```
With the proposed change it would be a bit more elegant:
```
preview_targets:
-
label: Entry
url: '{permalink}'
-
label: Overview
url: '{site}{mount}'
```

[4.x] Add site to resolvePreviewTargetUrl options

---

src/Entries/Entry.php

The save event in Entries does not honour the withEvents setting (set by saveQuietly) when saving descendants.
Fixes: https://github.com/statamic/cms/issues/8785

[4.x] Propagate save withEvents to the direct descendents on entry save

---

resources/views/extend/forms/fields/text.antlers.html

Addition to PR https://github.com/statamic/cms/pull/8623: implemented autocomplete in the default text-field template for forms
Sorry I forgot to do this the first time! 🥴

[4.x] Use 'autocomplete' attribute in the default Text-template

---

src/Fieldtypes/Entries.php

Removes the 'to-do' in the sorting and defers to the sort preferences from the first collection in the request.
Closes https://github.com/statamic/cms/issues/8723

[4.x] Default to first collection's sort config in entries fieldtype

---

resources/js/components/data-list/FieldFilter.vue

I noticed when working on the PR that comes next that filters in listing views only run when all fields have a value, even those that are hidden.
This PR updates the logic to only check for values on visible fields.
Thanks to @jacksleight for showing me where to look on this one.

[4.x] Ensure we only check that visible fields are filled in filters

---

src/Query/Scopes/Filters/Fields/Date.php

This PR adds the ability to filter dates by a range, not just an before or after value.
Requires: https://github.com/statamic/cms/pull/8778
Closes: https://github.com/statamic/ideas/issues/1027

[4.x] Date range filter

---

resources/lang/en/messages.php

This tiny tweak originated in **[a Discord chat with Erin & Sam](https://discord.com/channels/489818810157891584/1159256773312655372/1159259733870518302)**. Currently, the `fields_default_instructions`—which is used for the helper text below `Default Value` on field definitions—reads as:
> Set the default value.
This PR tries to put a lil more meat on dem bones. 🍖 Proposing a change to:
> Set a default value. Inserted whenever this field is empty, on **all** publishable forms.
This is definitely a subjective thing, so won't hurt my feelings if you all decide to reject or edit...but this has bit me a couple of times, with how the setting actually works. Copying in a bit of that Discord convo linked above, for more context:
I tend to think of **_default_** as more of a _UI …

[4.x] Clarify default field instructions/helper-text

---

src/Tags/Collection/Entries.php

At the moment, the `collection:next`/`prev` tags only work on dated or orderable collections. "Orderable" collections are ones with a structure set to max depth of 1.
This was because the "order" was ambiguous for multi-depth collections. A while ago in #4883 we made the decision for it to just assume the order is depth-first (how it looks if you read down the page while looking at the tree).
We never looped back and added support for that within the collection:next/prev tags.
This PR removes that requirement. If you want to sort by `order`, go for it. You can technically even sort a dated collection by order if you add an `order` field to each entry.
The default sort order of a multi-depth structured collection is `title`. Since we don't want to make it a breaking change, to get these …

[4.x] Remove requirement of orderable collection from next/prev tags

---

resources/js/components/fieldtypes/ToggleFieldtype.vue
resources/lang/en/fieldtypes.php
src/Fieldtypes/Toggle.php

This PR adds an optional `inline_label_when_true` field to the Toggle fieldtype's config, allowing for a separate inline label when the value of the Toggle is truthy. This is non-breaking/backwards compatible, as the existing `inline_label` is unchanged and used as the fallback within the Vue component. Here's what this change looks like, in each possible scenario:

[4.x] Feature: Add inline label for Toggle when truthy

---

config/cp.php
src/Imaging/Manager.php

I'm working on a project with a custom assets fieldtype that displays the preview image larger than 400px, so the default `small` thumbnail looks a bit fuzzy. The only alternative currently is to display the original file, but that could be huge.
This PR allows you to add extra CP thumbnail presets, for use by custom CP extensions/addons.
It does allow you to override the default `small` preset as well, as I couldn't really see any reason to prevent that. That could be useful if you just needed a slightly larger thumbnail and don't want to double up.
The config could make sense in either `assets` or `cp`. I went for `cp` but can change that if necessary.

[4.x] Support additional CP thumbnail presets

---

src/Assets/Asset.php
src/GraphQL/Types/AssetType.php
tests/Feature/GraphQL/AssetTest.php

Having terms on an Asset causes an almost an identical issues on Graphql (`User Error: expected iterable, but did not find one for field`) as was solved in #6379.
While I'm not entirely sure this is the correct approach I added the `ResolvesValues`-Trait to `Asset.php` and modified the resolve function. Otherwise simply adding the code ` if ($value instanceof Builder) { $value = $value->get();  }` in the resolver will also fix the issue.

[4.x] GraphQL: Fix assets not resolving query builders

---

src/View/Antlers/Language/Nodes/AntlersNode.php
src/View/Antlers/Language/Parser/AntlersNodeParser.php
src/View/Antlers/Language/Runtime/NodeProcessor.php
tests/Antlers/Sandbox/VariableAssignmentTest.php

This PR improves an over-aggressive internal tag parameter check. This internal check looks for specific tag parameters that will modify the resulting scope in some way that causes the current renderer to be unable to handle the tag's results.
With the current over-aggressive check, the following simplified example:
```antlers
{{ _the_count = 1; }}
{{ collection:articles limit="3" }}
{{ _the_count += 1; }}
Entry: {{ _the_count }}
{{ /collection:articles }}
```
would produce the following output:
```
Entry 1
Entry 1
Entry 1
```
The current check is over-aggressive since it will pass if the tag contains any parameter with the same name as an existing modifier. The refactored check will only pass if the tag has any of the following parameter names:
* as
* scope
* handle_prefix
The …

[4.x] Antlers: Improves custom variable assignment inside tags

---

src/Yaml/Yaml.php
tests/Yaml/YamlTest.php

Solves an issue where you cannot save localized entries in a multisite when your content field is an empty replicator.

[4.x] Fix error when saving entry where content is empty array

---

resources/css/components/fieldtypes/section.css

Small bug from #8807; I had the `mt-0` in `last-child`...should have been `first-child`. **Sorry about that!** 
Blaming a hole in my kitchen sink—gave a false-positive of sorts, since the `last-child` was also the `first-child` in that example.

[4.x] Bug: Fix Section fieldtype first-child's top-margin

---

resources/js/components/fieldtypes/bard/LinkToolbar.vue
resources/js/components/fieldtypes/bard/LinkToolbarButton.vue
src/Fieldtypes/Bard/LinkMark.php

This PR adds the following options to the Bard link panel:
* Email Type - Simplifies linking to `mailto:` URLs
* Phone Type - Simplifies linking to `tel:` URLs
* Relationship Field - Allows customisation of `rel` attributes per link
The relationship field exposes the `rel` value that's already generated by the field configuration, allowing you to add additional values and customise the default ones. This is the same way the open in new window field works.
The open in new window field is hidden and unset for email and phone links as I don't _think_ it would be relevant given that these links would always open in another application. Can change that if someone knows otherwise?
One UI thing I'm not sure about is how well the five type tabs will fit with other locales? I already had to bump …

[4.x] Bard link email, phone and relationship options

---

resources/js/components/fieldtypes/Fieldtype.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
resources/js/components/fieldtypes/replicator/Set.vue

When you have a lot of replicator sets the initial render speed of the page can be very slow (see video below). I've been looking into this and think I've found the cause and a good fix, but first some background:
1. When a replicator is loaded `replicator-preview-updated` events are fired for every field within each set, which then calls the `Fieldtype.updateMeta()` method and updates the publish container.
2. There used to be a bug (https://github.com/statamic/cms/issues/5081) where only the last set would show a preview on page load. 
3. As far as I can tell this bug was caused by a race condition. Loads of `replicator-preview-updated` events would all be fired at once, but the publish container updates asynchronously so each subsequent event would overwrite the update from the …

[4.x] Improve initial render speed of replicators with many sets

---

resources/js/components/publish/HasHiddenFields.js
resources/js/components/publish/Values.js

This is a non-breaking companion  to https://github.com/statamic/cms/pull/8684.
Bard data is still stored as encoded JSON strings, the only change this makes is instead of decoding/encoding all Bard fields for every preserved Revealer field, this will decode once at the start and then encode once at the end. This makes a big difference when your entry data contains a lot of Bard and Revealer fields.
I've tried to implement this in the most minimal way without affecting any of the Values object's existing behaviour. I've added a new `mergeDottedKeys` method (there's probably a better name) in the Values object which will set multiple values at once based on the provided list of dotted keys. And updated HasHiddenFields to use this.

[4.x] Improve post-save performance with many Bard and Revealer fields

---

src/View/Antlers/Language/Runtime/GlobalRuntimeState.php
src/View/Antlers/Language/Runtime/RuntimeParser.php
src/View/View.php
tests/Antlers/Runtime/ParserIsolationTest.php

This PR closes #8772. Sharing of custom variables would previously work if you executed a tag towards the end of the template, but sharing variables with the layout in this way was always unintended behavior.
This seems to come up quite a bit, so this PR resolves this by automatically sharing custom variables with the layout, without needing to resort to hacks/workarounds. Only variables declared _inside_ the template file will be shared with the layout.

[4.x] Antlers: Adds first-class support for sending custom variables to the layout

---

.github/workflows/tests.yml

This reverts #8843 just so the test suite continues running for other PRs.
We'll sort out PHP 8.3 for real in #8845.

[4.x] Revert adding PHP 8.3 tests

---

resources/js/components/fieldtypes/replicator/Set.vue

Fixes https://github.com/statamic/cms/issues/8839
The reason for this issue is that replicator passes the previews down to each set as a prop, but when the page loads and all fields trigger an update the prop isn't updated fast enough and each subsequent update wipes out the previews from the previous ones. The old `setTimeout` approach that the referenced PR changed avoided this.
The issue isn't specific to text fields, it could happen for any field, it's just that the last field to initialise would always win and text fields are so simple they usually initialise first. I replicated the same issue with toggle fields, and text fields that are last in the set.
This PR fixes it by storing a copy of the previews in the set component, so that it always has a complete set rather than relying …

[4.x] Fix missing replicator set previews

---

src/Validation/UniqueUserValue.php
tests/Validation/UniqueUserValueTest.php

Sometimes it's necessary to pass the column the `unique_user_value` validator validates on. For example when using Livewire Form Objects where the field handles get prefixed by `form.`.
Closes https://github.com/statamic/ideas/issues/1067.

[4.x] Allow overwriting the column for `unique_user_value` validation

---

resources/js/components/navigation/View.vue

This pull request fixes an issue I spotted where the 'Save Changes' button on navigations would take two clicks to clear the browser dirty state and disable the button.
Fixes #8859.

[4.x] Fix navigation 'Save Changes' button state

---

src/Fields/Field.php
src/Forms/Tags.php
src/Tags/Concerns/RendersForms.php
tests/Fields/FieldTest.php

The `RendersForms` concern handles the rendering of fields. 
However within a field's context during render, the field has no knowledge of the form it is being used on.
This PR updates the `getRenderableField` method of `RendersForms` to add the form to the Field (only if the `form` method exists).
This can be useful to help give the fieldtype rendering context as to what form it is belonging to.
For a custom fieldtype, developers can use `$this->field()->form()` within their fieldtype to get the form instance.

[4.x] Add form reference to field during render

---

src/Auth/User.php

As [reported here](https://github.com/statamic/cms/issues/8868) when you specify multiple guards copying the password reset token throws an error.
This PR fixes that by applying the same logic used elsewhere and checking if its an array and selecting the cp guard.
Closes https://github.com/statamic/cms/issues/8868

[4.x] Default to using the CP broker when multiple are available

---

resources/lang/en/fieldtypes.php
src/Fieldtypes/Entries.php

Our use case is that we have an entries field type hooked up to several collections, and because it's multi-site, when we're on the Arabic site, we can't actually find the entry we need because all we can search on is title, which of course, are in arabic.
We'd love to be able to search by slug, and have a search index that includes slug so we can do that in the English site.
However, when multiple collections are configured on an Entries fieldtype, on a 'like' query on the title is performed.
This PR adds a `search_index` to the config then uses it, if it exists.

[4.x] Improve Entries fieldtype search index logic, and add option to define an explicit one.

---

resources/js/components/inputs/relationship/Item.vue
resources/js/components/live-preview/LivePreview.vue

This pull request fixes an issue with Live Preview when updating a relationship item (entry / taxonomy term / etc) that it wouldn't refresh the Live Preview.
Closes #1975.

[4.x] Refresh Live Preview when relationship items are updated

---

src/Forms/Email.php
src/Forms/SendEmails.php
tests/Forms/EmailTest.php

This pull request allows for using Global Set variables in form configs.
Closes #2635.
For example you could have a "Company Information" global with Name & Email fields. 
Then, when configuring form emails, you'd be able to reference the global set data just like you would in a normal Antlers template: `{{ company_information:email }}`

[4.x] Allow using Global Set variables in form email configs

---

resources/js/components/fieldtypes/LinkFieldtype.vue

On small screens the url subfield of the link field type gets comically small:
To resolve this we can decrease the width of the link type so that it better fits any of the current options in it (ie. URL, Entry, Asset):

[4.x] Decrease the width of the link type selector

---

resources/js/plugins/slugify.js

This pull request fixes a small issue where single smart quotes (`’`) weren't being stripped out when slugifying a string.
Example title: `GTA Online’s latest news: “huge map”`
Fixes #8844.

[4.x] Ignore single smart quotes when slugifying string

---

src/Events/RevisionSaving.php
src/Revisions/Revision.php

As detailed [here](https://github.com/statamic/ideas/issues/1028) you can't currently stop a Revision from saving, which isn't ideal if you want to add some extra logic.
So this PR adds a `RevisionSaving` event, similar to `EntrySaving`.
Closes https://github.com/statamic/ideas/issues/1028

[4.x] Add `RevisionSaving` event

---

src/Http/Resources/CP/Entries/Entries.php

This pull request fixes an issue on the Entry Listing Table where the "Status" column is placed *before* the title & slug columns when resetting columns on the entry listing table.
Initially, when you load the Entry Listing Table without any preferences, it'll get all the fields set as visible. Then, when you "Reset" the columns in the `ColumnPicker` modal, it'll set the columns to those which are visible by default (`defaultVisibility`) and order by them by the column's `defaultOrder` setting.
This PR makes it so the "Status" column will be displayed as the last column in this scenario, fixing #8285.
Fixes #8285.

[4.x] Fixed issue when resetting columns on Entry Listing Table

---

src/CP/Navigation/Nav.php
tests/CP/Navigation/NavTest.php

This PR adds ability for an addon to remove specific core nav item children more easily. For example, in our [Shopify rad pack addon](https://github.com/statamic-rad-pack/shopify), @ryanmitchell is wanting to remove the `Products` collection item from `Collections`, because that item is being listed as a child of the `Shopify` nav item instead.
```php
Nav::extend(function ($nav) {
$collectionsNav = $nav->content('Collections');
$children = $collectionsNav
->resolveChildren()
->children()
->reject(function ($item) {
if (in_array($item->display(), ['Products', 'Variants'])) {
return true;
}
});
$collectionsNav->children($children);
});
```
```php
Nav::extend(function ($nav) {
$nav->remove('Content', 'Collections', 'Products');
$nav->remove('Content', 'Collections', 'Variants');
});
```
- …

[4.x] Add helper arg for addons to easily remove child item in core nav

---

resources/lang/en/validation.php
src/Fieldtypes/ButtonGroup.php
src/Fieldtypes/Select.php
tests/Fieldtypes/ButtonGroupTest.php
tests/Fieldtypes/SelectTest.php

This pull request adds validation to the `options` config field on the Select & Button Group fieldtypes to ensure keys are always entered.
By validating that keys exist, we can ensure that there's no weird arrays like this get saved:
```yaml
options:
option-value: 'Option Text'
another-option-value: 'Another Option Value'
'': Hallo
Wat: null
```
Closes #346.

[4.x] Validate that Select & Button Group options have keys

---

resources/js/components/fieldtypes/TagsFieldtype.vue

This pull request adds support for paste events in the Taggable Fieldtype so you can simply paste a string like `one, two, three` into the input and it'll split it up into separate tags.
I've removed the `v-if="config.multiple"` check since that setting doesn't exist on this fieldtype and I needed to hook into the `<input>` for the paste event.
Closes #1649.

[4.x] Support paste events in Taggable Fieldtype

---

resources/js/components/collections/Listing.vue
resources/js/components/collections/View.vue
resources/js/components/data-list/Table.vue
resources/js/components/globals/PublishForm.vue
resources/js/components/inputs/relationship/Item.vue
resources/js/components/navigation/View.vue
resources/js/components/taxonomies/Listing.vue
resources/js/components/user-groups/PublishForm.vue

As noted in https://github.com/statamic/cms/issues/8913 there was a missing translation on the collection list.
I also noticed them in the relationship and data list components so I've translated them there too.
Closes https://github.com/statamic/cms/issues/8913
Closes #3638

[4.x] Fix missing translation of some user defined strings

---

src/Tags/Collection/Entries.php
src/Tags/Concerns/QueriesConditions.php
tests/Tags/Concerns/QueriesConditionsTest.php

This pull request attempts to improve the handling of empty values when using the `{{ collection }}` tag.
For example, when you're using the `{{ collection }}` tag and filtering with query parameters, if any of those query params don't have a value, the query will return no results which often times isn't what you want.
Instead, you'd want that particular filter to be ignored unless a value is present.
```antlers
<div>
<h2>Filter articles:</h2>
<form action="{{ current_uri }}" method="get">
<select name="author">
<option value="">All users</option>
{{ users }}
<option value="{{ id }}" {{ if get:author == id }} selected {{ /if }}>{{ name }}</option>
{{ /users }}
</select>
<button type="submit">Search</button>
</form>
<ul>
{{ collection:articles author:is="{ get:author }" }}
<li><a href="{{ …
```

[4.x] Handle empty values in collection tag filters

---

resources/js/components/entries/PublishActions.vue

I noticed this visual glitch on a site of ours - when you click 'save' the revision publish action fields were still visible below the loading indicator. This PR means they are now hidden when saving.
Closes https://github.com/statamic/cms/issues/8798

[4.x] Hide publish action fields when saving

---

resources/js/components/inputs/relationship/InlinePublishForm.vue
src/Policies/EntryPolicy.php

This pull request improves how unauthorised responses are handled with the Inline Publish Form that's part of the Relationship Fieldtype.
Previously, when you opened an item that you weren't authorized to edit, the stack would show as loading but nothing would actually happen. It would stay "loading" forever.
Now, the `InlinePublishForm` will handle the case where the user is unauthorized to edit the item and display a toast message.
Fixes #1435.

[4.x] Handle unauthorized response in Inline Publish Form

---

src/Actions/Delete.php
src/Actions/DeleteMultisiteEntry.php

This PR prevents root entries from being deleted in listing views by not letting the delete actions be visible to these entries.
Before: (home is my root entry)
After: 
Closes https://github.com/statamic/cms/issues/8794

[4.x] Prevent root entries being deleted in listing view

---

resources/js/plugins/slugify.js

This pull request fixes a small issue with the `slugify` function:
* If you enter `Block - Hero` as a title
* `slugify` would generate `block_-_hero` as the slug
* With this fix, `slugify` will generate `block_hero` as the slug
Fixes #8749.

[4.x] Fix slugify when using hyphens surrounded by spaces.

---

src/Fieldtypes/Link.php
src/Fieldtypes/Link/ArrayableLink.php
src/Routing/ResolveRedirect.php
tests/Feature/GraphQL/Fieldtypes/LinkFieldtypeTest.php
tests/Fieldtypes/LinkTest.php
tests/Routing/ResolveRedirectTest.php

We use the `Link` fieldtype, and we often want to use the `title` of whatever we're linking to. Right now the `link` field augments to the url so the `title` is lost.
This change makes the field "arrayable" so you can now do `{{ link_field:title }}`.

[4.x] Make Link field arrayable

---

src/Console/Commands/ImportUsers.php

It seems MySQL 8 returns CHAR, instead of string for the column type, so we should allow that.
(Maybe its worth removing the column type check altogether?)
Also updated it to not assume id, but use $model->getKey()
Fixes: https://github.com/statamic/cms/issues/8907

[4.x] Remove schema check on import users command

---

src/Tags/Collection/Entries.php
tests/Tags/Collection/CollectionTest.php

This pull request fixes an issue where the `{{ collection:previous }}` and `{{ collection:next }}` tags would ignore other entries published on the same date. 
For example, say you had the following entries:
* 1st January: Article A
* 5th February: Article B
* 5th February: Article C
* 7th March: Article D
When you visited the "Article C" entry, the `{{ collection:previous }}` tag would have returned "Article A" as the previous entry and "Article B" would have been ignored.
Similarly, when you visited the "Article B" entry, the `{{ collection:next }}` tag would have returned "Article D" as the next entry and "Article C" would have been ignored. 
This PR fixes this issue by querying both entries _before/after the current entry's date_ **AND** those _on the same date where the title is …

[4.x] Fix entries on the same date being ignored by collection previous/next tags

---

resources/js/components/assets/Browser/Browser.vue

Fixes https://github.com/statamic/cms/issues/8922.
The `Upload` and `Create Folder` buttons were showing in the Asset Browser for users who don't have permission to do said actions.
Creating folders in an asset container relies on the `upload {container} assets` permission and not the `configure asset containers` permissions [see here](https://github.com/statamic/cms/blob/4.x/src/Policies/AssetFolderPolicy.php#L9-L18).
Also disables the uploader component as a nice side-effect so it doesn't confuse users seeing the ability to drag and drop files.

[4.x] Fix permissions for asset upload and folder creation buttons in CP

---

resources/js/components/fieldtypes/SlugFieldtype.vue

This pull request fixes an issue in the Slug Fieldtype. 
When used inside a Replicator Set, the Slug fieldtype previously couldn't "target" sibling fields, only fields in the root of the publish form.
Fixes #8881.

[4.x] Slug Fieldtype: Allow targeting sibling fields inside a replicator

---

src/Entries/Collection.php
tests/Data/Entries/CollectionTest.php

This pull request makes a collection's mounted entry available when a `Collection` is augmented.
This will allow you to access a collection's mounted entry when on an entry "show" page:
```
Mounted to: <a href="{{ collection:mount:url }}">{{ collection:mount:title }}</a>
```
Fixes #3625.

[4.x] Add `mount` to augmented collection

---

resources/js/components/fields/Settings.vue

This pull request fixes an issue where the "Always Saved" toggle didn't save when it was set on a linked/reference field.
Fixes #8277.

[4.x] Fix "Always Save" toggle not being saved when used on linked field

---

src/Entries/Collection.php

This pull request fixes an issue with #8928 where the listing table of a mounted collection would fail to load due to an infinite loop.

[4.x] Fix infinite loop on listing table of mounted collection

---

src/Modifiers/CoreModifiers.php

This PR allows you to pass arrays to the `wrap` modifier. So you can do:
```antlers
{{ test = "one two" }
{{ test | wrap('span') }}
{{ test | explode(' ') | wrap('span') | join(' ') }}
```
Resulting in:
```html
<span>one two</span>
<span>one</span> <span>two</span>
```

[4.x] Support arrays in wrap modifier

---

src/Providers/AppServiceProvider.php

This pull request attempts to fix an issue where Statamic's middlewares for the `statamic.web` group would not get used when the developer pushes their own array of middlewares. 
This PR ensures any custom middlewares provided for the `statamic.web` group in `app/Http/Kernel.php` are merged with Statamic's middlewares, rather than overriding them.
Fixes #8453.

[4.x] Fix `statamic.web` middleware not being merged

---

src/Entries/Collection.php

This pull request prevents fields from being ensured on entry blueprints if they already exist. Without this check, any changes you made to the config of any of the ensured fields would be overwritten the next time you save the blueprint.
I've added the check for this in `Collection` where we're ensuring them but happy to do something "upstream" (eg. in the `Blueprint` methods) if you'd rather go down that route.
Fixes #2743.

[4.x] Prevent ensuring fields on entries if they already exist

---

src/Fieldtypes/Relationship.php

This pull request fixes an issue with the Relationship Fieldtype where it would sometimes show a missing title on listing tables, when on multi-site.
Fixes #6605.
Fixes #8821.

[4.x] Fix missing title on relationship fields in multi-site

---

resources/js/translations/translator.js
src/Http/View/Composers/JavascriptComposer.php

This pull request ensures that when the site's primary locale is missing a translation then it'll fallback to using the site's fallback locale (configured in `config/app.php`).
Previously, when a translation was missing on the site's primary locale, the JavaScript translation method would display the translation key instead of a fallback which would be more useful.
Fixes #5610.
Closes #5277.

[4.x] Use translations from fallback locale when primary locale is missing translations

---

resources/js/components/sortable/SortableList.vue

This pull request fixes an issue with the `SortableList` component where it wasn't reacting to the `disabled` prop changing.
For example, when editing an entry's origin you could re-order assets. Then, if you switched to one of the entry's localizations, the assets field would still be re-orderable even though the value of the `disabled` prop was `true`.
This PR makes it so when `disabled` is `false`, the `Sortable` stuff is loaded in, then when it changes to `false` it'll be destroyed (& vice-versa).
Fixes #8920.

[4.x] Fix SortableList not reacting to disabled prop changes

---

src/Fieldtypes/Entries.php

This pull request makes a small quality-of-life improvement to the Entries Fieldtype. 
When a single collection is configured, the fieldtype will now show the user's preferred columns for the collection, rather than just the listable columns from the blueprint.
This means that the columns you configure on the collection's listing table will also be used when viewing its entries in the Entry Fieldtype stack selector.
Closes statamic/ideas#1052

[4.x] Entries Fieldtype: Use columns from preferences

---

src/Assets/AssetContainer.php
src/Assets/AssetContainerContents.php
src/Providers/FilesystemServiceProvider.php
tests/Assets/AssetFolderTest.php

Can we bind `AssetContainerContents` to the service provider so it can be extended by eloquent driver?
I would like to change it to use an eloquent AssetQueryBuilder rather than a stache/cache store, which is causing some issues with large amounts of assets (60k+).

[4.x] Bind `AssetContainerContents` to the service provider

---

resources/js/components/assets/Browser/CreateFolder.vue
resources/js/components/fieldtypes/TextFieldtype.vue
src/Actions/RenameAsset.php
src/Actions/RenameAssetFolder.php

This pull request adds a config setting to the `Text` fieldtype, removing the debounce when renaming assets & asset folders.
Fixes #8708.

[4.x] Remove debounce when renaming assets & folders

---

resources/js/components/fieldtypes/bard/Small.js
src/Fieldtypes/Bard/Marks/Small.php

Tiptap allows you to apply attributes to nodes/marks globally, which all the default extensions support.
This PR adds the same support to bard's `small` mark.

[4.x] Add global attribute support to bard's small mark

---

resources/js/components/users/ChangePassword.vue
resources/js/components/users/PublishForm.vue
resources/views/users/edit.blade.php
src/Http/Controllers/CP/Users/PasswordController.php
src/Http/Controllers/CP/Users/UsersController.php

This pull request hides the "Current Password" field when changing another user's password. The field will still be shown when users reset their own passwords. 
Closes #7395.
Regression from #7287.

[4.x] Don't require current password when changing another user's password

---

src/View/Antlers/Antlers.php
src/View/Antlers/Language/Parser/IdentifierFinder.php
tests/Antlers/Parser/IdentifierFinderTest.php

This PR adds an identifier finder utility which allows you to extract any potential variable usage within a template.
For example, in this template:
```antlers
{{ collection:articles :limit="the_limit" title:is="{foo} {bar}" }}
<a href="{{ url }}">{{ title }}</a>
{{ /collection:articles }}
```
```php
Antlers::identifiers($template);
// [collection, articles, the_limit, foo, bar, url, title]
```
A use case for this could be in the `nav` tag where we allow you to select specific fields for performance that you need in your template:
```antlers
{{ nav select="url|title" }}
<a href="{{ url }}">{{ title }}</a>
{{ /nav }}
```
We could potentially leverage the `identifiers` to automatically select fields rather than you having to manually specify them.

[4.x] Antlers identifier finder

---

src/Fieldtypes/Bard/ImageNode.php

Fix 'Call to a member function get() on null' where Bard asset doesn't exist.
If an asset used within a Bard image node does not exist (e.g. it has been deleted from the assets panel), currently a `Call to a member function get() on null` error will be thrown when Statamic attempts to fetch the alt text.
`Optional` only provides null safety for the first method call in the chain. Using the `?->` operator instead provides the desired effect.

[4.x] Fix error when getting alt on bard image when asset is missing

---

src/Actions/Impersonate.php

Closes #8970
When you impersonate, it would redirect to the control panel dashboard.
If the user's start page isn't the dashboard it might be a bit confusing, especially if they've made the conscious decision to hide the dashboard.
This PR will redirect to the control panel index, which redirects to the appropriate start page.

[4.x] Fix impersonation redirect

---

src/Modifiers/CoreModifiers.php

This pull request adds support for Bard fields to the `read_time` modifier. 
Closes statamic/ideas#94.

[4.x] Add Bard support to read_time modifier

---

resources/js/components/fieldtypes/ArrayFieldtype.vue

This pull request introduces a small improvement to the Array Fieldtype. It'll automatically populate the options values in the Array Fieldtype after entering the option key. 
This is useful when you're adding the keys for options in a Select fieldtype and the labels/values will pretty much be the same as the key, just with a capitalised initial character.
Closes statamic/ideas#1075.

[4.x] Auto-populate Array Fieldtype Options

---

src/Fieldtypes/Assets/DimensionsRule.php
src/Fieldtypes/Assets/ImageRule.php
src/Fieldtypes/Assets/MaxRule.php
src/Fieldtypes/Assets/MimesRule.php
src/Fieldtypes/Assets/MimetypesRule.php
src/Fieldtypes/Assets/MinRule.php
tests/Fieldtypes/AssetsTest.php

The custom asset validation rules are using statamic translations strings which makes sense inside the CP. But when outside the CP (eg a front end form) you may want to override them so they should look for the default lang validation strings.
Closes https://github.com/statamic/cms/issues/6254

[4.x] Only namespace asset validation attributes when on a CP route

---

resources/views/forms/show.blade.php

If there are no valid form exporters the hide submissions button shouldn't display. For example if you have an empty array in `statamic.forms.exporters`
This PR adds a check in the template to ensure the exporters collection is not empty.

[4.x] Hide export submissions button when there are no valid exporters

---

src/Auth/Eloquent/User.php
tests/Auth/Eloquent/EloquentUserTest.php

As [reported here](https://github.com/statamic/cms/issues/8978), adding super to an existing eloquent user would not save/persist.
This PR fixes that by setting it explicitly on saveToDatabase() and adds test coverage to ensure it works going forward.
Closes https://github.com/statamic/cms/issues/8978

[4.x] Fix super not saving on eloquent users

---

resources/js/components/SvgIcon.vue
resources/js/components/blueprints/Section.vue
resources/js/components/blueprints/Tab.vue
resources/js/components/fieldtypes/replicator/SetPicker.vue
src/Fieldtypes/Bard.php
src/Fieldtypes/Icon.php
src/Fieldtypes/Sets.php
src/Http/View/Composers/JavascriptComposer.php
src/Providers/CpServiceProvider.php
tests/Fieldtypes/SetsTest.php

This PR adds ability for user to customize bard/replicator set icons directory in a service provider.
Choose a different icon set for bard/replicator set icons...
```php
\Statamic\Fieldtypes\Sets::setIconsDirectory(folder: 'light');
```
Choose a different base directory altogether...
```php
\Statamic\Fieldtypes\Sets::setIconsDirectory(directory: resource_path('custom-icons'));
```

[4.x] Add ability to customize bard/replicator set icons directory

---

resources/views/forms/show.blade.php
src/Licensing/Outpost.php

This pull request attempts to prevent concurrent requests being made to the Outpost by implementing Laravel's [atomic locking feature](https://laravel.com/docs/master/cache#lock-driver-prerequisites).
Fixes #4194.

[4.x] Prevent concurrent requests to the Outpost

---

routes/cp.php
src/Http/Controllers/CP/Fields/FieldsetController.php

As [reported here](https://github.com/statamic/cms/issues/6826) adding a fieldset with a name already used redirected to a page that doesn't exist.
This PR fixes it by:
1. Preventing calls to the controller show method
2. Throwing an ajax error which the fieldset create page expects
Closes #6826

[4.x] Adding a fieldset with the same name should throw an error

---

resources/css/components/fieldtypes/bard.css
resources/js/components/fieldtypes/bard/BardFieldtype.vue

The goal of this PR is to improve the error reporting when Bard encounters invalid content:
Now friendlier and hopefully more useful messages are displayed for some of the most common issues, which could occur if a field's configuration is changed after content has been added or if content has been imported manually:
Possible messages are:
* Invalid content, [type] button/extension is not enabled
* Invalid content, nodes and marks must have a type
* Invalid content, text values cannot be empty
* Invalid content, text values must be strings
Other errors will just just output the usual "Something went wrong" message with the full error logged to the console:
Or in some instances it is possible for the editor to completely fail to load due to errors being thrown outside of the `onCreate` …

[4.x] Improve Bard invalid content error reporting

---

src/Http/Controllers/CP/Globals/GlobalsController.php
src/Http/Controllers/CP/Navigation/NavigationController.php

As [reported here](https://github.com/statamic/cms/issues/6826#issuecomment-1278088661), adding a globalset with the same handle overwrites the existing one. Thats not good.
This PR prevents that by checking if the handle already exists and throws an error if it does.

[4.x] Check if a globalset exists before adding one with the same handle

---

resources/views/taxonomies/blueprints/create.blade.php

As [reported here](https://github.com/statamic/cms/issues/6826#issuecomment-1278088661), adding a taxonomy blueprint with the same handle does not show an error message.
This PR prevents adds the error message to the display

[4.x] Show error when there is a duplicate taxonomy blueprint name

---

src/Http/Controllers/CP/Navigation/NavigationController.php

As [reported here](https://github.com/statamic/cms/issues/6826#issuecomment-1278088661), adding a navigation with the same handle overwrites the existing one. Thats not good.
This PR prevents that by checking if the handle already exists and throws an error if it does.

[4.x] Check if a navigation exists before adding one with the same handle

---

src/Http/Controllers/CP/Users/RolesController.php
src/Http/Controllers/CP/Users/UserGroupsController.php

As [reported here](https://github.com/statamic/cms/issues/6826#issuecomment-1278088661), adding a user roles and groups with the same handle does not show an error message and overwrites the existing role/group.
This PR checks if they already exist and shows an error message if they do.

[4.x] Check if user roles and groups exist before creating them

---

config/stache.php
src/Console/Commands/ImportUsers.php
src/Stache/ServiceProvider.php

This pull request fixes an error that some users would run into after moving users into the database. 
The error (`Call to undefined method Statamic\Auth\Eloquent\User::initialPath()`) happened due to the [`->initialPath()`](https://github.com/statamic/cms/blob/4.x/src/Stache/Stores/UsersStore.php#L49) method on the `UserStore` being called and trying to create a user in the Stache with the `User` facade.
However, by that point, the `UserRepository` contract had been switched to the Eloquent implementation away from the Stache implementation. It's only the Stache implementation that has an `initialPath` method.
This PR fixes that issue by preventing the users Stache store from being registered if users are currently powered by the database (or any other non-file user repository). It also …

[4.x] Prevent registering the Users Stache Store when users are stored in a database

---

src/StaticCaching/NoCache/Tags.php
src/View/Antlers/Antlers.php

Fixes #9001
The nocache tag intelligently grabs the appropriate fields you'll need in the template in #8956.
However since it uses a runtime parser feature to do it, it throws an error when you're using the regex parser.
This PR fixes that by falling back to the old less-performant behavior when you're using the regex parser.

[4.x] Fix nocache tag when using the regex antlers parser

---

resources/js/components/inputs/relationship/Item.vue

Sometimes it's useful to open related items in a separate tab, rather than the stack overlay. This PR adds an `href` attribute to relationship item links, allowing you to open them in a new tab via the browser's right-click context menu.

[4.x] Add `href` attribute to relationship item links

---

src/Http/Resources/CP/Concerns/HasRequestedColumns.php

This pull request fixes an error that would only occur when using Statamic, on Laravel Vapor, with a AWS function URL.
After some digging and talking with Vapor support, I managed to figure out that AWS function URLs parse query parameters like `title,status,slug` as an array, instead of a string like they'd be parsed anywhere else.
This happens due to the way that AWS maps the requests internally. This isn't an issue for projects with custom domains or vanity domains where Vapor is able to workaround the issue.
Fixes #6868.

[4.x] Fix error in `HasRequestedColumns` trait on Laravel Vapor

---

src/Tags/Range.php
tests/Tags/RangeTest.php

Fixes: https://github.com/statamic/cms/issues/9017

[4.x] Prevent `{{ range times="0" }}` from outputting

---

src/Search/Commands/Update.php

This pull request makes a small improvement to the `php please search:update` command. 
When you only have 1 search index configured in `config/statamic/search.php`, there's no point prompting the user to select  which index to update, if they only have one option to pick from.

[4.x] Don't prompt user to select search index when there's only 1 configured

---

config/assets.php
src/Http/Controllers/CP/Assets/AssetsController.php
src/Http/Controllers/CP/Fieldtypes/FilesFieldtypeController.php
src/Http/Controllers/FormController.php
src/Validation/AllowedFile.php

For improved security, file uploads are restricted to a list of extensions.
The list covers most use cases, but if you have a need for more you may them to your config.

[4.x] Only allow uploading certain file extensions

---

src/Assets/AssetUploader.php
src/Assets/FileUploader.php
tests/Assets/AssetTest.php

When uploading a file that has a mime type that doesn't match the file extension, the file extension will be changed so that it matches the mime type.
For example, this fixes an issue where someone could upload an `.html` file with a spoofed `image/jpg` mime type. This could allow parts of the system to believe it is a jpg, passing image validation, but continue to act as an html file in other parts.
Now, if you upload an `.html` file with a `image/jpg` mime type, it'll get saved as `.jpg`.
This PR also adjust some seemingly unrelated Glide tests so that we check against pdf instead of eps files. In faked uploaded files, eps files ended up getting renamed to ai files. (Actual uploaded files don't.) I changed the test to use pdf which is the same outcome, but doesn't end up with the …

[4.x] Apply appropriate file extension when uploading

---

src/Http/Controllers/CP/Fields/FieldsController.php

This pull request ensures that field handles are formatted in snake case (eg. without any spaces, dashes, slashes, etc). 
Closes #6457.

[4.x] Ensure field handles are in snake case

---

src/StaticCaching/NoCache/Controller.php

This pull request fixes an issue where the `{{ nocache }}` tag wouldn't return any regions when the page's URL ends in a `?`.
Fixes #8673.

[4.x] Fix nocache tag when URL ends in `?`

---

resources/js/bootstrap/globals.js
resources/js/components/fieldtypes/CodeFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/fieldtypes/replicator/ManagesPreviewText.js
resources/js/components/fieldtypes/replicator/PreviewHtml.js

This PR will escape the replicator preview text in a more central place so it happens automatically for all fieldtypes.
If you need html, you can wrap your html this function, like the assets fieldtype is doing here.
```diff
computed: {
replicatorPreview() {
const html = `<img src="thumbnail.jpg" />`;
-   return html;
+   return replicatorPreviewHtml(html);
}
}
```

[4.x] Improve sanitization of Replicator set preview text

---

src/Tags/Collection/Entries.php
tests/Tags/Collection/EntriesTest.php

This PR allows you to pass terms fields to a collection tag without having to consider the length of your terms field.
`{{ collection:articles :taxonomy:topics:any="taxonomy_terms_field" }}`
Closes https://github.com/statamic/cms/issues/7697

[4.x] Fix entries tag not filtering by taxonomy when terms field is `max_items: 1`

---

src/Support/Html.php
tests/Support/HtmlTest.php

This pull request copies the missing `nestedListing` method from [`laravelcollective/html`](https://github.com/LaravelCollective/html/blob/6.x/src/HtmlBuilder.php#L410) into our `Html` class.
Fixes #5233.

[4.x] Fix missing `nestedListing` method on `Html` class

---

src/Licensing/Outpost.php

This pull request fixes a regression from #9000, where we implemented cache locking to prevent concurrent requests to the Outpost. 
Most of the popular cache drivers have support for caching locking. However, the APC driver doesn't support cache locking. This PR works around that issue by creating a mock class for the locking stuff. 
This mock class won't prevent concurrent requests to the Outpost. If you're experiencing this issue on a cache driver that *doesn't* support locks, we'd recommend using [one that does](https://laravel.com/docs/master/cache#atomic-locks) like `file`, `redis`, `database`.
Fixes #9026.

[4.x] Fix Outpost locking code for cache drivers without locking support

---

src/Http/Controllers/CP/Collections/EntriesController.php

This pull request fixes an issue when creating a new entry, where the collection's route uses the entry ID, like this: `/members/{id}` or simply `/{id}`.
Previously, when creating an entry, no ID would exist so the URI would be simplified to `/members` so if you had an existing entry at `/members`, it would cause a validation error.
This PR attempts to fix this by always passing an ID into the `UrlBuilder` if the entry doesn't already have one set. 
Fixes #5500.

[4.x] Fix URI validation error when collection route uses entry IDs

---

src/Fieldtypes/HasSelectOptions.php

This pull request fixes an issue where nothing would be displayed for a Select Fieldtype option in a Listing Table if the selected option was missing a label. 
When a select option is missing a label, it'll display the option's key/value instead.
Fixes #6533.

[4.x] Select Fieldtype: Fallback to key when option label is missing

---

resources/js/components/revision-history/Revision.vue

This PR wraps the revision action in the revision history in the translate method, allowing these strings to be translated.
Currently the only possible values are `revision`, `publish` or `unpublish`
Closes https://github.com/statamic/cms/issues/8737

[4.x] Allow revision actions to be translated

---

src/Tags/Glide.php
tests/Tags/GlideTest.php

This pull request fixes an issue with the Glide tag, when using it with an external URL without a valid extension.
For example, with `{{ glide src="https://statamic.com/foo" }}`, the Glide tag would output `/foo`, which isn't very useful as a fallback.
Now, with this PR, `https://statamic.com/foo` will be outputted.
Fixes #5753.

[4.x] Glide: Output absolute URL when external image has invalid extension

---

resources/js/components/fieldtypes/TextFieldtype.vue
resources/js/components/inputs/Text.vue

The autocomplete config on text inputs wasnt being passed to text inputs in the CP. This PR now ensures the value is set.
Closes https://github.com/statamic/cms/issues/8988

[4.x] Pass autocomplete config param to CP text inputs

---

resources/js/plugins/slugify.js
src/Entries/Collection.php
src/Taxonomies/Taxonomy.php
tests/Feature/Collections/Blueprints/UpdateBlueprintTest.php
tests/Feature/Taxonomies/Blueprints/UpdateBlueprintTest.php

This pull request adds `max:200` to the ensured slug fields on both entry & term blueprints.
Fixes #4426.

[4.x] Add validation to limit characters in slugs

---

resources/js/components/fieldtypes/assets/Asset.js

This pull request makes a small improvement to the Assets Fieldtype....
When on a read-only asset field and clicking onto an asset, it would previously go to the asset's URL. However, if the asset container's filesystem doesn't have a URL set, the URL wouldn't work. Instead, it'll now open the download prompt. 
Fixes #8595.

[4.x] Assets Fieldtype: Download asset when no URL is available

---

resources/js/components/data-list/Table.vue

This PR fixes the table `jumping` bug that Rob was experiencing.
It seemed to be caused by the focus() being set on the table, which I assume was due to the need to support shift clicking (?). I moved it inside the shift logic and the jump went away.
Closes https://github.com/statamic/cms/issues/8536
~Leaving as a draft until Rob verifies that it works.~

[4.x] Fix checkbox selection in listing tables 'jumping' on Safari

---

resources/js/components/fieldtypes/ArrayFieldtype.vue

This pull request reverts #8980, which automatically populated labels from option keys in the Array Fieldtype.

[4.x] Revert "[4.x] Auto-populate Array Fieldtype Options (#8980)"

---

src/Auth/CorePermissions.php
src/CP/Utilities/UtilityRepository.php

This pull request attempts to fix an issue where the permissions for utilities are missing when you're using route caching.
From what I can tell, without route caching it looks like the utilities are booted **before** the permissions are booted but _with_ route caching, the permissions are booted before utilities are.
To workaround this, we've made the `boot` method in the `UtilitiesRepository` fluent so we can do `Utility::boot()->all()` to ensure utilities have always been booted before we use them.
Fixes #8691.

[4.x] Fix utility permissions not showing when using route caching

---

src/Modifiers/CoreModifiers.php

As proposed and approved in statamic/ideas#1083 this PR allows the usage of a color as parameter for the Ray modifier.
Example:
```antlers
{{ hello_world | ray('red');
```
Closes statamic/ideas#1083

[4.x] Extend Ray modifier for use of the color helper function

---

resources/js/components/inputs/relationship/Selector.vue
resources/js/components/structures/Branch.vue
resources/js/components/structures/PageTree.vue

This pull request makes a small improvement to the Entries Fieldtype in Tree Mode. 
Previously, you could only click on the checkbox to toggle if an entry was selected or not. Now, you can click anywhere on the "tree branch".
Closes #9043.

[4.x] Make whole tree branches clickable in Entries Fieldtype in Tree Mode

---

resources/js/components/inputs/relationship/Selector.vue

This pull request fixes an issue when using the pagination in the Relationship Fieldtype, where it'd scroll the user to the top of the page.
Fixes #7278.

[4.x] Fix pagination in Relationship Fieldtype causing page to scroll to the top

---

src/Http/Controllers/ActivateAccountController.php
src/Http/Controllers/ResetPasswordController.php
src/Http/Middleware/CP/RedirectIfAuthorized.php

This PR adds the `RedirectIfAuthorized` middleware to password reset & activate pages, so if a logged in user tries to visit those pages they will be redirected away.
I've also updated RedirectIfAuthorized to check if the user can access the cp or not, if they can they are taken to it, and if they cant they are just taken to the homepage.
I think this closes https://github.com/statamic/cms/issues/2521

[4.x] Use RedirectIfAuthorized middleware on password reset & activate pages

---

resources/js/components/entries/PublishForm.vue
resources/views/entries/create.blade.php
resources/views/entries/edit.blade.php

This pull request fixes an issue where changing the selected site when editing an entry doesn't take affect to the site selected when the user is redirected back to a collection's tree listing.
Fixes #6600.

[4.x] Pass site parameter from Entry Publish Form to Tree Listing

---

resources/js/components/Listing.vue

[Redirect actions](https://statamic.dev/extending/actions#redirects) show a toast error when you go back to the CP. 
This PR handles the situation checks when an axios request was made and has no response, instead of showing the default toast we do nothing.
Closes https://github.com/statamic/cms/issues/3166

[4.x] Fix redirect actions showing a toast error

---

src/Search/Algolia/Index.php
src/Search/Index.php
src/Search/Searchables.php

Maybe not the right approach, but this PR works to reduce the memory usage of searchables()->all() by providing a searchables()->lazy() method returning a less memory heavy LazyCollection. It also updates Algolia and Comb to use this instead of searchables()->all().
It could be possible to take this a step further and have the provider return a lazy collection and then insert each document individually rather than multiple, but that would mean more http calls so maybe thats a trade off.
Should help with https://github.com/statamic/cms/issues/8854

[4.x] Provide searchables()->lazy and insertLazily methods to search indexes

---

src/Fieldtypes/Terms.php

When using a term field type you can search for an existing value and press enter without selecting anything from the autocomplete. On save, this would cause a new term to be created using the same slug, which in turn overwrites the previous terms data.
This PR updates the term creation logic on the fieldtype to check if the term already exists. It also adds a unique constraint on process to prevent duplicates being added.
Closes https://github.com/statamic/cms/issues/7332

[4.x] Prevent existing term data being overwritten in terms fieldtype

---

src/Http/Responses/DataResponse.php
tests/FrontendTest.php

Not sure if this is the best approach, but this PR brings back the previous functionality when the redirect is to `@child`. This means if you add that to your .md file regardless of the field type (or if there isnt even one) the redirect still happens.
Closes https://github.com/statamic/cms/issues/8680

[4.x] Fix `redirect: @child` redirecting to `@child` when not a link fieldtype

---

src/Query/Builder.php

Passing `null` to parameter of type `string` (parameter 1 in `strtolower()`) is deprecated since PHP 8.1.

[4.x] Fix deprecated: passing null to parameter of type string

---

src/Tags/Concerns/QueriesConditions.php
tests/Tags/Concerns/QueriesConditionsTest.php

This PR allows tag conditions to query on sub fields, eg date ranges. 
Technically this was already possible, just the syntax was ugly:
`:date_field->end:is_after="today"`
after this PR you can do 
`:date_field.end:is_after="today"`
Which looks a bit nicer I think.
Closes https://github.com/statamic/cms/issues/7099

[4.x] Allow tag conditions to support querying on sub fields using dot notation

---

src/Query/Scopes/Filters/Concerns/QueriesFilters.php
src/Query/Scopes/ScopeRepository.php

We updated to Statamic 4. By having a great UI change anyways, we decided hide some default filters as we have many custom filters covering all our needed use cases. 
To hide default filters in the Service Provider.
```php
app()->bind(\Statamic\Query\Scopes\Filters\Fields::class, fn () => null);
app()->bind(\Statamic\Query\Scopes\Filters\UserRole::class, fn () => null);
app()->bind(\Statamic\Query\Scopes\Filters\UserGroup::class, fn () => null);
```
By doing so, a scope can return null. If a user has old presets containing those filters, an error occures.
This PR covers the case, that `app($scope)` might find a filter but returns null anyways. With this PR, Statamic can handle that case and should not include any breaking change. It is simply hardening the code base for funky cases like …

[4.x] Scope filters can return null

---

resources/js/components/field-conditions/Validator.js

Currently if you add a custom condition with a target field handle, like this:
```yaml
if:
my_target: 'custom foo:bar'
```
The field handle (my_target) isn't passed to the condition callback, only the target value is.
Having the field handle is useful if you want to run a condition based on meta data from the store, rather than the field's raw value. For example if you have a condition based a relationship field the target value will just be the ID, but you might want to check the collection handle that's stored in `store...meta.my_target.data[0]`.
This PR adds the field handle to the data that's passed to the callbacks.

[4.x] Pass target field handle to custom conditions

---

resources/js/components/users/Wizard.vue

In #9003 I unintentionally made the label css leak onto other pages.
This fixes it by using scoped styles.
It also removes the important which wasn't necessary.

[4.x] Fix user wizard styles

---

src/Fieldtypes/HasSelectOptions.php

This is an alternate solution of #9038.
The issue was that `Arr::get` will return only return the fallback if the key is completely missing.
In the bug's case, the key (the value) was there but the value (the label) was null. 
This adjusts it to use a `??` so we always get the fallback and never null.
```php
$arr = [
'alfa' => 'Alfa',
'bravo' => null,
];
Arr::get($arr, 'alfa', 'fallback'); // "Alfa"
Arr::get($arr, 'bravo', 'fallback'); // null - We were expecting "fallback"
Arr::get($arr, 'charlie', 'fallback'); // "fallback"
```

[4.x] Fix select fieldtype fallback differently

---

resources/js/components/fieldtypes/DateFieldtype.vue

Closes #9088
- When you have time enabled and no value, it would now as `null`. Now it outputs nothing as expected.
- Fix ranges being output as JSON. Now it outputs `start - end`.
- Fix configured date format not being used. Now it does.

[4.x] Fix date replicator preview in more configurations

---

src/Entries/Collection.php

This reverts #8926.
I noticed that when you create an entry, the `date` field is no longer pre-filled with the current date if you have a `date` field in your blueprint.
This is because we wouldn't merge `['default' => 'now']` into the config due to #8926.
I was ready to go ahead and re-fix #2743, but it looks like the issue isn't there anyway. You can make the slug field unlocalizable just fine.

[4.x] Fix date field not populating with current date, revert prevention of ensuring fields if they already exist

---

resources/js/components/fieldtypes/bard/Set.js

This pull request fixes a bug with Bard where you couldn't add any sets when you have a "horizontal cursor".
Normally, the `selection` with a normal cursor would be an instance of `TextSelection`. However, when it's a "horizontal cursor", a `GapCursor` will instead be returned which doesn't have a `$cursor` to get the position from.
Fixes #7712.

[4.x] Bard: Fix adding sets with horizontal cursor

---

resources/js/components/entries/PublishForm.vue
resources/js/components/globals/PublishForm.vue
resources/js/components/terms/PublishForm.vue
resources/js/components/users/PublishForm.vue
src/Http/Controllers/CP/Collections/EntriesController.php
src/Http/Controllers/CP/Globals/GlobalVariablesController.php
src/Http/Controllers/CP/Taxonomies/TermsController.php
src/Http/Controllers/CP/Users/UsersController.php
src/Revisions/Revisable.php
src/Revisions/Revision.php

This pull request fixes an issue where a successful "Saved" toast message would be displayed after cancelling the save with the `EntrySaving` event.
This fix also applies to some of the other `Saving` events.
Fixes #6293.

[4.x] Prevent showing "Saved" toast message when listener cancels save

---

src/Fieldtypes/Terms.php

When using typeahead mode for the terms field type, prevent any results from showing until a search is made. This prevents a full query being carried out on all terms - if you are using typeahead it's usually due to you having lots of terms.
Closes https://github.com/statamic/cms/issues/5919

[4.x] Prevent terms fieldtype in typehead mode showing results until a search is entered

---

src/View/Antlers/Language/Parser/AntlersNodeParser.php
tests/Antlers/Parser/ConditionalNodesTest.php
tests/Antlers/Runtime/ConditionLogicTest.php

This PR fixes #9096 by silently forcing all conditions to have the form
```antlers
{{ if (this == that) }}
{{ /if }}
```
this resolve an incredibly subtle issue where conditions would aggressively collapse values (in the original issue, the `ArrayableString` would be collapsed to its array too early). This behavior doesn't happen when using the modifiers normally (i.e., not in a condition).
This issue is easiest to reproduce with partials, but is not *caused* by conditions in partials. The linked issue contains a repository to reproduce the bug; updating the `default.antlers.html` to contain the following will also manifest the issue:
```antlers
{{ code = settings:code_field }}
{{ if code | starts_with('<div>') }}
<div>Yes, "code" starts with div</div>
{{ else }}
<div>No, it does …
```

[4.x] Antlers: corrects a subtle bug with conditions resolving variables

---

src/Imaging/GlideManager.php

In https://github.com/statamic/cms/pull/8661/ I didn't consider the possibility of the file extension changing, so if you do something like 
{{ glide src="/assets/content/lagoa.jpg" format="webp" width="200" dpr="2" }}
the file last part of the url is still .jpg, which is not good. This PR updates that to use the correct extension.

[4.x] When appending glide filename consider that the extension may have changed

---

src/Fields/Blueprint.php

This one took a bit of code diving, but when using an imported field which is in an ensuredField, the import prefix was being ignored when handles were being mapped at one point in the code.
This resolves that.
Closes https://github.com/statamic/cms/issues/4869

[4.x] Fix for Can't add title to a fieldset and use fieldset prefixes at the same time

---

src/Tags/Glide.php

We have a similar issue to https://github.com/statamic/cms/issues/2791 in that glide is throwing exceptions that are causing 500 errors on the page. Our errors are often due to a mismatch of image format (eg Image [image.jpeg] does not actually appear to be a valid image)
This PR prevents that by catching any glide errors and suppressing the output. Instead we log the errors, which feels more antlers-y ?
Closes https://github.com/statamic/cms/issues/2791

[4.x] Handle glide exceptions gracefully

---

src/StaticCaching/NoCache/Tags.php
tests/StaticCaching/NocacheTagsTest.php

In #8956 we made it so that the nocache tag will only add variables to the cached session if they are used in the template. This turns out to be too heavy handed.
If variables were being used indirectly, such as in a partial or a custom tag, they would be missing from the context.
This PR makes the optimizations opt-in. You will need to explicitly select the fields you need. Without any selections, the former unoptimized version containing all contextual variables will be used.
You can select explicit fields:
```antlers
{{ nocache select="this|that" }}
```
Or use the `@auto` placeholder to extract them from the template (this is similar to the `@shallow` placeholder in the nav tag):
```antlers
{{ nocache select="@auto" }}
```
Or combine them to extract the variables from the template and …

[4.x] Change nocache performance optimizations to be opt-in

---

resources/js/components/fieldtypes/DateFieldtype.vue

This pull request follows on from #9093, by fixing an issue with the Date fieldtype's replicator preview. When the time value was left empty, `null` would be returned in the replicator preview.
Related: https://github.com/statamic/cms/issues/9088#issuecomment-1835678901

[4.x] Fix replicator preview for Date fieldtype when time is empty

---

.github/workflows/tests.yml

Tests started failing in GitHub actions because of a change in the `setup-php` action.
This PR is the workaround mentioned in https://github.com/shivammathur/setup-php/issues/799#issuecomment-1843575027
Thanks @felipeelia @jhoff

[4.x] Fix test suite

---

resources/js/components/assets/Browser/Browser.vue
src/Policies/AssetPolicy.php

This pull request fixes an issue where the "configure asset containers" permission doesn't override other asset permissions (like the ability to upload assets or create folders).
Fixes #7382.

[4.x] "Configure asset containers" permission should override other asset permissions

---

src/Query/Builder.php
tests/Data/Entries/EntryQueryBuilderTest.php

Basically lifted from the Laravel builder, but we may as well support `chunk()` and `lazy()` in query builders, useful when you have lots of entries.

[4.x] Add chunk and lazy to query builder

---

.github/workflows/tests.yml

This reverts #9141 as the issue is now resolved so the workaround isn't necessary.

[4.x] Revert unnecessary workaround

---

src/Fieldtypes/Assets/Assets.php

The amount of times I forget to add a container to an assets field is staggering. While I realise this is definitely a me problem, this PR makes the field required to prevent future me from doing this again.

[4.x] Make the `container` field in the `assets` fieldtype required

---

src/Tags/Nav.php

This pull request excludes taxonomy index pages from being returned by the `{{ nav:breadcrumbs }}` tag when the index view is missing.
An attempt was made in #4147 to fix this but it implemented a new `view_exists` variable, instead of filtering the page out of the breadcrumbs like this PR does.
Fixes #3863.

[4.x] Exclude taxonomy index pages from nav:breadcrumbs tag when view is missing

---

src/Providers/ExtensionServiceProvider.php
src/Tags/Children.php
tests/Tags/ChildrenTest.php

Sometimes you want to get and loop over the children of the current page, for example to show an inline sub-nav. You can do this with the right combination of params on the `{{ nav }}` tag but given there is a `{{ parent }}` tag, people might expect an equivalent `{{ children }}` tag.
Closes https://github.com/statamic/cms/issues/5567

[4.x] Add `children` tag

---

resources/css/components/fieldtypes/replicator.css

This PR adds min-height to the set inner header matching the height of an icon, so the height of the set header stays consistent even if no delete icon is present.
Closes https://github.com/statamic/cms/issues/9127

[4.x] Fix styling of grid stacked mode header when deleting is not possible

---

src/Http/Resources/API/TermResource.php
src/Taxonomies/AugmentedTerm.php
tests/Data/Taxonomies/AugmentedTermTest.php

When a taxonomy is mounted make the `collection` variable available to the front end view by adding the key to the augmented term.
Closes https://github.com/statamic/cms/issues/8472

[4.x] Add `collection` to augmented term values

---

src/Entries/Collection.php
src/Routing/Routable.php
tests/Feature/Collections/DeleteCollectionTest.php

This pull request fixes an error which would occur when deleting a collection in a multi-site, where entries have localizations.
Fixes #3890.

[4.x] Fix deleting collections with localized entries

---

src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Runtime/ConditionLogicTest.php

This PR fixes #9161 by ensuring the Str::contains (when processing nested string interpolations) doesn't run on objects.

[4.x] Antlers: Corrects an issue where string interpolation checks would run Str::contains on objects

---

src/Http/Controllers/CP/Collections/CollectionsController.php
src/Http/Controllers/CP/Collections/EntriesController.php

A possible solution to both https://github.com/statamic/cms/issues/6762 and https://github.com/statamic/cms/issues/3756
If the collection is not set up on a site then redirect back with a toast message telling the user that the collection isn't available.
Closes https://github.com/statamic/cms/issues/6762 
Closes https://github.com/statamic/cms/issues/3756

[4.x] If collection is not available on a site, redirect back

---

resources/views/utilities/search.blade.php
src/Http/Controllers/CP/Utilities/UpdateSearchController.php
src/Search/IndexManager.php

As [reported here](https://github.com/statamic-rad-pack/meilisearch/issues/30) updating multi-site search indexes through the CP utilities is not working as it tries to find an index which already has a locale/site appended, then appends the current one to that.
This PR modifies the logic to check if the locale is already appended to the name, and if so, splits out the index name and the locale.

[4.x] Fix updating localized search index through the CP

---

src/StaticCaching/Cachers/FileCacher.php

We should make the nocache region and CSRF available through the event in case a developer needs to update a variable or something thats not handled by the default options provided.
The developer can then listen for this 
```js
document.addEventListener('statamic:nocache.replaced`, (event) => {
// do something with event.detail.regions or event.detail.csrf
});
```
Closes https://github.com/statamic/cms/issues/9162

[4.x] Add nocache regions and CSRF to `statamic:nocache.replaced` event

---

src/Fields/Field.php

As [reported here](https://github.com/statamic/cms/issues/9168), validation attributes are not being translated, so you get the default locale display for the field in the error message.
This PR fixes that by translating the display.
Before:
After:
Note the difference in the "Bericht" field.
Closes https://github.com/statamic/cms/issues/9168

[4.x] Translate validation attributes when pulled from display

---

src/Http/Controllers/CP/API/TemplatesController.php

Since [the last change](https://github.com/statamic/cms/commit/765d30bc10f146b5e137fe433a4d435b59e65b06) in `TemplateController.php` there is a problem with dots on the view path, because everything after the first dot will be stripped.
So, for example, if your site is located in `/Users/username/Sites/mysite.com` you’d get a list like this in the control panel when selecting a template:
- /Users/username/Sites/mysite
- /Users/username/Sites/mysite
- /Users/username/Sites/mysite
- ...
Fixes #9177.

[4.x] Fix template lookup with dots in view path

---

src/Entries/Entry.php
src/Http/Middleware/Localize.php
src/Modifiers/CoreModifiers.php
src/Providers/AppServiceProvider.php
tests/Feature/Fieldtypes/FilesTest.php
tests/FrontendTest.php

Inspired by #9101.
It could be very useful to add `Date::use(CarbonImmutable::class)` in your AppServiceProvider to make all dates immutable.
If we add that to our service provider and run the test suite, there were some errors and failures. This PR makes the necessary changes to get the tests passing again.

[4.x] Use date facade and carbon interface

---

src/Structures/CollectionStructure.php
src/Structures/Tree.php

Improve performance when CollectionStructure::in is called multiple times for the same collection and site. This increases performance when warming the stache: #8744 
Closes #8744.

[4.x] Improve CollectionStructure performance

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue

In grid table mode the label element doesn't exist to add the click listener to, so double check it exists before adding the listener.
Closes https://github.com/statamic/cms/issues/8947

[4.x] Prevent events being added to an element that doesn't exist when in grid table mode

---

src/Entries/Collection.php
src/Entries/Entry.php
src/Structures/StructureRepository.php
tests/Feature/Collections/DeleteCollectionTest.php

This pull request deletes the tree files for collection structures when deleting a collection. Previously, deleting a collection would result in an empty tree file like this:
```
{  }
```
I've added the nullsafe operator in some places to gracefully ignore issues about collections/pages not existing. 
Fixes #3848.

[4.x] Delete collection tree files when deleting collections

---

resources/js/components/collections/EditForm.vue

This pull request fixes an issue when selecting an entry to mount a collection onto. It would only happen when a site has 2 collections (eg. Pages & News) and the user is viewing the new "Tree View".
No site was being passed down the chain to the `PageTree` so the tree that was returned from the backend was empty and didn't contain any entries.
Fixes #9120.

[4.x] Fix tree view when configuring collection mount

---

src/Auth/Protect/Protectors/Authenticated.php
src/Auth/Protect/Protectors/Fallback.php
src/Auth/Protect/Protectors/IpAddress.php
src/Auth/Protect/Protectors/Password/PasswordProtector.php
src/Exceptions/Concerns/RendersHttpExceptions.php
src/Exceptions/ForbiddenHttpException.php
src/Exceptions/NotFoundHttpException.php

This pull request fixes an issue where the layout wouldn't be used when rendering the 403 Forbidden pages, only the template's content would be used.
Fixes #4014.

[4.x] Render layout on 403 Forbidden pages

---

src/Fields/Fieldset.php

This pull request fixes an issue where a Global Set without a blueprint would break the Fieldsets index page.
Fixes #9186.

[4.x] Fix Global Set without a blueprint breaking the Fieldsets page

---

resources/js/components/entries/PublishForm.vue
resources/js/components/globals/PublishForm.vue
resources/js/components/terms/PublishForm.vue

This pull request fixes an issue where the 'lock' icon wasn't being displayed correctly when viewing revisions.
Fixes #9184.

[4.x] Fix Read Only icon when viewing revisions

---

src/Entries/AugmentedEntry.php

If an augmented entry has an origin, the mount should be found from the origin, not the entry itself.
Closes https://github.com/statamic/cms/issues/6906

[4.x] If entry has an origin, get the mount from there

---

.github/ISSUE_TEMPLATE/bug_report.yml

Swap the default for the antlers parser in the bug report template. The runtime parser has been the new default since a while.

[4.x] Update the bug report template.

---

resources/js/components/revision-history/Preview.vue

This pull request fixes an issue when attempting to preview revisions via a Relationship Fieldtype. 
When clicking a revision in the revision history, it would show an endless loading spinner because it was trying to use the ID of the base entry, rather than the ID of the entry the revision's attached to.
Fixes #3810.

[4.x] Fix previewing revisions via Relationship Fieldtype

---

resources/js/components/publish/Sections.vue

This PR closes #7855 and hides sections with no visible fields.
I basically copied #9135. Thanks @edalzell.

[4.x] Hide sections with no visible fields

---

resources/js/components/field-conditions/Builder.vue

This pull request prevents you configuring multiple conditions for the same field in the blueprint/fieldset builder.
Previously, the "Field" dropdown in the builder allowed you to select fields even if they already had conditions configured against them. Then, when you saved the field, only one of the multiple conditions would actually be saved.
This PR prevents you from doing that until we implement the ability to configure multiple conditions for the same field (see statamic/ideas#1101).
Fixes #6008.

[4.x] Prevent configuring multiple conditions for the same field

---

resources/js/components/stacks/Stack.vue

There's currently a glitch with the background stack hover offset, best explained with a video:
https://github.com/statamic/cms/assets/126740/626e7dd9-7d15-4276-ad26-cd25f85fd8da
When the second stack is closed the first one moves (gap appears on the right) and then gets stuck there.
This happens because there's a 300ms delay between closing the stack and the component being destroyed. During that time the second stack's `mouseenter` event will still trigger, activating the first stack's hover state, but then it's destroyed so the hover state is never cleared.
The PR fixes it by checking that `visible` is true before firing any of the background hit area events. The same issue also occurs when you click on the hit area to go back, so to fix that I've added a `hit-area-mouseout` event …

[4.x] Fix stack hover offset on close

---

src/Search/ProvidesSearchables.php
src/Search/Searchables/Entries.php
src/Search/Searchables/Terms.php

Now that the [query builder supports lazy](https://github.com/statamic/cms/pull/9148), the searchable provider provide() method can make use of that to return documents in a more memory efficient manner.
The PR updates the interface to allow this method to return a LazyCollection and updates both entries and terms to do that. It seems this is not a breaking change, as other providers still return a standard collection and I encountered no errors.
I notice that assets and users are not using a query builder (they are just returning a filtered `all()`), so there is definitely scope to improve things further by updating those providers to do that.
This should close https://github.com/statamic/cms/issues/8854

[4.x] Provide searchable entries and terms lazily

---

src/Fields/Validator.php

In line with the file upload section here: https://laravel.com/docs/10.x/precognition#handling-file-uploads
I feel we should prevent asset fields from validating on precognitive requests, so this PR prevents any validation rules for assets running during those requests.
Closes https://github.com/statamic/cms/issues/9138

[4.x] Prevent precognitive validation on asset fields

---

src/Http/Controllers/CP/Navigation/NavigationController.php

This pull request fixes an issue where the Control Panel would error if you delete the tree file for a navigation. Now, when a tree file is missing, it'll be created.
Fixes #5244.

[4.x] Create tree for navigation if one doesn't exist

---

resources/js/components/entries/PublishForm.vue

In version 4.35.0, PR #8961 was introduced to show changes from the `EntrySaving` event in the edit-form UI. 
However, the values from the response are in many edge-cases slightly different than the current values. This causes the form to become dirty when an entry is saved. This dirtiness is especially inconvenient when using revisions as it causes the publish button to become disabled. Issue #9068 is an example of this.
This PR disables dirty-tracking while resetting the values from the response.
I am new to the Statamic-codebase and do not know if a timeout is the best approach here. Setting the timeout to 300 did not work which is why I increased it to 350.

[4.x] Prevent dirt on saved entry

---

resources/js/components/entries/PublishForm.vue

This pull request reverts to the original dirty state fix in #9203. 
Before merging that PR, I had refactored it to use `$nextTick` but I typo-d it & when I fixed it, it didn't sort the issue for Bard fields.
`setTimeout` seems to be used elsewhere for dirty state stuff so I reckon we'll be fine to use it here too.

[4.x] Revert to original dirty state fix

---

src/Tags/Children.php
tests/Tags/ChildrenTest.php

With the tag {{ children }} use the current collection instead of using Pages.
You can test it by creating a collection with parent & child entry and in the template of the parent use {{ children }} to return all of his children.
Fix #9207

[4.x] Fix tag {{ children }} for every collection

---

src/Http/Controllers/FormController.php
src/Http/Requests/FrontendFormRequest.php

Filter out any null values in checkboxes on front end form requests.
The hidden input cant be removed as it was [added to solve an issue on user profile forms](https://github.com/statamic/cms/pull/7180/files).
Closes https://github.com/statamic/cms/issues/9194

[4.x] Filter out any nulls from front end form checkboxes

---

src/Http/Controllers/CP/Fields/FieldsController.php

This PR addresses a bit of a regression introduced in #9039, which I believe was tagged in v4.36. Prior to that, you could do something like this in a field handle, and it would Just Work™:
```yaml
handle: config->nested_field
```
Due to the regex added in #9039, that functionality broke. Tbh, I'm not event 100% sure this functionality is intentional from Statamic's perspective, but we have a project that depends somewhat heavily on it. This PR simply tweaks the regex a bit, to allow for `->` arrows within the handle.
See **[this warning on the regex validation rule from Laravel's docs](https://laravel.com/docs/10.x/validation#rule-regex)**, for context on the switch to an array (instead of the normal string/piped approach) for the handle's `validate` property. And here's **[a RegExr if …

[4.x] (Re-)Allow nested JSON field handles

---

resources/js/components/entries/PublishForm.vue
src/Auth/File/Role.php

The permission cache is already cleared when adding a permission with the `addPermission()` method. It should also be cleared when removing a permission with `removePermission()` or overriding existing permissions with the `permissions()` method.
My use case is this middleware, where I remove permissions based on the current site. Without this PR, the user will still have access to edit the entries, as the permissions are cached.
```php
class AuthorizeGounity
{
public function handle(Request $request, Closure $next): Response
{
$site = Site::selected()->handle();
if ($request->route()->getName() === 'statamic.cp.collections.entries.edit') {
$id = array_last($request->segments());
$site = Entry::find($id)->site()->handle();
}
if ($site === 'gounity') { …
```

[4.x] Clear permission cache

---

resources/js/components/fieldtypes/LinkFieldtype.vue

This pull request fixes #9238, where a Link Fieldtype would break when used in a Bard set, which is nested in a Replicator or Bard field.
For clarity, here's what the blueprint needs to look like to test:
- Bard / Replicator
- Set
- Bard
- Set
- Link
This bug was caused by our previous fix in #9189. In that fix, we started cloning the field meta to prevent the same meta being references for all link fields.
This fix subsequently caused the `meta` to technically be different, which caused the `meta` watcher to get called. We've fixed this by returning early if the contents of the "new" meta and "old" meta are the same. 
Fixes #9238.

[4.x] Fix Link Fieldtype inside nested Bard

---

src/Providers/AuthServiceProvider.php

While getting Statamic working with Octane in our production environments I've hit an issue with AuthServiceProvider using an old instance of the Container.
Octane appears to be working by creating single instances of ServiceProvider for a worker's lifetime but created cloned instances of the Container for each request. The binding callbacks are then re-ran for each request and given the new container instance (a clone of the original.) This even appears to happen for the first request. As such the `$this->app` will be an instance of an Container that is never used for any request but just for initial registration.
Best practice [from the docs](https://laravel.com/docs/10.x/octane#container-injection) suggests using `app()` or however from testing the `$app` parameter from the singleton …

[4.x] Fix issue with AuthServiceProvider and Laravel Octane

---

src/View/Antlers/Language/Nodes/AntlersNode.php
src/View/Antlers/Language/Parser/DocumentParser.php
tests/Antlers/Runtime/ParametersTest.php

This PR solves an edge-case that can cause unexpected results when using string interpolations inside tag parameters (an example repo with this edge-case can be found here: https://github.com/aerni/statamic-collection-filter-bug).
At a high level, this happens when we have really short interpolations like so:
```antlers
{{ collection:events id:not="{id}" another_parameter="{another:variable}" }}
{{ /collection:events }}
```
Due to how interpolation is handled inside parameters when attempting to resolve to a string, it is possible for an unexpected value to be returned that incorporates the `another:variable` value.
This PR fixes this in two ways:
1. For parameters, the most specific replacements are handled first, continuing on to the least specific
2. The internal interpolation-variable …

[4.x] Corrects an issue with short interpolated variables

---

src/Fieldtypes/Bard.php

This pull request attempts to fix an issue when augmenting Bard fields after the "Save HTML" option is enabled on the field but it is yet to be re-saved (& be converted to HTML).
Fixes #6045.

[4.x] Prevent Bard augmentation error after enabling "Save HTML" option

---

resources/js/components/assets/Uploader.vue

Sometimes, when you upload a file which is larger than PHP's file size limit, you'll get an error from Nginx (or Apache) which isn't a JSON response.
Because it's not a JSON response, `JSON.parse` errors out before we can display a useful error message to the user. This PR handles that situation.

[4.x] Ensure error message is displayed when uploading large file

---

src/Entries/Entry.php

When using dates in auto generated titles with a user whose selected locale is different from the site locale they are editing, the antlers parser will use the user's locale rather than the site locale.
This PR ensures we are using the right locale to generate the dates.
Closes https://github.com/statamic/cms/issues/6966

[4.x] Use the site locale when auto generated titles

---

resources/js/components/revision-history/History.vue
resources/js/components/revision-history/Revision.vue

This will localize revision dates using native JS instead of Moment.
It scraps the relative time, which isn't really important.
Closes #2508

[4.x] Localize revision dates

---

resources/js/components/navigation/View.vue
resources/js/components/structures/Branch.vue
resources/js/components/structures/PageEditor.vue
resources/views/navigation/show.blade.php

This pull request fixes an issue where users with the "view ... nav" permission could see & click on things that are only intended to be shown if you have the "edit ... nav" permission.
Fixes #8184.

[4.x] Prevent users without "edit" permission editing navs 

---

resources/views/utilities/search.blade.php

This pull request fixes an issue where the "Update All" button in the Search utility was erroring out.
The error was happening due to the locale not being appended to the indexes here:
https://github.com/statamic/cms/blob/549a8baea9646a2932fc3dca3ab58bd6d63f5ca0/resources/views/utilities/search.blade.php#L17
While it was for the singular "Update" button in the indexes loop:
https://github.com/statamic/cms/blob/549a8baea9646a2932fc3dca3ab58bd6d63f5ca0/resources/views/utilities/search.blade.php#L74
Fixes #9267.

[4.x] Fix "Update All" in search utility

---

resources/views/partials/scripts.blade.php

This PR refactors away the `@json` directive that creates Statamic's `StatamicConfig` control panel object. The current implementation currently works fine on accident:
```blade
<script>
var StatamicConfig = @json(array_merge(Statamic::jsonVariables(request()), [
'wrapperClass' => $__env->getSection('wrapper_class', 'max-w-xl')
]))
</script>
```
If we were to add another item to merge in the future (or simply add a trailing comma):
```blade
<script>
var StatamicConfig = @json(array_merge(Statamic::jsonVariables(request()), [
'wrapperClass' => $__env->getSection('wrapper_class', 'max-w-xl'),
]))
</script>
```
the view will compile to invalid PHP code. The current version works "on accident" because the following values are used by the Blade compiler, and can take advantage of the emitted …

[4.x] Removes problematic JSON directive

---

src/Http/Controllers/API/TaxonomyTermEntriesController.php

This pull request addresses an issue with the Taxonomy Term Entries API endpoint, where you'd receive a 500 Server Error when fetching entries for a term that doesn't exist.
The API endpoint only accepts passing slugs of terms, not titles which was why the endpoint was erroring in #4219.
This PR fixes that by throwing a 404 exception when the specified term doesn't exist.
Fixes #4219.

[4.x] Throw 404 exception on Taxonomy Term Entries endpoint when term doesn't exist

---

src/Fieldtypes/Relationship.php
src/Http/Controllers/CP/Assets/BrowserController.php
src/Query/Scopes/ScopeRepository.php
src/Tags/Concerns/QueriesScopes.php

Inspired by the conversation in https://github.com/statamic/cms/pull/9058
This PR ensures the Scope facade is always used (instead of calling app.scopes directly) and also provides a way of removing scopes (`Facades\Scope::remove($handle)`).

[4.x] Always use the scope facade and allow removing of scopes

---

src/StaticCaching/Invalidate.php

This pull request attempts to fix an issue from the Static Caching invalidator when deleting entries in a structured collection.
When you have a structured collection, the invalidation logic would attempt to get the entry's URL but in doing so it called a method on an entry which no longer existed.
This PR changes when invalidation happens for entries. Instead of it happening *after* the entry has been deleted (& removed from the tree), it'll happen *before* the entry is deleted and removed from the tree so the full entry URI is known and to prevent the error from happening.
Fixes #5836.

[4.x] Fix error from static caching invalidator when deleting entries

---

src/Stache/Repositories/TermRepository.php
src/Stache/Stores/TaxonomyTermsStore.php

This PR adds some logic to the stache terms store to handle the issue that when a slug is updated it adds a second stache entry until stache:clear is called.
This issue only appears in terms as they are indexed by slug, rather than a unique id.
Closes https://github.com/statamic/cms/issues/5449

[4.x] Prevent updating a term slug from creating two stache terms

---

resources/js/components/fields/Settings.vue
resources/js/components/fieldsets/Listing.vue

This pull request attempts to fix two mobile issues:
* An overflow issue with the Fieldsets Listing Table
* An issue where you couldn't scroll on the Field Settings stack on Safari on iOS
Fixes #9237.

[4.x] Fix mobile issues with Fieldset Listing & Field Settings stack

---

src/Tags/Children.php

This pull request fix an issue where if you specify the site url in your multi-site you get the wrong data from the children tag on other sites.
Fixed by using the absolute url.
Fix #9279

[4.x] Fix usage of children tag with multisite and specified url

---

resources/js/components/data-list/HasPagination.js

This pull request fixes an issue on Listing Tables where any selections would be persisted even after navigating to another page (pagination).
This change doesn't seem to affect selections in the Relationship Fieldtype. You can continue to select items across multiple pages on there. 
Fixes #6767.

[4.x] Clear selections when navigating pagination

---

src/Forms/Form.php

This pull request prevents the Control Panel from erroring out due to invalid form submission data.
Instead of an error being thrown, Statamic will load the problematic form submission without any data & append a line to your log file so you can tell there's an issue. 
Fixes #6860.
Fixes #6969.
Fixes #7775.

[4.x] Prevent errors from invalid form submission data

---

resources/js/components/DirtyState.js

This pull request attempts to fix an issue where the "Save" button on a term's inline publish form would be disabled if you had created another term inside that publish form... 
If that description doesn't make any sense, watch the video in #8308 which will describe it nice and clear 😆 
When you saved the second term (in the demo, that's the province one), `isDirty` on the first term become `false` instead of `true`. After some digging, it seems like the `names` array was cleared when saving the second term, which it shouldn't have been (there's still dirty state on the root publish form & on the first term's publish form). 
This PR refactors how items are removed from the `names` array which seems to have fixed the issue in my testing.
Fixes #8308.

[4.x] Fix disabled save button when creating term inside term inside stack

---

src/Http/Controllers/CP/Collections/EntriesController.php

This pull request fixes an issue creating entries when using `JsonResource::withoutWrapping()` in a service provider.
I've tried to fix this in a similar way to some of the previous withoutWrapping fixes, see #7072.
Fixes #9283.

[4.x] Fix creating entries with `JsonResource::withoutWrapping()`

---

src/Assets/Asset.php
tests/Assets/AssetTest.php

This pull request fixes an issue where an asset's `.meta` file would not be deleted when the asset itself was deleted.
Although the meta file was actually deleted, it was shortly after being re-created by the `UpdateAssetReferences` listener which calls the `getOriginal()` method on the `Asset`, which ended up calling `meta()` and because of a meta file not being found for the asset, it created one.
This PR attempts to fix that issue by checking if the asset itself actually exists before writing the meta file to disk. If one doesn't exist, it'll now just return an empty meta array.
Fixes #7042.

[4.x] Fix asset meta file not being deleted with asset

---

resources/css/components/fieldtypes/bard.css

This pull request re-enables Bard's sticky toolbar when in Live Preview. 
Fixes #9223.

[4.x] Fix Bard's sticky toolbar in Live Preview

---

config/system.php

The config value for `statamic.system.php_max_execution_time` is currently set to `-1` by default. This value is then passed to `set_time_limit` to "crank things up" to eleven. The problem is though that the "no limit" value for setting the maximum execution time is `0` and not `-1` (see https://www.php.net/manual/en/function.set-time-limit.php). Apparently PHP-FPM just swallows this invalid value, but Frankenphp throws an error about receiving an incorrect value here.
The config value is only used on `set_time_limit` calls (https://github.com/search?q=repo%3Astatamic%2Fcms%20php_max_execution_time&type=code), so the default can safely be set to its correct value.

[4.x] Use correct set_time_limit no limit value

---

resources/js/components/assets/Browser/Browser.vue

Hey everyone,
Our users noticed weird behavior in the asset browser.
Basically what happened is when they had a `per-page` preference enabled for assets, the assets browser would trigger 2 network requests on the initial load.
Paired with an average internet and a lot of assets resulted in the following:
1. Opening the asset browser by clicking on Assets in the navigation
2. Asset browser would trigger 2 requests with parameter (perPage=500)
3. Our user would open a folder
4. Then a second request, that has been queued would finish, and our user would be returned to the first page
Steps to replicate:
1. Open assets browser
2. Try to search for something
3. Scroll to the bottom of the search results and set the `per-page` preference to different than the default
4. Open assets browser …

[4.x] Fix Asset browser firing 2 requests on initial Assets page load

---

resources/js/components/fieldtypes/grid/Grid.vue
resources/js/components/fieldtypes/grid/Stacked.vue
resources/js/components/fieldtypes/grid/View.vue

This pull request fixes spacing around the fullscreen button on Stacked Grid fields. This PR improves spacing both with & without the field's display being hidden.
Fixes #8748.
Replaces #9158.

[4.x] Fix spacing around fullscreen button on Stacked Grid

---

resources/js/components/structures/Branch.vue

This pull request fixes an issue where you wouldn't be able to select entries while using Tree mode in the Entries Fieldtype. It was due to a `v-if` in the wrong place - introduced by #9265.
There's no issue since I just ran into it while testing something else.

[4.x] Entries Fieldtype: Fix missing checkbox on Tree Mode

---

src/Http/Controllers/CP/Collections/CollectionsController.php

This PR resolves an issue with too many redirects when switching the selected site to a site that a collection is not configured for. In the example below, the `articles` collection is only configured for the `default` site. The redirect issue happens when switching to the `german` site. 
https://github.com/statamic/cms/assets/23167701/4f330134-61e3-478c-9088-52f3dd62805e
https://github.com/statamic/cms/assets/23167701/bbd00905-feb6-4981-8b7f-4737ca2848da

[4.x] Fix too many redirects

---

src/Fields/Blueprint.php

It seems the line that we changed was needed, otherwise when you save a blueprint it deletes the original blueprint in the vendor folder (the root vendor folder not the blueprint/vendor folder).
Maybe theres a better way to do it, but this does solve it.

[4.x] Updating an add-on blueprint shouldnt remove it from the vendor folder

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

After doing some digging into #9294, I managed to track down Bard as the culprit of the dirty state issues. 
After an entry is saved, the [publish form values get updated](https://github.com/statamic/cms/blob/4.x/resources/js/components/entries/PublishForm.vue#L570). This consequently triggers Bard's `value` to be updated, which causes Bard to think it's `json` has changed and it needs to emit the updated value upwards.
However... in comparing the string-ified JSON with the actual `value` being passed into Bard, they were exactly the same. Yet, because it was emitted up the chain, it triggered the dirty state. 
This only *seems* to be an issue when you have a few different sets open because it needs to take over 360ms (the timeout on `PublishForm@runAfterSaveHook`) to parse the JSON, …

[4.x] Prevent Bard causing dirty state issues

---

src/Fields/BlueprintRepository.php
src/Http/Controllers/CP/Fields/BlueprintController.php

This PR fixes a bug and makes a tweak to the new blueprint namespaces feature when using multi-part namespaces (`something.otherthing`).
The `findNamespacedBlueprintPath` and `filesIn` methods are currently using the namespace key to check the override paths rather than the namespace directory.
And the `humanize` helper doesn't replace the dots when generating titles for the listing view:

[4.x] Fix additional blueprints in multi-part namespaces

---

resources/js/components/publish/Field.vue

This pull request removes the unnecessary "Read Only" on section fields to avoid any confusion about an entire section being read-only just because the copy on the section says so.
Closes statamic/ideas#1087

[4.x] Fix "Read Only" text for section fields

---

resources/js/components/fieldtypes/relationship/RelationshipIndexFieldtype.vue

This pull request fixes an issue I spotted with the Relationship Index Fieldtype component, where it'd error causing items to not be shown after toggling a relationship column to show.
1. Add an Entries fieldtype to collection blueprint
2. Go into an entry and link some other entries
3. On the Listing Table, open the "Column Picker" and toggle the Entries field. 
4. A column *will* show for the Entries field but no items will be displayed until you refresh the page.

[4.x] Fix error from Relationship Index Fieldtype after toggling column

---

src/Stache/Stores/CollectionsStore.php

Part of https://github.com/statamic/cms/issues/9236
Right now when saving changes in the collection tree the uri index and order index will be rebuild completely, even though the specific ids are passed as a parameter.
This causes performance issues when having a lot of entries.
This PR fixes that and updates only the affected parts.

[4.x] Update entry order and uri by ids

---

vite.config.js

As [reported here](https://github.com/statamic/cms/issues/8773), it is currently not possible, to deploy a statamic cms application with a url-prefix (e.g. https://my-domain.example/my-application instead of https://my-application.example).
This PR fixes that by setting a relativ path in the vite config, that is used to bundle the frontend.
Closes #8773

[4.x] Update vite.config.js to allow deploying statamic with url-prefix

---

resources/js/components/fieldtypes/ArrayFieldtype.vue
resources/js/components/fieldtypes/ButtonGroupFieldtype.vue
resources/js/components/fieldtypes/CheckboxesFieldtype.vue
resources/js/components/fieldtypes/CodeFieldtype.vue
resources/js/components/fieldtypes/ColorFieldtype.vue
resources/js/components/fieldtypes/DateFieldtype.vue
resources/js/components/fieldtypes/Fieldtype.vue
resources/js/components/fieldtypes/GroupFieldtype.vue
resources/js/components/fieldtypes/RadioFieldtype.vue
resources/js/components/fieldtypes/SelectFieldtype.vue
resources/js/components/fieldtypes/TableFieldtype.vue
resources/js/components/fieldtypes/ToggleFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/grid/Grid.vue
resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue
resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue
resources/js/components/fieldtypes/replicator/Field.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
resources/js/components/fieldtypes/replicator/Set.vue

This pull request adds some checks to prevent unnecessary field previews from being computed & emitted to parent components when field previews are disabled. 
Without these changes, any time a field's value changes, it would compute & emit the field preview, even if it's a root field or the parent Bard/Replicator has field previews disabled. 
This should *hopefully* help somewhat with performance with the Bard & Replicator fieldtypes. 🤞 
In the [first commit](https://github.com/statamic/cms/pull/9353/commits/380c2ce5de8835ac3324849f109f74ce6d026d3e), I made it so the `replicator-preview-updated` event doesn't get emitted when field previews are disabled. 
Then, in my [second commit](https://github.com/statamic/cms/pull/9353/commits/b078329d0674ea3da5515bd062f9ca86230e21ad), I added the …

[4.x] Prevent handling field previews when previews are disabled

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

Fixes #4181
Intercepts Cmd/Ctrl + Enter inside bard and does nothing (instead of inserting a line break).

[4.x] Passthrough Cmd/Ctrl + Enter inside Bard

---

src/Query/Builder.php
tests/Data/Entries/EntryQueryBuilderTest.php

For a bit of context, check out: https://github.com/mitydigital/statamic-scheduled-cache-invalidator/pull/3#issuecomment-1899900451
The add-on was passing a full date string to whereTime... eg whereTime('2023-01-01 09:00'), which I hadn't accounted for. This meant it worked like whereDateTime() setting the whole date to that time, which unfortunately doesn't exist. I feel like Carbon should have been handling this possibility in their setTimeFromTimeString method, but they weren't.
The result was that it would get the date matches for that date only, ignoring any others that have a matching time but a different date, which isnt how whereTime is meant to work.
Anyway, its an edge case, and it was quite a nice bug as it made queries simpler, but its not the same behaviour as eloquent, so …

[4.x] Fix whereTime affecting the date as well as time

---

resources/js/components/fieldtypes/SlugFieldtype.vue

Previously, you'd need to have a value for it to show.
If you cleared out the slug field, the button would disappear.
Or, if you add a slug field to a form that didn't previously have slugs, like an user, then the button wouldn't be there until you typed something.

[4.x] Always show slug rengerate button if enabled

---

src/Structures/Page.php
tests/Data/Structures/PageTest.php

This pull request fixes an issue when using `.html` (or a few other file extensions) in collection routes.
For example: if you had a collection route like this...
```yaml
route: /{parent_uri}/{slug}.html
```
The URL for an entry could be `/parent.html/child.html` instead of `/parent/child.html` which is expected.
Fixes #7324.

[4.x] Strip out `.html` from `parent_uri`

---

src/Assets/Uploader.php
tests/Assets/AssetTest.php

This pull request implements sanitization around uploading SVG files, both through front-end forms and the Control Panel asset browser.

[4.x] Sanitize SVG uploads

---

src/Licensing/Outpost.php
tests/Licensing/OutpostTest.php

This backports #8475 to 3.4, which prevents the CP throwing an an exception if the Outpost has an unexpected error.

[3.4] Fix Outpost error handling

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

This pull request makes a small change to Bard so the TipTap Placeholder extension is only loaded when a placeholder has been configured for the Bard field.
Currently, the Placeholder extension seems to be breaking other extensions (see #9235) so moving this to only be enabled when a placeholder is configured should at least provide a workaround until the extension is properly fixed in TipTap Core.
Related: #9235

[4.x] Bard: Only configure placeholder extension when placeholder is provided

---

resources/js/components/forms/Listing.vue
resources/views/forms/show.blade.php
src/Http/Controllers/CP/Forms/FormsController.php

This pull request fixes a small issue on Forms pages where users could see dropdown options or empty dropdowns when they don't have the relevant form permissions.
No issue exists for this issue - just noticed it the other day on a personal project.

[4.x] Hide actions on form index/show pages when user is missing relevant permissions

---

src/StaticCaching/Middleware/Cache.php

Replaces #8964
Having token-based functionality on a page more than likely implies there's a dynamic aspect to the page.
We'll avoid statically caching the page if there's a valid token.

[4.x] Avoid caching URLs with a token

---

src/Http/Requests/FrontendFormRequest.php

When submitting a form on the front-end, validation messages will be in the appropriate site's language.
However, some people are using this same URL to create form submissions in a headless fashion, without using a `form:create` tag on the front-end.
Additionally, they are setting the app locale manually in a middleware.
This PR will make it so that the validation language is only used if submitted from the frontend. Otherwise it'll just fall back to the default locale (not the language of the default site like it does now).
It's worth noting that `URL::previous()` will fall back to the the home page when there's no referrer header, where as `session()->previousUrl()` will fall back to `null`, which is what we need here.

[4.x] Only use site language for form submission validation messages if submitted from front-end

---

resources/lang/en/messages.php
src/Http/Controllers/CP/Users/UsersController.php

This pull request implements handling to catch any errors thrown by mailers when sending the user activation email as part of the create user wizard.
Previously, when a mailer threw an exception while sending the activation email and you tried to re-submit you'd hit a validation error due to the email already being used, since the user was created the last time the wizard was submitted.
With the handling added in this PR, the wizard will complete but the user will see a toast message on the next page telling them the email didn't get sent. 
**Note:** The toast will only display if you're using the `sync` queue driver. If you're using a "proper" queue driver, we assume you already know how to handle failed jobs.
Fixes #9309.

[4.x] Catch errors when sending user activation email

---

src/Http/View/Composers/FieldComposer.php

This pull request fixes an issue when attempting to import a fieldset in the Blueprint Builder for a custom namespaced blueprint.
The error was happening due to `fieldsets` not being found in the `StatamicConfig` object due to the blueprint view being `resources/views/blueprints/edit.blade.php` instead of `resources/views/..../blueprints/edit.blade.php`
Fixes statamic-rad-pack/runway#410.

[4.x] Fix importing fieldsets in custom blueprint namespaces

---

src/Assets/AssetUploader.php
src/Assets/FileUploader.php

This PR reverts #9033 which seems to cause more problems than it resolved.
The problem that PR was solving also seems to be solved by #9037 which will remain in the codebase.
Resolves #9182
Resolves #9314

[4.x] Revert overzealous file extension renaming feature

---

src/Actions/CopyPasswordResetLink.php

This PR makes the "Copy Reset Password Link" action opt-in due to a security concern.
You may add `'allow_copy_reset_password_link' => true` to `config/statamic/users.php` to enable it.
The ability to send the reset link via email remains - it's just the ability to copy it that is changing.

[4.x] Make copy reset password link action opt-in

---

src/Auth/Eloquent/UserGroup.php
src/Auth/Eloquent/UserGroupModel.php
src/Console/Commands/ImportGroups.php
src/Console/Commands/stubs/auth/statamic_groups_table.php.stub
src/Http/Controllers/CP/Users/UserGroupsController.php
tests/Auth/Eloquent/EloquentUserGroupTest.php

Turns out that #5686 didn't support user group data. Probably because it was authored before the feature was introduced.

[4.x] Support data in Eloquent based user groups

---

routes/web.php
src/StaticCaching/NoCache/Controller.php
src/StaticCaching/NoCache/NoCacheLocalize.php

This pull request fixes an issue with translations when using the `{{ nocache }}` tag.
Fixes #7893.

[4.x] Fix translations in `nocache` tag

---

resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue

This pull request fixes an issue with the Tree view in the Entries fieldtype when used in on an asset publish form. 
This was happening due to there being no `site` in the publish form's `values`, which caused the tree request to return no entries.
This PR fixes it by falling back to the currently selected site when a site can't be found in the publish form's `values`.
Fixes #9403.

[4.x] Fix Entries fieldtype tree view on Assets publish form

---

resources/js/components/entries/Listing.vue

This pull request fixes an issue on the Entries Listing Table where it was possible to use filter views & search entries when reordering entries. 
This function was [previously disabled](https://github.com/statamic/cms/blob/3.4/resources/js/components/entries/Listing.vue#L21) when reordering, however, it must have been missed with the Listing Table refactoring that was done for v4.
Closes #9331.

[4.x] Hide listing filters when reordering entries

---

resources/js/components/fieldtypes/ColorFieldtype.vue

This pull request adds a button which allows you to reset the currently selected color in the Color Fieldtype. Previously, you could reset the colour by removing the hex value but that was only possible when `allow_any` was `false`.
Fixes #9410.

[4.x] Add reset button to Color Fieldtype

---

src/Http/Controllers/CP/Users/UsersController.php

Fixes a user wizard error when the user blueprint has a bard field, which was accidentally introduced by https://github.com/statamic/cms/pull/9003, and reported by @edalzell.
The issue is that the PR introduced a `toPublishArray()` call on a set of `preProcess()`'d fields (in order to provide the new additional fields to the user wizard). The additional `fields` passed to the user wizard don't need to be `preProcessed()` though, since we pass `values` separately, so this fix uses a fresh `Fields` instance off the blueprint.
There's no tests for this fix, because it's a bit of a bandaid fix for a slightly deeper issue. Bard fields `preProcess()` empty values to a string JSON value of `'[]'`, which then errors you try to `toPublishArray()`. We're unsure what the actual fix should be. We've …

[4.x] Fix user wizard error when user blueprint has bard field

---

src/StaticCaching/NoCache/Region.php

This pull request fixes a serialization error with the `@nocache` directive when using a Blade view component with a custom method.
This PR will evaluate any custom methods in Blade view components.
Fixes #8203.
Related: #6935

[4.x] Prevent serialization errors with`@nocache` directive when using Blade view components

---

src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php
src/Taxonomies/Taxonomy.php

https://github.com/statamic/cms/pull/8372 introducted termTemplate and template on Taxonomies, but it unfortunately also always saves the default values through the CP, which means the magic collection views never get called.
This PR reverts that behaviour, and doesnt save these values unless they are explicitly set.
Closes https://github.com/statamic/cms/issues/9418

[4.x] Don't set termTemplate and template if they are the defaults

---

resources/js/components/fieldtypes/ListFieldtype.vue
resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
resources/js/components/fieldtypes/bard/Set.vue

This pull request fixes an issue with Set Previews in Bard where fields returning `PreviewHtml` objects would be converted into "normal" objects when the previews are [cloned here](https://github.com/statamic/cms/blob/6bd4976198b9e4cdb68c3c69686487a3c391c30a/resources/js/components/fieldtypes/bard/Set.vue#L182).
You can easily reproduce this with an Assets field & Forms field in a Bard set. When you change/remove the form, the preview for the Asset field in the set shows you the JSON rather than the expected preview output. 
I've copied the fix for this from how we do the same thing on Replicator sets. I've also removed the `getReplicatorPreviewText` methods from the Asset & List fieldtypes since they're no longer used.
Fixes #9174.

[4.x] Fix issue with Set Previews in Bard

---

config/editions.php
src/Console/Commands/ProEnable.php
src/Providers/ConsoleServiceProvider.php

Adds `php please pro:enable` command, so that user doesn't have to find (or publish in Laravel 11) their editions config:
And if they still have old config with hardcoded boolean, we can instruct them:
The logic is mostly taken from our existing `license:set` command, so this isn't a new pattern 👌

[4.x] Improve the workflow around enabling Statamic Pro

---

src/Mixins/Router.php

When making simple routes like this:
```php
Route::statamic('my-page', 'my-page');
```
It's a little redundant when the view is the same as the URI. This PR makes the view optional and fall back to use the URI as the view.
```php
Route::statamic('my-page'); // Implies 'my-page'
Route::statamic('/my-page'); // Implies 'my-page'
Route::statamic('/foo/bar'); // Implies 'foo.bar'
```

[4.x] Implied Statamic route views

---

src/Entries/Collection.php

This pull request removes the deprecated `revisions` method from the `Collection` class. The [`revisionsEnabled`](https://github.com/statamic/cms/blob/bffeeddb6a023fc8d6fff73a9eb35df861a636f9/src/Entries/Collection.php#L629) method should be used instead.
Closes #9433.

[5.x] Remove deprecated `revisions` method from Collection

---

src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php
src/Taxonomies/Taxonomy.php

Who knew this would keep coming back around.
This PR makes template and termTemplate public, as otherwise the fields in the TaxonomyController never have values.
Im sorry.

[4.x] Ensure template and termTemplate are accessed correctly in Taxonomy controller

---

resources/js/components/fieldtypes/replicator/Field.vue

This pull request makes a small tweak to the styles of fields inside replicators to match the styles of "normal" fields in publish forms.
Closes #9438.

[4.x] Tidy up replicator field styles to match "normal" fields

---

src/Stache/Stores/CollectionsStore.php
src/Stache/Stores/Store.php
src/Stache/Traverser.php

This reverts #9302 as it turns out to be a breaking change in some situations, as mentioned in https://github.com/statamic/cms/pull/9302#issuecomment-1921815852.
I'm sure this will be back eventually.

[4.x] Revert Stache watcher performance PR

---

src/StaticCaching/NoCache/Region.php

This pull request fixes an issue where pages would timeout when the `{{ nocache }}` tag is being used on a page. This was caused by #9409.
It seems like the fact we were processing it through a `Collection` was causing the issue. When I tried refactoring to use a simple foreach loop, the timeout went away. 
Fixes #9437.

[4.x] Fix timeout when using nocache tag

---

src/Tags/Tags.php
tests/Tags/LinkTest.php

Instead of extending or overriding existing Statamic tags, make them macroable so we can extend them from multiple sources like addons and locally.
Simple example put in boot method of a serviceprovider:
```php
Link::macro('statamic', function () {
return 'https://www.statamic.com';
});
```
In antlers:
```antlers
{{ link:statamic }}
```

[4.x] Make tags macroable

---

src/Providers/AppServiceProvider.php

Sometimes its useful to know at a glance whether a project is using single or multisite, and how many.
This will output the names of the first few sites, which can be helpful to know _how_ people are using multisite.

[4.x] Add sites to support details output

---

resources/js/components/Echo.js
src/Providers/BroadcastServiceProvider.php

This PR allows you to use a custom broadcasting Echo client config within the CP.
It adds a new `Statamic.$echo.config()` method and passes some additional pusher options through to the JS side.
For example to use with [Soketi](https://docs.soketi.app/getting-started/client-configuration/laravel-echo) add this to `cp.js`:
```js
Statamic.booting(() => {
Statamic.$echo.config(() => ({
broadcaster: "pusher",
key: Statamic.$config.get('broadcasting.pusher.key'),
cluster: Statamic.$config.get('broadcasting.pusher.cluster'),
wsHost: Statamic.$config.get('broadcasting.pusher.host'),
wsPort: Statamic.$config.get('broadcasting.pusher.port'),
wssPort: Statamic.$config.get('broadcasting.pusher.port'),
forceTLS: false,
encrypted: true,
disableStats: true,
enabledTransports: ["ws", "wss"],
}));
}); …
```

[4.x] Allow custom Echo client configuration

---

src/Support/Str.php

Fixes #9471
The `trans_choice` helper expects the count argument to be an integer. The error was due to `number_format` resulting in an uncastable number sometimes when it got formatted with a comma.
The `trans_choice` helper doesn't need to be used anyway as it's not a different translation depending on the number. This PR changes it to `trans` as it should have been.
I've updated the three spots where `number_format` _wasn't_ used, for consistency, even though it wouldn't cause an error.

[4.x] Fix unit translations

---

resources/views/nav/updates.blade.php
resources/views/partials/nav-main.blade.php
resources/views/partials/nav-mobile.blade.php

In #9256 a `v-pre` was added, but this caused the Vue component within the updates nav item to not be compiled.
This PR moves the `v-pre` onto each nav item.
Fixes #9474

[4.x] Fix updates badge

---

resources/js/components/UpdatesBadge.vue
src/Http/Controllers/CP/Updater/UpdaterController.php
src/Updater/UpdatesOverview.php

**Fix double AJAX calls**
The update counter badge was performing 2 ajax request for every cp page request.
The vue component is rendered twice: once in the desktop nav and once in the mobile nav.
This is fixed now by using a Vuex store to keep track of the count and request. Only one of them will trigger the request.
**Remove unnecessary caching boolean**
The update count is cached. We had a boolean being passed to the ajax route which attempted to force a re-cache when necessary. This has never actually been working, and is unnecessary anyway. This PR removes that unnecessary code.

[4.x] Fix update counter

---

src/Fields/BlueprintRepository.php
tests/Fields/BlueprintRepositoryTest.php

This PR contains a small DX improvement.
Currently you can Blueprint::find('namespace::handle') but you cant Blueprint::make('namespace::handle') which feels inconsistent.
This PR changes that to be possible.

[4.x] Allow namespace to be passed in Blueprint::make()

---

src/Providers/AppServiceProvider.php

The `BlueprintRepository` isn't currently a singleton. This is causing a problem with the new blueprint namespaces feature as new repository objects are being created which don't have the additional namespaces registered.
This PR makes it a singleton
This matches the `FieldsetRepository` which is already a singleton.

[4.x] Make `BlueprintRepository` a singleton

---

src/Fieldtypes/Entries.php
src/Fieldtypes/Terms.php

This pull request fixes an issue where entry & term fields weren't being localized when querying taxonomy terms.
The *real* fix for this issue would be to add the `Localization` interface to the `LocalizedTerm` class. However, in doing that, we'd need to change the method signature of the `locale` method which would be a breaking change for anyone overriding that class. 
Fixes #9469.

[4.x] Localize entry & term fields in Taxonomy Term GraphQL queries

---

src/Forms/JsDrivers/AbstractJsDriver.php
tests/Tags/Form/FormCreateAlpineTest.php
tests/Tags/Form/FormCreateCustomDriverTest.php

This pull request adds the Honeypot field to the form data object (eg. `x-data` when using Alpine.js) to prevent forms being processed when the honeypot contains a value.
Although this PR adds the honeypot field to the form data (`x-data`), developers will still need to add an `x-model` to the honeypot fields in their templates.
```html
<input id="{{ honeypot }}" type="text" name="{{ honeypot }}" x-model="form.{{ honeypot }}" />
```
Fixes #9495.

[4.x] Include honeypot in Alpine.js form data

---

.github/workflows/tests.yml
routes/cp.php
src/Http/Controllers/CP/API/TemplatesController.php
tests/Fieldtypes/TemplatesTest.php
tests/__fixtures__/templates/blog/index.antlers.html

This pull request fixes an issue where the directory separator is wrong when using the Templates fieldtype on Windows.
I tried to fix this issue a few months ago in #9197 but seems like it's still an issue. I've added a test to ensure it's actually fixed since we don't use Windows for development.
Fixes #9458.

[4.x] Fix directory separator in Templates fieldtype on Windows

---

src/Events/Event.php

This pull request sets the `$authenticatedUser` property to `null` on our base `Event` class to prevent `$authenticatedUser must not be accessed before initialization` errors.
This error mostly seems to be happening for addons with their own events, which extend our base `Event`. It also only happens when they're [dispatching events with Laravel's `event` method](https://github.com/riasvdv/statamic-redirect/blob/f6e1ce3e128a718526199dc610fa5df31d507171/src/Stache/Redirects/RedirectRepository.php#L81), rather than the `::dispatch` static method we normally use in Core.
Fixes https://github.com/riasvdv/statamic-redirect/issues/163.
Related Discord conversation: https://discord.com/channels/489818810157891584/1153390699161587823/1204384286052978689

[4.x] Fix `$authenticatedUser` error with third-party addon events

---

resources/js/components/fieldtypes/CodeFieldtype.vue

This pull request fixes an issue with the Code Fieldtype where it would error out when switching between sites on the Globals Publish Form.
If the site you're switching into has no value, `value.code` would be null which causes issues in CoreMirror. This PR fixes that by instead passing in an empty string.
Fixes #9485.

[4.x] Fix error from Code Fieldtype when switching sites in global

---

resources/js/components/fieldtypes/date/RangePopover.vue
resources/js/components/fieldtypes/date/SinglePopover.vue

A couple of clients have been unsure how to clear a popover date fieldtype, as it's not super obvious that you have to delete the text or open the popover and deselect the date.
This PR adds clear buttons:
I wasn't 100% sure on where to place them. I think putting them in the fields looks tidiest, and it matches the select fieldtype's clear button, but it does feel a bit odd in time and range modes. At the moment the fields they appear in are the same ones that already clear the value when you delete the text, so there is some logic to it.

[4.x] Add clear value button to popover date fieldtype

---

src/Fieldtypes/Entries.php
src/Fieldtypes/Terms.php
src/Taxonomies/LocalizedTerm.php

In #9492, we implemented a temporary fix for entry & term fields not being localized when taxonomy terms were being queried in GraphQL. 
This PR reverts that temporary fix in favour of implementing the `Localization` interface on the `LocalizedTerm` class, which is what we do for entries. Since implementing this interface requires a change to the `locale` method signature, this is a breaking change. 
Related: https://github.com/statamic/cms/issues/9469

[5.x] Implement `Localization` interface on `LocalizedTerm`

---

resources/js/components/assets/Browser/Browser.vue
resources/js/components/data-list/Action.vue
resources/js/components/data-list/DataList.vue

This PR gets rid of some event handlers when the Vue components are destroyed.
This might help towards #9351

[4.x] Clean up some event handlers

---

src/StaticCaching/NoCache/Session.php
src/Tags/Concerns/OutputsItems.php

This pull request aims to fix issues with pagination when using the `{{ nocache }}` tag.
* In my testing, the previous/next page URLs were `/!/nocache?page=2` due to the "current URL" not being the URL of the original page.
Fixes https://github.com/statamic/cms/issues/8052.

[4.x] Fix pagination with the `nocache` tag

---

src/View/Antlers/Language/Parser/AntlersNodeParser.php
tests/Antlers/Runtime/ParametersTest.php

This PR removes an existing papercut by allowing number literals inside Antlers parameter variable bindings. Currently, it is difficult/non-obvious on how one should go about passing a numeric value to a tag, as normal parameters are converted to strings:
```antlers
{{ my_tag param="1234" }}
```
We can now simply use variable binding syntax to pass along the numeric literal:
```antlers
{{ my_tag :param="1234" }}
{{ my_tag :param="-1234" }}
{{ my_tag :param="1234.56" }}
```
The current behavior would treat the numeric literal as a variable name, which is invalid, and always end up returning `null`, so I don't see this is as a breaking change. This PR does not automatically cast numeric values in all other situations since that would be a breaking change:
The following will remain a string …

[4.x] Antlers: Allow number literals inside variable bindings

---

src/Console/Commands/StaticWarm.php

This pull request prevents entries with redirects from being warmed by the `static:warm` command.
There's no existing issue for this but I noticed it this morning while deploying my personal site, that it was warming external URLs.

[4.x] Prevent warming redirect URLs

---

resources/js/components/inputs/relationship/InlinePublishForm.vue

This pull request fixes an issue when scrolling the `InlinePublishForm` component on Safari on iOS. I copied the fix for this from my previous PR #9250, which fixed a similar issue but on the field settings stack.
Fixes #9501.

[4.x] Fix scrolling in Inline Publish Form on Safari on iOS

---

src/Http/Controllers/API/ApiController.php

This fixes an issue where if you're trying to use numbers in filters, they'd be strings and your comparisons would end up incorrect.
For example:
`/api/somewhere?filter[integer_field:gt]=5`
This would end up with a query like `where('integer_field', '>', '5')`. You want `5` though, not `"5"`.
This PR casts numeric values to either an integer or float.

[4.x] Fix numbers not being cast in API filters

---

src/Assets/AssetUploader.php

This pull request fixes an issue when using an asset container with a `source_preset` defined. All uploaded files would be renamed, even if they aren't images.
Fixes #9515.

[4.x] Prevent non-images being processed through source preset

---

resources/css/elements/tables.css

Sometimes when you click the "Reorder" button on a collection listing, the table row drag handles aren't visible.
This happens when you have enough columns that the horizontal overflow kicks in, and the drag handle table cell gets squished.
This PR gives it a min width to prevent squishing.

[4.x] Fix table drag handles disappearing

---

src/Modifiers/CoreModifiers.php

This PR adds support for YouTube Shorts to the embed_url Antlers modifier.
Also it fixes an issue where youtube-nocookie.com embeds are not working without [www](http://www/). You can reproduce it when omitting www from a YouTube embed link (working: https://www.youtube.com/watch?v=7hYbrdC_-s8, not working: https://youtube.com/watch?v=7hYbrdC_-s8)

[4.x] Support YouTube Shorts in embed_code modifier

---

src/Actions/DuplicateEntry.php

This pull request introduces a change to only check for descendants if multiple sites are used. 
**This will increase the perfomance of the control panel on single sites.**
When initializing the Duplicate Entry action, it will search for entries where the `origin_id` equals the `id` of the entry of this action. If the Multi-Site feature of Statamic is not used, this will cause multiple unnecessary file (or database) requests on the index page of a collection in the control panel.

[4.x] Only search for descendants if multi-site mode is enabled

---

src/Http/Controllers/CP/Users/UsersController.php

When you're editing a user while logged in as a super user, we add a toggle for you. We also check your permission on the server side when saving it back onto the user.
However if you explicitly added your own super field onto the blueprint, `$fields` would contain `super`, and the value gets applied without running through the check.
This PR excludes it from the values so it has to go through the explicit check.
It also removes it from the "User information" step of the create form. If you're a super user, it'll already be on the "Roles & Groups" step.

[4.x] Exclude super when using a custom field

---

src/Http/Controllers/CP/Collections/EntriesController.php

This pull request fixes an issue when updating entries when using `JsonResource::withoutWrapping()` to prevent wrapping of JSON resources.
Fixes #9518.

[4.x] Fix issues when saving entries with `JsonResource::withoutWrapping()`

---

src/View/Antlers/Language/Runtime/ConditionProcessor.php
src/View/Antlers/Language/Runtime/Sandbox/Environment.php
tests/Antlers/Sandbox/ConditionalsTest.php

This PR resolves a bug when using tags inside conditions. Currently, it will evaluate a tag _twice_ on initial usage. This existing bug can be observed by using a template similar to the following:
```antlers
{{ if {switch between='yes|no'} == 'yes' }}yes{{ else }}no{{ /if }}
{{ if {switch between='yes|no'} == 'yes' }}yes{{ else }}no{{ /if }}
```
Currently, all evaluations would print `no` since the tag with execute once when building up the context before evaluating the condition, and would execute again when evaluating the condition itself. This PR improves this internal behavior to prevent double execution for the initial tag execution.
Existing (valid) behaviors have not been changed, and additional test coverage added to ensure they are working correctly.
Interpolations are still …

[4.x] Antlers: stops double-initial execution of tags within conditions

---

tests/Antlers/Runtime/TemplateTest.php

This pull request fixes an issue with failing tests on `master`, due to a renamed class in #9529.
I'm not _entirely_ sure why it's only failing now, after [I merged in the latest commits](https://github.com/statamic/cms/commit/91c0834ace880da459c69c2186febada5cf3c89c#diff-9a1e4199f71e750b614f734d99704b91721cbe19146a9b22bdcb8fb0b5fd1869) from `master` and not after the PHPUnit 10 PR was merged.

[5.x] Fix failing Antlers tests

---

src/Fields/Fields.php
tests/Fields/FieldsTest.php

Something I overlooked in https://github.com/statamic/cms/pull/9080.
This PR ensures the new parent field and index are passed down to imported and referenced fields.

[4.x] Pass parent field and index down to imported fields

---

src/Http/Controllers/FormController.php
src/Http/Requests/FrontendFormRequest.php

I noticed that we arent checking if a form request wantsJson() in the failure message the way the success message is. 
This means using JS fetch() on the front end gets a redirect rather than JSON when you throw a validation exception in a FormSubmitted listener.
This PR fixes that to return the JSON response.

[4.x] Check if form request wantsJson

---

src/Http/Controllers/FormController.php
tests/Tags/Form/FormCreateTest.php

Before this PR if you silently fail a form submission through a `FormSubmitted` listener, or throw a validation exception in a `FormSubmitted` listener, any assets uploaded persist in the file system.
This PR changes that so any uploaded assets are removed.

[4.x] Remove any uploaded assets when submission silently fails or validation fails

---

src/Assets/Uploader.php

A potential solution to https://github.com/statamic/cms/issues/9512 is to not delete the temporary upload file until after the response has been sent. 
This avoids restructuring a lot of the upload logic or potentially introducing breaking changes.
Fixes #9512

[4.x] Delete temporary uploaded file after response

---

src/View/Antlers/Language/Runtime/PathDataManager.php
tests/Antlers/Runtime/ParametersTest.php

This PR corrects an issue when a `Values` object is returned by an augmented field, and is part of nested value call:
```antlers
{{ something:the_thing_that_augments_to_values:another_thing }}
```
The current buggy behavior will just return the `Values` object as the final result, regardless of what appears to the right of it.
This was discovered from the comment here: https://github.com/statamic/cms/pull/9503#issuecomment-1953164331
This change here is what triggered the bug condition: https://github.com/statamic/cms/pull/9499/files#diff-5c8d3eca361eba1478f85d8aa0cbf091c90260e0225230356b99aea0d37eb445R115
To trigger this bug, an Augmentable object has to augment to a Values object directly. The other fieldtypes that utilize `Values` always use them inside a wrapper array (which causes …

[4.x] Antlers: Resolve values from augmented values when there is more data to process

---

src/Stache/Indexes/Index.php

This PR fixes #9524 by adjusting how Stache index paths are created on Windows.
The breaking change happened here:
https://github.com/statamic/cms/pull/6131/files#diff-b0fa04a7e478fa6c45835c964c3230f6d455a170013366c3b6657e01519e2915R136
This PR adjusts the created path from `->` to `-]`, but only on Windows (to not impact any existing paths and cause unnecessary update challenges for non-Windows users). I'm not sure how to add a test for this, but the existing tests pass and the issues outlined in #6131 seem to be working fine for me on Windows.

[4.x] Corrects Stache problem on Windows

---

resources/css/components/modal.css
resources/css/core/utilities.css
resources/js/components/SessionExpiry.vue
resources/js/components/data-list/ColumnPicker.vue
resources/js/components/modals/KeyboardShortcutsModal.vue

This PR fixes #9473 by constraining the modal heights to 100% of the view height minus 1 pixel. This issue could also happen with the the Keyboard Shortcuts and Session Expiry modal windows if you *really* tried (I also added `overflow-y-auto` to the keyboards shortcut window so you could scroll and see content if you want a really short window).
The root cause seems to be inside `vue-js-modal`, where it gets confused when height is set to `auto` and the calculated height of the modal gets very close to the window's inner height on the problematic zoom levels. Constraining the height to `100vh` largely fixes the issue, but a noticeable shimmer would persist at the very bottom of the modal window. Adding the `- 1px` got rid of this shimmering.
The easiest way I found to reproduce this bug …

[4.x] Customize Columns Modal Height Thrashing

---

src/Fields/FieldTransformer.php

This pull request makes a small DX improvement by ensuring that Bard/Replicator/Grid sets always sit at the bottom of field configs, rather than in the midst of the various other config options.
The Bard & Replicator fieldtypes use `sets` for their sets & the Grid fieldtype uses `fields` for its set of fields. 
Closes #9432.

[5.x] Make Bard/Replicator/Grid sets sit at the bottom of the field configs

---

resources/js/components/field-validation/Rules.js
src/Fieldtypes/Bard.php

Adds the `accepted_if` validation rule to the field validation options. It turns out this exists and it's quite handy!
You can use this with the toggle fieldtype. E.g: toggle needs to be accepted (true) based on the value of another field.

[4.x] Add `accepted_if` validation rule

---

src/Tags/Locales.php
tests/Tags/LocalesTagTest.php

This PR fixes the `locales` tag inside a replicator, bard, or grid loop. 
Since Statamic v3.4 the `{{ id }}` inside a loop reflects the [ID of the item rather than the entry](https://statamic.dev/upgrade-guide/3-3-to-3-4#replicator-bard-and-grid-ids).
You could work around this issue by manually passing the `id` to the `locales` tag. But this is super cumbersome.
```antlers
{{ locales id="{page:id}" }}
{{ permalink }}
{{ /locales }}
```
So this PR gets the ID from the context's `page` instead.

[4.x] Fix locales tag inside replicator, bard, and grid

---

src/StaticCaching/NoCache/Session.php
src/StaticCaching/StaticCacheManager.php
tests/StaticCaching/ManagerTest.php
tests/StaticCaching/NoCacheSessionTest.php

Following on from https://github.com/statamic/cms/pull/9405 I've noticed that `php artisan cache:clear` clears the no cache store which goes hand in hand with the static cache URLS. This means you get missing no cache regions after a cache clear.
This PR ensures that the no cache stores use the same `static_cache` store as the static cache urls, which is cleared only when the static cache is cleared and not when the default cache is cleared.

[4.x] Also Use static_cache store for nocache

---

resources/css/components/items.css

This fixes a pixel gap on the top/bottom of relationship fieldtype items that's been hanging around for a while.
Before: 
After:

[4.x] Fix pixel gap on relationship fieldtype items

---

resources/js/components/fieldtypes/grid/FieldsFieldtype.vue

This pull request fixes an issue with the Grid Fieldtype where you couldn't configure field conditions for fields inside a Grid.
It was caused by my changes in #9379.
Fixes #9578.

[4.x] Fix field conditions in Grid fields

---

resources/css/components/items.css

Undoes: #9579 but apply new fix
Fixes: #9595

[4.x] Fix pixel gap on relationship fieldtype items and prevent padding issue

---

src/Contracts/Entries/EntryRepository.php

This pull request adds the `findOrFail` method to the `EntryRepository` interface.
The method was added into v4 in #9506, but without the method being added to the contract to avoid a breaking change.

[5.x] Add `findOrFail` method to `EntryRepository` interface

---

src/Tags/FluentTag.php

[According to the documentation](https://statamic.dev/blade#using-explicit-parameter-setters) we can use e.g. a filter-param with FluentTag's like this:
```php
Statamic::tag('collection:pages')->param('title:contains', 'pizza');
```
At least my IDE complains about the current docblock awaiting an array type.
This "fixes" this by changing the docblock to mixed.

[4.x] Fix docblock of FluentTag param method

---

src/Http/Requests/FrontendFormRequest.php

Sorry back with another tweak on this - the failedValidation change causes precognition errors to not return as they are JSON. My mistake.
Fixes: https://github.com/statamic/cms/issues/9598

[4.x] Only run custom validation errors when not precognitive

---

resources/js/components/blueprints/SuggestsConditionalFields.js

When working within a Replicator that imports a Fieldset with a prefix, the `SuggestsConditionalFields` logic converts the field configuration to a string, and results in an error.
A working repo with Fieldsets configured, and full details, is available:
[https://github.com/martyf/statamic-conditional-suggestions](https://github.com/martyf/statamic-conditional-suggestions)
The JS error looks like:
```
TypeError: can't access property "display", M.config is undefined
fieldOptions http://conditional-test.test/vendor/statamic/cp/build/assets/app-4e6d4633.js:172
fieldOptions http://conditional-test.test/vendor/statamic/cp/build/assets/app-4e6d4633.js:172
get http://conditional-test.test/vendor/statamic/cp/build/assets/app-4e6d4633.js:5
evaluate …
```

[4.x] Tweak SuggestsConditionalFields behaviour when dealing with a fields prefix.

---

resources/js/components/fieldtypes/TagsFieldtype.vue

This pull request fixes an issue where the "dropdown" in the Taggable Fieldtype was being hidden. This PR applies a fix suggested by @jacksleight on Discord.
Fixes #9594.

[4.x] Fix search dropdown being hidden on Taggable Fieldtype

---

src/Auth/Protect/Protection.php
tests/Auth/Protect/ProtectionTest.php

This pull request tweaks the `Protection@scheme` method so it uses the protection scheme from the data (eg. entry, term) _before_ it uses the site-wide default protection scheme.
Right now, if a site-wide protection scheme is configured, Statamic will use that before it checks the data.
Fixes #9552.

[4.x] Use protection scheme from data before using site-wide protection scheme

---

src/Fieldtypes/Bard.php
tests/Fieldtypes/BardTest.php

Filter away bad nodes during preprocessing instead of hard failing with exceptions.
Nodes without types would not be rendered anyway.

[4.x] Filter away bad bard nodes during preprocessing

---

routes/web.php
src/Auth/UserRepository.php
src/Http/Controllers/OAuthController.php
src/OAuth/Manager.php
src/OAuth/Provider.php
tests/OAuth/ProviderTest.php

This pull request fixes two issues preventing our Socialite/oAuth integration from working with SAML2 Socialite Providers, like Auth0/Okta.
Essentially, there were only two changes required to make our code work with SAML2:
* The `/oauth/{provider}/callback` route needs to accept `POST` requests, not just `GET` requests.
* When we're fetching the user via Socialite, we needed to call `->stateless()`, otherwise we'd get an error.
* However, the `->stateless()` option only works for *some* providers and not all of them. There's also no way for us to know programatically if a specific provider supports it or not - you need to simply test it and see.
* To workaround this, I've made it possible to specify `stateless` as a config option in the `providers` array in `config/statamic/oauth.php`... …

[4.x] OAuth improvements including support for SAML2 providers

---

src/View/View.php

This PR corrects an issue with Antlers sections not being yieldable in Blade layouts. The render method here https://github.com/statamic/cms/blob/4.x/src/View/View.php#L100 flushes the sections. The changes here put them back before rendering the layout.
After this, the following will now work again:
layout.blade.php
```blade
@yield('the_section')
```
template.antlers.html
```antlers
{{ section:the_section }}
The section contents.
{{ /section:the_section }}
```

[4.x] Fixes Antlers Sections not being yieldable in Blade layouts

---

src/Http/Requests/FrontendFormRequest.php

I've created an ongoing problem here, sorry about this.
The initial idea around https://github.com/statamic/cms/pull/9533 was to give the same response for XMLHttpRequest as for fetch() but maybe that was the wrong thing to do, lets just leave it as fetch() gets the 'normal' laravel error response format, rather than the amended response that Statamic is returning.
Lets just undo https://github.com/statamic/cms/pull/9599
Closes https://github.com/statamic/cms/issues/9627 
Closes https://github.com/statamic/cms/issues/9628

[4.x] Roll back to initial simple isAjax() check on front end forms

---

resources/js/components/blueprints/Section.vue
resources/js/components/blueprints/SuggestsConditionalFields.js
resources/js/components/fieldsets/EditForm.vue
resources/js/components/fieldtypes/grid/FieldsFieldtype.vue
resources/js/components/fieldtypes/replicator/SetsFieldtype.vue

Closes #9603
This PR passes along the current section where the suggestable fields are going to be used. This allows us to override the logic depending on a section.
When configuring a replicator, a section is a set. Inside SetsFieldtype, we'll accept that set and just use the fields on it.
Everywhere else, it continues to use the existing logic:
- standard "get all fields from all tabs" logic for top level fields
- "get all fields in this fieldset" when editing a fieldset
- etc

[4.x] Only suggest fields in the same replicator set

---

resources/js/components/field-validation/Builder.vue

This ensures the type passed into the component is an integer as expected, rather than a string.
You'd get a Vue warning whenever editing a field in the blueprint builder, but only when running npm run dev though. Annoying for us.
```
Settings.vue:276 [Vue warn]: Invalid prop: type check failed for prop "distance". Expected Number with value 5, got String with value "5".
```

[4.x] Fix prop type warning in validation builder

---

src/Data/HasOrigin.php

https://github.com/statamic/cms/issues/9631 (and similar other reports) seem to be being caused by the load order on multi-sites, specifically when an origin is loaded after a descendant (eg `de` loads before `en`).
As we syncOriginalState on load, and that now includes the origins, it blinks a null value, which persists.
This PR changes the origin approach from using Blink::once() to using a get/set approach, checking if the value is not null and early returning it. This should give most of the performance once() wanted, but also allow a re-query when the value is null.
Closes https://github.com/statamic/cms/issues/9631

[4.x] Only retrieve from origin blink cache when its not null

---

resources/js/components/entries/PublishForm.vue
src/Http/Controllers/CP/Collections/LocalizeEntryController.php
tests/Feature/Entries/LocalizeEntryTest.php

This pull request attempts to prevent users from being able to localize entries in other sites without the relevant "edit ... entries" permission.
This PR prevents it on the front-end by showing a tooltip when the user doesn't have enough permissions and also adds authorization in the controller to prevent it on the backend.
Fixes #9602.

[4.x] Prevent localizing entries without "edit ... entries" permission

---

src/Facades/Collection.php

If using named parameters, the Collection Facade has a wrong docblock. It's `$scopes`, not `$collection`. It also accepts arrays.

[4.x] Fix Collection::computed docblock

---

src/Http/Controllers/CP/Users/UsersController.php

Fix a bug in the destroy method of the UsersController, it was trying to get $user twice so the second call was throwing a stache error as its no longer a string.

[4.x] Fix bug in deleting users in the CP controller

---

config/users.php
resources/views/users/index.blade.php
src/Http/Controllers/CP/Users/UsersController.php
src/Tags/Users.php

This pull request introduces two new config options to Statamic's `users` config file, allowing developers to configure the default sort field & direction for the Users Listing Table.
At the moment, users are returned in ascending order by their `email`. However, it's possible that developers may wish users to be ordered by other fields like `last_login_at` instead.

[4.x] Users Listing: Allow for configuring default sort field & direction

---

src/Structures/TreeBuilder.php

This PR simply reuses the results of the `referenceExists` method when building up structure trees. While small, its noticeable across a large amounts of entries; more impactful changes planned for other PRs.

[5.x] Reuse results of `referenceExists` inside the structure `TreeBuilder`

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue
resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/replicator/Replicator.vue
resources/js/components/fieldtypes/replicator/Set.vue

This pull request displays the name of the set group, next to the name of the set.
The styles around the chevron look a bit off to me but I didn't have much luck in making it look better. Might need a bit of tweaking before being merged?
Closes statamic/ideas#1132.

[4.x] Bard & Replicators: Show set group in UI

---

src/Entries/Collection.php
tests/Data/Entries/CollectionTest.php

This pull request tweaks the logic in the `Collection@sortField` method so that by default, "structured collections" are ordered using the `order` field, instead of the `title` field.
We already default "orderable collections" (so, ordered collections where max depth = 1) to `order`, so that makes it true of "structured collections" too.
Closes #9429.
Related: #8810

[5.x] Ensure structured collections are ordered by `order` by default

---

composer.json
src/Actions/Concerns/MakesZips.php

This pull request upgrades the `maennchen/zipstream-php` package to v3, making the necessary code changes. 
Closes #9680.
Replaces #9679.

[5.x] Upgrade to Zipstream 3

---

src/Forms/Email.php

This pull request makes it so submission values take precedence over global set values when using Antlers variables in form email configurations.
In the case of #9696, since global sets called `global` don't need name-spacing and the global set had an `email` field, it conflicted with the `email` field present in the form submission.
Fixes #9696.
Related: https://github.com/statamic/cms/pull/8892 and eacf874.

[4.x] Ensure submission values take precedence over globals data

---

resources/views/widgets/collection.blade.php

This pull request fixes an issue where the "Create Entry" button on the collection widget in a multi-site install would always result in the entry being created in the "default" site, rather than the currently selected site.
Fixes #9678.

[4.x] Fix "Create Entry" button on collection widget in multisite

---

src/Modifiers/CoreModifiers.php

This pull request calls `->clone()` on the Carbon instance in the `modifyDate` modifier before it does any date modifying, so the original date instance doesn't change.
This change was initially PR'd by @jaygeorge in #9101. This PR just copies the over to the `master` branch, for v5. 
Related: #9100

[5.x] Clone the date in `modifyDate` modifier

---

resources/js/components/structures/PageTree.vue

This pull request fixes an issue where the navigation tree wouldn't load when attempting to edit a navigation, due to the `blueprints` prop not being passed in.
I've just ran into this myself after updating my site to the latest version.
Fixes #9708.
Caused by #9413.

[4.x] Fix broken navigation tree

---

composer.json

#9529 added support for PHPUnit 10, but kept 9 because we still needed it for older versions of Laravel.
Now that we've dropped Laravel 10, we can drop PHPUnit 9.

[5.x] PHPUnit 10

---

src/Http/Controllers/CP/Fields/FieldsController.php

This pull request fixes an issue when editing fieldsets where you'd run into this error message when applying changes to a field: "A field with the handle of ... already exists".
This validation message should only be displayed when there's already a field in the blueprint/fieldset with the same handle as the field you're applying.
For some reason, the code inside the `->when()` closure sometimes wasn't being called, meaning it wouldn't ignore the current field when looking at all fields for those with the same handle.
Fixes #9716.
Caused by #9337.

[4.x] Fix "A field with a handle of X already exists" error when editing fieldsets

---

resources/js/components/entries/Widget.vue
resources/views/widgets/collection.blade.php

This pull request fixes an issue where the pagination wasn't always displaying at the bottom of the collection widget if there was another widget in the same row that was longer.
Thanks to @robdekort for helping me with the fix.
Fixes #9439.

[4.x] Ensure pagination is always displayed at the bottom of collection widget

---

.github/workflows/tests.yml
composer.json

Waiting on https://github.com/orchestral/testbench to release 9.0

[5.x] Use stable versions of Laravel 11 and Testbench 9

---

resources/js/components/fieldtypes/grid/Stacked.vue
resources/js/components/publish/Field.vue

This PR builds on @duncanmcclean's https://github.com/statamic/cms/pull/9307 PR to fix more edge case styling issues around stacked grid rows...
- With different combinations of `fullscreen` and `hide_display` configured on `stacked` grids
- If you want to see the label, don't hide the label!
Here are some screenshots showing what it looks like after my proposed changes...
_Note: this is the edge case I need fixed for https://github.com/statamic/cms/pull/9632_

[4.x] Fix stacked grid margin-top styling

---

src/Data/DataCollection.php
src/Support/Comparator.php

This PR makes adjustments to the sorting and comparison implementation. For the multisort implementation itself, it prepares the sort column and direction outside of the `uasort` callback to reduce the number of `explode` calls. Additionally, it resolves the `Compare` instance once from the service container and reuses it.
For the Comparator, it moves the `class_exists(Collator::class)` call out of the `strings` method. The `Str::lower` calls were also refactored to just `mb_strtolower`.
These combined changes reduced control panel load times by ~ 1.5-2 seconds for 20K+ entries.

[5.x] Adjust sorting and comparison implementations

---

src/Listeners/ClearState.php
src/Statamic.php

Reverts #9638, at least temporarily. Putting it in a static property is too heavy handed. It turns out it doesn't always get cleared, e.g. in some tests. The first time you call isApiRoute it'll get saved to the static property then it'll persist across all tests.

[5.x] Revert isApiRoute static property cache

---

src/Preferences/CorePreferences.php

When the `Intl` extension is enabled, the dropdown options will be displayed in the appropriate languages. For example, the language name will also be displayed in the native language as hints:
If you have the CP currently set to another language, the labels will be in your language:
It also works with non-latin alphabets and RTL languages:
When the `Intl` extension is _not_ installed, you get the plain English options like would before this PR:
Additionally, we have Czech and Japanese translations but they were missing from this dropdown, so they've been added.

[4.x] Improve locale preference selector

---

src/Console/Commands/stubs/starter-kits/starter-kit.yaml.stub

We switched from Laravel Mix to Vite in `statamic/statamic` a while back. 
However, I noticed that the `starter-kit.yaml` stub still had Laravel Mix paths in it, so I've replaced them with Vite paths, so there's one less thing that needs tweaked when exporting your starter kit.

[4.x] Replace Mix paths with Vite paths in `starter-kit.yaml` stub

---

src/Providers/BroadcastServiceProvider.php

This pull request changes how we determine if Laravel's [broadcasting](https://laravel.com/docs/master/broadcasting#main-content) feature is enabled in order to be compatible with projects using the new Laravel 11 application structure.
Previously, we were checking if the `App\Providers\BroadcastServiceProvider` was uncommented in the user's `config/app.php` file.
However, with Laravel 11's new application structure, developers don't need to uncomment the service provider, instead they run `install:broadcasting` to install the relevant pieces.
After some testing, I've discovered that in both Laravel 10 and 11, with and without the new structure, that Laravel's own `BroadcastServiceProvider` is *also* being loaded, so we can check for that being loaded instead.

[5.x] Adjust broadcasting enabled check for Laravel 11

---

src/Stache/Repositories/EntryRepository.php
src/Stache/Repositories/TermRepository.php

This pull request makes a very small developer experience to the `Entry::whereCollection` and `Term::whereTaxonomy` methods where an exception will be thrown if the collection / taxonomy passed into the method does not exist. 
This PR does the same for the `whereInCollection`/`whereInTaxonomy` equivalents, where it'll loop through all the handles passed in and check if they exist. 
Closes statamic/ideas#1058.

[4.x] Throw exception from `whereCollection`/`whereTaxonomy` methods when collection/taxonomies don't exist

---

src/Search/Comb/Comb.php
tests/Search/CombTest.php

This PR adds slashes to the allowable characters in a Comb search query.
Closes https://github.com/statamic/cms/issues/9674
Closes https://github.com/statamic/cms/issues/4743

[4.x] Allow slashes in comb search queries

---

tests/Support/Concerns/TestsIlluminateArr.php

We have a copy of Laravel's Arr tests to ensure that our Arr class works properly.
This PR updates the `Arr::shuffle()` tests to reduce failure rates. See https://github.com/laravel/framework/pull/49769

[5.x] Reduce failure rate of Arr::shuffle() tests

---

resources/js/components/fieldtypes/CodeFieldtype.vue
resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue

This pull request fixes an issue with the Markdown fieldtype where you could edit the content even when the field was locked.
This was happening due to the `readOnly` state on the CoreMirror instance only being set when the fieldtype is being mounted. Changes to the `readOnly` prop weren't updating the CoreMirror state.
This PR also fixes an issue where the "Mode" dropdown was usable even when the Code Fieldtype was read-only.
Fixes statamic/collaboration#76.

[4.x] Fix markdown and code fieldtype read-only modes

---

resources/js/components/publish/Field.vue

This pull request fixes an issue where the "locking user" avatar isn't being displayed correctly. This PR tweaks the classes so they are the same as the avatars displayed at the top of the entry publish form.
Fixes statamic/collaboration#84.

[4.x] Fix field locking user avatar size

---

src/StarterKits/Installer.php
tests/Fakes/Composer/FakeComposer.php
tests/StarterKits/InstallTest.php

In a support request, a user was trying to install from specific branch by manually adding the repo to `require-dev` in their composer.json file:
```json
"require-dev": {
"<namespace>/<starter-kit-name>": "dev-develop"
},
```
But when Statamic runs `composer require --dev`, the composer require command stomps whatever is in their composer.json file, so it would just require the main/master branch.
This PR adds the ability to require a branch on the cli just as you would with `composer require package:branch`...

[4.x] Add ability to install starter kit from specific branch

---

src/Console/Commands/ProEnable.php
src/Statamic.php
tests/Console/Commands/ProEnableTest.php

When working on the `php please multisite` command for https://github.com/statamic/cms/pull/9632, I realized that `Statamic::enablePro()` updates the editions config, but https://github.com/statamic/cms/pull/9435 introduced smarter logic to enable Statamic Pro using an .env var.
If you have the newer editions config style with proper reference to the .env var, nothing has changed:
If it detects that your editions config is not properly referencing the .env var, it'll suggest the `--update-config` option:
When running with `--update-config`, it'll update both your .env var and your editions config:
And if it fails to update your editions config, you'll be given instructions on how to manually update this yourself:
_Note: I don't think the `--update-config` should be default behaviour, …

[4.x] Enable pro fix and improvements

---

src/Facades/AssetContainer.php

- Fix typo in return type of `AssetContainer` facade docblock
- Stumbled upon this through a phpstan error in a project

[4.x] Fix return type of AssetContainer:all()

---

resources/js/bootstrap/globals.js
resources/js/components/Listing.vue
resources/js/components/entries/Listing.vue
resources/js/components/terms/Listing.vue
resources/js/components/users/Listing.vue

This PR pushes the listing components `parameters` to the URL, so that you can bookmark, refresh and navigate back/forwards while maintaining the selected sort, filters, search, columns, page etc.
This is an opt-in feature of the listing mixin, since it might not make sense for all types of listing, especially when you have more than one on the same page (eg. Dashboard). To enable it set `pushQuery` to `true`.
I have enabled it for the main entry, term and user listings.
The `additionalParameters` are not pushed to the URL, since the listing mixin wont know what they are or how to handle them.
I asked ChatGPT for the `utf8atob` function, it seems to work fine but I have no idea if it's perfect.
Closes https://github.com/statamic/ideas/issues/93

[4.x] Push listing page state to URL query params

---

config/static_caching.php
src/StaticCaching/Cachers/Writer.php
src/StaticCaching/StaticCacheManager.php

This PR provides new configuration keys for the permissions with which to write static caching files and directories.
This also reduces the default permissions inline with what you'd expect based on Flysystem. See https://github.com/thephpleague/flysystem/blob/b25a361508c407563b34fac6f64a8a17a8819675/src/UnixVisibility/PortableVisibilityConverter.php#L13-L15
Closes https://github.com/statamic/cms/issues/9480

[4.x] Enable configuration of static cache file and directory permissions

---

src/Tags/Chunks.php
src/Tags/Concerns/GetsQueryResults.php
src/Tags/Concerns/OutputsItems.php
tests/Tags/Collection/EntriesTest.php

This PR add support for `chunk` on query builder variables in antlers, so you can now do:
```antlers
{{ assets_field chunk="2" }}
{{ chunk }}
{{ url }} - {{ alt }}
{{ /chunk }}
{{ /assets_field}}
```
Partially closes https://github.com/statamic/cms/issues/8195

[4.x] Support chunk on query builders in Antlers

---

src/Imaging/GlideManager.php

**Fixes** #9609
**Description**
- Make sure that reuploading an image will always clear the Glide cache, even if `append_original_filename` is enabled
**Required changes**
- Use the default Glide cache path callable during cache deletion
**Tests**
- No new tests for now
- First-time contributor here and having a bit of trouble finding my way through the test setup
- Might revisit that if I find the time

[4.x] Fix Glide cache not clearing on image reupload if `append_original_filename` is enabled

---

resources/lang/en/validation.php
src/Rules/ComposerPackage.php
src/Rules/EmailAvailable.php
tests/Console/Commands/MakeAddonTest.php
tests/Rules/ComposerPackageTest.php
tests/Rules/EmailAvailableTest.php
tests/Rules/ValidatesCustomRule.php

Was working on https://github.com/statamic/cms/pull/9778 and noticed that we are using a deprecated Laravel `Rule` contract. This PR adds test coverage and updates those implementations.

[5.x] Update deprecated contract usages in custom validation rules

---

src/Providers/ViewServiceProvider.php
src/View/Blade/BladeTagsDirective.php
src/View/Blade/TagsDirective.php
tests/View/Blade/TagsDirectiveTest.php

When working on Statamic projects that use Blade, we often run into needing to use `Statamic::tag` a lot. With a small directive like this we can simplify our usage of that a good bit.
This directive can be used in the following way:
```blade
@tags(['collection:products', 'taxonomy:types'])
```
This will give you camelCased variables called `$collectionProducts` and `$taxonomyTypes` that can then be used in your blade file.
Some other ways to use this:
```blade
@tags('collection:products')
```
```blade
@tags([
'products' => [
'tag' => 'collection:products',
],
'types' => [
'tag' => 'taxonomy:types',
'params' => ['color:is' => 'red'],
],
])
```
```blade
@tags([
'products' => 'collection:products',
'types' => ['taxonomy:types' => ['color:is' => 'red']],
])
```
I wasn't able to figure out a …

[4.x] Add @tags blade directive

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

Fixes https://github.com/statamic/cms/issues/9769
For whatever reason when you exit IME mode in Safari by hitting enter two extra update events are fired. The first of these reverts the new value back to the previous one and the second re-applies the new value. As the watcher is checking `this.value` when these two events are fired at the same time a race condition occurs and the revert update wins, resulting in the newly input text disappearing. At least that's what I think is happening.
Other browsers do not fire these two additional update events which is why they work fine.
This PR fixes it by comparing against the old value passed to the watcher rather than checking `this.value`, avoiding the race condition. It would be nicer if you could just detect and ignore these extra update …

[4.x] Fix Bard IME input in Safari

---

resources/js/components/live-preview/LivePreview.vue

Fixes https://github.com/statamic/cms/issues/9697
A regression was introduced in https://github.com/statamic/cms/pull/7899, which added the following to our `RevealerFieldtype.vue`...
```js
beforeDestroy() {
this.$store.commit(`publish/${this.storeName}/unsetRevealerField`, this.fieldPath);
},
```
Though this fix was/is necessary for when re-ordering bard/replicator sets (for example) with nested revealers, to ensure proper tracking of revealers in our VueX store, it caused an unintended side-effect when closing live preview...
^ When the live preview is closed, the destroy hooks on the fields in the live preview portal were happening AFTER the normal non-live-preview form gets re-mounted to the DOM. The reason this is an issue is because the mounted hooks are responsible for tracking …

[4.x] Fix Revealer state issues when closing live preview

---

src/Notifications/ActivateAccount.php

This pull request fixes an issue when customizing the body of the user activation email, where any new lines wouldn't show on separate lines in the email.

[4.x] Fix new lines not working in user activation email

---

resources/lang/en/validation.php
src/Http/Controllers/CP/Collections/EntriesController.php

This pull request ensures that the max depth of the parent is taken into consideration when validating an entry's parent.
Fixes #9388.

[4.x] Enforce max depth when validating entry parent

---

config/git.php

This pull request tweaks the Git commands in our default `git.php` config file, so the configured `binary` is used for Git commands.
Currently, the path to a custom Git binary has to be provided for in both the `binary` option and these two commands.
Closes #9767.

[4.x] Use the configured Git binary in commands

---

src/Entries/Entry.php
tests/Data/Entries/EntryTest.php

This pull request fixes an issue when serializing entries where routing is disabled for the collection, causing the `$entry->slug` property to be a closure, rather than a string.
This PR fixes that by evaluating the slug closure before the entry gets serialized. 
Fixes #9787.

[4.x] Fix serializing entries when `slug` property is a closure

---

composer.json

In PR #9695 I used `DB::connectUsing()` which was added in Laravel 10.40. This PR bumps the requirement to that.

[5.x] Bump Laravel requirement to support `DB::connectUsing()`

---

resources/js/components/data-list/FilterPresets.vue
resources/lang/en/messages.php

This pull request fixes an issue when renaming filter views, where the handle of the view wasn't updated when the view was renamed.
This meant it was possible to accidentally overwrite an existing view (for example: if you rename a view, then create a new view using the old view's name, it would overwrite the renamed view).
This PR fixes that issue by updating the handle of the view whenever a view is renamed (technically, it actually creates a new view and deletes the old one). 
This PR also adds a new warning message that'll show when creating/renaming a view with the same handle of an existing view:
Fixes #9703.

[4.x] Prevent overwriting filter views 

---

src/Entries/Collection.php
src/Stache/Repositories/CollectionRepository.php
tests/Data/Entries/CollectionTest.php

This PR refactors the `findByMount` method to use a cached mapping of mount ids and collection instances.

[5.x] Cache mounted collections

---

resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/replicator/Set.vue

This pull request fixes an issue where Bard & Replicator fields would completely break when they contain deleted sets.
Fixes #9814.
Caused by #9670.

[4.x] Fix deleted sets breaking Bard & Replicator

---

src/Licensing/Outpost.php
tests/Licensing/OutpostTest.php

We will now track the installed Laravel version to provide a better experience on statamic.com.

[4.x] Track Laravel version in the Outpost

---

src/Console/Processes/Git.php
tests/Git/GitProcessTest.php

This pull request fixes an issue with the Git integration where `Permanently added the ECDSA host key for IP address [...] to the list of known hosts` was being falsely logged as a Git error, even though it's just a warning.
Fixes #9817.

[4.x] Prevent "Permanently added the ECDSA host key for IP address" from being logged as a Git error

---

src/Http/Responses/DataResponse.php
tests/FakesContent.php
tests/FrontendTest.php

This pull request fixes an issue when using the [collection redirects feature](https://statamic.dev/collections#redirects), where localized entries of a redirect entry would return a 200 response, instead of a 301/302 redirect.
Fixes #9813.

[4.x] Ensure redirects work for localized entries

---

package-lock.json
package.json
resources/js/components/Echo.js
src/Providers/BroadcastServiceProvider.php

This pull request introduces support for [Laravel Reverb](https://laravel.com/docs/11.x/reverb), a self-hosted WebSockets server provided by a first-party Laravel package.
Previously, Statamic only supported using Pusher as a broadcasting driver so our Echo implementation was hardcoded to use Pusher (although, you could override it in JavaScript if you wanted). 
In adding support for Laravel Reverb, we've moved the generation of the Echo config into our `BroadcastServiceProvider` so we can easily return different config options depending on the `BROADCAST_CONNECTION` configured in your `.env`.

[5.x] Laravel Reverb support

---

.github/workflows/tests.yml

The failures must have something to do with GitHub deprecating Node versions.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
This PR is just kicking the can down the road. Explicitly requiring Node 16 fixes the errors. We'll need to figure this out properly eventually.

[4.x] Fix js tests GitHub action

---

src/Tags/Concerns/QueriesConditions.php

Wrap the value passed to queryInCondition and queryNotInCondition as they may not be arrays, as shown in the linked issue.
Closes https://github.com/statamic/cms/issues/9831

[4.x] Arr::wrap in/notIn values

---

resources/js/components/fieldtypes/bard/Set.vue
resources/js/components/fieldtypes/replicator/Set.vue

This pull request fixes an issue where the set group name & the set name would overlap in Safari 17.4 (17.3 would work fine). After a little bit of testing, it seems the fix is as simple as swapping `<template>` for `<span>`. Don't ask me why.
Fixes #9713.
Caused by #9670.

[4.x] Fix overlapping set group & set name in Safari

---

resources/lang/en/validation.php
src/Fieldtypes/Arr.php

I noticed this little oddity when working on https://github.com/statamic/cms/pull/9632, since we use array fieldtype in new sites configuration UI.
Before this PR, if you try to save a publish form with an array fieldtype that is set to `dynamic` mode, if you leave an empty key or value, you get weird data saved to your yaml:
```yaml
dynamically_keyed_array:
foo: Bar
'null': null
```
If you use `keyed` or `single` modes, key and value are both required for each submitted row. This PR adds validation to ensure you properly fill out each row.

[4.x] Improve array fieldtype validation for dynamically keyed fields

---

resources/js/components/forms/Listing.vue
resources/views/forms/show.blade.php

This PR adds an Edit Blueprint link to the form show page's action dropdown:
Saves going via the config page.

[4.x] Add Edit Blueprint link to form page dropdown

---

config/assets.php
src/Assets/Uploader.php
tests/Assets/AssetTest.php

This pull request makes it possible to disable the sanitization of SVG files when uploading to Statamic, which was introduced in #9365.
Most of the time, you'll want to keep SVG sanitization disabled. However, if you need to upload SVGs with dynamic portions **and** you trust your users (including those on the frontend if you're using form uploads), then this PR would allow for that:
```php
// config/statamic/assets.php
'svg_sanitization_on_upload' => false,
```
Ref support ticket: 5342

[4.x] Ability to disable SVG sanitization on upload

---

src/Entries/Collection.php
src/Entries/Entry.php
tests/Feature/Entries/MountingTest.php

When saving the mounted entry for a collection the URIs for the entries in that collection get only updated if the slug of the mounted entry has changed.
Fixes: https://github.com/statamic/cms/issues/9848

[4.x] Update URIs for mounted collection entries only if slug on mounted entry changed

---

src/Http/Controllers/CP/Collections/EntriesController.php
tests/Feature/Entries/UpdateEntryTest.php

This pull request fixes an issue with the recently introduced Max Depth validation on "Parent" fields, where you'd get the max depth validation message even if the collection has no max depth set.
I've added an additional check around the max depth validation to ensure the collection actually has a max depth set. This PR also adds some validation to prevent this from happening again.
Fixes #9847.

[4.x] Fix max depth validation on "Parent" field when collection has no max depth set

---

src/Tags/Concerns/RendersAttributes.php
src/Tags/Concerns/RendersForms.php
src/Tags/Svg.php
tests/Fieldtypes/IconTest.php
tests/Tags/Concerns/RendersAttributesTest.php
tests/Tags/Concerns/RendersFormsTest.php
tests/Tags/Form/FormCreateTest.php
tests/Tags/SvgTagTest.php
tests/Tags/User/ForgotPasswordFormTest.php
tests/Tags/User/LoginFormTest.php
tests/Tags/User/PasswordFormTest.php
tests/Tags/User/ProfileFormTest.php
tests/Tags/User/RegisterFormTest.php

This PR essentially reverts #9576.
Now, the only thing you'll need to change is that if you have a parameter that starts with `@`. Since #8887, prefixing a parameter with `@` will prevent parsing. You can get around this by prefixing with `attr:`, or using Vue/Alpine's alternate syntaxes:
```diff
{{ form:create
in="contact"
-   @click="submitForm"
+   attr:@click="submitForm"
+   (or x-bind:click="submitForm")
}}
```
However! We're planning to change the syntax of #8887 so you won't even need to do that.

[5.x] Revert requirement of prefixing attributes with `:attr`

---

src/View/Antlers/Language/Parser/AntlersNodeParser.php
src/View/Antlers/Language/Parser/DocumentParser.php
tests/Antlers/Parser/NodeParametersTest.php

This PR is an extension of #8887 except that it uses `\` instead of `@` to prevent parsing.
(It's actually what John originally pitched)
The `@` made upgrading to v5 more complicated than it needed to, because of how people would use Vue/Alpine event listeners like `@click`.

[5.x] Change @ to backslash to prevent parsing Antlers within tag parameters

---

src/Extend/AddonTestCase.php

Since eloquent driver was updated to use AddonTestCase its being showing warning about skipping tests, which I've worked out is due to a negative assertion count.
It seems to be due to it not triggering a call to version, so the simple fix is to allow this to be called zero or more time.

[5.x] Ensure expectation count isnt negative if Version is not called

---

.github/workflows/tests.yml

Since #9782, the entire Slack workflow job gets marked as skipped, and as a result the PR checks UI gets a little cluttered because it lists all the checks:
This PR moves the condition _into_ one of the steps of the job. ~Hopefully~ It does! it displays the job as successful so the UI goes back to the condensed version.
Super nitpicky thing but seeing the list of checks made me think something wasn't ready for merging.

[4.x] Adjust Slack action

---

resources/js/components/fieldtypes/bard/BardFieldtype.vue

Fixes https://github.com/statamic/cms/issues/9860
This was caused by the change in https://github.com/statamic/cms/pull/9788.
Tiptap isn't (always?) creating new objects when `onUpdate` fires or `getJSON` is called, so after the first update `oldJson` is exactly the same object as `json`, so the comparison passes and no further updates are fired.
This wasn't a problem before https://github.com/statamic/cms/pull/9788 because it was comparing against `this.value` which was already stringified in the previous update.

[4.x] Fix tables in Bard not saving updates

---

src/Http/Controllers/CP/Fields/FieldsController.php

This pull request adds `date` to the list of reserved field handles for Form blueprints. 
We don't pass any information about the _type_ of blueprint to the `FieldsController@update` method, so I'm just using the referrer URL to determine whether it's a form blueprint or not. 
Closes #9866.

[4.x] Add `date` to reserved fields for form blueprints

---

src/Http/Controllers/FrontendController.php
tests/Routing/RoutesTest.php

I love how these Statamic routes are so concise compared to using custom controllers. This PR adds the ability to use a closure for the data argument. So besides this
```php
Route::statamic('uri', 'view', ['foo' => 'bar']);
```
you can now also do this
```php
Route::statamic('uri', 'view', function () {
$bar = gatherDataExpensively();
return ['foo' => $bar];
});
```

[4.x] Support using closures for Statamic route data
