src/Stache/Repositories/EntryRepository.php
If you try to save an entry without a slug you receive this exception:
Slug validation rule for entries must use $site->handle()
=> Fixed slug validation rule for entries

resources/js/components/field-validation/Builder.vue
Laravel docs link was generated incorrectly if you are using Laravel 6
Using Laravel 5 the docs link works fine:
```
https://laravel.com/docs/5.8/validation#available-validation-rules
https://laravel.com/docs/5.7/validation#available-validation-rules
...
```
But from version 6, Laravel framework follows semver ... so docs url no longer contains the minor version but must use ".x".
```
https://laravel.com/docs/6.3/validation#available-validation-rules   <-- wrong
https://laravel.com/docs/6.x/validation#available-validation-rules   <-- ok
```
=> Fix Laravel docs link that uses semver from 6.x

src/Console/Commands/stubs/fieldtype.php.stub
As per a conversation on Discord, this PR updates the PHP stub generated by `php please make:fieldtype` to use `defaultValue` instead of the outdated `blank` method.
❤️
=> fix: use defaultValue in custom fieldtype PHP stub

resources/js/components/fieldtypes/TextFieldtype.vue, resources/js/components/inputs/Text.vue, resources/js/components/modals/ConfirmationModal.vue, src/Actions/RenameAsset.php
This PR uses Mousetrap to allow binding of the `enter` key while still focused inside a text fieldtype. This addresses #1040.
=> :sparkles: Enter now submits the rename action

resources/views/partials/head.blade.php, resources/views/partials/scripts.blade.php, resources/views/structures/show.blade.php, src/Http/Controllers/CP/Assets/ThumbnailController.php, src/Http/View/Composers/JavascriptComposer.php, src/Statamic.php
`Statamic::url()` is removed. It wasn't being used in core except by `assetUrl()` in the same class. It was also basing itself off the first site's URL. If you want to run all your Statamic sites in subdirectories (like in #1049), it would break. You should totally be able to do that, and you can after this PR.
Added `Statamic::vendorAssetUrl()` that gets a URL in the `public/vendor` directory. It now also uses Laravel's `asset()` helper, which will allow everything to be served correctly when using [Laravel Vapor](https://vapor.laravel.com). (Doesn't make Statamic 100% usable on Vapor, but it's a step in the right direction.)
`Statamic::assetUrl()` is now `cpAssetUrl()`. A bit more explicit.
Closes #1049
=> Change to Statamic url methods

resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue, resources/js/components/inputs/relationship/RelationshipInput.vue
Duplicate of #899 because the repository renaming and publishing broke that PR:
> ... by removing the disconnect via `selections` between its `:value` prop and what's emitted with `@input` events.
>
> Without this, passing in entry IDs in `:value` resulted in an `@input` event being emitted immediately (due to the watcher on `this.selection` and `data()` setting it to a clone of `this.value`).
>
> As a side effect, it became simpler and should be more performant because there are no watchers left.
>
> We found this bug when we wrapped the fieldtype, as always... :D
Now fixes #910, too.
=> make RelationshipFieldtype a proper reactive component

src/Data/Augmentable.php, src/Modifiers/CoreModifiers.php, src/Support/Arr.php, src/Tags/Tags.php, src/View/Antlers/Antlers.php, src/View/Antlers/Parser.php, tests/Support/ArrTest.php, tests/Tags/Collection/CollectionTest.php, tests/View/Antlers/ParserTest.php
A common problem people ran into in Statamic v2 was needing to ["fight the cascade"](https://docs.statamic.com/knowledge-base/wrong-variables).
For example: You're on an entry's page, looping through other entries using a collection tag, and one of the entries doesn't have a variable, but it exists on the outer entry. The entry in the loop will inherit the value from the outer entry, instead of being null/missing like you probably expect. (More detailed example in the link above)
The solution was to use the `scope` parameter and variable prefix to force the template to only use vars from that loop iteration.
This workaround was fine, but you'd have to know about it, and it became a frequent question needing to be answered.
To fight this problem, we made any tag pairs **not inherit** the …
=> Revert the scope / cascade behavior introduced in v3

resources/js/components/assets/Editor/FocalPointEditor.vue
Currently, the circle indicating the zoom level doesn't show up until after you manually change the zoom. Turning it into a computed property should make it work correctly.
=> fix focal point zoom reticle only showing up when manually changing zoom

config/assets.php
The driver for ImageMagick is called imagick.
See: http://image.intervention.io/getting_started/configuration
=> Wrong name for ImageMagick Driver

composer.json, src/Facades/Markdown.php, src/Fieldtypes/Markdown.php, src/Markdown/Manager.php, src/Markdown/Parser.php, src/Modifiers/CoreModifiers.php, src/Providers/MarkdownServiceProvider.php, src/Providers/StatamicServiceProvider.php, src/Support/Html.php, tests/Fieldtypes/MarkdownTest.php, tests/FrontendTest.php, tests/Markdown/ManagerTest.php, tests/Markdown/MarkdownTest.php, tests/Markdown/ParserTest.php, tests/View/Antlers/ParserTest.php
The commonmark package follows the spec, which is great, plus has an extension ecosystem so developers can more easily add custom features. Also, Laravel now uses it.
You can now do Markdown-y things using a dedicated facade.
``` php
Statamic\Facades\Markdown::parse('# Heading');
```
`Statamic\Support\Html::markdown('# Heading')` will still work (it just uses the facade now).
Any methods called on the facade are forwarded to the `default` parser.
You are free to create new parsers that are configured differently, and even have different extensions enabled.
``` php
$parser = Markdown::makeParser($config); // accepts an optional league/commonmark config array
$parser->addExtension(function () { ... }); // see extensibility section
$parser->parse('# Heading');
```
You can create them ahead …
=> [WIP] Markdown updates

src/Auth/User.php
The User class needs to implement the `Authorizable` contract same as the base [User](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Auth/User.php) in Laravel.
I found that without this, it breaks compatibility with other packages that expect a User object to be authorizable (ie. spatie/laravel-permissions) and we get this error:
> Argument 1 passed to Spatie\Permission\PermissionRegistrar::Spatie\Permission\{closure}() must be an instance of Illuminate\Contracts\Auth\Access\Authorizable, instance of Statamic\Auth\File\User given
Wasn't sure if this would break anything but I found that the same User object uses the `Authorizable` trait as well, so this shouldn't break anything.
=> Add Authorizable contract to User

resources/views/auth/passwords/email.blade.php, resources/views/blueprints/create.blade.php, resources/views/fieldsets/create.blade.php
These translation keys were being output instead of their values (`messages.forgot_password_enter_email` instead of `Enter your email address so we can send a reset password link.`). Fixed by prefixing with `statamic::` translation identifier.
=> Fix untranslated content

src/Auth/SetLastLoginTimestamp.php
Checks whether a User from the Login event is indeed a Statamic User - if so, we can let the listener do its thing. Fixes #1194
=> Execute setLastLogin() only when the given User is a Statamic User

resources/js/components/blueprints/Listing.vue, resources/js/components/fieldsets/Listing.vue
In ea2066d, a bug was created where blueprints & fieldsets would fail to delete because the URL would duplicate the `cp` part of the URL, causing it to look like this: `https://iamlittle.test/cp/cp/fields/blueprints/youtubeEmbed`.
It's because a `cp_url` was added around the url in listing components and it's also used inside `DeletesListingRow.js`.
After this fix, blueprints should be deletable once again!
=> Fix bug with deleting blueprints & fieldsets

src/Providers/AddonServiceProvider.php
Like when building a Laravel package, you should be able to boot policies from within your addon's Service Provider.
I've added the ability for that. All the developer needs to do is add the model and the policy to their service provider, like this:
```php
protected $policies = [
Product::class => ProductPolicy::class,
];
```
=> Ability to boot policies from AddonServiceProvider

src/Fields/LabeledValue.php, src/Fieldtypes/Checkboxes.php, src/Fieldtypes/Radio.php, src/Fieldtypes/Select.php, src/View/Antlers/Parser.php, tests/Fields/LabeledValueTest.php, tests/Fieldtypes/CheckboxesTest.php, tests/Fieldtypes/RadioTest.php, tests/Fieldtypes/SelectTest.php, tests/View/Antlers/ParserTest.php
This PR is a solution for being able to get a select/radio/checkboxes field's label within templates.
- In v2 you just couldn't.
- In v3 we made `select` fields augment straight to the label, and you could get the value by using the raw modifier. That seemed to cause more confusion. **This PR reverts it**, but adds a way to easily get the label on demand.
``` yaml
fields:
-
handle: country
field:
type: select
options:
au: Australia
ca: Canada
us: USA     
```
``` yaml
country: au
```
```
{{ country }}         // au
{{ country:label }}   // Australia
{{ country }}
{{ label }}         // Australia
{{ value }}         // au
{{ key }}           // au
{{ /country }}
```
This now works for `select`, `radio`, and `checkboxes` fieldtypes.
Parser bonus: Also now, when a `Value`'s augmented value …
=> Ability to get labels for select, radio, and checkboxes fieldtypes.

resources/js/components/fieldtypes/SelectFieldtype.vue
There were some problems with locking elements when multiple users were working on the same entry. To lock the elements correctly, we need to emit the events `@focus` and `@blur`.
=> Select-Fieldtype emit @focus and @blur events

src/Http/Controllers/CP/Users/UsersController.php
Before this fix, the `$id` variable was an instance of `User` instead of being an ID. So I figured that there is no point in finding a `$user` from a user instance as we already have one.
Hopefully that makes sense 😃
Here's a [Flare link](https://flareapp.io/share/lm2Q0A5x) for the bug I was hitting.
=> Fixed issue with loading the user detail page

resources/views/widgets/collection.blade.php, src/Widgets/Collection.php
Allows for `sort` or `order_by` control (like collection tag) on collection widget.  ie)
```php
[
'type' => 'collection',
'collection' => 'daughters',
'width' => 50,
'limit' => 5,
'sort' => 'non_favourite:desc',
],
```
Defaults to `date:desc` on dated collections, and `title:asc` on non-dated collections.
Closes #1342.
=> Add `sort` config to collection widget. References #1342.

resources/js/components/data-list/Table.vue
The svg arrow for sortable columns is always rendered at the table head of data listing (visible or not). This has the effect that the lines jump (screenshot).
I updated the condition because it looks like the arrow is only displayed in the selected column. See if that works for you.
=> Data-List // Table // update display of svg in sortable column

resources/js/components/entries/Widget.vue
If a collections widget does not have more than 1 page, then the background of the pagination element will be displayed with no links.
This pull request hides the pagination background element if there is only one page.
=> Don't show widget pagination if only has single page

src/View/Debugbar/AddRequestMessage.php, src/View/Debugbar/AddVariables.php
If you install with `composer install` through a lock file, debugbar can be installed which causes it to be bound into the container. It's still disabled though.
However not checking that debugbar is enabled will cause the view to always get all variables and can cause performance problems
The callgraph below shows about 10.000 calls to flatMap that don't need to be happening when the debugbar is disabled
=> 🚀 Debugbar can be bound but not enabled which can cause performance issues

src/Entries/Entry.php
Getting the blueprint of an Entry is a fairly expensive operation, and balloons up to a lot of internal calls, if we store this once for the request it helps the performance quite a bit.
Call graph: https://blackfire.io/profiles/bb1a8568-12c4-4214-afbf-b7176f771108/graph
Starts from here:
And ends with about 30k calls here
=> 🚀 Store an entry's blueprint in the Blink cache

resources/views/fieldsets/edit.blade.php
The breadcrumb link on the edit page of a fieldset was not working. This fixes that.
=> Fix Edit Fieldset breadcrumb link

src/Http/Controllers/CP/Taxonomies/TermsController.php
A namespacing issue meant non-superusers were unable to create terms even if they had the permission to do so.
=> Fixed new term authorisation.

resources/js/components/assets/Folder/Folder.vue, resources/js/components/keys/Binding.js, resources/js/components/keys/Keys.js
The asset's folder dialog throw this error in console when it's opened:
This PR restore the ability to use Mousetrap's `stopCallback` method to allow key commands with a focused input
=> Fix mousetrap on asset’s folder dialog

src/Tags/Concerns/RendersForms.php
Fixes #1473, but I'm not sure if there was a specific reason you were doing it the way you were.
The issue occurs because the action attr ends up as: `action:http://localhost:8000/!/forms` and gets split into three bits: `action`, `http://localhost` and `8000/!/forms` when it should be two: `action` and `http://localhost:8000/!/forms`
=> Use `explode` to split form attrs

src/Entries/Collection.php, src/Tags/ArrayAccessor.php, src/Tags/Collection/Collection.php, tests/Data/Entries/CollectionTest.php, tests/Tags/Collection/CollectionTest.php
Collection objects can be augmented. You can access their data in templates.
The collection tag/variable without any params that indicate how to retrieve a collection (eg. `from`, `in`, etc) will just let you access the current context's collection.
```
{{ collection }} {{ title }} {{ /collection }} // Blog blog
```
With one of those params, it'll run the tag:
```
{{ collection from="blog" }} {{ title }}, {{ /collection }} // Entry One, Entry Two
```
When used as a single tag, it'll get the handle:
```
{{ collection }} // blog
```
As a single tag, you can get nested values:
```
{{ collection:title }} // Blog
```
Caveat: The tag pair plus nested syntax will conflict:
```
{{ collection:title }}
{{ handle }}
{{ /collection:title }}
```
Would you think this should loop through entries in the …
=> Collection augmentation

src/Http/Controllers/CP/Users/PasswordController.php
I've fixed a bug where users were getting 'Unable to change password' when trying to reset user passwords through the Control Panel.
Fixes #1561 and #1556
=> Fix Password Resets from the Control Panel

src/Validation/UniqueUserValue.php
The value of `$except` is a string in a fresh v3 install (for me at least), the identical-to comparison operator therefore means it's not possible to edit an existing user. Typecasting `$except` to an integer fixes this.
=> Fixes save of existing user for database users

resources/js/components/data-list/Actions.vue, src/Http/Controllers/CP/ActionController.php
By returning the Action's `run` method we can check its data. This allows us to return a `redirect` URL as per suggested in https://github.com/statamic/cms/issues/1496. Tested locally and works nicely, but if this isn't the implementation you want feel free to close.
=> Add ability to return a redirect from an Action (closes #1496)

src/Actions/Publish.php, src/Actions/Unpublish.php
Previously, both `Publish` and `Unpublish` would be shown for entries in data table regardless of whether or not they are already published or not.
This pull request fixes that issue. There's probably a cleaner way to do it with ternary operators.
Fixes #1614
=> Don't show both 'Publish' and 'Unpublish'

resources/js/components/entries/PublishForm.vue, src/Entries/Entry.php, src/Http/Controllers/CP/Collections/EntriesController.php
This references #1183. It's possible we may want to _explicitly_ disable Live Preview if there are cases where you may want to be able to render a live preview with an external URL (e.g. headless), but I'm not sure if that's possible or even makes sense really. Hence the PR.
=> Hide the Live Preview when a collection has no route

resources/js/components/data-list/BulkActions.vue, src/Actions/Action.php
Hi gents! 
This PR allows for Actions to only be shown in the Inline Actions contextual menu, hiding it from the Bulk Actions area at the top of Data Lists.
My particular use-case for this is for Impersonator; allowing users to start an Impersonation session directly from the Users Listing view. Since users are only ever allowed to choose 1 account to authenticate as, it makes sense to remove it from Bulk Actions and only show it in a singular contextual menu.
As you'll see from the code changes, all it takes is 1 new (optional) property in an Action class, which defaults to show both Action menus from the abstract class:
```
abstract class Action implements Arrayable
{
protected $inlineOnly = false;
//...
```
I thought about the naming of this property for a while and landed on …
=> Allow Actions to only be shown in Inline Actions menu

src/Entries/Entry.php
This PR fixes an issue I was having where the Entry queries for a user even if updated_by is not set. This is when the user repository is set to eloquent.
It's similar to the existing check on `lastModified()` and `UserRepository` already returns `null` if the user doesn't exist in the database.
=> Fix issue where query is still performed when updated_by is null

resources/js/components/assets/Browser/Browser.vue, resources/js/components/assets/Editor/Editor.vue, resources/js/components/assets/Editor/EditorActions.vue, resources/js/components/collections/View.vue, resources/js/components/data-list/Actions.js, resources/js/components/data-list/BulkActions.vue, resources/js/components/data-list/HasActions.js, resources/js/components/data-list/InlineActions.vue, resources/js/components/entries/Listing.vue, resources/js/components/forms/SubmissionListing.vue, resources/js/components/terms/Listing.vue, resources/js/components/users/Listing.vue, resources/views/collections/show.blade.php, resources/views/forms/show.blade.php, resources/views/taxonomies/show.blade.php, resources/views/usergroups/show.blade.php, resources/views/users/index.blade.php, routes/cp.php, src/Actions/Action.php, src/Actions/ActionRepository.php, src/Actions/Delete.php, src/Actions/MoveAsset.php, src/Actions/Publish.php, src/Actions/RenameAsset.php, src/Actions/SendPasswordReset.php, src/Actions/Unpublish.php, src/Http/Controllers/CP/ActionController.php, src/Http/Resources/CP/Assets/Asset.php, src/Http/Resources/CP/Assets/FolderAssetsCollection.php, tests/Feature/Assets/BrowserTest.php
- Adds `visibleToBulk()` method to better control when bulk actions are shown.
- Implements @jackmcdade's suggestion (see https://github.com/statamic/cms/pull/1650#issuecomment-611816554) on publish/unpublish actions.
- Removes `$bulk` property.
- Introduced by https://github.com/statamic/cms/pull/1612; Can use `visibleToBulk()` method instead.
- Renames `filter()` to `visibleTo()`.
- For consistency with `visibleToBulk()` and our `visibleTo()` pattern.
=> Improve actions

resources/js/components/data-list/Actions.vue, src/Http/Controllers/CP/ActionController.php
This pr should allow the creation of actions with file downloads.
In a project I have created an action to allow the user to download selected entries to an excel spreadsheet.
Unfortunately this does not work, because the `ActionController` does not actually return the actions return value and therefore does not respond with my file.
My action looks as follows:
```php
public function run($items, $values)
{
$filename = 'file.xlsx';
$file = Excel::download(collect($items), $filename);
return $file;
}
```
A simple return on the execution of my action in the `ActionController` solves this problem.
In the frontend the `Actions.vue` mixin only needs to handle the response accordingly. I have added the code for that as well.
The only not so clean thing about my changes is the `responseType: …
=> Allow file download on Action response

composer.json, src/Exceptions/Handler.php, src/Http/Resources/API/AssetResource.php, src/Http/Resources/API/EntryResource.php, src/Http/Resources/API/GlobalSetResource.php, src/Http/Resources/API/TermResource.php, src/Http/Resources/API/UserResource.php, src/Providers/ExtensionServiceProvider.php
Not sure if this is something you're open to, but this seems to get Statamic up to Laravel 7, although you need to wait for https://github.com/mrclay/minify/pull/666 to actually get there.
However all of these changes should work for L5.8+ regardless to be ready!
=> Updates as per Laravel 7 upgrade guide

src/Providers/EventServiceProvider.php
The `\Statamic\Stache\Listeners\SaveCreatedId` class no longer exists in the Statamic codebase, so there should be no need to point to the listener.
(Originally noticed this because [lorisleiva/laravel-actions](https://github.com/lorisleiva/laravel-actions) tried reading the class and it doesn't exist so was throwing an error)
=> Remove reference to SaveCreatedId listener

src/Sites/Site.php, tests/Facades/ConfigTest.php, tests/Sites/SiteTest.php, tests/Sites/SitesTest.php, tests/View/CascadeTest.php
Things like `{{ site_url }}` would force a trailing slash. Sometimes unnecessary, usually ugly.
Now it doesn't. If your site url ends with a slash, it'll get stripped off.
```php
'sites' => [
'default' => [
'url' => 'http://mysite.com/', // becomes 'http://mysite.com'
]
]
```
A relative urls and subdirectories still work:
- `/` stays as `/`
- `/subdirectory/` becomes `/subdirectory`
=> Site URLs shouldn't have trailing slashes

resources/js/components/blueprints/Fields.vue, resources/js/components/blueprints/LinkFields.vue, resources/js/components/fieldsets/EditForm.vue, resources/views/fieldsets/edit.blade.php, src/Fields/Fieldset.php, src/Http/Controllers/CP/Fields/FieldsetController.php, tests/Fakes/Fieldtypes/FieldtypeWithPreprocessableConfigField.php, tests/Feature/Fieldsets/UpdateFieldsetTest.php, tests/Fields/BlueprintRepositoryTest.php, tests/Fields/BlueprintTest.php, tests/Fields/FieldRepositoryTest.php, tests/Fields/FieldsTest.php, tests/Fields/FieldsetRepositoryTest.php, tests/Fields/FieldsetTest.php, tests/Fieldtypes/NestedFieldsTest.php
In order to support importing fieldsets into fieldsets, the fieldset syntax needs to use the same one as blueprints do.
ie. Instead of this:
```
fields:
myfield:
type: text
```
It should be
```
fields:
-
handle: myfield
field:
type: text
```
Then we're able to use the `import` syntax just like Blueprints.
Closes statamic/ideas#130
=> Fieldsets use Blueprint syntax

src/Http/Controllers/CP/Assets/ThumbnailController.php
The `generate()` function in ThumbnailController.php has a potential deadlock which occurs when an exception is thrown before the mutex is released. In this case the mutex will be locked for the next two hours. Subsequent requests to the same thumbnail url will hang in `waitIfProcessing()`. Depending on the php server setup and the configured timeouts this can lead to a situation where these requests pile up and exhaust the available server processes.
This PR adds a finally block to make sure the mutex gets released in case of an error.
Also the cache time of two hours seems a bit high to me. Is there a specific reason for that?
=> Fix deadlock in ThumbnailController::generate

resources/views/forms/submission.blade.php, src/Forms/Form.php
`m` is for month and `i` for minutes 
Fix for #1706 issue
=> Fix for wrong time format at forms. Closes #1706

src/Tags/Structure.php
Implementing the nav tag's `depth` variable...
PR'ing because I'm not sure the implications with and without `root: true`.
=> Nav tag `depth` variable

config/users.php, resources/views/auth/passwords/reset.blade.php, routes/web.php, src/Actions/SendPasswordReset.php, src/Auth/Passwords/PasswordBrokerManager.php, src/Auth/Passwords/PasswordReset.php, src/Auth/Passwords/TokenRepository.php, src/Auth/User.php, src/Http/Controllers/ActivateAccountController.php, src/Http/Controllers/CP/Users/UsersController.php, src/Http/Controllers/ForgotPasswordController.php, src/Http/Controllers/ResetPasswordController.php, src/Notifications/ActivateAccount.php, src/Notifications/PasswordReset.php
When creating an account for someone else, we send an activation email which is basically just a password reset with different words.
The reset link in there expires after an hour (by default) which is fine, but when creating a new user, it might be too short of a time before they even see the email sitting in their inbox.
This PR separates regular password resets from account activations.
Previously when you try to reset a password, it would change the notification based on whether you had a password. Now, we'll send an activation notification when you create a user, and a regular password reset everywhere else.
Laravel uses a [password broker](https://github.com/laravel/laravel/blob/master/config/auth.php#L96-L101) to manage password reset tokens. The broker can have an expiration …
=> Separate reset password and account activation

src/StaticCaching/StaticCacheManager.php
Fixes #1841
Exclusions for the static caching half measure are currently not working. The bug can be reproduced following the steps in the issue above.
It looks like the config data in StaticCacheManager::getConfig is pulling directly from "statamic.static_caching.strategies.$name", but the AbstractCacher expects an exclude key in the config data, which was not being set. This one-line fix ensures the exclude data is also passed along to the config.
=> Add missing exclude data to StaticCacheManager::getConfig

src/Entries/Entry.php, src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Entries.php, src/Fieldtypes/Taxonomy.php, src/Taxonomies/LocalizedTerm.php, tests/Fieldtypes/AssetsTest.php, tests/Fieldtypes/EntriesTest.php, tests/Fieldtypes/TaxonomyTest.php
Currently, fieldtypes are responsible for determining what gets used when shallow augmenting an item. This PR moves the responsibility into the items themselves. (Entry, Asset, Term, etc)
Now if you want to customize what keys are used, you can override a single method on the item as outlined in #1897
```php
public function register()
{
$this->app->bind(\Statamic\Contracts\Assets\Asset::class, \App\CustomAsset::class);
}
```
``` php
class CustomAsset extends Asset
{
protected function shallowAugmentedArrayKeys()
{
return ['url', 'alt'];
}
}
```
Closes #1757
=> Shallow augmented fields come from the items

composer.json, src/Console/Processes/Composer.php, src/Extend/Manifest.php, tests/Composer/ComposerTest.php
You can try out Composer v2 alpha by running `composer self-update --snapshot`. It's nice and snappy.
The main issue you would likely run into was not being able to install Statamic because the pixelfear/composer-dist-plugin was not compatible with Composer 2. The [0.1.4 release](https://github.com/pixelfear/composer-dist-plugin/releases/tag/v0.1.4) solves this.
This PR fixes a few related things too.
- Addons not being discovered because the installed.json changed.
- Composer commands (inside the CP, etc) will now use the global composer rather than a local one. This prevents composer 2 being used on the command line but composer 1 being used in the CP.
- The --no-plugins flag is used when grabbing JSON from composer output to prevent any warnings from making it unusable.
=> Composer 2 Support

resources/js/app.js, resources/js/vendor/eqcss/index.js
This PR attempts to fix #1171 and #1915.
With lots of fields on a page, things start to slow down as you're typing. Looks like it's because of EQCSS.
Thanks @JonKaric in [this comment](https://github.com/statamic/cms/issues/1171#issuecomment-621284583) for working out that the main culprit is that eqcss is doing work on every `input` event. (Just about every keystroke).
I brought eqcss inline and removed the input binding. It also does work on mousemove, but I figure if you're busy typing away, you probably aren't also moving your mouse.
If there are any issues because of removing this, we can tackle it later. They'd likely only be minor cosmetic issues, if any.
Closes #1171 
Closes #1915
=> EQCSS optimization

src/Tags/Session.php, tests/Tags/SessionTagTest.php
I needed to grab a session key that was a local variable (specifically, `page:slug`), and `session:page:view` did not work.
Added a convenience method `{{ session:value :key="your-var" }}` so I could do `{{ session:value :key="page:slug" }}`.
Includes test!
=> Add session:value and test

src/Fields/Value.php, src/Fieldtypes/Bard/Augmentor.php, src/Tags/Context.php, src/Tags/Tags.php, src/View/Antlers/Antlers.php, src/View/Antlers/AntlersLoop.php, src/View/Antlers/AntlersString.php, src/View/Antlers/Engine.php, src/View/Antlers/Parser.php, src/View/View.php, tests/Tags/ContextTest.php, tests/Tags/ThemeTagsTest.php, tests/View/Antlers/ParserTest.php
tldr: Setting `antlers: true` will work better.
Fields have `antlers: false` by default.
If you add `{{ stuff }}` to your fields, you'll see `{{ stuff }}`.
If you set `antlers: true`, `{{ stuff }}` will get parsed and swapped with the value of `stuff`.
---
A little info on noparse.
When the Antlers parser wants to avoid parsing stuff (eg. because you wrapped something with `{{ noparse }}...{{ /noparse }}`) it'll "extract" it and replace it with `noparse_somehash`.
Since there may be multiple parses (eg. nested loops, partials, etc), we hold all the extractions until the very end.
Once everything is done, after the template gets injected into the layout, *then* we get the parser to put back all the extracted noparses. That way, we avoid them accidentally getting parsed.
One problem was …
=> Antlers parsing and noparse tweaks

src/Stache/Stores/CollectionEntriesStore.php
Cleaning the path fixes the comparsion between the directory and the file path which contained backslashes.
Fixes #1933
=> Fix #1933: Multisite on windows

src/Extend/Manifest.php, src/Providers/AddonServiceProvider.php
The docs reference a structure similar to the following for an addon:
```
/
| src/
| resources/
| views/
```
but the `bootViews` method currently generates a path that tries to load views from a folder that will never exist, something like `addon/srcresources/views`.
This PR fixes that by adding the necessary path part (`/../`) to the method to make this work as expected.
=> Fix AddonServiceProvider bootViews method

resources/js/components/collections/View.vue, resources/js/components/structures/Branch.vue
This PR removes the menu entry "Create child" from the root node menu.
Closes #1948
=> Remove the menu entry "Create child" on root node in collections

src/Tags/Collection/Entries.php, src/Tags/Concerns/GetsQueryResults.php, tests/Tags/Collection/EntriesTest.php
We want to be able to support using `offset` with `paginate` on query tags, ie)
```
{{ collection:news as="posts" offset="1" paginate="12" }}
```
To make it easier to style featured posts differently, and because it was something we supported in v2.
PS. This had to be done on the tag level, because there doesn't seem to be an Eloquent-friendly way to do it on the query builder.
=> Pagination with offset

src/Data/HasOrigin.php
After the last two updates I had to change this core file manually to get my multisite website running. The method checks the attribute `$this->origin`, not what comes out of the method `$this->origin()`. In my case this was a problem, because in the method `values()` it actually checks the attribute through `hasOrigin()` (which seemingly is not null) but then uses the method (which is null). The website then breaks with the error `Call to a member function values() on null`.
=> Fix false positive return from hasOrigin()

composer.json
We moved html-to-prosemirror and prosemirror-to-html to a new organization, more on this here: https://github.com/scrumpy/tiptap/issues/759
See also:
https://packagist.org/packages/scrumpy/html-to-prosemirror
https://packagist.org/packages/scrumpy/prosemirror-to-html
TL;DR 
* tiptap and related packages move to a new organization name, but it’s the same people (me and others)
* we plan to focus on open source work, so it’s good news
=> use html-to-prosemirror and prosemirror-to-html from new namespace

src/Facades/Entry.php
The `find` method, which should be one of the most important ones, has not been included. 
I did as well point to the contact class only.
=> Update the Entry Facade Doc blocks

resources/js/components/AddonList.vue, resources/js/components/updater/Updater.vue
When running in a sub-directory (e.g. domain.com/docs), some axios requests to cp routes are not passed through the `cp_url` function. This results in 404s because they go to `domain.com` instead of `domain.com/docs`.
This is preventing the Updates and Addons pages from working.
=> Fix cp axios requests when in subdirectory

src/Forms/Email.php, tests/Forms/EmailTest.php
Fixes #2131 by casting AntlerString to string so Laravel Mailer will know it can use the view.
=> Fix for Email.php to evaluate html view AntlerString for use with Mailer

src/Console/Commands/DebugCommand.php, src/Providers/ConsoleServiceProvider.php
After talking with Jason yesterday, I've created a command which can be run by a user and will output information, like Statamic version, PHP version, installed addons etc.
It should be helpful to replace the bottom part in Github issues asking about environment information etc, where it could ask users to run this command instead and paste the output into the Github issue.
Implements #267. Let me know if there's any changes you'd like me to make to this.
I've taken a screenshot of the command output.
=> Debug Command

resources/js/components/collections/View.vue
This pull request fixes an issue where a user who doesn't have permission to create an entry would be shown the 'Create Entry' button on the entries listing page in the Control Panel.
=> Don't show 'Create Entry' button if the user isn't authorised to

src/Stache/Stores/UsersStore.php
This pull request fixes an issue where if a user was created manually (ie. in the files) and it didn't already contain an ID, one would be generated. This fix stops this issue from happening:
```
(1/1) ErrorExceptionfile_put_contents(.../storage/framework/cache/data/stache/items/users/): failed to open stream: Is a directory
```
I fixed the issue by copying the equivalent on the `CollectionEntriesStore`. I left out the `$idGenerated` function, wasn't sure what that did and if it was needed, let me know if you'd like me to add that.
This pull request fixes #2138. I copied the user file from that issue to ensure it was fixed, and it worked!
=> Fix ID not being generated for manually created users

src/Forms/Tags.php
Whilst looking into the Forms tags code and playing around with it, I noticed the debug data was never loaded in the debug bar due to a small typo (`debug_bar` vs `debugbar`) on line 213.
Also couldn't find any references to `$this->blink` so I fixed that as well. I assumed the default store suffices for now.
I thought I'd fix it and clean it up a bit 👍
=> Fix and clean up form data in debug bar.

src/Providers/AddonServiceProvider.php
I had to open a new PR because I had to change the target branch. This is the same PR as #2135. 
An addon's config and translations now automatically merge and load. 
You can also publish the files:
```bash
// Config
vendor:publish --tag="addon-slug-config"
// Translations
vendor:publish --tag="addon-slug-translations"
```
If you don't want to merge the config and load the translations you can opt-out of it by setting the following properties in the addon's Service Provider:
```php
protected $config = false;
protected $translations = false;
```
=> Make configs and translations publishable

resources/js/components/fieldtypes/TemplateFieldtype.vue
if `hide_partials` is true, also remove the partials that are in the `partials` folder.
=> ignore partials when they’re in the ‘partials’ folder

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
This pull request will set the locale to `default` whenever a new `Entry` is created. This means when using the `Entry` facade, you'll no longer need to use the `->locale()` method when creating/making an entry (unless you want to override it, obviously).
I've added a new test for this change and updated an existing one. Although, maybe we don't need that extra test and the existing one is fine?
This pull request fixes #1389.
=> Set locale to 'default' when creating a new Entry

src/Facades/Term.php
Was doing some source-diving into the Term facade & repository this morning. Discovered this small thing in the facade which would cause the IDE intelligence to show `$collection` instead of `$taxonomy` in the method name. I've fixed it up, per [the repositories method signature](https://github.com/statamic/cms/blob/2547cc6a0403de057130e599c66a3c94d6359531/src/Stache/Repositories/TermRepository.php#L82).
=> IDE Hint change

resources/sass/components/fieldtypes/section.scss
The current specificity of field type labels leaves a section field type looking a bit off. This fixes the specificity for styling that field type label and changes it to just have equal margin on top and bottom.
Before:
After:
=> Fix section fieldtype label margin

src/Events/GlideImageGenerated.php, src/Imaging/ImageGenerator.php
This PR adds a missing event to /Statamic/Imaging/ImageGenerator. It was already noted as a TODO and is implemented pretty much the same as it was in V2.
=> Add GlideImageGenerated event to ImageGenerator

src/Fields/Field.php, src/Http/Controllers/CP/Fields/FieldsController.php
This pull request makes it so fields with the `Section` fieldtype should no longer be listable or appear as columns anywhere in the CP.
* If a field is has the type of `section`, it will no longer be listable and will no longer show as as column when you click the 'column dropdown' on the collection entries listing page.
* When a user adds/updates a section field in the Fieldset/Blueprint builder, they will no longer see the option to configure if it's listable or not. I thought it would make sense to hide/remove this option as we override it anyway in the `Field` class.
It fixes #2117 and fixes #2013.
=> Section Fieldtype should not be listable

resources/sass/components/publish.scss
This pull request sets the width of the sidebar on the publish forms to a fixed 300px, instead of it being `max-width`. Without this being a fixed width, it causes issues like in the below screenshot.
This pull request fixes #2081.
=> Sidebar width should be fixed

SECURITY.md
I can't find any modern equivalent to the original link, but the one I've enclosed gives some information? Or might be worth replacing with some other source. 👍
**EDIT: Actually the link I've provided does seem to be the updated source as per**  (legacy / archival site) https://wiki.owasp.org/index.php/open_redirect
=> Security Info: OWASP Open Redirect Link is dead

config/system.php, src/Tags/Cache.php
This pull request adds in the `cache_tags_enabled` configuration option that existed in Statamic v2 [(docs)](https://v2.statamic.com/caching#frag-off).
I've added the configuration option in the `system.php` file. I wasn't sure where would be best so I popped it in there. The help text for it could also be improved. 
I'm leaving this as a draft pull request for now until I have some time to properly test it.
This PR closes #2418.
=> Bring 'cache_tags_enabled' configuration option back in v3

resources/views/extend/forms/fields/default.antlers.html, resources/views/extend/forms/fields/text.antlers.html
The text and textarea fieldtypes have a placeholder field (when created in the cp), but the default templates to render those fields don't. This pull request would render them as expected.
=> Add placeholder attr to form fields

resources/views/utilities/email.blade.php
In Utilities > Email configuration, if a value is empty, an empty `<code>` tag is shown:
=> Email settings: prevent show empty <code>

resources/views/widgets/getting-started.blade.php
This pull request fixes the description text for 'Enable Pro Mode' on the getting started widget.
This PR fixes #2432.
=> Fixed description text for 'Enable Pro Mode'

resources/js/components/collections/Listing.vue, src/Http/Controllers/CP/Collections/CollectionsController.php, tests/Feature/Collections/ViewCollectionListingTest.php
This pull request adds in a few `v-if` statements that were missing from the Collection Listing component. 
Previously, the action items would appear for anyone, regardless of their permissions. Obviously when the user clicked on it, they wouldn't be able to do the action due to server side permissions, yay! 🎉
This PR adds some properties to each of the collection items before they get passed to the frontend. I implemented it this way as couldn't see anywhere in Vue or Vuex where the user permissions were stored.
I've tested this with different combinations for non-super users (just edit fields, just manage collections and both together). I've also tested this for super users and the same behaviour as normal continues.
This pull request fixes #2136.
=> Add v-ifs to Collections Listing component

src/Fieldtypes/Entries.php
This pull request fixes #1788. It will now throw a `CollectionNotFoundException` when a collection is not found.
=> Throw an exception if collection not found

resources/js/components/assets/Browser/Browser.vue
This pull request fixes a bug where you'd be unable to preform a search while using the asset browser in Grid view.
This pull request fixes #2318.
=> Fix search on Grid mode of Asset browser

resources/views/assets/containers/blueprints/edit.blade.php, resources/views/assets/containers/edit.blade.php
This corrects the breadcrumb links on two CP routes:
`/cp/asset-containers/assets/edit`
`/cp/asset-containers/{custom-container}/blueprint`
=> Correct breadcrumb links when editing Asset Containers & Blueprints

composer.json, src/Fieldtypes/Bard.php, src/Fieldtypes/Bard/Augmentor.php, src/Fieldtypes/Bard/ImageNode.php, src/Fieldtypes/Bard/SetNode.php
This PR updates the `html-to-prosemirror` and `prosemirror-to-html` packages.
- `Scrumpy` has been removed from their namespace.
- Added `values()` to `removeDisabledSets()` because it didn't like that the keys were not zero indexed. It would result in nothing being output. I think it's [this change](https://github.com/ueberdosis/prosemirror-to-html/compare/0.10.0...2.1.0#diff-6bad14fcad6d24f73a6ab908bc699d95R177).
- Closes #2517 because the updated version of prosemirror-to-html includes the strike mark by default.
- Replace the now-default image node with our own custom one which has the asset url support.
=> Update Bard Dependencies

src/Fields/Blueprint.php
Only prepend fields when they are missing in the blueprint; don't force them to the top if they exist in the blueprint. Fixes #2173.
I left in the `! $exists` for readability; you can leave it out if you prefer to.
=> Stop forcing prepended 'ensuredFields' to the top of the blueprint.

src/Fields/BlueprintRepository.php
This PR adds some optimizations related to retrieving blueprints. Simple stuff - just wrapping existing logic in blink closures.
Depending on how your site is set up, how much content you have, number of collections, what you're putting in your templates, etc - that we might end up repeating a lot of blueprint work.
Instead of constantly reading files and parsing YAML, it will only do it once.
In one test site, this reduced load time by about a second.
=> Use blink cache in the blueprint repository

src/Console/Commands/stubs/auth/statamic_auth_tables.php.stub
This pull request adds a `down` method to the auth database migration run by users who want to move their site's users to a database.
Previously, there was no `down` method that would drop columns added by the `up` method.
This PR closes #2543
=> Added down method to Statamic Auth Migrations

src/Auth/SendsPasswordResetEmails.php, src/Auth/UserTags.php, tests/Tags/User/ForgotPasswordFormTest.php
Several improvements to forgot password form tag...
- Fix broken `email_sent` / `success` output.
- Scope success and error output to message bag so that it plays nice with other forms on page.
- Clean up code and make consistent with user login and register form tags.
Closes #1777.
=> Forgot password form tag

src/Entries/Collection.php, src/Entries/Entry.php, tests/Data/Entries/CollectionTest.php
When using `{mount}` in a route, it was getting the `url` of the mounted entry. The problem was twofold:
1. The collection wasn't localizing the mounted entry, so the url would always be for whichever site the entry was in.
2. Since it was calling url, and not uri, we'd see the site root twice. Once in the collection's mounted entry's url, and again after the uri was built.
Closes #1977
=> Fix mount variable causing incorrect urls

src/Stache/Stores/CollectionsStore.php, src/Stache/Stores/Store.php
When you change a collection's route, the entries need to have their urls updated.
And, when you change a orderable collection's tree, the `order` index needs to be updated.
At the moment, this happens on every request to all collections.
This PR makes it so the actions are only performed for collections that have been modified.
=> Prevent handling collection changes on every request

resources/js/components/field-validation/Builder.vue
This fixes #2540 
When the `RULES` object is run through lodash's chain command, the object itself is getting filtered and mapped for some reason. By cloning the object, it stops this odd behavior and allows the rule label to get built properly.
Lion-O would be proud.
=> Fixed validation rule label bug

src/Http/Controllers/CP/Forms/FormExportController.php
This pull request fixes an issue where even if a user could see the form submissions, they would not be able to export the submissions, via either CSV or JSON.
This PR fixes #2576.
=> Fix form submission export permissions

.github/workflows/tests.yml, composer.json, src/Imaging/GuzzleAdapter.php, src/Imaging/ImageGenerator.php, tests/Auth/Eloquent/EloquentUserTest.php
The Guzzle Adapter package doesn't support Guzzle 7 via constraints but does work with no changes. License was MIT, so brought in house so we can support Laravel 8.
All tests pass.
=> Laravel 8 support - bring guzzle adapter in house

README.md
It now just redirects to the main Statamic site.
=> Remove link to Statamic Development Blog

src/Http/Controllers/CP/Collections/LocalizeEntryController.php, tests/Feature/Entries/LocalizeEntryTest.php
Fixes #2471 
Includes tests for what was already happening in there, plus new ones for the structure stuff.
=> Place entries in structure when localizing

src/Tags/Cache.php
This pull request adds the ability for a developer to specify the cache key they want to use when using Statamic's `{{ cache }}` tag.
Instead of Statamic creating a random cache key, a developer can specify it with the `key` param.
```
{{ cache key="the_alphabet" }}
a b c d e f g h i j k l m n o p q r s t u v w x y z
{{ /cache }}
```
This PR implements statamic/ideas#349.
=> `key` parameter for Cache tag

src/Search/Searchables.php, tests/Search/SearchablesTest.php
This PR allows you to add a `transformers` key to your search index configuration:
For example, when you have a location field that saves all raw data in the entry:
```php
'indexes' => [
'locations => [
'driver' => 'algolia',
'searchables' => 'collection:locations',
'fields' => [
'title',
'address',
],
'transformers' => [
'address' => function ($address) {
if (is_null($address)) {
return null;
}
return [
'_geoloc' => $address['rawAnswer']['hits'][0]['_geoloc'],
'country' => $address['rawAnswer']['hits'][0]['country'],
'city' => $address['rawAnswer']['hits'][0]['city'],
'postcode' => $address['rawAnswer']['hits'][0]['postcode'],
];
}
]
],
],
```
This would result in a document like this:
```php
[
'title' => 'A new location',
'_geoloc' => [
'lat' => 51.3345,
'lng' => 4.3712,
],
'country' => …
```
=> Allow transforming of search index values

resources/js/bootstrap/mixins.js
This pull request makes the `components/Listing.vue` component a global mixin. This means that addon developers no longer need to do imports from vendor directories to use this component.
Instead, now it can be imported as a mixin:
**Before:**
```js
import Listing from "../../../vendor/statamic/cms/resources/js/components/Listing";
export default {
components: {
Listing,
},
}
```
**After:**
```js
export default {
mixins: [Listing],
}
```
---
This PR closes #2559.
=> Make Listing component a Global Mixin

src/Facades/Endpoint/Parse.php
Fixes https://github.com/statamic/cms/issues/2603
You might want to check for other places where you use PHP_EOL for parsing.
=> Fix parse frontMatter for all line ending types

resources/lang/da/fieldtypes.php, resources/lang/de-CH/fieldtypes.php, resources/lang/de/fieldtypes.php, resources/lang/en/fieldtypes.php, resources/lang/es/fieldtypes.php, resources/lang/fr/fieldtypes.php, resources/lang/it/fieldtypes.php, resources/lang/nl/fieldtypes.php, resources/lang/pt/fieldtypes.php, src/Fieldtypes/Radio.php, src/Fieldtypes/Select.php
This pull request copies the `cast_booleans` configuration option from the Select fieldtype to the Radio fieldtype. 
This PR closes #2558.
=> Add cast_booleans configuration option to Radio fieldtype

src/Tags/Structure.php
This pull request fixes #2609 by providing context when using recursive children inside the nav/structure tag.
Currently, inside of recursive children, you're not able to see the data for the global page. In the below example, you wouldn't be able to access `{{ current_url }}` in any of the children. 
```html
{{ nav:collection:pages }}
<li>current_url: {{ current_url or 'nada' }}</li>
{{ if children }}
{{ *recursive children* }}
{{ /if }}
{{ /nav:collection:pages }}
```
The above example is something this PR fixes. It does this by providing the context available to the tag and merging it with the entry & structure data for the child.
=> Provide context to the recursive children in the structure tag

resources/views/licensing.blade.php
Use the `docs-callout` partial for Licensing like other sections does.
=> Use docs-callout for Licensing section

src/Search/Searchables.php, src/Taxonomies/Term.php, tests/Search/SearchablesTest.php
Closes #1722 
When you save an entry (or term, or asset, etc) it updates the search indexes.
It looks through all the configured indexes, and checks whether the entry belongs in that index.
It did this by getting all the items that _should_ be in the index, and check to see if that entry was in that array. Stupid in hindsight, but was simple to write originally and wasn't testing with enough content to notice a performance issue.
When you have a butt-tonne of entries (or assets, as per the issue) it has to do a lot of work to get _all_ of them.
The problem is compounded when your assets are on S3 which is even slower.
This check has been reworked to just check against the rules and doesn't need to bother getting all the searchables.
Saving an entry on my 14,000-asset test site went from 7 …
=> Fix searchable item checking

src/Query/Builder.php, tests/Query/BuilderTest.php
This pull request adds a `find` method to the Statamic\Query\Builder class.
The method takes an ID as the first parameter and an optional array of columns as a second parameter (this array is passed to the `get` method to set `selectedQueryColumns `). It returns the first entry matching the ID (there should only be one of course).
Usage:
```php
Entry::query()->find('the-searched-id');
// or a more "verbose" and exhaustive alternative
Collection::find('posts')->queryEntries()->find('the-searched-id');
```
I didn't add PHPDoc comment blocks or comments because there weren't any. Same goes for type hinting. If that's an issue, I can adjust as needed.
=> Add find method to query builder

src/Http/Controllers/API/ApiController.php
This PR fixes #1736. 
Previously, when using a filter in the Content API, like the one in the URL below, `true` would be string which wouldn't work for the check (`true` !== `'true'`), where as now, it will be cast to a boolean and the check will work.
```
http://statamic.test/api/collections/pages/entries?filter[published]=true
```
=> Cast filter values to booleans on Content API

src/Modifiers/CoreModifiers.php, src/View/Cascade.php, tests/Modifiers/AddQueryParamTest.php, tests/Modifiers/RemoveQueryParamTest.php, tests/Modifiers/SetQueryParamTest.php, tests/View/CascadeTest.php
**This pull request adds the following:**
1. The `current_full_url` cascade contextual variable which behaves the same as `current_url` but includes query parameters
2. An `add_query_param` modifier which adds the specified key/value pair to the URL as a valid query param
3. A `set_query_param` modifier which adds the specified key/value pair to the URL (or updates the matching key) as a valid query param
4. A `remove_query_param` modifier which removes the query param matching the specified key (if it exists) from the URL
**Usage**
```html
{{ url add_query_param="category|dogs" }}
{{ url set_query_param="category|dogs" }}
{{ url remove_query_param="category" }}
{{ url add_query_param:category:dogs }}
{{ url set_query_param:category:dogs }}
{{ url remove_query_param:category }}
```
**Todo …
=> Improve query params manipulation

config/static_caching.php
There are cases, where you want to use different caching strategies in different environments. 
You might want a caching strategy in production, but not locally for your development. Making it available in your .env does make it easy to change those strategies, depending on your environment.
=> Make statamic caching strategies available in your .env file

src/Fields/Fields.php, src/Fieldtypes/Bard/Augmentor.php, src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php
The field "parent" is the item that has the field on it. (i.e. an entry)
This lets a fieldtype know the context its being used for.
It was originally added in ea374e8 but only applied to regular inline fields.
This PR passes the parent along to referenced fields, and fields via imported fieldsets.
This PR also makes sure that Bard, Replicator, and Grid fields pass the parent along.
=> Pass along field parent

src/Fieldtypes/Entries.php
Fixes #2507 
The `entries` fieldtype will now localize its selections when augmenting based on the locale of the parent entry.
For example:
- Have an entry in english
- Have an entries fieldtype with a few english entries selected
- Translate it to french
When you're viewing the french entry on the frontend and you loop over the entries, you would probably expect that they would be the french versions.
This PR does exactly that. Any entries that _aren't_ localized into that site will simply be filtered out.
If you *are* expecting the existing behavior, we can add a feature that would bring that back. In our eyes, the previous behavior was a bug.
=> Localize based on entry's locale

src/Forms/Email.php, src/Forms/SendEmails.php, src/Http/Controllers/FormController.php, tests/Forms/EmailTest.php
This PR passes along the site where the form was submitted into the mailable.
The translator will use the appropriate locale.
Any globals will be localized to the appropriate site.
Fixes #2386
=> Localize Form Emails

src/Fieldtypes/Entries.php
**Problem:**
Let's asume you have a collection (eg. Pages) with a field where you refer to another collection entry.
If the entry behind "link" is removed but you refer to that in the antler file somewhere the page throws an exception:
cause:
**Proposal:**
Add the nullcheck to avoid the exception throwing.
=> Add null check to avoid an exception if a linked item got deleted 

src/Stache/Indexes/Terms/Associations.php, src/Stache/Stores/TaxonomyTermsStore.php, tests/Stache/Stores/EntriesStoreTest.php, tests/Stache/Stores/TermsStoreTest.php
This fixes a handful of taxonomy + stache + cache related issues:
- Terms not deleting when you try to delete them #1349
- Terms showing the slug instead of the title #1982 
- An undefined offset 1 error when creating terms #2020 
- Entry keeping term association when you remove it. #1870 
- Terms showing their id instead of the title when you create new ones on the entry edit page.
This is a combination of PRs #2684 and #2685 
Fixes #1982 
Fixes #1349
Fixes #2020
Fixes #1870
=> Taxonomy cache fixes

src/Console/Commands/stubs/auth/statamic_auth_tables.php.stub
Running migrate:rollback failed due to the incorrect variable name.
=> Fixes variable name in down command

composer.json, src/Modifiers/CoreModifiers.php, src/Support/Html.php
Due to popular demand (at least 3 whole people 🤷). This PR brings back the `smartypants` modifier and a `Statamic\Support\Html::smartypants()` method if you want to use it from PHP.
Previously there was the ability to choose the 'behavior' but you had to pass in arbitrary constants which were ints and it was just a bit weird. I didn't include those. If someone needs them, we can think about a better way. Doing `{{ words | smartypants:2 }}` doesn't make sense.
Closes #2683 
Closes #2139 
Closes statamic/docs#203
=> Bring back smartypants

src/Tags/Collection/Entries.php, tests/Tags/Collection/EntriesTest.php
This PR fixes #2293.
In v2, when you had an empty `taxonomy` param on the `collection` tag, all results would be displayed, just without taxonomy filtering.
However, in v3, if the `taxonomy` parameter was empty, no results would be returned.
=> Fix issue where an empty taxonomy parameter would return no results

src/Providers/AddonServiceProvider.php
Otherwise `php artisan view:cache` breaks
=> Only register views when the folder exists

src/Tags/Structure.php, src/View/Antlers/Parser.php, tests/Fixtures/Addon/Tags/RecursiveChildren.php, tests/Tags/StructureTagTest.php, tests/View/Antlers/ParserTest.php
This fixes an issue that #2610 introduced.
While that PR looked like it was working fine, it was actually causing data to be overridden where it wasn't supposed to.
This PR reverts that PR, and fixes the underlying issue instead.
One of the most common examples of this is a nav where you have alternative titles (here, a `nav_title` var).
```
{{ nav }}
{{ nav_title or title }}
{{ /nav }}
```
This will work fine until you're actually _on_ a page that has a nav_title. Then the nav_title of the actual page will trickle down into every item of the nav loop.
A workaround for this is to use the `scope` parameter to say "I want a variable from this iteration without the parent context leaking into it".
```
{{ nav scope="iteration" }}
{{ iteration:nav_title or title }}
{{ /nav }}
```
PR 2610 broke …
=> Fix data being passed into recursive vars

src/Entries/Entry.php, src/Structures/Page.php, src/Structures/Tree.php, tests/Data/Entries/EntryTest.php, tests/Data/Structures/PageTest.php, tests/Tags/StructureTagTest.php
This PR adds eager loading when looking up an page's entry in a structure tree.
At the moment when we need to do page/entry lookups, it does them all separately. Now, it'll do a whereIn the first time and blink-cache them:
Before:
```
select * from `entries` where `id` = 1
select * from `entries` where `id` = 2
select * from `entries` where `id` = 3
select * from `entries` where `id` = 4
select * from `entries` where `id` = 5
```
After:
```
select * from `entries` where `id` in (1, 2, 3, 4, 5)
```
...and this example only has 5 pages in the tree.
=> Eager load structure tree entries

CONTRIBUTING.md
Removed ‘to’ as it’s not supposed to be there in the sentence.
=> Remove word to fix sentence flow

src/Modifiers/CoreModifiers.php, src/Support/Str.php, tests/Support/StrTest.php
=> Let Str::isUrl() check more URLs

composer.json, src/Extend/Addon.php, src/Extend/Manifest.php, tests/Extend/AddonTest.php, tests/Fixtures/Addon/TestAddonServiceProvider.php
Currently, when you run `php please addons:discover`, (which happens when you composer install) it'll generate a cache file in `bootstrap/cache/addons.php` that has information about all the addons.
One of the things that get stored in there are the paths of each addon. It's a full path so it might be something like `/Users/jason/addons/addon-name`.
This isn't an issue if you're using Git and Composer to deploy, because the contents of`bootstrap/cache` will be ignored and regenerated whenever you composer install on the server.
However, some users don't use Composer on their server, and just plop files up there through FTP. Now the server will see paths from the user's local dev environment instead of the server's paths, and things will break.
This PR makes it so that directories aren't …
=> Addons can get their directory without needing it in the manifest

src/StaticCaching/DefaultInvalidator.php, src/StaticCaching/Invalidate.php, tests/StaticCaching/DefaultInvalidatorTest.php
Duncan's PR #2639 was wiping out all the URLs when you edit a nav or global. Rather, you can define the URLs like you can with collections and taxonomies.
```php
'invalidation' => [
'rules' => [
'globals' => [
'settings' => [
'urls' => [
'/*'
]
]
],
'navigation' => [
'links' => [
'urls' => [
'/*'
]
]
]
],
],
```
In there, you're free to just tell it to wipe them all, if that's what you want.
Also clean up tests by using regular mocks, not spies, and do a little tidying.
Closes #2639
Closes #2393
=> Support navigation and globals in the static caching invalidation

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/ManagesPreviewText.js, resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/Set.vue, resources/js/components/inputs/relationship/RelationshipInput.vue, src/Fieldtypes/Bard.php, src/Fieldtypes/Replicator.php
Replicator fields with lots of set blocks (like, really _a lot of them_) can cause slow downs because of how many components need to be created and rendered on the page. This would typically happen for people using Replicators as page builders. When you try to add a new set, it might take a few seconds before anything happens.
At the moment when you collapse a set, it just hides it with CSS (using Vue's `v-show` directive). This PR will properly hide it using `v-if`, which takes it off the page. Vue no longer needs to do any rendering, event handling, etc. Now, you can improve performance drastically by using the collapse by default #2771 or accordion 979daebec8337d9e6caf753e4e13e39ed96edcd6 options.
A side effect of this is that the collapsed previews get wiped out. So this PR also moves …
=> Replicator / Bard Performance

src/Stache/Indexes/Value.php, src/Stache/Repositories/TermRepository.php, src/Taxonomies/AugmentedTerm.php, src/Taxonomies/LocalizedTerm.php, src/Taxonomies/Term.php, tests/Data/Taxonomies/TermTest.php
When building the stache and you have a lot of terms, getting the entry count is a pretty expensive operation and can slow it down. (If you're using `entries_count` in your templates, you'll want to have it [configured](https://statamic.dev/stache#configuring-additional-indexes) to be indexed up front.)
Having a dedicated method gives us the ability to make a more performant query. In this case, filter down the entry-term associations in the Stache rather than perform a query. Also, we can throw it in the blink cache.
On one particular term-heavy test site, the cache build time dropped about 30 seconds.
=> Add dedicated entriesCount method for counting a term's entries

composer.json, config/stache.php, src/Http/Middleware/StacheLock.php, src/Providers/AppServiceProvider.php, src/Stache/NullLockStore.php, src/Stache/ServiceProvider.php, src/Stache/Stache.php
This PR adds support for locks within the Stache.
If a request is made on the site while the stache is being warmed, it will just wait until the warming is finished. This prevents the subsequent response from triggering _another_ cache build, which would increase CPU and memory usage.
If the second request (any subsequent request) waits for 30 seconds (configurable) it'll exit with a 503 status, and a meta refresh tag that'll just re-request the page.
At the moment it only locks when "warming". e.g. when you run `php please stache:warm`.
More locking features will be added later, like Redis support, and cache updates outside of the stache:warm command.
Closes #552
=> Stache Locks

resources/js/components/blueprints/ImportField.vue, resources/js/components/blueprints/RegularField.vue, resources/sass/components/blueprints.scss
This PR fixes #2670 
Added “flex-none” to controls and Tailwind class “break-all” to wrap word when overflow
=> Fix issue when long field names go outside of the section element

resources/sass/vendors/vue-select.scss
By default, the flex wrappers around the select field will inherit their width from their content, allowing them to overflow the container when the value is really long.
Setting a min-width of 0 allows them to shrink to the containing element.
=> Fix long Select fields from overflowing

src/Fieldtypes/Text.php
References #2703.
Previously, if you had a text field, with an `input_type` of number, the value would be saved as a string, with the single quotes around the value in the YAML.
However, with this pull request, that value will now be converted to an integer if the type is a number.
I couldn't find an existing Text Fieldtype test so I didn't write a test for it but I could create one if you want.
=> Convert value to number, on Text fieldtype with input_type of Number

src/Support/Manager.php
When creating a custom driver the name from the config is not passed.
In my case I'm extending with a custom search driver, but the index name `public` is currently not available in the custom creator callback. So the custom driver don't know how to name the index.
This PR passes the config name as a third parameter to the custom creator callback.
Example config:
'indexes' => [
'public' => [
'driver' => '<my-custom-driver>',
'searchables' => 'collection:<my-collection-name>',
'fields' => ['title', 'description'],
],
],
=> Pass name to custom driver

src/Fields/Validator.php
This fixes the issue of not being able to translate attribute names when validating forms.
It enables utilizing Laravels custom validation rules for form validations without changing previous behaviour.
You can now specify custom attribute names and messages by adding configuration for the fields' `handle` in `/resources/lang/{locale}/validation.php`:
```php
<?php
return [
// ...
/*
|--------------------------------------------------------------------------
| Custom Validation Language Lines
|--------------------------------------------------------------------------
|
| Here you may specify custom validation messages for attributes using the
| convention "attribute.rule" to name the lines. This makes it quick to
| specify a specific custom language line for a given attribute rule.
|
*/ …
```
=> Enable translating field attributes when validating fields.

src/Modifiers/CoreModifiers.php, tests/Modifiers/EmbedUrlTest.php
Youtube has a no-cookie feature when embedding videos via the `youtube-nocookie.com`-url. This way users are not tracked and reference to these cookies can be removed from privacy policies & cookie consent popovers.
Same goes for vimeo videos with the `dnt` query parameter set.
=> Make embed_url modifier load embeds without cookies from Vimeo / YouTube

src/Assets/Asset.php, src/Assets/AssetContainer.php, src/Assets/QueryBuilder.php, src/Http/Controllers/CP/Assets/BrowserController.php
Though there is still room for performance optimizations, this should fix timeouts in asset browser when working with thousands of files (both locally and in S3).
Closes #2145
Closes #1188
Also possibly related...?
References #2644
References #2279
=> Asset optimization

src/Entries/Collection.php, src/Fields/Blueprint.php, src/Fields/Fields.php
tl;dr: Added more stuff into the blink cache.
The main issue this is solving is that when we try to get augmented values for entries etc, it needs to look into the blueprint to see the fieldtype. This happens for every field. So this PR will reduce repeated lookups etc.
Building the contents of a blueprint is an expensive operation, especially where fields have been been appended (which is often, for entries). Now it'll only happen once per blueprint, and be reset appropriately.
Getting an entry's blueprint (e.g. `$entry->blueprint()`) would get all of the collection's blueprints and then grab the appropriate one. Now it'll only get them all one time. 
The second part of this is the EntryBlueprintFound event, which lets devs add fields to the blueprint (like SEO Pro) - it needs to know …
=> Blueprint optimizations

composer.json
Hey,
fzaninotto/faker development has been discontinued and the project archived as you can read [here](https://marmelab.com/blog/2020/10/21/sunsetting-faker.html).
However, the Laravel core team has started maintaining their own fork, which will also be used in the Laravel projects from now on, according to tweet from [Taylor Otwell](https://twitter.com/taylorotwell/status/1321091021342650377?s=20)
Kind regards,
g
=> Replace fzaninotto/faker with fakerphp/faker

resources/js/components/structures/PageTree.vue, src/Http/Controllers/CP/Collections/CollectionStructureController.php
This PR fixes #2647. 
On the front any drag actions that result in a root node with children are rejected. On the back end the structure tree is validated before saving.
=> Prevent root page with children

resources/js/components/Listing.vue, resources/js/components/collections/View.vue, resources/js/components/data-list/DataList.vue, resources/js/components/entries/Listing.vue, resources/js/components/forms/SubmissionListing.vue, resources/js/components/terms/Listing.vue, resources/views/collections/show.blade.php, resources/views/forms/show.blade.php, resources/views/taxonomies/show.blade.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Forms/FormsController.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, src/Http/Resources/CP/Concerns/HasRequestedColumns.php, src/Http/Resources/CP/Entries/Entries.php, src/Http/Resources/CP/Submissions/Submissions.php, src/Http/Resources/CP/Taxonomies/Terms.php
Improves performance on listings by own requesting data for visible columns.  This can especially speed up listings when the collection blueprint has several relationship fields that aren't being shown.
=> Lazy load listing columns

src/Assets/Dimensions.php
Perform extra checks when getting image dimensions. Fixes #2793
=> Handle corrupted image gracefully in asset search

resources/js/components/entries/PublishForm.vue, resources/js/components/inputs/relationship/InlinePublishForm.vue
This fixes #2469 ["After Save" options should not be used inside Stacks] specifically for when editing an entry through a relationship field. 
Maybe this is sufficient, or maybe a more generic solution is desired and this code can be inspiration for it.
This would also fix #2448.
=> Don't use "After Save" options when editing an entry in a stack through a relationship field

src/Console/Commands/Install.php
This pull request updates the array of directories created during the `php please install` command so that instead of the paths being hard coded, they will come from the configuration inside the `config/statamic/stache.php` file.
For the users directory, the path instead comes from the `config/statamic/users.php` file.
This PR closes #1400.
=> Use directories from Stache config in Install Command

src/Http/Controllers/CP/Assets/AssetsController.php
This pull request fixes an issue that happens when a directory or filename in an asset path includes a special character.
Somehow when you wrap `utf8_encode`, it fixes an issue where there was a `b` in front of the string. Apparently, it's something to do with literal strings 🤷‍♂️
This PR will fix #2353.
=> Fix issue when special characters are in asset path

resources/views/entries/create.blade.php
This pull request fixes #2885.
Whenever you'd have a collection with multiple blueprints and you picked one from the create list (that's not the first one) and you then used the `Create Another` mode when creating. The next entry would go back to using the default blueprint (the first one in that create list).
I saw that the `create` method of the `EntriesController` pulled a `blueprint` from the request so I just passed it the relevant prop.
Hopefully that makes sense, let me know if you have any questions.
=> Pass current blueprint into 'Create Another' URL

src/Auth/Eloquent/User.php, src/Auth/Eloquent/UserRepository.php, src/Auth/UserRepository.php, src/Stache/Repositories/UserRepository.php
This PR fixes OAuth when the Eloquent driver is enabled.
The file based auth stuff works just as well for Eloquent, so just moved that to the abstract repo. If someone wants to put columns in their users table, they're welcome to make a migration and override the method on their own repo.
As pointed out in #2879, there's an error where Laravel tries to access the timestamps property. Rather than make a property that just doesn't do anything, it'll now pass it along to the actual model.
Fixes #2388 
Closes #2879
=> Eloquent OAuth

src/Console/Commands/AssetsGeneratePresets.php, src/Providers/ConsoleServiceProvider.php
Ports the command to generate assets presets `php please assets:generate-presets` from v2. Closes #2277.
=> Add assets:generate-presets command

resources/js/components/fieldtypes/assets/Asset.js, src/Config.php, src/Console/Commands/AssetsGeneratePresets.php, src/Facades/Image.php, src/Http/Resources/CP/Assets/Asset.php, src/Http/Resources/CP/Assets/FolderAsset.php, src/Imaging/GlideServer.php, src/Imaging/Manager.php, src/Providers/GlideServiceProvider.php, tests/Feature/Assets/BrowserTest.php
PR #2909 pointed out a few leftover issues.
- We were still using "large" preset for CP thumbnails (aka "toenail"), even though it's not used in the CP anymore. Removed that.
- The toenail code was still littered throughout the codebase. Again, never rendered, so it's gone.
- `Config::getImageManipulationPresets()` is a bit weird. Made some better named methods in the `Image` facade and deprecated the existing ones.
- When you uploaded an image, it would only generate user defined presets. Now it'll generate the CP ones too.
- Tidied up the generate command a tad.
=> Throw out toenail clippings

src/Tags/Collection/Entries.php
This pull request where `$values` is null or isn't countable. This PR fixes #2904.
I think this is probably something I introduced in #2672.
=> Fix issue where $values isn't countable

resources/js/components/fieldtypes/SelectFieldtype.vue
The preview text is a comma-separated list of the selected options, just like the CheckboxesFieldtype shows. 
Closes #2878.
=> Add replicatorPreview to SelectFieldtype

src/Fieldtypes/Entries.php
As per @jasonvarga, update the Entries field type so it can handle entries that have an integer `id`, when using the eloquent driver
=> update to work w/ entries with int id (using eloquent driver)

resources/views/nav/updates.blade.php, resources/views/partials/nav-main.blade.php, resources/views/partials/nav-mobile.blade.php, src/CP/Navigation/NavItem.php, tests/Facades/CP/NavTest.php
This pull request allows for developers to pass custom SVG icons to their Control Panel Nav Items. This PR closes #1452.
Here's a quick overview of the things I've changed:
* When creating a `NavItem` and using the `->icon()` method, a developer can either provide the name of an icon in Statamic's `resources/svg` directory or they can provide a string of an SVG. 
* Instead of using the `@svg` blade directive to display icons, I've changed it for a inlining it with Blade. This works for both Statamic icons and custom SVGs as they are all strings when they are returned from the `->setter` method.
=> Allow for passing custom icons to CP Nav Items

resources/sass/components/fieldtypes/replicator.scss
=> Improve visual spacing when adding replicator blocks

src/Fieldtypes/Text.php
This is especially useful when building forms where you want to pass hidden dynamic data
=> Add a hidden input_type to the text fieldtype

.github/workflows/release.yml, .github/workflows/tests.yml
> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
Updated `ubuntu-latest` to `ubuntu-20.04` to test out the upcoming change.
Everything in the tests workflow runs fine. The release workflow isn't complicated, I'm confident it'll work.
> setup-php v1 is deprecated.
> Please upgrade to v2 - https://github.com/shivammathur/setup-php/wiki/Switch-to-v2
Followed the upgrade instructions. It works fine.
> Input 'extension-csv' has been deprecated with message: The extension-csv property is deprecated. Use extensions instead.
This is solved by updating `setup-php`
Much better.
=> Get rid of GitHub action warnings

src/Taxonomies/LocalizedTerm.php
This adds a status of `published` for all terms which fixes #2949 
Currently there is no concept of status for Taxonomy Terms which makes sense. Maybe this should be expanded upon later to check if any terms exist? But for now, since all terms are considered published in other senses, it feels like a sensible default to start with.
=> 🐛 add status to LocalizedTerm

src/Search/Comb/Index.php
Fixes #2971, this time staying inside the `Statamic\Search\Comb` namespace.
=> Fix 500 errors for an empty search string

src/Http/Controllers/ForgotPasswordController.php
When using the Forgot Password Form tag, the `reset_url` param wasn't being respected. This fixes that. E.g.:
```
{{ user:forgot_password_form reset_url="/reset-password" }}`
```
=> Use the correct password reset email link's hidden result_url param

src/Auth/UserRepository.php, src/Events/UserBlueprintFound.php
This PR adds a new `UserBlueprintEvent` to make it inline with the other BlueprintFound events like `EntryBlueprintFound` and to help with v2 compatibility.
Unlike the `EntryBlueprintFound` event though, I've not been able to implement the `$user` parameter as adding this would mean updating the `blueprint` method signature to include a `$user` so it can be passed in from the `User.php` file. If I updated it, it would be considered a breaking change for anyone who has bound their own `UserRepository`.
This PR addresses #2905.
=> Add UserBlueprintEvent

resources/js/components/fieldtypes/bard/BardFieldtype.vue
This fixes #2959 
There where circular events caused by the previews watcher in BardFieldtype.vue
The watcher should update meta data only if there is e diff to the new value to prevent them.
Tested with the simple Neste Bard Setup deschribed in the issue.
---
This is my very first OS PR. So please let me know if I sould do anything diffrent or better
=> only trigger update if value has really changed

src/Auth/Eloquent/User.php
This PR fixes the `isInGroup` function for the Eloquent user driver. It does this by changing the collection returned by `getGroups` to key by handle. This makes it the same as the `getRoles` function in the Eloquent driver and the `getGroups` in the File driver. When the groups collection is keyed by the handle, the `has()` check in the `isInGroup` function will work properly.
=> Fix isInGroup for eloquent user driver

src/Providers/CacheServiceProvider.php
As per https://github.com/laravel/docs/pull/6598
Closes #1721
=> Extend the cache driver within register instead of boot

resources/js/components/blueprints/Builder.vue, resources/lang/en/messages.php, src/Fields/Blueprint.php, src/Fields/BlueprintRepository.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Fields/ManagesBlueprints.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, tests/Fields/BlueprintTest.php
Closes #2419.
I've added the 'hidden' field to where the title is usually displayed when editing blueprints. This means that you can't set blueprints to 'hidden' when the title is not being displayed (globals, asset containers etc).
Edit: N.B. the key in blueprint is `hide` (see: https://github.com/statamic/cms/issues/2419#issuecomment-743302040)
=> Allow hiding of fields from CP.

src/Http/Controllers/CP/Fields/ManagesBlueprints.php
Not sure how this happened since in my initial testing it did work, but right now it's not possible to turn off the 'hidden' toggle on a blueprint. This is because the `false` value will get filtered out... I've provided a patch so it will actually turn it off.
This will fix #3032.
=> Patch hidden blueprint functionality

src/Console/Processes/Composer.php
Always require and update `--with-dependencies` to avoid version conflicts.  Fixes #2548.
_Note: We shouldn't `--with-all-dependencies` though, as we want to respect the user's composer.json/lock.  If they've explicitly required another package, it should be up to them to update it._
=> Composer require & update --with-dependencies

config/cp.php, resources/sass/components/global-header.scss, resources/sass/components/login.scss, resources/sass/core/layout.scss, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/unauthorized.blade.php, resources/views/outside.blade.php, resources/views/partials/favicon.antlers.html, resources/views/partials/global-header.blade.php, resources/views/partials/head.blade.php, resources/views/partials/outside-logo.blade.php
This PR adds the following `cp` config options that only work when Pro is enabled:
- `support_link`: Customizable or disableable support link
- `login_theme`: With `rad` and `business` modes
- `cms_name`: With which to replace the word "Statamic"
- `logo_path`: With which to replace the Statamic logo
=> Wire up white label config options

routes/api.php, src/Http/Controllers/API/CollectionTreeController.php, src/Http/Controllers/API/NavigationController.php, src/Http/Controllers/API/NavigationTreeController.php, src/Http/Resources/API/Resource.php, src/Http/Resources/API/TreeResource.php, src/Structures/AugmentedPage.php, src/Structures/Page.php, src/Structures/TreeBuilder.php
=> API structures

src/Entries/AugmentedEntry.php, src/View/Cascade.php, tests/Data/Entries/AugmentedEntryTest.php
This PR implements a new `mount` variable to entries when they are augmented, as [suggested by Jason](https://github.com/statamic/cms/pull/3040#issuecomment-749063934) on my previous PR.
This feels a lot cleaner than doing it directly on the Cascade class. Let me know if there's any changes you'd like me to make to this.
This PR implements #1352.
=> Add 'mount' variable to Entries - Take #2

resources/js/components/updater/Release.vue, resources/js/components/updater/Updater.vue
This pull request adds a confirmation modal to the Statamic updater before the site begins to update. Closes #884.
=> Add confirmation to modal before updating

src/Events/UserRegistering.php, src/Http/Controllers/UserController.php, src/Tags/Concerns/GetsFormSession.php, tests/Feature/Users/UserRegistrationTest.php
Other part of https://github.com/statamic/cms/issues/2395.
Based it on how form handles it, added a couple of tests.
Needed for Akismet, which needs to be able to stop user registration the same way it does form submissions.
Closes https://github.com/silentzco/statamic-akismet/issues/5
=> Add UserRegistering event

resources/js/components/entries/BaseCreateForm.vue, resources/js/components/entries/PublishForm.vue, resources/views/entries/create.blade.php, resources/views/entries/edit.blade.php, src/Fieldtypes/Entries.php, src/Http/Controllers/CP/Collections/EntriesController.php, tests/Feature/Entries/StoreEntryTest.php, tests/Feature/Entries/UpdateEntryTest.php
This PR fixes #1011 where if the 'manage publish state' permission isn't checked on a role and when a user in the role tries, they would be able to toggle the publish state.
This PR fixes this bug from the front-end by passing in a new `can-manage-publish-state` prop of whether or not the user has permission to manage publish state on that collection. 
However it does seem like it could be a good idea to also enforce this on the backend side as well. What do you think?
=> Read-only Publish toggle on Entries

config/static_caching.php, src/StaticCaching/Cachers/FileCacher.php, src/StaticCaching/StaticCacheManager.php, tests/StaticCaching/FileCacherTest.php
The ignore_query_strings was half implemented when ported from v2. Not enough for it to be usable, though.
If you added it to your config file, it wasn't being sent through to the drivers. Now it it.
Also, the file cacher would write query strings into the filename even if they're supposed to be ignored.
=> Ability to ignore query strings in static caching

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/buttons.js
Adds the ability to use a horizontal rule in bard.
You have to add the button to your bard field in order to be able to use it.
If you have the button enabled, then 3 dashes will be a keyboard shortcut for it.
Closes #3074﻿
=> Add horizontal rule to Bard

src/Entries/Entry.php, tests/Factories/EntryFactory.php, tests/Feature/Entries/EntryRevisionsTest.php, tests/Feature/Revisions/RevisionsTest.php
Fixes #2397 
When creating an entry from a revision, it wasn't applying the date. So when it would build an entry based on a revision, it would always just use the original entry's date.
We'll now write the date as a timestamp into the entry revision attributes which gets used when creating a revision (and working copy). When an entry is created from a revision (or working copy), it'll now use that date.
The check for the `date` inside the `$attrs` happens in the condition in order to prevent an error when you have a revision/working copy created before this change - otherwise you'd get an "undefined index 'date'" error.
Also adds a `date` method to the EntryFactory helper class.
=> Fix date handling in revisions

src/Providers/AddonServiceProvider.php
I did notice that we explicitly do allow to register tags, fieldtypes, modifiers, widgets and others, but **no filters**. 
This PR does add the possibility to register filters like other components: https://statamic.dev/extending/addons#registering-components
```php
protected $filters = [
\Acme\Example\Filters\First::class,
\Acme\Example\Filters\Second::class,
// etc...
];
```
I am happy to update the docs as well, if this is getting merged.
=> Add filters to the addon AddonServiceProvider.php

resources/js/components/fieldtypes/TableFieldtype.vue
This fixes #2470 
Adding top down reactivity in c975aa3 caused #1447 which was solved by 4536ef2 but then caused #2470
This commit implements c975aa3 in a smarter way, which will prevent all the sortable _id keys being regenerated which prevents a dom update, which caused #1447.
Got that? Phew.
This PR also fixes #2790 - The logic for showing the delete row button was using canDeleteColumns instead of canDeleteRows.
=> Table fieldtype fixes

src/Exceptions/NotFoundHttpException.php
#3088 pointed this out to me.
When you visit a URL with a route binding, (like the users in that PR, or /cp/collections/non-existent) you get your front-end 404 view rather than a CP based one.
=> Fix 404s within the CP rendering on front-end

routes/cp.php, src/Http/Controllers/API/UsersController.php, src/Http/Controllers/CP/Users/PasswordController.php, src/Http/Controllers/CP/Users/UsersController.php, src/Providers/RouteServiceProvider.php
This pull request resolves #2316, where issues crop up in existing Laravel apps if people are using route model binding to bind to their `User` model.
This PR just straight out removes the route model binding and replaces it with a lookup in the controllers where it is referenced with `Entry::find($id)`.
While working on this PR, I've also found posts on the Discord by some developers complaining that Statamic's route model binding is a bit generic and can cause issues if used side by side on an existing Laravel app. I'm happy to make any changes to any of the other route model binding stuff if that's something you'd like me to do.
Let me know if you have anything you'd like me to change.
=> Remove route model binding for users

src/Http/Controllers/CP/Collections/EntriesController.php, src/Structures/Tree.php, tests/Data/Structures/TreeTest.php
Closes #3083 
This fixes what 3083 was trying to do.
When you save an entry, if the selected "parent" field is the root, it'll make it so it doesn't try to make it a child. It'll just place it at the top level.
This will also now throw an exception if you try to move a page into the root at the code level.
=> Fix some tree issues

src/Console/Commands/Multisite.php, src/Ignition/Solutions/EnableStatamicPro.php, src/Statamic.php
- Fixes #2802 by clearing the Stache at the start of the command.
- It will now tell you that Pro is required (if you don't already have it enabled) and offer to enable it.
- It will now update the sites config file for you rather than just telling you to do it.
- If either instance of updating the config files fail, it'll tell you how to manually do it.
- Added some minor output improvements now that it's doing a little more.
=> Multisite command improvements

resources/js/components/updater/Updater.vue
This pull request implements #2586. It makes two of the updater messages translatable, like most other places in the CP.
=> Updater messages should be translatable

src/Fieldtypes/Date.php
This pull request resolves #2497, where the time would always be saved, even if the `time_enabled` config setting was set to `false`.
The issue seems to have come from the `preProcess` function of the Date fieldtype where it was formatting the date value to one that can then be understood by Moment on the frontend.
Essentially, it was just a case of adding a ternary to check if time is enabled, if yes the format will be `Y-m-d H:i`, otherwise it will be `Y-m-d`.
=> Time should not be saved if time is disabled on Date field

src/Entries/Entry.php
This pull request fixes #2953.
When the API was enabled and you tried to use the live preview feature when creating a new entry, it would error out about missing parameters. Essentially, the issue was that the `$this->id()` was returning as null, as no entry had been created yet. I've added a check in before it returns the route.
From what I can tell, the reason it didn't happen when the API was disabled was because the API routes weren't registered at that point as there's a check in the `routes/routes.php` file.
=> If entry hasn't been created, return null as API URL

src/Search/Algolia/Index.php, src/Search/Comb/Index.php
This pull request fixes #2727. Currently, when you delete an entry, it will not be removed from the search index, it will just stay there until the end of days.
This PR fixes that, where when an entry is deleted, it will also be deleted from the search index as well.
This PR not only fixes it for entries but also for anything else that is held in the search index.
In the index, documents are stored by their `reference` (eg. `entry::the-entry-id`) but when deleting, it was trying to find a document called `the-entry-id` (by the ID), which obviously wasn't found. This ID basically just passes the reference instead of the ID.
=> Fix documents not being removed from search index

resources/views/partials/global-header.blade.php
When you have a multisite and select another site as the default one in the CP, it now goes to the url of the selected site.
Closes #3107
=> View site button in CP supporting multisites

src/Forms/Email.php
This is a nice band-aid solution to allow translation of the subject of form emails.
Closes #2994
=> Allow translation of email subjects

src/Yaml/Yaml.php, tests/Yaml/YamlTest.php
Symfony recently released a new version of the yaml component which slightly changes how multilines are dumped. It was causing our tests to fail in a very minor way - but still fails.
Rather than testing the actual yaml is dumped correctly, mock it. Symfony's Yaml component is already under test.
This fixes the tests before and after 5.2.2
=> Inject and mock yaml dumper

src/GraphQL/Queries/EntryQuery.php, tests/Feature/GraphQL/EntryTest.php
Add the ability to query an entry by slug or URI.
Closes statamic/ideas#456
=> [3.1] GraphQL query an entry by slug or URI

src/Facades/Taxonomy.php
It would appear you couldn't override the taxonomy repository because the Stache one would always be used.﻿
=> Fix Taxonomy facade accessor

src/Assets/QueryBuilder.php
In #2828 we added caching to asset listings.
Inside the asset query builder it converts paths to asset objects. As part of that, if the asset file doesn't exist, it'll return null.
We discovered an issue where if you delete an asset by hand during the cache window (through the filesystem or by git), you'd get an error because the asset path (which was still in the cache) was converted to null (because the actual file doesn't exist).
We fixed this by filtering out null values when you don't care how many are supposed to be returned.
But when you do care (like when using `paginate`, or `take`), we'll check if there are any nulls, if there are we bust the cache and requery.
=> Improve cached asset handling

src/GraphQL/Types/GridItemType.php, src/GraphQL/Types/ReplicatorSetType.php, tests/Feature/GraphQL/Fieldtypes/BardFieldtypeTest.php, tests/Feature/GraphQL/Fieldtypes/GridFieldtypeTest.php, tests/Feature/GraphQL/Fieldtypes/ReplicatorFieldtypeTest.php
This makes sure `Value` objects are converted appropriately inside Bard, Replicator, and Grid fields.
Fixes #3200
=> Improve nested subfield handling in GraphQL

CHANGELOG.md, src/Fieldtypes/Date.php, src/GraphQL/Fields/DateField.php, src/GraphQL/TypeRegistrar.php, src/GraphQL/Types/DateRangeType.php, tests/Feature/GraphQL/Fieldtypes/DateFieldtypeTest.php, tests/Fieldtypes/DateTest.php
When [testing out another date range issue](https://github.com/statamic/cms/issues/2349#issuecomment-776299830), I was using the 3.1 branch, and noticed I had broken date ranges.
This is because I added augmentation to the date fieldtype, but didn't include support for ranges.
This PR adds support for augmenting date ranges, explains the breaking change in the changelog, and adds support for querying date ranges in GraphQL.
```graphql
range {
start(format: "Y-m-d")
end(format: "Y-m-d")
}
```
=> Date augmenting and ranges

src/StaticCaching/Cacher.php, src/StaticCaching/Cachers/AbstractCacher.php, src/StaticCaching/Cachers/ApplicationCacher.php, src/StaticCaching/Cachers/FileCacher.php, src/StaticCaching/Cachers/NullCacher.php, src/StaticCaching/Middleware/Cache.php, tests/StaticCaching/ApplicationCacherTest.php
Fixes #3209 
When a request is made, we get the cached response up front - if there is one, we'll use it.
It was done this way so there wouldn't be separate cache hits for checking and getting. The point of this feature is speed so every little bit helped. 😄 
However, this causes a log when the page is generated in #3209.
This PR splits up checking for the existing cache vs. getting it. Checking the existing cache won't trigger a log.
For half measure, the overhead is now alleviated even with a separate "has" method by storing the cached value in a property.
For full measure, you'll have the same number of file operations as before.
Uncached pages get one for checking the cache, and another for writing it.
Cached pages with the server rewrite set up won't even hit PHP.
Cached pages with …
=> Split checking of static cache vs getting it

resources/sass/elements/forms.scss
=> Keep text field width within limits in Firefox

src/Tags/Parameters.php, src/View/Antlers/Parser.php, tests/Tags/ParametersTest.php
But the test fails because (I believe) the mocked data isn't correct.
Fixes #3248
=> Parameters can now access:nested:variables

src/Auth/Eloquent/UserRepository.php
This PR closes #1511, where for each entry in your site, a database query would be made to find the `updated_by` user. 
This PR fixes that by caching the database query so it's only needed to be done once per request.
=> Wrap Eloquent User::find logic inside Blink

resources/sass/vendors/vue-select.scss
* Only put the grey background on the container element (fixes #3073)
* Make sure the button that opens the dropdown also has a 'not-allowed' cursor
This applies to all ```read_only``` fields with a select input.
=> Fix disabled select input styling issues

src/Fieldtypes/Arr.php
This fixes #3156 because the Array field type is also used in configuring the options of a Select field type.
=> Preserve numeric keys in the Array fieldtype

src/Forms/AugmentedForm.php, src/Forms/Fieldtype.php, src/Forms/Form.php
Fixes #3182 by making the form augmentable. Returns handle, title and fields.
=> Show valid data for a Form field in the content API (take 2)

src/Console/Composer/Lock.php, src/UpdateScripts/UpdateScript.php, tests/Composer/ComposerLockTest.php, tests/UpdateScripts/UpdateScriptTest.php
This fixes an issue where `$this->isUpdatingTo('3.1')` wouldn't work but `3.1.0` would.
This also scraps our version normalizing code in favor of Composer's. They already have a full-fledged thing.
But since their method normalizes the versions to 4 digits (e.g. `3.0.0.0`), I've made a separate `getNormalizedInstalledVersion` that does the normalizing. `getInstalledVersion` just uses whatever is actually installed with Composer.
This lets us use the normalized version for `version_compare`, but the regular one for displaying.
=> Composer package versions

resources/js/components/fieldtypes/RangeFieldtype.vue
Flex items have `min-width: auto` by default. To prevent the `<input type="range">` from overflowing the container, I set `min-width: 0` by using the existing Tailwind class `min-w-0`.
Here is a before and after comparison in Chrome, Firefox and Safari. The range field has a width of 25%.
**Before:**
----
**After:**
=> Control Panel: Fix range field input overflowing flex container

src/Auth/Eloquent/User.php, src/Auth/File/User.php, tests/Auth/UserContractTests.php
Added `email` property getter for file users so that I can pass a collection of Statamic users to the `Mail::to` method. That method expects a `name` & `email` field.
=> Get email via property

src/View/View.php
This PR closes #1848. It introduces a new `current_template` variable which is added in the `View`, when data is merged inside the `gatherData` method.
I've put it here after [a comment by Jason](https://github.com/statamic/cms/pull/3279) last week on my previous PR, #3279.
=> Add current_template to View

src/GraphQL/Queries/EntriesQuery.php, src/GraphQL/Types/EntryInterface.php, tests/Feature/GraphQL/CreatesQueryableTestEntries.php, tests/Feature/GraphQL/EntriesTest.php, tests/Feature/GraphQL/EntryTest.php
This PR ensures that draft and scheduled entries aren't shown in entries queries by default.
If you filter on `status` or `published`, the default behavior goes away and does whatever you've asked for instead.
This PR also:
- Performs a default sort on `id`. This is mainly to make it more predictable in tests.
- Adds a `status` field to entries
Ref statamic/ideas#459
=> [3.1] Filter published entries in GraphQL

src/Tags/Redirect.php
Some syntactic sugar to turn this:
```
{{ redirect to="{route:login}" }}
```
Into this:
```
{{ redirect route="login" }}
```
Which is much nicer.
=> Add `route` param to `redirect tag

src/Providers/AppServiceProvider.php
I think this might be removed. There is no constructor defined for FieldsetRepositories or did I miss something?
https://github.com/statamic/cms/blob/3.0/src/Fields/FieldsetRepository.php
co-authored: @juliawarnke
=> Don't inject files to the Fieldset Repository

src/Assets/AssetContainer.php, src/Assets/AssetFolder.php, tests/Assets/AssetContainerTest.php, tests/Assets/AssetFolderTest.php
Part one of many to fix #3216
Back in the 3.0 beta, we decided to remove the folder.yaml "title" field. (#281) While we removed the UI and some other spots, the code to read from the `folder.yaml` files stayed around.
There are a number of bottlenecks when using an S3 asset container because there are so many API calls. One of the bottlenecks was due to looking at each folder's `folder.yaml` every time.
We're doing pretty much absolutely nothing with it, so there was overhead for no reason.
I've removed it in this PR.
When viewing a directory with 25 subdirectories and 11 assets (completely arbitrary numbers - it's just what I had in there at the time) **the number of API requests went from 167 down to 14. Or about 10 seconds down to 1.2 seconds.**
I'm targeting master as it's a little …
=> Remove remaining asset folder yaml reads

src/Filesystem/AbstractAdapter.php, tests/Filesystem/FlysystemAdapterTest.php
This PR removes the additional "exists" check when "getting" a file's contents.
Part 2 of who knows to fix #3216 
It's an improvement on #3330 which would break the fallbacks if you've disabled asserts on the filesystem disk. That's Flysystem's own performance feature that will prevent throwing the exception if the file exists. If the file doesn't exist, it'll return `false`. So, we'll just check for that.
For benchmarking I looked at the ajax request performed in the CP when you edit an asset.
I have the same setup as described in #3353 - 25 subdirectories and 11 assets.
Before this, there were 52 API calls taking 3.5 seconds.
After, there were 27 calls taking 2 seconds. Good improvement.
When combining with the changes in #3353 it dropped to 2 calls in 450ms. Better.
Closes #3330
=> Rely on exception rather than separate exists call to reduce api calls

config/assets.php, src/Assets/Asset.php, src/Assets/AssetContainer.php, src/Assets/AssetFolder.php, src/Assets/QueryBuilder.php, tests/Assets/AssetContainerTest.php, tests/Assets/AssetFolderTest.php, tests/TestCase.php
Part 4, I think, of multiple, to fix #3216 
This PR aims to reduce S3 API calls when checking for file existence.
Story time.
We check an asset's underlying file exists in order to prevent a situation where you may have requested one that has been deleted or moved.
For example, if you have an `assets` field in an entry, and you pick a few assets, you'll get yaml like this:
```
images:
- one.jpg
- two.jpg
- three
```
If you delete or move two.jpg using the filesystem or the asset browser, the entry doesn't get updated, and will reference an outdated path. When Statamic converts those paths to assets, it will fail on two.jpg. We solved this by checking that each path existed, and filtered it out if it didn't. This came at the cost of API requests on S3.
This PR improves the …
=> Optimize the asset exists check

src/Assets/Asset.php, src/Imaging/ImageGenerator.php, tests/Assets/AssetRepositoryTest.php, tests/Assets/AssetTest.php
This PR is another in the #3216 saga.
This adds a `mimeType` method to the Asset class which will read it from the meta instead of needing to read it directly from the file every time.
Because #3280 was implemented, this will lazily insert the mime type into the meta file for existing assets.
Also, for security, we check the mime type before sending an image to Glide. This would be an extra API call to S3 every time. Now that it uses the mimeType method, that API will only be needed once when the meta file is written.
=> Add mime type to asset meta

config/assets.php, config/stache.php, src/Assets/Asset.php, src/Assets/AssetContainer.php, src/Assets/AssetContainerContents.php, src/Assets/AssetFolder.php, src/Assets/AssetRepository.php, src/Assets/QueryBuilder.php, src/Stache/Indexes/Value.php, src/Stache/ServiceProvider.php, src/Stache/Stores/AssetsStore.php, src/Stache/Stores/BasicStore.php, src/Stache/Stores/ContainerAssetsStore.php, src/Stache/Stores/Store.php, tests/Assets/AssetContainerTest.php, tests/Assets/AssetFolderTest.php, tests/Assets/AssetRepositoryTest.php, tests/Assets/AssetTest.php, tests/Stache/Stores/AssetContainersStoreTest.php, tests/TestCase.php
Another one to fix #3216 
In #3359 we made the `exists` checks better by instead of actually checking the file for existence, it would grab the directory listing and see if the path was in there. We cached those listings, so every existence check wouldn't result in another API call on S3.
That was good, but it fell apart when uploading assets. The caches are invalidated when you save an asset, so it would cause those listings to be blown away and rebuilt over way too many times and would be slow.
What needed to happen is that when updating an asset, it should update that item in the cache rather than blow the whole thing away.
That's pretty much what the Stache does, so this PR piggybacks off that.
In this PR:
- Adds an assets stache store
- Values get indexed in the stache so better …
=> Assets + Stache

src/Facades/Endpoint/URL.php, tests/Facades/UrlTest.php
Same as #3397 but retargeted to the 3.0 branch.
- Handle situation when the site url is relative.
- Handle situation where the passed url is relative. If it's relative, it can't be external.
Fixes #2825
=> Improve URL::isExternal()

src/Modifiers/CoreModifiers.php, tests/Modifiers/MarkdownTest.php
Hi there 👋 
Just a quick little bug I've noticed.
When creating a custom parser as per the documentation:
```php
Markdown::extend('special', function ($parser) {
return $parser
->withStatamicDefaults()
->addExtensions(...);
});
```
And then using this custom parser via the `markdown` modifier:
```html
{{ text | markdown:special }}
```
It always uses the `default` markdown parser no matter what option we provide.
A quick check at the source code and I found that this check:
```php
in_array($parser, [true, 'true', ''])
```
always returns `true` since it does not use strict comparison and `"any_non_empty_string" == true`.
This tiny PR fixes this by making the `in_array` strict.
=> Fix markdown modifier with custom parser

config/git.php, src/Git/Git.php
This allows the connection used by the git integration to be different than the default.
Work around for https://github.com/statamic/cms/issues/3291 so default queue connection is `sync` but git uses `redis`
=> Use custom queue connection

config/git.php, src/Console/Processes/Git.php
Closes #3392
This is an idea to fix #3392 by making the path to the git binary configurable for a case where the `git` command is not directly available in the environment. Sorry for my bad english in the code comment 🙈
=> Add option to set custom path to git binary

resources/views/partials/global-header.blade.php, resources/views/partials/outside-logo.blade.php, src/Http/View/Composers/CustomLogoComposer.php, src/Providers/CpServiceProvider.php
Fixes #3394 
Move the now more complicated logic for determining the logo url into a composer, and share it between the two views that need it.
=> [3.1] Fix custom logo when using arrays with null

src/Assets/AssetContainer.php, src/Assets/AssetContainerContents.php
When you do `$assetContainer->files()` it would get the raw file listing which includes stuff in `.meta`, `.gitignore`, `.DS_Store`, etc and it would filter those out. It would do it every time you called `files()`.
Users were reporting it would be slow when they have lots of assets. That makes sense, because if you have 5,000 assets, you'll have 5,000 hidden meta files. If you have all those assets spread out through many directories, then it'll also have all those directories. That'll give you over 10,000 items to filter though. Makes sense why it's slow.
This PR will make it so it only performs the filtering once per request by caching the listing to a property.
=> [3.1] File filtering caching

src/Forms/Tags.php
Add `action` and method params to `form:create` tag. This is useful for people who want to generate forms off blueprints, but submit to an external form handler, say in the case of an SSG site on netlify, vercel, etc.
=> `form:create` action and method params

resources/js/components/inputs/relationship/RelationshipInput.vue, resources/sass/components/fieldtypes/relationship.scss, resources/sass/components/toggle.scss, resources/sass/cp.scss
Fixes #2518 (and #2770 which is actually a separate issue)
When you look at the three dots at the right of the row, you see they already line up nicely with a text field (and other fields with the default height). The `.row-controls` class simply has a `padding-top` to achieve this.
This PR applies a similar trick to the toggle fieldtype and to an empty relationship input in stack selector mode.
=> Vertically align fieldtypes in a grid

src/Modifiers/CoreModifiers.php, src/Support/Str.php, tests/Modifiers/WidontTest.php
Fixes #3241
Before
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```
After
```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus orci a turpis vestibulum&nbsp;ornare.</p><p>Pellentesque interdum at odio ut tristique. Quisque in dui non turpis eleifend&nbsp;dignissim.</p><p>Etiam ultricies sem massa, imperdiet lobortis velit luctus eu. Morbi bibendum tortor vel ultricies&nbsp;tempor.</p>
```
However, it doesnt take into consideration the params. Will push an update to add support for …
=> #3241 - Adds &nbsp's for each paragraph rather than the last one

resources/lang/en/messages.php, src/Forms/Email.php, src/Forms/Form.php, src/Http/Controllers/CP/Forms/FormsController.php, tests/Feature/Forms/UpdateFormTest.php
Currently, if you set up a form submission email to use a markdown template, there's no way to indicate that you're using markdown. Through [the mailable's `build` method](https://github.com/statamic/cms/blob/fc4d56dfd426e0d4be42a243743b23450862cc08/src/Forms/Email.php#L30) (and then the `addViews` method), `view` is called instead of `markdown`, which throws an error:
`InvalidArgumentException
No hint path defined for [mail]. (View: C:\xampp\htdocs\statamic-site\resources\views\emails\form-submission.blade.php)`
This PR adds a toggle field in the CP, allowing a user to indicate the HTML template should be rendered using markdown. If the toggle is on, `addViews` will call the `markdown` method. Otherwise, it falls back to the standard `view` method.
This is (very loosely) related to [a …
=> Add markdown option to render form emails

resources/js/components/fieldtypes/DateFieldtype.vue
[vCalendar is using `-` instead of `_` in their locale](https://github.com/nathanreyes/v-calendar/blob/07e676e0ee5e08f5c10addabd85decb7aaa3b313/src/utils/defaults/locales.js)
People using `de_CH` and `zh_TW` will be affected. They won't be able to see the date picker.
=> Replace `_` to `-` in locale for vCalendar

src/Taxonomies/Taxonomy.php, tests/Data/Taxonomies/TaxonomyTest.php, tests/Stache/Repositories/EntryRepositoryTest.php, tests/Stache/Repositories/TaxonomyRepositoryTest.php, tests/Stache/__fixtures__/content/collections/blog.yaml
This PR adds support for a taxonomy instance to have a url and supplemental data.
Both are needed in order for the nav:breadcrumbs tag to work on a taxonomy's url as outlined in #1776.
It also makes the uri/url adjust itself based on whether the instance is connected to a collection.
e.g. `/tags` vs. `/blog/tags`
Fixes #1776
=> Adjust taxonomy uri, url, and supplemental data.

composer.json
This one fixes the problem with the version of `symfony/var-exporter` dependency which occurs when you try to install in a project that has that package on version > 5.
See this composer error for more information:
```
Problem 1
- statamic/cms[v3.1.0-alpha.1, ..., 3.1.x-dev] require symfony/var-exporter
^4.3 -> found symfony/var-exporter[v4.3.0-BETA1, ..., 4.4.x-dev] but the package
is fixed to v5.2.3 (lock file version) by a partial update and that version doe
s not match. Make sure you list it as an argument for the update command.
```
Fixes #2263.
=> Fix symfony/var-exporter allowed versions

resources/js/bootstrap/globals.js, resources/js/components/Listing.vue, resources/js/components/assets/Editor/Editor.vue, resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue, resources/js/components/inputs/relationship/Selector.vue, resources/js/components/publish/FieldMeta.vue, resources/js/components/structures/PageSelector.vue, src/Http/Controllers/CP/Assets/AssetsController.php
Fixes #1931 
Fixes #2175 
Fixes #2009 
Apparently, [a string in JavaScript is representing in UTF-16 and converting a non-ASCII character using `btoa` will resulting error.](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#unicode_strings)
There are many places in statamic using `btoa` to encode strings and passing it to the backend.
For example, the field relationship contains following code:
https://github.com/statamic/cms/blob/de8b1847243ca3ccb46f7b98d54ce82aa78ff309/resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue#L87-L89
If there are any non-ASCII character in `this.config`, for example, someone might decide to use a fancy Emoji inside their field name, the field will just stop working.
AFAIK, these encoded string will be (and …
=> Add `utf8btoa` to encode utf8 strings

src/View/Antlers/Parser.php, tests/View/Antlers/ParserTest.php
Fixes #3374.
See [this comment](https://github.com/statamic/cms/issues/3374#issuecomment-811447899) for the rationale behind it.
=> Recognise tag pairs correctly for a collection alias

src/Http/Controllers/GlideController.php, src/Imaging/ImageGenerator.php
Fixes #3070.
I used a `try/catch` here instead of a `File::exists()` call for performance reasons.
=> GlideController now returns 404 for non-existing images

resources/js/app.js, resources/js/components/inputs/Text.vue
Fixes #3396.
I've sent quite some characters into the void myself too because of this one 😁
* The issue is not limited to creating a new entry though, it concerns all text inputs with autofocus. So it needed solving on the DOM-level.
* It seems a fix was attempted for this in Text.vue, but it doesn't do anything (this.autofocus doesn't exist) so I removed it.
* Yes, the blur() is necessary.
* Yes, the setTimeout() is necessary.
* No, $nextTick() doesn't work.
* Yes, it looks a bit ugly 😜
=> Fix autofocus issues in Safari and Firefox

src/Imaging/ImageGenerator.php
This fixes an issue introduced in 3.1.3 where if you use Glide with a file in your `public` directory, it would always fail.
```
{{ glide src="something/in/public.jpg" }}
```
The `$path` passed to the `File::exists()` check didn't have the `public_path()` wrapped around it.
=> Use public_path in exists check

src/Stache/Stores/Store.php
Closes #3476 
In the asset store, we just clear it every request, which is different from all the others.
Since the `path` index was still tracked on the property, this line of code returned early, before the array could be cached.
https://github.com/statamic/cms/blob/7ecfffaad53111390f810f2693297696c371d811/src/Stache/Stores/Store.php#L107-L111
=> Clear the used indexes property when clearing

src/Assets/Dimensions.php, tests/Assets/DimensionsTest.php
This PR fixes #3479 where SVG dimensions are always taken in pixels where sometimes they shouldn't.
=> Fix SVG dimensions

src/Console/Commands/AssetsGeneratePresets.php, src/Jobs/GeneratePresetImageManipulation.php
This PR adds a `queue` option to the command.
```
php please assets:generate-presets --queue
```
You must have a queue connection set up.
If you don't (i.e. it's set to `sync`) then it'll tell you, and just generate them without a queue.
Closes statamic/ideas#480
=> Make the `assets:generate-presets` command queue friendly

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/LinkToolbar.vue, resources/lang/en/fieldtypes.php, resources/sass/components/fieldtypes/bard.scss, src/Fieldtypes/Bard.php, src/Fieldtypes/Bard/Augmentor.php, src/Fieldtypes/Bard/LinkMark.php, tests/Fieldtypes/BardTest.php
This PR adds the link picker to Bard.
Rather than the `{{ link:id-of-thing }}` syntax that v2 used, I think we're better off with a `statamic://id-of-thing` syntax.
The prosemirror-to-html renderer would handle this, so it could be usable from anywhere: Antlers, API, GraphQL, etc.
The v2 way required Antlers for it to convert to a url.
Todo:
Closes #801
=> Bard links

src/Http/Controllers/FrontendController.php, tests/FrontendTest.php
This PR fixes #3469, where you visiting a page with a URL like this would simply 404, `/about/?ref=smth`.
=> Fix 404 error when URLs have both ending slash and query parameters

src/Licensing/Outpost.php
If one uses CarbonImmutable app wide, the cacheResponse method gets a CarbonImmutable instance, which leads to PHP throwing an error. By using CarbonInterface this issue is resolved.
=> Use CarbonInterface in case CarbonImmutable is used app-wide

src/Console/Commands/AssetsGeneratePresets.php
Fixes #3501 
The `dispatchSync` method was introduced in Laravel 8.
We need to use `dispatchNow` on earlier versions.
=> Only use dispatchSync if its supported

src/Search/Algolia/Index.php, src/Search/Comb/Index.php, src/Search/QueryBuilder.php, src/Search/Tags.php
This would fix #2728. And it fixes #3480.
I'm not that happy about injecting the search_score into the data, but there your are. It is the best I could think of without changing the return type. And the fact that this is a QueryBuilder for searching specifically might justify it.
=> Include search score in search results ‘with data’

src/Stache/Repositories/TaxonomyRepository.php, src/Stache/Repositories/TermRepository.php, tests/Data/Taxonomies/ViewsTest.php
This fixes #3159
It adds tests for all of our automatic view-based taxonomy/term routes, with and without localized slugs.
This PR also makes the collection based routes work without needing to mount them, on multisite.
For some reason, we only made that work when using a single site.
=> Fix taxonomy routes using localization

src/Assets/Asset.php, src/Yaml/Yaml.php, tests/Yaml/YamlTest.php
You can tell the YAML parser which file is being parsed by doing `YAML::file($path)->parse()`.
You can also choose to _not_ pass the path, if you're just parsing a string of YAML: `YAML::parse($string)`.
The filename was being stored as a property on the yaml parser, and would be remembered if you do those two things in order.
```
YAML::file($path)->parse();
YAML::parse($str);
```
If the second one threw an exception, it would use the file you provided in the first call. This would send the user on a wild goose chase, looking in the wrong YAML file.
This PR fixes that.
---
Also, if you provide a non-existent path (or one that's not on the local filesystem)  for the purpose of a nicer exception (i.e. the asset meta file change in this PR), then the exception would be empty. Ignition would …
=> Improve YAML exception handling

src/Routing/Routable.php, src/Structures/Page.php, src/Tags/Structure.php, tests/Data/Entries/EntryTest.php, tests/Data/Structures/PageTest.php
In this PR:
- Add `urlWithoutRedirect` and `absoluteUrlWithoutRedirect` methods to the `Routable` trait. (Which means `Entry`, etc) I didn't want to add arguments to `url` and `absoluteUrl`, which #3234 was doing.
- Fixes #2359 by using the new redirect-less urls in the ancestor comparison in the nav/structure tag.
- Removed redundant `url` and `absoluteUrl` logic inside `Page`. Let it delegate to the entry.
- Adds test coverage for nav items with hardcoded urls, or url-less ones.
- Fixes `absoluteUrl` / `{{ permalink }}` for nav items with hardcoded urls. Previously they would simply output whatever was input. It wouldn't convert it to absolute.
- Removes code introduced in 17b7978 which is no longer relevant since #1445
=> Nav and url handling improvements

resources/js/components/assets/Browser/Breadcrumbs.vue, resources/js/components/assets/Browser/Browser.vue, resources/js/components/assets/Browser/Thumbnail.vue
Fixes #3521.
Also groups the hover on the folders in the regular view.
=> Add border to selected non-image thumbnails in the asset browser

src/Tags/Link.php, src/Tags/Path.php, tests/Tags/LinkTest.php, tests/Tags/PathTest.php
This PR adds data fetching to the link and path tags. We had this in v2.
Fixes #3529 
```
{{ link to="this-is-an-id" }}
{{ path to="this-is-an-id" }}
```
It'll output that entry for the current site. You can ask for it in a specific one:
```
{{ link to="this-is-an-id" in="site_two" }}
{{ path to="this-is-an-id" in="site_two" }}
```
There's also the shorthand version when using the `link` tag:
```
{{ link:this-is-an-id }}
{{ link:this-is-an-id in="site_two" }}
```
=> Let the link and path tags output data urls

src/Data/ExistsAsFile.php, src/Entries/Entry.php, tests/Data/Entries/EntryTest.php, tests/Data/ExistsAsFileTest.php
Fixes #3406 
Until now, Statamic would strip out any nulls, empty strings, and empty arrays from the YAML before writing files. This was mainly to keep the files tidy.
Statamic's localization worked in such a way that if a localized entry didn't have a key in the YAML, it would fall back to whatever was in the origin.
Combine these two things, and you are left with the issue explained in #3406. Intentionally emptying out a field that would result in null would mean that it wouldn't be in the file, so always fell back to the originating entry's value.
This PR fixes that by preventing the nulls from being stripped out of localized entries.
Rather than preventing a huge change by preventing this in _all_ files (objects that use the `ExistsAsFile` trait) - it's selectively done to entries. …
=> Allow localized entries to have empty values

src/Http/Responses/DataResponse.php
Fixes #3287.
I tried several solutions on the Javascript level, but to no avail. This forces the reload by adding a changing parameter to the `src` attribute of the `script` tag.
=> Force reload of javascript modules in Live Preview

src/Http/Responses/DataResponse.php, src/StaticCaching/Middleware/Cache.php, tests/FrontendTest.php
=> Show private pages in Live Preview (and don’t cache them)

src/Taxonomies/Taxonomy.php, tests/Data/Taxonomies/TaxonomyTest.php
If you have a site that uses a subdirectory (like `/subdirectory/` or `/blog/` or `/statamic/`) then it would incorrectly prefix that to the taxonomy's `uri`, which should be relative to the site root.
When you visit `/subdirectory/tags`, it would look for a taxonomy with a uri of `/tags`, which doesn't match what Statamic thinks the taxonomy's uri is. This results in a 404. A similar thing happens for the term url.
The taxonomy `url` would also have the double prefix. e.g. `/subdirectory/subdirectory/tags`.
=> Fix taxonomy not loading when using site subdirectory

src/Auth/Eloquent/Roles.php, src/Auth/Eloquent/UserGroups.php
We've just had a staging site become really slow.
We did some discovery and it turns out it is mostly down to Statamic making N+1 queries on the `all` method of the  Role & Group classes. 
Here's the kind of things we were seeing:
This PR fixes the issue by wrapping the `all` code in a `Blink` closure, meaning it will be cached for the request.
I'm sure there was an issue for this at some point, not sure where it's gone. I fixed a similar issue for the `users` table I think a couple months back.
Let me know if you need any changes. I'd be happy to make them. This is a fairly big issue for us at the moment 😅
=> Fix N+1 queries from `all` method on User Roles & User Groups classes

src/Http/Middleware/DisableFloc.php, src/Providers/AppServiceProvider.php, tests/FrontendTest.php
This PR adds a middleware that disables Google's FLoC by default. No action will be necessary from the user. Upgrade Statamic and it'll be disabled.
If you want to enable it, you can flick the switch in `config/statamic/system.php`.
```php
'disable_floc' => false,
```
Closes #3520 
(I'm still just working on the assumption that this header is enough to stop whatever it does. I don't know what I'm supposed to do to confirm it. The header is definitely there though.)
=> Disable FLoC by default

routes/web.php, src/Statamic.php
It's possible to use Nova with Statamic already - you can see how here: https://statamic.dev/knowledge-base/laravel-nova
This PR makes the integration just a little nicer, reducing those steps from 5 to 3.
https://github.com/statamic/ideas/issues/238
=> Improve Nova integration

resources/js/components/assets/Uploader.vue
Fixes #3558.
This uses a new string `'File is too large'`, which should be added to the translations.
=> Always show an error when an asset upload fails

resources/js/components/data-list/Pagination.vue, resources/js/components/entries/Widget.vue
=> Don’t scroll to top when using pagination in collection widget

resources/js/components/assets/Browser/Browser.vue, resources/js/components/assets/Editor/Editor.vue, resources/sass/components/assets.scss
Fixes #930.
* No editing buttons below the image (full-height image preview)
* Read Only data fields (if any)
* No save / delete buttons
=> Read-only asset editor

resources/sass/components/fieldtypes/bard.scss
This fixes #3438. See the comments in the issue.
This is a continuation of #3557, I closed that one by accident.
@jasonvarga Good catch, the fix broke #3115 again. This time I fixed #3115 again, and not by using `hyphens: auto;` (which causes #3438). This css puts words that don't fit anymore on the next line. And very long words, longer than a single line, just get cut off at the end of the line.
=> Turn off automatic hyphenation in Bard

resources/js/components/fieldtypes/bard/Image.vue
Fixes #1069.
The obligatory `ref="content"` [thingy](https://github.com/ueberdosis/tiptap/blob/2466d3398f3cd1c64aa9a6211860a69bc253cb91/examples/Components/Routes/DragHandle/DragItem.js#L20) was causing the problem. I moved it to another place, problem gone.
By the way I don't see any custom drag handle, before or after this change. The `<div ref="content" .. />` can even be removed, together with the `data-drag-handle` attribute and dragging still works.
=> Bard: make first line after image editable

src/Tags/Link.php, src/Tags/Path.php, tests/Tags/LinkTest.php, tests/Tags/PathTest.php
In #3530 I added support for entries to be retrieved by ID using the `link to="id"` syntax.
It doesn't just get entries though. It gets anything by ID. Assets, collections, whatever.
There was a conflict pointed out in #3548
This PR makes the ID functionality only happen if you use an `id` param.
```
{{ link to="path" }} outputs "/path"
{{ link id="123" }} outputs url of item with id 123
```
The shorthand still expects ids, though.
```
{{ link:123 }}
```
Fixes #3548
=> Link tag ID lookup only when using id param

resources/js/components/fieldtypes/replicator/Field.vue
Fixes #2274. 
Fixes it for Replicators too, because Bard and Replicators use the same set component.
=> Add a red asterisk to required fields in a set

resources/js/components/fieldtypes/bard/BardFieldtype.vue
Fixes #2861.
The area that triggers autoscrolling up gets hidden under the fixed page header. I looked for autoscroll configuration options in TipTap and ProseMirrror, but didn't find any. So I ended up with putting a `pointer-events: none;` on the header while dragging. That works.
=> Fix Bard autoscroll issues 

src/Tags/Path.php, tests/Tags/LinkTest.php, tests/Tags/PathTest.php
This fixes the issue outlined in [this comment](https://github.com/statamic/cms/pull/3576#issuecomment-825613525)
If you use the link tag to point to an entry, and the entry doesn't exist in the target locale, it'll use the url of the original entry.
=> Use the original item's url if doesnt exist in the target site

src/Entries/AugmentedEntry.php, tests/Data/Entries/AugmentedEntryTest.php
Fixes #3597 
In 3.1, we added the entry author permissions feature.
You defined the authors by adding user IDs to an `author` (singular) field. You could put multiple authors in there if you want, but it would still go in the singular `author` field. We did this because if people were already using their own author based thing, there was a pretty high chance they were already calling the field `author`.
In the code though, we used the `authors()` method (plural). We did this because there _could_ be multiple.
Then, with the way augmentation works, if there's a method on the entry, it'll use that. Thats the conflict that was happening in #3597.
This PR makes it so that if you have an `authors` value, it'll favor that over the method.
=> Handle custom authors field

resources/js/components/assets/Browser/Browser.vue, resources/js/components/assets/Selector.vue, src/Http/Controllers/CP/Assets/BrowserController.php
Fixes #3602.
* Automatically adds the uploaded asset to the selection. And sorts by last modified, most recent first.
* Enables sortable columns in the Asset Browser.
=> Autoselect uploaded asset in selector

src/Assets/Asset.php, tests/Assets/AssetTest.php
In [this comment on the static site generator](https://github.com/statamic/ssg/issues/16#issuecomment-828407480) @tao was finding pages with mp3 assets taking a bonkers amount of time.
Turns out it was because when `width` was being requested somewhere in augmentation. Width comes from dimensions, dimensions looks in the meta data. If there's a null value in the meta data, it assumes its just missing or invalid and regenerates it.
His asset container had a ton of mp3 files, on s3, and would regenerate the meta file for each of them on every page load.
It's an mp3 so the dimensions _should_ be null. This PR adds that short circuit.
The page flies now.
=> Prevent regenerating asset meta file for non-images

resources/js/components/publish/Container.vue
This fixes #3537.
The meta object is deeply nested, so the `===` operator didn't cut it.
=> PublishContainer: deep compare before and after values in watch handler

.github/workflows/release.yml
`npm ci` will install all dependencies based on the package-lock.json.
`npm install` is kind of the same as `composer update` for PHP.
Just a few minutes ago, I finished a small article about it, which might explain a little better:
https://dev.to/visuellverstehen/why-to-use-npm-ci-instead-of-npm-install-mfd
=> Use npm ci instead of install

src/Stache/Indexes/Index.php, src/Stache/Stores/BasicStore.php
Fixes #3600 
When you delete an entry, the Stache will loop through the indexes and remove that entry from each of them.
If an index hasn't been cached already, it creates it. 
In #3600, if the `uri` index didn't already exist, it would create it. It's in here that the error happened. It has to query the structure to build the uri. The file was deleted at that point so it couldn't work it out. If the uri index already existed, it wouldn't try to rebuild it and you wouldn't get the error.
There's no point to create an index just to remove an item from it. In this PR, it will only try to update indexes that already exist.
=> Only remove items from indexes that have been cached

src/Stache/Indexes/Value.php
Fixes the issue in [this comment](https://github.com/statamic/cms/issues/3597#issuecomment-829256092) in #3597
Mimics the behavior of #3599 
The `authors` case is kinda special, but a guard here feels a little silly. It'll do until the refactor for #1759 happens.
=> Favor authors value in Stache index

resources/js/components/fieldtypes/grid/StackedRow.vue
Fixes #3498.
Since only top-level fields can be localizable, the `stacked-row` overrides the grid subfield's localizable setting in the config just before handing it to the `publish-field`.
=> Fix localizable grid in stacked mode

src/Fieldtypes/Bard/Augmentor.php
I've been looking into extending the Paragraph and Heading nodes to allow the addition of extra attributes. While it is currently possible to add new node types to the ProseMirror renderer, it is not possible to replace the built in ones. This functionality exists in the ProseMirror Renderer (Statamic is already using it to replace the Image node), but the Augmentor class does not expose a way for addons etc. to access it. This commit adds that ability.
=> Support replacing the built in ProseMirror nodes and marks with custom nodes and marks

src/Events/Concerns/ListensForContentEvents.php, src/Events/DuplicateIdRegenerated.php, src/Http/Controllers/CP/DuplicatesController.php
When you regenerate an ID as per #3619, it'll dispatch an event and trigger:
- A Git commit (if using the integration)
- GraphQL cache to be cleared
- REST API cache to be cleared
=> Dispatch and listen for duplicate ID regeneration event

src/Yaml/Yaml.php, tests/Yaml/YamlTest.php
Fixes #3612 
There wasn't a line break at the end if the last key was a multiline string.
Trim the dump first to prevent two line breaks, if there was one.
=> Fix yaml fence when dumping multiline string as last key

src/Fieldtypes/Bard.php
Fixes #3668.
Filters out the collections without a route when no collections have been selected. When the user decides to select specific collections in the Bard config, the responsibility for picking suitable ones is left to the user.
=> Bard: only show entries for collection with a route

src/Support/Str.php, tests/Support/StrTest.php
Our `Statamic\Support\Str` class extends `Illuminate\Support\Str` and offloads any undefined methods to `Stringy`.
When you would call `Statamic\Support\Str::replace()`, it would use `Stringy::replace()`.
[Laravel 8.41.0](https://github.com/laravel/framework/pull/37186) introduced `Str::replace()` with a different method signature than Stringy's `Str::replace()`. Since our class extends this, their new method will be favored.
This PR adds a `replace` method that explicitly uses Stringy's, so that it continues working like it used to.
Fixes #3697
=> Explicitly use Stringy for `Str::replace()`

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Node.js
Statamic includes a helper function for creating bard mark extensions. This PR adds the same functionality for node extensions.
=> Add bard node extension helper function

src/Globals/Variables.php, src/Taxonomies/LocalizedTerm.php, tests/Feature/GraphQL/ResolvesValuesTest.php
Fixes #3658 
There are tests for values being returned appropriately (i.e. CodeFieldtypeTest and CheckboxesFieldtypeTest) but they use entries. The implementation will call the same methods on terms, globals, users, whatever. This PR adds tests that ensure the methods exists in those classes and work as expected.
=> Resolve GraphQL values in globals and terms

src/Fieldtypes/Bard.php, src/Fieldtypes/Entries.php
This function assumes the `$collections` array contains the index `0`:
https://github.com/statamic/cms/blob/feeffbcd60c4ecd623c0175827de30b1d5210bbc/src/Fieldtypes/Entries.php#L97-L107
`$collections` has been filtered and doesn't necessarily contain the `0` index; after manipulating Collections, there may be "holes" in the indexes:
https://github.com/statamic/cms/blob/feeffbcd60c4ecd623c0175827de30b1d5210bbc/src/Fieldtypes/Bard.php#L376-L380
If the first collection has been filtered out because it doesn't have a route, the app crashes with `Undefined array key 0`.
Please tell me if you prefer another way to solve this.
The bug was introduced in https://github.com/statamic/cms/pull/3679. Pinging @arthurperton in case he has some opinions:)
=> don't rely on array index when showing first collection

resources/js/components/assets/Browser/Browser.vue
=> Fix permission name style on asset Browser canEdit method

src/Http/Controllers/CP/Collections/CollectionsController.php
This pull request closes #3720 by ensuring that the only collections that entries come from in the `mount` field is any collection *but* the current one.
=> Don't allow mounting collection on entries within that same collection

src/Forms/Email.php
This change allows other implementations of the submission storage (database).
It is currently not possible to store submissions in the db without creating a new class that replaces Statamic\Forms\Submission. This is the only change needed to implement a DB submission storage.
Sorry for the wrong PR before, I need to find a better way to create these.
=> Allow for other implementations of Submission Storage

src/Facades/Endpoint/URL.php
We are running statamic behind reverse a reverse proxy to terminate SSL for us before our docker container handles the request.
Currently this makes the URL Facade return a rather useless URL when calling `getSiteUrl`.
Instead of writing custom logic to determine if the original request was https (X-Forwarded-Proto or similar) I think it would make sense to just use Laravels request class to determine this.
Fixes #3696
=> Leverage Laravel to determine secure connection

src/Data/DataRepository.php, tests/Data/DataRepositoryTest.php
Fixes #3752 
Prevents the overhead of looping through all the repositories since we know it's going to return null anyway.
=> Bail out of Data::find() early if null is passed

src/Console/Processes/Process.php
Aim's to fix issue with installing/updating Addons or Statamic via the Statamic Control Panel.
For those who get the error:
```
In Factory.php line 677:
The HOME or COMPOSER_HOME environment variable must be set for composer to   
run correctly   
```
As referenced in https://github.com/statamic/cms/issues/3383
Addon installation is currently now working.
However there are issues with the Statamic Core updates, which appear to remove the contents of vendor/statamic/cms
I'm not sure where to start in regards to the removal issue, so feel free to chime in.
Thanks.
=> Pass ENV to SymfonyProcess via getenv() call.

src/Stache/Stores/BasicStore.php, src/Stache/Stores/Store.php, src/Stache/Stores/TaxonomyTermsStore.php, tests/Feature/GraphQL/TermsTest.php, tests/Stache/Stores/TermsStoreTest.php
In #3369, there was a changed made to how paths were stored in the Stache:
> Stache paths are stored as if they were an index, which prevents asset meta needing to be loaded for the initial cache build. It also makes all the other stache stores like entries etc just a tad faster.
Terms were handled a little differently, and the change introduced in that PR didn't take it into account and caused #3739 and #3775.
---
Since localized versions of terms exist in the same file, we would previously wangjangle the list of paths so that there would be multiple of the same path. We'd prefix the path with the site. Like `siteone::/path/to/term.yaml`. We did that so if we needed to `array_flip()` the paths, the dupes wouldn't disappear and we'd be able to quickly grab the key.
Now, we'll just use the …
=> Improve Stache path handling

src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php, tests/Fieldtypes/BardTest.php, tests/Fieldtypes/GridTest.php, tests/Fieldtypes/ReplicatorTest.php
Fixes #3481 
The meta for sub fields wasn't being appropriately passed along through Replicator.
The data wasn't preprocessed, so when you had `min_rows` in a Grid field, it was missing those dynamically added rows, and JS would 💩 itself.
The change looks bigger than it actually is. I changed the formatting of the `preload` method to match Bard's.
The real change is only a single method call. [In this commit](https://github.com/statamic/cms/pull/3782/commits/fd36172c840c1b6832e0fbd48aae679a1541d896).
=> Pass preProcessed values into Replicator's 'new' meta

src/View/Antlers/Parser.php, tests/View/Antlers/ParserTest.php
Similar to #3784, this one handles single tags that span multiple lines.
Like this example that the docs was using:
```
@{{ collection:blog
title:contains="awesome"
title:contains="thing"
author:is="joe"
}}
```
=> Handle multiline`@{{ }}` noparse tags

resources/js/components/field-validation/Builder.vue, resources/js/components/field-validation/Rules.js, src/Fields/Validator.php, src/Http/Controllers/CP/Collections/EntriesController.php, tests/Fields/ValidatorTest.php
In #3671, I'm moving the unique slug validation into the `slug` field of the blueprint, instead of being dynamically added.
When doing that, I noticed we don't really have any way to have different rules for updating vs creating within a blueprint.
If you've ever tried to use the `unique` validation rule in a Laravel app, you would have probably found yourself trying to exclude the current model from the rule. That's what I'm talking about here.
Since you can't do PHP stuff from inside the blueprint, I've introduced a concept of replacements (like in routes, or translations) that'll let you inject data from the entry.
```yaml
field:
type: text
validate:
- "rule_with_params:{id}"
```
This would become `rule_with_params:123` where `123` is the ID of the entry. Or `NULL` if on the "create" …
=> Validation replacements

src/Stache/Stores/CollectionEntriesStore.php
If you manually create an entry file without an ID, one gets added automatically.
Since #3671, the part where the filename gets incremented looks for an id.
Combine those two, and there was an infinite loop when you added an entry without an id.
Also, this now just writes the file. It doesn't "save" it, which avoids events and whatever other overhead is involved.
=> Prevent an infinite loop when you create an entry without an id

src/Http/Controllers/CP/Collections/EntriesController.php
When submitting an entry, it'll check for URI uniqueness.
This PR fixes it so that it'll validate it for the given site.
It's fine to have two entries with the same URI if they're on different sites, because their URLs will be different.
=> Validate uri uniqueness per site

src/Tags/Redirect.php, tests/Tags/RedirectTest.php
Recently had the need to pass route params to the `redirect` tag and discovered it wasn't supported.
This adds that ability. All params except `route` are passed to the `route()` helper.
Tests added.
=> Pass route params to `redirect` tag

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
=> Save the inherited blueprint to localized entry files

src/Forms/Email.php, src/Forms/Submission.php
When creating templates (HTML or Text) for use when sending emails, there are times when you just want a single template that any form on the site can use. However, I could not see a way to reference the form from within the template antler files, or in the data that was passed.
This pull request adds the Form to the Submission array that will be passed to the Email template.
You can then get the Form's title in your email templates using:
```{{ form:title }}```
This means that you can create a standard email template for your Forms, and the template itself can include a reference to Form details - such as the Form Name. This is really useful when your template loops over the ``{{ fields }}`` in the submission to output them as it makes the template more generic in nature.
The one …
=> Add “form” to Submission array

src/Sites/Site.php, tests/Sites/SiteTest.php
Proposal to add a `direction` to the site config allowing RTL configruations.
In the site config a optional parameter `direction` would be added.
The default value is `ltr` but can be set to `rtl`
``` php
'sites' => [
'default' => [
'name' => config('app.name'),
'locale' => 'ar_SA',
'url' => '/',
'direction' => 'rtl', // optionals: fallsback to ltr
],
],
```
In the layout it is usable from the site config
``` html
<html lang="{{ site:short_locale }}" dir="{{ site:direction }}">
```
This would be only for the frontend, I don't have any plans to change anything in the CP
---
Relates: [Ideas #248](https://github.com/statamic/ideas/issues/248)
=> Proposal: Direction in site config to support rtl layouts

resources/js/components/data-list/Actions.js, resources/js/components/data-list/HasActions.js, src/Http/Controllers/CP/ActionController.php
Closes statamic/ideas#549
Related to #3719 
This PR lets action classes provide their toast message, rather than just the "Action Completed" that you currently get.
```php
public function run($entries, $values)
{
$entries->each->whatever();
return 'This will be in the toast.';
}
```
Of course, you should probably be using translations:
```php
return trans_choice('Did whatever to an entry.|Did whatever to :count entries.', $entries);
```
If you don't return anything (like actions currently do), you'll continue to see the basic "Action Completed" message.
You may either return a string as shown above, or you can return an array with a `message` key.
```php
return [
'message' => 'This will be in the toast.',
'foo' => 'bar',
];
```
The array could be useful if you are creating your own …
=> Improve action responses

resources/js/components/fieldtypes/MarkdownFieldtype.vue, routes/cp.php, src/Fieldtypes/Markdown.php, src/Http/Controllers/CP/Fieldtypes/MarkdownFieldtypeController.php
Instead of using the `marked` JS library to generate the `markdown` fieldtype's preview, it'll now use an AJAX request to generate the preview on the server.
This lets us preview using any custom markdown parsers, which is more accurate with what you'd see on the frontend. (Closes https://github.com/statamic/ideas/issues/442)
It's also going to be necessary in #3850 which is going to add support for ID-based `statamic://` image URLs. If we continued to a JS preview, those would 404 since they wouldn't be the actual image URLs.
=> Render markdown preview on the server

src/StaticCaching/Cachers/FileCacher.php
Closes #3210 
This prevents the error you get when trying to statically cache a long URL.
It just prevents the page crashing. The page doesn't get cached though.
Used 255 since that's the limit on most operating systems.
=> Prevent error when url is too long for static caching

resources/js/components/fieldtypes/assets/AssetRow.vue
SVG thumbnails are smaller than raster thumbnails when using the asset fieldtype in list mode.
This PR updates the Tailwind classes so the thumbnails are consistent.
=> Adjust asset list svg dimensions

src/Auth/Passwords/PasswordDefaults.php, src/Auth/ResetsPasswords.php, src/Console/Commands/MakeUser.php, src/Http/Controllers/CP/Users/PasswordController.php, src/Http/Controllers/UserController.php, tests/Tags/User/RegisterFormTest.php
An updated version of #3732 utilising the suggestions from @jasonvarga 
Props to @rrelmy  for much of the code / work on this one, I believe with time #3732 would have got there I just have a client waiting for this so I'm impatient!
Really the only thing I'm unsure of is if it was the right move to make the PasswordDefaults class - possibly that function could have lived off something else, but this keeps it explicit, it seems like it's in an appropriate namespace etc
Most users will need to upgrade their underlying Laravel framework version to use this - 8.43.0 only dropped 2 weeks ago.
- Opens up support for utilising Laravel's Password::defaults() function
- Checks for the minimum framework version (8.43.0)
- Behaviour is exactly the same for users on older versions
- Behaviour is …
=> Add support for Laravel 8.x's Default Password Rules

src/StaticCaching/ServiceProvider.php
Fixes #3868 
Nothing was broken, but this avoids generating jobs that basically do nothing.
=> Only set up Static Caching invalidation when enabled

src/Stache/Indexes/Terms/Associations.php, src/Stache/Query/TermQueryBuilder.php, src/Stache/Stores/TaxonomyTermsStore.php, tests/Data/Taxonomies/TermQueryBuilderTest.php
Fixes #1993 
Fixes #1684 
Whether you use the taxonomy tag like this:
```
{{ taxonomy:tags collection="blog" }} ... {{ /taxonomy:tags }}
```
Or through the query builder like this (which is basically what the tag is doing):
```php
Term::query()->where('taxonomy', 'tags')->where('collection', 'blog')->get()
```
It's supposed to filter down the terms to ones being used within that collection. It doesn't.
Looks like [a refactor a while ago](e23065f8acbb2328f6f529a83e1cef411e6bb476) removed this and it never made it back in.
This PR brings it back, and adds some general term querying tests.
=> Fix filtering taxonomy terms by collection

src/Http/Controllers/FrontendController.php, src/Http/Responses/DataResponse.php, src/Providers/ViewServiceProvider.php, src/View/Antlers/Engine.php, src/View/View.php, tests/FrontendTest.php, tests/Routing/RoutesTest.php
This PR provides some enhancements for dealing with XML - for sitemaps, RSS feeds, etc.
The `.antlers.xml` extension is now supported.
If your template uses `.antlers.xml`, then the content type will automatically be set to `text/xml`. There's no need to manually set `content_type: xml` anywhere.
This applies to content (e.g. entries):
```yaml
---
title: Sitemap
template: sitemap  # sitemap.antlers.xml
---
```
or routes:
```php
Route::statamic('/sitemap', 'sitemap');
```
If your layout uses `.antlers.xml`, it'll set the content type to `text/xml`, and it'll inject the template into it like you're used to. It'll do it regardless of whether your template is xml or not. This is useful if you intentionally want to have a wrapper layout.
```yaml
title: Sitemap
template: sitemap
layout: …
```
=> Antlers XML views

src/StaticCaching/Cachers/FileCacher.php, src/StaticCaching/StaticCacheManager.php, tests/StaticCaching/FileCacherTest.php
I've been following #3210 and #3860. 
This PR adds a **fallback** for requests with long query strings by hashing them. 
The retrieval of the related responses from the cache will be slower than for regular requests, because Statamic needs to be fired up. I guess the performance is comparable to half measure static caching. Still beats not caching the response at all though.
I also made `max_filename_length` configurable for those who know what they're doing and want to tweak things to the max.
=> Static caching fallback for long query strings

resources/js/components/assets/Browser/Browser.vue
=> Hide breadcrumbs in asset browser when navigation is restricted

resources/js/components/fieldtypes/grid/Cell.vue
Fixes #3721 by applying the classes to the grid table cell.
**Rationale**
For regular fields (i.e. outside a grid) the field config's `classes` are already applied to the `form-group` wrapper, which also carries the `xxx-fieldtype` class. The equivalent to that wrapper in a grid table is the `td`. That element carries the `xxx-fieldtype` class too.
So the classes are always applied to the wrapper. In addition to that the classes are (already) only ever applied to the actual input for text fields.
=> Apply field config ‘classes’ to grid fields too

src/View/View.php, tests/FakesViews.php, tests/FrontendTest.php, tests/Routing/RoutesTest.php
Fixes #3892 
Routes could set a `null` layout.
```php
Route::statamic('/page', 'page', ['layout' => null]);
```
Entries though, `null` didn't do anything, but `false` would prevent the layout.
```yaml
title: My Page
layout: false
```
It'd probably be nice for null to work, but since it wasn't like that before, it would arguably be a breaking change, so I'm not going to change that.
This also makes our view fake throw an exception when you request a null view. The error would happen in the browser but not during tests.
=> Handle entries with layout false and routes with layout false or null

src/Search/Tags.php, src/Tags/Concerns/OutputsItems.php
Fixes #3682 
In order to use pagination with search and get the `pagination` array, you **need** to opt into it by using the `as=""` parameter.
I've done it this way to prevent it from being a breaking change. Normally you wouldn't _need_ the `as` parameter, and it'd default to the `results` array.
You use the same Antlers templating described on the collection tag. You need that inner loop over the results.
```mustache
{{ search:results paginate="5" as="results" }}
{{ results }}
{{ title }} {{ result_type }} <br>
{{ /results }}
{{ paginate }}
<a href="{{ prev_page }}">Previous</a>
<a href="{{ next_page }}">Next</a>
{{ /paginate }}
{{ /search:results }}
```
If you were using pagination as it was introduced in 3.0.30, you'd probably have done this:
```mustache
{{ search:results …
```
=> Search tag pagination

tests/CP/BreadcrumbsTest.php
Something in laravel/framework 8.48.2 broke our `BreadcrumbsTest`.
Looks like https://github.com/laravel/framework/issues/37789
Grabbing the instance out of the container, making it a partial mock, and putting it back into the container fixes it.
=> Use partial mock to fix breadcrumbs test

resources/sass/components/fieldtypes/button-group.scss, resources/sass/components/fieldtypes/time.scss, resources/sass/components/toggle.scss
Fixes #3897.
Because the rules were too generic, they were unintentionally applied to some other elements. They should only apply to the table cell.
=> Make column squeezing css rules more specific

resources/js/components/blueprints/LinkFields.vue
This will filter out `import` fields from the field suggestions you see when you click "Link Existing".
The lack of a `config` was causing an error. You shouldn't be referencing `import` fields anyway. You can just import a fieldset.
Fixes #3904 
This PR is really just adding `.filter(field => field.type !== 'import')`. The diff is bigger because it's been moved out to a variable for readability.
=> Filter out import fields

resources/js/components/assets/Browser/Browser.vue, resources/js/components/data-list/Table.vue
It's completely additive, in that it's only designed to SELECT items, not deselect. Works in all directions (up to down, down to up, etc).
It also prevents users from selecting text while holding down shift so you don't get a derpy looking UI after the interaction.
=> Multi-select DataList rows and Assets with shift key

src/Assets/Dimensions.php
Fixes #3932 
Apparently sometimes a failure just returns false, and sometimes it throws an exception.
Also changes the null dimensions to zeroes. If they're nulls, it'll continuously try to grab new dimensions.
=> Fix dimensions for zero byte image

src/Fieldtypes/Assets/AssetRule.php, src/Fieldtypes/Assets/Assets.php, tests/Fieldtypes/AssetsTest.php
Just a small refactor of #3922 
Instead of passing in the validation message, it'll know how to work itself out.
=> Keep all the asset rule logic in the class

src/Http/Responses/DataResponse.php
Site specific views stopped working in 3.1.25 when the XML templates were introduced.
This is because we interacted with the view before the extra view paths were added. This PR just adds them earlier.﻿
Fixes #3945
=> Fix site specific views not loading

resources/js/components/fieldtypes/CodeFieldtype.vue, resources/js/components/inputs/Textarea.vue, resources/js/components/publish/Sections.vue
Apparently this is a design "decision" from CodeMirror (https://github.com/codemirror/CodeMirror/issues/2469). Upside, we now have a new event when tabs are switched.
Also, I manually bound the autosize helper on the textarea component instead of using a directive as it doesn't handle all the events necessary to trigger the proper update.
Closes #3391 and #1952. Apologies for the branch name, didn't realize I could kill two issues with one PR at first.
=> Fix issue with Code and Textarea fieldtypes in inactive tabs

src/Tags/Session.php
This pull request adds a helpful `has` method to the [Session](https://statamic.dev/tags/session#content) tag.
This could be used to check if something exists in the users' session.
```
{{ if {session:has key="cart"} === false }}
No cart around here...
{{ /if }}
```
Without this tag, you can just do something like this instead.
```
{{ if {session:cart} === null }}
No cart around here...
{{ /if }}
```
---
I know this PR wasn't really asked for anywhere but just came across it while working on a site. Feel free to shoot it down, the alternative is a fine workaround.
=> Add 'has' method to Session Tag

src/Auth/Eloquent/User.php
Changed 
```php
public function removeFromGroup($group)
{
$groups = collect(array_wrap($group))->map(function ($group) {
return is_string($group) ? group::find($group) : $group;
})->filter();
$groups->each(function ($group) {
$this->groups->forget($group->id());
});
return $this;
}
```
To
```php
public function removeFromGroup($group)
{
$groups = collect(array_wrap($group))->map(function ($group) {
return is_string($group) ? UserGroup::find($group) : $group;
})->filter();
$groups->each(function ($group) {
$this->groups->forget($group->id());
});
return $this;
}
```
=> Change group:: to UserGroup:: in removeFromGroup method.

src/StaticCaching/Cachers/AbstractCacher.php, src/StaticCaching/StaticCacheManager.php
The StaticCacheManager is run before the TrustedProxy class. If TrustedProxy promotes your request to https, the StaticCache config thinks it's still on http, due to the config being set earlier in the request. Seen as though the string which is used to generate the hash which is used to store/get the page from cache (responses:<HASH>) is created using the request class directly, it (correctly) contains https://, but when the config is used (during invalidation for example), it contains http://, due to TrustedProxies not yet being evaluated when it's set.
This PR stops the base_url config from always being set, and instead uses the Request facade if it's not set.
=> Use Request facade to get base URL in AbstractCacher instead of StaticCacheManager if not set in config.

src/Stache/Stores/BasicStore.php, src/Stache/Stores/CollectionEntriesStore.php, src/Stache/Stores/CollectionsStore.php, src/Stache/Stores/Store.php, src/Stache/Stores/TaxonomiesStore.php, src/Stache/Stores/TaxonomyTermsStore.php, src/Stache/Stores/UsersStore.php
These two methods were doing essentially exactly the same thing.
Maybe once upon a time they were doing different things, but right now it's the same.
It takes a file and checks whether its applicable to a respective Stache store. (e.g. ignore non-yaml files in the globals directory)
When the cache gets built, it was using `getItemFilter`, but in the file change handler (where it detects if you've manually saved files) it was using `getFileFilter`.
While reviewing #3948 I noticed that I was still getting the error when I'd manually save a tree yaml file, but it would work fine on a fresh cache. That's why.
Then there's the poor `filter` method on the `UsersStore` who hasn't done anything for even longer. It wasn't renamed to `getItemFilter` whenever that happened everywhere else.
=> Consolidate Stache's `getItemFilter` and `getFileFilter`

src/Fieldtypes/Arr.php, src/GraphQL/TypeRegistrar.php, src/GraphQL/Types/ArrayType.php, tests/Feature/GraphQL/Fieldtypes/ArrFieldtypeTest.php
This fixes #3961 for both dynamic and keyed arrays. It just outputs them as is:
=> Support Array fieldtype in GraphQL

resources/js/components/assets/Editor/Editor.vue, resources/sass/components/assets.scss, src/Assets/Asset.php
Fixes #3962.
Took the new approach for image previews and applied it to SVG, audio en video previews too.
=> Make sure media previews don’t overflow in the asset editor

src/Modifiers/CoreModifiers.php
The modifier isn't able to handle collections which is what arrays get augmented into when passed to the view. This PR adds support for the augmented collection.
=> Support collections in the `reverse` modifier

src/Http/Controllers/CP/Collections/CollectionsController.php
Together with #3889 this should fix #3478.
(#3889 deletes the tree file when deleting the collection)
=> Delete trees when setting a collection to not orderable

src/Sites/Site.php, tests/Sites/SiteTest.php
Closes https://github.com/statamic/ideas/issues/602
If this is accepted, I can also update the docs before it will be merged.
now you can define site-specific `attributes` in your `config/statamic/sites.php`
This is useful if you want to define different themes per site for example.
```php
<?php
return [
'sites' => [
'default' => [
'name' => config('app.name'),
'locale' => 'en_US',
'url' => '/',
'attributes' => [
'theme' => 'default',
],
]
]
];
```
This can now be used to set a class:
```html
<body class="theme-{{ site:attributes:theme }}">
</body>
```
=> feat: add attributes to the Site config

resources/js/components/data-list/Table.vue
Allows for quick single selection in data lists. When you select an item and you're only allowed to select one item tops, any previously selected item is deselected automatically. Fixes #3949 by implementing the suggested UX. Applies to all data lists.
=> Data list single select

resources/lang/en/fieldtypes.php, src/Fieldtypes/Link.php
Fixes #3805. Makes the collections configurable and defaults to all mounted collections.
Part of the code is copied from a recent addition to `Fieldtypes/Bard.php`. It would be nice to add something like a `whereMounted()` method to the `Collection` facade and have this logic in one single place, but that would mean a breaking change I guess.
=> Make Link fieldtype collections configurable

resources/js/components/fields/Settings.vue, resources/lang/en/messages.php, resources/lang/en/validation.php, src/Fields/Fields.php, src/Fields/Validator.php, src/Http/Controllers/CP/Fields/FieldsController.php, tests/Fields/FieldsTest.php
This is an implementation for [idea #46](https://github.com/statamic/ideas/issues/46) and a partial fix for #3956.
It adds the mechanics for checking for reserved words and notifying the user in a meaningful way. The list of reserved words can (and probably should) be extended in the future of course.
=> Prevent using reserved words as field handles

src/Http/Controllers/CP/Fields/FieldsController.php
Fixes #4007
By calling process() _before_ validate(), it was using the processed values for validation. It shouldn't.
In the case of #4007, that meant it would convert the array into a string because the field had max_files: 1. Then the validation would fail because it was expecting an array.
=> Fix validation on blueprint editor

resources/js/components/fieldtypes/VideoFieldtype.vue
Fixes #3744 in the most peculiar way.
The iframe with the video caused Vue / Javascript to completely stop working in Safari. Now it doesn't anymore.
=> Stop iframe from killing Vue in Safari

src/Stache/Stores/CollectionTreeStore.php
Fixes #4018.
I ended up with tidying the path on the spot, using the same approach as in `Statamic\Stache\Traverser->traverse()`. No need to worry what kind of (mix of) (back)slashes any specific `SplInfo` method returns.
=> Tidy tree path before parsing

src/Exceptions/BlueprintDoesNotExistException.php, src/Exceptions/BlueprintNotFoundException.php, src/Http/Controllers/CP/Collections/EntriesController.php
This pull request adds a helpful exception that'll be thrown if a specified blueprint does not exist. I've added an Ignition solution to the exception that'll suggest any blueprints close _ish_ to the specified one (done the same way as in the [`CollectionNotFoundException`](https://github.com/statamic/cms/blob/3.1/src/Exceptions/CollectionNotFoundException.php))
Closes #3920
=> Throw a helpful exception if a referenced blueprint does not exist

src/Console/Commands/StaticWarm.php, src/Providers/ConsoleServiceProvider.php
This is a continuation of #3745 by @edalzell, which was closed 25 days ago. I think this command will be a very welcome addition to the toolbox and Erin was okay with me taking over. So here we go.
=> Command to warm the static cache

src/Http/Controllers/CP/Collections/EntriesController.php
Fix updating of entry's `author` field when user doesn't have permission to edit other authors. This would even break when trying to save the author's own entry.
Closes #3677.
=> Fix updating of entry's `author` field

src/Assets/AssetRepository.php
This reverts #3964, which would reopen #3896.
Fixes #4048
=> Revert "Generate asset meta after updating the container contents (#3964)"

resources/views/partials/global-header.blade.php
Checks if the user can access Telescope, will only add the link if they can.
Also changes the check from telescope.enabled to instead look for the existance of the route and changes the link to be returned from route('telescope'), so that it is functionally the same as https://github.com/statamic/cms/pull/4074
=> Check permissions for Telescope

src/Fieldtypes/Bard/ImageNode.php
A client renamed a folder today. Seems like when URLs in the bard field are changed it's not handled gracefully.
This is a quick PR and seemed to work on my machine. Sorry I did not have time to do more extensive investigation and testing and PHP is not my main language... what I am trying to say is feel free to make changes!
=> Prevent 500 error when users move or rename assets

tests/Tags/Concerns/QueriesConditionsTest.php
While testing #3976 I suspected it would conflict with existing query code and maybe even fail the tests. I notice the tests were written in a way that they should have been failing, but weren't.
- Add expectation counts so the test would fail if the method wasn't called as expected.
- There was a test for an `is_in` condition, which should have failed because it's actually just `in`.
=> Fix QueriesConditionTest

src/Console/Processes/Process.php, src/Git/Git.php, tests/Console/ProcessTest.php, tests/Git/GitTest.php
Fix an error that prevents git commit and push when one of the paths is a symlink.
Note: More on how git deals with symlinks here: http://tdongsi.github.io/blog/2016/02/20/symlinks-in-git/
References #4045.
=> Fix git integration symlinked paths

src/Console/Commands/AssetsGeneratePresets.php, src/Console/Commands/Multisite.php, src/Console/Commands/StacheDoctor.php, src/Console/Commands/StacheWarm.php, src/Console/Commands/StaticWarm.php, src/Console/Commands/SupportDetails.php, src/Git/CommitCommand.php
Some commands descriptions do use a dot at the end and others don't. 
This PR does align the syntax as used by Laravel.
=> Align command descriptions

src/Console/Commands/SiteClear.php
When running `php please site:clear`, it removes any filesystem disks that are being used by asset container.
So if you create a container, you probably also create a disk in `config/filesystems.php`. It'll reset that. Great, that's handy.
But not always. If you're using the `assets` disk that we've added to `statamic/statamic`, it'll remove that too. Starter kits in 3.2 assume the clear slate is what you get on `statamic/statamic`. If we remove the `assets` disk (or any other default ones) it may be broken if they're relying them being there.
This PR prevents removal of the disks that you'd find in `statamic/statamic`.
=> Prevent clearing the default disks

resources/lang/da/messages.php, resources/lang/de/messages.php, resources/lang/de_CH/messages.php, resources/lang/en/messages.php, resources/lang/es/messages.php, resources/lang/fr/messages.php, resources/lang/id/messages.php, resources/lang/it/messages.php, resources/lang/nl/messages.php, resources/lang/pt/messages.php, resources/lang/sl/messages.php, resources/lang/zh_TW/messages.php, src/Actions/RenameAsset.php
It's now not true - references _will_ be updated.
Closes #4137
=> Remove warning about renaming assets

resources/js/components/structures/PageEditor.vue, resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/id.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json, resources/lang/sl.json, resources/lang/zh_TW.json
Removing the `title` instructions:
- For regular nav items, the fallback behavior doesn't even happen as it was saying.
- For entry nav items, the entry's title will be displayed in the field due to the syncing feature, so it will be implied to the user.
Changing the `url` instructions to remove the "leave blank for a text-only item" part. It's clear enough. If you leave out a url, you don't get a url.
Fixes #4140
=> Fix nav item editor stack instructions

resources/views/collections/blueprints/create.blade.php, src/Http/Controllers/CP/Fields/ManagesBlueprints.php
Slugify blueprint handles with underscores instead of snake casing.
This removes things like colons and question marks.
Fixes #4114 
While I was in here I noticed the validation wasn't working.
This also fixes that.
=> Fix blueprint handles and validation

resources/js/components/fieldtypes/LinkFieldtype.vue, src/Fieldtypes/Link.php
Replaces #4146. Moves a bunch of the logic to the server side, so the initial values are passed directly into the component.
Also targets 3.1 instead of master.
Fixes #4133
Ref #3500
=> Fix the LinkFieldtype's perpetual dirty state

src/CP/Navigation/NavItem.php
=> Ignore query string when determining active status in CP nav

src/Taxonomies/AugmentedTerm.php, tests/Data/Taxonomies/AugmentedTermTest.php
In #4090 I noticed that editing a title in live preview would not be reflected on the front end.
Turns out it's because the `title` method doesn't use supplemental data.
Live preview supplements the item with values you've entered in live preview.
I put it in the augmented term class rather than change the term's title() method because the title() seems more of an "official" value - you probably don't want the temporary supplemental values to have an effect there.
=> Augmented term titles uses supplemental data

src/Console/Commands/StaticWarm.php
From what I experience locally, this should fix #4082. In addition it also outputs errors for failed requests now.
@jasonvarga I remember you had a preference for the Laravel HTTP Client, but it has these issues that I'm not able to solve and that don't occur when using Guzzle directly (see discussion in #4082).
@edalzell I added your `->sort()` addition from your PR #4124 here for convenience. That PR can be closed if this one gets merged. Bear in mind that, since we're using concurrent requests, the responses might still come back in a different order.
@edalzell I am really curious if this solves the problems for your specific site and setup. Would be great if you're able to test this.
=> Fix failing / missing requests in Static Warm command

src/Assets/AssetReferenceUpdater.php, tests/Listeners/UpdateAssetReferencesTest.php
=> Update asset references in links inside bard

src/Modifiers/CoreModifiers.php, tests/Modifiers/AliasTest.php
Much Statamic data, augmented, is now a collection and not an array. The `as` modifier was expecting an array.
=> `alias` modifier works with collections

src/Tags/Nav.php, src/Tags/Structure.php
Entries with redirects use the redirect url, not the entry url, to determine `is_current`. All redirected pages are current when the target of the redirect(s) is current. A simple sidebar navigation to illustrate the problem:
Original
Fixed
=> Use `urlWithoutRedirect` to determine `is_current`

src/Imaging/Manager.php
This works fine (and crops while respecting the image's focal point):
```php
'presets' => [
'small' => ['w' => 80, 'h' => 80, 'q' => 75],
],
```
But explicitly defining `crop_focal` breaks cropping altogether:
```php
'presets' => [
'small' => ['w' => 80, 'h' => 80, 'q' => 75, 'fit' => 'crop_focal'],
],
```
That said, `crop_focal` is essentially the default behaviour, so we can just filter this out of the user's preset.
Closes #1431.
=> Fix explicit `'fit' => 'crop_focal'` in configured glide presets.

src/Tags/Iterate.php
This PR adds the option to pass a variable by parameter. This makes it possible use dynamic variables:
```html
{{ foreach :array="fields[field].options" }}
...
{{ /foreach }}
```
=> Enhance foreach tag to support dynamic variables 

config/system.php, src/Console/Processes/Process.php
It appears that a few people are still having issues with
```
In Factory.php line 677:
The HOME or COMPOSER_HOME environment variable must be set for composer to   
run correctly 
```
There might be more ENV needed to expand upon https://github.com/statamic/cms/pull/3734 
Pending the results of https://github.com/statamic/cms/issues/3383
=> HOME or COMPOSER_HOME environment variable - continued

src/Facades/Blueprint.php
Updated the docblocks as the source of truth, the [BlueprintRepository](https://github.com/statamic/cms/blob/3.2/src/Fields/BlueprintRepository.php) doesn't have an `all` method anymore.
=> The `BlueprintRepository` does not have an `all` method anymore

resources/js/components/AddonList.vue
When working on a trial site in the Control Panel, the add-on seller avatars show in front of the info bar. Removing the `z-index` resolves this.
=> Don't stack add-on seller avatars above infobars

src/Http/Controllers/FormController.php
Currently, the form controller is looking for a `X-Requested-With` header to equal `XMLHttpRequest` in order to respond with JSON. This isn't standard though, and is mostly used with libraries such as Axios.
This means a regular `fetch` request won't get a JSON response. The user can add this header manually, but I think this PR adds a sensible check to see if the request is wanting a JSON response as well.
=> Send JSON back for form submissions via a standard fetch request

src/StarterKits/Installer.php
Fixes #4200
The bit where it would take the file path and remove the vendor/{vendor}/{package}/ part would fail on windows because it would have backslashes, but the code was expecting forward slashes.
Adding Path::tidy() would convert backslashes to forward slashes.
=> Fix starter kits not being installable on Windows

src/Fieldtypes/Replicator.php
Fixes #4208
When using a validation rule such as `min`, it'll act like a string unless you also have an `array` rule, then it'll treat it like an array.
=> Validate replicator as an array

resources/views/widgets/collection.blade.php
This pull request makes the title of the collection widget into a link.
Closes statamic/ideas#636
=> Make collection widget title into a link

src/Statamic.php, tests/Facades/CP/NavTest.php
References #4022 
When using Vapor, the assets in the `public` directory won't exist. They get sent over to S3 and served via a CDN.
The `Statamic::svg()` method reads the svg files from the `public` directory. But again, on Vapor, they're not there.
This PR just changes the method to look for svgs in the Composer vendor directory, which _would_ be there.
=> Read inline svgs from composer vendor directory

src/Assets/AssetContainerContents.php, src/Assets/AssetFolder.php, tests/Assets/AssetFolderTest.php
Adds new folders to the asset container contents path, so they still show after a refresh when the stache watcher is disabled. Let me know if you want anything changing.
Fixes #3722
=> Add new folders to container contents cache

src/Fieldtypes/Bard.php
Fixes #4240 
There's more to the issue, it only happens when it's inside a replicator. But this'll at least let it pass validation.
=> Don't use array validation for bard

resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/id.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/zh_TW.json, resources/views/licensing.blade.php
This adds the "Buy Licenses" translation. Closes #4280
=> Add missing translation

resources/views/globals/configure.blade.php, src/CP/Navigation/CoreNav.php, src/Http/Controllers/CP/Globals/GlobalsController.php, src/Policies/GlobalSetPolicy.php, src/Policies/GlobalSetVariablesPolicy.php, tests/Feature/Globals/ConfigureGlobalsTest.php, tests/Feature/Globals/ViewGlobalsListingTest.php
Fixes #1636
- Globals that don't exist for the selected site will use the "configure" url instead of the "edit variables" url.
- If you don't have permission to configure it, it'll just get filtered out.
- Applies to the side nav and the globals index listing.
- Also fixes an issue where a user without permission to configure a set could visit the edit page. (They couldn't submit, though)
=> Adjust Globals listing

resources/js/components/Slugify.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/fieldtypes/SlugFieldtype.vue
When you create a localization of an entry, the `slug` will become reactive to the `title` change again.
Only happens when creating the initial localization, not when switching to an existing one.
Closes #3933
Closes statamic/ideas#334
~WIP. Not sold on this particular event approach, it feels too global. But it's working so far.~
It only does it for "the slug field". Other `slug` fieldtypes that aren't called slug won't be affected. It'll do.
=> Re-enable slugification when creating a localization

src/Facades/Entry.php, src/Tags/ParentTags.php
Fetch the parent data from the current site/locale.
Updated the Entry::findByUri `@method` signature to include the `$site` parameter
Also, `URL::removeSiteUrl()` adds a superfluous slash and should probably call `URL::tidy()` before returning. I did not change `removeSiteUrl` in this PR  yet, because I wanted to confirm whether the current behavior is intentional (as far as I see, that method is not covered by a test).
=> Localize the parent tag

src/Tags/Partial.php
There are instances where it can be useful to check if a partial exists before including it, and conditionally change the output based on this check's result.
For example, you could have a partial (such as an SVG icon) that gets included based on the slug of a Taxonomy Term. During dev, you can create Terms and their associated partials. But if a content author creates a new Term in production, and a partial doesn't exist, the partial inclusion will throw an exception (and bring that page down).
The aim of this is to provide a simple mechanism to check if the partial exists using Laravel's `exists` method on the view. This uses the same `src` attribute as the `partial` tag, and works for a string, dynamic string, or variable
Use as a string:
```
{{ if {partial:exists …
```
=> Add "exists" method to Partial tag

src/Data/HasOrigin.php, src/Entries/Entry.php, tests/Data/Entries/EntryTest.php, tests/Search/SearchablesTest.php
By setting `field: null` in your front-matter on a localized entry, it should actually be null, instead of falling back to the value in the origin entry. If you omit the field, it'll fall back. 
Fixes #3987
Fixes #3738
Actually fixes #3406 even though it was closed. The previous "fix" only added the nulls to the files.
=> Prevent explicit nulls from falling back to origin

resources/js/components/inputs/relationship/RelationshipInput.vue, resources/js/components/inputs/relationship/Selector.vue, src/Fieldtypes/Entries.php, src/Fieldtypes/Relationship.php
Regular entry listings are fast, they only get the values for the columns that are visible.
This wasn't happening for the `entries` fieldtype. It was getting all the values for each entry.
This PR applies the treatment to the `entries` fieldtype.
Related: #2857
=> Fix slow entries fieldtype

src/Modifiers/CoreModifiers.php, tests/Modifiers/GroupByTest.php
The existing `group_by` modifier does the grouping, but then it's keyed so in order to template anything, you need to know the key. This is from the existing docs:
```yaml
sponsors:
-
sport: basketball
team: Jazz
-
sport: baseball
team: Yankees
-
sport: basketball
team: Bulls
```
```html
{{ sponsors group_by="sport" }}
{{ basketball }}
<h2>{{ team }}</h2>
{{ /basketball }}
{{ /sponsors }}
```
```html
<h2>Jazz</h2>
<h2>Bulls</h2>
```
This PR adds a `groups` array that lets you loop over all the groups, with the the `items` inside each one.
```html
{{ sponsors group_by="sport" }}
{{ groups }}
<h2>{{ group }}</h2>
<ul>
{{ items }}
<li>{{ title }}</li>
{{ /items }}
</ul>
{{ /groups }}
{{ /sponsors }}
```
```html
<h2>basketball</h2>
<ul>
<li>Jazz</li>
<li>Bulls</li>
</ul>
<h2>baseball</h2> …
```
=> Enhance the `group_by` modifier

src/Modifiers/CoreModifiers.php
This modifier lets you split an array into `$n` number of equal groups. You can loop through the groups with `{{ groups }}` and the items inside each group with `{{ items }}`. This is really useful for breaking a list up into multiple columns or boxes and other things like such as.
```
<div class="flex">
{{ collection:blog as="entries" }}
{{ entries split="2" }}
{{ items }}
<div class="w-1/2">
{{ items }}
<a href="{{ url }}">{{ title }}</a><br>
{{ /items }}
</div>
{{ /items }}
{{ /entries }}
{{ /collection:blog }}
</div>
```
```
{{ entries split="2" }}
```
=> Split Modifier

resources/js/components/data-list/Table.vue
This pull request partly addresses #4246 by hiding the 'toggle all' checkbox in the Asset Browser if `max_items` on the field is 1.
=> Don't show 'toggle all' checkbox if `max_items` is 1

src/Auth/Eloquent/User.php, src/Auth/Eloquent/UserQueryBuilder.php, src/Auth/Eloquent/UserRepository.php, src/Auth/UserRepository.php, src/Console/Composer/Lock.php, src/Fieldtypes/Users.php, src/Providers/AuthServiceProvider.php, src/Stache/Repositories/UserRepository.php, tests/Auth/EloquentUserRepositoryTest.php, tests/Auth/StacheUserRepositoryTest.php, tests/Auth/UserRepositoryTests.php, tests/Fakes/Composer/Package/PackToTheFuture.php
This fixes an issue where you couldn't override the user class.
You can now do:
```php
public function register()
{
$this->app->bind(\Statamic\Contracts\Auth\User::class, CustomUser::class);
}
```
Bonus: Fixes `Composer::getInstalledVersion()` not checking dev packages.
=> Fix user binding and shallow augmenting

src/Stache/Repositories/TermRepository.php, src/Taxonomies/LocalizedTerm.php, src/Taxonomies/Term.php, tests/Data/Taxonomies/LocalizedTermTest.php, tests/Feature/Taxonomies/TermEntriesTest.php
Fixes #4320 
`entriesCount()` was not filtering by site or collection. Now it does both.
`entries()` was filtering by collection, but not site. Now it does both.
When calling `entries()` or `entriesCount()` from the base Term class, it won't do any site filtering. It will do the collection filtering.
=> Fix term entries and entry counts

src/Fields/Blueprint.php
This simple PR makes it possible to ensure multiple Blueprint fields at once by providing an array of fields like so:
```php
$event->blueprint->ensureFieldsInSection([
'seo_title' => [
'type' => 'seo_meta_title',
'display' => 'Meta Title',
'instructions' => 'Set the Meta Title of this entry. Defaults to the entry\'s `Title`.',
'localizable' => true,
'listable' => 'hidden',
'character_limit' => 60,
'input_type' => 'text',
'antlers' => false,
'validate' => [
'max:60',
],
],
'seo_description' => [
'type' => 'textarea',
'display' => 'Meta Description',
'instructions' => 'Set the Meta Description of this entry.',
'localizable' => true,
'listable' => 'hidden',
'character_limit' => 160,
'validate' => [
'max:160',
],
],
], 'SEO');
```
=> Allow to ensure multiple Blueprint fields at once

src/Entries/Entry.php, src/Http/Responses/DataResponse.php, src/Taxonomies/LocalizedTerm.php, src/View/Cascade.php, tests/View/CascadeTest.php
Adds a `Cascade::hydrated()` method so you can do whatever to the cascade after it's been populated with data.
```php
Cascade::hydrated(function ($cascade) {
$cascade->set('foo', 'bar');
});
```
Fixes #4013
Closes #4156
=> Fix cascade hydration

src/Search/Search.php
Hi There,
Unsure if it was the desired outcome, but I would have expected for \Statamic\Facades\Search::indexExists('Index does not exist') to return false, however this isn't the case and instead the exception below is thrown.
```
InvalidArgumentException
Search index [Index does not exist] is not defined.
```
This PR changes the following check, which will throw the exception if the index doesn't exist in the config and will return true or false, if it does but then the index data file does or does not exist.
```php
public function indexExists($index = null)
{
return $this->index($index)->exists();
}
```
To this, which will return false instead of throwning the exception, if the index has not been entered in the config, and then will respond with the same true or false condition that …
=> Adjustments to Search::indexExists

resources/js/components/fieldtypes/ArrayFieldtype.vue, resources/js/components/fieldtypes/CodeFieldtype.vue, resources/js/components/fieldtypes/Fieldtype.vue, resources/js/components/fieldtypes/FloatFieldtype.vue, resources/js/components/fieldtypes/IntegerFieldtype.vue, resources/js/components/fieldtypes/LinkFieldtype.vue, resources/js/components/fieldtypes/ListFieldtype.vue, resources/js/components/fieldtypes/MarkdownFieldtype.vue, resources/js/components/fieldtypes/RangeFieldtype.vue, resources/js/components/fieldtypes/SlugFieldtype.vue, resources/js/components/fieldtypes/TableFieldtype.vue, resources/js/components/fieldtypes/TextFieldtype.vue, resources/js/components/fieldtypes/TextareaFieldtype.vue, resources/js/components/fieldtypes/YamlFieldtype.vue, resources/js/components/fieldtypes/bard/BardFieldtype.vue
UI performance / responsiveness decreases when user is typing in fields which are part of replicator (or even nested replicators) fieldset.
The reason for the decrease of performance is side effects caused by `fieldtypes/Fieldtype.vue` component emitted `input` event, which starts to bubble events to parent components (keep in mind that in some cases, depending on field sets size, payloads of events can be quite big) as a result of which data in parent components is replaced and then passed down back to child components, where events related to data changes might also be triggered.
This issue affects all field types where a lot of user input is expected - Bard, Code, Text, etc.
The first thought that came to my mind is debouncing of `update` method in `fieldtypes/Fieldtype.vue` component. …
=> Fieldtype debounce update

resources/js/components/users/Wizard.vue, resources/views/users/create.blade.php, src/Http/Controllers/CP/Users/UsersController.php
Essentially, whenever a user is being created using the wizard, they will either be presented with a single name field or two name fields (first/last) - depending on if a `first_name` field exists on the user blueprint.
Feel free to close if you're planning on implementing in a different way.
Closes #4395
=> Allow for separate first/last name fields when creating user, if they are separate in the blueprint

resources/sass/components/fieldtypes/bard.scss
The floating toolbar button styles are applied broadly to all toolbar buttons, including the link popover buttons. This PR scopes it to the `bard-toolbar-button` class, same as in fixed mode.
=> Bard: fix popover button styles when using floating mode

resources/js/components/collections/View.vue, resources/views/collections/show.blade.php
Honestly this is not as beautiful as I'd hoped it could be, but it works. I can't find a clean way to check in Vue to check whether the slot is 'empty'. That's why now it's just doing a check to see if the slot is missing instead.
Closes #4348
=> Hide the twirldown on the collection view page when it's empty.

src/Fieldtypes/Structures.php
Fixes #3875
This prefixes the handle with `collection::` so that collection selections are properly recognized. Navs continue to just use their handle.
Threw a private method in there instead of changing the id() method to prevent any intentional knock-on effects.
=> Use appropriately prefixed collection structure handles

src/Fieldtypes/Code.php, tests/Fieldtypes/CodeTest.php
- Add processing tests
- The tests showed I had the condition backwards for how it's processed. Fields with a selectable mode should save the mode. Non-selectable modes should just save the string. It was the other way.
- Prevent preprocessing config. `html` fields were showing the code/mode array because it was running preProcess on the code field.
=> Fix a couple of code fieldtype issues

src/Auth/UserTags.php
This one will also be accompanied by [a PR to the docs](https://github.com/statamic/docs/pull/573), since the docs are outdated; nowadays we only add a `token` variable to the password reset URL. This token is then sent with the email address + password (& confirmation) to check whether the reset is valid.
Closes #4340 => adds the `url_invalid` variable for in the template.
Closes #4370 => redirects to the current page when you don't pass a `redirect` parameter to the `user:reset_password_form` tag.
Fixes another bug that hasn't been opened: it now actually sets the `success` variable for you when the reset was successful. Before it was checking for the `success` session, [but it's actually named `status`](https://github.com/statamic/cms/blob/3.2/src/Auth/ResetsPasswords.php#L152) …
=> Fix user:reset_password_form tag.

src/Http/Controllers/API/GlobalsController.php
Fixes #4184. Allows for fetching localized content via the Globals API endpoint for a single global like you can for all globals.
```
/api/globals/some_global # returns default site content
/api/globals/some_global?site=sitetwo # returns sitetwo's localized content
```
=> Add multisite support to Globals API

resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/id.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/zh_TW.json, translator
In some languages the translation key was using a different apostrophe than the [text from laravel](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Notifications/resources/views/email.blade.php#L54) so it was not translated correctly.
For example in the password reset mail the text is used.
=> Fix translation key apostrophe

resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/id.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/zh_TW.json, translator
In #4630, the line should have been added, not replaced.
In versions of Laravel before 8.48.0, users will still have the translation with the older apostrophe, so the line would be untranslated. This PR adds both. Same translation though.
=> Bring back the old apostrophe for older versions

resources/js/components/field-conditions/Converter.js
=> Fix null and empty string field condition handling

src/Structures/Tree.php, tests/Data/Structures/TreeTest.php
Quite the rabbit hole, but it turns out that the `parent` method of a tree was not yet supplying the page data to the new page instance it was creating.
This means that when displaying navs with `include_home="true"` there wouldn't be any supplemental data available that was set on the nav.
Fixes #4258
=> Add supplemental page data to the parent of trees.

src/Sites/Site.php, src/Tags/Locales.php, tests/Sites/SiteTest.php, tests/Tags/LocalesTagTest.php
This PR enhances the `locales` tag with an `all` parameter. When set to `true` the tag will include basic data for all entries that are not localized or published. This makes it possible to use the tag for a global language switcher that falls back to the homepage if an entry doesn't exist for a particular site. I've also added an `exists` variable, which lets you visusally indicate if a site is localized or not.
This PR solves an issue that is talked about on Discord on a regular basis. It's one of the most asked for features when working with multi-sites. It also closes this idea: https://github.com/statamic/ideas/issues/695.
Closes statamic/ideas#695
Closes statamic/ideas#588
=> Enhance Locales Tag

src/Fieldtypes/HasSelectOptions.php, tests/Fieldtypes/LabeledValueTests.php, tests/Fieldtypes/MultipleLabeledValueTests.php
When select fields (or radio/checkboxes/button_group fields) use numeric options, like this...
```yaml
myfield:
field:
type: select
options:
1: One
2: Two
```
...the fieldtype ends up saving the value as a string (javascript objects can't have numeric keys), so you end up with this:
```
myfield: '1'
```
Then in #4483, it was made so that if the value didn't match an option exactly, it would use itself as the value and label.
The string version of the number does not exactly equal the option in this case.
This PR makes it so that integer strings get treated as integers.
ie. both these work
```
myfield: '1'
```
```
myfield: 1
```
Floats get treated as strings though, since you can't have a float as a key in PHP. They'll be strings, even if there's a real float in the data.
```yaml
myfield: …
```
=> Handle selects (etc) with numeric keys

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
- ie. If the collection is `articles` and the blueprint is `standard_article`, it will load the following template: `resources/views/articles/standard_article.antlers.html`.
Closes https://github.com/statamic/ideas/issues/192.
=> Ability to infer template from blueprint

src/Http/Middleware/Localize.php
Configures the app to take advantage of the new `lang` config introduced in https://github.com/statamic/cms/pull/4612. This allows the `trans` modifier to search for translations like `fr_FR` when `lang` is configured for a site.
=> Set the app locale to the sites lang

src/Exceptions/NavigationNotFoundException.php, src/Tags/Nav.php, src/Tags/Structure.php
It now does boom 💥 .
The question is whether it should only do it for the `handle` parameter, or for everything. Right now it does so for:
- `{{ nav:doesnt_exist }}`
- `{{ nav handle="doesnt_exist" }}`
But **not** for: `{{ nav }}`, this falls back to `{{ nav:collection:pages }}` like before.
Since it now says boom instead of 'silent fail' it's not a backwards compatible change, but maybe that's fine?
Closes #4223
=> Throw exception when navigation could not be found.

config/oauth.php, resources/views/auth/login.blade.php, src/Http/Controllers/CP/Auth/LoginController.php
This pull request adds a config option in case developers want to hide the 'Login with email' button when their using OAuth.
For reference: #4599
=> Add config option to hide email login button when using OAuth

src/Query/Builder.php, src/Query/IteratorBuilder.php, src/Stache/Query/Builder.php, src/Tags/Concerns/QueriesConditions.php, tests/Data/Assets/AssetQueryBuilderTest.php, tests/Data/Entries/EntryQueryBuilderTest.php, tests/Search/QueryBuilderTest.php
Sorry for all the PRs but for the sake of completeness this adds `whereNull` / `whereNotNull` methods to the QueryBuilder.
Allows you to write queries such as:
```
Entry::query()
->whereNull('field')
->get();
Entry::query()
->whereNull('field')
->orWhereNotNull('another_field')
->get();
```
This test is failing, however should the assert count not be 2 rather than 3? Or does is_empty cover both blank and null?
https://github.com/statamic/cms/blob/d49cbf9cf9fc67d4cc6bea77a333e6a682bddafc/tests/Tags/Concerns/QueriesConditionsTest.php#L472
=> Querybuilder: add whereNull / whereNotNull

.github/workflows/tests.yml, src/Fields/Value.php, tests/Data/AugmentedCollectionTest.php
Closes #4720
I've updated the GitHub test suite workflow to include 8.1, as well as a little general cleanup.
- Mockery min versions are required in a separate step rather than cramming into 'additional-deps'.
- Testbench can rely on the regular composer constraint, except for L8/P8.1 which needs a specific min version installed in a separate step.
- Adjusted laravel/framework constraint to match what's in composer.json. We've updated composer.json a couple of times but never matched it in the test suite. It would be nice if we could just read from composer.json, but I don't think that's possible without a custom action.
- Removed composer's deprecated no-suggest option.
- Renamed laravel-constraint to framework, and dependency-version to stability.
Everything passed without needing to …
=> PHP 8.1 Support

config/git.php
After trying to find the docs when inspecting the git config, I think the correct links make sense :)
=> Fix and improve paths to git documentation

src/Forms/Email.php, tests/Forms/EmailTest.php
Hi
We are using forms for sending emails. For emails the site's short locale will be used for translations. As we live in Switzerland we need to use de_CH (mainly because Germany has this ß character when needing ss, but only sometimes. I do not now the exact grammer here. I only know we don't have this on our "German"-Language variant).
So I think for emails the full locale should be used.
This can be a breaking change, since other swiss devs could used this and after this PR is merged, the locale will no longer be found (as de_CH will be used instead of de).
What do you think @jasonvarga?
=> Use full locale for emails

src/Providers/AddonServiceProvider.php
When it's in a `booted` closure it's actually called twice. Since this method is already in a `Statamic::booted` closure we don't need it here.
=> Schedule doesn't need to be in `booted`

src/Modifiers/CoreModifiers.php, tests/Modifiers/TrackableEmbedUrlTest.php
We have a client who would like to gather analytics on their video links (I know I know), but the `embed_url` always adds do not tracking.
=> add `trackable_embed_url`

resources/lang/en/messages.php, resources/views/partials/licensing-alerts.blade.php, src/Licensing/LicenseManager.php, src/Licensing/StatamicLicense.php, tests/Licensing/LicenseManagerTest.php, tests/Licensing/StatamicLicenseTest.php
Right now if your license's support window has ended, it'll just tell you it's invalid. This makes the messaging a little more user friendly.
=> Adjust licensing messaging

src/Fields/Blueprint.php
I need to get a blueprint's parent for an addon I'm working on. Can we please add this tiny little method?
=> Add method to get Blueprint parent

resources/sass/elements/forms.scss
=> Links shouldn't be red. That was dumb.

src/Fields/Fieldtype.php, tests/MiscTest.php
Fixes #4889
Fixes #4839
This PR adds some test coverage for the weird bugs.
The multi-day investigation ended up having a 6 character fix, because of course it did.
The incorrect caching as pointed out in #4890 should still probably be sorted out, but we can come back to that.
=> Fix fieldtype field parent caching

src/Tags/Increment.php, tests/Tags/IncrementTest.php
This PR adds a new `increment:reset` tag that enables developers to reset an incrementing value. This is useful when using the `increment` tag within partials, or when iterating any list where the `increment` value is being used to generate CSS class-names (such as z-index).
Anyone who is currently using `reset` as an incrementing counter name would need to rename `{{ increment:reset }}` to something else. Due to issues with tag pairing while testing, the decision was made not to use a "reset" parameter.
The `increment:reset` tag accepts the following parameters:
* `counter`: The name of the increment variable to reset. Required.
* `to`: A value to reset the counter to. Not required.
```html
{{ data }}
Reset the counter, so everything starts over at 0 for each iteration of data.
{{ …
```
=> Add increment:reset tag

resources/js/components/field-validation/Rules.js
This PR adds an `ends_with` validation rule, that is an accompanying rule for already existing `starts_with`. `ends_with` was introduced in Laravel v5.8.17 (https://github.com/laravel/framework/releases/tag/v5.8.17).
=> Add ends_with validation rule

src/Console/Commands/StaticWarm.php
Tiny change, it allows you to configure the amount of concurrent requests when warming the static cache in your strategy. By default the guzzle pool will use `25`, so that's what I've set as the default as well to remain backwards compatible.
i.e.
```php
'strategies' => [
'full' => [
'driver' => 'file',
'path' => public_path('static'),
'lock_hold_length' => 0,
'warm_concurrency' => 10,
],
],
```
**Edit**: tpyo
=> Allow configuring of the pool concurrency when warming the static cache

src/Modifiers/CoreModifiers.php, tests/Modifiers/CompactTest.php
This PR introduces a new `compact` modifier that accepts a list of comma-delimited variable names as input, resolves their values, and then returns a new array containing the requested values.
The `compact` modifier would accept a `string` as its input, which should be a comma-delimited list of variable names. The return value of this modifier can be used anywhere arrays are accepted:
```
---
var_one: 'Value One'
var_two: 'Value Two'
var_three: 'Value Three'
---
{{ foreach :array="'view:var_one, view:var_two, view:var_three'|compact" }}
{{ value }}
{{ /foreach }}
```
would produce the following output:
```
Value One
Value Two
Value Three
```
Attached is an entry that can be used as a starting point for the Docs site
[compact.md](https://github.com/statamic/cms/files/7741353/compact.md)
=> Adds a compact modifier to convert a list of variables to an array

resources/js/components/fieldtypes/replicator/Replicator.vue
Closes #4774.
I'm basically undoing what we did in https://github.com/statamic/cms/commit/323234748145e1ad4330499fdb66ca182d8cea64 to fix https://github.com/statamic/cms/issues/564 way back in the v3-beta days. That said, I can't reproduce either issue with this fix, so I think it's fine?
Also noteworthy is that we're splicing `this.values` directly in `removed()`, so I think we should be fine splicing `this.values` directly in `updated()`.
=> Fix replicator updated logic

src/View/View.php, tests/View/Antlers/BladeLayoutTest.php, tests/View/Antlers/fixtures/blade_injection.antlers.html, tests/View/Antlers/fixtures/blade_layout.blade.php
This PR corrects an issue where `{{ noparse }}` extractions were not being replaced in the rendered output when extending a Blade layout.
**Setup**
Data:
```yaml
title: 'The Title'
```
`layout.blade.php`
```blade
{!! $template_content !!}
```
Any Antlers template that extends `layout.blade.php`:
```
{{ title }}
{{ noparse }}
{{ title }}
{{ /noparse }}
```
Before, an Antlers template that included `{{ noparse }}` tags would produce output similar to this when extending a Blade layout:
```
The Title
noparse_167a28b913b93a01d90aa945a4cd7770
```
With this PR, the output would now be:
```
The Title
{{ title }}
```
=> Fix noparse extractions with non-Antlers layouts

src/Tags/Assets.php
For the asset field values the sort + limit was not being applied since the value was directly returned. Now it outputs the assets through the `output` method, which will make sure they get applied.
Fixes #4680
=> Use the output method so filter + sort gets applied on assets.

src/Entries/Entry.php, src/Entries/UpdateStructuredEntryOrder.php, src/Tags/Collection/Entries.php, tests/Data/Entries/EntryTest.php, tests/Tags/Collection/EntriesTest.php
I didn't want to mess around with `Collection::orderable()` as it looks like being used a lot of places.
Since the order behind the scenes uses a flatmap of the structure IDs, I can't see why this shouldn't be included, as long as users understand that the order is done depth-first instead of breadth-first.
Thoughts?
=> Collections: Sort nested structure by order

src/Http/Controllers/CP/Assets/AssetContainersController.php, tests/Feature/AssetContainers/UpdateAssetContainerTest.php
Closes #4952
The field was there, but even if you edit it, it didn't update.
We don't really want you to change it, so to be consistent with editing a collection, I've just removed the field.
It's there when you're creating the container, though.
=> Don't show asset container handle when editing

src/Modifiers/CoreModifiers.php, tests/Modifiers/GroupByTest.php
Fixes #4898
If you target an object in the `group_by` modifier, it didn't know how to handle it.
Now if it enounters an object, it'll convert it to a string. (i.e. in the case of a `Blueprint`, it'll convert it to its handle.)
=> Allow `group_by` modifier to support stringable objects

resources/sass/elements/forms.scss
Browsers keep changing how they render checkboxes vertical position. This fixes em again.
=> Fix checkbox position

resources/js/components/fieldtypes/bard/Image.vue
Due to the way event propagation for child node inputs is handled in TipTap v1, pasting into Image alt field in Bard is broken (results in text pasted in main content flow). This has beed [changed in TipTap v2](https://github.com/ueberdosis/tiptap-next/commit/1a74bbb0fbb8949a3aa26b9ccebe4bd3808666af). This PR stops event propagation for Alt field, as [recommended](https://github.com/ueberdosis/tiptap/issues/1100#issuecomment-800432299) by TipTap author.
Fixes #4768.
=> Fix pasting into Bard image alt field

src/Tags/Concerns/OutputsItems.php
Allow a new optional param `on_each_side` which modifies the amount of links on each side of the slider when using `paginate="true"` and `limit="x"`
For reference, here is the link to the Laravel docs:
https://laravel.com/docs/8.x/pagination#adjusting-the-pagination-link-window
Closes statamic/ideas#710
=> Allow pagination slider window to be adjusted

src/Query/IteratorBuilder.php, tests/Search/QueryBuilderTest.php
This is just the specific bug mentioned in #4899 split into its own PR.
I called the method "items" to be more generic instead of "entries" which I assume is just a copy/paste from the entry query builder.
This query builder does not necessarily deal with entries.
Also, made the method private since it's only called internally, at least for now.
=> Fix intersection on iterator query builder

src/Forms/Uploaders/AssetsUploader.php
Fixes #4777. Uses the same logic now as the Assets fieldtype.
=> If you only have one asset container, use that as a default in form submissions

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/grid/StackedRow.vue
This fixes #3498 fully. It replaces the quick fix in #3518 with a proper fix. Grid uses the same Field component now as Replicator and Bard do.
Working on this I saw that when a Bard field is readonly, its sets were still editable. This PR fixes that too (separate commit).
=> Fix readonly fields in localizable grids

resources/js/components/entries/PublishForm.vue
Fixes #4685
Fixes #4985
References #4977
When changing sites, the fieldtypes would get populated with the new entry's values.
When any field updates their value, the form becomes dirty.
After the site is changed, we clear the dirty state.
The problem was that since we added debouncing, the dirty state got cleared and *then* the value was updated, making it dirty again.
This PR changes the nextTick to a simple timer a little longer than the debounce.
=> Fix unnecessary dirty state

src/View/View.php
The `template` method was treating a `null` argument as getter so you couldn't do `View::make()` without an argument.
Normally you'd do `View::make('foo')` but if you wanted to specify the template fluently (maybe because it's a long name and looked tidier) you couldn't. Now you can.
```php
View::make()
->template('foo/bar/baz/qux')
->with(['foo' => 'bar']);
```
=> Fix View methods

resources/js/components/field-validation/Rules.js, src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Assets/MaxRule.php, src/Fieldtypes/Assets/MinRule.php, src/Fieldtypes/Assets/SizeBasedRule.php, tests/Fieldtypes/AssetsTest.php
This fixes #4217 as requested. 
Careful though, this is a breaking change: before the `min` and `max` rules would validate the _number of assets_ and now they check the file size.
I'm thinking should we use custom names for these rules to differentiate between the two?
=> Add min and max file size validation rules for assets

src/Query/OrderBy.php, tests/Query/OrderByTest.php
This is to complement #4758.
Closes statamic/ideas#428
It will allow you to sort collection tags using a colon syntax.
```
{{ collection:blog sort="foo:bar:baz:desc" }}
```
This will sort by `foo->bar->baz` in descending order.
If the last segment is `asc` or `desc`, it'll assume that's the direction.
For anything else, it'll just assume it's part of the subfield path, and use `asc` for the direction.
As per #4758, you could continue to use the JSON arrows if you wanted.
```
sort="foo->bar->baz:desc"
```
=> OrderBy class can support subfields

src/Tags/Section.php, src/Tags/Yields.php
Typically, templates are injected into layouts through a `template_content` variable.
But if you use Blade for your template, this behavior doesn't happen. We do this intentionally to allow you to use `@extends` to manage your layout, which is a totally normal thing in the Laravel world. Then you use the `@section` directive in your template to capture it and `@yield` in your layout to output it. Like this:
```blade
@extends('layout')
@section('content')
<div>...</div>
@endsection
```
```blade
<html>
<body>
@yield('content')
</body>
</html>
```
That's fine if you plan to use Blade all over, and you want to use a Blade layout too.
But if you want a hybrid approach - a Blade template but an Antlers layout - you couldn't. We had a `yield` tag, but it only worked with a `section` tag in …
=> Support Blade section yields in Antlers layouts

src/Modifiers/Modify.php, src/Statamic.php, src/Tags/FluentTag.php, tests/Modifiers/FluentModifyTest.php, tests/StatamicTest.php, tests/Tags/FluentTagTest.php
Resurrecting a version of the work done by @riasvdv in #2724 and #2717 (🎉) to bring antlers support to blade via convenient wrappers.
We don't want to pollute the global namespace, but as a `Statamic::` accessible function, we're thinking it would be nice to bring this kind of antlers support to blade.
The nice thing about Rias' approach here is that it'll allow the user to work with / loop over the output however they want in blade (ie. `@foreach`, `@forelse`, pass data into an `@include`, etc) 👍 
```blade
{{-- // Loop over results however you want in blade --}}
@foreach(Statamic::tag('collection:pages') as $page)
{{ $page['title'] }}<br>
@endforeach
{{-- // Fluently add tag params --}}
@foreach(Statamic::tag('collection:pages')->sort('date:desc')->limit(3) as $page)
{{ $page['title'] …
```
=> Antlers wrapper for blade

src/Console/Commands/StaticWarm.php
New features:
1. Visit taxonomy URLs too
2. Skip taxonomies and terms that have no template
3. Add multisite support for taxonomies and terms
4. Show the number of URLs that will be visited
5. Skip URLs in the `'exclude'` list
Fixes #4468, see feature 2.
Fixes #4732, see feature 5 and 2.
=> `static:warm` command updates

src/Assets/Asset.php, src/Auth/User.php, src/Data/HasAugmentedInstance.php, src/Entries/Entry.php, src/Forms/Form.php, src/Query/Builder.php, src/Stache/Query/Builder.php, src/Structures/Page.php, src/Tags/Collection/Entries.php, src/Tags/Concerns/GetsQuerySelectKeys.php, src/Tags/Locales.php, src/Tags/Structure.php, src/Taxonomies/LocalizedTerm.php
This PR is inspired by #4924 and #4926. Thanks @FrittenKeeZ !
Related to statamic/ideas#543
This adds a `select` parameter to some tags that use augmentation. (`nav`, `locales`, and `collection`)
It allows you to pick specific fields to be augmented if you want to improve performance. By default, all fields are augmented, even if you don't end up using them.
```
{{ nav select="title|foo" }}
```
You may also use the `@shallow` placeholder which will expand into the appropriate set of fields.
```
{{ nav select="@shallow|foo" }}
```
e.g. for entries, you'd get `id`, `title`, `url`, `permalink`, `api_url`, plus `foo`.
This also adds the `select()` method to the query builder for selecting columns.
```php
Entry::query()->select(['foo', 'bar'])->get()->toAugmentedArray();
// select foo,bar from …
```
=> Add ability to select fields in tags

src/Modifiers/Modify.php, src/Structures/Page.php
This removes a few deprecation warnings/logs on PHP 8.1
=> Attributes to remove deprecation warnings

composer.json
Composer v2.2 added a new requirement to explicitly allow plugins that can execute code during a Composer run. This addition is the result of answering "yes" to the list of given plugins during a composer install of `statamic/cms`.
See:
- https://github.com/composer/composer/pull/10314
- https://blog.packagist.com/composer-2-2/
=> Add allowed composer plugins

.github/workflows/tests.yml
It's recommended to use npm ci, as the usage of `install` can lead to failures.
https://dev.to/visuellverstehen/why-to-use-npm-ci-instead-of-npm-install-mfd
=> Use npm ci instead

resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/hu.json, resources/lang/id.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/sv.json, resources/lang/zh_TW.json, src/Actions/Delete.php, src/Http/Controllers/CP/Collections/EntriesController.php
Not used $collection removed from EntiesController's destroy function. 
Duplicate texts are removed from delete methods.
=> Fix delete confirmation translations, and remove unused method.

src/Http/Controllers/GlideController.php
In debugging an error in glide, I had to add some logging to code in production.
Would be nice to have this all the time, when there are errors.
This also prevents huge call stacks filling up the log as we only log what's relevant.
Fixes #3760
=> 404 on Glide asset urls when there's an invalid container

src/Stache/Query/Builder.php, src/Stache/Query/UserQueryBuilder.php
Fixes #5078
A new abstract method snuck into the query builder in PR #4754 which was fine for us because we implemented it everywhere, but developers who had their own classes would get an error.
The implementation in the users query builder is generic enough that I moved that to the parent class.
=> Fix abstract query builder method

src/Support/Str.php
This copies `Illuminate\Support\Str::studly` into our class verbatim except for using `str_replace()` method explicitly.
We have this weird conflict between Str and Stringy.
In v4 we'll likely make our Str class not inherit from anywhere, and not do the Stringy fallbacks.
Fixes #5126
The actual bug was that we call `Str::camel()`, which calls `Str::studly()`, which calls the problematic `Str::replace()`.
=> Add Str::studly

src/Auth/Eloquent/UserQueryBuilder.php, src/Query/EloquentQueryBuilder.php, src/Tags/Collection/Entries.php
Our Eloquent Query builder always ends up dealing with Statamic objects, which need all the columns.
When you use the new `select` param in the `collection` tag, or if you were to do `$query->select(...)`, your DB query may be faster from not selecting everything, but the objects wouldn't get hydrated correctly since they're expecting all the column values.
This PR will track the selected columns and pass them along to the eventual objects (Users, Entries, etc) so that when they're augmented, you'll only get the keys you asked for, which is a performance benefit.
I also made the `select` param on the collection tag not modify the query at all if you don't pass anything.
Fixes #5108
=> Fix Eloquent query builder selects

resources/js/components/fields/FieldtypeSelector.vue
This suffixes fields names like `assets`, `date` and `link` so they become `assets_field`, `date_field` and `link_field` to avoid problems like #3687.
=> Suffix tricky field names in Blueprint and Fieldset builders

resources/js/components/assets/Editor/Editor.vue, resources/js/components/data-list/HasHiddenFields.js, resources/js/components/entries/PublishForm.vue, resources/js/components/field-conditions/ValidatorMixin.js, resources/js/components/field-validation/Rules.js, resources/js/components/globals/PublishForm.vue, resources/js/components/publish/Container.vue, resources/js/components/terms/PublishForm.vue, resources/js/components/users/PublishForm.vue, src/Fields/Field.php, src/Fields/Fields.php, src/Fields/MissingValue.php, src/Http/Controllers/FormController.php, tests/Fields/FieldsTest.php
Closes https://github.com/statamic/cms/issues/5092.
- We can revisit this in another PR after @arthurperton finishes his grid/replicator/bard validation related fixes 👍
=> Track and handle hidden fields on publish forms to fix `sometimes`, `required_if`, etc. rules

resources/js/components/fieldtypes/replicator/Set.vue
Fixes #5081.
All the preview texts of the fields in a set get generated simultaneously on load in `Fieldtype.vue`. Somehow that caused `meta.previews` to still contain the old data in the components when updating. Maybe because action dispatching is asynchronous, but I'm not sure here. This simple solution fixes it though.
=> Fix replicator preview text generation

src/Support/Str.php, tests/Modifiers/WidontTest.php
- Don't replace new line characters in between mismatched tags (such as Nested Lists). HTML will handle this natively, as widont is meant for orphans within text only. It does not need to be a non-breaking space.
- Add another regex to handle nested list content, before a nested list, not being "widonted". This is due to the existing widont code only matching on matching (i.e. li) tags.
I tried to add the second part to the existing step 2 but my regex skills weren't good enough to figure out how to do that. 
Fixes #5040
=> Nested lists now handled correctly by widont

src/Http/Controllers/CP/Fields/FieldsetController.php, src/Http/Controllers/CP/Fields/ManagesBlueprints.php, tests/Feature/Collections/Blueprints/UpdateBlueprintTest.php, tests/Feature/Fieldsets/UpdateFieldsetTest.php, tests/Feature/Taxonomies/Blueprints/UpdateBlueprintTest.php
Closes statamic/ideas#716 which in the ideas repo but I'd argue is a bug.
Replaces #5114 and #5097
cc @jacksleight
=> Extra blueprint/fieldset contents stay when saving in the CP

src/Fields/Field.php, src/Fields/Fieldtype.php, src/Fields/Validator.php, src/Fieldtypes/Bard.php, src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php, tests/Fields/ValidatorTest.php
This also fixes #1702. I somehow overlooked #1703 and created this solution. It's nice and short, but doesn't display the field names nicely in the errors (yet):
Edit from Jason:
The field names totally work now too.
=> Replace {this} in field validation rules

src/Fieldtypes/Color.php
As seen in the screenshot, in the "Default Color Mode" the term "HEXA" is used, while the "Color Modes" uses "HEX". This PR changes "HEX" to "HEXA" to have some consistency. 
**Question:** `HEXA` is very unusual to refer to hexadecimal color code system. Was it introduced to use the same term like the user can see in the color picker?
=> Set the color mode default correctly

CHANGELOG.md, src/Auth/RoleRepository.php
We noticed some small speed problems if a user had multiple roles. This graph shows two identical server instances with identical data sets. They only differ by using the Blink cache. 
The test case shows a user with 6 roles in total. The request would take even longer with more roles attached.
This PR would speed up the overall cp speed, as the roles will be fetched in most requests. Our example uses the dashboard, but the article listing shows nearly identical values.
Originally authored by @jojotl
=> Cache user roles

src/Forms/JsDrivers/AbstractJsDriver.php, src/Forms/JsDrivers/Alpine.php, tests/Tags/Form/FormCreateAlpineTest.php, tests/Tags/Form/FormCreateCustomDriverTest.php
=> Refactor JSON encoding for form attributes in JS drivers

tests/Modifiers/GroupByTest.php
This test fails on the 31st day of the month. When we set `setMonth(9)` (September), it only has 30 days, so it ends up being October 1st.
This changes to a more explicit date.
=> Adjust test for 31-day months

src/Http/Controllers/CP/Fields/FieldsController.php
The word `type` is way too common to be reserved.
It should only be reseved within a Replicator or Bard set.
Reverts #5088
Reopens #5087
=> Revert type being a reserved word

src/Search/Comb/Comb.php
The exception `Exception` is aliased as `CombException`.
=> Fix exception usage in Comb

.gitattributes, .github/workflows/tests.yml, tests/Modifiers/WidontTest.php, tests/WindowsHelpers.php
This adds a Windows test to the test matrix.
We're okay with just one - the latest windows. No need to double the entire suite.
I changed `ubuntu-20.04` to `ubuntu-latest` because the latest is ubuntu-20.04 now anyway, and then we don't need to change the required branch checks which is a pain for existing PRs.
This PR also changes the line ending rule that we added to `.gitattributes` in #4843.
Turns out it caused sporadic StyleCI issues [(example)](https://github.styleci.io/analyses/orPvkg) because when you clone the repo, images/etc would have their line endings changed and you'd end up with those files marked as modified [(example)](#5207).
We only need PHP files to have their line endings enforced.
This also skips the test added in #5115. It's the only one that fails. We can sort …
=> Windows, Line endings, etc

CHANGELOG.md, src/Fieldtypes/Entries.php, src/GraphQL/ResolvesValues.php, src/View/Antlers/Parser.php, tests/Fieldtypes/EntriesTest.php, tests/View/Antlers/ParserTest.php
Extracted from #5201
The `entries` fieldtype previously augmented to an `EntryCollection` of `Entry` objects.
Now, it'll augment to a query builder so you can continue to chain onto it and further refine your query.
This PR helps allow better fluent templating in Blade. See #5201.
```blade
@foreach ($entry->related_entries()->limit(3)->orderBy('title')->where('featured', true)->get() as $related)
{{ $related->title }}
@endforeach
```
This PR makes Antlers handle query builders in more places. You can call the same methods that you would use on a `collection` tag.
```
{{ related_posts limit="3" sort="title" featured:is="true" }}
<li>{{ title }}</li>
{{ /related_posts }}
```
Unlike Blade or raw PHP, you don't have to call `->get()` on the query. Antlers will know you intend to loop over the …
=> Entries fieldtype augments to a query builder

.github/workflows/tests.yml
Basically #5229 but straight to `master` so we can avoid testing extra versions until #5188 is merged.
=> Remove PHP and Laravel versions from test suite

src/Fields/Validator.php, src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php, tests/Fields/ValidatorTest.php
See title. Especially handy if you want to reuse fields or fieldsets at top level as well as nested in meta fields.
=> Discard `{this}.` at top level

resources/sass/components/configure.scss
Fixes #5091 
* This ensures that pushing the toggles to the right in `configure-sections` only applies to top level fields, and not to toggles in grids etc.
* Also fixes vertical alignment for toggles that are pushed to the right.
=> Fix toggle fieldtype alignment issues in config panels

resources/js/app.js, webpack.mix.js
Fixes #5181
Replaces #5279
Honestly I don't understand it. Seems like something changed in how underscore.js modules worked when we upgraded.
But this makes everything work again.
=> Fix Underscore.js OOP syntax

src/Modifiers/CoreModifiers.php
The method only accepts one parameter, remove the two unused parameters from call.
=> Remove unused parameters from call to `HTML::email()`

src/Fieldtypes/Entries.php, src/Fieldtypes/Relationship.php
Fixes an issue introduced in #5238. The preProcessIndex wasn't updated to handle query builders.
=> Fix entries fieldtype preProcessIndex

CHANGELOG.md, src/Providers/CollectionsServiceProvider.php, tests/Fields/ValuesCollectionTest.php
This reverts #5286.
It's basically rendered pointless by #5297.
=> Revert "Add toValuesCollection macro"

src/Tags/FluentTag.php, tests/Tags/FluentTagTest.php
```php
FluentTag::make($usedTag)
->sort('slug:desc')  // dynamically call params via methods
->param('title:contains', 'chewy') // explicitly set param, with colon for example
->params(...); // or set multiple params at once
```
=> Add param() and params() setters to FluentTag

resources/sass/components/fieldtypes/bard.scss
Fixes a css issue with lists in the Bard field type.
With current css
With updated css
=> Fixes nested lists css to display correct list style

src/Forms/Submission.php, tests/Forms/SubmissionTest.php
- Remove the has/get/set/data methods so they delegate to ContainsData which does the same thing.
- The data method will always return a collection.
- The data method used to filter out fields that weren't in the blueprint. This was a leftover thing from v2 before we moved to v3 style validation. Now it won't do any filtering.
This goes along with #5297 but moving into its own PR to avoid noise there.
=> Adjust Form Submission data logic

src/Assets/Asset.php, src/Assets/AssetContainer.php, src/Auth/Role.php, src/Auth/User.php, src/Auth/UserGroup.php, src/Data/HasAugmentedInstance.php, src/Entries/Collection.php, src/Entries/Entry.php, src/Fields/Blueprint.php, src/Globals/Variables.php, src/Structures/Page.php, src/Taxonomies/LocalizedTerm.php, src/Taxonomies/Taxonomy.php, tests/Assets/AssetContainerTest.php, tests/Assets/AssetTest.php, tests/Auth/RoleTest.php, tests/Auth/UserContractTests.php, tests/Auth/UserGroupTest.php, tests/Data/Entries/CollectionTest.php, tests/Data/Entries/EntryTest.php, tests/Data/Globals/VariablesTest.php, tests/Data/Structures/PageTest.php, tests/Data/Taxonomies/LocalizedTermTest.php, tests/Data/Taxonomies/TaxonomyTest.php, tests/Fields/BlueprintTest.php
Adds ArrayAccess to augmentable items, to go along with #5297.
Now you can do `$entry['field']` which will have the identical result as `$entry->field`.
=> ArrayAccess

src/GraphQL/Queries/Concerns/FiltersQuery.php, src/GraphQL/Queries/EntriesQuery.php, src/GraphQL/Queries/EntryQuery.php, tests/Feature/GraphQL/EntryTest.php
This PR implement the same filter capability and default behavior you implemented in #3349 for the `entry` query.
If you filter on status or published, the default behavior goes away and does whatever you've asked for instead.
I didn't write any tests yet. I'll be happy to add those if you're happy with the PR.
=> Filter published entry in GraphQL

src/Data/HasAugmentedInstance.php, tests/Data/HasAugmentedInstanceTest.php
I didn't add this in #5327 but it's needed.
When you call `Arr::exists()` on an ArrayAccess, it'll call `offsetExists`. This was happening in some places that weren't covered by tests.
=> Implement offsetExists

.github/workflows/release.yml, composer.json
Fixes the resources directory getting wiped out when the dist folder was copied over.
Use two separate zips instead - the composer plugin supports that.
Change introduced in #4949
=> Use multiple zips

src/GraphQL/Types/GridItemType.php, src/GraphQL/Types/ReplicatorSetType.php, tests/Feature/GraphQL/Fieldtypes/GridFieldtypeTest.php, tests/Feature/GraphQL/Fieldtypes/ReplicatorFieldtypeTest.php
Fixes #5366
Fixes fieldtypes that return query builders (e.g. `entries`) when nested in Grid or Replicators.
=> Fix querying nested entries fields in GraphQL

resources/sass/components/fieldtypes/datetime.scss, resources/sass/components/fieldtypes/grid.scss
Fixes #5073 (the time field) and also fixes the handle and row control columns that were too wide.
**before:**
**after:**
=> Grid table UI tweaks

src/Assets/Asset.php, src/Assets/AugmentedAsset.php
The duration of audio and video files is currently added to the meta data but can't be received in antlers.
This PR adds duration (in seconds and minutes) to the `AugmentedAsset` class.
Hope this is fine. At least it's a starting point.
Sorry I need help with tests :-(
=> Add duration to augmented asset

src/Modifiers/CoreModifiers.php
The `reverse` modifier accepts strings, arrays and since this [PR](https://github.com/statamic/cms/pull/4003/files) also Collections. When reversing an array the modifier uses the PHP function `array_reverse()` where the flag `preserve_keys` is set to `false` by default and the modifier does not overwrite it. When adding support for Collections, it is just calling `->reverse()` on the Collection, but the method sets `preserve_keys` to `true`. This results in two different reversed arrays from the same modifier:
```php
Array
(
[0] => party
[1] => eat
[2] => service
[3] => photos
)
```
```php
Array
(
[3] => party
[2] => eat
[1] => service
[0] => photos
)
```
This PR changes this by calling `values()` on the reversed Collection, which resets the keys of the underlying array.
=> Consolidate `preserveKeys` settings for `reverse` modifier

src/Structures/Tree.php
When working with the Eloquent driver with incrementing ids, adding a new nav on a structured collection was always adding it at the end of the nav, even if you chose a parent entry.
After some digging the cause was the strict equivalent check in the amended file.
While working on it I also noticed the blink cache was not updating when the tree is updated as it referenced the getter $tree instead of $this->tree.
=> Fix issues with collection trees in eloquent driver

src/Forms/Email.php
Fixes #5360
This PR will reindex the collection so it'll work across parsers.
---
Turns out the old parser allowed looping over non-numerically-indexed collections, but only if they were a collection. Arrays didn't work. We never documented it as working though.
Numerically-indexed array:
```yaml
field:
- # technically 0
title: Alfa
- # technically 1
title: Bravo
```
```
{{ field }} {{ title }} {{ /field }} // Works fine. Outputs: Alfa Bravo
```
Non-numerically indexed
```yaml
field:
foo:
title: Alfa
bar:
title: Bravo
```
```
{{ field }} {{ title }} {{ /field }} // This shouldn't work, but was, but only if it was a collection.
```
I don't consider this a parser bug since it's an undocumented case.
=> Fix email fields not being loopable

src/StarterKits/Installer.php
Trying to add better github auth error handling to statamic/cli so that the starter kit installation doesn't get this far. However, it is still possible to bypass the CLI tool with `php please starter-kit:install`, so this just improves the composer error output...
References https://github.com/statamic/cli/issues/43
=> Improve messaging around github auth errors.

src/Console/Commands/StarterKitInstall.php
Detect and add temporary prompt to inform user of updated CLI tool. The newest version has better messaging around paid starter kit licenses, so we want to push users to upgrade to minimize support requests around expired licenses. The newer version of the CLI tool will also notify the user of older CLI tool versions going forward, so we can revert this PR later.
=> Add temporary notification of CLI tool update

src/Fieldtypes/Entries.php, src/Query/OrderedQueryBuilder.php, tests/Fieldtypes/EntriesTest.php, tests/Query/OrderedQueryBuilderTest.php
This fixes the issue where the new entries query builder augmentation (#5238) wouldn't maintain the order you picked.
i.e. In the control panel you intentionally pick entries in a specific order, and it wouldn't output them in that order. Now it will.
Adds an "ordered" query builder decorator.
It wraps up a query builder with a custom order. If you don't call `orderBy` on it, it'll apply the custom order when retrieving the items.
---
In database-land, you could do a raw orderby query, like this:
```php
->whereIn('id', [4, 2, 5])
->orderByRaw("FIELD(id, 4, 2, 5)")
```
...but we don't support that, and it would be way more effort to do it than this decorator class.
=> Ordered Query Builder

composer.json, resources/views/partials/nav-main.blade.php, resources/views/partials/nav-mobile.blade.php, src/CP/Utilities/CoreUtilities.php, src/Statamic.php, src/namespaced_helpers.php
This is a proof of concept attempt at solving the issue where if you create a translation file named the same as a string, you get an array and the site explodes.
- Fixes #2341
- Fixes #4852
- Supersedes #5139
The more ideal solution would be for Laravel to only return strings through the `__` or `trans` methods, but it looks like that's not going to happen:
- laravel/framework#30690
- laravel/framework#30666
- laravel/framework#26664
It's happening in other packages too:
- kontenta/kontour#178
So here I'm creating our own version of `trans` that will throw away the translation if it was an array.
We can import the namespaced function wherever we use `__` so we can avoid updating `__()` to `Statamic::trans()` in a million places.
=> Namespaced translation methods

src/View/Antlers/Language/Parser/DocumentParser.php, src/View/Antlers/Language/Runtime/RuntimeParser.php, src/View/Antlers/Language/Runtime/Sandbox/Environment.php, tests/Antlers/Parser/StringsTest.php, tests/Antlers/Runtime/ParametersTest.php
This PR adds support for escaping `{` and `}` inside tag parameters and string literals to the Runtime parser by prefixing each occurrence with `@` when inside parameters or strings (to prevent the interpolation parser from seeing them as interpolations)
=> Allow escaped braces inside tag parameters and string literals

resources/js/components/updater/Release.vue, resources/js/components/updater/Updater.vue, src/Updater/CoreChangelog.php
This PR will disable the upgrade button in the Control Panel if you're trying to upgrade to a potentially breaking version.
For example:
- Going from 3.2.x to 3.2.x is fine.
- Going from 3.2.x to 3.3.x (or 4.x) will require some manual or breaking changes, so want to prevent you from just clicking the button and maybe breaking stuff.
If there are actual Composer issues, Composer will stop the update anyway. (e.g. upgrading a Statamic 3.2 site on Laravel 7 to 3.3 won't let you because it requires Laravel 8)
This PR just prevents you from getting as far as the Composer error.
--- 
When Statamic 4 is released, we'll start using semantic versioning, so these rules will need to change.
- Going from 3.2.x to 3.2.x will be fine.
- Going from 3.x to 3.x will be fine.
- Going from 3.x to 4.x will …
=> Prevent upgrading beyond a patch number

resources/js/components/entries/PublishForm.vue, resources/js/components/terms/PublishForm.vue
Fixes an error when trying to open an inline publish form.
This property is what's causing the error and was refactored out but never removed.
=> Remove unused live preview property

src/Tags/Route.php
Fixes: #5348 
Allows route tags in the form `{{ route name="xxx" }}`
=> Add index method to route tag

src/StarterKits/Installer.php
Could only reproduce this once, normally it gives different output...
By adding 'authenticate' to the composer output handling, we can show the nicer error when this happens for whatever reason.
=> Fix rare github auth error output

src/View/Antlers/Language/Parser/DocumentParser.php, src/View/Antlers/Language/Runtime/RuntimeParser.php, tests/Antlers/Parser/BasicNodeTest.php, tests/Antlers/Parser/CommentsTest.php, tests/Antlers/Runtime/StacksTest.php, tests/__fixtures__/views/partials/_stacksections.antlers.html
This PR closes #5425 and closes #5422 by ensuring that sections and stack content is only replaced at the very end of the current parser life-cycle.
Previously section & stack content would attempt to be evaluated too early, causing the no content issue for sections, and the array index error for stacks (since the internal list would be cleared too soon).
This PR also closes #5430 by trimming whitespace after a comment, if it is the first item in the template. Other whitespace has been left alone to not accidentally remove intentional whitespace.
=> Antlers Runtime Bugfixes

composer.json
We use the Commonmark parser's `convert()` method (introduced in 2.2), rather than the old `convertToHtml()` method (which is deprecated).
For context, this was causing failure in SEO Pro tests with prefer-lowest flag, but we're actually calling/using the package here in core.
References https://github.com/statamic/cms/pull/5188
References https://github.com/statamic/seo-pro/pull/204
=> Up minimum commonmark version

src/Assets/AssetContainer.php, src/Assets/AssetFolder.php, tests/Assets/AssetContainerTest.php
Fixes #5405
Part of the folder moving process is to delete the old folder.
Part of that is to delete all the assets inside it.
This is a two parter:
**One**
When the folder was attempting to find the assets inside it, since it was named just `"0"`, it was failing a strict comparison and acted as though there was no folder filter - resulting in _all_ assets being queried and then deleted.
This PR makes the folder check strict, and allows a folder named `"0"`.
**Two**
When we do a recursive asset lookup, it was doing "find assets where the asset's folder starts with this folder".
When there were assets in another folder that _started the same_ as your folder, it would pick those up too.
In #5405's case - it would be looking for assets in `2022/0` - which would include assets from `2022/01`, …
=> Fix a few asset issues

src/Tags/Collection/Entries.php, tests/Tags/Collection/EntriesTest.php
In 3.2, passing a terms field into the taxonomy parameter worked because it would be a collection of Term objects.
In 3.3, it would be a Query Builder instance instead of a collection of Terms. This PR will get the query results if it detects a Query Builder.
Fixes #5431
=> Allow a terms fieldtype value to be passed into the taxonomy param

src/View/Debugbar/AddVariables.php
In the event that Debugbar is enabled and Statamic\View\View::make is used multiple times on a single page, an exception for DebugBar\DebugBarException 'Variables' is already a registered collector, will be thrown.
This aims to only register the Variables collector once for the page load/request.
This allows Statamic\View\View to be used multiple times, and will automatically pass the cascade data onto the views.
An example of how I had previously tried to use this can be see here: https://github.com/HandmadeWeb/buildamic/blob/e114f52411b136aec3e8620ba1359dbe29462f44/src/BuildamicRenderer.php (sections render rows, which render columns etc...) but this resulted in the exception to be thrown, I had since reverted those changes in https://github.com/HandmadeWeb/buildamic/commit/82628d18080fa …
=> Register Variables debugbar collector, only if it has not already been registered

src/View/Antlers/Engine.php, tests/View/Antlers/ParserTests.php
The regex parser will now handle them.
The runtime parser already does.
Fixes #5459
=> Regex parser can handle when tags return query builders

src/Modifiers/CoreModifiers.php, tests/Modifiers/PluckTest.php
Fixes #5460
Lets the pluck modifier support ArrayAccess items, like `Values`, which is returned from Replicators/Grids/Bards.
=> Pluck modifier supports ArrayAccess types

src/Fields/Values.php, src/Modifiers/Modify.php, tests/Fields/ValuesTest.php, tests/Modifiers/FluentModifyTest.php
Since #5436, a Replicator/Bard set or Grid row would now be a Values instance and no longer an array.
We were fine with that being a breaking change, but we can avoid it from breaking _too_ much.
If you were to use certain array modifiers on them, what would previously work will no longer work because they'd have `is_array` checks in there. e.g. `contains`, `in_array`, `is_array`, etc
This PR will convert `Values` instances to their underlying arrays before running each modifier so it behaves exactly like it did before.
For cases where a _nested_ item is a `Values` instance, we'll still need to manually handle it. See #5462 for an example.
=> Modifiers convert Values objects to arrays

composer.json, src/Assets/ExtractInfo.php, tests/Assets/ExtractInfoTest.php
=> Fix `ExtractInfo` size call between Laravel 8 and 9

src/Fieldtypes/Terms.php, tests/Fieldtypes/TermsTest.php
Fixes #5472
When you have a `terms` field named the same as a taxonomy, there's some extra features that go along with it.
One of which is that it'll filter out any terms that aren't used in that entry's collection.
This should only happen for top level fields. If you have a field in a grid/replicator, it should leave it be.
=> Fix terms being filtered out unintentionally

src/Tokens/Handlers/LivePreview.php, tests/Tokens/Handlers/LivePreviewTest.php
Fixes #5484
If this header is in the request, drafts will load. The logic and tests were already there, but during #5109 the header on the request dropped off. This PR brings it back and tests that the handlers adds it.
=> Set header on live preview request so drafts are viewable

composer.json, resources/js/components/Slugify.vue, resources/js/components/fieldtypes/SlugFieldtype.vue, resources/js/plugins/slugify.js, src/Http/View/Composers/JavascriptComposer.php, src/Routing/Routable.php, tests/Data/Entries/EntryTest.php, tests/Routing/UrlBuilderTest.php, tests/Tags/ParentTest.php, tests/Validation/UniqueEntryValueTest.php
Replaces #5291
Fixes #2631
- The `$slugify` plugin accepts a `lang`, and will fall back to the selected site, and then the default site.
- The `<slugify>` component can accept a `language` prop.
- The `<slug>` fieldtype gets the language of the entry being edited from the store.
- The Entry's `slug()` method will use its sites locale.
- Update tests now to include locales now that the slug method looks for the site.
=> Slug languages

src/Modifiers/CoreModifiers.php, tests/Modifiers/WhereTest.php
Since #5477 "fixes" the inconsistency with how modifier parameters work (#3614), I'm sure plenty of people using the `where` modifier as documented will run into an issue.
This PR lets the `where` modifier continue to work if you use the colon syntax:
```
{{ myarray where="foo:bar" }}
...
{{ /myarray }}
```
Technically that's a single argument of `"foo:bar"` which we'll just split.
If you do it the "right" way (`where="foo|bar"`) it'll be considered two arguments (`"foo"` and `"bar"`) and work fine too.
Tip: you can use the new modifier syntax to avoid all the confusion entirely:
```
{{ myarray | where('foo', 'bar') }}
...
{{ /myarray }}
```
=> Support colon syntax in where modifier

.github/workflows/tests.yml, composer.json, src/Imaging/GuzzleAdapter.php, src/Imaging/GuzzleAdapterV1.php, src/Imaging/ImageGenerator.php, src/Imaging/LegacyGuzzleAdapter.php, src/Providers/AppServiceProvider.php, tests/Imaging/ImageGeneratorTest.php
Fixes #5358
When using Glide to point to a non-asset there would be errors because there was still Flysystem v1 specific code.
A non-asset meaning either:
1. a relative path to somewhere in your `public` directory
2. an external URL
For the public directory stuff, we use Laravel's on-demand disks pointing to the public directory. This pushes the Flysystem-specific code off to Laravel, which already handles both versions. This method wasn't available when we supported Laravel 6/7.
For the external url stuff I've added Flysystem v3 compatible version of the Guzzle adapter. It doesn't do everything an adapter should do, but has enough for our use case.
=> Support Flysystem 3 with Glide

src/Tags/Glide.php
Fixes #5544
If you use the glide tag to loop over an assets field, it would be given a query builder now in 3.3. This PR just gets the results of the query before carrying on with the tag.
=> Glide tag pair can handle query builders

src/Filesystem/AbstractAdapter.php, src/Filesystem/FilesystemAdapter.php, src/Filesystem/FlysystemAdapter.php, tests/Filesystem/FilesystemAdapterTests.php
Previously you could use `null` as a path to represent the root of a filesystem disk (the disk, not the entire server).
I believe the original intention was to be able to support `$disk->exists()` to determine if a disk had been created or not. But this also let you explicitly pass `null` in, which you might do unintentionally. This PR prevents nulls being passed in. You can still use `"/"` if you want to target the root.
=> Prevent usage of nulls as filesystem paths

src/GraphQL/Queries/UsersQuery.php, src/Http/Controllers/API/UsersController.php, tests/API/APITest.php, tests/Feature/GraphQL/UsersTest.php
Prevents an opportunity to brute force a user's password hash. With request throttling (enabled by default) it would be a long process, but nevertheless, this prevents you from doing it.
=> Prevent filtering users by password hashes in the APIs

resources/js/components/fieldtypes/SlugFieldtype.vue
This is #5523 which fixes #5522 again, but on the 3.2 branch.
=> Fix error when determining slug language on non-entry forms

src/Query/Builder.php
This morning I was working on a "load more posts" functionality for a client using Livewire and an Entry Query. Everything seemed to work, other than the same page being loaded over and over again.
Here is what I was using inside of my Livewire component to fetch new posts at the click of a button:
```
public function loadPosts()
{
$posts = Entry::query()->where('collection', 'blog')->paginate(6, ['*'], $this->pageNumber);
$this->pageNumber += 1;
$this->hasMorePages = $posts->hasMorePages();
$this->posts->push(...$posts->items());
}
```
The problem with this code, is that there was no was to explicitly set the page number. Because I was fetching posts using a load more button, it would always load the first page of entries that matched the criteria instead of the next page as I'd …
=> Allow query builder to accept current page parameter

.github/workflows/tests.yml
Had a bit of trouble getting both of these to pass in migrator, and figured we could benefit from a bit more Windows testing in core as well...
=> Expand Windows testing

src/Forms/Tags.php, src/Tags/Concerns/RendersForms.php
This PR adds a `csrf` parameter to the form tag that defaults to `true`. When setting it to `false` the form tag won't add a hidden `_token` input field to the form. It looks like this:
```
{{ form:create :in="form:handle" csrf="false" }}
```
The reasoning for this is as follows. In Peak I used to do this to render forms that could be statically cached:
```js
// Get a token and set it.
this.$refs.form.querySelector('input[name="_token"]').value = await getToken()
// Post the form.
fetch(this.$refs.form.action, {
headers: {
'X-Requested-With' : 'XMLHttpRequest',
}
```
In Peak 4 I changed it to this:
```js
// Post the form.
fetch(this.$refs.form.action, {
headers: {
'X-Requested-With' : 'XMLHttpRequest',
'X-CSRF-Token' : await getToken()
}
```
Which is well, cleaner and less yucky. …
=> Add CSRF parameter to form tag

src/Facades/Endpoint/URL.php, tests/Facades/UrlTest.php
Fixes #5630
This PR fixes the `is_external` boolean incorrectly believing URLs starting with an anchor being external.
=> Fix is_external check for anchors

resources/js/components/fieldtypes/SlugFieldtype.vue
Fixes #5653
Similar to #5523 which handled when site was missing from the publish container, but this is for when there's no publish container at all.
=> Prevent slug error when used on forms without containers

resources/js/components/inputs/Textarea.vue
Closed: https://github.com/statamic/cms/issues/4700
With the fix the height of the textarea is also updated when the fieldtype is loaded
=> Update height of textarea on mount

resources/views/assets/containers/edit.blade.php, resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/collections/blueprints/create.blade.php, resources/views/forms/edit.blade.php, resources/views/partials/global-header.blade.php, resources/views/taxonomies/blueprints/create.blade.php, resources/views/updater/index.blade.php
Spaces the closing tags of a few blade echo's
=> Space blade echo's

resources/views/updater/index.blade.php, src/Extend/Addon.php, src/Http/Controllers/CP/Updater/UpdaterController.php, tests/Extend/AddonTest.php
- Sometimes the updates badge would show an update when comparing `1.2` with `1.2.0`, which should be equal.
- Before: ![image](https://user-images.githubusercontent.com/5187394/160492859-5e661862-be31-4546-8249-427376aa1c62.png)
- After: ![image](https://user-images.githubusercontent.com/5187394/160492984-f6b63bef-5a88-4244-8faf-49add2fb41ce.png)
=> Updater fixes

src/Http/Controllers/API/CollectionEntriesController.php, src/Http/Controllers/API/TaxonomyTermsController.php, tests/API/APITest.php
This adds the same missing or wrong collection check that was applied to the REST API entry lookup prior to https://github.com/statamic/cms/pull/5623. It currently throws a 500 on the unpublished check since `$entry` is `null`. With this change, we just apply the same checks as a non-REST API route and throw a 404 when the entry can't be found or the collection segment is wrong. I've also added a test to compliment the published/unpublished test and check against exists/doesn't exist entries.
=> Add 404 handling to entries/terms in REST API

src/GraphQL/Middleware/CacheResponse.php, tests/Feature/GraphQL/RequestCacheTest.php
=> Don't cache tokenized requests in GraphQL

resources/js/components/fieldtypes/DateFieldtype.vue
Fixes https://github.com/statamic/cms/issues/5681
Sets falsey date values as null rather than passing them through to setSingleDate (where it is ignored) or to setDateRange (where it creates a console error trying to access a property on a null).
=> Fix to allow a date fieldtype to be cleared.

src/Fields/ArrayableString.php
fixes #5718
Choose the attribute because `:mixed` is not compatible with php 7.4.
=> Add attribute to suppress deprecation notice

src/Stache/Stores/ContainerAssetsStore.php
I am thinking this is [a bug with flysystem](https://github.com/thephpleague/flysystem-aws-s3-v3/issues/291), but it doesn't hurt for us to filter out pathless `FileAttributes` responses here as well 👍 
Closes #5535.
=> Fix for flysystem returning pathless FileAttributes response

resources/js/components/terms/BaseCreateForm.vue, resources/views/terms/create.blade.php
Fixes slugification by the proper language when creating a term.
=> Create Term form: set initial value for `site` in Vue / VueX

src/Imaging/GlideServer.php
Fixes #5662
Passing a path into the Glide server factory will have Glide create a filesystem behind the scenes with the default visibility.
In Flysystem 1 the default visibility was public, but in Flysystem 3 the default is private, which is responsible for the bug.
Instead of passing a path, you can pass a Filesystem instance. That's what this PR is doing, and it's explicitly setting the visibility to public.
=> Fix Glide cache disk permissions

src/View/Antlers/Language/Parser/DocumentParser.php, tests/Antlers/ScratchTest.php
This PR closes #5703 by swapping the dynamic split/substr functions to their mb_ counterparts when fetching the next chunk of an Antlers region.
These dynamic functions are in place to prevent them from being used on the entire document, and shouldn't have been used to handle Antlers tag internal contents.
=> Runtime Parser: Uses mb_ functions when fetching DocumentParser chunks

src/View/Antlers/Language/Parser/DocumentParser.php, tests/Antlers/Parser/NodeParametersTest.php
Prevents trailing literal content from being removed if a parameter contains double braces:
```
<div>{{ tag param="{{ variable }}" }}</div>
```
will no longer remove the trailing `</div>`
=> Runtime: Prevents literal from being removed when using multiple nested double braces in a parameter

src/View/Antlers/Language/Parser/DocumentParser.php, tests/Antlers/Runtime/NoparseTest.php
This PR closes #5739 by having the DocumentParser specifically handle `{{ noparse }}`. When the DocumentParser encounters these regions, all further parsing is disabled until it finds the next `{{ /noparse }}`.
=> Runtime: Corrects noparse behavior

src/Modifiers/CoreModifiers.php, tests/Modifiers/LengthTest.php
When using the `length` modifier on a `Collection`, it would call `toArray()` on it, causing each item to also have `toArray()` called on it. If the items were augmentables (like entries or terms) it would get all the augmented values in each one.
All of that, just to count how many entries there were. Massive overhead for nothing.
This has only become a problem in 3.3 and when using the new parser, when in a situation like this:
```
{{ terms_field }}
{{ if terms_field|length > 1 }} ... {{ /if }}
{{ /terms_field }}
```
The `terms_field` would be a query builder. The parser would store the results of it in the scope so it wouldn't have to re-query next time. Then the `length` modifier would get an instance of a `TermCollection`. It would call `toArray` on it which will do the whole …
=> Count collections more efficiently in the `length` modifier

src/Markdown/Parser.php
As suggested in https://github.com/statamic/cms/pull/5796#issuecomment-1092878903
Makes the  `Markdown\Parser` class macroable so that custom parsing methods can be added.
=> Make `Markdown\Parser` macroable

src/Tags/FluentTag.php, src/Tags/Nav.php, tests/Tags/FluentTagTest.php
Fixes #5598
This PR removes the Antlers parser from when a tag is loaded via Statamic::tag().
Then we can use the absence of a parser in tags for checking whether it's being used within Antlers or not.
Some tags do specific things like modifying the content of the tag pair in Antlers. When being used in Blade this isn't applicable, so we could return a useable array of stuff earlier.
=> Fix nav breadcrumbs in Blade

src/View/Antlers/Language/Runtime/NodeProcessor.php
This PR simply checks against `null` values before attempting to loop over them/perform sanity checking. This prevents items like the following from appearing in your logs when the value is `null`:
```
local.DEBUG: Cannot loop over non-loopable variable: {{ doesnt_exist }}
```
To reproduce simply loop over a variable that contains `null` or does not exist:
```
{{ doesnt_exist  }}
{{ /doesnt_exist  }}
```
=> Runtime: Prevents looping over nulls from being added to the log

src/View/Antlers/Language/Runtime/NodeProcessor.php, src/View/Antlers/Language/Runtime/Sandbox/Environment.php, tests/Antlers/Runtime/LoopTest.php
This PR resolves an issue where short-hand modifiers on tag pairs can be evaluated _twice_ when returning an array; often leading to unpredictable/incorrect results.
This bug prevent templates like the following from being evaluated correctly:
```
---
widths:
- '25'
- '50'
- '75'
---
{{ loop from="1" to="10" }}
{{ view:widths | shuffle | limit:1 }}
{{ value }}  <-- Should pull a random width, but will get confused after the first iteration before the fix.
{{ /view:widths }}
{{ /loop }}
```
=> Runtime: Prevent shorthand modifier tag pair modifiers from being evaluated twice

routes/cp.php, src/Auth/HasAvatar.php, src/Http/Controllers/CP/Assets/ThumbnailController.php, tests/Auth/HasAvatarTest.php
Fixes #5729
This one takes different approach from #5730, here I forcefully generate 1:1 aspect ratio image with existing `ThumbnailController@show` route.
However I had to change `ThumbnailController` to allow to override orientation, because before it would read the orientation from the asset, and it would be impossible to force `cp_thumbnail_small_square` image manipulation preset.
The only other place where this thumbnail route seems to be used is in `src/Assets/Asset.php`. The orientation path segment is optional and should not break existing usage.
One concern I see is that the `avatar()` method on `HasAvatar` trait could impact the avatar outputted on Antlers front-end, but from what I can see it does not (I tried outputting avatar from `{{ current_user }}`. From my understanding …
=> Square orientation user avatar generation for CP header

resources/js/components/fieldtypes/ToggleFieldtype.vue, resources/lang/en/fieldtypes.php, resources/views/extend/forms/fields/toggle.antlers.html, src/Fieldtypes/Toggle.php, src/Forms/Submission.php, src/Forms/Uploaders/AssetsUploader.php, src/Http/Controllers/FormController.php
=> Make toggle fieldtype available in frontend forms

resources/js/components/data-list/HasHiddenFields.js, resources/js/components/field-conditions/Omitter.js, resources/js/components/field-conditions/ValidatorMixin.js, resources/js/components/fieldtypes/Fieldtype.vue, resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/grid/Cell.vue, resources/js/components/fieldtypes/grid/Grid.vue, resources/js/components/fieldtypes/grid/Row.vue, resources/js/components/fieldtypes/grid/Stacked.vue, resources/js/components/fieldtypes/grid/StackedRow.vue, resources/js/components/fieldtypes/grid/Table.vue, resources/js/components/fieldtypes/grid/View.vue, resources/js/components/fieldtypes/replicator/Field.vue, resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/Set.vue, resources/js/components/publish/Container.vue, resources/js/components/publish/Field.vue, resources/js/tests/FieldConditionsOmitter.test.js, src/Fields/Field.php, src/Fields/Fields.php, src/Fields/Validator.php, src/Fieldtypes/Bard.php, src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php, tests/Fields/FieldsTest.php, tests/Fields/ValidatorTest.php
In https://github.com/statamic/cms/pull/5101, we added tracking for hidden fields, so that users could use `sometimes`, `required_if`, etc. validation rules. That PR only handled fields at the top level though, and caused issues between nested fields and top level fields with the same handles. This PR adds proper handling of nested hidden fields.
- We are now using error key for more than error handling, since those keys match payload structure.
=> Track and remove nested hidden fields

src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php
=> Fix taxonomy creation if collection exists with the same handle

src/View/Antlers/Language/Parser/DocumentParser.php, tests/Antlers/Fixtures/Addon/Tags/EchoMethod.php, tests/Antlers/Parser/BasicNodeTest.php
This PR closes #5842
The following will now render correctly:
```
{{ a = "A" ab = "AB" }} {{a}} invisible {{ a }} visible {{ab}} visible
```
=> Runtime: Fixes Single Letter Variables Without Spaces Skipping HTML Content

src/View/Antlers/Language/Parser/DocumentParser.php
This PR optimizes the parsing of `{{ noparse }} {{ /noparse }}` pairs by skipping everything in the document between the pairs, reducing the number of total characters processed.
=> Runtime: optimized noparse parsing

src/Fieldtypes/Terms.php, tests/Fieldtypes/TermsTest.php
Fixes #5768 
In addition to all the existing conditions, also only do the extra collection filtering/attachment magic when the parent entry is configured to use that taxonomy.
The bug in #5768 in a nutshell:
- You're on a `page` collection's entry.
- That entry has a terms field named `tags` (which matches a taxonomy named `tags`)
- When trying to use the `tags` field, it would filter down the terms to ones that are used within the `pages` collection, since that's the parent entry.
That last point was the issue. It was filtering the terms down, which since the collection wasn't configured to use it, was zero. You ended up with an empty array of terms. It should only do that if the `pages` collection also had `taxonomies: [tags]` in it.
This also adjusts the test to use named variables …
=> Add another condition for when the terms fieldtype filters with collection

src/Console/Processes/Composer.php, src/StarterKits/Installer.php, tests/Composer/ComposerTest.php, tests/StarterKits/InstallTest.php
We used to run a separate `composer require` call for each dependency. This PR groups dependencies into one `require`, and dev dependencies into another `require`, for a more efficient install...
=> Add ability to require multiple composer / starter kit dependencies at once

resources/js/components/fieldtypes/bard/Image.vue
It seems that the Bard inline image component tries to load null images before they are set.  This is related to the following issues: https://github.com/statamic/cms/issues/5860 https://github.com/statamic/cms/issues/5861
This PR makes the image not attempt to be loaded if the `id` is null.
Closes #5860
=> Ignore null image in Bard

resources/js/components/fieldtypes/grid/StackedRow.vue
I started tracking hidden nested fields in https://github.com/statamic/cms/pull/5805, but forgot to account for "stacked" grid row mode.
=> Fix hidden field tracking in stacked grid rows

src/View/Antlers/Language/Runtime/NodeProcessor.php, src/View/Antlers/Language/Runtime/Sandbox/Environment.php, tests/Antlers/Runtime/ConditionLogicTest.php
This PR fixes #5872 by ensuring that Cascade instances are sent through nested environments/conditional processors/etc.
=> Runtime: fixes conditions checking the Cascade

src/View/Antlers/Language/Lexer/AntlersLexer.php, tests/Antlers/Parser/BasicNodeTest.php, tests/Antlers/Runtime/ConditionLogicTest.php
This PR closes #5910 by adding support for uppercase/mixed-case language keywords.
The following will now work as expected:
```
{{ if something AND something_else == 'some value' }}
{{ /if }}
```
=> Runtime: Adds support for uppercase logical keywords

resources/js/components/Listing.vue, resources/js/components/assets/Browser/Browser.vue, resources/js/components/data-list/HasActions.js
- `Browser.vue` uses the mixin, which has the extra stuff like javascript callbacks ready to go, so #5901 will be able to work.
- Removed the `actionUrl` prop from the mixin. `Listing.vue` (the only thing using this mixin) needs a prop, but the asset browser uses a data property.
- Renamed `loadingAssets` to just `loading` in `Browser.vue`. It was called that back when we also had `loadingContainers`. Now using `loading` will allow the HasAction mixin to "just work" a little better.
- Added an `afterActionSuccessfullyCompleted` method to make it easier to override.
=> Asset browser uses HasActions mixin

src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Sandbox/VariableAssignmentTest.php
This PR fixes #5880 by checking what assignments were present before and after a tag call. Only assignments present in both will be respected.
=> Runtime: Prevent variables from leaking out of tags

resources/js/components/fieldtypes/replicator/Set.vue
It looks like that when a replicator set is toggled "off", the `updated` method isn't called and therefore it's not stored w/ the data nor available in Live Preview.
Not sure if this is the right approach, but it worked for me in extremely limited testing.
Closes https://github.com/statamic/cms/issues/5785
=> Update data when replicator set is toggled

src/Fieldtypes/Code.php
Fixes #5555
Replaces #5896
The code fieldtype was written expecting the Vue component to submit an array.
However if it's hidden using field conditions, nothing will be submitted. This PR handles the null.
=> Fix hidden code field

src/Modifiers/CoreModifiers.php, tests/Modifiers/StrPadBothTest.php, tests/Modifiers/StrPadLeftTest.php, tests/Modifiers/StrPadRightTest.php, tests/Modifiers/StrPadTest.php
As the title says, here's core modifiers for `str_pad()` with additional `str_pad_both`, `str_pad_left` and `str_pad_right` modifier helpers.
=> Added str_pad() modifiers

routes/cp.php
Statamic 3.3 did introduce the change, that the edit url of an entry did change. The slug has been removed from the url:
https://github.com/statamic/cms/commit/da97be6389b34113a13f3d41ef10b6e95419c2a8#diff-1d817f0299e963881205eac675e8f8b1e4cc38c5cf5a35659d46f1d19a42bbcf
In our case, this is introduction a breaking change for external systems, which did save the "old" edit url. Having such a change from 3.2 to 3.3 is fine and should generally not be a problem to many others I guess.
**I am suggestion this PR anyways, as this does add backwards compatibility and is not doing any harm to the core itself.** 
I am interested to hear if this is a good addition or if there are any concerns about this PR.
=> Add backwards compatibility to entry edit url

src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Runtime/ParameterStyleModifierTest.php
This PR corrects an issue where using parameter style modifiers under certain conditions can overwrite the scope accidentally. The setup to encounter this bug is to have something like this:
```
{{ collection:articles as="entries" }}
{{ taxonomy from="topics" sort="title:asc" as="some_alias" }}
{{ entries scope="entry" }}
Title: {{ entry.title }}<br />
Taxonomy Length: {{ some_alias | length }}<br />
{{ /entries  }}
{{ /taxonomy }}
{{ /collection:articles }}
```
I've created this repo to compare the before/after behavior in: https://github.com/Stillat/antlers-runtime-parameter-style-scope-reproduce
Before output:
```
Title: 'Dance Like No One is Watching' Is Bad Advice
Taxonomy Length:
Title: Nectar of the Gods
Taxonomy Length:
Title: The Magic Happens at 7 1/2 Pumps
Taxonomy Length:
``` …
=> Runtime: corrects parameter style modifier scope overwriting issue

src/Query/IteratorBuilder.php, src/Stache/Query/Builder.php, tests/Data/Assets/AssetQueryBuilderTest.php, tests/Data/Entries/EntryQueryBuilderTest.php, tests/Data/Taxonomies/TermQueryBuilderTest.php, tests/Search/QueryBuilderTest.php
When performing some queries, you might get results that are no longer zero indexed. This causes issues in Antlers because you can only loop over zero indexed things.
e.g.
```php
[
'foo',
'bar',
'baz'
]
```
If you do something to filter out foo, like `offset(1)`, you'd get
```php
[
1 => 'bar',
2 => 'foo',
]
```
This PR will call `values()` on the results which resets the indexes.
```php
[
'bar',
'baz'
]
```
This is consistent with Laravel's Query Builder.
Fixes #5758
=> Reindex query builder results

src/Query/OrderedQueryBuilder.php, tests/Query/OrderedQueryBuilderTest.php
This PR moves the limiting and offsetting from the query to the collection after the results have been retrieved.
For assets/entries/etc fields, the query gets wrapped in a decorator that'll apply the order after the results are retrieved. If you limit/offset, it would have already limited it on the query level before the decorator has a chance to change the order. This made using limit/offset on those types of fields sometimes output things in an unexpected/incorrect order.
=> Fix limit and offset on ordered query builders

routes/cp.php
In #5924 I moved a route too early in order to tidy up. Since it's a wildcard it needs to come after the other routes.
Fixes #5960
=> Move route to fix live preview pop out

src/Fields/Value.php, tests/Antlers/Runtime/Fieldtypes/CodeFieldtypeTest.php
This PR closes #5963  by casting instances of `ArrayableString` to strings when resolving a value for Antlers when the field is configured with `antlers: true`. This is only done when the site is set to `runtime` to prevent accidentally breaking something else.
To reproduce the original issue create a code field and set `antlers: true` on the field and include some Antlers code in the value. The code will not be evaluated before this PR, but will afterwards (the included test will also fail when moved to the main branch as another way to validate).
=> Runtime: evaluate Antlers within `code` fieldtype when `antlers: true` is set

resources/js/components/fieldtypes/MarkdownFieldtype.vue
The browser prompt asking for a URL in the Markdown field editor is currently defaulting to `http://`.
This PR just updates that value to `https://` by default.
=> Update default Markdown editor URL prompt value to `https://`

src/View/Antlers/Language/Nodes/AntlersNode.php, src/View/Antlers/Language/Parser/LanguageParser.php, tests/Antlers/Runtime/ParametersTest.php
This PR corrects an issue where parameters would not receive Cascade data, and also improves variable parsing when a numeric value makes up the beginning of a variable (like `{{ 404:button_text }}`).
Discovered while reading here: https://github.com/statamic/cms/discussions/5994
=> Runtime: fix numeric variables inside parameters and shares cascade data

src/Providers/AddonServiceProvider.php
This change does allow to overwrite the `getAddon()` method if extending it.
**Our usecase**
We are working on an addon, which can be customized a lot. To allow for that behaviour, that addon has two ServiceProviders, as done by knows addons like Laravel Horizon or Laravel Telescope.
This does allow for multiple things, but to name one concrete example, it's useful to register Fieldtypes. After publishing the ServiceProvider into the app Namespace, our Fieldtypes can be used or replaced by own implementations.
As known from addon context, you can simply register everything like this, just to give one example:
```php
protected $fieldtypes = [
\Spiegel\SomeFiedltype::class,
\Spiegel\AnotherFieldtype::class,
];
```
BUT
If the ServiceProvider is not in the addon Namespace, nothing will get …
=> Allow overwriting the `getAddon` method

src/Assets/AssetFolder.php, tests/Assets/AssetFolderTest.php
This fixes little bug I found while messing with #5996.
Say you had the following folders...
```
kit/
kitten/
kittens/
```
And you delete `kit`, all three would be deleted from the asset listing cache with stache watcher disabled, due to an overzealous `Str::startsWith()` check.
=> Fix overzealous deleting from asset listing cache with stache watcher disabled

src/Assets/AssetContainerContents.php
When adding a new folder to an s3 asset container with the stache watcher disabled, when refreshing the asset browser, the new folder would disappear because it wasn't being added to asset listing cache properly. It _looked_ like a data loss bug, but was just a caching thing.
I was able to reproduce this all the way back in 3.2.0 even with Flysystem 1.x even, so I'm not sure what could have changed. Maybe we just didn't catch it until now?
References #5723.
Closes #5888.
=> Fix adding new s3 folder to asset listing cache with stache watcher disabled

resources/js/components/fieldtypes/CodeFieldtype.vue, resources/js/components/fieldtypes/MarkdownFieldtype.vue, resources/js/components/fieldtypes/YamlFieldtype.vue
CodeMirror supports the browser spellcheck but it is not enabled by default. This would be really useful in markdown fields. It's only supported with the `inputStyle: 'contenteditable'` option, but the documentation states:
> **inputStyle: string**
>  Selects the way CodeMirror handles input and focus. The core library defines the "textarea" and "contenteditable" input models. On mobile browsers, the default is "contenteditable". On desktop browsers, the default is "textarea". Support for IME and screen readers is better in the "contenteditable" model. The intention is to make it the default on modern desktop browsers in the future.
https://codemirror.net/doc/manual.html
Given that `contenteditable` mode is already the default on mobile, will become the default on desktop, improves …
=> Enable spellcheck in markdown fields, improve CodeMirror accessibility

resources/js/components/field-conditions/Validator.js, resources/js/components/field-conditions/ValidatorMixin.js
=> Fix hidden data when replicator sets are collapsed by default

src/Assets/AugmentedAsset.php, src/Auth/Protect/Protectors/Authenticated.php, src/Auth/User.php, src/Fields/Blueprint.php, src/Fieldtypes/Bard.php, src/Modifiers/CoreModifiers.php, src/Query/Builder.php, src/Query/OrderedQueryBuilder.php, src/Routing/ResolveRedirect.php, src/Support/Str.php, src/Tags/Concerns/QueriesOrderBys.php, src/Tags/Concerns/QueriesScopes.php, src/Tags/FluentTag.php, src/Tags/Structure.php, src/Tags/Taxonomy/Terms.php, src/Tags/Theme.php, src/View/Antlers/Language/Lexer/AntlersLexer.php, src/View/Antlers/Parser.php, tests/Assets/AssetTest.php, tests/Auth/Eloquent/EloquentUserTest.php, tests/Fieldtypes/BardTest.php, tests/FluentlyGetsAndSetsTest.php, tests/TestCase.php
This PR expands on #5981 by fixing up more deprecated things.
I disabled deprecation handling in the test suite so it throws errors, and this PR is the result of fixing everything until there were no failures.
I don't have a good way to automate it on GitHub actions, but it's not difficult to do this manually every now and then.
```php
use Illuminate\Foundation\Testing\Concerns\InteractsWithDeprecationHandling;
abstract class TestCase extends \Orchestra\Testbench\TestCase
{
use InteractsWithDeprecationHandling;
// ...
protected function setUp(): void
{
// ....
$this->withoutDeprecationHandling();
}
}
```
=> Clean up deprecations

resources/js/components/fieldtypes/grid/StackedRow.vue
=> Fix revealers and inline field errors within stacked grid rows

src/Providers/RouteServiceProvider.php
A better approach (replacing https://github.com/statamic/cms/pull/5774)
Check if we are in a Statamic CP or API route before applying bindings.
Fixes: #4108
=> Ensure route bindings only apply to Statamic routes

config/antlers.php, src/View/Debugbar/VariableCollector.php
For complex pages with lots of variables, the rendered HTML in DebugBar makes pages unusable when DebugBar is enabled.
I want DebugBar, but not at the expense of a horrific on-page performance.
Turning this option off speeds things back up again.
=> Add config for pretty DebugBar variables

resources/js/components/fieldtypes/bard/BardFieldtype.vue
This PR adds a simple `replicatorPreview()` method to the Bard fieldtype, so you get the actual text content instead of a JSON string. Turns this:
Into this:
Parses the value and walks the data, concatenating any text node content. Breaks out of the loop once it hits >150 chars as that's all that's needed.
=> Improve Bard replicator preview

src/Http/Resources/CP/Taxonomies/ListedTerm.php, src/Http/Resources/CP/Taxonomies/Terms.php
Fixes: #5983 by ensuring the taxonomy title is returned in the JSON payload. It was erroring previously as it was only returning blueprint fields, which didn't include the taxonomy.
=> Add taxonomy column to return data in taxonomy terms field

src/Forms/Form.php, src/Forms/Tags.php, tests/Forms/FormTest.php
This adds an actionUrl method to the form class, so that it is easier to get the correct action url for the form.
Usage:
```php
$form = \Statamic\Facades\Form::find('contact');
$form->actionUrl();
```
`actionUrl` will return the action route from `route('statamic.forms.submit', $handle)`, which in the above context and with a default configuration should be ` /!/forms/contact`
=> Add actionUrl method to Form class

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Set.js, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/Set.vue
This PR adds a duplicate set option to the Replicator and Bard fieldtypes. Closes https://github.com/statamic/ideas/issues/756 and closes https://github.com/statamic/ideas/issues/81.
https://user-images.githubusercontent.com/126740/170833249-ae490b51-b3a7-4520-b8de-f579096d4774.mp4
I wasn't sure if there's a simple way for `BardFieldtype` to access the node attributes and position just using the set ID, which is why I'm parsing those values to `duplicateSet()` along with the ID.
=> Add duplicate set option to Replicator and Bard

src/View/View.php, tests/Antlers/Runtime/StacksTest.php
This PR improves stack/literal replacements when combined with tags like `{{ 404 }}`. If there is something (like the 404 tag) that stops the current parser process, it won't reach its final stack count where it removes the stack/literal replacements. This simply adds a "catch all" step that will remove anything left over at the very end.
Steps to reproduce:
1. Create a `stack` within a layout
2. On a template, do not push anything to the stack and trigger a 404 error with the `{{ 404 }}` tag.
3. Observe items like `__stackReplacement::_96e89a298e0a9f469b9ae458d6afae9f` or `__literalReplacement::_96e89a298e0a9f469b9ae458d6afae9f` in final output
=> Runtime: Removes literal/stack replacements on 404/error

src/View/Antlers/Language/Runtime/GlobalRuntimeState.php, src/View/Antlers/Language/Runtime/LiteralReplacementManager.php, src/View/View.php, tests/Antlers/Runtime/StacksTest.php
This PR fixes https://github.com/statamic/ssg/issues/98 by clearing the stack contents when the main Antlers render method is invoked.
To validate the fix, use stacks in the site's layout, and push to it from a template that is rendered multiple times. Once you run the `ssg:generate` command, you will find that the pushed contents are rendered multiple times on subsequent pages. In addition to validating against an SSG site, the provided test case will also fail when moving it to the base branch 👍
There exists a test case already to ensure this change does not break using stacks from partials: https://github.com/statamic/ssg/issues/98
=> Runtime: resets stack state

src/View/Antlers/Language/Runtime/NodeProcessor.php, src/View/Antlers/Language/Runtime/RuntimeParser.php, tests/Antlers/ParserTestCase.php, tests/Antlers/Sandbox/VariableAssignmentTest.php, tests/__fixtures__/blueprints/article.yaml, tests/__fixtures__/content/1996-11-18-dance.md, tests/__fixtures__/fieldtype_tests/replicator_blocks/expected.txt, tests/__fixtures__/fieldtype_tests/replicator_blocks/template.antlers.html
This PR fixes #6137 by improving how variables are managed when moving between parser boundaries. The linked repository in the original issue is a great way to test this fix. Additionally, the provided test case will fail when moved to the base branch.
=> Runtime: fixes variable scope across parser boundaries

config/assets.php, src/Assets/Asset.php, tests/Assets/AssetTest.php
Closes #6030, by enforcing lowercased asset filenames when uploading moving, and renaming.
I've made this configurable, but lowercasing by default is probably safer, especially for mac developers (with case-insensitive filsystems) deploying to linux servers (with case-sensitive filesystems).
=> Enforce lowercase asset filenames by default

src/Providers/ExtensionServiceProvider.php, src/Tags/Mount.php, tests/Tags/MountTagTest.php
This PR adds a `mount` tag which returns the mount URL of a collection, useful if you want to dynamically link to a collection's main page:
```html
<a href="{{ mount:blog }}">Read Our Blog</a>
```
If this might be accepted I can do a docs PR as well.
=> Add `mount` tag

resources/js/components/fieldtypes/ArrayFieldtype.vue, src/Fieldtypes/Arr.php
This is useful if you want to manage an array one item at a time, using a select box to switch between keys. Could be super useful for translatable Blueprint fields. 😊
=> New Single Mode for Array Fieldtype

resources/views/layout.blade.php
Reference statamic/ideas#248
The `dir` attribute in the Control Panel's `<html>` tag uses the direction from the "current" site, which will always just be the first/default site.
By changing it to "selected", it will use the direction for whichever site is selected in the global site picker, as expected.
This also removes the fallback. It would never be reached because the `direction` method already handled it, plus the fallback should have been ltr anyway.
=> Fix CP language direction

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
This PR refactors the Entry saveQuietly logic to avoid the value being cached/saved across multiple calls. I've also increased test coverage to ensure that events are fired after an initial saveQuietly call.
Fixes: #5628
=> Refactor saveQuietly logic

src/Tags/Tags.php
At the moment any tag that calls `Tags::parse()`, `Tags::parseLoop()`, or `Tags::parseNoResults()` fails when used from Blade with the following error:
```
Statamic\View\Antlers\Antlers::usingParser(): Argument #1 ($parser) must be of type Statamic\Contracts\View\Antlers\Parser, null given
```
Eg. `search:results` and `assets` when there are no results, or `get_files`.
This is because the `FluentTag` class doesn't set a parser, but `Antlers::usingParser()` expects one.
While that method could just be changed to accept nulls to fix the error, that still leaves Blade receiving `AntlersString` and `AntlersLoop` objects, which aren't particularly useful to Blade. Instead, this implements the same change from https://github.com/statamic/cms/pull/5599 to just return the raw data if no parser is …
=> Fix parser error when using Blade, provide raw data to Blade

src/Providers/RouteServiceProvider.php
As part of #5775 we didn't factor in that the broadcasting features uses these route bindings, except without passing along a route. This PR makes the routes optional. If one isn't passed in, we consider it "not an api/cp route".
Fixes #6167
Fixes statamic/collaboration#65
=> Fix route binding for broadcasting

src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Runtime/PhpEnabledTest.php
This PR corrects an issue where variables defined in a PHP node would not stay in scope. This PR addresses this by ensuring that all variables created in a PHP context are set within the Antlers internal variable assignments state.
To reproduce the issue this PR addresses, attempt to evaluate a template similar to the following:
```antlers
{{? 
$value_one = 100; 
$value_two = 0;
?}}
{{ loop from="1" to="5" }}
{{? $value_one += 5; ?}}
{{? $value_two += 5; ?}}
{{ /loop }}
{{ value_one }}
{{ value_two }}
```
The provided test case will also fail if moved to the base branch 👍
=> Runtime: Fixes variables created in PHP not staying in scope

src/View/Antlers/Language/Runtime/PathDataManager.php, tests/Antlers/ParserTestCase.php, tests/Antlers/Runtime/Fieldtypes/GridFieldtypeTest.php, tests/__fixtures__/fieldtype_tests/grid_array_plucking/expected.txt, tests/__fixtures__/fieldtype_tests/grid_array_plucking/template.antlers.html
This PR resolves `Statamic\Fields\Values` objects within the data manager. This change makes array plucking, dynamic access, etc. work with fieldtypes that argument to `Values`, such as the grid.
Before the fix, using array plucking on a grid field would not work as expected:
```antlers
{{ grid_field.0.field_name }}
```
The provided test case will also fail when moved to the base branch.
Source: https://discord.com/channels/489818810157891584/489819906540568593/983275015992659980
=> Runtime: Resolves Values objects

src/Http/View/Composers/JavascriptComposer.php
This fixes an recursion issue when the authenticated user has a relationship field on them, which references an item that has a reference to themselves, (eg. on an updated_by).
ie.
- User has an entries field
- The entries field has an entry selected
- That entry has updated_by the original user
This PR uses the augmented collection and toarray methods, which has handling built in for preventing recursion when using relationship fields.
Fixes #6074
=> Fix user recursion

src/Providers/ExtensionServiceProvider.php, src/Tags/MountUrl.php, tests/Tags/MountUrlTagTest.php
Fixes https://github.com/statamic/cms/issues/6180
Includes `mount` as an alias so it's non-breaking and you can still use that in Blade or with disambiguation.
=> Rename mount tag so it doesn't clash with variable

resources/js/components/field-conditions/Omitter.js, resources/js/tests/FieldConditionsOmitter.test.js
Fixes #5907
Fixes #6175 
There's some logic in a JS class that converts a "dotted path" to a "js path" that uses braces around numeric keys.
e.g. `foo.0.bar.baz` to `foo[0].bar.baz`
But the regex was too aggressive, causing braces to be added around parts of field names with numbers.
e.g. `field_1.0.bar.baz` to `field_[1].[0].bar.baz`, which is invalid, and results in the errors from the issues.
**Numbers at the *start* of a field name will still be broken.** I think this is a less common situation though. It requires a more drastic change to fix, so leaving it for another time.
=> Fix JS error when a field has a number

src/Tags/GetError.php, tests/Tags/GetErrorTest.php
Fixes #6196
The `get_error:somefield` tag pair should output nothing if there are no `somefield` errors.
Currently, the tag pair only outputs nothing if there are no validation errors *at all*. This fixes that.
=> Fix get_error tag outputting something when there are other errors

src/Exceptions/ControlPanelExceptionHandler.php, src/Exceptions/ValidationException.php
Laravel 9 introduced a "validation summary". https://github.com/laravel/framework/pull/35524
Normally when you have a validation exception, you'd loop over the validation errors and it wouldn't be an issue.
However in Statamic we're using inline validation messages. e.g. `This field is required` instead of `The title field is required`. Then we displayed the generic exception message in the toast: `The given data is invalid.`
In Laravel 9 the messaged changed to `[first validation message] (and 3 more)` which is super awkward when our inline translations are used.
"This" field? Which field?
This PR adds a custom Validation exception class that overrides the summary to the old text, but only within the Control Panel.
=> Use old generic validation exception summary

src/Http/Controllers/GlideController.php, src/Imaging/ImageGenerator.php
Resolve https://github.com/statamic/cms/issues/5709 by changing reference to FlysystemFileNotFoundException from Flysystem 1.x to \Exception, so that Flysystem 2.x and 3.x can be used.
=> Replace reference to FlysystemFileNotFoundException

src/Fields/Field.php
The 'isListable' method is tying to access an undefined array key "type" while accessing page listing.
The issue is fixed using the method 'type' which provide a fallback.
=> [Fix] class Field : Using config type fallback

resources/js/components/live-preview/UpdatesIframe.js
There may be other use cases I've not considered, but on a vanilla Statamic install its very frustrating to have live preview keep jumping back to the top every time you make a change... so this PR attempts to maintain the scroll position by getting and resetting the scroll position.
Fixes: #5564
=> Maintain iframe scroll position in live preview

src/Modifiers/CoreModifiers.php, tests/Modifiers/ShuffleTest.php
As reported by RustyMonkey on Discord, this allows you to use shuffle on an entries field type value
=> Support QueryBuilder values in shuffle modifier

src/Fieldtypes/Date.php, tests/Fieldtypes/DateTest.php
This allows you to use any available macros on the date field values.
Closes: [662](https://github.com/statamic/ideas/issues/662)
=> Augment date fields to Illuminate\Support\Carbon

src/Data/DataRepository.php, src/Http/Controllers/FrontendController.php, tests/Data/DataRepositoryTest.php
When you visit a Statamic route, the `FrontendController` has a bunch of logic to work out which entry/term/etc should be loaded.
This PR moves that controller logic into the `DataRepository` class so it can be used it in other places. (e.g in the upcoming static caching exclusion PR #6231)
```php
Statamic\Facades\Data::findByRequestUrl('http://mysite.com/foo');
```
=> Move data finding controller logic into repository

resources/js/components/entries/Listing.vue, resources/js/components/forms/SubmissionListing.vue, resources/js/components/terms/Listing.vue
Currently only the asset browser provides context to the bulk actions component, which means the context values are missing when fetching the bulk actions for entries, terms and form submissions.
This PR adds context values to the bulk actions in the other listing components.
=> Fix missing context when fetching bulk actions list

src/Tags/Locales.php, tests/Tags/LocalesTagTest.php
On a multi-site, if you have a `locales` tag in your template/layout AND you create a new entry but do not save it AND you use Live Preview, there's an error because the `id` in the context is a `Value` object, which the `Data:find` method can't handle.
Using the `value` method on the context instead of `get` resolve this.
Fixes #6262
=> Fix `locales` tag when using Live Preview

src/Providers/ExtensionServiceProvider.php, src/Tags/Vite.php
Since version [v9.19.0](https://github.com/laravel/framework/releases/tag/v9.19.0) of Laravel, Vite is now the default tool for bundling frontend assets.
In order for Statamic to fully migrate to this we will also have to change the `statamic/statamic` repo and remove the default Laravel Mix. Vite also plays nicely with Vue@2 which is required to build Fieldtypes or extending any frontend stuff.
If required I can also submit a PR to the docs for the new Vite tag.
More info on Vite at the Laravel [docs](https://laravel.com/docs/9.x/vite).
P.s thanks to @duncanmcclean for the tag.
=> Added Vite tag

src/Entries/Collection.php, src/Taxonomies/Taxonomy.php, tests/Data/Entries/CollectionTest.php, tests/Data/Taxonomies/TaxonomyTest.php
I've been working on a script to import data into a fresh Statamic install. When testing the script I want to clear out the previous data first. While this is simple enough, this PR adds a shorter convenience method called `truncate` that you can use to empty out a collection or taxonomy.
=> Add truncate method to collections and taxonomies

src/Search/UpdateItemIndexes.php, tests/Feature/GlobalSearch/GlobalSearchTest.php
Hi,
When using Statamic's search feature we can index Users, Assets, Entries and Taxonomies. But when it comes to updating existing indexed entities, only entries will be updated in `src/Search/UpdateItemIndexes.php`.
This PR adds events for all four entities and triggers an update of the corresponding indexed document.
=> Update search indexes for assets, terms, and users

resources/js/components/data-list/Pagination.vue, resources/js/components/entries/Listing.vue, resources/js/components/entries/Widget.vue, resources/js/components/forms/SubmissionListing.vue, resources/js/components/terms/Listing.vue, resources/js/components/users/Listing.vue
Fixes https://github.com/statamic/cms/issues/6276
Apologies, I overlooked this in the original PR. Have gone with the suggestion in the issue to hide them within widgets. I've also changed they way they work to be opt-in generally, as they only really work in the main listings and don't look great in the selectors either.
=> Remove item totals in widgets and selectors

src/Fields/Blueprint.php, src/Http/Controllers/CP/Collections/EntriesController.php
This simple PR closes https://github.com/statamic/cms/issues/5991. We set a blueprint's parent when we edit an entry. And we also reset the fields cache whenever a parent gets set.
=> Update Blueprint Parent

resources/js/components/users/Listing.vue, src/Auth/UserRepository.php, src/Http/Controllers/CP/Users/UsersController.php, src/Http/Resources/CP/Users/ListedUser.php, src/Http/Resources/CP/Users/Users.php
=> Add column selector to users listing

src/Fieldtypes/Entries.php
This pull request fixes #6281 by returning only blueprints that haven't been marked as hidden when using the 'Create' function on the Entries fieldtype.
=> Don't show hidden blueprints from Entries fieldtype

resources/js/components/fieldtypes/assets/AssetRow.vue
This PR adds the size of the asset to the tooltip.
**Reason behind PR:**
Content editors usually want an easy way to check the sizes of the assets that are uploaded for performance reasons. Now, you have to popup a modal that takes the whole screen and then close it again just to check the file size. Annoying. Now you can just hover over the asset.
**How it looks:**
=> Add file size to asset row tooltip

src/View/Antlers/Language/Parser/AntlersNodeParser.php, tests/Antlers/Parser/NodeParametersTest.php
This PR fixes #6287 by allowing parameters to start with numbers.
To reproduce, use a tag with parameters like the following:
```antlers
{{ tag lg:ratio="2" 2xl:ratio="7" }}
```
The provided test case will also fail when moved to the base branch.
=> Runtime: Allows parameters to begin with numbers

src/Fieldtypes/Assets/MimesRule.php, src/Fieldtypes/Assets/MimetypesRule.php, src/Forms/Exporters/CsvExporter.php, src/Support/Str.php, src/Tags/Nav.php, src/Tags/ParentTags.php
We keep discarding these php-cs-fixer changes. Might as well just use the actual functions instead of the aliases. Also cleans up output for https://github.com/statamic/cms/pull/6298
=> Use `implode()` instead of `join()` alias to appease style fixers

resources/sass/components/fieldtypes/bard.scss
Tables are valid inside list items and blockquotes, and Bard allows you to add them. Everything works fine except they have no styling due to the CSS only targeting tables that are a direct descendant of the editor.
This PR fixes that. It adds selectors for tables inside `blockquote` and `li` elements. It also tweaks the selector for paragraphs inside lists/blockquotes, so those styles do not apply to paragraphs in tables that also happen to be inside lists/blockquotes.
Before:
After:
=> Fix bard nested table styling

resources/js/components/publish/Sections.vue
Very long lines/words in code mirror based fields can kick out the layout, forcing the main section wrapper too wide and the sidebar offscreen. This problem can also occur when using `line_wrapping: true` if the content has very long "words".
This PR fixes that by setting the wrapper's `min-width` to `0`.
https://user-images.githubusercontent.com/126740/177972186-254c775a-a1d1-43a0-9e5d-8239415fadfc.mp4
=> Fix long lines/words in code mirror breaking the layout width

src/View/Antlers/Language/Analyzers/RecursiveParentAnalyzer.php, src/View/Antlers/Language/Nodes/AbstractNode.php, src/View/Antlers/Language/Runtime/RecursiveNodeManager.php, tests/Antlers/Runtime/RecursiveNodesTest.php
This PR fixes #6319 by correcting two subtle issues that are working together to produced the undesired behavior.
The first is an issue where the runtime would resolve the incorrect recursive parent when rendering recursive children. This issue is most apparent when using multiple nav tags in the same template, but having many recursive children nodes was enough to confuse it when nested inside if statements. To reproduce, create any nav with children and attempt a template like the following:
```antlers
<ul>
{{ nav:test }}
<li class="one">
{{ title }} - {{ depth }}<br />
{{ if children }}
<ul>
ONE
{{ *recursive children* }}
</ul>
{{ /if }}
</li>
{{ /nav:test }}
</ul>
<ul>
{{ nav:test }}
<li class="two">
{{ title }} - {{ depth }}<br />
{{ if children }}
<ul>
TWO
{{ *recursive children* }} …
```
=> Runtime: Fixes using many `{{ *recursive children* }}` within a nav tag (and many recursive navs within a single template)

src/Statamic.php, tests/StatamicTest.php
Fixes #6326 
When you have a custom translation file and you try to use the name of it as a translation string, it loads that file.
e.g. `__('file')`
To combat this, we introduced `Statamic::trans()` that will just return the string if an array is encountered.
This PR uses that method within breadcrumbs.
=> Translate breadcrumbs using statamic trans method

src/Assets/Asset.php, tests/Assets/AssetTest.php
- We have this on `Entry`, and Laravel offers this on their models as well
=> Add `saveQuietly()` method on `Asset` to avoid firing events

src/Console/Commands/SupportDetails.php, src/Providers/AppServiceProvider.php
This PR adds items to the new `artisan about` command.
It also now treats `please support:details` as an alias for `artisan about` with more copy-pasteable formatting for GitHub issues.
On older versions of Laravel that don't yet have the `about` command, `support:details` will continue to work as it always did.
=> About command

src/Stache/Stores/UsersStore.php
When a user file doesn't have an `id`, Statamic would generate one and put it back in the file.
This was working fine until #3379 which introduced an infinite loop.
https://github.com/statamic/cms/blob/e71a79b94bacde2746455e2b87caf539d510afa1/src/Auth/User.php#L158
Instead of "saving" the entry again (which would trigger a bunch of other logic causing the loop) we can simply write the file.
=> Fix infinite loop when user file doesn't have id

src/Statamic.php
Better safe than sorry ☺️
(I just run into this myself)
There might be cases, where a full path to an asset does contain a extension already. That would lead to a file path like `app.css.css?v=xxx` which is not wanted. 
The PR does fix that. Before extending the path with the extension, it will check if the path already ends with the given extension.
=> A versioned asset path can contain a extension

src/View/Antlers/Language/Parser/LanguageParser.php, tests/Antlers/Runtime/ArithmeticTest.php
This PR fixes #6360 by correctly grouping the `%` operator with its operands.
The following will now work as expected without explicitly adding `()`:
```antlers
{{ if 6 % 2 == 0 }} ... {{ /if }}
```
The provided test case will also fail when moved to the base branch.
=> Runtime: Modulo throwing DivisionByZeroError

src/Fieldtypes/Toggle.php, src/Forms/Form.php, tests/Feature/Forms/UpdateFormTest.php, tests/Fieldtypes/ToggleTest.php
Ensure the toggle fieldtype only casts to a saveable boolean when the value is submitted. When conditionally hidden, it should save neither `true` nor `false`, [according to our docs on conditional field data flow](https://statamic.dev/conditional-fields#data-flow).
Fixes #6347.
=> Fix toggle field casting to boolean when field is hidden

src/GraphQL/Types/CollectionType.php, tests/Feature/GraphQL/CollectionTest.php
This allows you to add custom fields to collections, like this:
```php
GraphQL::addField('Collection', 'mount', function () {
return [
'type' => GraphQL::type('EntryInterface'),
'resolve' => fn ($collection) => $collection->mount(),
];
});
```
=> Allow custom graphql fields to be added to collections

src/Modifiers/CoreModifiers.php, tests/Antlers/Runtime/CoreModifiersTest.php
Now the test matches [the documentation](https://statamic.dev/modifiers/word_count). Could also pass the `PREG_SPLIT_NO_EMPTY` flag through to `preg_split()` for the same effect.
=> Fix word count in CoreModifiers treating punctuation as a word

src/Tags/Concerns/OutputsItems.php
If there are no results when using the search tag `no_results` is set to `true`, but if there are results `no_results` doesn't exist at all. This is fine in antlers because antlers doesn't mind the missing variable, but in blade you cant simply check for `@if ($search['no_results'])` without getting an undefined array key error when there are results.
This PR fixes that by always including `no_results` in the data, even when it's `false`.
=> Always include no_results in tags that output items

src/Stache/Stores/CollectionTreeStore.php, tests/Feature/Collections/UpdateCollectionTreeTest.php
This basically reverts #4978 and fixes #4495.
#4978 only seemed to fix the problem when the collection had the word `collection` _within_ it. e.g. `my_collection`. However it was still broken when the handle was literally just `collection`.
Removing the "fix" makes it works for all scenarios:
- Handle named literally `collection`
- Handle with `collection` in it, like `my_collection`
- Completely different handle like `pages`
Something else in the codebase must have resolved #4495 since the issue was originally opened.
Added test coverage to prevent another regression.
=> Fix reordering entries in a collection named literally collection

src/Providers/StatamicServiceProvider.php
Credit to @JohnathonKoster for this find!
To test, throw this in your sandbox's composer.json...
```json
"require": {
"php": "^8.0",
"laravel/framework": "9.22.0",
"statamic/cms": "dev-fix/cache-macro-not-found-error as 3.3.23",
...
},
```
Also worked when I tested deploying to Netlify...
Fixes https://github.com/statamic/cms/issues/6365
=> Fix `rememberWithExpiration` cache macro not found error

src/Actions/CopyPasswordResetLink.php
Fixes #6402
This change makes sure that the token is generated into the right spot.
i.e. If you have your `config/statamic/users.php` site configured like this
```php
'passwords' => [
'resets' => 'resets',
'activations' => 'activations',
],
```
then the activation token would be generated into the resets table/file, which was the issue.
Also, the "waiting for the link to expire" step mentioned in the issue was not necessary to see the bug. A first time activation link would have been just as broken.
=> Generate appropriate token in password reset action

src/Tags/Concerns/RendersForms.php, tests/Tags/Concerns/RendersFormsTest.php
We intentionally minify dynamically rendered field html for a few reasons:
- This trims whitespace around textarea content, ensuring weird results aren't submitted
- Users should be able to use style their own margins/gaps between checkbox inputs and label text using CSS
- etc.
However, if someone wants to render an `<a>` or `<span>` tag in a checkbox option, our regex was a bit too aggressive. This PR adds a whitelist of element types to ignore, leaving whitespace around those elements where used.
Example of how minification now handles a checkbox with a link:
```html
<label><input type="checkbox">Option with <a href="/link">a link</a> to click</label>
```
See test coverage for more detailed examples.
Fixes #6390
=> Fix aggressiveness of html minification when rendering form fields

src/Tags/Partial.php, src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Tags/PartialTagsTest.php
This PR makes partial parameters available to slots and named slots:
```antlers
{{ partial:partial_name size="lg" color="blue" }}
{{ slot:footer }}
Named slots can also access the parameter variables: {{ size }} - {{ color }}
{{ /slot:footer }}
Can now access the parameter variable: {{ size }} - {{ color }}
{{ /partial:partial_name }}
```
Currently, you cannot access the parameter values by name within slots or named slots. This PR also includes test cases for these two scenarios.
=> Antlers: Makes parameters available within slots and named slots

.github/workflows/tests.yml, composer.json
Within a GitHub action, if there's a problem connecting to packagist.org, the composer step will fail and cause the entire workflow to fail.
This PR wraps the composer steps in the nick-invision/retry action. Usually running the same composer command again fixes the issue.
=> Use the retry action for composer steps

resources/js/components/fieldtypes/ToggleFieldtype.vue, resources/sass/components/toggle.scss
```yaml
inline_label: I agree [to the terms](/terms)!
```
Styles mostly copied from our `instructions` `.help-block`
Closes #6411
=> Add markdown support to toggle `inline_label` config

src/Modifiers/CoreModifiers.php, tests/Modifiers/EmbedUrlTest.php
Vimeo.com unlisted videos currently can't be embedded as the embed_url modifier doesnt handle the extra 'hash' on the end of the url being converted to an URL param.
eg. currently `https://vimeo.com/735352648/fa55a4d0fc` becomes `https://vimeo.com/735352648/fa55a4d0fc?dnt=1` which gives an error.
the correct behaviour should be `https://vimeo.com/735352648/fa55a4d0fc` becomes `https://vimeo.com/735352648?dnt=1&h=fa55a4d0fc`
This PR updates the modifier and adds tests to do just that.
=> Handle embedding vimeo.com unlisted urls

config/antlers.php, tests/TestCase.php
This makes the runtime parser the default for 3.4.
The regex parser will **not** be removed yet. It'll still be available if you need it.
**Potential breaking change**
If you had a pre-3.3 site and upgraded to 3.3 and _didn't_ opt into the new parser (by adding or editing `config/statamic/antlers.php`), you would have stayed on the old parser. When you upgrade to 3.4, you'll get switched to the new one. If you want to stay on the old one, you'll simply need to adjust the config.
```php
// config/statamic/antlers.php
'version' => 'regex',
```
=> Default to the Runtime Antlers parser

src/Fieldtypes/Bard/Augmentor.php
This PR adds the ability to use a custom Tiptap editor class.
This PR is for Bard 2 / TipTap 2 and targets the master branch.
As much as I’ve tried to work around it there are some bard customisations that are only really possible if you can get some extra logic into the start of the Tiptap rendering process. An example is the [metadata feature](https://jacksleight.github.io/statamic-bard-mutator/mutators.html#metadata) of my Mutator addon. My current implementation of this [relies on a tag](https://jacksleight.github.io/statamic-bard-mutator/rendering.html#tag), but that’s a bit of a hack and the dependency on a tag means these features aren’t available when using the REST/GraphQL APIs (without the user jumping through additional hoops).
If I could bind an extended version of the editor …
=> Ability to use a custom Tiptap editor class

src/Fieldtypes/Grid.php, src/Fieldtypes/Replicator.php, tests/Fieldtypes/BardTest.php, tests/Fieldtypes/GridTest.php, tests/Fieldtypes/ReplicatorTest.php
If you have a template with a query like `{{ collection:products mygrid:exists="true" }}` where you are attempting to only show entries that have something in the grid field.
If you save an entry with an empty grid, the empty array was being indexed, which made the "exist" condition pass, even though it was empty.
This PR makes sure that if you have an empty Grid/Replicator/Bard, that a null will be indexed instead of an empty array.
=> Empty grid/replicator/bard should be indexed as null

src/View/Antlers/Language/Parser/LanguageParser.php, tests/Antlers/Sandbox/VariableAssignmentTest.php
This PR corrects an issue that was preventing the creation of new array variables. The following will now work as expected:
```antlers
{{ my_array = [] }}
{{ my_array += 'Item 1' }}
{{ my_array += 'Item 2' }}
{{ my_array += 'Item 3' }}
```
=> Antlers: Corrects an issue preventing the creation of new array variables

src/View/Antlers/Language/Runtime/RecursiveNodeManager.php, tests/Antlers/Runtime/RecursiveNodesTest.php
This PR fixes #6439 by resetting the recursive state of the recursive parent node before it exits and moves onto the next internal node. This prevents depths from being carried onto the next execution if the same node is re-used (like when they are contained within partials). The linked issue contains fantastic steps to reproduce.
```antlers
<ul>
{{# This PR now tracks how deeply nested we are on this node. #}}
{{ nav:menu }}
<li>
<span>{{ title }} - {{ depth }}</span>
{{ if children }}
{{#
Each time we hit this point, we'll update the total nesting level,
as well as continue to update the depth mapping.
#}}
<ul>{{ *recursive children* }}</ul>
{{ /if }}
</li>
{{# The recursive state is now forecfully reset before we leave this point for the last time. #}}
{{ /nav:menu }}
</ul>
```
This PR …
=> Antlers Runtime: fix incorrect nav depth when using a partial multiple times

resources/lang/en/fieldtypes.php, src/Fieldtypes/Bard.php, tests/Fieldtypes/BardTest.php
This PR allows removing empty paragraphs from Bard fields. As discussed over here: https://github.com/statamic/ideas/issues/836
It introduces `remove_empty_paragraphs` with three options:
- `false`: Don't remove empty paragraphs
- `true`: Remove all empty paragraphs
- `trim`: Remove empty paragraphs at the top and the bottom
=> Remove empty Bard paragraphs

src/Forms/SendEmails.php
This simple PR makes the augmented submission data available to the form email config. This allows doing things like:
```
subject: 'Hi, {{ salutation:label }} {{ name }}. You signed up for course {{ course:title }}.'
```
=> Augment submission data in email config

CHANGELOG.md, src/Tags/Partial.php, src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Tags/PartialTagsTest.php
This reverts #6405 as it was found to be a breaking change.
=> Revert "Antlers: Makes parameters available within slots and named slots (#6405)"

src/Forms/Email.php, src/Forms/Form.php, src/Forms/SendEmails.php, tests/Feature/Forms/UpdateFormTest.php, tests/Forms/EmailTest.php, tests/Forms/SendEmailsTest.php
- Adds test coverage to email sending
- Minor refactors to ease testability
- Prevent parsing Antlers in email configs twice
- Fix issue where if you configure a single email (un-nested) and then save the form it'd fail.
e.g.
```yaml
email:
to: foo@bar.com
```
instead of the proper
```yaml
email:
-
to: foo@bar.com
```
=> Improve form emails

src/Stache/Query/EntryQueryBuilder.php, src/Stache/Query/TermQueryBuilder.php
When working on #6455 I noticed that there are some unnecessary orWhere()s in the builders (my fault) so I've removed them to keep the code tidier.
=> Remove unnecessary orWheres

src/View/Antlers/Language/Parser/LanguageParser.php, tests/Antlers/Fixtures/MethodClasses/CallCounter.php, tests/Antlers/Runtime/MethodCallTest.php
This PR corrects a subtle issue with node pairing that could lead to methods being called more times than wanted.
To recreate this issue, have some class like so:
```php
<?PHP
namespace App;
class CallCounter
{
protected $count = 0;
public function increment()
{
$this->count += 1;
return $this;
}
public function __toString(): string
{
return 'Count: ' . $this->count;
}
}
```
Inject it into a view (`counter` in the following) and call the `increment` method three times:
```antlers
{{
counter:increment()
:increment()
:increment()
}}
```
Before this fix, the result `Count: 4` would be displayed. This PR also includes new test coverage for this.
=> Antlers: fix methods getting called too much

src/Tags/Locales.php
Fixes #6418
Fixes #3833
Replaces #4047
Since it's looking likely that there will be a [taxonomy overhaul](https://github.com/statamic/ideas/issues/839), I figured it's better to just apply a quick workaround into the locales tag, rather than a "proper" fix that'll end up affecting way too many parts of the codebase, and eventually may have not even be needed if taxonomies are changing. That's why #4047 was sitting there for so long - it was too big of a change. Plus I was tired of seeing it sit there.
This PR will make the locales tag compare the ID to the "page" ID. If it's the same term, it'll just use the term object, which will be associated with the collection already and therefore output the collection specific URL.
The downside to this is that if you're using a `taxonomy:foo` tag …
=> Fix locales tag not outputting collection specific term urls

src/Providers/AddonServiceProvider.php
As a PHP Developer, I found statamics core fairly hard to discover - both, because of the indirection some Laravel features such as facades add and because of the lack of type information.
I raised this issue in Discord, where we agreed, that I would start making small PRs to add missing type information which would make the code
* Easier to discover for newer developers looking to develop addons
* Parsable by static code analyzers such as Psalm or PHPStan in order to leverage them when developing such addons
I was careful, only to add type information in docblocks. Ideally, 'real' Type information would be added (e.g. `protected array $listen`) - but that would be considered a breaking change for downstream code.
=> Add type information to AddonServiceProvider

src/GraphQL/Types/TermType.php, tests/Feature/GraphQL/TermTest.php
Fixes #6166
Fixes `User Error: expected iterable, but did not find one for field` error.
When a taxonomy has a relation to another taxonomy with multiple terms, a `Statamic\Query\OrderedQueryBuilder` is returned by the `resolver` method in `Statamic\GraphQL\Types\TermType` when it's queried as a nested taxonomy in GraphQL.
In the `completeListValue` method in `GraphQL\Executor\ReferenceExecutor` there's a check to see if the `$results` variable is an array or at least Traversable.
```
Utils::invariant(
is_array($results) || $results instanceof Traversable,
'User Error: expected iterable, but did not find one for field ' . $info->parentType . '.' . $info->fieldName . '.'
);
```
By using the `resolveGqlValue` method in the resolver method of `Statamic\GraphQL\Types\TermType` an extra check …
=> GraphQL: Fix terms not resolving query builders

resources/js/components/fieldtypes/bard/Set.vue
This computed was added to 3.3 after the Bard 2 upgrade. We had merged 3.3 into master but didn't tweak this, which results in an error when you add a set.
=> Fix bard set showFieldPreviews

package-lock.json, package.json, resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/buttons.js, src/Providers/BardServiceProvider.php, tests/Fieldtypes/BardTest.php
This PR adds text align support to Bard by implementing the official Tiptap 2 TextAlign extension:
https://tiptap.dev/api/extensions/text-align
I think just enabling it for `heading` and `paragraph` works for everything you'd want it too, as Tiptap adds paragraphs inside list items and table cells.
When enabled this extension does add a default `textAlign` attribute to the nodes in the data, which is why I've had to tweak the tests. However when this is set to `left` the rendered HTML remains unchanged.
This PR is for Bard 2 / TipTap 2 and targets the master branch.
Closes https://github.com/statamic/ideas/issues/470
=> Add text align support to Bard

src/Entries/Entry.php
I've got a collection of persons with auto-generated titles:
```
title_format: '{academic_title} {first_name} {last_name}'
```
Not every person has an academic title. This would result in an untrimmed title. I hate untrimmed strings. This PR fixes that.
=> Trim auto generated titles

src/Statamic.php, tests/StatamicTest.php
An Issue came up on Discord:
```php
class ServiceProvider extends AddonServiceProvider
{
protected $stylesheets = [
__DIR__.'/../resources/css/admin-styler-base.css'
// Under the hood, Statamic::style() will be called. The name     
// `admin-styler` will be used automatically as  name, as it's the addon name.
// The cache prefix will be::
// "statamic-{$extension}-{$name}"
// In that case `statamic-css-admin-styler`
// @see https://github.com/statamic/cms/pull/6312/files#diff-a932c529bea3a9e695fb0306ae4635bda104d78b85cb8eb7bc15de11bc2f44d7R397
];
public function boot()
{
parent::boot();
Statamic::style('admin-styler', 'admin-styler-custom');
// The name is `admin-styler` as well, so the cache kicks in and will deliver the cached file instead.
}
}
```
**The fix does allow for assets with …
=> Cache files with different paths differently

src/Http/Resources/CP/Concerns/HasRequestedColumns.php
In an Entries fieldtype, when I filter by a collection, an exception is thrown. It happens when the first collection in the list has fields that are listable (listable: true) and when those fields do not exist in the collection selected for filtering.
This PR fixes that problem.
Also fixes #4317
=> Fix "filtering a collection throws an exception"

resources/sass/components/fieldtypes/datetime.scss
If you have a date field with time disabled in a narrow container extra margin appears below the field. This is visible when the field appears in a grid or when the field can be toggled, where it will cause a layout shift:
https://user-images.githubusercontent.com/126740/182614214-75bcd755-8780-4196-8486-0202329e7ee0.mp4
This PR fixes that by moving the margin from the date container to the time container, so it only appears when time is enabled.
=> Fix extra margin on narrow date only fields

src/View/Antlers/Language/Runtime/Sandbox/Environment.php, tests/Antlers/ParserTestCase.php, tests/Antlers/Runtime/CoreModifiersTest.php, tests/Antlers/Runtime/Fieldtypes/BardFieldtypeTest.php
This PR fixes #6482  by not resolving Antlers values when the value contains the `raw` modifier as its first modifier. The linked issue contains steps to reproduce the issue. The PR contains new test coverage for this scenario.
=> Runtime: fixes `raw` modifier on fields with `antlers: true`

CHANGELOG.md, src/View/Antlers/Language/Nodes/AntlersNode.php, src/View/Antlers/Language/Runtime/NodeProcessor.php, src/View/Antlers/Language/Runtime/RecursiveNodeManager.php, tests/Antlers/Runtime/RecursiveNodesTest.php
This PR fixes #6485 by keeping track of the recursive nodes active depth on the node itself. This depth is then pushed to the manager instead of the other way around, which could easily get confused.
This PR also includes new tests to cover this scenario. An easier way to replicate would be to follow the steps in the linked issue and check the behavior before/after the changes in this PR.
=> Runtime: improves recursive children

src/Providers/AddonServiceProvider.php
This PR adds a `bootFormJsDrivers` method to the `AddonServiceProvider` to simplify registering custom form JS drivers.
Should it be `formJsDrivers` or `formsJsDrivers`?
=> Add form JS driver boot method to `AddonServiceProvider`

resources/js/components/assets/Browser/Thumbnail.vue
SVG thumbanils get stretched to fill the space in the asset browser:
This PR fixes that by adding `object-contain` to the `<img>` element:
=> Fix stretched SVG thumbnails

config/assets.php, config/system.php, resources/js/components/fieldtypes/bard/Image.js, resources/js/components/fieldtypes/bard/Image.vue, src/Assets/AssetReferenceUpdater.php, src/Data/DataReferenceUpdater.php, src/Listeners/UpdateAssetReferences.php, src/Listeners/UpdateTermReferences.php, src/Taxonomies/TermReferenceUpdater.php, tests/Listeners/UpdateAssetReferencesTest.php, tests/Listeners/UpdateTermReferencesTest.php
=> Improve updating and deleting of term and asset references

resources/lang/en/messages.php
Change "considered" to "consider"
ie. `Consider the first page in the tree a "root" or "home" page.`
=> Minor typo fix for Root Page CP Documentation

src/Http/Controllers/FormController.php
Event is already [fired here](https://github.com/statamic/cms/blob/b23c3e970a53fbfbcfaeaa28ed36407fd258588c/src/Forms/Submission.php#L165) so no need to fire it again
=> Handle double `SubmissionCreated` event

src/Tags/Cache.php
Adds `{{ cache scope="user" }}` option to the cache tag, to scope it to the currently logged in user or guest. 
Closes: https://github.com/statamic/ideas/issues/850
=> Add user scope on cache tag

src/Providers/ExtensionServiceProvider.php, src/Tags/UserGroups.php, tests/Tags/UserGroupsTagTest.php
This tag allows you to return all user groups or a specific group, both of which can be useful in some situations (eg membership sites).
Usage:
`{{ user_groups }} {{ title }} {{ /user_groups }}`
`{{ user_groups handle="group_handle" }} {{ title }} {{ /user_groups }}`
I'm happy to work on this further if you feel its lacking, and I'll create a docs PR if you are happy to merge this.
=> Add `user_groups` tag

src/Providers/ExtensionServiceProvider.php, src/Tags/UserRoles.php, tests/Tags/UserRolesTagTest.php
Similar to the user_groups tag PR, this tag allows you to return all user roles or a specific roles, both of which can be useful in some situations (eg membership sites).
Usage:
```
{{ user_roles }} {{ title }} {{ /user_roles }}
{{ user_roles handle="role_handle" }} {{ title }} {{ /user_roles }}
```
I'll create a docs PR if you are happy to merge this.
=> Add `user_roles` tag

src/Auth/Eloquent/Roles.php
=> Collect eloquent roles on sync to preserve passing them as an array

src/Forms/Tags.php
When updating the docs for #6542 I noticed that you have to explicitly use the handle:
```antlers
{{ form:create :in="formfield:handle" }}
```
This PR allows you to just pass the form directly into it, which feels more intuitive:
```antlers
{{ form:create :in="formfield" }}
```
=> Support passing a form instance into tags

src/Fieldtypes/Toggle.php, src/Query/Scopes/Filters/Fields/Toggle.php
This PR adds a true/false filter for the toggle fieldtype:
You currently have to do `is: "1"` or `isnt: "1"` to filter on a toggle field, which isn't very user-friendly.
Related to https://github.com/statamic/ideas/issues/843 but doesn't close it as this doesn't cover filtering empty values.
=> Add toggle field true/false filter

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
=> Allow setting of entry blueprint instance using instance

resources/js/components/fields/Settings.vue
Fixes #1616. 
Tested with Grid and Replicator fields. The config gets stored in the blueprint yaml and is available in the fieldtype's Vue component.
=> Add support for using meta fields as config fields

resources/js/components/fieldtypes/bard/BardFieldtype.vue
This PR does remove the key binding if a bard fieldtype gets destroyed.
_If using the Live Preview, Statamic has memory leaks:_
- Open the Live Preview
- Close the Live Preview
- Repeat multiple times
_Depending on the size of replicator fields etc, the memory usage will grow with every switch from live preview to non-live preview._
This PR is only a small part of it, but does help to reduce the leak at least a tiny little bit.
=> Destroy esc binding in Bard fieldtype

resources/views/utilities/index.blade.php, src/CP/Utilities/Utility.php
This pull request allows for developers passing in custom SVG icons for Utilities. 
Here's a quick overview of the things I've changed:
* When creating a `Utility` and using the `->icon()` method, a developer can either provide the name of an icon in Statamic's `resources/svg` directory or they can provide a string of an SVG. 
* Instead of using the `@cp_svg` blade directive to display icons, I've changed it for a inlining it with Blade. This works for both Statamic icons and custom SVGs as they are all strings when they are returned from the `->setter` method.
This PR follows up on #2890 which did the same thing for CP Nav Items & comes after a discussion on Discord (#extending).
=> Allow for passing custom icons to Utilities

resources/js/components/inputs/relationship/RelationshipInput.vue
This PR does remove the sortable binding if a relationship input gets destroyed.
If using the Live Preview, Statamic has memory leaks:
- Open the Live Preview
- Close the Live Preview
- Repeat multiple times
_Depending on the size of replicator fields etc, the memory usage will grow with every switch from live preview to non-live preview._
This PR is only a small part of it, but does help to reduce the leak at least a tiny little bit.
=> Destroy sortable in Relationship-Input

resources/js/components/modals/ConfirmationModal.vue
This PR does remove key bindings if closing a modal.
This PR is only a small part of it, but does help to reduce memory leaks by removing unused bindings.
=> Destroy key bindings in modal after close

resources/js/components/revision-history/History.vue
**This PR does remove key bindings if closing the revision history**
This PR is only a small part of it, but does help to reduce memory leaks by removing unused bindings.
The fastes way to reproduce:
* Open the Live Preview
* Close the Live Preview
* Repeat multiple times
=> Destroy revision history key binding after closing

resources/js/components/Popover.vue
This PR does remove the key binding after opening a popover.
_If using the Live Preview, Statamic has memory leaks:_
* Open the Live Preview
* Close the Live Preview
* Repeat multiple times
Depending on the size of replicator fields etc, the memory usage will grow with every switch from live preview to non-live preview.
As the Popover (small drop down menu with three dots) might exists multiple times (in our case about 180 times), this does make difference if editing an entry for a longer time. Every usage of the popover / dropdown does add another key binding, without removing it, which might pile up over time.
=> Remove key bindings from popover after close

resources/js/components/data-list/Table.vue, resources/js/components/inputs/relationship/RelationshipInput.vue, resources/js/components/inputs/relationship/Selector.vue, resources/sass/elements/tables.scss, src/Http/Resources/CP/Entries/ListedEntry.php, src/Http/Resources/CP/Taxonomies/ListedTerm.php
This PR adds the collection or taxonomy names to the stack selector, to make it easier to distinguish entries in different collections that have identical or similar names:
The property name "type" might be a bit generic, I'm not sure if there's a better term that would work for both collections and taxonomies?
Closes https://github.com/statamic/ideas/issues/819
=> Add collection/taxonomy names to stack selector

src/Forms/Email.php
It was removed unintentionally in #6464.
Closes #6573
=> Bring back env value parsing in form email configs

resources/js/app.js, src/Actions/DownloadAsset.php, src/Providers/ExtensionServiceProvider.php
This PR adds a "download" option to Assets. Currently, we have the feature to download Assets when you open an asset. This addition will add an option in the dropdown to download an Asset from the Assets folder navigation saving a click.
https://user-images.githubusercontent.com/17038330/187508902-3de4754d-4497-4c26-86ba-d6182f39b0e9.mov
=> Add "Download" Action to Assets

src/Modifiers/CoreModifiers.php, src/Support/Html.php, src/Support/Str.php, tests/Modifiers/MarkTest.php, tests/Modifiers/RegexMarkTest.php
This PR adds two new modifiers: `mark` and `regex_mark`.
These modifiers will wrap any matched words/phrases in `<mark>` tags, in order to highlight them on the page.
The idea behind the `mark` modifier was to highlight search queries when displaying results. For this reason it's fairly opinionated in the way it behaves:
* It will treat individual word as separate matches
* It's case-insensitive
* If no words are provided it'll use the `get:q` value from the context
The `regex_mark` modifier is more flexible, only thing it imposes is case-insensitivity.
They expect an HTML value, if you have a plain text value you should encode any special characters first using the `entities` modifier.
```yaml
value1: 'Lorem, ipsum dolor sit amet'
value2: 'Lorem, ipsum <x-amet …
```
=> Add `mark` modifiers for highlighting words in text

src/Tags/Concerns/GetsQueryResults.php
This PR adds support for the `page_name` pagination parameter in the collection tag. This parameter allows you to customise the name of the URL query parameter used for a particular paginator, from the default of `page`.
When working with Livewire components multiple components on the same page can have their own pagination, however if they all use `page` they conflict with one another. Livewire supports different parameter names for each component, this change allows you to use those with the collection tag:
```antlers
{{ collection:pages paginate="10" }} ... {{ /collection:pages }}
```
```antlers
{{ collection:posts paginate="10" page_name="postsPage" }} ... {{ /collection:posts }}
```
```
http://localhost/?page=3&postsPage=6
```
=> Support the `page_name` pagination parameter in the collection tag

src/Query/EloquentQueryBuilder.php
Everything still works the same way. The empty array was a mistake. If you were to pass an empty array or an asterisk before, you'd still end up with the behavior of passing `['*']`.
=> Make eloquent paginate columns argument default to asterisk

src/Forms/Email.php, tests/Forms/EmailTest.php, tests/Forms/SendEmailTest.php
In order for the language to be applied to the mailable, the `locale` method needs to be called _before_ `build`.
Peek under the hood: https://github.com/laravel/framework/blob/e07e00507e67c710798eb98cdb09845f65026429/src/Illuminate/Mail/Mailable.php#L194-L197
The refactor in #6464 mistakenly moved that.
Fixes #6602
=> Fix form email language

resources/js/app.js, src/Actions/DownloadAsset.php
References #6594
Our abstract action already provides a handy `download()` method, so the JS callback isn't necessary.
=> Use `download()` instead of custom JS callback in `DownloadAsset` action

src/Events/Subscriber.php, src/Git/Subscriber.php, src/Providers/EventServiceProvider.php, tests/Events/MacroTest.php, tests/Events/SubscriberTest.php, tests/Git/GitEventTest.php
This is also needed for #4832, but I'll wait for this PR to be merged first.
=> Add ability to temporarily disable and re-enable an event subscriber

src/Assets/Asset.php, tests/Assets/AssetTest.php
While working on #6585, we found a bug when trying to dump `$asset->meta()` more than once, which seemed to clear out asset meta completely (in-memory, not on the filesystem). This PR fixes meta hydration, and fleshes out test coverage around our `meta()` and `hydrate()` methods.
=> Fix asset data handling

resources/js/components/field-conditions/Omitter.js, resources/js/tests/FieldConditionsOmitter.test.js
Fixes #6611
References #6187
There's some logic in a JS class that converts a "dotted path" to a "js path" that uses braces around numeric keys...
e.g. `foo.0.bar.baz` to `foo[0].bar.baz`
However, JS considers an underscore `_` after an integer as a numeric separator, so keys like `404_text` need to be wrapped in square braces as strings in the converted js path as well...
e.g. `field.404_text.bar.baz` needs to be converted to `field["404_text"].bar.baz`
=> Fix numeric separators JS error

src/Http/Controllers/API/CollectionEntriesController.php, tests/API/APITest.php
Fixes #6119.
Supported syntax:
`?filter[taxonomy:categories]=events`
`?filter[taxonomy:categories:in]=events|bananas`
`?filter[taxonomy:categories:not_in]=apples|pears`
I am removing the taxonomy filters from the list by overriding `->getFilters()`, so they don't also get applied as regular filters in `ApiController->filter()`.
=> API: Add support for filtering entries by taxonomy terms

resources/js/components/Popover.vue
The change in #6601 caused the popper elements to remain on the screen (but invisible) which was causing the overflow pointed out in #6627.
Turns out it's necessary for the poppers to be initialized when mounted. We can't just initialize when clicking them.
This PR reverts the initialize-on-click behavior, but will make sure they are still destroyed when the component is destroyed, which should help with the memory leak that #6601 was trying to fix.
Fixes #6627
=> Fix popper causing overflow

resources/js/components/publish/Sections.vue
This is an easy way to fix #6584.
Bonus: Fixes the layout shift. Before when you had no tabs, three little dots where briefly rendered above the edit form and then disappeared, making the main and side bar panels shift upward.
=> Avoid fieldtypes getting mounted twice

resources/views/extend/forms/fields/select.antlers.html
The [documentation for select fields](https://statamic.dev/fieldtypes/select#options) says that the `placeholder` is used for the 'non-selectable placeholder text'. Currently, the value does not do anything for fieldtypes in forms. The placeholder text for those currently is hardcoded with `{{ trans key="Please select..." }}`.
I believe that the value from `placeholder` should be used instead (if available).
=> Show placeholder in form select fields

resources/js/components/fieldtypes/TextFieldtype.vue, resources/js/components/fieldtypes/assets/AssetRow.vue, resources/js/components/fieldtypes/assets/AssetTile.vue, resources/sass/components/assets.scss, src/Assets/AssetContainer.php, src/Imaging/Manager.php
First, image ratios are now properly shown in landscape and portrait orientations in Grid mode. I've added a border to each grid asset tile to help make things feel a bit tighter.
Next, added a "Set Alt" button if an image doesn't have an alt tag. Clicking it will open the Asset Editor and make sure the Alt field is autofocused. This is present in both grid and list modes.
=> Asset field improvements

src/Http/Controllers/CP/Collections/EntriesController.php
In #6353 we included the published value in order to be able to validate against it.
This was unintentionally forcibly adding it to the data. We only needed it there for validation.
This caused the problem reported in #6557.
When a revision was created, it would have that published boolean in the data, but shouldn't have.
Then when the entry is published, the `published` boolean remains in the data.
When you clear the cache, it would need to read the entry from the file, which would see that `published: false` in the data, and set it as a draft.
Fixes #6557
=> Exclude published from data when saving entries

resources/js/components/navigation/View.vue
When adding a child to a nav item the "Add child link to entry" option appears even if no collections are configured. Clicking on this results in a JS error:
This PR fixes that by removing the option if no collections are set.
Closes https://github.com/statamic/cms/issues/4201
=> Fix 'Add child link to entry' appearing when no collection is set

resources/js/components/publish/Sections.vue
I noticed a JavaScript error when resizing edit pages in the new version, probably introduced by #6632. The error says "TypeError: Cannot read properties of undefined (reading 'childNodes')". This PR fixes that.
=> Fix JavaScript error when resizing edit pages

src/Facades/Endpoint/URL.php, tests/Facades/UrlTest.php
An a tag with a blank href will link back to the same page (likewise for form actions), so I don't think blank URLs should be considered external. This PR fixes that.
=> Fix blank URLs being flagged as external

resources/js/components/data-list/HasActions.js
There's a JS error in the console when you download assets because `response` is undefined.
This PR fixes that.
=> Fix JS error when downloading assets

src/Http/Controllers/CP/Navigation/NavigationController.php
This PR adds the missing "view" authorisation check on the CP navigation show method
Fixes: #6653
=> Add missing view nav authorization

resources/js/components/assets/Browser/Browser.vue, routes/cp.php, src/Http/Controllers/CP/Assets/BrowserController.php, tests/Feature/Assets/BrowserTest.php
Fixes #6275.
Pretty straightforward. I have one thing I am not sure about though. In `BrowserController@search`, will it be okay to add the where clause `$query->where('folder', $path)` when a search index is used?
=> Asset Browser: Optionally restrict the search to a single folder

src/Fieldtypes/Date.php
If `time_enabled: true` without `mode` explicitly being set to `single`, then date will be stripped of its time component.
=> Fix date field default format not including time when mode isnt explicitly set

resources/js/components/structures/Branch.vue, src/Http/Controllers/CP/Collections/CollectionTreeController.php, src/Structures/Tree.php
This fixes #4453.
It may fix #3791 too, although I had trouble reproducing that one in the first place.
- The changes in `Tree->move()` fix 4453 
- The changes in `CollectionTreeController->update()` prevent any deleted pages from staying in the tree file afterwards (this issue was not reported)
- The changes in `Branch.vue` make sure that any orphaned children are moved up one level "in place", instead of moving them to the bottom of the list.
=> Fix deleting an entry with children from the tree view

tests/Data/AugmentedTestCase.php, tests/Data/Structures/AugmentedPageTest.php
We have an assertion helper to help test augmentation values. I noticed it was behaving incorrectly when reviewing #6666.
When you tried to assert that a value is `null`, it was essentially being skipped. This is because we were using isset instead of array_key_exists. If the value was null, it didn't pass the condition, so basically nothing happens.
There's one place where this was being used, and has been updated.
```php
'entry_id' => ['type' => 'string', 'value' => null],
```
The mock was returning false, which should have caused the test to fail. When adjusting the assertion, it started to fail, showing that the mock was returning the wrong value - it should have been null.
=> Fix augmentation test

resources/js/components/Popover.vue
There's a bug in Popover.vue which can occur in an entry edit page while resizing the window: "TypeError: Cannot read properties of null (reading 'destroy')". This fixes that.
=> Fix JavaScript error in Popover when resizing

src/Search/Tags.php
This PR allows you to override the search query _value_ used in the `{{ search:results }}` tag (not the query parameter name).
Not sure if `value` is the right name, `query` would probably be better but that's already taken. Maybe `q` could work?
I've written a spellcheck modifier that I want to use to correct spelling mistakes in search queries before they're run, but at the moment it's not possible to get the corrected query string into the search tag as it will only read a value from the request. 
This PR would allow you to do:
```antlers
{{ search:results :for="get:q | spellcheck" }}
```
=> Ability to override search:results tag query value

CHANGELOG.md, src/Data/AbstractAugmented.php, src/Data/ContainsSupplementalData.php, src/Http/Controllers/CP/Collections/EntriesController.php, tests/Data/AugmentedTest.php, tests/Data/Entries/EntryTest.php
Fixes #6002.
Live Preview supplements the saved entry data with the current values in the edit form. Right now supplementing with `null` (the value for an empty field) will be interpreted as "there is no supplement, let's use the original value".
To check if there is a supplemental value (possibly null) for a key, I added the `->hasSupplement($key)` method to the`ContainsSupplementalData` trait.
For convenience I also added a `$fallback` parameter to `->getSupplement()`. If that is not cool, we can just do the `->hasSupplement()` check in `AbstractAugmented->getFromData()` instead.
=> Distinguish between a missing and a `null` supplemental value

resources/sass/components/fieldtypes/bard.scss
Lists are valid inside tables and blockquotes, and Bard allows you to add them. Everything works fine except they have no styling due to the CSS only targeting lists that are a direct descendant of the editor.
This PR fixes that.
I didn't add any bottom margin to the lists inside tables as paragraphs dont have any either.
Related to https://github.com/statamic/cms/pull/6315, that fixed tables inside lists.
=> Fix styling of lists inside tables and blockquotes in bard fields

resources/js/components/publish/Sections.vue
While working on some bugs in `Sections.vue`, I improved the readability for myself by rearranging (and removing) some code and adding some comments. I also noticed a lot of unnecessary re-renders (5-10 times per second when resizing) which made things a bit 'heavy'. I cut those out too and ended up simplifying the visibleTabs mechanism. Here's a PR with those improvements.
=> Improve performance and readability of `Sections.vue`

resources/js/components/fieldtypes/DateFieldtype.vue
In #6651 I noticed that the day was showing up incorrectly.
e.g. My entry's date was 1996-11-18 but the fieldtype rendered it as 1996-11-17
This is because when you pass a date-only string into `new Date` (which the date component does) then it'll assume you mean UTC. That's why the day turned a little wonky.
If you pass a time into `new Date`, then it'll assume local time, and is why it worked before.
But, it didn't work in Safari, probably because the format was wrong. Looking at the [MDN Date docs page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date), it explains that the time string should have a T in it. `"1970-01-01T12:00"`. Swapping the space for a T fixes it.
=> Adjust date picker value format
