README.md
Looks like the same update needs to be made here too 😃
=> Fix application repo link

resources/js/components/fieldtypes/DateFieldtype.vue
=> Fix double outline when Date field has focus

resources/js/components/inputs/relationship/Selector.vue
=> use cancel tokens in relationship selector to handle filter changes

resources/views/fields/index.blade.php
=> Add Docs URLs to "fields" page

resources/js/components/field-validation/Builder.vue
=> 🐛 Support laravel minor version greater than 9 in validations

src/Providers/AuthServiceProvider.php
=> Only apply gates when a Statamic user is present.

resources/js/components/inputs/Text.vue
That would be extra handy for small numbers or currencies.
=> Making the step attribute available in input fields

src/Tags/Tags.php
Need tags to be able to set the `method`
I didn't see where you have the tests for Tags, so I didn't make one. Let me know if you want me to make one.
=> formOpen can set method

src/Tags/Tags.php
Sorry you merged before I could fix this.
=> Use form method helper

resources/js/components/field-conditions/Constants.js, resources/js/components/field-conditions/Validator.js, resources/js/tests/FieldConditionsValidator.test.js
=> Improve custom field conditions

resources/lang/en/fieldtypes.php
Correcting two typos as described in #1688 
Not much, but maybe still helpfull
=> Correct Typos in Fieldtype.php

src/Console/Commands/MakeFieldtype.php
=> Add `--php` option to the `make:fieldtypes` command.

src/Console/Commands/MakeAction.php, src/Console/Commands/stubs/action.php.stub, src/Providers/ConsoleServiceProvider.php, tests/Console/ExtensionGeneratorTest.php
=> Add `make:action` to the please command.

src/View/Cascade.php, tests/FrontendTest.php, tests/View/CascadeTest.php
=> Site variables as an array

resources/sass/components/fieldtypes/replicator.scss
Closes #1968
**Right now**
**This PR does change it to**
=> Fix spacing for the »add set« button on the replicator fieldset

resources/js/components/blueprints/Builder.vue, resources/js/components/field-conditions/Converter.js, resources/js/components/fieldtypes/bard/Image.js, resources/js/components/fieldtypes/bard/RemoveFormat.js
I used eslint in conjunction with the [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports) plugin to detect those.
=> Remove unused imports

resources/lang/en/messages.php
=> Fix the typo Create Asset Container

src/Forms/Uploaders/AssetUploader.php
=> Fix fetching of Asset container in forms uploader

resources/js/components/entries/PublishForm.vue, resources/js/components/terms/PublishForm.vue, src/Http/Controllers/CP/Collections/EntriesController.php, src/Http/Controllers/CP/Taxonomies/TermsController.php, src/Taxonomies/LocalizedTerm.php
=> Ability to switch blueprints

resources/sass/components/fieldtypes/replicator.scss
=> Make images inline in the replicator preview

resources/js/components/fieldtypes/ButtonGroupFieldtype.vue
This looks like a bug. Correct me if I'm wrong.
=> Fix closing tag in Button Fieldtype

resources/lang/de-CH.json, resources/lang/de.json, resources/lang/es.json, resources/lang/fr.json, resources/lang/it.json, resources/lang/nl.json, resources/lang/pt.json
This has been pointed out as a bug and would partially fix:
https://github.com/statamic/cms/issues/1662
=> Add Target Blank translation to json lang files

src/Forms/Email.php
This pull request contains a small improvement to the emails that forms sent when they are submitted. It would allow developers to use data from Global Sets inside their email templates.
One use case for this could be that a developer wants to include an email or social media link in the 'Thank you' email after submitting a contact form.
This pull request lets developers use globals in the same way they can if it was a page on their site where the data comes from the Cascade. 
```
Thank you for your submission! We will respond soon. In the mean time, checkout our Facebook profile: {{ social:facebook }}
```
I've tested this and it seems to work well. I copied the code from the `hydrateGlobals` method on the Cascade. The only thing I didn't copy was the 'main global' part. I've never seen …
=> Add Global Data to form emails

resources/js/components/data-list/Action.vue
=> if action doesn’t need to be confirmed, run it (Closes #1497)

src/Fields/Blueprint.php, tests/Fields/BlueprintTest.php
Need to ensure a section is removed to fix https://github.com/statamic/seo-pro/issues/108.  We already have `ensureField()`, `removeField()`, `ensureFieldInSection()`, `removeFieldInSection()`, etc… Just don’t have `removeSection()` yet.
=> Add ability to blueprint section

src/Fieldtypes/Markdown.php, tests/Fieldtypes/MarkdownTest.php
=> null should return null (#2502)

src/Modifiers/CoreModifiers.php
Just had a use for one, thought it might be useful to have in core
=> Add an md5 modifier

resources/lang/nl.json, resources/lang/nl/messages.php
=> Human Dutch translations for 3.0.17

src/Exceptions/ArrayKeyNotFoundException.php, src/View/Antlers/ArrayKeyNotFoundException.php, src/View/Antlers/Parser.php, tests/View/Antlers/ParserTest.php
Unfortunately, as great a contribution as #1983 was, it introduced some gnarly bugs.
This PR adds tests for them, and ~(at the moment) reverts~ fixes the array access stuff.
~I'm going to have a go at re-implementing it. If I can't work it out in a reasonable amount of time, the existing broken conditional bugs are more important than this very new undocumented feature.~
Fixes #1193 
Fixes #2614 
Fixes #2537 
Fixes #2456
=> Fix Antlers Array Access

src/Http/Controllers/CP/ActionController.php
Reopen of https://github.com/statamic/cms/pull/2736
=> Action download - Use Symfony\Component\HttpFoundation\Response

composer.json, tests/Query/BuilderTest.php
Resolves https://github.com/statamic/cms/issues/2732
=> Make tests compatible with psr-4

src/Modifiers/CoreModifiers.php
This fixes the shuffle modifier for collections
=> Make shuffle work for collections

src/Tags/Assets.php
This PR adds a new `collection`, `fields`, and `type` parameter to the assets tag.
Use the `collection` parameter to get assets from a specific collection instead of a container:
```html
{{ assets collection="pages" }}
// All assets from the `pages` collection
{{ /assets }}
```
Use the `fields` parameter to filter assets by their field handle. You can pass multiple values separated with a pipe.
```html
{{ assets collection="pages" fields="images|videos" }}
// All assets from the `images` and `videos` field in the `pages` collection
{{ /assets }}
```
Use the `type` parameter to filter assets by their type. Supported values are `image`, `svg`, and `video`. This parameter works with both the `container` and `collection` parameter.
```html
{{ assets container="assets" type="image" }}
// All …
```
=> Enhance Assets Tag

src/Assets/Asset.php, tests/Assets/AssetTest.php
Closes #2831
Closes #2840
References #2834
References #2836
=> Fix cached asset meta

src/Forms/Email.php
Simple pull request that makes configs accessible in email views.
It can be useful to access info such as the app url defined in the .env file for example.
=> Make config variables available in email views

src/Tags/Concerns/RendersAttributes.php, tests/Tags/Concerns/RendersAttributesTest.php
This PR fixes https://github.com/statamic/cms/issues/2844. This is my first PR and I would like to get some feedback if I have overseen something by changing the renderAttributes function to render falsy values.
=> Render attributes whose value is false

src/Events/UserRegistered.php, src/Http/Controllers/UserController.php, tests/Feature/Users/UserRegistrationTest.php
Mailchimp, as well as an upcoming project need to "do stuff" when a user is registered.
Added test as well.
Closes #2395
=> add UserRegistered event

src/Http/Controllers/CP/SearchController.php, tests/Feature/GlobalSearch/GlobalSearchTest.php
=> Filter CP search results by permission

resources/js/components/fieldtypes/replicator/Replicator.vue, resources/lang/en/fieldtypes.php, src/Fieldtypes/Replicator.php
Closes https://github.com/statamic/ideas/issues/245.
I can't seem to shrink the `Listable` field to make it `33`, so I made `collapse` and `max_sets` both `25%`, which I don't really like. Feel free to re-organize.
=> add max sets (statamic/ideas/issues/245)

resources/lang/pt.json
Better definition for **placeholder**
=> corrections

src/Contracts/Forms/Submission.php
Discovered this during a source dive - aware it's a very minimal PR.
=> Fix typo in Submission.php

resources/js/components/assets/Folder/Folder.vue, resources/js/components/structures/PageEditor.vue
This PR fixes #1794. It also fixes the same issue in one other component.
=> Fix keyboard shortcut bindings

resources/lang/de-CH.json, resources/lang/de.json
Added a more understandable german translation for publish date
=> Enhance german translation

src/Tags/Nav.php
Not sure if this is how you want to fix this, but it has worked in my testing
Fixes #1618
=> Fix breadcrumbs not rendering properly when not including home

resources/js/components/fieldtypes/grid/Grid.vue, resources/js/components/fieldtypes/grid/Row.vue, resources/js/components/fieldtypes/grid/Stacked.vue, resources/js/components/fieldtypes/grid/Table.vue, resources/js/components/fieldtypes/grid/View.vue
=> Hide Duplicate Row button when max grid rows reached

src/Facades/Term.php
The method were missing the return type hint so intellisense was complaining.
=> update method signatures

src/Tags/Locales.php
This is useful for conditions to decide if you want to display a translations list or not.
```
{{ if locales:count > 1 }}
{{ /if }}
```
=> Add a count method to locales to help with conditional logic

src/Entries/Collection.php, src/Events/CollectionCreated.php, src/Http/Controllers/CP/Collections/CollectionsController.php, tests/Data/Entries/CollectionTest.php
As per https://github.com/statamic/cms/pull/3037#issuecomment-749769296, put the dispatching in the collection.
Added test.
=> Collection created event

src/Fieldtypes/Bard.php, src/Fieldtypes/Replicator.php
=> Remove null values from bard and replicator

src/Structures/Tree.php, tests/Data/Structures/TreeTest.php
=> Prevent unnecessary moving of pages

src/Modifiers/CoreModifiers.php
Add support for Laravel Ray via the `ray` modifier.
Use like `dump`, for example, `{{ foo | ray }}`
=> add `ray` modifier

resources/views/forms/widget.blade.php
Updated the styling to look consistent with the collection widget. The current version is using classes that are not defined anywhere resulting is a inconsistent look, especially if you display multi-field form.
Please see the before and after screenshots:
**Before**:
**After**:
=> Update widget.blade.php look

.github/workflows/tests.yml
Just use Composer 2 as it's stable now. Having the whole test suite repeated for v1 is a waste of time.
=> Adjust Composer in test suite

src/Tags/Trans.php
Just stumbled upon this and it is bugging me.
=> Use local $params in Trans-Tag

src/Forms/Submission.php
=> Use more data when augmenting a form submission

resources/js/components/fieldtypes/DateFieldtype.vue, src/Fieldtypes/Date.php
=> Use the date string in the range values rather than Date objects

src/Forms/Email.php
=> Id and date aren't fields

src/View/Antlers/Parser.php, src/View/Cascade.php, tests/View/Antlers/EngineTest.php, tests/View/Antlers/ViewTest.php, tests/View/Antlers/fixtures/partial-with-front-matter.antlers.html
=> Put front matter view data into the context so its available to tags

resources/js/components/fieldtypes/ArrayFieldtype.vue
=> Handle null labels correctly in the array fieldtype

resources/views/entries/create.blade.php
=> Include parent in create another url for entries

src/Fieldtypes/Terms.php
=> Localize terms in the control panel

resources/js/components/fieldtypes/SelectFieldtype.vue, resources/sass/vendors/vue-select.scss
=> Disable deleting options for a select in readonly mode

src/Tags/Collection/Entries.php
=> Filter a collection by a single taxonomy term taken from the context

resources/sass/components/fieldtypes/bard.scss
Fixes #3230 and some other minor issues with the fixed Bard toolbar.
=> Enable fixed toolbar on a Bard field inside a set

routes/api.php, src/Http/Controllers/API/FormsController.php, src/Http/Resources/API/FormResource.php, src/Http/Resources/API/Resource.php
Adds ```GET /api/forms``` and ```GET /api/forms/{handle}```.
=> [3.1] Add an API endpoint for forms

src/Tags/Glide.php
=> Use the SVG smartness in glide tag pairs too

src/Entries/Collection.php, tests/Data/Entries/CollectionTest.php
=> Default to non-hidden entry blueprint

src/Fieldtypes/Entries.php, src/Fieldtypes/Relationship.php, src/Modifiers/CoreModifiers.php
=> Adds ability to sort DataCollection objects with the sort modifier. References #3194

resources/views/partials/nav-main.blade.php, src/CP/Navigation/CoreNav.php, src/CP/Navigation/NavItem.php
=> Support setting HTML attributes on NavItems

src/Facades/Markdown.php
Hiya 👋  Very very tiny PR this time (honestly I don't know how it could be smaller) but it causes PHPStorm to be very unhappy otherwise. 😅
=> Fix wrong Closure typehint

composer.json
https://github.com/laravel/framework/security/advisories/GHSA-x7p5-p2c9-phvg
=> Require laravel/framework versions with security patches

src/Modifiers/CoreModifiers.php
=> Get value from ArrayableString before applying markdown modifier

resources/views/partials/head.blade.php, src/Providers/AddonServiceProvider.php, src/Statamic.php
Implements [idea #430](https://github.com/statamic/ideas/issues/430).
=> Add an external stylesheet from an addon

resources/js/components/structures/Branch.vue, src/Structures/TreeBuilder.php
=> Show published status in tree view

src/Assets/Asset.php
=> Do urldecode on asset filename before saving

resources/js/components/assets/Browser/Breadcrumbs.vue, resources/js/components/assets/Browser/Browser.vue
Fixes #1927.
Based on code that was already there as work in progress.
=> Add breadcrumbs to asset browser

resources/js/components/assets/Editor/Editor.vue
=> Respect allow-deleting prop in asset editor

src/Facades/Endpoint/URL.php
Fixes an issue getting pages to render with Laravel Octane
=> Use request helper instead of server variables

resources/js/components/publish/Field.vue
=> Don't show 'read only' and translation icons on sections

resources/js/components/fieldtypes/TimeFieldtype.vue
Fixes #2920.
It fixes the NaN thing and some other little glitches, for example before you could enter values like 59999 or 45555 without it being corrected visually.
=> Fix NaN and other glitches in the Time fieldtype

src/Http/Controllers/CP/Collections/EntriesController.php
=> Preserve user defined defaults for new entries

src/Tags/Structure.php
=> Add max_depth parameter to Nav tag

resources/js/components/entries/PublishForm.vue, resources/js/components/terms/PublishForm.vue
Fixes #3236 ~and fixes #3173~.
=> Add extra visual hints to multi-site toggle

src/Http/Controllers/CP/Collections/EntryPreviewController.php
=> Use correct site and locale in Live Preview

resources/js/components/fieldtypes/bard/Image.vue
=> Display images in Bard editor when the content is saved as HTML

resources/js/components/collections/Routes.vue, src/Http/Controllers/CP/Collections/CollectionsController.php
Fixes #2447.
It also fixes #3580 which was closed as a partial duplicate of #3500.
=> Configure collection: fix disappearing routes and incorrect dirty state

src/Actions/Delete.php
Fixes #3565 as suggested by @rrelmy 😄
=> Enable delete action for asset folder

src/Modifiers/CoreModifiers.php, tests/Modifiers/SentenceListTest.php
As per [this comment](https://github.com/statamic/cms/pull/3502#issuecomment-826403685)
Also adds tests.
=> Support collections in the `sentence_list` modifier

src/Http/Controllers/UserController.php
=> Remember old input values in user registration form

src/View/View.php
=> Reuse cascade on subsequent calls rather than rehydrating

src/Modifiers/CoreModifiers.php, tests/Modifiers/OptionListTest.php
Following the example of the [sentence_list modifier](https://github.com/statamic/cms/pull/3593). 
This is my first test ever... Hope it is ok.
=> Support collections in the option_list modifier

resources/js/components/fieldtypes/LinkFieldtype.vue
Fixes #1928 and fixes #3500. 
* Removes the toggle and adds a 'None' option instead.
* Entered info is remembered when switching back and forth between options.
* Fixes incorrect dirty state. --> I believe all reported cases in #3500 are solved now. The link field is in the second screenshot (*Erster Untereintrag* is a translation of the First Child option).
=> Friendlify link fieldtype

resources/lang/de/permissions.php, resources/lang/de_CH/permissions.php
=> Fix german translation typo

resources/js/components/fieldtypes/LinkFieldtype.vue
=> Link fieldtype: display URL value on page refresh

src/Tags/TransChoice.php
=> Fix trans_choice Tag

resources/views/extend/forms/fields/assets.antlers.html, resources/views/extend/forms/fields/checkboxes.antlers.html, resources/views/extend/forms/fields/default.antlers.html, resources/views/extend/forms/fields/radio.antlers.html, resources/views/extend/forms/fields/select.antlers.html, resources/views/extend/forms/fields/text.antlers.html, resources/views/extend/forms/fields/textarea.antlers.html, tests/Tags/Form/FormCreateTest.php, tests/Tags/User/RegisterFormTest.php
=> add required attribute

src/Fieldtypes/Bard.php
See [this comment](https://github.com/statamic/cms/issues/2199#issuecomment-834100881) in #2199.
=> Choose an asset container for links or images

src/Fieldtypes/Bard.php
=> Bard: fix error when linked entries and assets are deleted

resources/sass/components/tabs.scss
=> Lower active tab z-index

src/Fieldtypes/Entries.php, tests/Fieldtypes/EntriesTest.php
=> Entries fieldtype: filter out unpublished entries when augmenting

resources/js/components/fieldtypes/bard/LinkToolbar.vue
Implements [idea #548](https://github.com/statamic/ideas/issues/548).
=> Autofocus the URL input when creating a link in Bard

src/View/Antlers/Parser.php, tests/View/Antlers/ParserTest.php
=> Fix modifier not working with dynamic array keys

src/Console/Composer/Lock.php, src/Console/Processes/Composer.php, src/Providers/ExtensionServiceProvider.php, src/Tags/Installed.php, tests/Composer/ComposerLockTest.php, tests/Composer/ComposerTest.php, tests/Tags/InstalledTest.php
Can be used as tag pair:
```
{{ installed:foo/bar }}
...
{{ /installed:foo/bar }}
```
Or as boolean within `if` condition.
```
{{ if {installed:foo/bar} }}
...
{{ /if }}
```
=> `installed` tag

src/Fields/Validator.php
=> Only parse string based validation rules

src/Entries/GetSuffixFromPath.php, src/Entries/RemoveSuffixFromPath.php, src/Stache/Stores/CollectionEntriesStore.php, tests/Data/Entries/GetDateFromPathTest.php, tests/Data/Entries/GetSlugFromPathTest.php, tests/Data/Entries/GetSuffixFromPathTest.php, tests/Data/Entries/RemoveSuffixFromPathTest.php, tests/Stache/Stores/EntriesStoreTest.php
=> Fix entry slug or date changes not being reflected in filename

resources/js/components/data-list/Table.vue
Closes https://github.com/statamic/ideas/issues/553
=> Add width attribute to DataListTable component

resources/views/fieldsets/index.blade.php
=> remove create fieldset permission check

src/Console/Processes/Git.php, src/Console/Processes/Process.php, src/Git/Git.php, tests/Console/ProcessTest.php, tests/Git/GitProcessTest.php, tests/Git/GitTest.php
=> Fix git status checks on symlinked git paths

src/Taxonomies/Taxonomy.php
Missing the `use` statement for this.
=> Missing Search class

src/Fieldtypes/Entries.php, src/Http/Controllers/CP/Collections/CollectionsController.php
Same as #3845 but with an extra commit. I couldn't pull down the branch for some reason.
Closes #3845 
Fixes #3844
=> Don't assume the first collection has array key 0

src/Entries/Entry.php, src/Http/Controllers/CP/Collections/EntriesController.php, src/Routing/Routable.php, tests/Data/Entries/EntryTest.php
=> Entries without routes shouldn't have URIs at all

resources/js/components/fieldtypes/grid/Cell.vue
=> Hook up the grid field width setting

src/Assets/AssetRepository.php, tests/Assets/AssetRepositoryTest.php
Fixes https://github.com/statamic/cms/issues/3836
=> Fix wrong AssetContainer being resolved by url

src/Fieldtypes/Terms.php
This fixes #3228 and fixes #3154.
=> Always save taxonomy terms as a file

src/StaticCaching/Invalidate.php
=> Static caching: invalidate Nav when its tree is edited

src/StaticCaching/DefaultInvalidator.php, src/StaticCaching/Invalidate.php
=> Static caching: invalidate collection URL after reordering collection

resources/js/components/inputs/Text.vue
Helps with autofocus in popups. Fixes #3840.
=> Apply focus on text input

src/View/View.php, tests/View/Antlers/ViewTest.php
This aims to bring some additional functionality from Laravel's View class into Statamic's
```php
Statamic\View\View::exists($dynamicViewName);
Statamic\View\View::first([$dynamicViewName, 'fallbackView'])
```
It also updates the Make and With functions to behave more like Laravel's
```php
$view = Statamic\View\View::make('contact', ['address' => '42 Wallaby Way, Sydney'], ['name' => 'E Blurman']);
$view->data();
// Address: 42 Wallaby Way, Sydney
// Name: E Blurman
$view->with(['name' => 'P Sherman']); // Or $view->with('name', 'P Sherman');
$view->data();
// Address: 42 Wallaby Way, Sydney
// Name: P Sherman
```
=> Feature/extend view class (Add First/Exists, adjust Make/With)

src/StaticCaching/DefaultInvalidator.php, tests/StaticCaching/DefaultInvalidatorTest.php
=> Static caching: invalidate term url within collections

resources/js/components/inputs/relationship/RelationshipInput.vue, src/Fieldtypes/Entries.php
=> Entires fieldtype: check permissions for Create & Link Item button

src/Stache/Indexes/Index.php
This is #3931 but against the 3.1 branch.
=> Update a Stache index only when it hasn't been cached

src/Search/Tags.php
=> Fix search tag when the as param is used without paginate

src/Stache/Stores/CollectionTreeStore.php, tests/Stache/Stores/CollectionTreeStoreTest.php
As [suggested](https://github.com/statamic/cms/pull/3902#issuecomment-872314038) by Jason in the discussion at PR #3902.
=> Have CollectionTreeStore ignore trees without a matching collection

resources/sass/components/fieldtypes/bard.scss
=> Fix Live Preview toolbar covering Bard toolbar

src/Assets/AssetRepository.php
=> Generate asset meta after updating the container contents

resources/views/navigation/index.blade.php
=> Fix create navigation button policy check

resources/sass/components/assets.scss
=> Revert css change in Asset Editor

resources/js/components/publish/Sections.vue, resources/sass/components/tabs.scss
Closes #1050 and partially addresses #3556 while we're at it.
Video of it in action: <https://d.pr/v/HWRnEG>
=> Tabs now overflow into a dropdown when there's no more room

src/GraphQL/Queries/EntryQuery.php, tests/Feature/GraphQL/EntryTest.php
=> Support querying individual entries in a specific site using GraphQL

resources/js/components/fieldtypes/bard/BardFieldtype.vue
=> Hide 'Add Set' button in Bard field when there are no sets

src/Assets/Dimensions.php, src/GraphQL/Types/AssetInterface.php
=> Use float instead of int for image dimensions

src/Auth/User.php
Used in Laravel's Notifications when you pass a collection of users
Fixes https://github.com/statamic/ideas/issues/623
=> add getKey method

resources/js/components/fieldtypes/VideoFieldtype.vue, src/Fieldtypes/Video.php
Replaces #4161 but targets the `3.1` branch.
=> Allow overriding video fieldtype placeholder

src/Fieldtypes/Bard.php, src/Fieldtypes/Concerns/ResolvesStatamicUrls.php, tests/Fieldtypes/BardTest.php
=> Prevent error when augmenting empty bard field and saving html

src/Console/Processes/Process.php
=> Add more environment variables, mainly for Windows.

src/Tags/Structure.php
Just like the Collection, Taxonomy and Search tags have. Very useful in some cases.
=> Add count and index variables to Nav tag

resources/js/components/blueprints/ImportField.vue, resources/js/components/data-list/Filters.vue, resources/js/components/field-conditions/Builder.vue
Some icons are scaling up after the 3.2.6 update. Added dimensions and some minor formatting to a couple we encountered.
=> Add dimensions to icons

src/Fields/Fields.php
Fixes statamic/ssg#69
What was happening was the fields were getting blinked which is good, but when another entry used that same blueprint, it would have the first entry attached.
The diff of this PR makes it look like a lot has changed.
Essentially everything got moved into a `Blink::once()` closure instead of using a `Blink::has()` guard. It was probably done that way to avoid a funky diff initially. The only difference is that `->each->setParent($this->parent)->all();` on line 228 was moved outside of the blink so it happens on every call to `getImportedFields`.
=> Set the field's parent item/entry outside the blink

src/Modifiers/CoreModifiers.php
=> Add a new modifier to get translated Carbon dates

resources/views/extend/forms/fields/checkboxes.antlers.html, resources/views/extend/forms/fields/default.antlers.html, resources/views/extend/forms/fields/radio.antlers.html, resources/views/extend/forms/fields/select.antlers.html, resources/views/extend/forms/fields/text.antlers.html, resources/views/extend/forms/fields/textarea.antlers.html, tests/Tags/Form/FormCreateTest.php, tests/Tags/User/RegisterFormTest.php
Replaces https://github.com/statamic/cms/pull/4242 with support on all fieldtypes, not just text.
=> Support default on all applicable form inputs

src/Statamic.php, tests/StatamicTest.php
=> Adjust isCpRoute

src/Facades/GraphQL.php
Delving into GraphQL land and realised this facade didn't have a docblock so I added one.
=> Improve IDE completion of `GraphQL` facade

src/Tags/ParentTags.php, tests/Tags/ParentTest.php
=> Fix parent tag regression

src/Modifiers/CoreModifiers.php, tests/Modifiers/PluckTest.php
=> make pluck modifier work with array/collection of arrays

resources/js/components/fieldtypes/assets/AssetRow.vue
=> Add dimensions to trash icon

resources/lang/en/messages.php, resources/views/collections/empty.blade.php
=> Move the docs link to the footer and add link to manage Blueprints.

resources/js/components/fieldtypes/DateFieldtype.vue, resources/lang/en/fieldtypes.php, src/Fieldtypes/Date.php
=> Actually hook up earliest_date (and add latest_date while we're at it)

src/Fieldtypes/Replicator.php
=> Fix bard field validation when nested inside replicators

resources/js/components/fieldtypes/grid/StackedRow.vue, src/Fieldtypes/Grid.php
=> Fix validation on nested fields within grids

resources/lang/nl/fieldtypes.php
=> Update Dutch translations

resources/sass/elements/buttons.scss, resources/views/utilities/cache.blade.php, src/CP/Utilities/CoreUtilities.php, src/Http/Controllers/CP/Utilities/CacheController.php
=> Warm stache utility

src/Http/Controllers/CP/Collections/CollectionsController.php
=> Show a more helpful error if someone hides all blueprints for a collection

src/Fieldtypes/HasSelectOptions.php, tests/Fieldtypes/LabeledValueTests.php, tests/Fieldtypes/MultipleLabeledValueTests.php
=> Fix error on select (etc) field when there are no options

resources/js/components/inputs/relationship/RelationshipInput.vue
=> Add spacing

resources/js/components/fieldtypes/RangeFieldtype.vue
Closes #4701.
Added watch to update field when site switches.
Note that when the site is changed there's now an "unsaved data" warning, not sure how to fix that, sorry.
=> Update range field when site changes

src/Assets/Asset.php, src/Contracts/Assets/Asset.php, src/Http/Controllers/CP/Assets/AssetsController.php, tests/Assets/AssetTest.php
Adding a helper method to make it nice to download an asset.
=> Add `download` method to Asset

src/Auth/Protect/Protectors/Password/Controller.php
=> Use Statamic view on password protect page so that cascade data is included

resources/js/components/publish/Sections.vue
This pushes a hash of the current #tab to the URL so you can link to a specific tab or refresh the page and stay where you are. Resolves statamic/ideas#102.
=> Preserve/Link Section Tabs

src/Http/Controllers/FormController.php
=> Return default site when site not found in FormController

tests/Feature/Entries/EditEntryTest.php, tests/Feature/Entries/StoreEntryTest.php, tests/Feature/Entries/UpdateEntryTest.php
I plan to add a test or two in #4667.
This PR just removes the outdated test code in here, which was being skipped anyway. In the future when the tests are filled out, the diffs will be easier to grok.
=> Remove unused tests

src/Modifiers/CoreModifiers.php
It seems like everything else has been included except this one, so hopefully it can be added too. If this change is accepted, I'll make a PR for updating it in the docs too.
=> Added support for Carbon's isTomorrrow

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
=> Fix read-only mode on grid solo assets

resources/js/components/publish/Field.vue
This PR fixes the jumpy origin sync button.
**Before the fix:**
https://user-images.githubusercontent.com/23167701/143403384-a5df38a2-bc0d-40d8-8d19-44a1ec69ac33.mov
**After the fix:**
https://user-images.githubusercontent.com/23167701/143403389-9f9b17c7-ad67-40b6-ac42-f4369a9a2dcd.mov
=> Fix jumpy origin sync button

resources/js/components/publish/Sections.vue
=> Fix publish tabs FOUS

resources/js/components/data-list/Actions.js
=> Fix action downloading file not being completed in control panel

tests/Feature/GraphQL/AssetTest.php
This adds a test for querying custom fields on an asset.
See #4831
=> Add GraphQL query test

src/View/Cascade.php, tests/FrontendTest.php, tests/View/CascadeTest.php
As suggested in https://github.com/statamic/cms/pull/4854#issuecomment-990325828
=> Add current_user to the cascade

resources/js/components/fields/FieldtypeSelector.vue
Just a little refactor and tidying up.
=> Fieldtype picker tweaks

src/Http/Controllers/CP/Collections/EntryRevisionsController.php
=> Fix viewing revision

src/Data/AbstractAugmented.php, src/Data/AugmentedData.php
Reduces unnecessary overhead - related to statamic/ideas#543
=> Sped up augmentation by caching blueprint fields

src/Stache/Stores/CollectionTreeStore.php
=> Fix reordering in a collection ending with the word collection

src/View/Cascade.php, tests/Modifiers/GroupByTest.php, tests/View/CascadeTest.php
Closes https://github.com/statamic/ideas/issues/682
=> add `is_homepage` to cascade

resources/lang/da/messages.php, resources/lang/de/messages.php, resources/lang/de_CH/messages.php, resources/lang/en/messages.php, resources/lang/es/messages.php, resources/lang/fr/messages.php, resources/lang/id/messages.php, resources/lang/nl/messages.php, resources/lang/pt/messages.php, resources/lang/sl/messages.php, resources/lang/zh_TW/messages.php
This PR changes some strings. Someone who is fluid in other supported languages may have a look.
Closes statamic/docs#663
Closes statamic/ideas#719
=> Add link to documentation next to the route config in Collection edit view

src/Http/Controllers/UserController.php
Fixes #4908. 
Logic borrowed from `Statamic\Http\Controllers\UserController`.
=> Add login throttling to `user:login_form`

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/js/components/fieldtypes/grid/Grid.vue
Fixes #4245
See also dev notes in #4997 for some background info.
=> Avoid 'illegal' store state mutations in Grid and AssetFieldtype

src/Assets/Asset.php, tests/Assets/AssetTest.php
=> Fix removing asset meta data

resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/Set.vue
Fixes #4996 and fixes #4997 without breaking #4774.
=> Fix state mutations in Replicator

resources/js/components/entries/PublishForm.vue
=> Wait 151ms before saving so debounced fieldtype updates can finish.

src/Http/Resources/CP/Taxonomies/Term.php
=> Redirect to edit page after saving created term

src/Providers/AppServiceProvider.php
=> Replaces the hardcoded path to resources/lang with function

resources/js/components/fieldtypes/grid/ManagesRowMeta.js
Fixes #5050
This is similar to what's been done in #5031.
=> Update meta without accidentally modifying object

resources/sass/components/fieldtypes/bard.scss
Closes #4666 
With the fix applied
=> Remove min height from nested bard fields inside bard in fullscreen mode

config/api.php, src/Data/AbstractAugmented.php, tests/API/APITest.php
=> Ability to disable certain fields in API

src/Http/Controllers/CP/Fields/FieldsController.php
=> Add 'type' to the list of reserved words

resources/js/components/fieldtypes/replicator/Replicator.vue
=> Add new Replicator set at the clicked position

resources/js/components/fieldtypes/IntegerFieldtype.vue, resources/js/components/inputs/Text.vue, src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Integer.php, src/Fieldtypes/Relationship.php, src/Fieldtypes/Select.php, src/Fieldtypes/Users.php, src/Forms/Fieldtype.php
=> Set min value on `max_items` & `max_files` config

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
=> Fix infinite loop in UI when removing assets from asset fieldtype

src/Fieldtypes/Code.php, src/Fieldtypes/Select.php
=> Remove duplicated array keys in fieldtype Code and Select

src/Modifiers/CoreModifiers.php
=> Ensure list value is an array not a collection

src/Stache/Query/QueriesTaxonomizedEntries.php, src/Tags/Collection/Entries.php, tests/Tags/Collection/EntriesTest.php
Based on a conversation in Discord: https://discord.com/channels/489818810157891584/489819906540568593/939297442623549460
=> Support taxonomy:term:not="something" syntax

src/Fieldtypes/Grid.php
This pull request fixes #5271 by implementing the same fix applied for Bard & Replicator fields in #3126.
=> Remove null values from Grid

src/Fieldtypes/Replicator.php
=> Remove unused replicator method

resources/js/components/fieldtypes/VideoFieldtype.vue
=> Avoid double question marks in video URLs

src/Exceptions/SiteNotFoundException.php, src/Http/Controllers/CP/Collections/CollectionsController.php
=> Provide a helpful exception if a site doesn't exist

resources/views/terms/create.blade.php, src/Http/Controllers/CP/Taxonomies/TermPreviewController.php
=> Fix live preview when creating a term

resources/js/components/data-list/Table.vue, src/CP/Column.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, tests/CP/ColumnTest.php
=> Align entries/terms count columns to the right

src/GraphQL/Types/FormType.php, tests/Feature/GraphQL/FormTest.php
Fixes #5250 as [suggested by Jason](https://github.com/statamic/cms/issues/5250#issuecomment-1036561347).
=> Make form validation rules queryable in GraphQL

src/Fields/Validator.php, tests/Fields/ValidatorTest.php
=> Don’t make replacements in regex validation rules

src/Modifiers/CoreModifiers.php, tests/Modifiers/PluckTest.php
=> Let count, length, and pluck modifiers handle query builders

src/Http/Controllers/CP/Forms/FormSubmissionsController.php
=> Fix error when viewing form submission

resources/js/components/assets/Editor/Editor.vue, src/Assets/Asset.php, src/Contracts/Assets/Asset.php, src/Http/Controllers/CP/Assets/PdfController.php, src/Http/Resources/CP/Assets/Asset.php
=> PDF Tweaks

resources/js/components/users/Wizard.vue
This is just #5413 but retargeted to `3.2`.
Closes #5307
=> Fix user wizard icon size

src/Fieldtypes/Grid.php, tests/Fields/ValidatorTest.php
=> Fix validation attribute error in grid

src/View/Antlers/Parser.php, tests/View/Antlers/ParserTests.php
...on the regex parser. The runtime parser works fine.
=> Fix error when entries etc are used in conditions

src/Data/HasAugmentedInstance.php
=> Add return typehint attributes

resources/js/components/fieldtypes/LinkFieldtype.vue
Fixes #5185
Fixes #4042
Replaces #5130
=> Fix link fieldtype not updating when switching sites

src/Assets/Asset.php, tests/Assets/AssetTest.php
=> Fix division by zero error when calculating asset ratio

src/Http/Controllers/CP/Utilities/CacheController.php
=> Fix flysystem error on cache manager utility page

src/View/Antlers/Parser.php, tests/View/Antlers/ParserTests.php
=> Fix nested query builder access in regex parser

src/Fields/Values.php, tests/Fields/ValuesTest.php
=> Make Values JsonSerializable

resources/js/components/assets/Editor/Editor.vue, resources/js/components/stacks/Stack.vue
Also adds a `full` mode for stacks if we ever need full width elsewhere.
=> Make asset editor full width.

src/Modifiers/CoreModifiers.php
=> to_json modifier can handle query builders

src/Assets/AugmentedAsset.php, tests/Assets/AssetTest.php
=> Add has_focus variable to assets

resources/js/components/assets/Editor/Editor.vue, resources/sass/components/assets.scss
=> Fix asset editor overflow issues

src/Fieldtypes/Users.php
https://github.com/statamic/cms/blob/b8c611bae3f450cbe307d4ff0311173f41e73e26/src/Auth/User.php#L213
=> Users fieldtype will show the first/last name in listings if available

src/CP/Breadcrumbs.php
Tired of seeing this deprecation message.
=> Add ReturnTypeWillChange attribute

resources/sass/vendors/vue-select.scss
=> Fix entries select fieldtype overflow

src/Modifiers/CoreModifiers.php, tests/Modifiers/GroupByTest.php
=> Fix `group_by` modifier not working with grids

resources/js/components/fieldtypes/CodeFieldtype.vue, resources/js/components/fieldtypes/MarkdownFieldtype.vue, resources/js/components/fieldtypes/YamlFieldtype.vue, resources/views/layout.blade.php, resources/views/outside.blade.php
=> Hook up CodeMirror's `direction` config property

src/Revisions/WorkingCopy.php
Expect the RevisionContract instead of the concrete implementation.
=> Expect the RevisionContract inside WorkingCopy

src/Console/Commands/StaticWarm.php
Optionally it could be changed to be a configuration
=> Disable SSL certificate verification locally for static:warm command

src/Query/EloquentQueryBuilder.php
This PR should mirror the changes in #5602 but for Eloquent queries.
=> Allow eloquent query builder to accept page parameters

src/Forms/Submission.php
Regression caused by #5789
Fixes #5933
=> Fix file uploads in front end form submissions

src/Modifiers/CoreModifiers.php, tests/Modifiers/ChunkTest.php
=> Support query builder in chunk modifier

src/Tags/Dd.php, src/Tags/Dump.php
=> Sort `dd` & `dump` output

resources/views/partials/global-header.blade.php
Fixes some blade echo spacing, that I didn't catch in https://github.com/statamic/cms/pull/5645
=> Additional fixes for blade echo spaces

src/StaticCaching/Cachers/ApplicationCacher.php, src/StaticCaching/DefaultInvalidator.php, tests/StaticCaching/ApplicationCacherTest.php, tests/StaticCaching/DefaultInvalidatorTest.php
=> Fix static caching invalidation when using separate domains

src/Providers/RouteServiceProvider.php
Update checker functions to handle empty cp route config
Fixes: #6148
=> Update route bindings checks to handle empty cp route config

src/Fieldtypes/Users.php
This PR also handles searching
Fixes: #4357
=> Make users fieldtype paginated in stack view

src/Http/Controllers/FrontendController.php
=> Fix amp not working on home page

src/Providers/AddonServiceProvider.php
This PR closes #6213. Who said PRs have to be long and complicated ;-)
=> Fix publish path of addon translations

src/Http/Controllers/CP/Collections/EntriesController.php
Fixes #5546
I had this stashed and then got distracted. Pushing progress up so it doesn't get lost in the void. Will update this description with more details and complete the fix when I have a chance.
Related #5576, #5824
=> Fix publish date with times

resources/js/components/fieldtypes/RevealerFieldtype.vue, resources/js/components/publish/Container.vue
=> Fix revealer tracking when re-ordering bard/replicator sets

resources/js/components/live-preview/UpdatesIframe.js
=> Only attempt to scroll live preview when on the same origin

src/Entries/Entry.php
=> fix propagation with status draft

src/Data/DataRepository.php, tests/Data/DataRepositoryTest.php
=> Fix finding data by request url when theres no root-based site

resources/js/components/fieldtypes/TemplateFieldtype.vue, resources/lang/en/fieldtypes.php, src/Fieldtypes/Template.php, src/Http/Controllers/CP/Collections/CollectionsController.php
@jasonvarga follow up from your https://github.com/statamic/cms/pull/5844#issuecomment-1184502300
=> Add `@blueprint` as a template option for collections

src/Licensing/Outpost.php
At the moment we have graceful handling of when the CP can't connect to the Outpost. However, there's not a great way to diagnose _why_ there was an issue.
Now the error message will be logged. It will also only be logged once (until the cache expires).
=> Log error when contacting the Outpost fails

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/js/components/sortable/SortableList.vue
=> Fix sortable on assets fieldtype when read-only

src/Http/Controllers/CP/Collections/EntriesController.php, tests/Feature/Entries/StoreEntryTest.php, tests/Feature/Entries/UpdateEntryTest.php
References: https://github.com/statamic/cms/discussions/6250
=> Allow validation against `published` value on entry publish form

resources/lang/nl.json, resources/lang/nl/fieldtypes.php, resources/lang/nl/messages.php
Update the Dutch translation for some new strings
=> Update Dutch translation

src/Modifiers/CoreModifiers.php
=> Deprecate format_localized modifier

.gitignore
Added `.vscode` for users using Visual Studio Code IDE
=> Add vscode directory to gitignore

resources/lang/en/fieldtypes.php, src/Fieldtypes/Bard.php, tests/Fieldtypes/BardTest.php
This PR adds to https://github.com/statamic/cms/pull/6438 by also removing empty headings.
=> Remove empty Bard nodes

resources/js/components/collections/DeleteLocalizationConfirmation.vue, src/Actions/DeleteMultisiteEntry.php
=> Fix docs URLs

resources/js/components/field-validation/Builder.vue, resources/js/components/fieldtypes/TagsFieldtype.vue, resources/js/components/inputs/relationship/SelectField.vue, resources/sass/vendors/vue-select.scss
As discussed in https://github.com/statamic/ideas/issues/844#issuecomment-1206465034
=> Add grab cursor to sortable tags/select items

config/forms.php, src/Forms/SendEmail.php, src/Forms/SendEmails.php, tests/Forms/SendEmailTest.php, tests/Forms/SendEmailsTest.php
Replaces #6469
I just wanted to make tweaks and didn't have permission to push to the other PR.
=> Send form emails in separate jobs

src/Modifiers/CoreModifiers.php, tests/Modifiers/AntlersTest.php
Add antlers modifier as per [this comment](https://github.com/statamic/cms/pull/6226#issuecomment-1213204688).
=> Add antlers modifier

resources/js/components/data-list/HasHiddenFields.js, resources/js/components/field-conditions/Validator.js, resources/js/components/field-conditions/ValidatorMixin.js, resources/js/tests/FieldConditionsValidator.test.js
=> Fix revealer handling when multiple field conditions are being evaluated

src/Auth/UserTags.php, tests/Tags/User/ResetPasswordFormTest.php
=> Fix user reset password form tag action

src/Http/Middleware/AddViewPaths.php, tests/Http/Middleware/AddViewPathsTest.php
Closes https://github.com/statamic/ideas/issues/776
References https://github.com/statamic/cms/pull/6528
=> Support multi-site, namespaced view overrides

resources/lang/en/permissions.php, src/Auth/CorePermissions.php, src/CP/Navigation/CoreNav.php, src/Http/Controllers/CP/GraphQLController.php, src/Providers/ExtensionServiceProvider.php, src/UpdateScripts/AddGraphQLPermission.php
Fixes: https://github.com/statamic/ideas/issues/853
=> Add "View GraphQL" permission

resources/js/components/fieldtypes/DateFieldtype.vue
Hi, I felt the 500ms little bit few when I used the datepicker, so I changed it to 1000ms and now its more user friendly I think.
=> Datepicker debounce change

config/users.php
=> Remove redundant `statamic.users.repositories.file.paths.users` config

resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/Set.vue, resources/js/components/fieldtypes/replicator/SetPicker.vue, resources/sass/components/fieldtypes/replicator.scss
We would also like to avoid drag and drop when we want to add a set at the first position.
Closes https://github.com/statamic/ideas/issues/720
=> 'Add Set' button at the top of the Replicator-Fieldtype

src/Assets/Asset.php, tests/Assets/AssetTest.php
=> Fix bulk asset renaming when selecting more than 2 assets

src/Entries/Collection.php, src/Taxonomies/Taxonomy.php, tests/Data/Entries/CollectionTest.php, tests/Data/Taxonomies/TaxonomyTest.php
=> Clone default blueprint before modifying it

src/StaticCaching/DefaultUrlExcluder.php, tests/StaticCaching/DefaultUrlExcluderTest.php
This fixes #4318 and fixes #5099.
=> Static caching: don't be picky about trailing slashes when excluding URLs

resources/js/components/fieldtypes/grid/Row.vue
=> Grid: hide row controls when there aren't any actions available

resources/js/components/fieldtypes/DateFieldtype.vue
=> Fix date not showing in Safari

src/CP/Navigation/NavItem.php, tests/Facades/CP/NavTest.php
=> Prevent wrongly marking CP navigation items as current

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/sass/components/assets.scss
@arthurperton I couldn't push to your branch, but I had made a few other tweaks to improve this as well as I saw your commit come in.
Fixes https://github.com/statamic/cms/issues/6649.
=> Fix asset fieldtype drag mirror

src/Taxonomies/LocalizedTerm.php
Fixes #6658 , I think this potentially fixes the underlying issue with the locales tag solved by the workaround in #6466 (although I've not tested that specifically)
=> Correctly localize localized term collection URLs 

resources/js/components/publish/Sections.vue
=> Make sidebar tab accessible again

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
=> Don't show the asset picker when squished or inside a Grid

resources/js/components/publish/Sections.vue
=> Fix publish form tab not being set properly on load

src/StaticCaching/Cachers/AbstractCacher.php, tests/StaticCaching/CacherTest.php
=> Remove trailing slash from static caching base url / domain

resources/sass/components/fieldtypes/replicator.scss
=> Replicator: Fix plus buttons spacing issue

resources/js/components/fieldtypes/bard/BardFieldtype.vue, src/Fieldtypes/Bard.php
This PR adds the collapse option to Bard, just like Replicator has.
Closes https://github.com/statamic/ideas/issues/407
=> Add collapse option to Bard fieldtype

resources/js/components/assets/Browser/Browser.vue, resources/sass/components/assets.scss, src/Http/Resources/CP/Assets/FolderAsset.php
=> Asset Browser thumbnail style now matches the Fieldtype's

src/Http/Controllers/CP/Fields/FieldsController.php
=> Make `status` a reserved word

src/Actions/RenameAsset.php, src/Actions/RenameAssetFolder.php
Closes #5943.
Fairly simple. :cake:
=> Auto-focus to the rename field input when opening a rename action modal

src/Http/Controllers/CP/Taxonomies/TermsController.php
Fixes https://github.com/statamic/cms/issues/6898
=> Fix taxonomy term field filters not working

config/assets.php
As pointed out in statamic/statamic#48
=> Fix duplicated word in assets config

resources/js/components/entries/PublishForm.vue, src/Http/Controllers/CP/Collections/EntriesController.php
=> Update entry publish form values after saving

resources/js/components/data-list/FilterPresets.vue
=> Use translation for 'all'

resources/js/components/assets/Browser/Thumbnail.vue, src/Fieldtypes/Assets/Assets.php
=> Make sure SVGs are rendered in collection listing.

src/Fieldtypes/Entries.php
I've had the need to do this for all projects we've done, so now I've decided to make a PR for it instead of just making a custom fieldtype extending entries.
=> Allow filtering by blueprints in Entries fieldtype

resources/js/components/fieldtypes/TemplateFieldtype.vue
=> Fix empty template fieldtype dropdown style

resources/sass/components/fieldtypes/grid.scss
=> Fix grid table header position inside stacks.

resources/js/components/collections/View.vue, resources/js/components/data-list/Table.vue, resources/js/components/entries/Listing.vue
It's not working as intended.
Closes #7094
Reverts #4895
=> Revert PR 4895

src/Providers/RouteServiceProvider.php
See [comment](https://github.com/statamic/cms/commit/662bc32f0c0de863655ebd1fbc79fbd6b9387348#r90351225).
=> Ensure `bindForms` takes configurable route prefix into account

src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Entries.php, src/Http/Resources/CP/Assets/Asset.php, src/Http/Resources/CP/Entries/Entries.php, src/Http/Resources/CP/Entries/Entry.php, src/Http/Resources/CP/Submissions/Submissions.php, src/Http/Resources/CP/Taxonomies/Term.php, src/Http/Resources/CP/Taxonomies/Terms.php, src/Http/Resources/CP/Users/Users.php
Refactored `ResourceCollection` and `JsonResource` to work with using `JsonResource::withoutWrapping()`
Closes #7068
=> Refactored `ResourceCollection` and `JsonResource` responses

src/Stache/Repositories/EntryRepository.php, tests/Stache/Repositories/EntryRepositoryTest.php
=> Fix case insensitive entry urls

src/Http/Controllers/CP/Assets/AssetsController.php
Fixes #7129. Pretty sure it fixes #7109 too, looks like the same issue.
=> Fix CP Exception when editing an image / asset

src/StaticCaching/Cachers/AbstractCacher.php, tests/StaticCaching/CacherTest.php
=> Fix static caching error `Undefined array key "scheme"`

resources/js/components/data-list/TableField.vue, resources/sass/elements/tables.scss
Looks terrible. Let's fix that.
=> Don't wrap date index fields.

src/Actions/DuplicateAsset.php, src/Actions/DuplicateEntry.php, src/Actions/DuplicateForm.php, src/Actions/DuplicateTerm.php, tests/Actions/DuplicateAssetTest.php, tests/Actions/DuplicateEntryTest.php, tests/Actions/DuplicateFormTest.php, tests/Actions/DuplicateTermTest.php
=> Add authorization to duplicate actions

package-lock.json
This reverts commit 7452f1629fa2a31523558802b1d0bdf1884df535.
It just breaks the build.
=> Revert "Bump decode-uri-component from 0.2.0 to 0.2.2 (#7159)"

src/Fieldtypes/Link.php
A small deprecated warning fix for PHP 8.1
=> Fix deprecation notices in link fieldtype when empty

src/Fieldtypes/Terms.php
=> Fixed terms slugging when creating through fieldtype

resources/views/widgets/collection.blade.php, src/Widgets/Collection.php
=> Hook up the blueprint picker for the collection widget.

resources/js/components/publish/Field.vue
Closes statamic/ideas#671. Solution based on https://github.com/markedjs/marked/issues/144#issuecomment-49252714
=> Open links in field instructions in a new window

config/assets.php, src/Imaging/GlideManager.php, src/Imaging/ImageGenerator.php, src/Imaging/Manager.php
Closes statamic/ideas#616
Closes statamic/ideas#898
=> Support Glide defaults, and aliases in presets

resources/lang/de.json, resources/lang/de_CH.json
String was introduced in https://github.com/statamic/cms/pull/6400.
=> Add translations for "Current Password"

src/Extensions/Translation/Translator.php
=> Add property to translator to prevent deprecation message

resources/js/components/assets/Editor/Editor.vue
=> Rename filename to path

routes/cp.php, tests/Feature/Assets/BrowserTest.php
=> Fix asset search in nested subdirectories

resources/js/components/entries/PublishActions.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/terms/PublishActions.vue, resources/js/components/terms/PublishForm.vue
=> Check ‘manage publish state’ permission in publish actions

resources/views/forms/automagic-email.antlers.html
Fixes https://github.com/statamic/cms/issues/7364
=> Fix missing form values in submission emails

src/Tags/Svg.php
=> Handle SVG titles and descriptions for a11y

src/View/Antlers/Language/Runtime/ModifierManager.php
In certain cases, if a modifier threw an exception, you'd see a `ModifierException` rather than the actual exception, so you couldn't really see in the stack trace where the error was originating from.
=> Fix modifier exception being thrown

resources/views/partials/scripts.blade.php
Fixes https://github.com/statamic/cms/issues/7428
=> Don't rely on Vite alias

resources/js/components/entries/PublishForm.vue, resources/js/components/publish/HasHiddenFields.js, resources/js/components/publish/Values.js
Same as #7443 but targeting 3.4.
Fixes #7441
=> Fix create entry form not redirecting on save

.github/workflows/tests.yml
As per https://github.com/actions/runner-images/issues/675#issuecomment-1419388451
=> Workaround for GitHub Actions network issue

src/Translator/Commands/Generate.php, src/Translator/Commands/Review.php, src/Translator/Commands/Translate.php
Fixes: #7501 by defining any class-level variables.
=> Prevent deprecation warnings in translate commands

resources/lang/en/messages.php
=> Fix typo in preference start page instruction

src/CP/Navigation/NavItem.php, tests/CP/Navigation/NavTest.php
=> Fix active nav item check on CP urls with an `#anchor`

resources/js/components/publish/Field.vue
There were some changes in #7548 that didn't need to happen.
=> [4.x] Revert field changes

src/Http/Controllers/FrontendController.php, tests/FrontendTest.php
=> 404 pages are protected

resources/lang/cs/permissions.php, resources/lang/da/permissions.php, resources/lang/de/permissions.php, resources/lang/de_CH/permissions.php, resources/lang/en/permissions.php, resources/lang/es/permissions.php, resources/lang/fr/permissions.php, resources/lang/hu/permissions.php, resources/lang/id/permissions.php, resources/lang/it/permissions.php, resources/lang/ms/permissions.php, resources/lang/nb/permissions.php, resources/lang/nl/permissions.php, resources/lang/pl/permissions.php, resources/lang/pt/permissions.php, resources/lang/pt_BR/permissions.php, resources/lang/ru/permissions.php, resources/lang/sl/permissions.php, resources/lang/sv/permissions.php, resources/lang/tr/permissions.php, resources/lang/zh_CN/permissions.php, resources/lang/zh_TW/permissions.php, src/Auth/CorePermissions.php, src/Http/Controllers/CP/Users/UsersController.php
Left over of https://github.com/statamic/cms/pull/7703
=> [4.x] Remove perform updates permission

src/Fieldtypes/Entries.php, tests/Fieldtypes/EntriesTest.php
=> Fix whereAnyStatus error

resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/replicator/AddSetButton.vue, resources/js/components/fieldtypes/replicator/SetPicker.vue
- Fix issue where once you pick a set, if you open the picker again, it's empty.
- Fix add set button not doing anything when theres only one set.
=> [4.x] Set picker fixes

resources/js/components/fieldtypes/replicator/AddSetButton.vue, resources/js/components/fieldtypes/replicator/SetPicker.vue
Position the set picker by the button.
The button got left aligned in #7819 but not the picker.
=> [4.x] Replicator set button placement

resources/css/components/fieldtypes/color.css, resources/js/components/fieldtypes/ColorFieldtype.vue
=> Tighten up the color UI a bit more

resources/js/components/data-list/ColumnPicker.vue
Same as #7824 but targeting the column picker
=> [4.x] Fix data-list columns not being removable

resources/js/components/Popover.vue, resources/js/components/assets/Browser/Browser.vue
=> [4.x] Popovers now stop click propagation

resources/js/components/fieldtypes/replicator/SetPicker.vue
=> [4.x] Set Picker now has a max-height and is scrollable

src/Fieldtypes/Bard.php, src/Fieldtypes/Replicator.php, tests/Feature/GraphQL/Fieldtypes/BardFieldtypeTest.php, tests/Feature/GraphQL/Fieldtypes/ReplicatorFieldtypeTest.php
=> [4.x] Fix Bard and Replicator in GraphQL when using set groups

resources/js/components/fieldtypes/replicator/Set.vue
=> [4.x] Fix Replicator sorting

resources/js/components/fieldtypes/TimeFieldtype.vue
- Only add seconds when needed.
- Bind the initial value into the mask.
=> [4.x] Couple of Time fieldtype fixes

resources/css/components/fieldtypes/bard.css
=> [4.x] Bard fullscreen style fixes

resources/css/components/login.css, resources/views/auth/login.blade.php
Closes https://github.com/statamic/cms/issues/7932
=> [4.x] Fix OAuth login styles

resources/js/components/data-list/ColumnPicker.vue
Closes https://github.com/statamic/cms/issues/7918
=> [4.x] Remove unnecessary tabindex target.

resources/css/vendors/vue-select.css, resources/js/components/field-conditions/Builder.vue, resources/js/components/fields/Settings.vue
Closes https://github.com/statamic/cms/issues/7956
=> [4.x] Better responsive conditions.

resources/lang/de/messages.php, resources/lang/de_CH/messages.php
Added missing key _field_validation_sometimes_instructions_ in de / de_CH messages.php translation
=> German translations

resources/js/components/fieldtypes/replicator/Replicator.vue
Closes https://github.com/statamic/cms/issues/7937
=> [4.x] Fix z-index overlap issue when replicator display label is hidden

resources/css/elements/tables.css
Closes https://github.com/statamic/cms/issues/7966. Thanks @o1y!
=> [4.x] Fix Firefox data-table issues

resources/css/components/fieldtypes/bard.css, resources/css/components/fieldtypes/table.css, resources/css/components/fieldtypes/textarea.css, resources/css/elements/forms.css, resources/js/components/collections/OneOrManySitesField.vue, resources/js/components/fieldtypes/grid/Cell.vue, resources/js/components/fieldtypes/replicator/Field.vue
Closes https://github.com/statamic/cms/issues/8016
=> [4.x] Text field size consistency

resources/js/components/users/Listing.vue, src/Actions/AssignGroups.php, src/Actions/AssignRoles.php, src/Providers/ExtensionServiceProvider.php
=> [4.x] Add actions to assign roles and groups to users from the users listing

resources/js/components/Bard.js
I'd like to use ProseMirror model and view in a custom extension, please can they be exported? 🙂
=> [4.x] Export ProseMirror model and view

resources/js/components/fieldtypes/ToggleIndexFieldtype.vue
=> [4.x] Fix toggle listing icons

config/cp.php
=> [4.x] Remove unused config option

resources/js/components/fieldtypes/bard/BardFieldtype.vue
=> [4.x] Fix Bard fullscreen button aria-label

resources/css/components/assets.css
=> [4.x] Fix asset grid tile size.

resources/js/components/fieldtypes/MarkdownFieldtype.vue, resources/lang/de.json, resources/lang/de_CH.json
=> [4.x] Fix full screen mode translation casing

resources/js/components/fieldtypes/TemplateFieldtype.vue
=> [4.x] Apply floating-ui treatment to select fieldtype

resources/js/components/modals/ConfirmationModal.vue
=> [4.x] Fix confirmation modal's confirm button text

resources/js/components/fieldtypes/assets/Asset.js, resources/js/components/fieldtypes/assets/AssetRow.vue, resources/js/components/fieldtypes/assets/AssetTile.vue, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, src/Fieldtypes/Assets/Assets.php
=> [4.x] Fix asset fieldtype min_files validation and the show set alt option.

src/Fieldtypes/Date.php, src/Validation/DateFieldtype.php, tests/Fieldtypes/DateTest.php
Same as #8205 but for date ranges.
Fixes #8187
=> [4.x] Fix validation of nested date range fields

src/Console/Commands/FlatCamp.php
=> [4.x] More lines from Flat Camp

resources/js/components/nav/Branch.vue
Fixes #8220
It was more than just the pin icon mentioned in the issue.
=> [4.x] Fix nav builder icons

src/Auth/UserTags.php, src/Tags/Tags.php
I should have been more thorough with my PR yesterday, this adds blade support for the remaining user tags.
Fixes: #8238
=> [4.x] Add blade support to user:in, user:not_in, user:is, user:isnt and user forms

src/GraphQL/TypeRegistrar.php, src/GraphQL/Types/UserType.php, tests/Feature/GraphQL/UserTest.php
=> [4.x] Fix missing GraphQL types for more complex fields in user blueprints

src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php
Refer to this bug report https://github.com/statamic/cms/issues/7262, i take a look into it and I found this solution
Closes #7262
=> [4.x] Fix relationship fieldtype encoding issue

resources/css/components/assets.css, resources/js/components/assets/Browser/Browser.vue, src/Http/Resources/CP/Assets/FolderAsset.php
=> [4.x] Fix checkboard bg on asset tiles

resources/css/components/configure.css, resources/css/components/toggle.css
=> [4.x] Fix issues with toggle fields collapsing too far and not wrapping instructions in sidebars.

src/View/Debugbar/AntlersProfiler/PerformanceCollector.php
Removes some debug code that was left behind 🤦
=> [4.x] Profiler: Removes debug code

resources/lang/fr/validation.php, translator
Updating French translations for 4.9.2 and adding the icon.title key to the Translator
=> [4.x] French translations and Translator

src/Fieldtypes/Markdown.php, src/Fieldtypes/Text.php
=> [4.x] Adding missing translation calls

resources/lang/fr.json, resources/lang/fr/fieldtypes.php
=> [4.x] French translations

src/GraphQL/Types/ArrayType.php, src/Stache/Repositories/TaxonomyRepository.php, tests/Antlers/Runtime/PhpEnabledTest.php, tests/Modifiers/AddQueryParamTest.php, tests/Modifiers/RemoveQueryParamTest.php, tests/Modifiers/SetQueryParamTest.php, tests/View/Antlers/ParserTests.php
A new version of Pint was released that added some rules. They are causing updates to unrelated lines of code in some PRs. Just going to tackle it here.
(I'm aware of the irony of changing to Pint in #8310)
> Twice now, StyleCI has decided to change it's styling rules at seemingly random times. You'd open a PR that changes one file, and all of a sudden the entire codebase is modified. 
But at least we can see what changed as Pint is open source where StyleCI was a black box.
=> [4.x] Trigger Pint

resources/js/components/CodeBlock.vue
=> [4.x] Only show code block copy button on https

resources/js/components/collections/View.vue
Fixes #8488. Introduced by #8487.
=> [4.x] Fix create entry button

resources/js/plugins/slugify.js
=> [4.x] Don't slugify apostrophes. 

resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue
=> [4.x] Fix link insert cancel in Markdown field.

resources/css/components/items.css, resources/js/components/inputs/relationship/CreateButton.vue, resources/js/components/inputs/relationship/Item.vue, resources/js/components/inputs/relationship/RelationshipInput.vue
=> [4.x] Fix Relationship Item long titles

resources/js/components/forms/Listing.vue
=> [4.x] Fix form listing table corner clip.

resources/js/components/fieldtypes/bard/Set.vue
=> [4.x] Conform Bard Set Headers to match Replicator

resources/js/components/fieldtypes/relationship/RelationshipIndexFieldtype.vue
=> [4.x] Fix Relationship Index Field Item height

resources/js/components/entries/Listing.vue
=> [4.x] Better entry listing hit target

src/CP/Navigation/NavItem.php, src/CP/Navigation/NavTransformer.php, tests/CP/Navigation/NavTest.php, tests/CP/Navigation/NavTransformerTest.php
=> [4.x] Fix special character handling in created CP nav sections

src/Marketplace/AddonsQuery.php
=> [4.x] Fix v4 addons not appearing in listing

resources/css/components/nav-main.css, resources/views/partials/global-header.blade.php
=> [4.x] Fix hamburger icon wompyness.

resources/lang/en/fieldtypes.php, src/Fieldtypes/Taggable.php
=> [4.x] Add placeholder text to make Taggable usage more clear

resources/js/bootstrap/globals.js, resources/js/components/fieldtypes/CodeFieldtype.vue
=> [4.x] More thoroughly escape and truncate Code replicator previews

src/Tags/FluentTag.php, tests/Tags/FluentTagTest.php
=> [4.x] Fix fluent tag camelCase params

resources/css/components/publish.css, resources/js/components/entries/PublishForm.vue, resources/js/components/publish/Tabs.vue
=> [4.x] Fix sidebar's empty card when no actions are present

resources/js/components/field-conditions/Builder.vue
=> [4.x] Make condition operators translatable.

src/View/Antlers/Language/Runtime/NodeProcessor.php, src/View/Antlers/Language/Runtime/RecursiveNodeManager.php, tests/Antlers/Runtime/RecursiveNodesTest.php
This PR resolves #8565 by adding support for custom variable assignment tracking within recursive loops.
=> [4.x] Adds custom variable persistence to recursive loops

resources/js/components/entries/Widget.vue, resources/views/forms/widget.blade.php
=> [4.x] Empty form widget styling is now consistent with other widgets

src/Modifiers/CoreModifiers.php
``` yaml
title: I see a bad-ass mother who don't take no crap off of nobody.
```
``` antlers
{{ title | headline('ap') }}
I See a Bad-Ass Mother Who Don't Take No Crap Off of Nobody.
```
``` antlers
{{ title | headline('mla') }}
I See a Bad-ass Mother Who Don't Take No Crap Off of Nobody.
```
=> [4.x] New modifier for AP and MLA style headlines

resources/js/components/terms/PublishForm.vue
Applies #8720 to the term publish form.
=> [4.x] Fix sidebar missing background on term publish form

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
=> [4.x] Adjust data passed to live preview targets

src/Console/Please/Application.php
Solves the issue with resolving commands in [#8783](https://github.com/statamic/cms/issues/8783)
=> [4.x] Check for type in Please command resolver

src/Assets/AssetUploader.php, tests/Assets/AssetTest.php
=> [4.x] Fix lowercasing asset filenames to include file extension

.github/workflows/tests.yml
This PR just adds PHP 8.3 to our test matrix. The tests passed without having to add any code. Nice.
=> [4.x] PHP 8.3

composer.json, src/Tags/Svg.php, tests/Tags/SvgTagTest.php
Backports #8408 and #8428 to battle potential XSS issues.
=> [3.4] SVG tag sanitization

src/Actions/DuplicateEntry.php
Fixes #8938
The translator tool wasn't picking up the translation. Adding these comments fixes it.
=> [4.x] Fix duplicate entry action translation

composer.json
I'm a VScode hold out. 
Can we have the pint-cli in dev so I can run it before submitting PRs?
=> [4.x] Add pint cli in require-dev

src/Http/Controllers/FormController.php
=> [3.4] Front-end form asset field php file validation

resources/js/components/collections/EditForm.vue, resources/views/forms/edit.blade.php
Fixes: https://github.com/statamic/cms/issues/8350 by allowing the title to be changed by an optional prop on the Vue component.
=> [4.x] Fix for edit form page saying edit collection

src/Http/Controllers/CP/Assets/AssetsController.php, src/Http/Controllers/CP/Fieldtypes/FilesFieldtypeController.php, src/Http/Controllers/FormController.php
Prevents even more php file types being uploaded.
=> [4.x] More php file validation

resources/js/components/assets/AssetManager.vue, resources/js/components/globals/Listing.vue
Fix missing translations as referenced [here](https://github.com/statamic/cms/issues/7098#issuecomment-1817935278) and [here](https://github.com/statamic/cms/issues/8913#issuecomment-1817937415) 
Thanks @espenlg !
=> [4.x] Translate global titles in listing and asset tiles on show page

src/Assets/AssetUploader.php, src/Assets/FileUploader.php, tests/Assets/AssetTest.php
=> [3.4] Apply appropriate file extension when uploading

resources/css/components/publish.css
=> [4.x] Fix section header padding in the sidebar

resources/js/components/fieldtypes/DateFieldtype.vue
This pull request improves the Replicator Preview of the Date fieldtype.
Closes statamic/ideas#1082
=> [4.x] Improve replicator preview for Date Fieldtype

resources/views/widgets/collection.blade.php, resources/views/widgets/header.blade.php
Some translations that were missed.
=> [4.x] Translate widget header and collection widget title

resources/js/components/publish/Field.vue, resources/js/components/users/Wizard.vue, resources/views/users/create.blade.php, src/Http/Controllers/CP/Users/UsersController.php
This PR adds an "Additional information" step to the User Create Wizard for any required fields in the user blueprint:
Closes: https://github.com/statamic/cms/issues/7925
=> [4.x] Add additional user blueprints fields to user create wizard

resources/js/components/entries/BaseCreateForm.vue, resources/views/entries/create.blade.php
Fixes #9090
In #9075 the prop was applied to the wrong place.
=> [4.x] Fix 404 redirect after creating entry

src/Search/Comb/Comb.php
This PR improves the speed of the built-in comb search driver.
In my testing it results in an ~80% reduction in query time (as measured by comb's internal `query_time` stat).
It returns exactly the same rankings and scores as the current version and produces exactly the same internal match counts. (assuming I haven't messed anything up)
I've made the following changes:
* **Remove the word loop**
The current version splits the search values into an array of words and then loops over them, performing a set of regex checks on each word. This has been replaced by a single set of regex checks that look for words in the same way but across the entire value at once.
* **Remove a duplicate regex check**
The current version checks for partial matches across the entire value, and checks for partial …
=> [4.x] Improve comb search driver performance

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
=> [4.x] Make url and uri available in preview targets

src/Fieldtypes/Link/ArrayableLink.php
Closes https://github.com/statamic/cms/issues/9118
=> [4.x] Make arrayable link url method public

resources/lang/en/fieldtypes.php
Closes https://github.com/statamic/cms/issues/9140
=> [4.x] Add group title translation string

src/Query/EloquentQueryBuilder.php
Brings the same changes from https://github.com/statamic/cms/pull/9142 into our eloquent query builders.
We unfortunately cant defer to `$this->builder` on these as the results need transformed by our get()
=> [4.x] Add chunk and lazy to eloquent query builder

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Couple of notes when creating a PR, especially about opening an issue in the docs repo for new features.
=> [4.x] Update contribution guide

src/Fields/Fieldset.php
Check field is truthy before running the fieldImportsFieldset function 
Closes https://github.com/statamic/cms/issues/9173
=> [4.x] Ensure field exists before checking if it imports a fieldset

src/Http/Controllers/CP/Forms/FormSubmissionsController.php
This PR localizes the date format on form submission show view
=> [4.x] Localized date format on form submission show view

resources/views/blueprints/index.blade.php, resources/views/forms/widget.blade.php, resources/views/partials/breadcrumb.blade.php, resources/views/partials/nav-main.blade.php, resources/views/partials/nav-mobile.blade.php, resources/views/widgets/collection.blade.php
=> [4.x] Avoid compiling certain user defined strings

src/Taxonomies/LocalizedTerm.php
Closes https://github.com/statamic/cms/issues/9277.
=> [4.x] Add `saveQuietly` to `LocalizedTerm`

src/Http/Controllers/FormController.php
Adds a check if files have actually been submitted within a form.
fixes #9354
=> [4.x] Allow optional asset fields in form submissions

src/Providers/AddonServiceProvider.php
This PR adds autoloading of addon blueprints the same way it already works for fieldsets.
=> [4.x] Autoload addon blueprints

src/Search/UpdateItemIndexes.php, tests/Auth/Eloquent/EloquentUserTest.php
=> [4.x] Allow search index updates to be queued

src/Assets/Asset.php, tests/Assets/AssetTest.php
Follow-up on https://github.com/statamic/cms/pull/9284 to have 1 source of truth.
=> [4.x] Uniform image validation

src/Actions/CopyPasswordResetLink.php
=> [4.x] Make copy reset password link action opt-in

src/Actions/CopyPasswordResetLink.php
=> [3.4] Make copy reset password link action opt-in

src/Assets/AssetUploader.php, src/Assets/FileUploader.php
Reverts #9048
Essentially backporting #9389
=> [3.4] Revert overzealous file extension renaming feature

src/Fieldtypes/Group.php, src/GraphQL/Types/GroupType.php
This pull request adds a GraphQL type to the relatively new Group Fieldtype (#8836).
Closes #9494.
=> [4.x] Add GraphQL type for Group fieldtype

resources/lang/en/fieldtypes.php, src/Forms/Fieldtype.php
Adds the UI mode option to the forms fieldtype config.
=> [4.x] Add UI mode option to forms fieldtype config

tests/Modifiers/RelativeTest.php
Today is February 29th. This test fails today only. 😂
=> [4.x] Fix test that fails on February 29th

resources/views/partials/global-header.blade.php
This PR adds a direct link to your user preferences from the avatar dropdown.
This is just a shortcut to save you going gear icon > preferences > my preferences.
=> [4.x] Add direct link to preferences

config/antlers.php, config/assets.php, config/git.php
This updates a few config options that were added to `statamic/statamic` but not into the core.
- https://github.com/statamic/statamic/pull/57
- https://github.com/statamic/statamic/commit/41830dba67163d1d88fecfbe72ab3b7c8c2f7fe9
- https://github.com/statamic/statamic/pull/59
=> [4.x] Update config

src/Entries/Entry.php
Replaces https://github.com/statamic/cms/pull/9832
=> [5.x] Prevent cachedKeys and siteCache from being stored on sleep

tests/Tags/Concerns/RendersFormsTest.php
This fixes a bunch of deprecation warnings that have started popping up in PHPUnit.
=> [4.x] Fix PHPUnit deprecations warnings

src/Stache/Stores/CollectionEntriesStore.php, tests/Data/Entries/EntryTest.php
=> [5.x] Fix 404s due to entry uri caching changes

routes/web.php, src/Http/Controllers/User/LoginController.php, src/Http/Controllers/User/PasswordController.php, src/Http/Controllers/User/ProfileController.php, src/Http/Controllers/User/RegisterController.php, src/Http/Controllers/User/UserController.php
Reviewing #8924 would have a fair bit simpler if the various tags/actions had their own controllers.
This PR does that, plus a little more general cleanup.
=> [5.x] Organize user controllers

resources/css/components/fieldtypes/yaml.css, resources/js/components/fieldtypes/YamlFieldtype.vue
Fixes the code mode and rounded border lost by the Code Fieldtype redesign.
Closes #10084
=> [5.x] Fix YAML fieldtype UI

src/Sites/Site.php
This reverts #9645 as it appears to cause some issues.
Closes #10114
#10079
#10067
=> [5.x] Revert caching site absolute url

config/git.php, src/Git/Git.php, tests/Git/Concerns/PreparesTempRepos.php, tests/Git/GitTest.php
Small improvement on top of https://github.com/statamic/cms/pull/10134.
=> [5.x] Provide git binary var to commands array in config

resources/css/components/page-tree.css
=> [5.x] Fix Dark Mode Tree Node margins.

resources/js/components/fieldtypes/replicator/AddSetButton.vue
This pull request makes the label on the "Add Set" button localizable.
Closes #10212.
=> [5.x] Make label on Add Set button localizable

resources/js/components/fieldtypes/CodeFieldtype.vue
=> [5.x] Fix Code fieldtype not removing the overflow hidden style on body when closing Fullscreen Mode

resources/lang/da/moment.php
This PR translates strings from the moment.php file into danish
=> [5.x] Danish translation of moment strings

src/Query/Scopes/Filters/Fields.php
This PR localises field titles in the filter dropdown:
=> [5.x] Localise field titles in collection filter

src/Console/Commands/FlatCamp.php
=> [5.x] Colin's quote

src/Console/Commands/FlatCamp.php
=> [5.x] More Flat Camp Quotes

resources/lang/fr.json, src/Actions/RenameAsset.php, src/Sites/Sites.php
=> [5.x] Update some translations

resources/css/components/array.css, resources/css/components/fieldtypes/bard.css, resources/css/components/fieldtypes/datetime.css, resources/css/components/outside.css, resources/css/components/tabs.css, resources/css/components/toggle.css, resources/css/core/fonts.css, resources/css/core/utilities.css, resources/css/elements/badges.css, resources/css/elements/buttons.css, resources/css/vendors/codemirror.css, src/View/Debugbar/AntlersProfiler/resources/widget.css
I have come into some errors in base CSS files and tried to resolve them. Thanks to this PR, the CSS files will be cleaner, smaller and with less errors
=> [5.x] CSS improvements

src/StaticCaching/Middleware/Cache.php
This swaps the lock in the Static Cache middleware from a hardcoded file-based Symfony Lock to Laravel's cache-based atomic lock.
This will allow people that use a horizontal scaling approach to use a more appropriate cache driver for locks. e.g. Redis.
This will use the same `static_cache` cache store if it exists. [Docs](https://statamic.dev/static-caching#custom-cache-store) 
This also moves the locking behavior to only around the writable bits. If there's a cached response available to be served, it will be served without waiting for the lock.
=> [5.x] Use cache locks in static cache

resources/css/vendors/vue-select.css
=> [5.x] Fix select fieldtype disabled cursor

src/Console/Commands/Multisite.php
=> [5.x] Improve multisite fresh-run detection logic

resources/css/components/fieldtypes/datetime.css
References: https://github.com/statamic/cms/pull/10488#issuecomment-2243782819
=> [5.x] Fix Date Picker dark mode bg color

src/Entries/Entry.php, src/Http/Controllers/CP/PreviewController.php
This pull request fixes an issue where changes to `template` and `layout` fields wouldn't take affect in Live Preview.
Fixes #10527.
=> [5.x] Fix Template & Layout fields in Live Preview

src/Http/Controllers/ForgotPasswordController.php
=> [5.x] Adding page title to forgot your password page

src/Fieldtypes/Assets/Assets.php
While working through the issues reported in https://github.com/statamic/eloquent-driver/issues/262 I noticed that Assets fields weren't included in the augmentation blinking when max_items: 1, maybe this was intentional, maybe not.
This PR augments them which should remove (some) duplicate queries.
Similar to https://github.com/statamic/cms/pull/9938
=> [5.x] Blink augmentation of asset fields with `max_items: 1`

composer.json
This PR updates tiptap-php to include the fixes for #9363 (from @jacksleight).
From my testing this worked, however, I found it difficult to test the editors features.
=> [5.x] Update tiptap-php

.github/PULL_REQUEST_TEMPLATE.md
This pull request makes a teeny, tiny change to update the suggested branch name in the PR template.
=> [5.x] Update the PR template for v5

config/system.php
makes a change to how it reads
=> [5.x] Fix small typo

src/Providers/AddonServiceProvider.php
This pull request builds on top of #9270, by introducing autoloading for Dictionaries in addons.
=> [5.x] Auto-load addon dictionaries

package-lock.json
This runs `npm update x` for each `@tiptap/x` dependency we have in our `package.json`.
=> [5.x] Update tiptap npm dependencies

src/Providers/AddonServiceProvider.php
Statamic 5.33.0 (https://statamic.com/release-notes#5.33.0) introduced auto-registration of listeners from add-ons, however this auto-registration is limited to listeners that are implemented via the handle() method (see #10911).
Since Laravel also supports listeners via the `__invoke` method on a class (https://laravel.com/docs/11.x/events#event-discovery), this PR expands Statamic's auto-discovery of listeners to include those that are implemented using `__invoke()`.
=> [5.x] Support auto-registering of listeners using __invoke() not handle

resources/js/components/fieldtypes/ColorFieldtype.vue
=> [5.x] Fix color fieldtype's collapsed state showing plain HTML

src/Fieldtypes/Bard.php, tests/Fieldtypes/BardTest.php
Fixes https://github.com/statamic/cms/issues/11037
=> [5.x] Fix inline Bard with leading line break

src/Http/Controllers/CP/Assets/BrowserController.php
Adjust the asset browser folder sort to apply across all pages. Currently, only the last page's folders are sorted and the sort only applies to that page. The main adjustment is in moving line 85 (the slicing down of all folders to the currently visible ones) to happen after the sorting, not before.
Closes #11085
=> [5.x] Enable asset folder sort across pages

src/View/Blade/helpers.php
Thanks @JohnathonKoster for this neat little value helper 👍
Does it make sense to add the `LabeledValue` as well?
=> [5.x] Add ArrayableString to Blade value helper

resources/css/components/publish.css, resources/js/components/publish/Field.vue
Fixes https://github.com/statamic/cms/issues/11157
=> [5.x] Fix field actions when display is hidden

resources/js/components/fieldtypes/bard/BardFieldtype.vue
Fixes https://github.com/statamic/cms/issues/11163
=> [5.x] Fix inline bard expand/collapse actions

resources/css/elements/dropdowns.css
Dark mode styles for the quick menu.
=> [5.x] Fix field actions dark mode

resources/lang/nl.json
Fix the dutch translation of "Statamic"
=> [5.x] Fix Dutch translation of Statamic

src/Providers/ExtensionServiceProvider.php
Fixes #11231 caused by #11046
Replaces #11233
=> [5.x] Fix subdirectory autodiscovery on Windows

src/Query/Builder.php
=> [5.x] Fix deprecation warning from regex operator

src/StaticCaching/Replacers/NoCacheReplacer.php, tests/StaticCaching/FullMeasureStaticCachingTest.php
=> [5.x] Remove type attribute in nocache replacer

src/Search/Result.php, src/Tags/Concerns/GetsQueryResults.php
=> [5.x] Fix search:results tag when offset and paginate are set

src/CP/Breadcrumbs.php
=> [5.x] Handle extra translation files in breadcrumbs

resources/js/components/fieldtypes/TableFieldtype.vue
Removes an additional reference I missed in #11420
=> [6.x] Remove reference

resources/lang/nl/markdown.php
I was following along with [this bug](https://github.com/laravel/vs-code-extension/issues/212) in the Laravel VS Code extension repo and was curious about the translation structure and noticed some typos. :)
Full disclosure, Dutch is not my native language, but I think I speak/write well enough to submit this. I'm sure Robb or someone else similarly qualified can give it a once over and give the OK!
=> [5.x] Update Dutch translation

.github/workflows/tests.yml
=> [5.x] Use ubuntu-latest in GitHub Actions workflow

resources/js/components/inputs/relationship/SelectField.vue
=> [5.x] Adjust relationship field typeahead no-options message

resources/js/components/nav/ItemEditor.vue
Same as #11560, but I missed a usage in the nav builder.
=> [5.x] Fix icon fieldtype in nav builder

resources/js/components/nav/Builder.vue
Fixes an error when you try to un-hide a hidden nav item.
=> [6.x] Fix nav builder error

src/Http/Controllers/CP/Collections/EntriesController.php
Fixes https://github.com/statamic/cms/issues/11710
=> [5.x] Fix collection index search when using a non-dedicated search index

resources/js/components/fieldtypes/LinkFieldtype.vue
fix https://github.com/statamic/cms/issues/11563
=> [5.x] Fix Add truncate class to flex container in LinkFieldtype

resources/js/components/fieldtypes/bard/LinkToolbar.vue
Fix https://github.com/statamic/cms/issues/11627
=> [5.x] Fix pop-up position of for Bard link inconsistent

src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, tests/Data/Taxonomies/TaxonomyTest.php
Fix https://github.com/statamic/cms/issues/11472
=> [5.x] Fix wrong taxonomies count on multiple sites

src/Query/Scopes/Filters/Fields/Terms.php
Fixes https://github.com/statamic/cms/issues/11527
Fixes https://github.com/statamic/cms/issues/11707
Fixes https://github.com/statamic/cms/issues/11562
=> [5.x] Fix Term filter on entry listing not working when limiting to 1 term

resources/js/bootstrap/fieldtypes.js, resources/js/components/fieldtypes/BlueprintsFieldtype.vue, src/Fieldtypes/Blueprints.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Providers/ExtensionServiceProvider.php
There's probably a better way to do this, but it's all I could come up with.
Closes https://github.com/statamic/ideas/issues/936.
=> [6.x] Blueprints fieldtype so we can style the Blueprints setting

resources/js/components/entries/PublishForm.vue
Same as #10876, but ... more 🫣 (see Discord)
=> [5.x] Further increase trackDirtyState timeout

resources/views/assets/index.blade.php, resources/views/components/empty-screen.blade.php, src/CP/Navigation/NavItem.php, tests/Antlers/Runtime/NamedSlotsTest.php, tests/CP/Navigation/NavTest.php, tests/CommandPalette/ContentSearchTest.php, tests/Feature/Assets/AssetIndexTest.php, tests/Feature/Collections/Blueprints/StoreBlueprintTest.php, tests/Feature/Collections/ViewCollectionListingTest.php, tests/Feature/Taxonomies/Blueprints/StoreBlueprintTest.php
This pull request fixes the failing tests on the `ui` branch, making it easier to spot test failures caused by PRs.
=> [6.x] Fix failing tests on `ui`

resources/js/package/vite-plugin.js
This fixes a vite error when you try to run the build but you have two files (e.g. a js file and a css file).
The issue was the iife format isn't supported when you have multiple entry points, but we needed iife for the globals to work. This reworks how globals are resolved by rewriting the imports at compile time.
(You'll still need to run `vite build --watch` rather than `vite` for the moment.)
=> [6.x] Fix multiple Vite entry points

resources/js/components/ui/Combobox.vue
=> [6.x] Prevent combobox input from being autofilled

resources/js/components/fieldtypes/ToggleFieldtype.vue
It fixes the things or it gets the hose again.
=> [6.x] Fix read-only toggles. Closes #12090

src/Fields/Section.php
=> [6.x] Fix error when section is collapsible, but not collapsed by default

resources/js/components/blueprints/Builder.vue
=> [6.x] Fix broken blueprint builder after validation error

resources/js/components/fieldtypes/bard/Set.vue
Copies #12148 and applies it to Bard sets too.
=> [6.x] Fix badges in bard set handles

resources/js/components/command-palette/CommandPalette.vue
=> [6.x] Don't hard code `/cp` in command palette URL

resources/lang/nl/messages.php
=> [5.x] Update messages.php for Dutch translations

src/Addons/Addon.php
Tiny little helper to save a few lines of code and add defaults
=> [6.x] Addon setting helper

src/Modifiers/CoreModifiers.php, tests/Modifiers/TimezoneTest.php
=> [6.x] Fix timezone modifier altering original value

resources/js/components/fieldtypes/VideoFieldtype.vue, resources/js/components/ui/Input/GroupAppend.vue, resources/js/components/ui/Input/GroupPrepend.vue
Fix some prepend/append things, making them consistent with each other.
This also fixes the video field, where its input had a border, which would butt up against the `URL` prepend.
=> [6.x] Prepend append consistency

src/Fieldtypes/Width.php
=> [6.x] Make Base & Large translatable in width field type

resources/js/components/ui/Combobox.vue, resources/js/components/ui/Select/Select.vue
=> [6.x] Make 'Select...' translatable

resources/views/terms/empty.blade.php
=> [6.x] Fix string on terms empty state

resources/js/components/assets/Browser/Browser.vue
=> [6.x] Hide "Customize Columns" button in Grid mode

resources/lang/en/messages.php
=> [6.x] Improve term template instructions

packages/ui/src/CodeEditor.vue, resources/css/components/fieldtypes/bard.css, resources/css/components/fieldtypes/markdown.css, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue, resources/js/components/fieldtypes/replicator/Set.vue
This closes #12526. It mostly involves accounting for the border px value of the outer containers so we close the gap a little more
=> [6.x] Border radius inception

resources/lang/fr/fieldtypes.php, resources/lang/fr/messages.php, resources/lang/fr/permissions.php
=> [6.x] French translations

resources/lang/it.json
The string "Start typing to search." was not translated to italian language
=> [5.x] Italian translations

resources/js/components/structures/PageTree.vue, resources/js/pages/collections/Empty.vue, resources/js/pages/collections/Index.vue, resources/js/pages/layout/Layout.vue, resources/js/pages/layout/architectural-background.js, resources/js/pages/navigation/Index.vue, resources/js/pages/navigation/Show.vue, resources/js/pages/taxonomies/Empty.vue, resources/js/pages/taxonomies/Index.vue, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php
Passing a prop was a bit derpy. This adds a helper function like the body classes.
=> [6.x] Wire up architectural line backgrounds in Inertia
