statamic/cms

src/Console/Commands/stubs/addon/TestCase.php.stub, src/Testing/AddonTestCase.php, src/Testing/Concerns/PreventSavingStacheItemsToDisk.php, src/Testing/Concerns/PreventsSavingStacheItemsToDisk.php, tests/PreventSavingStacheItemsToDisk.php, tests/TestCase.php
This pull request makes a couple of changes around addon testing:
* Moves the `AddonTestCase` introduced in #9573 into the `Statamic\Testing` namespace
* Makes the `PreventSavingStacheItemsToDisk` trait available for addons
* This trait prevents Stache items from being kept around on the disk after the test suite has finished running. 
* I had to make some changes to the trait in order for the paths to be correct. Otherwise, the Stache files would live in `vendor/statamic/cms/src/Testing/Concerns/__fixtures__`.
=> [5.x] Addon Testing Changes

src/Providers/EventServiceProvider.php
This pull request fixes an issue with Laravel 11 where event listeners weren't being triggered when they should have been.
Fixes #9862.
=> [5.x] Fix event listeners not being triggered with Laravel 11

src/Console/Please/Application.php, src/Console/Please/Kernel.php
This pull request fixes two issues with Please commands on Laravel 11:
* It fixes an issue where an app's commands in `app/Console/Commands` with the `RunsInPlease` alias weren't available with Please. Updating `getArtisan` to be inline with Laravel's method fixes that.
* It fixes an issue where Artisan commands couldn't be called using `Artisan::call()`. We "defer" regular non-please commands within please so they don't show up in the listing. We fix this by resolving them when using Artisan::call().
Closes #9875.
Closes #9861.
=> [5.x] Fix issues with Please commands on Laravel 11

src/Testing/AddonTestCase.php, src/Testing/Concerns/PreventsSavingStacheItemsToDisk.php
This pull request fixes some issues I introduced in my previous PR, #9871:
* After testing with the Eloquent Driver, I realised that it was creating the temporary files in paths like this: `tests/__fixtures__/dev-null/Users/duncan/Code/Statamic/eloquent-driver/vendor/orchestra/testbench-core/laravel/content/collections` instead of simply `tests/__fixtures__/content/collections`
* This was only happening for addons, so I refactored the path replacement logic in the trait and configured the default Stache directories in the `AddonTestCase`
* After running the tests, the `tearDown` method is _supposed_ to delete the temporary Stache files. However, after I renamed the `PreventsSavingStacheItemsToDisk` trait in [c0d5f1f](https://github.com/statamic/cms/pull/9871/commits/c0d5f1f9ef4ab0fccacaa84 …
=> [5.x] Fix issues with `PreventsSavingStacheItemsToDisk` trait

src/Assets/AssetReferenceUpdater.php, src/Data/DataReferenceUpdater.php, src/Taxonomies/TermReferenceUpdater.php, tests/Listeners/UpdateAssetReferencesTest.php, tests/Listeners/UpdateTermReferencesTest.php
This PR takes over from where #7555 and #9790 left off, but addresses more edge cases.
Closes and fixes #7555
Closes #9790
Fixes #9701
Fixes #7547
References #7555
References #8114
=> [4.x] Fixes for asset/term reference updater strictness

resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
Closes #9900 by checking the count of available set groups, instead of the existence of an associated set group. I've also added a secondary check, to ensure that the set group has a `display` property defined. That's actually how I stumbled onto this regression in the first place, as it kicks out a label that looks like this (if the `display` is missing):
So this PR requires **both** conditions are met, for the set group label & chevron to be visible:
1. More than one set group option must be available, and
2. The associated set group, if present, must have a `display` defined
Feel free to amend that (or any) part of this PR, and let me know if there's anything else I can do to help this along!
=> [4.x] Fix regression on bard/replicator group set previews

src/API/Cachers/DefaultCacher.php, tests/API/CacherTest.php
This PR adds hashing to API request cache keys to handle long route and query parameters which might exceed limits for cache keys.
Resolves: https://github.com/statamic/cms/issues/9859
=> [4.x] Hash API cache keys the key to handle long route and query parameters

resources/js/components/fieldtypes/grid/Grid.vue
When entering fullscreen mode in the grid field type configuration editor, two headers are unexpectedly added.
=> [5.x] Fix duplicated field config header

resources/css/components/fieldtypes/grid.css, resources/js/components/fieldtypes/grid/Row.vue, resources/js/components/fieldtypes/grid/Table.vue
This pull request fixes an issue where the `row-controls` styles from the Grid fieldtype were messing up the styles of `row-controls` elements in fields in the Grid, for example the List fieldtype.
Fixes #9873.
=> [4.x] Fix Grid styles messing up row-controls of nested fields

src/Contracts/Imaging/UrlBuilder.php, src/Imaging/GlideImageManipulator.php, src/Imaging/GlideUrlBuilder.php, src/Imaging/StaticUrlBuilder.php, tests/Imaging/GlideUrlBuilderTest.php
Since #9616 appends filenames automatically, there's no need to specify filenames manually anymore.
This was an undocumented relic of a feature that let you add a "fake" or "vanity" filename to the end of Glide URLs to be able to improve SEO. Now that's happening automatically rendering this feature irrelevant. This feature was broken in certain situations anyway, like if you tried to add `filename=""` to a glide tag where you are passing the path.
This is technically a breaking change since method signatures are changing. Also, you will need to remove `filename=""` from any `glide` tags otherwise nothing will be output.
=> [5.x] Remove manual Glide filenames

src/Imaging/GlideManager.php
Alternate solution to #9781.
This PR lets you customer the unique hash in Glide-generated files.
By default, the hash is just literally just a md5 hash of the manipulation parameters.
You may want to customize it to make it more human readable for debugging or QA purposes as explained in #9781 or just because you prefer it aesthetically.
You can do this in your AppServiceProvider:
```php
public function register()
{
$this->app->booting(function () {
Glide::generateHashUsing(function (string $source, array $params) {
return collect($params)
->sortKeys()
->map(fn ($value, $param) => "$param-$value")
->join('-');
});
});
}
```
When generating a glide image like this:
```antlers
{{ glide:myimage width="100" height="50" fit="crop" quality="50" }}
```
normally it would be generated to a path …
=> [5.x] Ability to set custom Glide hash

src/Fields/Field.php
This pull request prevents computed fields from being shown as "sortable" in listing tables. 
Since computed fields are by their very nature, computed, we don't store them which means we can't order by them in the query builder. However, the fact it looks like you *could* order by them caused some confusion in #9908.
Closes #9908.
=> [4.x] Prevent computed fields from being sortable in listing tables

src/Console/Please/Kernel.php
In #9877, we unintentionally made the version displayed when running `please` show the Laravel version instead of the Statamic version.
=> [5.x] Fix please version

src/Testing/AddonTestCase.php
This pull request makes the `tearDown` method on our new `AddonTestCase` class protected instead of public.
In my testing, `tearDown` being public was causing issues for addons with Pest test suites. The `setUp` method is already protected.
=> [5.x] Make `tearDown` method protected on `AddonTestCase`

src/Console/Please/Kernel.php, tests/Console/PleaseTest.php
This fixes when `Artisan::call('statamic:something')` is used in a command run via `please`. If you used `artisan`, it would've worked fine.
Closes #9861
=> [5.x] Fix statamic-prefixed commands not working when running Artisan::call() within please

src/GraphQL/ServiceProvider.php, src/Http/Controllers/CP/GraphQLController.php
This pull request drops some code added during the Laravel 9 compatibility PR (#5188) to allow applications to continue using older versions of the `rebing/graphql-laravel` package. 
This code can be dropped now since the version of the package we're using for Laravel 11 compatibility [only supports Laravel 10 and 11](https://github.com/rebing/graphql-laravel/blob/master/composer.json#L39-L40), nothing before that.
=> [5.x] Drop legacy `rebing/graphql-laravel` code

resources/views/graphql/graphiql.blade.php
This pull request updates the version of GraphiQL (the GraphQL IDE) that's available in the Control Panel.
From what I can tell, we were usually a relatively old version of GraphiQL. It's since been redesigned and includes dark mode (the reason I went looking in the first place 👀 ).
For reference, I copied from their [CDN example](https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html).
=> [5.x] Update GraphiQL

src/Stache/Query/EntryQueryBuilder.php
We noticed that #9317 actually made things a bit slower.
When you query by collections, we would a status clause for each query you specified.
However if you don't query for a collection, we would add a status query for _all_ collections. An example of that is if you query entries by only ID. These add up the more collections you have.
This PR improves on that by if you don't query a collection and you query by ids, we automatically query the collections for you. This results on those status nested wheres only being added for appropriate collections.
=> [5.x] Fix slowdown caused by status PR

src/Fieldtypes/Entries.php, src/Fieldtypes/Terms.php
This PR will use blink to prevent unnecessary re-querying on entries and terms fieldtypes when using max_items 1.
On one particular test site, a blog post template a handful of typical taxonomy related bits on the page loaded in about 1.3s. This PR gets it down to about 750ms.
=> [5.x] Blink augmentation of terms and entries fieldtypes

resources/js/components/fieldtypes/VideoFieldtype.vue, resources/lang/en/validation.php
This pull request attempts to fix an issue where it was possible to add HTML into the "URL" input causing a Control Panel 404 page to be shown.
When an invalid URL is passed, an error/warning message will be displayed where the video preview would usually sit:
Related: #9943
Also updates the `url` validation translation to match Laravel (but using inline grammar).
=> [4.x] Prevent passing HTML to the Video fieldtype

src/Providers/ViewServiceProvider.php
This pull request fixes an issue where you could run into "Target class [blade.compiler] does not exist", which is caused by the `registerBladeDirectives` method in our `ViewServiceProvider` being called in the `register` method instead of the `boot` method.
Fixes #9940.
Related: #9732
=> [4.x] Fix "Target class [blade.compiler] does not exist" issue

composer.json, src/Console/Composer/Lock.php, src/Extend/Addon.php, src/UpdateScripts/UpdateScript.php
Requiring the entire composer package isn't necessary. We only need their semver classes.
Ref: #9945
=> [4.x] Require composer/semver instead of composer/composer

src/Http/Controllers/FrontendController.php, tests/Routing/RoutesTest.php
A little addition to #9868 in response to the comments. Route parameters are passed to the closure now:
```php
Route::statamic('uri/{baz}', 'view', function ($baz) {
$bar = gatherDataExpensively($baz);
return ['foo' => $bar];
});
```
=> [4.x] Support route parameters in Statamic routes with closures

src/Http/Resources/CP/Entries/ListedEntry.php
When you have a dated collection with time enabled the time does not appear in the listing column.
This PR fixes it by using date field's `preProcessIndex` method rather than `inPreferredFormat`.
=> [4.x] Fix dated collection listing when time is enabled

src/Data/DataReferenceUpdater.php, tests/Listeners/UpdateAssetReferencesTest.php
This pull request fixes an issue in the `DataReferenceUpdater` (& therefore the asset reference updater), where if `Arr::get()` returned `null`, `Arr::dot()` would error while trying to get a "dotted item" from the array. 
Closes #9930.
=> [4.x] Fix `DataReferenceUpdater` when field data from array is null

src/Structures/Page.php
This reverts #9659. It seemed to be the reason for the slowdown of SSG generation in #9888.
This was a micro optimization for extreme numbers. There doesn't seem to be much of a difference without it for most sites.
Closes #9888.
=> [5.x] Revert caching entry to property on Page instances

src/Console/Commands/InstallEloquentDriver.php
https://github.com/statamic/eloquent-driver/pull/277 adds the ability to have an eloquent token repository so it makes sense that this command would also support migrating to it.
Duncan made this nice and easy with how he set up the original command 🔥 
Requires https://github.com/statamic/eloquent-driver/pull/277
=> [5.x] Add tokens to eloquent cli install

src/Http/Controllers/CP/Navigation/NavigationController.php, src/Policies/NavPolicy.php, tests/Feature/Navigation/EditNavigationTest.php
Currently every user that is allowed to edit a nav (meaning adding new entries etc.) is also allowed to _configure_ a nav (meaning changing the name, max depths etc.). This PR changes this behaviour to only allow the latter with the added `configure` policy, which resolves to the `configure navs` permission.
I don't know if that would be considered a breaking change. It _feels_ like this should be a fix, as the behaviour for e. g. collections works like that, however, I can see that it actually changes something that might be used in a certain way for some people. If you consider it breaking, maybe it might be better to add this to 5.x.
=> [4.x] Use 'configure' permission for configuring navs

src/Routing/ResolveRedirect.php, tests/Data/Entries/EntryTest.php
When you are using the array syntax for redirects, selecting "first child redirect" would result in the URL of the entry being output as `@child`.
It works fine when you have the older string syntax.
This PR fixes it so that the url will actually be the first child's url.
=> [4.x] Fix first child redirects when using array syntax

src/Console/Processes/Composer.php
This PR fixes https://github.com/statamic/cms/issues/9967
If we run a command that doesn't actually install the Stater Kit, we will end up with the `Starter kit config [starter-kit.yaml] does not exist.` error when installing using `php please starter-kit:install` directly, and is one of the ways to trigger the `There was a problem installing...` error when using the Statamic CLI.
The `where composer` command can return multiple results, which this PR handles. Additionally, since we are eventually passing this all to PHP, we need to look for the `composer.phar` file, as the results will often point to either a `composer.bat` file, or a `composer` file which often internally invokes PHP with the `composer.phar` file.
=> [4.x] Fix Starter Kit installation on Windows

src/Console/Commands/StarterKitInstall.php, src/StarterKits/Installer.php, tests/StarterKits/InstallTest.php
When [installing a starter kit from custom branch](https://github.com/statamic/cms/pull/9766)... if branch has a slash, it was failing composer package validation...
This PR fixes that...
References https://github.com/statamic/cms/pull/9766
=> [4.x] Fix `starter-kit:install` with custom branch when branch has slash

config/system.php
Just improving this code comment so people don't need to go searching the docs for where to see the aforementioned "queries".
=> [5.x] Improve the fake sql config code comment

src/Entries/Entry.php, src/Stache/Query/EntryQueryBuilder.php, src/Stache/Query/QueriesEntryStatus.php
This allows Eloquent driver etc to use it without having to reimplement most of it.
This also sneaks in the exclusion of the `augmentationReferenceKey` property when unserializing an entry. For whatever reason, this branch was causing errors in https://github.com/statamic/eloquent-driver/pull/279 and that fixes it. It should be done anyway.
=> [5.x] Extract whereSite query method to trait

src/Fields/Value.php, tests/Fields/ValueTest.php
This PR fixes #9988 by ensuring field default values are not returned when the field's value is falsey.
Additionally, this PR corrects an issue where a falsey default value could not be used.
=> [5.x] Prevent falsey values from returning blueprint defaults

resources/js/components/fieldtypes/date/RangePopover.vue, resources/js/components/fieldtypes/date/SinglePopover.vue
Removed the "x" button from the date field / date range field when it is readonly.
Removing this button eliminates the option to empty the date field. This resolves the issue where, if the date field is required but left empty, the page cannot be saved.
Before, we could click on the cross to clear this field, thus making it impossible to save the entry if the date field is required :
=> [4.x] Remove clear button of readonly date field

src/Console/Please/Application.php
Fix error/regression when trying to list please command options/arguments via `--help`
Before:
After:
=> [5.x] Fix please command `--help` listing

resources/lang/fr.json
This pull request fixes the French translation for the "total characters" string used at the bottom right of Bard fields, it was previously only showing the character limit and not the total count like the English translation.
Fixes #9980.
=> [4.x] Fix French "total characters" translation

resources/js/components/fieldtypes/GroupFieldtype.vue
This pull request fixes an issue with the Group Fieldtype, where the fullscreen button wasn't being correctly positioned.... now it is:
---
Fixes #10007.
=> [4.x] Fix fullscreen button in Group Fieldtype

src/Http/Middleware/CP/AddVaryHeaderToResponse.php, src/Providers/CpServiceProvider.php
This pull request adds a `Vary: X-Requested-With` header to Control Panel responses.
This fixes an issue with the Users listing page on Chrome. If you go onto the users listing table, do any kind of filtering, click on a user, then use the browser back button, you'll see a JSON response instead of the listing page.
This was only happening on the Users listing because it's the Blade view & JSON responses share the same URL, where our other listing pages have separate URLs.
From what I can tell, I believe this issue is only affecting Chrome(ium). The `Vary` header seems to tell the browser which headers cause a different response to be returned - the `X-Requested-With` header is different between the two types of requests so it fixes the issue.
Fixes #9937.
=> [4.x] Add `Vary: X-Requested-With` header to CP responses

resources/js/components/blueprints/Section.vue, resources/js/components/blueprints/Tab.vue
This pull request fixes an issue where it was possible to set the handle for a blueprint tab/section to an empty string, which would lead to a broken publish form.
This PR fixes that by ensuring tabs & sections always have handles, by generating one when editing the tab/section if one hasn't been set in the edit modal.
Fixes #9983.
=> [4.x] Ensure blueprint tabs & sections always have handles

src/Facades/Parse.php
This pull request makes a minor tweak to the `Parse` facade by updating the return type of the `template` method. It now returns an `AntlersString` instance rather than a string.
=> [4.x] Fix docblock on `Parse` facade - `template` returns `AntlersString`

src/Assets/Asset.php, tests/Fieldtypes/AssetsTest.php
This pull request adds the `alt` field to the array of keys included when "shallowly augmenting" assets.
Without `alt` being part of shallowly augmented assets, it means developers need to do an additional API request for every asset they need to get alt text for.
Fixes #10011.
=> [4.x] Include `alt` field in shallowly augmented assets

src/Fields/Value.php, tests/Antlers/Runtime/RuntimeValuesTest.php
This PR fixes #10001 by adding the missing calls to `resolve` within `Fields\Value`.
Without this, `shouldParseAntlers()` would check if `$this->fieldtype` was set, which might not always be the case with the lazy/deferred logic.
=> [5.x] Ensures values are resolved when checking Antlers parsing settings

src/StaticCaching/NoCache/Session.php, src/StaticCaching/NoCache/StringRegion.php, src/StaticCaching/NoCache/ViewRegion.php
This PR removes the randomness within nocache region keys, and instead relies on the session's URL and an incrementing value to determine the nocache region key. This allows the nocache regions to be unique within each session, but also not get regenerated on each request.
An easy way to test this behavior is to run `php please ssg:generate` on a decently sized site that contains `{{ nocache }}{{ /nocache }}` somewhere. Subsequent SSG runs should not cause the `storage/statamic/static-urls-cache` folder size to double on each run.
=> [5.x] Prevent excessive nocache cache growth

src/Tags/Vite.php
Related to #9972.
To inline Vite asset content you can use a new Antlers tag `{{ vite:content src="path/to/vite/asset" }}`
For exemple:
```twig
<script>{{ vite:content src="resources/js/manifest.js" }}</script>
<style>{{ vite:content src="resources/css/critical.css" }}</style>
```
=> [4.x] Add missing Vite content tag

resources/css/components/fieldtypes/button-group.css, resources/js/components/fieldtypes/ButtonGroupFieldtype.vue
This PR introduce a ResizeObserver for the ButtonGroup to handle the Overflowing cases.
Fix: #9044 
Fix: #9830 (Indirectly by removing the `width: 1%` of the `button-group.css` file - which was interfering with this)
- I did not test the performance of such a change as I'm not sure what to look for ? If someone willing to do it and knowing how could have a look ? 
- I was not sure about the use of the `button-group.css` file. If needed, I can naturally put all css in the `resources/css/elements/buttons.css` file.
When the button group can correctly be displayed as a flex row element, then the button still works the same:
When the button group does not have enough place to be displayed correctly without overflowing, then it will be display as a vertical button group:
This also works in …
=> [4.x] Fix ButtonGroup from overflowing

resources/js/components/inputs/relationship/Item.vue, resources/js/components/publish/Container.vue, src/Fieldtypes/Terms.php, src/Http/Resources/CP/Entries/Entry.php, src/Http/Resources/CP/Taxonomies/Term.php
This pull request fixes an issue with the recursive editing check added in #9841, where it'd sometimes prevent editing unintentionally when it shouldn't be.
This issue can be seen in two scenarios:
* Eloquent Driver
* Entries & terms are both using incrementing IDs.
* When you're editing entry `1`, then try to edit term `1` inline, it'd error out because the IDs are the same, even though they're different "things".
* Runway
* Two resources, with a Has Many or Belongs To fieldtype configured.
* In this example, we have a `Product` model and a `Manufacturer` model.
* When you're editing Product `1`, then try to edit manufacturer `1` inline, it'd error out because the IDs are the same, even though they're different models.
To fix this, we're now passing the item's "reference" to the publish …
=> [4.x] Check the reference as part of recursive editing check  

resources/js/components/blueprints/Section.vue, resources/js/components/blueprints/Tab.vue
In #10014, I used the `this.$slugify` helper to generate handles for tabs & sets based on their display names. 
In v5, `this.$slugify` has been deprecated in favour of `Statamic.$slug`. This PR updates that code in v5 to use the `Statamic.$slug` helper.
=> [5.x] Use `Statamic.$slug` helper instead of `$slugify`

src/Tags/Svg.php, tests/Tags/SvgTagTest.php
We made SVG tag sanitization enabled by default and let you opt out per tag.
This PR adds a method you can throw into a service provider to disable it. This may make upgrading simpler for some users.
You can still choose to sanitize per tag by adding `sanitize="true"` like you did in v4.
=> [5.x] Allow opting out of svg tag sanitization

resources/css/components/fieldtypes/button-group.css
This PR fix an issue caused by the #10000.
Button groups that were not part of a button-group fieldtype where wrapped for no reasons.
Example on the Page Listing before this fix:
Fixed by targeting more specificaly the `.button-group-fieldtype-wrapper` :
(Still with some flex shrinking issues, but from before this PR - that would be for another time)
=> [4.x] Fix button group wrapping on non-fieldtype buttons

src/Assets/AssetContainerContents.php
This PR resolves an issue where the `AssetContainerContents` are not updated when creating an asset in a job. 
I tried to submit a failing test but gave up after half a day and three different approaches. I just can't get a test going that reproduces the issue. So I went ahead and created a sample repo with a detailed explanation: https://github.com/aerni/statamic-assets-cache-bug
The fix appears to be quite simple.
I found a couple of related PRs: 
- https://github.com/statamic/cms/pull/6726
- https://github.com/statamic/cms/pull/7467
=> [4.x] Fix queue worker state issue around assets

src/Query/EloquentQueryBuilder.php
This pull request attempts to fix an issue with the `EloquentQueryBuilder@enforceOrderBy` where it was erroring out. The `query` property is [protected on Laravel's Eloquent `Builder` class](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Builder.php#L44), so this PR updates the code to use the `getQuery` method.
```
Exception: Property [query] does not exist on the Eloquent builder instance.
/home/runner/work/eloquent-driver/eloquent-driver/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1943
/home/runner/work/eloquent-driver/eloquent-driver/vendor/statamic/cms/src/Query/EloquentQueryBuilder.php:514
/home/runner/work/eloquent-driver/eloquent-driver/vendor/statamic/cms/src/Query/EloquentQueryBuilder.php:488 …
```
=> [4.x] Fix EloquentQueryBuilder orderby bug

src/Auth/AugmentedUser.php
This pull request adds a `notifications` method to the `AugmentedUser` class to prevent it falling back to the `notifications` method on the `User` when Laravel's `Notifiable` trait is present.
Fixes #9932.
Replaces #9936 & #10022.
=> [4.x] Add `notifications` method to `AugmentedUser`

src/Modifiers/CoreModifiers.php
This pull request fixes an issue with the `is_external_url` modifier where it'd error out when passed a Link field.
The error is actually coming from inside the [`URL::isExternal`](https://github.com/statamic/cms/blob/5.x/src/Facades/Endpoint/URL.php#L224) method, with the caching changes introduced in #9646. The method is expecting a string be passed to it instead of an `ArrayableLink` object like is the case w/ Link fields.
This worked fine in v4 because `ArrayableLink` casts to a string but with the recent caching changes, it's trying to get items in an array using `ArrayableLink` as a key which doesn't work. I though converting the value to a string before it ends up in `isExternal` might be the best way to fix it.
Fixes #10026.
=> [5.x] Fix `is_external_url` modifier with Link fields

resources/js/components/forms/SubmissionListing.vue
This pull request applies overflow styling to the Form Submissions listing table, to improve its usability on mobile.
Copied from #8739.
=> [5.x] Apply overflow styling to form submissions table

src/Translator/Commands/Generate.php, src/Translator/Commands/Review.php, src/Translator/Commands/Stats.php, src/Translator/Commands/Translate.php
This PR adds the return type to the translation commands to keep compatibility with Laravel
Closes https://github.com/statamic/cms/issues/10033
=> [5.x] Fix translation command compatibility

src/Fields/Blueprint.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php
If a key from a dictionary has been utilized for the blueprint title, it should be translated in the collection and taxonomy controller pages.
=> [5.x] Translatable blueprint titles in collection & taxonomy controllers

resources/css/components/fieldtypes/markdown.css, resources/css/elements/tables.css, resources/css/rtl.css, resources/js/components/FavoriteCreator.vue, resources/js/components/data-list/Pagination.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/fieldtypes/TextFieldtype.vue, resources/js/components/nav/Builder.vue, resources/js/components/navigation/View.vue, resources/js/components/roles/PermissionTree.vue, resources/js/components/stacks/Stack.vue, resources/js/components/structures/PageTree.vue, resources/js/components/users/Wizard.vue, resources/views/utilities/git.blade.php, resources/views/utilities/phpinfo.blade.php, src/CP/Breadcrumbs.php, src/Sites/Sites.php, src/Statamic.php
- force direction to the left where necessary
- set default direction to `ltr` in get function
- set arrow direction in rtl
=> [5.x] Fix some RTL issues

resources/js/components/structures/Branch.vue
Currently, when you right click on an entry in a page tree, the "open in new tab" option doesn't show up, which is a little annoying when you want to open up multiple entries at once since clicking on them opens the edit form up in the same tab.
This PR adds the `href` attribute to the tree branch links, which will cause the "open in new tab" option to show.
=> [5.x] Entries Tree View: Make it possible to "open in new tab"

src/Console/NullConsole.php, src/UpdateScripts/MigrateSitesConfigToYaml.php, tests/UpdateScripts/Concerns/RunsUpdateScripts.php, tests/UpdateScripts/MigrateSitesConfigToYamlTest.php
If your sites.php config was referencing `APP_NAME` or `APP_URL`, we automatically convert these to `{{ config:app:name }}` and `{{ config:app:url }}` in our upgrade script 👍 
However, if you referenced other custom env vars, it would just resolve / hardcode them. This PR adds some transparency in the messaging after the end of a successful composer install, so that you can handle these yourself...
Closes #10043
=> [5.x] Improve sites update script output when custom `env()` calls are detected

composer.json
This pull request updates the `ajthinking/archetype` dependency to `^5.0`. This adds support for v5 of `nikic/php-parser`, which PHPUnit seems to require.
Fixes #10028.
Related: https://github.com/ajthinking/archetype/pull/85
=> [5.x] Update `ajthinking/archetype` dependency

resources/js/components/revision-history/Preview.vue, routes/cp.php, src/Http/Controllers/CP/Collections/EntryRevisionsController.php
This pull request fixes an issue where the revision edit URLs were invalid when you were tried to view the revision publish form for an entry in a different collection than the current entry.
Fixes #10034.
=> [5.x] Fix incorrect revision edit URLs

routes/web.php
This  pull request fixes an issue with the `{{ nocache }}` tag and OAuth routes, for applications using the new Laravel 11 application skeleton.
Laravel applications previously included a `VerifyCsrfToken` middleware. However, with Laravel 11 and the slimmer application skeleton, the middleware is no longer included in the app's files and falls back to one in the Laravel framework.
Fixes #10068.
=> [5.x] Fix `nocache` and OAuth routes for Laravel 11 apps

src/Fields/ConfigField.php, src/Fields/Field.php, src/Fields/FieldTransformer.php, src/Fieldtypes/Assets/Assets.php, src/Forms/Fieldtype.php, src/Http/Controllers/CP/Fields/FieldsController.php, tests/Fields/FieldTransformerTest.php
In #9685 we stripped out redundant blueprint configs where they matched the defaults.
This looks to be a bit heavy handed in some situations.
This PR allows certain keys to be forced into the config even when they match the defaults.
Replaces #10054
=> [5.x] Prevent certain blueprint config keys getting stripped out

src/Structures/Nav.php
This pull request fixes an issue where you'd get an error viewing a navigation when one of the associated collections have been deleted.
This PR fixes it in [the same way](https://github.com/statamic/cms/blob/08cb2b70986e0f9d811a2fabc0d05f0b08a02b3a/src/Entries/Collection.php#L835) we handle viewing collections where the associated taxonomies have been deleted. 
Closes statamic/ideas#1164
=> [5.x] Prevent errors when viewing nav after collection has been deleted

src/Fieldtypes/Bard.php
We find anytime we are using Bard fields the default buttons are not what we would want selected, for example we always remove image and table, and rarely use block quote. So you end up deselecting them on every site.
It would be useful to be able to select the defaults so we don't have to do this. It's a 30 second time saver, but it's just one less thing to think about.
I considered using a config for this but theres no existing bard config so it felt like overkill for one setting. Instead I've defined the default buttons as a static property on the bard field type, so you can overwrite them as follows:
```php
// only allow h2 and h3
\Statamic\Fieldtypes\Bard::setDefaultButtons(['h2', 'h3']);
```
=> [5.x] Allow Bard's default buttons to be configured

src/Modifiers/CoreModifiers.php
This pull request fixes another issue with `is_external_url` - this time when an Entry is selected in a Link field, rather than a URL.
https://github.com/statamic/cms/issues/10026 was raised previously and fixed in https://github.com/statamic/cms/pull/10027
Fixes #10072.
=> [5.x] Handle entries in Link field with `is_external_url` modifier

resources/js/components/fieldtypes/SlugFieldtype.vue, resources/js/components/slugs/Slugify.vue, src/Fields/Field.php
The async behavior is more correct as it uses the server-side slug logic, but it's slower because it makes server requests. 
This PR adds the ability to opt out of it when using the `<slugify>` component by adding an `async="false"` prop, or the `slug` fieldtype by adding an `async: false` option.
While I wasn't able to reproduce the completely incorrect slug behavior as described in #9959, I'm guessing that people were able to somehow trigger an issue in the additional debouncing within the Slug JS class itself. Since the async is opted out of in field settings now, it'll be back to how it performed in v4. The only delay is now the standard debouncing when you type into the title field.
It's possible the issue will reappear in other places that still use the async slugging, like the …
=> [5.x] Ability to opt out of async slug behavior, and opt out in field settings

src/Stache/Query/Builder.php
Fixes #10074
Copied from https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Query/Builder.php#L2977
=> [5.x] Wrap columns in query builder

resources/lang/nl.json
Hi!
This is a very small change, but it fixes something that took a little bit of finding out 😅 This PR capitalizes the Dutch translation of "Regards". The default Laravel email signs off with "Regards,", and in the Dutch version it became "vriendelijke groeten,".
=> [5.x] Dutch translations

composer.json
Some packages still require the old version of `nikic/php-parser` which `ajthinking/archetype` requires. This prevents Statamic 5.1.0 being installable.
I don't think there's a problem with requiring v1.
=> [5.x] Bring back support for archetype v1

src/Console/Commands/StaticWarm.php
This PR closes https://github.com/statamic/cms/issues/10089 by setting the site for each URL before it is run through the `UrlExcluder` class. This ensures that the `getBaseUrl()` in the `AbstractCacher` returns the correct site URL on each request.
=> [5.x] Ensure correct exclusion of URLs in static:warm command

src/View/Cascade.php
The `existsIn()` method calls `->in()` inside. The `in()` method is resource consuming when someone has a lot of sites.
This reduce the loading time of this function up to 50%.
=> [5.x] Don't call ->in() twice while hydrating globals

src/Stache/Query/QueriesEntryStatus.php, tests/Data/Entries/EntryQueryBuilderTest.php
This fixes an issue where if you have a collection that is _not_ dated but you have defined `date_behavior` for whatever reason, querying by status would not work correctly. Those entries would get filtered out.
Closes statamic/eloquent-driver#288
=> [5.x] Fix querying by status on non-dated collections

resources/js/components/entries/PublishForm.vue, src/Http/Controllers/CP/Collections/EntriesController.php, src/Http/Controllers/CP/Collections/ExtractsFromEntryFields.php, src/Http/Controllers/CP/Collections/PublishedEntriesController.php
https://github.com/statamic/cms/pull/6842 made it so that the entry publish form values are synced on save. This PR adds the same functionality when you publish/unpublish a revision. This is useful when you have listeners that update entry values on publish/unpublish.
At the moment I've had to duplicate the `extractFromFields` method as this is in a different controller. I had to the same thing in the https://github.com/statamic/cms/pull/6375 for the actions controller. It makes sense to move this method somewhere that all the controllers can use, I'm just not sure where would be best?
=> [5.x] Sync entry form values after revision publish

src/Console/Commands/InstallEloquentDriver.php
This pull request fixes an issue with the `install:eloquent-driver` command where the Eloquent model for entries wasn't being swapped to the special `UuidEntryModel`, used when importing existing entries.
We're updating the `eloquent-driver.php` file using simple string replacement, which didn't work here due to whitespace changes.
=> [5.x] Fix entry model not being updated when importing entries

src/View/View.php
This PR fixes an issue where the current site wasn't resolved correctly when returning a view from an action route. Consider the following scenario:
I'm returning a `View` in a controller from an action route. 
```php
return (new View)
->layout($layout)
->template($template)
->cascadeContent($data);
```
When the `cascade()` is hydrated in the `View` class, it will resolve the `Cascade::instance()`from the container, where it was bound with `Site::current()`.
https://github.com/statamic/cms/blob/5cb5da6c34a5c6ea670266f53c8ceb9abeea4e74/src/View/View.php#L188-L194
https://github.com/statamic/cms/blob/5cb5da6c34a5c6ea670266f53c8ceb9abeea4e74/src/Providers/ViewServiceProvider.php#L39-L41
At the time when the `Cascade` is bound in the container, the current site will be resolved from the …
=> [5.x] Respect the current site when returning a View

resources/js/components/field-conditions/Builder.vue, resources/js/components/field-conditions/Condition.vue
This pull request prevents you configuring multiple conditions for the same field in the blueprint/fieldset builder.
Previously, the "Field" dropdown in the builder allowed you to select fields even if they already had conditions configured against them. Then, when you saved the field, only one of the multiple conditions would actually be saved.
This PR prevents you from doing that until we implement the ability to configure multiple conditions for the same field (see https://github.com/statamic/ideas/issues/1101).
I originally fixed this in #9199. However, after my refactoring of the field conditions builder in #9379 that fix seems to have been lost.
=> [5.x] Prevent configuring multiple conditions for the same field

resources/js/components/users/Wizard.vue
When looking at the Wizard for creating a new user, I noticed that the `id`/`for` pairs for a few fields was incorrect or absent.
This PR corrects these.
=> [5.x] Correct id and for pairs in user sign up Wizard

resources/js/components/users/Wizard.vue, resources/lang/en/messages.php
Pluralize based on expiry hours. Closes #10116
It's a bit redundant but I don't see a better way.
=> [5.x] Pluralize user activation email message

src/Structures/Page.php
This pull request fixes an issue with URL nav items not being augmented properly. 
I managed to track down the issue to some changes made in https://github.com/statamic/cms/pull/9636. As part of those changes, a `getBulkAugmentationReferenceKey` method has been added. It seems like the returned key is unique for entry nav items but wasn't for URL-based nav items.
This PR appends the nav item ID to the returned reference key which seems to fix the issues.
Fixes #10055.
Fixes #10080.
=> [5.x] Fix augmentation issues for URL nav items

src/View/Antlers/Language/Runtime/Sandbox/RuntimeValues.php, tests/Antlers/Runtime/TagsTest.php
This PR fixes #10111 by adjusting some internal bulk augmentation behavior. The fix involves checking the `first()` item of a collection rather than assuming an element always exists at `0`.
=> [5.x] Corrects issue returning some collections from tags

resources/js/components/fieldtypes/TagsFieldtype.vue
While reviewing #9933 I noticed a couple of little things that would be nice to address.
First, setting to close on select. This mimics how the relationship fieldtype works when in taggable mode.
The issue is that when you enter a tag, the dropdown doesn't close, so you can't see the values until you manually close it by hitting escape or clicking away.
Before:
After:
The other thing is that the dropdown is visible even if there are no options. It's not really useful. You can see this in the previous gif. Now you'll only see the dropdown if there are options.
No options:
With options: (Free text entry is still allowed - you're not restricted to just the options)
=> [5.x] Taggable fieldtype tweaks

resources/js/components/entries/Widget.vue
When a Widget, such as "collection", requires pagination, the footer panel was still light, and had no dark styles.
This PR adds styles - not 100% sure if the right background colour was picked, but I think it is close.
Before:
After:
=> [5.x] Fix to add dark mode to Widget pagination background

config/cp.php, resources/views/partials/global-header.blade.php, resources/views/partials/outside-logo.blade.php, src/Http/View/Composers/CustomLogoComposer.php
Dark mode looks awesome! But not all custom logos work on a dark background, such as:
This PR adds support for a second (optional) custom logo URL:
This can be added using the new `STATAMIC_CUSTOM_DARK_LOGO_URL` env.
If it is not included, it will use the `STATAMIC_CUSTOM_LOGO_URL` logo behaviour. In other words, it only uses the dark version of the logo if one has been provided.
This applies to the global header (outside the CP) and the nav bar logo.
=> [5.x] Add support for a dark mode custom logo

resources/js/components/DarkModeToggle.vue, resources/views/partials/head.blade.php
At the moment your theme preference gets saved to your user account.
However if you log out, your preference won't be applied on the login page.
By also saving to local storage, your preference will be maintained when logged out, at least on that browser.
=> [5.x] Save dark mode theme preference to local storage

config/git.php
This pull request attempts to fix #10102, where the `binary` wasn't being correctly pulled through to the commands in the Git config.
I'm not quite sure how I didn't notice this originally but it seems like referencing config settings in the *same* config file doesn't work so this PR references the binary as a variable instead, which in my testing seems to work.
Once this has been merged, I can copy the change over to `statamic/statamic`.
Fixes #10102.
Related: #9793.
=> [5.x] Reference git binary as a variable, rather than config setting

resources/css/components/assets.css, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
This pull request fixes a couple of dark mode styling issues with the Assets Grid & the Assets Fieldtype in Grid mode:
Fixes #10126
=> [5.x] Fix styling issues with Assets Grid & Assets Fieldtype

resources/js/components/forms/SubmissionListing.vue
Looks like I didn't need to add `overflow-scroll` here in #10036, it works fine without it. I only added it because I saw it was being used on another of our listing tables.
This PR removes `overflow-scroll` since it causes a scrollbar to always be shown on the form submissions listing table.
=> [5.x] Remove unnecessary `overflow-scroll` on submission listing

resources/js/components/fieldtypes/replicator/AddSetButton.vue, resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/fieldtypes/replicator/SetPicker.vue
This pull request fixes an issue where it was possible to click on the `add-set-button` and open the set picker, even when the `max_sets` option had been exceeded.
The top instance of `add-set-button` was missing a `v-if` that the bottom one had. Then, to maintain the same spacing, I've added an empty div with the relevant classes.
Fixes #10105.
=> [5.x] Prevent opening set picker when `max_sets` has been exceeded

.github/workflows/pint-fix.yml, .github/workflows/pint-lint.yml, .github/workflows/pull-requests.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/tests.yml
This PR updates the versions of the GitHub Actions workflows.
Some changes are unproblematic in my opinion, but some need some more considerations or are not testable by me.
If you want to run a specific pint version, you can configure that using the following configuration.
```yaml
- name: "Laravel Pint Action"
uses: aglipanci/laravel-pint-action@v2
with:
pintVersion: 1.15.3
```
v1 runs using the latest version of pint as far as I know.
The last of the changes, were on failure of tests and js-tests when the tests were scheduled are not testable by me, if it not works, these changes should probably be reverted.
- technote-space/workflow-conclusion-action
- 8398a7/action-slack (v3 requires explicitly listing the fields)
=> [5.x] Update GitHub Actions workflow versions

resources/css/components/cards.css, resources/css/elements/buttons.css, resources/views/widgets/getting-started.blade.php
So it can be re-used without needing to manually apply Tailwind dark mode classes everywhere.
=> [5.x] Abstract a super-btn component 

.github/workflows/tests.yml
When creating a PR from a branch within the same repo (i.e. not a fork), the current tests workflows gets triggered twice - for both push and pull_request:
This PR adds constraints so that the workflow only runs once.
(Push Event will only be triggered on the `master`, `*.x` and `3.4` branch, See supported versions according to https://statamic.dev/release-schedule-support-policy#support-policy)
I already created a similar PR for the Laravel Framework, with my main reasons being that it is annoying to see always two test runs, double the run time and for environmental reasons of course:
https://github.com/laravel/framework/pull/44053
Branch names can use patterns for Pull Requests:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sh …
=> [5.x] Run GitHub Actions workflows only once

resources/css/components/updater.css
The list items in the Update Release list items (`resources/css/components/updater.css`) do not support dark mode for their list item mark:
This PR addresses this:
Just like https://github.com/statamic/cms/pull/10171, using `dark:` with a pseudo-element was not working, so the same approach is done here.
=> [5.x] Add dark mode support for list items

resources/js/components/fieldtypes/replicator/SetPicker.vue
The current Set Picker is not great in Dark Mode:
This PR improves Set Picker dark mode:
Resolves https://github.com/statamic/cms/issues/10125
=> [5.x] Fix dark mode for Set Picker

resources/css/components/fieldtypes/assets.css, resources/css/components/wizard.css, resources/js/components/users/Wizard.vue
The new User Wizard had poor Dark Mode support:
This PR adds dark mode support:
The one odd part in `resources/css/components/wizard.css` is that the `dark:` prefix for the `:before` and `:after` elements did not get picked up correctly - so added it as a new section which is wrapped with `.dark`. Not sure if I missed something but couldn't get that to work.
=> [5.x] Add dark mode to new User Wizard

resources/js/components/fieldtypes/LinkFieldtype.vue
Fixes #9526
When the link fieldtype is created, it initializes its state from the metadata. (e.g. the dropdown option).
Fresh link fields have nulls in the meta data (the "None" option in the dropdown, for example).
When you switch into live preview, or a bard field gets saved, the components get recreated. Since it gets reinitialized from the meta, it'll reset various things and that's why you see the dropdown revert to "None".
This PR maintains the meta data appropriately.
The meta data is called `initialThis`, `initialThat`, etc and updating those is a _little_ weird, but I don't want to get into renaming those right now.
=> [5.x] Fix link fieldtype state

src/Modifiers/CoreModifiers.php, tests/Modifiers/OnlyTest.php, tests/Modifiers/SelectTest.php
Sometimes it is useful to do more than just pluck a single set of values from an array/collection of items.
Similar to [Laravel's](https://laravel.com/docs/11.x/helpers#method-array-only) `Arr::only` this PR adds an `only` modifier to handle those cases where you need more than one key.
```php
$items = [
['title' => 'Bread', 'slug' => 'bread', 'price' => '2'],
['title' => 'LEGO Coffee', 'slug' => 'lego-coffee', 'price' => '37'],
];
```
```antlers
{{ items | only('title', 'slug') | to_json }}
```
```json
[{"title":"Bread","slug":"bread"},{"title":"LEGO Coffee","slug":"lego-coffee"}]
```
=> [5.x] Add select modifier

src/Modifiers/CoreModifiers.php, tests/Modifiers/FlattenTest.php
This PR passes through the a depth parameter to the underlying `collect()->flatten($depth)` call inside the `flatten` modifier.  It still defaults to infinite if no depth is specified.
```php
$input = [
'ingredients' => [
'spices' => ['garlic', 'cumin', 'ginger', 'turmeric', 'paprika', 'curry powder'],
'vegetables' => ['tomatoes', 'onion'],
'meat' => ['chicken'],
],
];
```
```antlers
{{ data | flatten(1) | to_json }}
```
```json
[
["garlic", "cumin", "ginger", "turmeric", "paprika", "curry powder"],
["tomatoes", "onion"],
["chicken"]
]
```
=> [5.x] Add depth parameter to flatten modifier

src/Auth/Eloquent/User.php
This pull request adds a `merge` method to the Eloquent `User` class. 
The `merge` method already exists on the file `User` class, via the `ContainsData` trait, this PR just adds it to the Eloquent `User` class for consistency.
Fixes https://github.com/duncanmcclean/simple-commerce/issues/1078.
=> [5.x] Add `merge` method to Eloquent User class

src/Modifiers/CoreModifiers.php, tests/Modifiers/KeysTest.php, tests/Modifiers/ValuesTest.php
This PR adds two modifiers `keys` and `values` to complement the already robust array of array modifiers (ie. flip, flatten, sort, etc.)
```php
$data = [
'key1' => 'Value 1',
'key2' => 'Value 2',
];
```
```antlers
{{ data | keys | to_json }}
{{ data | values | to_json }}
```
```
['key1', 'key2']
['Value 1', 'Value 2']
```
=> [5.x] Add keys and values modifiers

resources/css/components/nav-main.css
In the closed nav, there is still one border visible in the window. While it's not necessarily a problem, it could potentially confuse some users like me! :d
=> [5.x] remove border and shadow in closed nav

src/Modifiers/CoreModifiers.php, tests/Modifiers/BardTextTest.php
Ran into a case where `null` was being passed into the `bardText` modifier and an error was being thrown.
=> [5.x] Handle `null` in `bardText` modifier

src/GraphQL/Queries/TermsQuery.php, tests/Feature/GraphQL/TermsTest.php
This PR adds the `site` filter argument on the Graphql `TermsQuery`. This aligns it with the `EntriesQuery` and `GlobalSetQuery` that already had it.
=> [5.x] Add site filter to TermsQuery

src/Modifiers/CoreModifiers.php, tests/Modifiers/ToQsTest.php, tests/Modifiers/ToQueryTest.php
This PR adds a simple `to_qs` modifier that passes the incoming array or array-like value to Laravel's `Arr::query()` helper method.
```php
$params = [
'mode' => 'plaid',
'area' => [51, 52],
'hat' => null,
'transportation' => [
'bike' => true,
'delorian' => false,
],
];
```
```antlers
<a href="/search?{{ params | to_qs }}">Search Now</a>
```
```html
<a href="/search?mode=plaid&area%5B0%5D=51&area%5B1%5D=52&transportation%5Bbike%5D=1&transportation%5Bdelorian%5D=0">Search Now</a>
```
(I don't like the encoded characters any more than you do - but that is the output)
---
Edit: Changed the modifier to `to_qs` per the discussion below.
=> [5.x] Add `to_qs` modifier

src/Facades/FormSubmission.php
This pull request updates the `@see` in the docblock on the `FormSubmission` facade.
=> [5.x] Fix `@see` in docblock on `FormSubmission` facade

src/Query/EloquentQueryBuilder.php
This pull request fixes an issue with the `{{ nocache }}` tag and Statamic's `EloquentQueryBuilder`, where passing eloquent query builder instances to partials would cause an error to be thrown:
```
Serialization of 'PDO' is not allowed
```
This error was happening due to the `PDO` object, which is nested in Eloquent's query builder not being serializable. This PR fixes that by removing the `connection` and `grammar` properties from the query before serializing, then sets them again when unserializing. 
Fixes statamic/eloquent-driver#291.
=> [5.x] Fix error when serializing eloquent query builders

src/Providers/ViewServiceProvider.php, src/View/Antlers/Language/Runtime/GlobalRuntimeState.php, src/View/Antlers/Language/Runtime/StackReplacementManager.php, src/View/Interop/Stacks.php, src/View/View.php
This PR closes #9880 by allowing Antlers and Blade stacks to be used together. This is accomplished by modifying the output of stack-related Blade directives to push/prepend content to Antlers stacks, and pushing/prepending content to Blade stacks from Antlers templates.
This repository contains some example files that may be used to help review this PR: https://github.com/JohnathonKoster/statamic-antlers-blade-stacks
=> [5.x] Allows Antlers & Blade stacks to be used interchangeably

src/Forms/JsDrivers/AbstractJsDriver.php, src/Forms/JsDrivers/Alpine.php, src/Forms/Tags.php, tests/Tags/Form/FormCreateAlpineTest.php, tests/Tags/Form/FormTestCase.php
We use the Alpine form driver and precognition forms on most of our sites. For some forms you need to pass extra x-data beyond what is available in the blueprint fields, for example something from the page context, logged in user etc etc.
It would be useful to be able to add to the x-data Statamic generates, so this PR enables you to do that:
```antlers
{{ form:test js="alpine:form" \x-data='{"something_extra": "value"}' }}
```
or
```antlers
{{ form:test js="alpine:form" :x-data="some_variable" }}
```
I've intentionally made it that passed x-data takes precedence over the x-data Statamic generates, so values can be overwritten if necessary.
=> [5.x] Allow extra `x-data` to be passed to alpine forms

resources/js/components/fieldtypes/replicator/AddSetButton.vue
This pull request fixes a JavaScript error that'd be thrown on Replicator fields, where no "Add Set Label" has been configured.
The `label` was undefined, so calling `.length` on it was causing an error. I wasn't able to reproduce the save issue reported in the issue but this fix prevents the JS error for me.
Fixes #10210.
=> [5.x] Fix JavaScript length error from Add Set button label

resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
Wrapping is better than overflowing, and truncating is often a subpar user experience.
=> [5.x] Allow long set names to wrap. Closes #9838

src/Http/Requests/UserRegisterRequest.php, tests/Tags/User/RegisterFormTest.php
Someone [reported on discord](https://discord.com/channels/489818810157891584/489818810157891586/1245129915880312923) that the changes to the RegisterController / UserRegisterRequest have meant that the password_confirmation is being saved - in eloquent this causes issues as the column doesn't exist, and when file based this adds it to the yaml which it definitely shouldn't.
This PR updates the except in the form request to exclude it from being saved.
=> [5.x] Prevent user registration form from saving `password_confirmation`

resources/css/dark.css
Include `strong` in the dark mode `.prose` class so that it is readable when dark mode is active
Closes #10234
=> [5.x] Ensure `prose`-based strong tag is readable in dark mode

src/Support/Html.php, tests/Modifiers/ObfuscateTest.php
I encountered a bug with using livewire (v3) with Statamic v5 that told me "Malformed UTF-8 characters, possibly incorrectly encoded". After some digging I found out that the obfuscate modifier caused the trouble. I also found out that since PHP 8.2 the `utf8_encode()` is deprecated and should be replaced with a multibyte encoding method. All of this led me to trying `mb_str_split()` and `mb_ord()` for the obfuscate modifier. I reckon the error was caused by a multibyte character in my content and with the multibyte method equivalents I was able to fix it. 
Unfortunately I can't really expand on that problem any further, but I think it should be safely replaceable, since the methods just widen the range of values above 128.
=> [5.x] Use multibyte methods for obfuscate

tests/Modifiers/RandomTest.php
This pesky test fails every now and then and has finally got under my skin enough to fix it.
We copied the test from the `shuffle` test - where this made more sense. The `shuffle` modifier gives you back a 26-item array. That's a huge number of combinations.
But in the `random` modifier, it's pulling _one_ item out of the 26. The odds of you picking the same single number out of 26 is much higher.
This PR bumps 26 possibilities to 5000. If we see a failure now, buy a lottery ticket.
=> [5.x] Decrease the failure rate of RandomTest

resources/js/components/terms/PublishForm.vue
=> [5.x] Fix styling of "Live Preview" and "Visit URL" buttons on terms publish form

tests/Modifiers/RelativeTest.php
When it is the 31st of the month and the previous month has 30 days, the test fails.
This PR addresses that by using fixed dates rather than relying on real life "now".
=> [5.x] Fix relative modifier test

.github/workflows/tests.yml
Windows workflows are very slow.
Turns out the "setup php" step installing certain extensions was the bottleneck. e.g. it tries for ages to install `imagick` and failed anyway. I've removed any non-essential extensions.
=> [5.x] Address slow Windows GitHub actions

src/Revisions/Revisable.php
This pull request moves the handling of parent entries in the `Revisable` trait inside of if statements, since the revisions feature shouldn't be tied to just entries.
=> [5.x] Only run parent code in `Revisable` trait when item is an entry

resources/views/assets/index.blade.php, resources/views/collections/empty.blade.php, resources/views/collections/index.blade.php
There were two templates not referencing the docs URL correctly:
* `resources/views/assets/index.blade.php`
* `resources/views/collections/empty.blade.php`
These show up like this (using Collections as an example):
For example:
```php
@include('statamic::partials.docs-callout', [
'topic' => __('Assets'),
'url' => 'assets'
])
```
Instead of:
```php
@include('statamic::partials.docs-callout', [
'topic' => __('Assets'),
'url' => Statamic::docsUrl('assets')
])
```
In addition, `resources/views/collections/index.blade.php` was set up correctly, but pointing to https://statamic.dev/collections-and-entries which just redirects to https://statamic.dev/collections. This changes that so it's uniform with the `empty.blade.php` changes.
=> [5.x] Fix broken docs URLs; rename docs URL redirect to permalink

src/Fieldtypes/Relationship.php
This pull request adds a new method to allow overriding the `statusIcons` property in Relationship Fieldtypes.
For context: in Runway, I'm adding the concept of "publish states". This will be an opt-in feature, so the status icons are only needed when it's enabled.
=> [5.x] Allow overriding `statusIcons` property in relationship fieldtype

resources/js/components/collections/DeleteEntryConfirmation.vue, resources/js/components/collections/DeleteLocalizationConfirmation.vue, resources/js/components/navigation/RemovePageConfirmation.vue
This fixes the dark mode behavior in the modals noted in #10252 
Closes #10252
=> [5.x] Fix dark mode entry and navigation deletion modals

src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Bard.php, src/Fieldtypes/Files.php, src/Fieldtypes/Grid.php, src/Fieldtypes/Group.php, src/Fieldtypes/Relationship.php, src/Fieldtypes/Replicator.php, tests/Fields/FieldtypeTest.php
In Statamic 5, we introduced some changes to how field configs work. Instead of saving all of a field's config options in a blueprint or fieldset's YAML file, we only saved the config options that *differ* from the option's default. This change is intended to help tidy up blueprints & fieldsets.
As a side affect of this change, it meant that when fieldtypes went to get their config values, they'd only be able to access those config options which are explicitly set in the field config (eg. the config values which differ from their defaults).
We fixed this in #10139, where the `Fieldtype::config()` method now merges in the default values from the fieldtype's config options.
However, as a result of this fix, it means that the `$defaultValue` property set on some of our fieldtypes would be …
=> [5.x] Drop default values from fieldtypes

resources/js/components/entries/Widget.vue, src/Widgets/Collection.php
This pull request fixes an issue in the collection widget, where it wasn't possible to configure the `status` field to display as a column in the collection widget.
Fixes #10256.
=> [5.x] Allow displaying status badges in collection widget

resources/css/core/typography.css
This fixes the CP's addon page description `<code>` block to match the CSS used in the [public addon page](https://statamic.com/addons/stillat/entry-relationships) (i.e., scrollbar for the `<code>` block.)
**Before:**
**After:**
=> [5.x] Prevent text in <code> blocks from extending outside parent <pre> container

resources/css/elements/tables.css, resources/js/components/data-list/Table.vue
This pull request fixes a small UI issue in the collection widget, where hovering on the first item in the table shows a tiny border left radius.
Right now, I've only removed the border radius when it's used in the context of a data table inside a widget. However, if this border radius shouldn't exist anywhere, let me know and I can update this PR. 😄 
Fixes #10260.
=> [5.x] Fix tiny top left border radius on collection widget

resources/js/components/entries/PublishForm.vue, resources/js/components/publish/HasActions.js, resources/js/components/terms/PublishForm.vue, resources/js/components/users/PublishForm.vue
This PR fixes an issue where the dot menu on the publish form will only appear if you have the configure fields permission, but since it now includes actions it should also appear if there are actions avaliable.
Related https://github.com/statamic/cms/pull/6375
=> [5.x] Fix publish form actions permission check

src/View/Antlers/Language/Runtime/StackReplacementManager.php, src/View/Interop/Stacks.php
This PR prevents prepending/pushing stack contents twice to a Blade stack. This seems to be the root cause of #10258, but would need help to validate this. This issue can be reproduced by utilizing a Blade template *and* a Blade layout together.
The changes in this PR address this by not invoking the interop logic to push to Blade if the request is coming from Blade itself. I've added another example page to https://github.com/JohnathonKoster/statamic-antlers-blade-stacks with this setup configured (simply navigate to `/blade-route` to observe the before/after behaviors).
=> [5.x] Prevent adding content to Blade stacks twice

src/Fields/Fields.php, src/Fieldtypes/Replicator.php
This re-implements #8397 and potentially fixes issue #8395
This adds Blink caches to avoid redundant method calls when importing same fields in a nested replicator context.
=> [5.x] Add cache for nested imported fieldsets

config/static_caching.php, src/Exceptions/Concerns/RendersHttpExceptions.php, src/StaticCaching/Cachers/ApplicationCacher.php, src/StaticCaching/Middleware/Cache.php, src/StaticCaching/Page.php, src/StaticCaching/ServiceProvider.php, tests/StaticCaching/ApplicationCacherTest.php
At the moment when you enable static caching and hit a 404-ing page, it does not get cached. If that 404-ing page is heavy, you could visit it repeatedly and increase the load on the server.
This PR has two parts. Both are only supported when using half measure, for now.
This PR allows 404s to be statically cached when using half measure. This is automatic and doesn't require a setting. This likely didn't already exist because it's not possible when using full measure. We handle this by a simple check for whether half measure is being used.
Additionally, this PR allows those 404s to be shared. For instance, the first time you encounter a 404, it will be rendered and cached. Then if you visit another 404ing page, it will serve the previously cached version regardless of the URL.
Each URL …
=> [5.x] Statically cache 404s

src/Fields/Fields.php, src/Fieldtypes/Replicator.php, tests/Fieldtypes/ReplicatorTest.php
https://github.com/statamic/cms/pull/10280 introduced blink caching of the Fields objects in the replicator fields method. This took set indexes into account but not parent paths, which causes the wrong cached objects to be used when you have nested replicators.
This PR fixes that.
I also found an issue with the way field objects loaded from the repository are re-used. They have their parent index set when fetched, but since the same object is being returned it just updates that each time, resulting in one object with the last index set, rather than one object per index. I'm not sure if this is a result of the new blink caching or some other field caching that was introduced with v5, but cloning the object before setting the index fixes it.
=> [5.x] Fix nested field path prefixes

src/Search/Result.php, src/View/Antlers/Language/Runtime/Sandbox/RuntimeValues.php
This PR fixes #10251 by only running the bulk augmentation process in Antlers when a collection contains `BulkAugmentable` instances. Additionally, the `Result` class's `toDeferredAugmentedArray` will now return the results of `toAugmentedCollection` to ensure the extra search data is added.
Notes for review: I had originally looked into simply adjusting the what the `Result` augments to, but decided against that since it could be quite the unexpected change for anyone doing stuff the results of `newAugmentedInstance` on `Result` objects. If curious, that was implemented here: https://github.com/statamic/cms/compare/5.x...JohnathonKoster:cms:search-result-augmentation and makes it Just Work ™️ with the bulk augmentation stuff. However, with _this_ PR, I think having it check for …
=> [5.x] Prevent additional augmented search result data from being lost

src/Data/AbstractAugmented.php
This pull request fixes an issue when augmenting entries, where using a `hook` field would cause an error, due to the addition of the new Hooks functionality introduced in #9481.
Related: statamic/docs#1362.
=> [5.x] Fix using `hook` as field name

src/Console/Commands/InstallEloquentDriver.php
Requires https://github.com/statamic/eloquent-driver/pull/302
This PR adds the ability to install eloquent fieldsets separately to blueprints.
=> [5.x] Split fieldsets out in install eloquent command

src/Tags/Cache.php, tests/Tags/CacheTagTest.php
Similar to #10303, we'd like to define which cache store our cache tags are using, as we need them to use an unprefixed store in a multi-tenant application.
=> [5.x] Allow defining a store in the cache tag

resources/js/components/fieldtypes/FilesFieldtype.vue
This pull request fixes an issue with the "Reupload Asset" action, where the Files fieldtype wasn't being displayed due to console errors.
There's no open issue for this but I've seen it crop up a few times on Discord.
=> [5.x] Fix "Reupload Asset" action

src/Console/Processes/Git.php, tests/Git/GitProcessTest.php
This pull request prevents the `remote: Processed 1 references in total` Git error from being logged by the Git integration. 
Fixes #10329.
=> [5.x] Prevent logging "remote: Processed 1 references in total" Git errors

src/StaticCaching/Middleware/Cache.php, src/StaticCaching/ResponseStatus.php, src/StaticCaching/ResponseStatusTracker.php, src/StaticCaching/ServiceProvider.php
This PR allows developers to figure out if a given response was statically cached or not.
For example, in a custom middleware...
```php
public function handle($request, $next)
{
$response = $next($request);
if ($response->wasStaticallyCached()) {
// the request was previously cached and has just been retrieved.
} else {
// the request was not previously cached and has just been rendered from scratch
}
return $response;
}
```
The `ResponseStatusTracker` class exists purely because we can't put arbitrary properties on classes in PHP anymore. If we could, we'd just pop a `$staticCacheResponseCode` property on the `Request` via a macro. Alas.
The `ResponseStatus` enum will let us have different statuses for static cache types, similar to how Cloudflare does it. e.g. `hit` for when serving …
=> [5.x] Static cache response statuses

src/Console/Commands/InstallCollaboration.php
This pull request fixes an issue in our `php please install:collaboration` command, where Laravel's `install:broadcasting` command wasn't being run, causing things like its config and routing files to not be published.
It seems like this was caused by the `BroadcastServiceProvider` always being part of the app's loaded service providers, even if Laravel's `install:broadcasting` command hasn't been run.
This PR fixes it by simply checking for the existence of the `broadcasting.php` config file, which is created as part of the `install:broadcasting` command.
Fixes statamic/collaboration#101.
=> [5.x] Ensure `install:broadcasting` is run when installing into Laravel 11 application

resources/js/components/structures/Branch.vue
This pull request fixes an issue in the Entries Fieldtype when using Tree View, where collapsing/expending "tree branches" would cause that entry to be selected.
This pull request adds `.stop` to the toggle's click event to prevent it from propagating to the parent click handler which handles the item selecting.
Fixes #10321.
=> [5.x] Prevent entries being selected when collapsing/expending entries in Tree View

package-lock.json, package.json, resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue
Vue countable, which is being used for counting words and characters inside the markdown field (and only fullscreen) has not been updated for a long time: https://github.com/johndatserakis/vue-countable
Other than that, vanilla JS is powerful enough to cover this functionality.
Mainly, this PR will contribute to the upgrade to Vue 3 in the future 🔥
=> [5.x] Migrate from vue-countable

src/Sites/Site.php, tests/Sites/SiteTest.php
When using Antlers, accessing Site attributes is straightforward. For example, you can use:
`{{ site:attributes:company_name }}`
In Blade, the equivalent is often done like this?
`{{ $site->attributes()['company_name'] }}`
However, if the attribute isn't set, this will throw an "Undefined array key" exception. Using `Arr::get` to handle this is an option, but it adds a lot of overhead.
This pull request introduces a simple attribute helper:
`{{ $site->attribute('company_name') }}`
As a bonus, this helper "supports" dot notation and allows you to provide a fallback value.
=> [5.x] Provide Site attribute helper

src/StaticCaching/ServiceProvider.php
The shared error pages introduced in https://github.com/statamic/cms/pull/10294 currently throw a "Region not found" error when you use a nocache tag and hit a second URL. This is because there's only one cached page under a fake URL, but nocache is saving/fetching the region based on the actual URL.
This PR fixes it by setting the no cache session's URL to the fake one when calling `fakeStaticCacheStatus`.
=> [5.x] Fix nocache tags on shared error pages

src/Fields/FieldTransformer.php, tests/Fields/FieldTransformerTest.php
In our site builder, we have field sets that link to other fieldset fields:
```yaml
-
handle: image_asset
field: 'simple::image_asset.image_asset'
```
When you try to load a blueprint containing this, you get an error :
```
ErrorException: Undefined array key "type"
/Users/erin/Development/cms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:256
/Users/erin/Development/cms/src/Fields/FieldTransformer.php:152
/Users/erin/Development/cms/src/Fields/FieldTransformer.php:128
```
This is because Statamic's `Arr` helper class is used and it converts `:`'s to `'.'` so you get `simple..image_asset.image_asset` as the key, which isn't found.
=> [5.x] Fix linking to addon fields

src/Http/Controllers/CP/Collections/EntryRevisionsController.php, tests/Feature/Entries/EntryRevisionsTest.php
Fixes: https://github.com/statamic/cms/issues/10331
When clicking on the 'View History' button of an **unpublished entry** in the CP, the revision history panel loads indefinitely.
The called route `cp/collections/{collection}/entries/{entry}/revisions` fails with error 500.
```
Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameter for [Route: statamic.cp.collections.entries.revisions.show] [URI: cp/collections/{collection}/entries/{entry}/revisions/{revision}] [Missing parameter: revision].
```
Apparently the working copy of the entry included in the entry's list of revisions has no id, as it is not associated with another revision. But this id is necessary to create a link in the list of revisions.
Using an empty link fixes this problem, as the working copy …
=> [5.x] Fix broken revision links on unpublished entries

resources/js/components/Preference.js, resources/js/components/data-list/FilterPresets.vue, src/Http/View/Composers/JavascriptComposer.php
This pull request hides the "Rename" and "Delete" options for default filter presets, since renaming & deleting doesn't *really* work for them.
Fixes #10278.
=> [5.x] Hide "Rename" and "Delete" options for default filter presets

src/Git/Git.php, src/Support/Html.php
While implementing an company-wide errorlog that tracks errors on all our websites, including Statamic-based ones, it throws errors we cannot fix. Therefore I have added some ternary operators to mute those errors. I am not a PHP prodigy, so if you have a better idea of fixing it, be my guest 🤙🏻 
Also I found many functions have PHPDoc description of input and return types, but isn't it better to have it also inside the function's body?
Thanks for clarification!
=> [5.x] Resolving PHP Deprecated errors

src/Console/Commands/SupportDetails.php
The `support:details` command offloads its work to the `about` command. When using a version of Laravel that didn't have the `about` command, it would render its own output. Now that Statamic only supports versions of Laravel that contains the `about` command, this fallback logic can be removed.
=> [5.x] Remove old logic from support details command

resources/js/components/entries/PublishForm.vue, resources/js/components/revision-history/History.vue, resources/js/components/revision-history/Revision.vue, src/Http/Controllers/CP/Collections/RestoreEntryRevisionController.php
This pull request fixes an issue where the "Restore Revision" button would be shown in a revision preview stack, even when the user is missing the relevant permissions.
Fixes #10279.
=> [5.x] Hide "Restore Revision" button when user is missing relevant permissions

src/Extensions/FileStore.php, src/Providers/CacheServiceProvider.php, tests/Extensions/FileStoreTest.php
We have a customized file driver for the cache that will organize any Stache related keys into a simplified file structure for ease of debugging.
This would only affect your default cache store.
This PR changes it so that _any_ store using the file driver will be changed to use our custom version. This is useful along with #10303.
We are newing up the FileStore [identically to how Laravel does it](https://github.com/laravel/framework/blob/7100359775330c7485cf5e65d78aa279cd483c72/src/Illuminate/Cache/CacheManager.php#L149-L153) now which would also fix custom `lock_path` not working.
Additionally, this PR avoids a nested `stache` directory if you point your cache store to a directory already named `stache`.
The cache driver named `statamic` is now deprecated in favor of just using `file`.
=> [5.x] Custom file cache store adjustments

src/Assets/Asset.php
This PR changes the visibility of Asset::clearCaches from private to protected, to allow it to be overridden by the eloquent driver. [See the conversation here](https://github.com/statamic/eloquent-driver/issues/307).
=> [5.x] Make Asset::clearCaches protected

README.md
Providing a clearer title and explanatory note at the top of the readme, to help new users understand the differences between the two Statamic repositories.
Also moving the note to using the Github markdown styled alerts.
=> [5.x] Clarify Statamic repository differences in README

src/Modifiers/CoreModifiers.php, tests/Modifiers/WhereTest.php
This PR adds the ability to pass operators to the where modifier, so that you can do checks like "where not" and "where greater than":
```antlers
{{ products | where('status', '!=', 'hidden') }}
```
Any operators supported by the [collection where method](https://laravel.com/docs/11.x/collections#method-where) can be used.
=> [5.x] Support operators in where modifier

src/Http/Controllers/FormController.php, tests/Tags/Form/FormCreateTest.php
As [discussed here](https://github.com/statamic/cms/discussions/10375#discussioncomment-9923796), throwing a ValidationException during a precognitive/fetch request returns a different errors response format to 'normal' errors, due to how formFailure was handling it.
This PR updates the logic to return the standard ValidationException response when the request wants it.
=> [5.x] Refactor frontend formFailure to handle precognitive and fetch exceptions

resources/js/components/fieldtypes/bard/Image.vue
Because you're not deleting the image, just removing it from the content.
=> [5.x] Rename "Delete" to "Remove" for clarity.

resources/js/components/inputs/Textarea.vue
Because this element is aligned to the right, it creates a larger-than-normal gap between this field and the next one below it. This change will pull the next field up by the proper amount so it looks the same whether it's there or not.
=> [5.x] Add negative bottom margin to Textarea's character counter

resources/css/components/outside.css
This PR fixes the CSS for the CP background when dark mode and the "rad" theme are enabled.
Most (if not all) browsers ignore a CSS background shorthand specification with color and multiple gradients. Therefore, this line was a problem:
`background: #212223 radial-gradient(at 32.6% 91.5%, #142038 0px, transparent 50%), radial-gradient(at 87.4% 39.4%, #353945 0px, transparent 50%), radial-gradient(at 84.6% 52.5%, #171717 0px, transparent 50%);`
Screenshot before:
Screenshot after the change:
=> [5.x] Fix CSS for dark mode cp login background

src/Console/Commands/StaticWarm.php, src/Console/Commands/StaticWarmJob.php, tests/Console/Commands/StaticWarmJobTest.php
This pull request fixes an issue with the `static:warm` command, where you couldn't queue warming **and** provide HTTP Auth credentials.
The HTTP Auth credentials were only being used in the `StaticWarm` command itself when newing up the Guzzle client. Those details weren't being passed to the `StaticWarmJob`, which is responsible for newing up it's own Guzzle client.
No issue, came out of a support ticket.
=> [5.x] Pass the Guzzle config to the StaticWarmJob

resources/js/components/entries/PublishForm.vue
In https://github.com/statamic/cms/pull/6375 and https://github.com/statamic/cms/pull/10095 I added updating the publish store with values from the server after actions or revison publish, but they did not disable the dirty state tracking during that update, which can result in the store having an invalid dirty state if something changed on the server.
This PR fixes it.
=> [5.x] Fix dirty state after entry action or revison publish

resources/views/widgets/updater.blade.php
=> [5.x] Fix updater widget icon in dark mode

src/Stache/Stores/ContainerAssetsStore.php
This PR addresses a bug where S3 zero-byte "folders" do not send a "type" element. Debugging steps are shown below.
1. I set up S3 as my asset container
2. I created a folder via the Statamic UI
3. I run stache:clear (or try to access the cache utilities page in the cp):
```
php please stache:clear
ErrorException
Undefined array key "type"
at vendor/statamic/cms/src/Stache/Stores/ContainerAssetsStore.php:84
80
81    private function getFiles()
82    {
83        return $this->container()->listContents()->reject(function ($file) {
->   84            return $file['type'] !== 'file'
85                || $file['path'] === ''
86                || $file['dirname'] === '.meta'
87                || Str::contains($file['path'], '/.meta/')
88                || in_array($file['basename'], …
```
=> [5.x] Allow for undefined file type in ContainerAssetsStore

src/Data/AbstractAugmented.php
PR https://github.com/statamic/cms/pull/9636 introduced a refactor to the `AbstractAugmented` class that broke a custom augmented class of mine. I need to be able to customize the returned `Value` object. This used to be possible by overriding the `wrapValue` method. However, the PR added some new methods that are currently `private` and can't be overridden.
This PR changes the visibility of those methods to `protected`. I talked to @JohnathonKoster about it and got green lights for this change.
=> [5.x] Change method visibility in `AbstractAugmented` class

resources/js/components/assets/Browser/Browser.vue, resources/js/components/assets/Selector.vue, resources/js/components/data-list/Pagination.vue, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/js/components/fieldtypes/bard/Image.vue, resources/js/components/fieldtypes/bard/LinkToolbar.vue, resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue, src/Http/Controllers/CP/Assets/RedirectsToFirstAssetContainer.php
This pull request removes container tabs from the Asset Manager, in favour of navigating between asset containers using the Control Panel navigation.
The asset container tabs were inherited from v2 and we don't really use tabs for navigating between "things" elsewhere, so we thought just removing them would be the easiest option.
By removing the tabs altogether, it means developers can re-order & hide asset containers by using the CP Nav customizer. This saves us needing to build a special way to re-order asset containers, as suggested in #10177.
In addition to removing the tabs, I've also tweaked the "redirect to first container" logic so it takes into the account any re-ordering of asset containers that has taken place in the CP nav customzer. 
Closes #10177.
Closes #10285.
Closes …
=> [5.x] Remove container tabs from Asset Manager

resources/js/components/data-list/FilterPresets.vue
During the upgrade to Vue 3, we found out about a small issue related to reactivity. The dropdown is not properly removed after the unmount. With this commit, this is now fixed.
=> [5.x] Open modal instead of immediate deletion on click

src/Fields/Value.php
PR https://github.com/statamic/cms/pull/9636 introduced the concept of transient values that are only resolved once they are needed. This PR fixes an issue that would make it impossible to get the `augmentable` from the Value, as it is never resolved.
Consider this simple tag:
```php
class Resolver extends Tags
{
public function index()
{
dd($this->context->get('id'));
}
}
```
This is the dump: 
Getting the augmentable would return `null`:
```php
class Resolver extends Tags
{
public function index()
{
dd($this->context->get('id')->augmentable());
}
}
```
So we need to resolve the value in the `augmentable()` method first to be able to get the augmentable entry:
=> [5.x] Fix augmentable not resolved in transient values

resources/js/components/data-list/Filter.vue
This pull request fixes an issue when using Toggle fields in data list filters, where changing the value between true/false wouldn't trigger the data table to be refreshed.
It looks like this was happening due to Underscore's `_.isEmpty` function considering `true`/`false` to be empty, causing the toggle field's value to be filtered out before updating the filter's values.
I've replaced the check with a simple "is null or undefined" check which seems to fix the issue.
Fixes #10194.
=> [5.x] Fix toggle fields in data list filters

resources/js/components/entries/PublishForm.vue
Right now if you have the ability to create/edit an entry but NOT the `Manage Publish State` permission, the "publish" button says "Publish" instead of "Create Revision".
No behaviour is changed, only the name.
=> [5.x] Use `Create Revision` instead of `Publish` in publish form if no publish permission 

src/Tags/Concerns/GetsQueryResults.php, tests/Tags/Collection/EntriesTest.php
Throw an error, [as per Jason's suggestion here](https://github.com/statamic/cms/discussions/10407#discussioncomment-9990452) when trying to use `paginate` collection tag parameter with incompatible params like `limit` and `chunk`...
```antlers
{{ collection:articles paginate="10" limit="50" }}
{{ collection:articles paginate="10" chunk="50" }}
```
This is obviously [kinda confusing](https://github.com/statamic/cms/discussions/10407#discussion-6909445) because `limit` and `chunk` are completely and silently ignored in the above scenarios.
Introducing exceptions may seem like a breaking change, but technically these params were never meant to work together like this; It would only be breaking if people are relying on this already non-functional combo of tag params.
=> [5.x] Prevent incompatible pagination parameter combinations

.github/workflows/tests.yml, src/View/Antlers/Language/Utilities/StringUtilities.php
This PR removes a small papercut where you cannot use  the `<?xml ... ?>`  tag when the PHP option `short_open_tag` is enabled. This PR uses a temporary placeholder to preserve them while sanitizing.
=> [5.x] Preserve <?xml tags when sanitizing PHP short open tags

src/Entries/Entry.php
This PR makes `config` available to live preview url generation, so you can use config values to determine the URL (eg by setting an .env value).
=> [5.x] Pass `config` to live preview targets url generator

resources/views/partials/outside-logo.blade.php
This pull request prevents the Dark Mode gradiant from tinting custom logos on the authentication pages.
Fixes #10420.
=> [5.x] Prevent dark mode gradient affecting custom logos

src/Console/Commands/StaticWarm.php
There's an issue where if you run `static:warm` immediately after a cache clear, entries from a structured collection will 404.
This is because mid-query for entries, the `uri` indexes get built (as expected) but for structured entries their uris come from their structures. As part of that, the trees are validated, which also queries the same entries, which don't have uri yet. The uris get indexed as nulls, and therefore will 404 when they are searched for later.
Or, something close to that. 😅
This PR is really a workaround, but seems to resolve it.
If you were to run `stache:warm` before `static:warm`, or if you visited any pages before running `static:warm`, you wouldn't have this issue.
=> [5.x] Warm structure trees during static warm

resources/js/components/fieldtypes/FilesFieldtype.vue, src/Fieldtypes/Files.php
This pull request fixes an issue with the Files Fieldtype (which powers the "Re-upload asset" action). 
In #10272, we dropped the default values from various fieldtypes, including the Files fieldtype, since the default values weren't really needed.
This caused an issue with the Files fieldtype which we attempted to fix in #10333, however, that PR only fixed the *rendering* of the fieldtype. You'd get another error related to the `value` not being set after uploading a file.
This PR fixes it by reverting the fix from #10333, and instead returning an empty array in the fieldtype's `preProcess` method so that `value` is never null.
Fixes #10440.
=> [5.x] Fix files fieldtype

src/Tags/Svg.php, tests/Tags/SvgTagTest.php
This PR makes sure that the SVG tag adds additional parameters after sanitization. This solves the problem of parameters being unintentionally removed by the sanitizer.
Until 5.0 this was possible without any issues:
```
Antlers:
{{ svg src="logo" x-ref="logo" }}
Result:
<svg x-ref="logo" xmlns="...
```
But since 5.0 this has changed, as sanitizing is active by default:
```
Antlers:
{{ svg src="logo" x-ref="logo" }}
Result:
<svg xmlns="...
```
We can set `sanitize="false"` of course. But in my opinion, it would be nicer to have the best of both worlds. First sanitizing potentially dangerous code, then merge additional parameters.
This relates to #9948 and potentially to #10161 as well.
=> [5.x] Merge additional params after SVG sanitization

resources/css/components/tabs.css, resources/css/elements/buttons.css, resources/css/rtl.css, resources/js/components/DarkModeToggle.vue, resources/js/components/assets/Editor/Editor.vue, resources/js/components/blueprints/Tabs.vue, resources/js/components/entries/Listing.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/fieldtypes/assets/AssetTile.vue, resources/js/components/fieldtypes/bard/Image.vue, resources/js/components/fieldtypes/bard/LinkToolbar.vue, resources/js/components/forms/SubmissionListing.vue, resources/js/components/terms/Listing.vue, resources/js/components/users/Listing.vue, resources/js/components/users/Wizard.vue, resources/views/partials/global-header.blade.php, resources/views/playground.blade.php
The Super button uses `space-x-4`, which has not been styled for RTL layout.
=> [5.x] Reverse spaces in RTL

src/Listeners/Concerns/GetsItemsContainingData.php
We were doing some localization mapping on the collection level, which is [no longer needed](https://github.com/statamic/cms/issues/3274#issuecomment-1402636955) since https://github.com/statamic/cms/pull/6318.
=> [5.x] Clean up reference updater localization mapping logic

config/cp.php, resources/views/partials/global-header.blade.php, resources/views/partials/outside-logo.blade.php, src/Http/View/Composers/CustomLogoComposer.php
**Description**
Add an option to display the site's name in plain text in the control panel, as suggested in [feature idea #1185](https://github.com/statamic/ideas/issues/1185).
**Advantages of doing that**
- Consumes less bandwidth than a logo file
- Light/dark mode comes along for free
- Less setup for new projects: just paste in the name
**Details**
- When defined, logo image urls take precedence over logo text
- The logo text goes into a new `statamic.cp.custom_logo_text` config key
- Can also be set from a new `STATAMIC_CUSTOM_LOGO_TEXT` environment variable
- I guess this can be backported to 4.x without problems
- As far as I can tell, there's currently no tests for the custom logo behavior, so I haven't added any
- Manually tested, though :)
**Screenshots**
 
 
 
Closes …
=> [5.x] Display custom logo as plain text

resources/css/components/fieldtypes/radio.css, resources/css/cp.css, resources/js/components/fieldtypes/RadioFieldtype.vue, resources/svg/icons/regular/radio-deselected.svg, resources/svg/icons/regular/radio-selected.svg
This gives us better control over contrast, dark/light, and disabled states — something native HTML cannot do, sadly. Closes #10427.
=> [5.x] Radio Fieldtype gets custom button icons

resources/js/components/entries/CreateEntryButton.vue, resources/js/components/terms/CreateTermButton.vue
If you have a ton of blueprints (or a tiny screen), the picker is a bummer. This fixes that and closes #10436.
=> [5.x] Make Blueprint Picker scrollable

resources/js/components/data-list/Pagination.vue, resources/js/components/entries/Widget.vue
Widgets are for quick glances, not browsing thousands of entries. Closes #10348.
=> [5.x] Hide data list pagination page links on collection widget

resources/views/partials/licensing-alerts.blade.php
This PR adds dark mode classes to the request failed warning at the bottom of the CP. That banner now has the same styling as warning banners on the licenses page.
Before:
After:
=> [5.x] Add missing dark mode styles for license request failed warning

src/Http/Controllers/CP/Utilities/CacheController.php
This pull request changes how the Cache Manager utility clears the static cache, to bring it inline with the `static:clear` command.
Currently, the `static:cache` command calls the `StaticCacheManager::flush()` method. However, the "Clear" button on the cache manager utlity calls the cacher's `flush` method (eg. `FileCacher::flush()` or `ApplicationCacher::flush()`).
The `flush` method on the `StaticCacheManager` does end up calling the cacher's `flush` method but it also deals with clearing other static caching related stuff from the cache (like nocache URLs).
This isn't causing any issues right now, however, as part of #10403, I'm adding a `StaticCacheCleared` event which I'd like to be able to dispatch in one place (the `StaticCacheManager`, rather than in two places).
=> [5.x] Use StaticCache facade in Cache Manager utility

src/Events/SiteCreated.php, src/Events/SiteDeleted.php, src/Events/SiteSaved.php, src/Sites/Sites.php, tests/Sites/SitesConfigTest.php
Adds `SiteCreated`, `SiteSaved`, and `SiteDeleted` events.
References https://github.com/statamic/ideas/issues/1169
References https://github.com/statamic/cms/issues/10403
References https://github.com/statamic/cms/pull/10459
=> [5.x] Add Site events

src/Data/AbstractAugmented.php, src/Fields/Field.php
This pull request fixes an issue where it wasn't possible to use `value` as a field handle, due to the fact that augmentation was calling the `->value()` method on the entry (which errored, due to not enough parameters being provided).
This PR fixes that by adding `value` to an "allow list" we have for field handles which match methods on data objects. 
Fixes #2495.
=> [5.x] Allow using `value` as a field handle

config/git.php, src/Events/Concerns/ListensForContentEvents.php, src/Events/SiteDeleted.php, src/Events/SiteSaved.php, tests/Git/GitEventTest.php
We should git track sites.yaml by default too, now that we have the content file events to do so.
References https://github.com/statamic/cms/pull/10460
=> [5.x] Track sites.yaml path in git integration config

resources/js/components/publish/SaveButtonOptions.vue
This pull request fixes an issue with the `save-button-options` component, where the Radio buttons were huge, after its recent refactoring in #10453.
The CSS to set the height/width of the icon was relying on a class automatically added to fields in publish forms. However, it wasn't there in the save buttons component, causing the huge icons.
This PR also adds a smidge of padding at the top and bottom of the radio buttons, to add some additional spacing, like it had before the recent refactor.
=> [5.x] Fix styling issues with the `save-button-options` component

resources/js/components/fieldtypes/TimeFieldtype.vue
This pull request fixes an issue with the Time Fieldtype, where its value would end up being saved in the localized entry's data, even when the field wasn't marked as "Localizable" in the blueprint.
This was happening due to the fact the fieldtype was updating the field's value in the publish container, which subsequently added the time field to the `localizedFields` array, which is the array that contains the fields that should end up getting saved to the entry's data.
To fix this, I've wrapped the "update the value" code in a conditional to check whether the value has actually be changed or not.
No issue, related to support ticket 5742.
=> [5.x] Prevent updating time fieldtype value if it hasn't changed

src/Console/Commands/StaticWarmJob.php
This PR implements `ShouldBeUnique` on the `StaticWarmJob` and makes sure each job gets a unique ID based on the path of the URL it's supposed to warm. 
I'm fairly positive I'm doing stuff wrong here, but I wanted to give it a shot anyways :-).
Closes #10404
=> [5.x] Use `ShouldBeUnique` on  `StaticWarmJob`

src/Sites/Sites.php
I'm working on eloquent storage for sites here: https://github.com/statamic/eloquent-driver/pull/322
This PR adds some refactoring to allow eloquent to save sites without having to recreate the event firing logic, and also pulls the default into its own function so we can call it too.
=> [5.x] Refactor sites to allow eloquent storage

resources/js/components/login/login.js, resources/views/auth/login.blade.php, resources/views/auth/passwords/reset.blade.php
This fixes an issue where some people were seeing 419 errors after logging in.
We found that the reason was typically due to submitting the form twice.
Either by:
- Clicking the log in button multiple time
- Using 1Password to auto-fill their credentials, which submits the form, and then the user clicking log in before the redirect happens.
It seems that the first time the form is submitted, you get logged in and your csrf token is updated. Then if you click it a second time, the old token is submitted but no longer matches your current one, resulting in the error.
This PR fixes that issue by disabling the submit button while the form is submitting, preventing you from submitting twice.
This PR gives the same treatment to the reset password form which has the same issue.
=> [5.x] Prevent double login causing 419 CSRF token mismatch

resources/js/components/inputs/relationship/Item.vue, resources/js/components/inputs/relationship/RelationshipInput.vue, resources/js/components/inputs/relationship/SelectField.vue, src/Fieldtypes/Entries.php, src/Fieldtypes/Relationship.php, src/Fieldtypes/Terms.php, src/Http/Resources/CP/Entries/EntriesFieldtypeEntries.php, src/Http/Resources/CP/Entries/EntriesFieldtypeEntry.php, src/Http/Resources/CP/Entries/EntriesFieldtypeListedEntry.php, src/Http/Resources/CP/Taxonomies/TermsFieldtypeListedTerm.php, src/Http/Resources/CP/Taxonomies/TermsFieldtypeTerms.php
This PR adds the ability for the relationship fieldtype to display "hints".
Hints are necessary when you have multiple options that could have the same value. For example if you have two entries in different collections with the same title, you don't know which is which:
The entries fieldtype already had this solved when in "stacked" mode because the collection is displayed as a column in the listing as well as having the collection title as a hardcoded hint in the selected item.
This PR makes the concept of these hints more generic across relationship fieldtypes.
- For the entries fieldtype specifically it uses the collection title to keep it behaving the same when in stacked mode.
- For the terms fieldtype it'll use the taxonomy titles.
This PR also improves the dropdown modes (select …
=> [5.x] Ability for relationship/entries fieldtype to add "hints"

src/Sites/Sites.php
Small method rename to @ryanmitchell's awesome #10461 PR, to better clarify difference between `getDefaultSite()` and `default()` (which returns default site instance, rather than default sites config).
References https://github.com/statamic/eloquent-driver/pull/322
=> [5.x] Clarify difference between `default()` and `getFallbackConfig()` site methods

CHANGELOG.md, resources/js/components/navigation/View.vue, resources/js/components/structures/PageSelector.vue, resources/js/components/structures/PageTree.vue
This pull request makes some improvements around the handling of required fields in Navigation blueprints.
Currently, when you select entries to add to a navigation, you'll be able to get away without filling any required fields.
With this PR, you'll only be able to select a single entry at a time. After selecting, you'll be taken to the "Edit Page" stack where you'll be able to fill the required field.
Fixes #4582.
=> [5.x] Handle `required` fields when adding entries to nav

resources/js/components/fieldtypes/TableFieldtype.vue
This pull request fixes an issue where the Table Fieldtype's fullscreen view wasn't adapted for dark mode.
Fixes #10481.
=> [5.x] Fix Table Fieldtype in dark mode

src/Taxonomies/Taxonomy.php
I've noticed that when [listing the terms](https://statamic.dev/taxonomies#listings-and-indexes) on a taxonomy route, all the localizations of a term would be output. It should only output the terms of the current locale, though. This is consistent with the behavior when [listing term entries](https://statamic.dev/taxonomies#listing-term-entries) on a term route, which also only shows the entries in the current locale.
=> [5.x] Only output terms in the current locale

resources/css/components/fieldtypes/datetime.css, resources/js/components/DarkModeToggle.vue, resources/js/components/Statamic.js, resources/js/components/fieldtypes/date/RangeInline.vue, resources/js/components/fieldtypes/date/RangePopover.vue, resources/js/components/fieldtypes/date/SingleInline.vue, resources/js/components/fieldtypes/date/SinglePopover.vue
The V-Calendar component features a dark mode using shades of blue, but it isn't synchronized with the control panel.
Fixes https://github.com/statamic/cms/issues/10482.
=> [5.x] Sync datetime dark mode with control panel

.github/workflows/tests.yml, composer.json
Tests are failing. This unfails them.
---
Turns out this is due to `league/commonmark` 2.5. As a temporary solution, this PR constrains that package to under 2.5.
=> [5.x] Fix failing markdown tests

tests/Fieldtypes/EntriesTest.php
EntriesTest.php had `@test` metadata from a recent PR, when it should now use `#[Test]`.
=> [5.x] Remove metadata in EntriesTest

resources/js/components/AddonDetails.vue, resources/js/components/updater/Release.vue, resources/js/components/updater/Updater.vue, resources/lang/ar.json, resources/lang/cs.json, resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fa.json, resources/lang/fr.json, resources/lang/hu.json, resources/lang/id.json, resources/lang/it.json, resources/lang/ja.json, resources/lang/ms.json, resources/lang/nb.json, resources/lang/nl.json, resources/lang/pl.json, resources/lang/pt.json, resources/lang/pt_BR.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/sv.json, resources/lang/tr.json, resources/lang/uk.json, resources/lang/zh_CN.json, resources/lang/zh_TW.json, resources/views/partials/docs-callout.blade.php
Turkish typically follows a subject-object-verb (SOV) order for verb phrases, similar to languages like Persian, Japanese, and Korean. However, unlike these other languages, where the phrase can often be rewritten to place the object at the end, Turkish does not allow for such restructuring.
I've rewritten this term for Persian and Turkish, but I placed the link at the end of the terms in other languages.
=> [5.x] Position the "Learn More" link as desired

src/Search/Comb/Comb.php, src/Search/Comb/Index.php
Sometimes you want to show users a list of results, and then allow a query to be entered that filters that listing, rather than entering the query before showing the listing. 
As things stand that means using the collection tag for the non-query state, and then the search:results tag for the queried state. This is because the Comb search driver doesn't allow blank queries. This isn't ideal and means a lot of code repetition for what is the same thing.
This PR updates the logic to allow blank queries when you have `'min_characters' => 0` in your search index config. This allows you to use the search:results tag for both situations mentioned above:
```antlers
{{ search:results for="{get:q ?? '*'}" as="results" }}
```
This shouldn't break any existing installs as min_characters: 1 is the …
=> [5.x] Don't enforce a query length on comb searches

composer.json
The issue that #10492 was addressing has been fixed in `league/commonmark` 2.5.1.
=> [5.x] Revert commonmark back to original constraint

src/Facades/Parse.php
The `frontMatter()` method is not hinted by LSP when using the Parse facade; this PR fixes that by adding it to the docblock.
Method lives here:  https://github.com/statamic/cms/blob/5.x/src/Facades/Endpoint/Parse.php#L60-L72
=> [5.x] Add frontMatter method to docblock for Parse facade

resources/js/components/fieldtypes/ButtonGroupFieldtype.vue, resources/js/components/fieldtypes/RadioFieldtype.vue
This PR fixes button group and radio replicator previews, they only show the keys not the display values currently:
After:
(Middle one is select which works correctly)
=> [5.x] Fix button group and radio previews

resources/js/components/blueprints/Fields.vue, resources/js/components/blueprints/RegularField.vue, resources/js/components/fields/Settings.vue, resources/js/components/fieldtypes/replicator/SetsFieldtype.vue, src/Http/Controllers/CP/Fields/FieldsController.php
This pull request prevents `type` from being used as a handle for fields in Replicator sets. 
In Replicators, the `type` key is reserved for determining which set an item is using, so it shouldn't be possible for sets to have fields with the same name.
In order for the validation rule to only kick in when used inside a set, I'm passing a new `isInsideSet` prop to the `field-settings` component, which then gets passed to the backend when the field gets validated.
This PR doesn't cover the situation where fields are imported from a fieldset, since we don't do any validation when linking fieldsets. 
Closes #5087.
=> [5.x] Prevent using `type` as a handle for fields in sets

src/Data/BulkAugmentor.php
Fixes https://github.com/statamic/cms/issues/10510
=> [5.x] Updated the BulkAugmentor to be able to handle iterables that don't have sequential numeric keys

src/Assets/AssetUploader.php, tests/Assets/AssetUploaderTest.php
In rare cases where users upload assets with percentages in their filenames, Glide assets currently return 400 errors.
=> [5.x] Replace percentages in filenames

src/Http/Controllers/CP/Assets/RedirectsToFirstAssetContainer.php
This pull request prevents a `Call to undefined method Closure::first()` error from happening when redirecting to the first asset container.
Sometimes, due to how the CP Nav gets cached, a nav item's `children` property may be a closure. In our case, we can simply call `->resolveChildren()` to ensure a nav item's children are "resolved" before we get them.
Fixes #10520.
=> [5.x] Prevent error when redirecting to first asset container

src/Providers/CacheServiceProvider.php
Statamic customizes the file cache store. In #10362 we reworked how this is wired up. This caused a problem when you are using a custom file cache store - our one would override it.
This PR makes it so that we only extend with ours if there's not already an extension.
Fixes the issue explained in [this comment](https://github.com/statamic/cms/pull/10362#issuecomment-2245589356).
=> [5.x] Avoid extending already-extended file cache store

resources/js/components/fieldtypes/DictionaryFields.vue
This fixes an error when configuring a dictionary field. When you change the type to countries, the region subfield would be empty because there's a JS error.
=> [5.x] Fix error when changing dictionary type

src/Http/Controllers/CP/Forms/FormsController.php
Hello everyone!
We stumbled upon a bug on `/admin/forms`. We would get endless loading screens and eventually timeouts when visiting this page. We have quiet an amount of form submissions (~150.000), and the controller in the current setup retrieves all submissions, loads them in memory, to then return a count.
We're using Statamic 5 with the `statamic/eloquent-driver` implementation, and in that package it would retrieve the model for the submission, and then the model for the form. But it would do that for every submission. First we changed something there, but then realized a simple fix for this would be in the `FormsController` instead.
If you have any questions or comments about this, let me know!
=> [5.x] Use form submission query count instead of collection count

resources/js/components/slugs/Slug.js
Part of #10533
- Parenthesis are removed
- When `statamic.system.ascii_replace_extra_symbols` is ...
- `true`, currencies will be converted to the word. (e.g. `$` to `dollar`)
- `false`, currencies will be removed (e.g. `$` to nothing) 
These match how it works in PHP.
=> [5.x] Prevent parentheses and currencies in js slug

src/Modifiers/CoreModifiers.php, tests/Antlers/Runtime/CoreModifiersTest.php, tests/Modifiers/WhereInTest.php
This PR adds a ``where_in`` modifier that can come in handy in various situations where you want to check a value against an array.
```yaml
games:
-
feeling: love
title: Dominion
-
feeling: happy
title: Netrunner
-
feeling: hate
title: Chutes and Ladders
```
```
<h2>I love...</h2>
{{ games | where_in('feeling', ['love', 'happy']) }}
{{ title }}<br>
{{ /games }}
```
```html
Dominion
Netrunner
```
=> [5.x] Add where_in modifier

resources/lang/nl/messages.php
Fixes a typo in the dutch (nl) messages translation file.
=> [5.x] Fix nl locale spelling mistake

resources/js/components/fieldtypes/grid/Stacked.vue, resources/js/components/fieldtypes/grid/StackedRow.vue
This PR adds a duplicate icon for the Stacked UI-Style of the Grid Fieldtype to be in line with the Duplicate option available in the Table UI-Style.
It also implement the canAddRows check to disable the button if the maximum number of entries is reached.
=> [5.x] Add duplicate stacked row option to Grid fieldtype

resources/js/components/fieldtypes/VideoFieldtype.vue, src/Modifiers/CoreModifiers.php, tests/Modifiers/EmbedUrlTest.php
This pull request fixes an issue with the Video fieldtype, where Vimeo "file URLs" were being parsed as if they were unlisted videos.
**Examples:**
* Unlisted / private video URL: `https://vimeo.com/735352648/fa55a4d0fc`
* File URLs: `https://player.vimeo.com/progressive_redirect/playback/990169258/rendition/1080p/file.mp4?loc=external&log_user=0&signature=275be15f3630d1ca3e7a51456a911e11e3ba9fddf89911f49140f6de95357e05`
Fixes #10508.
=> [5.x] Fix the Video fieldtype with Vimeo file URLs

src/Tags/Asset.php
This pull request fixes an issue with the `{{ asset }}` tag where the `AssetAPI::find()` call would throw an exception if the value passed to it was `null`.
Instead of an exception being thrown in this case, the tag will simply fail silently and not return anything.
Fixes #10532.
=> [5.x] Asset tag: Fail silently when no URL has been provided

resources/js/components/fieldtypes/ColorFieldtype.vue
Pasting colors into the color fieldtype requires they have a leading `#`. However, when copy-pasting from most layout apps, the colors come without the `#`, requiring editors to add it manually for each color field. This PR will make editors' lives a bit easier and sanitize any valid hex colors to the required format including the leading hash.
=> [5.x] Allow entry of hex colors without leading hash

resources/css/components/fieldtypes/bard.css
Links inside Bard headings currently don't have any styles applied, making it impossible to scan for headings with links.
This PR applies the same style to links within headings as applied in paragraphs and other block-level elements.
While at it, I explicitly added a font-weight to bold sections in headings as Safari/Firefox (don't remember which one) wasn't getting the memo and required an explicit font-weight.
=> [5.x] Fix invisible links in Bard headings

resources/js/components/fieldtypes/GroupFieldtype.vue, resources/lang/en/fieldtypes.php, src/Fieldtypes/Group.php
The group fieldtype is great to have the data scoped under a common key, but it tends to create visual clutter. Making the border optional solves this nicely :) Defaults to `true`, so no breaking change.
Also removed a superfluous padding class that was being added downstream anyway, as well as a bottom margin that looked a bit large. The screenshot below is after removing the bottom margin, which has plenty space already.
Closes statamic/ideas#1137.
=> [5.x] Allow hiding border around group fieldtype

resources/js/components/fieldtypes/IntegerFieldtype.vue, src/Fieldtypes/Integer.php
The `integer` fieldtype was missing a placeholder option. Figured I'd add it :)
=> [5.x] Add placeholder option to integer fieldtype

resources/js/components/fieldtypes/LinkFieldtype.vue
Render meaningful replicator previews of link fields.
For reference and quick testing, this is the example fieldset I've been using to test this:
```yaml
-
handle: link
field:
type: link
display: Link
collections:
- pages
container: assets
```
=> [5.x] Display replicator preview of link fields

src/Stache/NullLockStore.php
If `statamic.stache.lock.enabled` is `false` PHP bails with:
`Got error 'PHP message: PHP Fatal error:  Declaration of Statamic\\Stache\\NullLockStore::exists(Symfony\\Component\\Lock\\Key $key) must be compatible with Symfony\\Component\\Lock\\PersistingStoreInterface::exists(Symfony\\Component\\Lock\\Key $key): bool in /vendor/statamic/cms/src/Stache/NullLockStore.php on line 20'`
This patch fixes up the `NullLockStore` method signatures to match interfaces.
=> [5.x] Fix NullLockStore (disabling of Stache locking)

resources/css/elements/buttons.css, resources/js/components/inputs/relationship/Selector.vue, resources/views/auth/protect/password.antlers.html
I stumbled across a couple of duplicate or incorrect Tailwind CSS utility classes. This pull request cleans them up.
=> [5.x] Clean up duplicate tailwind classes

src/Fieldtypes/DictionaryFields.php, tests/Fieldtypes/DictionaryFieldsTest.php
This makes some things easier to resolve in #10467. 
There's no reason we need collections here anyway since it's just going to JavaScript.
=> [5.x] Avoid collections in dictionary fields fieldtype

src/Auth/User.php
This pull request fixes an issue where an error would occur when creating a new user, when the Laravel Telescope package is installed.
* When a user is being created, it dispatches two events: `UserCreating` and `UserSaving`. 
* Laravel Telescope listens for any events being dispatched and [attempts to serialize them](https://github.com/laravel/telescope/blob/5.x/src/ExtractProperties.php#L34) using `json_encode`.
* When the `User` object gets serialized, it'll end up augmenting the user via [`HasAugmentedInstance::jsonSerialize()`](https://github.com/statamic/cms/blob/d446b3b827490a123382f4113c1092e82c279a55/src/Data/HasAugmentedInstance.php#L105-L108).
* The `AugmentedUser::commonKeys()` array includes `edit_url` and `api_url`.
* When the `editUrl` and `apiUrl` methods are called on the …
=> [5.x] Prevent error when Laravel Telescope serializes a user before its created

src/Rules/Handle.php, tests/Rules/HandleTest.php, tests/Rules/SlugTest.php
This pull request adjusts our field handle validation to allow for using uppercase characters in field handles.
Fixes #10572.
=> [5.x] Allow uppercase characters in field handles

src/Console/Commands/InstallEloquentDriver.php
This pull request adds the Sites repository as an option to the `install:eloquent-driver` command, after it being added in statamic/eloquent-driver#322.
Unlike other repositories, there's no "Do you want to import existing sites" option since not importing them could cause issues.
=> [5.x] Add Sites to `install:eloquent-driver` command

resources/js/components/inputs/relationship/RelationshipInput.vue
This pull request fixes an issue when using the `RelationshipInput` component inside a listing filter, where errors occur when the filter is removed.
When the filter is removed, `this.value` becomes null which the `items` and `maxItemsReached` computed properties aren't expecting.
Closes #10581.
=> [5.x] Fix broken `RelationshipInput` after removing filter

src/Forms/Email.php
This pull request fixes an issue when using the Files Fieldtype in Forms, where an error would occur when no files have been uploaded.
Closes #10575.
=> [5.x] Fix error with Files Fieldtype in Forms when no files are uploaded

resources/js/app.js, resources/views/partials/licensing-alerts.blade.php
As suggested on [this issue](https://github.com/statamic/cms/issues/10564#issuecomment-2268675166), it'd be nice if clicking "Dismiss" on the license banner meant it'd actually go away when navigating to other pages.
This PR makes that a reality, dismissing the banner will hide it for 5 minutes.
Closes #10564.
=> [5.x] License banner is snoozable

src/Actions/RenameAssetFolder.php, src/Assets/AssetFolder.php, src/Http/Controllers/CP/Assets/FoldersController.php, src/Rules/AllowedFolder.php, src/Rules/AlphaDashSpace.php, tests/Assets/AssetFolderTest.php
When uploading assets, the filenames are automatically sanitized. This does the same for asset folders.
Closes statamic/ideas#503
Currently a completely valid folder name is required when creating/moving/renaming folders. Spaces in folder names lead to validation errors and require manual correction. This quickly becomes exhausting when editors need to create dozens of folders by copy-pasting from their local filesystem.
With this change, folder name inputs allow spaces. For that, it introduces a new rule for valid folder name inputs: same as `alpha_dash`, but with spaces allowed. The spaces are then removed by re-using the basename sanitizer from the `FileUploader` class, which also sanitizes upload filenames. Handles creation and renaming/moving.
~~Wasn't sure about the rule name …
=> [5.x] Sanitize asset folder name on creation

resources/js/components/collections/View.vue, resources/views/collections/show.blade.php, src/Actions/DeleteMultisiteEntry.php, src/Entries/Entry.php, src/Http/Controllers/CP/Collections/CollectionsController.php
This pull request fixes an issue where it was possible for users to delete localized entries in other sites, even if they don't have permissions to access that site.
Fixes #10519.
=> [5.x] Always detach localizations when user is missing permissions to delete in other sites

resources/js/components/fieldtypes/assets/AssetRow.vue, resources/js/components/fieldtypes/assets/AssetTile.vue
Improve the title attributes of asset edit buttons on hover.
- Include file extension in filename
- Add title to 'Edit' button
- Add title to 'Remove' button
- Remove invalid button `alt` attribute
=> [5.x] Optimize hover titles of asset edit buttons

src/Console/Commands/InstallCollaboration.php
This pull request fixes an issue when installing the Collaboration addon, and all the bootstrapping that happens behind the scenes to enable Laravel's broadcasting functionality.
In Laravel 11, the environment variable key used to determine an app's broadcasting driver is `BROADCAST_CONNECTION`. Previously, this key was `BROADCAST_DRIVER`
For applications upgraded to Laravel 11 manually (eg. not via Laravel Shift), they'll still have the legacy `BROADCAST_DRIVER` key in their `.env` files as the change wasn't part of the Laravel 11 upgrade guide.
So, when you install Laravel's broadcasting stuff into an upgraded Laravel 11 app, it'll be referencing the new key, rather than the old one present in the app's `.env`. 
This PR introduces a warning during the `install:collaboration` command …
=> [5.x] Warn when using legacy broadcasting env variable when installing the Collaboration addon

src/Tags/Concerns/RendersAttributes.php, tests/Tags/Concerns/RendersAttributesTest.php
Something that always trips me up is adding attributes to forms tags that contain json (eg Alpine x-data). Currently if you do:
```
{{ form:create \x-data='{"something":"here"}' }} 
```
it will output the x-data inside double quotes (") which means on the browser side its invalid, eg.
```
<form x-data="{"something":"here"}">
```
This PR updates the attribute outputting to check for the presence of a double quote, and if it finds one it uses single quotes to wrap the attribute instead:
```
<form x-data='{"something":"here"}'>
```
=> [5.x] Render attributes inside single quotes when value contains double quotes

src/StaticCaching/Middleware/Cache.php
If you have static caching enabled, and you visit a page that is being generated in another process, your request will wait until the other request is done. If that takes longer than 30 seconds, you'll get an exception since #10370. Before that, I think the page would just time out.
This PR will now output a blank page that says unavailable and automatically refreshes. This is the [same thing that happens in the Stache locking middleware](https://github.com/statamic/cms/blob/457e056b6016f7ed2b5d84b20065abdc3611d41d/src/Http/Middleware/StacheLock.php#L21).
=> [5.x] Handle lock timeout in cache middleware

src/Events/NavCreated.php, src/Events/NavCreating.php, src/Events/NavSaving.php, src/Structures/Nav.php, tests/Data/Structures/NavTest.php, tests/Stache/FeatureTest.php
This pull request adds three new nav-related events:
* `NavCreating`
* `NavSaving`
* `NavCreated` 
Related: #10602
=> [5.x] Implement NavCreating / NavSaving / NavCreated events

src/Fieldtypes/Textarea.php, tests/Fields/BlueprintTest.php, tests/Fields/SectionTest.php, tests/Fields/TabTest.php
When you go to edit a textarea, the character_limit field is a text field. It should be an integer. 
Strings were being saved to the config, and you get a Vue warning saying the prop should have been an integer.
(The tests were updated to coincide with the `text` field a handful of lines above each change. Text fields have had character_limit 0 for a while now.)
=> [5.x] Change character_limit to integer on textarea

resources/js/components/SessionExpiry.vue
This PR adds padding and tweaks fonts of the session expiry modal so that the contents line up with the heading and look more like other modals.
Before:
After:
=> [5.x] Add padding to session expiry modal

src/Forms/Tags.php, tests/Tags/Form/FormCreateTest.php
One thing I overlooked in https://github.com/statamic/cms/pull/8491 is that you may want to access the new config fields in antlers. 
This PR changes that by adding a `form_config` variable to the antlers scope in `form:create` tags. The name was the best I could come up with, I wanted to use `config` but it would clash with the [config](https://statamic.dev/variables/config) variable which is potentially being used in form tags.
=> [5.x] Pass any appended form config to antlers

resources/js/components/publish/Field.vue
The readonly label looked a bit off in dark mode. In light mode, it's lighter than the field display label. I've adjusted the dark mode color to also slightly subdue the readonly label. Also nudged the label down a bit to put it on the typographic baseline.
=> [5.x] Adjust dark mode readonly label

resources/js/components/fieldtypes/assets/AssetTile.vue
The asset control bottons looked a bit off for read-only asset fields. I've added back a gap between buttons and updated the svg icon component to use the correct download icon. The current download icon seems to be a fallback icon.
| Before | After |
| --- | --- |
| <img width="260" alt="Screenshot 2024-08-13 at 17 58 21" src="https://github.com/user-attachments/assets/07cdbf2d-7b93-4228-9a6b-74f94d0ee0de"> | <img width="261" alt="Screenshot 2024-08-13 at 18 00 26" src="https://github.com/user-attachments/assets/768baa35-563f-4f54-84e9-c425b113abfc"> |
| <img width="262" alt="Screenshot 2024-08-13 at 17 58 34" src="https://github.com/user-attachments/assets/6f5d3512-cb61-4626-933b-7ec0b4347e95"> | <img width="258" alt="Screenshot 2024-08-13 at 18 00 16" …
=> [5.x] Fix asset tile buttons in read-only mode

resources/css/components/assets.css, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
Fix two tiny inconsistencies I've encountered in the asset field. You really have to squint to see them, but once you did, there's no unseeing them 🤠
**Before**
**After**
**Before**
**After**
=> [5.x] Fix rounded corners in asset fields

src/Fieldtypes/HasSelectOptions.php
Bug introduced in https://github.com/statamic/cms/pull/10467
Cast to array to prevent issues with listings when data is returned as a Statamic\Entries\EntryCollection
The issue will happen when filters don't return an array, but a EntryCollection like this.
```php
public function fieldItems()
{
$entries = \Statamic\Facades\Entry::query()->where('collection', 'locations')->get();
return [
'locations' => [
'type' => 'select',
'multiple' => true,
'options' => $entries->mapWithKeys(function (\Statamic\Entries\Entry $item, int $key) {
return [$item->id() => $item->title];
}),
],
];
}
```
=> [5.x] Cast to Array to Resolve Issues with Filters Returning `EntryCollection`

src/Fields/Field.php
This PR hides the "Sortable" config option for computed fields.
Closes #10610.
=> [5.x] Hide "Sortable" config option for Computed fields

resources/js/components/fieldtypes/ArrayFieldtype.vue, resources/js/components/fieldtypes/ButtonGroupFieldtype.vue, resources/js/components/fieldtypes/CheckboxesFieldtype.vue, resources/js/components/fieldtypes/RadioFieldtype.vue, resources/js/components/fieldtypes/SelectFieldtype.vue, resources/js/components/publish/SaveButtonOptions.vue
This pull request fixes an issue where the radio buttons weren't showing in the `save-button-options` component, due to the fieldtype now expecting options to be passed in via the `meta` prop instead of the `config` prop.
Fixes #10632.
Related: https://github.com/statamic/cms/pull/10467
=> [5.x] Fix save button options not showing

resources/js/components/AddonDetails.vue
This pull request updates the `AddonDetail` component to display special install commands for some first-party addons, like the Eloquent Driver and the Collaboration addon.
=> [5.x] Display special install commands for first-party addons

src/StaticCaching/NoCache/StringFragment.php
Fixes a race condition when rendering antlers views via nocache.
It's possible that two requests come in at almost the exact moment and one request's view is cleaned up before the other request has a chance to render it, resulting in a `view not found` exception.
This PR makes the view names unique so there's no overlap.
It also removes a file exists check that isn't related to the race condition but noticed it's not necessary while in there.
=> [5.x] Fix nocache race condition

src/Rules/UniqueEntryValue.php, src/Rules/UniqueTermValue.php, src/Rules/UniqueUserValue.php
This pull request adds support for arrays being passed to the "unique value" validation rules, allowing for validating unique entry fields (and similar).
Closes #10614.
=> [5.x] Support arrays in unique value rules

src/Fieldtypes/HasSelectOptions.php
This pull request fixes an issue caused by our recent changes in #10467, where options for various fieldtypes are saved in a new "expanded" format, allowing for integer keys in options.
However, these changes broke Checkboxes  / Radio Buttons / etc in frontend forms, since the templates assume `option` is just a key/value array, which it no longer is.
Closes #10645.
=> [5.x] Form fields should continue to output a key/value array

src/Forms/Email.php
This pull request makes config values available in form emails. 
This can be helpful if you want to control who receives form emails on a per-environment basis.
Closes https://github.com/statamic/cms/issues/10647.
=> [5.x] Make config values available in form emails

resources/js/components/fieldtypes/HasInputOptions.js, resources/js/tests/NormalizeInputOptions.test.js
This pull request fixes an issue with the suggested fields in the Field Conditions builder, after changes to how field options are stored in #10467.
Say you have a Button Group or Select field that looks like this:
```yaml
-
handle: developer_type
field:
options:
-
key: partner
value: Partner
-
key: other
value: Other
default: other
type: button_group
display: 'Developer Type'
```
Then, when you add another field to the blueprint and configure a field condition, it'll save like this:
```yaml
if:
developer_type: 'equals Partner'
```
The saved value for this field condition is the "label" for the option, not the key or the value. This means the field condition won't actually work.
This is happening due to the format the options are saved in. The `normalizeInputOptions` only picks up on the …
=> [5.x] Fix suggested options in Field Conditions builder

resources/js/app.js, resources/views/layout.blade.php
This pull request improves the handling of "copy to clipboard" actions when on iOS.
iOS [only allows](https://stackoverflow.com/a/34046084) for copying to the user's clipboard from an `<input>` or `<textarea>`. 
This means that iOS browsers end up in the `catch` statement, with a browser alert containing the URL, which the user has to copy manually. However, some browsers like Chrome don't allow copying from alerts. 😬 
To workaround this, instead of showing a browser alert, it'll open up a modal with the ability to copy from there (the copy button here will work since it's copying text from a textarea).
Closes #6378.
=> [5.x] Display text in modal instead of alert, to improve things on iOS

resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
This pull request wraps the name of set groups in set previews in the `__()` helper so they can be translated.
Fixes #10657.
=> [5.x] Translate set groups in set previews

resources/js/components/fieldtypes/bard/LinkToolbar.vue
This pull request makes a small improvement to linking email addresses in Bard.
Previously, when you had an email address selected and clicked on the "Link" button in the toolbar, it would default to a normal URL.
Now, with this PR, when you have an email address selected and click on the "Link" button, it'll default to the "Email" link type and prefill the value:
=> [5.x] Bard: When email address is selected, assume link is a mailto

src/Fields/BlueprintRepository.php, tests/Fields/BlueprintRepositoryTest.php
While reviewing #9327 I noticed that there's some behavioral issues with how blueprint overrides work.
- When you have a custom namespace, and the `vendor` override directory exists (e.g. `blueprints/vendor/custom`), if the directory is empty, you see no blueprints at all. Not even ones that haven't been overridden.
- If there are any overrides in that directory, only they are shown. Non-overridden ones do not get displayed.
- If you have a yaml file in the override directory that doesn't exist in the regular directory, it gets shown. It shouldn't. You shouldn't be able to override a blueprint that doesn't exist. You're overriding, not adding. (Up for debate I guess, but it was ambiguous so I went with this.)
=> [5.x] Fix blueprint override logic

composer.json, tests/TestCase.php
We use ray constantly while developing. This requires it plus adds it to the providers which lets you chain `->ray()` onto collections.
=> [5.x] Require spatie/laravel-ray in dev

src/Fields/BlueprintRepository.php, tests/Fields/BlueprintRepositoryTest.php
In #10661, I made it so that it ignores any blueprints in the override directory that don't exist in the original directory and said that behavior was up for debate. Well, someone debated it and showed they were relying on that behavior.
This PR brings it back.
=> [5.x] Fix blueprint override logic, pt 2

src/Stache/Indexes/Index.php
This fixes #10666
Which is caused by `->` not being a valid set of filename characters on windows.  Since there is already a condition used to sanitize the key for windows I re-used that and just added a replacement.
=> [5.x] Fix fatal windows cache key error

resources/js/components/blueprints/Builder.vue, resources/views/blueprints/edit.blade.php, src/Http/Controllers/CP/Fields/BlueprintController.php
When working on https://github.com/statamic/cms/pull/8516 I decided to prevent custom namespaces blueprints from being hidden. I shouldn't have. This PR undoes that mistake.
Closes https://github.com/statamic/ideas/issues/1175
=> [5.x] Stop hiding `hidden` field in namespaced blueprints

.github/workflows/tests.yml, resources/js/tests/FieldConditionsValidator.test.js
We figured out there was a small issue in our glob pattern for changed JS files. It used to work on JS files at the root level, but not in subdirectories.
Before:
After:
References https://github.com/statamic/cms/pull/8269
=> [5.x] Fix github workflow for changes in JS tests

src/Exceptions/CascadeDataNotFoundException.php, src/Providers/ViewServiceProvider.php, src/View/Blade/CascadeDirective.php, tests/View/Blade/CascadeDirectiveTest.php
When using blade the cascade data is only available in the entry's main template, and the layout if you're using `@extends `. This can leave situations where you don't have quick access to the cascade data (without workarounds), for example:
1. When inside blade components, particularly when using them for the layout
2. When in standard views loaded by non-Statamic routes/controllers
This PR adds a new blade directive called `@cascade` which will add cascade data to the current scope.
It works in exactly the same way as the `@props` directive used in blade components, with the ability to require certain values or provide default fallback values:
```blade
{{-- Fetch my_global and site, will throw an exception if either are missing from the cascade --}}
@cascade([
'my_global',
'site',
])
{{ …
```
=> [5.x] Add blade `@cascade` directive

src/Modifiers/CoreModifiers.php, tests/Modifiers/WhereTest.php
This PR closes #10679 by only applying the default `==` operator if the number of supplied parameters is less than 3.
=> [5.x] Improves "where" modifier value check

src/Events/LocalizedTermDeleted.php, src/Events/LocalizedTermSaved.php, src/Taxonomies/LocalizedTerm.php, tests/Data/Taxonomies/LocalizedTermTest.php
This pull request implements `LocalizedTermSaved` & `LocalizedTermDeleted` events. 
These events are fired after the `TermSaved` and `TermDeleted` events, however, instead of the generic `Term` object being passed in, the `LocalizedTerm` object will be passed, allowing for determining which site the term was just updated in (which will be helpful in #10669).
=> [5.x] Add `LocalizedTermSaved` & `LocalizedTermDeleted` events

resources/views/taxonomies/show.blade.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, src/Taxonomies/Taxonomy.php
This pull request hides the "Create Term" button on the taxonomy show page when all of the taxonomy's blueptints are marked as hidden.
This PR copies the behaviour from #9744.
Closes #10675.
=> [5.x] Hide "Create Term" button when all taxonomy blueprints are hidden

src/Assets/AssetUploader.php, tests/Assets/AssetUploaderTest.php
This pull request attempts to fix an issue with the "safe filename" code which seems to be erroring out (sometimes) when uploading assets.
I haven't been able to replicate the issue myself yet, however, since we're just doing some simple string replacements, I don't think we really need to be touching regex functions for it, so I've refactored it to use Laravel's `Stringable` class instead.
Closes #10672.
=> [5.x] Fix `preg_replace` error when uploading assets

src/Search/Comb/Index.php
This PR solves a race condition when reading and writing a Comb-driven search index.
It's possible that one request will try to read the JSON file when another is writing to it, causing the JSON parsing to return invalid JSON.
Invalid JSON would return null. Passing null to `collect()` would be an empty collection. If this happened when you are trying to insert something into the index, it would result in that index **only** containing the inserted data.
This is solved by throwing an exception when encountering invalid JSON. This would prevent the search index being emptied out but of course now results in an exception.
Additionally, file locks are now used when reading and writing those files to prevent getting into that situation where the exception would be thrown to begin with.
=> [5.x] Fix search index race condition

resources/js/components/navigation/View.vue
This pull request fixes an issue where the twirldown wouldn't be shown on the navigations show page in the Control Panel due to it checking something that dioesn't exist. 🤦‍♂️
Caused by #9265.
=> [5.x] Fix twirldown on navigation show page

resources/js/components/fieldtypes/DictionaryFieldtype.vue, src/Fieldtypes/Dictionary.php
This pull request fixes two issues with the recently added Dictionary fieldtype:
* Option keys were being displayed in listing tables, rather than the labels.
* Already selected options were able to be selected, when they shouldn't have been.
Fixes #10713.
=> [5.x] Dictionary Fixes

resources/lang/en/messages.php
This pull request adds a link to the "Reserved Words" page on the Statamic Documentation from the instructions of the "Handle" field, to make it a little eaqsier to see what you can & can't name fields.
Closes #6794.
=> [5.x] Link to "Reserved Words" docs page from field settings.

src/Modifiers/CoreModifiers.php, tests/Modifiers/PushTest.php
This just came up on discord (https://discord.com/channels/489818810157891584/1153390699161587823/1277561682406805576) - might be handy to have a `push` modifier.
`{{ my_array | push('value') }}`
=> [5.x] Add `push` modifier for arrays

resources/js/components/fieldtypes/replicator/Field.vue
This pull request makes it so field handles are displayed when hovering over fields in Bard & Replicator sets.
Closes #10717.
=> [5.x] Show field handle on hover for fields in Bard & Replicator sets

src/Console/Commands/stubs/action.php.stub
This pull request updates the return type of the `run` method in the action class stub, as it's not always going to return void, it's [very possible](https://statamic.dev/extending/actions#responses) a string or array might be returned.
No issue for this, but just a small thing I noticed.
=> [5.x] Update docblock in action class stub

resources/views/collections/show.blade.php
This pull request fixes an issue I spotted at the weekend where the Twirldown on the collection show page wouldn't be displayed unless the user had "edit collection" permissions for that collection, even if actions were available.
Related: #10471
=> [5.x] Twirldown should be shown even if the user doesn't have edit collection permissions

resources/js/components/data-list/Filter.vue, resources/js/components/inputs/relationship/Item.vue, resources/js/components/publish/FieldMeta.vue, resources/js/components/users/Wizard.vue
This pull request fixes two instances where the ID of a selected relationship item as being displayed instead of the item's title.
This was happening due to the item data not flowing back to the field meta's "source of truth" properly.
Fixes #8363.
Fixes #10673.
=> [5.x] Fix relationship fieldtypes showing ID instead of item title

src/Data/AbstractAugmented.php
This pull request adds `entry` to one of the augmentaion "allow lists", allowing for `entry` to be used as a field on navigation blueprints.
Fixes #8657.
=> [5.x] Allow using `entry` as a field handle in navigation blueprints

src/Http/Controllers/CP/Assets/BrowserController.php
This resolves issue #10708
In the control panel assets table view, column sort was not functioning after a search term was used. This allows searched assets to be sorted in table view.
=> [5.x] Fix CP Asset Sort After Search issue

src/Fieldtypes/HasSelectOptions.php
This pull request fixes an issue where select options stored in the new format (see #10467) wouldn't be augmented properly.
Fixes #10696.
=> [5.x] Fix augmentation of select options

src/Stache/Query/QueriesEntryStatus.php, tests/API/APITest.php, tests/Tags/Collection/EntriesTest.php
References statamic/eloquent-driver#347
Doing `$query->whereStatus('any')` would be the same as not calling `whereStatus` at all. This is useful in situations like the collection tag or REST/GraphQL APIs where it filters by the `published` status by default.
```
{{ collection:articles status:is="any" }}
```
```
entries(
collection: "articles",
filter: {status: "any"}
)
```
```
/api/collections/articles/entries?filter[status]=published
```
=> [5.x] Support querying by any status

resources/js/components/fieldtypes/ButtonGroupFieldtype.vue
This pull request fixes an issue with the "Delete Entry" action where clicking on one of the button group buttons automatically submits the form, instead of it being submitted when you click the big red button.
Fixes #10754.
=> [5.x] Prevent button group fieldtype from submitting actions

src/Search/Comb/Index.php
This pull request fixes an issue caused by #10695 where an error would be thrown when attempting to write the index's JSON file if the `storage/statamic/search` directory doesn't exist.
This was happening [under the hood](https://github.com/statamic/cms/blob/5.x/src/Filesystem/AbstractAdapter.php#L27) when we were using the Flysystem stuff.
=> [5.x] Prevent error when writing to Comb index file

src/Forms/Email.php
This pull request filters out the Spacer fieldtype from being output in form emails.
Related: https://github.com/statamic/cms/issues/10305#issuecomment-2312768574
=> [5.x] Filter out Spacer fields from form emails

resources/js/components/fieldtypes/RadioFieldtype.vue
This pull request fixes an issue where the selected state wouldn't be displayed correctly in the Radio Fieldtype due to the strict equals check.
Fixes #10763.
=> [5.x] Fix Radio Fieldtype with numeric keys

src/View/Debugbar/AddRequestMessage.php
This pull request fixes an issue when passing an Eloquent Model into a view's `->cascadeContents() method.
I'm currently fixing a bug in Runway, with its frontend routing feature, where the `page` variable isn't available in Blade views (see statamic-rad-pack/runway#590). 
The [`page` variable](https://github.com/statamic/cms/blob/dd4ad041859660a80a96aa9c9145225463336986/src/View/Cascade.php#L169) is only set when the view has `cascadeContent` set, whereas previously we were only passing an array of the augmented model into the `View::with()` method.
However, when passing the model to `View::cascadeContents()`, it resulted in an error because the model doesn't have an `id` method on it.
I could add an ID method but that has caused issues in the past where folks have already implemented …
=> [5.x] Prevent error when `cascadeContent`  is an Eloquent Model

resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
We would like to add some functionality based on the set handle we have in our replicators. To identify which set the visible set is in the code, we'd like to have this data-type attribute so we can select html elements with it.
=> [5.x] Add data-type attribute to replicator and bard set divs

src/Assets/AssetContainer.php, tests/Assets/AssetContainerTest.php
This was always the intention, but it didn't.
Doing `$asset->url()` on a private asset would already return `null`, it's just calling on the container itself that had the issue.
This was discovered by doing `Asset::findByUrl($url)` and having a private S3 container.
https://github.com/statamic/cms/blob/a9f4e41478cbef40312ae54b5343d3317cca89c5/src/Assets/AssetRepository.php#L75-L83
It would loop through all containers, get their urls, and figure out a matching container. When you had a private s3 container, getting its URL here would throw an exception. Now since it returns null the exception is avoided. The private container is skipped in findByUrl as expected, since they don't have URLs.
=> [5.x] Private asset container url method should return null

src/Http/Controllers/GlideController.php
Replace a `new ImageGenerator` call with dependency injection to allow binding the ImageGenerator and overwriting it.
All other places in the code already use the ImageGenerator this way. This ocurrence is the only one using the `new`.
=> [5.x] Allow bind of ImageGenerator by removing last `new` call

resources/js/components/data-list/HasFilters.js
Fixes #10776
@925dk identified the likely cause of the reported issue as being this small piece of code 'leftover from the filter refactor'.
This PR removes that code.
I am a novice Statamic contributor so this will need thorough double-checking, but I haven't seen any other issues in my testing as a result of this change.
=> [5.x] Remove legacy code that likely caused issues typing 'f' in asset file rename field

src/Search/Searchables/Entries.php
At the moment, we index any entries marked as published. i.e. not drafts. (Since https://github.com/statamic/cms/pull/6318)
However, this would include scheduled or expired entries.
This PR makes it so that only entries with a status of published are indexed. Not drafts, scheduled, or expired.
=> [5.x] Only index entries with published status

src/Http/Controllers/CP/Auth/ImpersonationController.php
This pull request fixes an issue where ending impersonation would result in the impersonator being logged out, rather than redirected back to the Control Panel.
This was happening due to the `stop-impersonation` route existing outside the middleware group with the `AuthenticateSession` middleware. Adding it directly to that controller does the trick!
Fixes #10772.
=> [5.x] Prevent user from being logged out when ending impersonation

src/Http/Controllers/CP/Collections/EntriesController.php
This pull request fixes an issue where the value of the `parent` field would be persisted to entry data, when it shouldn't have been.
Closes #5457.
=> [5.x] Prevent saving value of `parent` field to entry data

src/Http/Controllers/CP/Assets/ThumbnailController.php, src/Http/Controllers/GlideController.php, src/Imaging/ImageGenerator.php
In the old situation `src/Imaging/ImageGenerator.php` throws http exceptions while by namespace it has nothing to do with http.
This causes confusing errors when used to pregenerate images since getting the actual error message is impossible and instead you get a 404.
This PR moves throwing the 404 for this error to the controllers running the generator, so exceptions are thrown according to the task that class should perform.
This will make debugging and error handling much better.
caused by: https://github.com/statamic/cms/pull/3450/files#diff-a241fa0e16c263728c96b0f5b5b590e06e14a79e2e7260a3501bba22ceb88755R152
fixes: https://github.com/statamic/cms/issues/10788
=> [5.x] Improve ImageGenerator Exception handling

src/Http/Controllers/CP/Collections/ExtractsFromEntryFields.php
This pull request fixes an issue where the "Parent" field on a Home entry could get into a weird state when you save it using revisions.
Fixes #10724.
=> [5.x] Fix broken state of "Parent" field when saving Home entry with Revisions

resources/js/components/SessionExpiry.vue
Fixes #10793
If the login modal closes automatically it would have been before the session was renewed elsewhere.
At the moment the token is only updated when you submit the form. Since you don't actually submit the form in this case, the token was never updated. Now it will.
=> [5.x] Update CSRF token when session expiry login modal is closed

resources/js/components/collections/View.vue, resources/js/components/entries/Listing.vue
This pull request prevents the "Site" filter from showing after re-ordering entries in a single-site setup.
It also resets your filters to what you had active before you clicked "reorder". (Clicking reorder will remove any filters since we need to show you all the entries).
Closes #10796.
=> [5.x] Reset previous filters when you finish reordering

src/Assets/AssetFolder.php
When moving an asset folder, the new path should be set. If you do `$folder->path()` currently the old path is shown.
Now the new one would be shown.
This already happens when you move an asset. https://github.com/statamic/cms/blob/d795c89acaa0f3e5584439ec43813d0622a8c5ed/src/Assets/Asset.php#L756
When dispatching the deleted event, we clone the object so `$folder->path()` within the listener *does* output the old path. That was the one that was deleted. If we didn't clone, since the object is passed by reference, the path would be the new one.
=> [5.x] Set path on asset folder when moving

resources/lang/en/messages.php, src/Dictionaries/Countries.php
By default flag emojis are shown. This adds an option to disable them.
=> [5.x] Add option to exclude flag emojis from countries dictionary

src/Modifiers/CoreModifiers.php, tests/Modifiers/LimitTest.php
I ran into a scenario in Antlers where I needed to limit the selected entries of an entries fieldtype. This PR extends the `limit` modifier to also support query builders.
**Fieldset**
```yaml
handle: galleries
field:
collections:
- galleries
type: entries
```
**Content**
```md
galleries:
- a56a6437-5a5d-4479-a6dc-38095322ba8a
- 97e4e258-5fec-4ef3-8f54-64d855224ac1
- bdf45d98-d6fb-471b-81b0-d11714551e24
- 5429adf7-0a63-4e21-9163-feee07faf1f6
- 86b1c86b-f1dc-47c1-841b-156bfca33660
limit: 3
```
**Template**
```antlers
{{ galleries | limit({limit}) }}
```
=> [5.x] Make limit modifier work with query builders

resources/js/components/AddonDetails.vue, resources/views/addons/index.blade.php, src/Marketplace/AddonsQuery.php
This pull request makes various UI improvements to the "Addons" page in the Control Panel. It's still not perfect, but it's way better than what we have right now.
=> [5.x] Improve addons listing

resources/js/components/ToastBus.js
When using the `Toast` facade in an action request, the toast would not be shown.
This is because the action requests were expecting blob types, not json, so they weren't being picked up.
I noticed this in #10264 when adding a toast in an `EntryDeleting` listener.
```php
Event::listen(function (EntryDeleting $event) {
Toast::error('Cannot save entry ['.$event->entry->title.'] because of a reason.');
return false;
});
```
The action would complete, but the entry would be deleted, and you'd get no feedback. With this PR you will at least get the toast about why it wasn't deleted.
(In #10264 you will get feedback about the action not being successful too).
=> [5.x] Fix toasts in actions not being shown

src/CP/Navigation/NavPreferencesNormalizer.php, src/CP/Navigation/NavTransformer.php, tests/CP/Navigation/NavPreferencesNormalizerTest.php, tests/CP/Navigation/NavTransformerTest.php
At a high level, this PR changes the YAML schema in saved CP Nav preferences to use a new array format...
```yaml
nav:
reorder:
- fields
- content
sections:
...
```
Reordering the old way required object key order to be preserved, but this breaks down once saved to JSON column in MySQL, and it tries to order keys alphabetically instead...
```yaml
nav:
reorder: true
sections:
fields: @inherit
content: @inherit # This would end up first, because `c` comes before `f`
```
This new format solves that ordering issue in SQL, but should also work just fine in flat file scenarios. I have also taken care to ensure the old legacy format can still be read when building navs from existing users' preferences as well.
=> [5.x] Fix CP nav ordering for when preferences are stored in JSON SQL columns

src/StaticCaching/Replacers/NoCacheReplacer.php, tests/StaticCaching/FullMeasureStaticCachingTest.php
I've worked on a couple of PR's for Jonas' Livewire addon to enhance support for Statamic's static caching. See https://github.com/jonassiewertsen/statamic-livewire/pull/61 and https://github.com/jonassiewertsen/statamic-livewire/pull/64. 
The newly added `AssetsReplacer` adds support for Livewire's [`@assets` Blade directive](https://livewire.laravel.com/docs/javascript#loading-assets), that allows you to push assets into the `<head>`. 
I've previously PR'd support for Livewire and Statamic's full measure static caching in https://github.com/statamic/cms/pull/8762. This script works as expected in general scenarios. However, I've encountered an edge case, where the CSRF token isn't replaced in time before a request to Livewire is made. 
This can happen, when a script, added to the …
=> [5.x] Fix issue when using Livewire with full measure static caching

src/StaticCaching/Cachers/AbstractCacher.php
While overriding the ApplicationCacher with my own Cacher, to change the logic behind cache key creation, I found I had to override 2 methods instead of one because the logic was duplicated... 
There is no breaking change in here, just using an already existing method instead.
=> [5.x] Use existing getUrlsCacheKey method instead of duplicating the creation logic

resources/js/components/publish/FieldMeta.vue, routes/cp.php
This pull request fixes an issue with filters, where a config field (usually a Select field with lots of options) could cause a request to go over the server's max headers size.
This can be easily resolved by sending the encryped field config in a POST request, rather than a GET request, since POST requests can handle larger payloads.
I've kept the `GET` version of the `field-meta` endpoint for now, as it's being used in third-party addons ([example](https://github.com/tv2regionerne/statamic-filter-builder/blob/d3a117b25ba4d3d4580b3806e77aa46aad9ddacc/resources/js/components/fieldtypes/Mixins/UsesFields.vue#L74)).
For easier testing, here's a filter with lots of select options: https://gist.github.com/duncanmcclean/171e55a861273d111c6ca037d8650aad
=> [5.x] Allow for large field configs in filters

resources/css/elements/forms.css
This PR fixes a tiny UI spacing bug with textareas.
Before:
After:
=> [5.x] Fix textarea UI bug

src/Http/Controllers/CP/Users/PasswordController.php
This PR fixes the following error when changing the password of a user within the control panel:
The controller was trying to deal with the user as an Eloquent model, rather than using Statamic's facade.
=> [5.x] Fix User Accessor in Password Reset

src/Console/Commands/MakeAddon.php
This pull request fixes an issue with the `php please make:addon` command where Composer will throw an error when requiring a new addon when an app's `minimum-stability` setting is anything other than `dev`.
=> [5.x] Allow make:addon to work for any minimum-stability

resources/js/components/publish/HasActions.js
This PR fixes incorrect toast status, when actions are ran from the publish form. The change to `data-list\HasActions.js` was initially added in #10264, but the corresponding changes to `publish/HasActions.js` were missing. That resulted in a "false positive" toast when an Action would throw an exception from its `run` method—see below.
=> [5.x] Fix false-positive on publish form Action exceptions

src/Marketplace/Client.php
In #10815, we introduced caching and locking around requests to Statamic's Marketplace API. 
However, when the lock times out and we want to serve the cached response, an error would occur complainging that the `$key` variable was undefined. This PR should fix that by defining it outside of the try/catch statement.
=> [5.x] Fix "Undefined variable $key" error with Marketplace API Client

src/Forms/Tags.php, src/Stache/Query/SubmissionQueryBuilder.php
This pull request implements filtering, sorting and pagination to the `{{ form:submissions }}` tag, since form submissions have their own query builder now (after #6455).
Related: https://github.com/statamic/ideas/issues/450#issuecomment-2366918848
=> [5.x] Allow filtering/sorting/paginating with the `form:submissions` tag

resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
When you have an assets field that does _not_ have the new dynamic feature enabled and no `folder` set (so you
are intending the assets to go directly in the container) it results in a validation error.
The issue was that slashes were being stripped so the required `folder` should have been `'/'` but it became `''`
resulting in a validation error.
Bug introduced in #10808
Fixes #10856
=> [5.x] Fix assets not being uploadable when not using dynamic folders

src/Dictionaries/BasicDictionary.php
This pull request fixes an issue when searching for a multi-word option in the Dictionary fieldtype because it was only taking option "values" into account and not their labels.
For example: you couldn't search `Cold Cases`, you'd have to search `Cold-Cases` for a result to be returned.
Fixes #10823.
=> [5.x] Allow searching by labels in Dictionary fieldtype

tests/Dictionaries/TimezonesTest.php
There were some recent random looking failure on Windows.
Rather than checking against a hardcoded number, check against what we'd get back from PHP.
=> [5.x] Better timezone dictionary test

src/Providers/AddonServiceProvider.php
It's pretty common for an addon to have `routes/web.php`, `routes/cp.php`, `routes/actions.php` route files. Right now, you have to configure these yourself in the addon's `ServiceProvider`:
```php
protected $routes = [
'web' => __DIR__.'/../routes/web.php',
'cp' => __DIR__.'/../routes/cp.php',
'actions' => __DIR__.'/../routes/actions.php',
];
```
However, if you're following convention, it would be nice if Statamic would automatically register an addon's route files, in a similar fashion to how fieldtypes, tags, etc are autoloaded.
Inspired by #9270.
=> [5.x] Auto-load addon routes

src/Search/Algolia/Query.php, tests/Search/AlgoliaQueryTest.php
If you have pagination enabled in the search tag the index is queried twice, once when fetching the results themselves and once when counting the results for pagination. With the Algolia driver both of these queries are identical but consume two of your search requests.
This PR blink caches the API call so that the first request can be reused for the count.
=> [5.x] Blink cache Algolia search API calls

src/Fieldtypes/Relationship.php
This PR ensures a relationship's getCreatables is only called if it's possible to create items. This ensures that any policies and gate checks for creation are not called unnecessarily.
This might make a dent in https://github.com/statamic/cms/issues/7132
=> [5.x] Only get relationship createables if can create

src/Tags/Collection/Entries.php
This PR updates the collection tag to query scopes after orderBys, which allows the scope to modify the default orderBy set.
For example, in the linked issue, inside the scope you could:
```php
public function apply($query, $values)
{
$query->reorder('my_column', 'desc');
}
```
Requires: https://github.com/statamic/cms/pull/10871
Closes https://github.com/statamic/cms/issues/10230
=> [5.x] Run query scopes after all other query methods so the query can be changed

resources/js/components/field-conditions/Condition.vue
If referenced field is a `revealer`, show condition value as boolean toggle, just like we do for `toggle` fieldtypes...
=> [5.x] Show toggle UI in conditions builder for revealer fields

src/Query/Builder.php, src/Query/EloquentQueryBuilder.php, tests/Data/Entries/EntryQueryBuilderTest.php
This PR adds a reorder() method to the query builders, allowing any existing orders to be cleared and a new one optionally set.
eg.
```php
$query->reorder(); // clears all orders
$query->reorder('title', 'desc'); // clears all orders and orders by title descending
```
=> [5.x] Add reorder() query builder method

src/Providers/AddonServiceProvider.php
This pull request fixes an issue with the addon auto-loading feature introduced in #9270, where it would attempt to autoload abstract classes and interfaces, which obviously won't work.
For example, in my Simple Commerce addon I was extending Statamic's abstract `GeneratorCommand` class. However, it was still trying to be loaded by the autoloading stuff, resulting in this error:
Fixes duncanmcclean/simple-commerce#1163.
=> [5.x] Prevent autoloading of abstract classes and interfaces

src/Providers/AddonServiceProvider.php
Since https://github.com/statamic/cms/pull/9270 issues have been reported with add-ons that include console commands (https://github.com/statamic/cms/issues/10873)
This PR updates the logic around the command autoloading to ensure we only run that once the app is booted.
Closes https://github.com/statamic/cms/issues/10873
=> [5.x] Prevent autoloading addon files causing exception when called early

src/Policies/AssetFolderPolicy.php
In our `AssetFolderPolicy`, we are currently performing a whole bunch of redundant ability checks, which [really slows down performance in super large asset containers](https://github.com/statamic/cms/issues/9710).
For example, this ability check is done in our `AssetFolderPolicy`:
But then right after that, you can see we loop over every asset in the folder:
Which essentially just does the same ability check within `AssetPolicy`:
This PR changes improves performance by only looping over each asset if a custom `AssetPolicy` class is registered. If a custom policy is registered, there is likely extra logic that run to be checked on an asset-by-asset basis, so we'll do the more thorough check only in those scenarios.
Fixes #9710
=> [5.x] Improve `AssetFolderPolicy` performance

resources/views/updater/index.blade.php, src/Extend/Addon.php, src/Http/Controllers/CP/Updater/UpdaterController.php, src/Updater/UpdatesOverview.php
Hide this updates badge count for local/dev installations...
=> [5.x] Don't show updates badge count for local/dev installations

src/Providers/AddonServiceProvider.php
This pull request fixes an issue where Statamic would try and load non-PHP files in autoloaded directories, such as `src/Commands`.
=> [5.x] Prevent autoloading non-PHP files

src/Providers/RouteServiceProvider.php
The globals route binding site check needs to consider the requested site when on an API route
Closes https://github.com/statamic/cms/issues/10636
=> [5.x] Check site requested when using global route binding on api routes

src/Dictionaries/BasicDictionary.php, src/Dictionaries/Dictionary.php, src/Providers/ExtensionServiceProvider.php, src/Tags/Dictionary/Dictionary.php, src/Tags/Dictionary/DictionaryItem.php, tests/Tags/DictionaryTagTest.php
This PR adds a `{{ dictionary }}` tag to Antlers, allowing you to use dictionaries outside the field type.
`{{ dictionary:countries }}{{ label }} {{ value }}{{ /dictionary:countries }}`
or
`{{ dictionary handle="countries" }}{{ label }} {{ value }}{{ /dictionary}}`
It also gets any ‘extra’ data:
`{{ dictionary handle="countries" }}{{ emoji }} {{ value }}{{ /dictionary}}`
`{{ dictionary:countries search="Aus" }}{{ label }} {{ value }}{{ /dictionary:countries }}`
Any params passed that arent handle or search will be passed as config... eg
`{{ dictionary:countries emojis="false" }}{{ label }} {{ value }}{{ /dictionary:countries }}`
It supports conditions, pagination, chunking and limiting eg
`{{ dictionary:countries iso2:is="AUS" paginate="4" }}{{ label }} {{ value }}{{ /dictionary:countries …
=> [5.x] Dictionary tag

src/Console/Commands/InstallEloquentDriver.php
This pull request adds three new options to the `install:eloquent-driver` command, to assist with some changes we're making in the CLI.
* The `--all` option will select all of the repositories - preventing the "Which repositories would you like to migrate?" prompt from showing.
* The `--import` option will automatically toggle the importing of existing content - preventing the individual "Would you like to import existing ...?" prompts from showing.
* In the CLI, we want to import all existing content so you don't start out with an empty site.
* The `--without-messages` option will prevent any info messages from showing, to cleanup the output.
*  We can't use `--quiet` because that stops Laravel Prompts from showing.
=> [5.x] Improvements to the `install:eloquent-driver` command

.github/ISSUE_TEMPLATE/bug_report.yml
This pull request tweaks the description of the "Environment" textare in the "Bug Report" issue template, to make it clearer that it should be the _full_ output of the command, not just the partial output.
=> [5.x] Update "Bug Report" issue template

src/Tags/Taxonomy/Taxonomy.php
This PR adds a `count` method to the `taxonomy` tag. This is a simple copy of the existing `{{ collection:count }}` tag.
```antlers
{{ taxonomy:count in="categories" collection="galleries" }}
```
I needed this for the upcoming photography starter kit.
=> [5.x] Add `{{ taxonomy:count }}` tag

src/Console/Commands/Multisite.php
While it is possible to place your content outside the statamic project by just connfiguring the stores in the config/statamic/stache.php, it's necessary to use these paths in the multiside command as well.
=> [5.x] Use directory paths from stache config instead of static paths

src/Modifiers/CoreModifiers.php, tests/Modifiers/BardTextTest.php
This PR ensures that if no 'type' is present the node is skipped.
Closes https://github.com/statamic/cms/issues/10912
=> [5.x] Handle empty nodes in bard_text modifier

src/Globals/AugmentedVariables.php
This pull request fixes an issue where the default values for Globals weren't available in templates. 
This was due to the fact that the `AugmentedVariables` class was only making available fields with *actual* values, unlike entries where we also merge in the keys of all blueprint fields.
Fixes #10901.
=> [5.x] Ensure default values for globals are available in templates

resources/js/components/publish/Sections.vue
This pull request fixes an issue where the synced/de-synced state was showing for fields that weren't on the linked entry's blueprint.
Fixes #10930.
=> [5.x] Only show the sync/de-synced state for syncable fields

src/Search/Result.php
This pull request fixes an issue where it wasn't possible to order entry search results by `date`.
Essentially, when you order search results, it uses the `DataCollection::multisort()` method to perform the ordering. As part of that, it tries to get the value of the `date` field using this code below:
https://github.com/statamic/cms/blob/7bf2816e97d40a081c366d64b383711371140f12/src/Data/DataCollection.php#L99-L101
The `->get()` here defers to the `Result::get()` method, which will do `->get('date')` on the entry. However, since dates aren't part of an entry's data, it was trying to order results by `null`.
This PR fixes that by checking if the `$key` is `date` and deferring to the entry's `date` method instead.
Fixes #10892.
=> [5.x] Fix ordering search results by date

resources/js/components/assets/Uploader.vue
When you use the uploader (for example, in the asset browser) and one file error is, any subsequent erroring files will just sit there and spin and not show their own errors. Or rather, the first erroring file will have its error message updated with the next error, although its usually the same message so you don't notice.
This is because the upload queue always tries to grab the first upload in the queue, even if it has errored.
This PR makes it so that it will grab the next non-erroring upload in the queue.
=> [5.x] Fix errors in upload queue

src/Console/Commands/StarterKitInstall.php, src/StarterKits/LicenseManager.php
Currently, when you try to install a paid starter kit into an existing site *without* the `--license` parameter, it'll error out:
However, I thought it'd be nice if it could prompt you for your license key instead of erroring out straight away:
Inspired by https://github.com/statamic/docs/issues/1480.
=> [5.x] Prompt for license when installing starter kit

src/Console/Commands/MakeDictionary.php, src/Console/Commands/MakeFieldtype.php, src/Console/Commands/MakeFilter.php, src/Console/Commands/MakeModifier.php, src/Console/Commands/MakeScope.php, src/Console/Commands/MakeTag.php, src/Console/Commands/MakeWidget.php
Some of the `make:` command descriptions mention making addons, which is left over from v2 where you had to create addons to do anything custom.
=> [5.x] Tweak `make:` command descriptions

src/Actions/RenameAssetFolder.php, src/Http/Controllers/CP/Assets/BrowserController.php
Following on from #10941, this PR will autopopulate the current name of a folder when using the "Rename Folder" action.
This PR also fixes an issue where actions weren't being returned for individual folders, only for the "current" folder. This was probably caused by #10419.
=> [5.x] Improve UX of rename asset folder action

resources/js/components/assets/Browser/Browser.vue
History navigation currently doesn't work inside the asset browser. Going back and forth updates the url and shows a loading indicator, but it doesn't update the current folder or its contents. This PR re-enables it by watching the selected path prop and updating the current path from the watcher whenever the passed-in path changes.
Closes #10920
=> [5.x] Fix asset browser history navigation

src/Console/Commands/InstallEloquentDriver.php
This pull request prevents commands from timing out and causing errors during the `install:eloquent-driver` command.
The import commands can take a while to run, especially when there's a lot of existing content being imported.
Fixes statamic/eloquent-driver#364.
=> [5.x] Prevent timeout during `install:eloquent-driver` command

src/Auth/Protect/Protectors/Password/Controller.php, src/Auth/Protect/Protectors/Password/PasswordProtector.php
This PR resolves an issue that would occur if you clicked the submit button on the password protect page without having entered a password.
**Issue before PR**
**After PR**
=> [5.x] Fix issue if submitted password is null

src/Console/Commands/MakeAction.php, src/Console/Commands/MakeDictionary.php, src/Console/Commands/MakeFieldtype.php, src/Console/Commands/MakeFilter.php, src/Console/Commands/MakeModifier.php, src/Console/Commands/MakeScope.php, src/Console/Commands/MakeTag.php, src/Console/Commands/MakeWidget.php
Now that addon "components" are being autoloaded behind the scenes by Statamic, we don't need to be manually setting the protected properties on addon service providers anymore.
=> [5.x] `make:` commands dont need to register addon components

src/Auth/Protect/Protectors/Password/Controller.php
This PR makes the data of a password-protected page available in the view. This is useful in situations like the following example, where you want to show things like a title or images.
=> [5.x] Make data of password-protected available in the view

src/Auth/Protect/Tags.php
This PR replaces https://github.com/statamic/cms/pull/10947 and takes another stab at making the password protect page flow a little better. 
It introduces a new `invalid_token` variable that can be used instead of the existing `no_token` variable. Both variables are available when the token is missing or invalid. Previously, the `no_token` variable was only available when the token was missing. Functionally, both variables are the same, but `invalid_token` might make a little more sense to use.
=> [5.x] Introduce `invalid_token` variable for password protected page

resources/js/components/assets/Browser/Browser.vue
PR #10948 tried to enable history browsing in the asset browser and inadvertently introduced a bug where editing an asset would try to load the `filename.txt/edit` url in the asset browser. This fixes the regression by ignoring path updates pointing at the asset editor.
Fixes #10957
=> [5.x] Fix regression where editing an asset loads the `/edit` url in the browser

src/Fieldtypes/Sets.php
This pull request fixes an issue I just spotted where it wasn't possible to edit a Bard field when one of the sets has no fields.
=> [5.x] Fix error when editing Bard field with set and no fields

src/Console/Commands/stubs/addon/README.md.stub
This pull request removes mention of installing addons via the Control Panel from the `README.md` stub which gets published when you run `php please make:addon`.
=> [5.x] Remove mention of installing addons via CP from addon stub

src/Auth/Protect/Protection.php, src/Http/Responses/DataResponse.php, src/StaticCaching/Middleware/Cache.php, tests/FrontendTest.php
This pull request fixes an issue where protected pages would be staticly cached, unless manually excluded in the `static_caching.php` config file.
Closes statamic/ideas#190.
=> [5.x] Prevent protected pages being cached

resources/css/vendors/codemirror.css
This pull request fixes an issue with the Markdown fieldtype when using the Control Panel with an RTL locale, like Persian. 
I've fixed this by removing a CSS rule which was causing the text to show left-to-right, even when the CP is in right-to-left mode. 
This CSS rule was updated in #9447. Maybe there's a reason for it... but it doesn't match how other fieldtypes (like the Textarea fieldtype) handle RTL.
Fixes #10928.
=> [5.x] Fix text direction in the Markdown fieldtype when using RTL mode

src/Assets/AssetFolder.php, src/Http/Controllers/CP/Assets/BrowserController.php
This pull request makes it possible to sort folders in the Asset Browser. Previously, changing the sort order wouldn't have any affect on folders.
Closes #10919.
=> [5.x] Allow sorting folders in asset browser

resources/js/components/assets/Upload.vue, resources/js/components/assets/Uploader.vue, src/Http/Controllers/CP/Assets/AssetsController.php, tests/Feature/Assets/StoreAssetTest.php
Fixes #10980
I went with a [409 Conflict status](https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-409-status-code/) as it seems the most appropriate:
> The request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request.
Now you will only get the option to "fix" the upload when its due to being a duplicate. Regular validation errors and file size limit issues will not.
=> [5.x] Avoid showing asset upload fixes when inappropriate

src/Modifiers/CoreModifiers.php, tests/Modifiers/SortTest.php
This PR adds support for query builders to the `sort` modifier. I ran into this on a collection term details page where I wanted to sort the entries by title.
Now you can do this:
```antlers
<a-components.galleries-grid :entries="entries | sort('title')" />
```
Also needed this for the photography starter kit.
=> [5.x] Make sort modifier work with query builders

src/Providers/AddonServiceProvider.php
Currently, things like fieldtypes, tags and route files in addons are autoloaded if they follow convention.
However, when I was tidying up a `ServiceProvider` in one of my addons the other day, I realised that event listeners and subscribers weren't being autoloaded.
This pull request makes that possible by using Reflection to extract the event being listened to from the listener's typehints.
=> [5.x] Autoload event listeners and subscribers

resources/js/components/fields/Settings.vue
This pull request fixes a `z-index` issue when configuring Replicator/Bard sets in the Field Settings stack. I was only able to replicate the issue in a Chromium browser.
Fixes  #10897.
=> [5.x] Fix z-index issue when configuring Replicator fields

src/Forms/Email.php, tests/Forms/EmailTest.php
In some of our projects, we are using some of the form email configuration data in the email content. (Specifically, we added a custom field that lets us set email content in this configuration---however you may also consider using the email subject, for example).
Before a recent Laravel update (11.16.0 to be exact), we were able to get the right data in a sort of hacky way. However, this doesn't work anymore as a side effect of a small change in the Laravel mailer where the email data only gets built after setting the content, rather than before.
This small change fixes our *very* specific use case when having more than 1 email for a form active and wanting to use some of the email configuration fields inside of those emails' content :)
=> [5.x] Make email config data accessible in email templates

resources/css/vendors/codemirror.css
This reverts #10931
It was pointed out how awkward it is when using RTL in markdown when you are mixing RTL text and markup.
It looks like CodeMirror has support for handling these situations. We should solve it properly later. https://codemirror.net/examples/bidi/
=> [5.x] Revert markdown field RTL PR 10931 

src/Marketplace/Marketplace.php
This fixes an error when the marketplace client returns null for whatever reason.
It looks like there could be a problem with the lock in some situations, and Client::get() returns null, causing errors further up.
This PR will prevent the error, but there will be missing addon data. That's less of a problem for those affected.
=> [5.x] Avoid error when marketplace client returns null

resources/js/components/assets/Upload.vue, resources/js/components/fieldtypes/FilesFieldtype.vue
This pull request fixes a couple of issues when the Files fieldtype is used in Dark Mode.
**Before:**
**After:**
=> [5.x] Fix issues with the Files fieldtype in Dark Mode

src/Console/Commands/MakeUser.php, tests/Console/Commands/MakeUserTest.php
Adds support for a `password` option to the `make:user` command to enable certain integrations.
=> [5.x] Add `password` option to `make:user` command

resources/js/components/assets/Uploader.vue, resources/js/components/fieldtypes/FilesFieldtype.vue, src/Http/Controllers/CP/Fieldtypes/FilesFieldtypeController.php, src/Rules/AllowedFile.php
This pull request adds an `allowed_extensions` config option to the Files fieldtype, allowing you to override which file extensions are allowed.
For example: in the case of the Importer addon, I want to allow `.csv` and `.xml` files to be uploaded, but not any other file extensions.
=> [5.x] Add `allowed_extensions` option to Files fieldtype

src/Forms/Tags.php
This PR introduces three new hooks into form tag processing. These hooks allow add-ons to do the following:
- Add additional attributes to generated form tags
- Add additional content at the start of the form
- Add additional content before the end of the form
=> [5.x] Introduce additional form tag hooks

src/Search/Algolia/Index.php
This PR adds Algolia's highlights and snippets to the result data. Highlights are usually included by default, snippets can be included with these [settings](https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/):
```php
'default' => [
'driver' => 'algolia',
'settings' => [
'attributesToSnippet' => ['content:40'],
'highlightPreTag' => '<mark>',
'highlightPostTag' => '</mark>',
],
],
```
You can then use them in results:
```antlers
<a href="{{ $url }}">
<h2>{{ search_highlights:title:value }}</h2>
<p>{{ search_snippets:content:value }}</p>
</a>
```
The key names are based on the convention established in the comb driver for snippets.
=> [5.x] Include Algolia highlights and snippets

src/Providers/AddonServiceProvider.php
Fixes #11012
This adjusts the code to allow for unions, eg. `handle(EventOne|EventTwo $event) { }` which is where the error in #11012 was coming from.
It also adds support for `handleWhatever(EventName $event) { }` syntax, since I've lifted the code from Laravel. This is probably a lesser known thing but it works in Laravel so should here.
=> [5.x] Support unions in addon event listener discovery

src/Tags/FluentTag.php, tests/Tags/FluentTagTest.php
Some of our recent projects use third-party templating languages and would benefit from being able to set the content of tag pairs when emulating Antlers tags. That's what this PR would allow.
So to emulate...
```antlers
{{ dictionary handle="countries" }}
{{ label }}
{{ /dictionary }}
```
One could do the following...
```php
Statamic::tag('dictionary')
->params(['handle' => 'countries'])
->withContent('{{ label }}')
->fetch();
```
=> [5.x] Allow setting tag pair content from fluent tags

resources/js/components/FileIcon.vue, resources/js/components/fieldtypes/assets/Asset.js, src/Assets/Asset.php, src/Fieldtypes/Assets/ImageRule.php, src/Filesystem/AbstractAdapter.php, src/Http/Resources/CP/Assets/FolderAsset.php, tests/Assets/AssetTest.php, tests/Filesystem/FilesystemAdapterTests.php, tests/Imaging/ImageValidatorTest.php
- Add `avif` to the list of known image formats
- Add `webp` where it was still missing as well, for good measure :)
=> [5.x] Add support for avif image format

resources/js/components/field-validation/Builder.vue
I was encountering an error when using the example field while trying to extend rules this way in cp.js.
```
Statamic.booting(() => {
Statamic.$config.set('extensionRules',
[
{
label: 'Email Authenticator',
value: 'email_authenticator:',
example: 'email_authenticator:form'
},
]);
});
```
```
TypeError: Cannot read properties of undefined (reading 'example')
at q.helpBlock (app-4350e625.js:392:218858)
at M.get (app-4350e625.js:5:42279)
at M.evaluate (app-4350e625.js:5:43343)
at q.helpBlock (app-4350e625.js:5:45757)
at q.M (app-4350e625.js:392:221720)
at M._render (app-4350e625.js:5:24987)
at q.N (app-4350e625.js:5:29723)
at M.get (app-4350e625.js:5:42279)
at M.run (app-4350e625.js:5:43050)
at flushSchedulerQueue (app-4350e625.js:5:32642)
TypeError: Cannot read properties of undefined …
```
=> [5.x] Fix helpBlock error with custom js validation rule

src/Filesystem/AbstractAdapter.php
I learned about this the hard way.  I spent over an hour trying to figure out why a custom media importer I had built was failing on the step only to find out `$assetContainer->disk()->put()` returns null instead of the normal true/false on success/fail.
Example of what I am trying to solve:
```php
$success = \Statamic\Facades\AssetContainer::find('assets')->disk()->put('test.txt', 'test');
```
You'd expect if the file is created `$success` would be true, but it is not.  It is null.
This is true of all other methods in the AbstractAdapter so I believe this being left out is just a typo/bug.
One could make an argument this should target 6.x since it changes a return type, but since null was always being returned there should be no logic dependent upon it.
=> [5.x] Fix Filesystem AbstractAdapter put method return

config/routes.php, config/system.php, src/Entries/Collection.php, src/Http/Controllers/FrontendController.php, src/Taxonomies/Taxonomy.php, tests/Routing/RoutesTest.php
This PR adds a new config `statamic.routes.layout` that allow the default layout to be changed to something other than `layout`. I've also set it to look for an .env variable (`STATAMIC_FRONTEND_ROUTES_LAYOUT`).
Our use is we have a site where the same codebase is shared across slightly different site versions and need to adapt the layout significantly per site - but other than that the codebase is the same.
If it helps make the case - Livewire [allow the layout to be changed in a config](https://github.com/livewire/livewire/blob/82e2b40361f1779f541c18ee30d2d0d201ae768b/config/livewire.php#L41).
=> [5.x] Add a config for specifying the default layout

resources/views/partials/scripts.blade.php
This pull request fixes an issue reported via support, where external script URLs containing query parameters like `?foo=bar&bar=baz` were being returned as `?foo=bar&amp;bar=baz`.
=> [5.x] Fix query parameters in external script URLs being wrongly encoded

package-lock.json, package.json, resources/js/components/data-list/DataList.vue, resources/js/components/fields/FieldtypeSelector.vue, src/Dictionaries/Countries.php, src/Dictionaries/Currencies.php, src/Dictionaries/Dictionary.php, src/Dictionaries/File.php, src/Dictionaries/Timezones.php, src/Fields/Fieldtype.php, src/Fieldtypes/Assets/Assets.php, src/Fieldtypes/Bard.php, src/Fieldtypes/Collections.php, src/Fieldtypes/Color.php, src/Fieldtypes/Date.php, src/Fieldtypes/Dictionary.php, src/Fieldtypes/Entries.php, src/Fieldtypes/Markdown.php, src/Fieldtypes/Replicator.php, src/Fieldtypes/Select.php, src/Fieldtypes/Toggle.php, src/Fieldtypes/Yaml.php, tests/Fields/FieldtypeTest.php
This PR allows fieldtypes to define keywords that will be used in the selector.
For example, if you search for "rich text" or "gutenberg" you will now see Bard as a result.
Dictionaries can also define keywords and will get pulled in by the fieldtype. So for example searching "country" will show the dictionary fieldtype as a result.
This also updates Fuse.js to the latest version but I don't believe that's an issue as it's only used in core. It's not exposed to the public.
=> [5.x] Improved fieldtype search using keywords

resources/js/components/fieldtypes/FilesFieldtype.vue
This pull request prevents the filenames of existing files from being truncated in the Files fieldtype.
**For example:** in the importer, I'm passing the basename of the file to the Files fieldtype, allowing users to see the currently uploaded file and replace it, if needed.
I thought that since we're [not truncating filenames in the `Upload` component](https://github.com/statamic/cms/blob/5.x/resources/js/components/assets/Upload.vue#L11), we don't need to be here. Although, I might be wrong.
=> [5.x] Files Fieldtype: Don't truncate existing filename

src/Fieldtypes/Relationship.php, src/Fieldtypes/Terms.php
When creating new taxonomy terms in a typeahead select, it currently allows creating new terms even if that term already exists. Both the existing as well as the newly created term can be selected and submitted. On save, the data is deduplicated, but the keys aren't reset. The resulting data structure is now an array with skipped keys, which in JSON turns into an object, and the input refuses to display the data. See issue #11019 for details and screenshots.
This PR fixes the latter part (the corrupted data and broken input state) by always making sure that relationship field data is returned as a list, without skipping array keys.
Partially closes #11019.
=> [5.x] Fix typeahead relationship input corrupting data

src/Console/Commands/MakeUser.php
If you have Pro disabled, already have a user, and run `make:user`, currently it tells you Pro is required and exits.
This PR will now offer you to enable Pro and then continue with the command.
=> [5.x] Offer to enable Pro during make user command

src/Exceptions/ComposerJsonMissingPreUpdateCmdException.php, src/Exceptions/StatamicProRequiredException.php, src/Ignition/Solutions/EnableComposerUpdateScripts.php, src/Ignition/Solutions/EnableStatamicPro.php
Runnable solutions weren't actually showing the option to run them.
For example, the StatamicProRequiredException should show the button to enable it for you. It wasn't appearing.
Now it does again.
=> [5.x] Fix Ignition Runnable Error Solutions

src/Console/Commands/stubs/addon/.gitignore.stub
This pull request updates the `.gitignore` stub used when creating addons. 
* The `mix-manifest.json` file doesn't exist anymore (addons now use Vite). 
* It's generally discouraged to commit `composer.lock` files inside packages. 
* No one wants to commit the PHPUnit results cache 😅
=> [5.x] Update addon `.gitignore` stub

resources/views/extend/forms/fields/integer.antlers.html
This pull request adds a template for Integer fields in forms to ensure `type="number"`, instead of being a text input.
Fixes #11063.
=> [5.x] Integer fields should render with `type="number"`

composer.json, src/Exceptions/AssetContainerNotFoundException.php, src/Exceptions/BlueprintNotFoundException.php, src/Exceptions/CollectionNotFoundException.php, src/Exceptions/ComposerJsonMissingPreUpdateCmdException.php, src/Exceptions/DuplicateFieldException.php, src/Exceptions/FieldsetNotFoundException.php, src/Exceptions/FieldsetRecursionException.php, src/Exceptions/FieldtypeNotFoundException.php, src/Exceptions/NavigationNotFoundException.php, src/Exceptions/NotBootedException.php, src/Exceptions/SiteNotFoundException.php, src/Exceptions/TaxonomyNotFoundException.php, src/Exceptions/TermsFieldtypeBothOptionsUsedException.php, src/Exceptions/TermsFieldtypeTaxonomyOptionUsed.php, src/Fieldtypes/Assets/UndefinedContainerException.php, src/Fieldtypes/MultipleValuesEncounteredException.php, src/Forms/Exceptions/BlueprintUndefinedException.php, src/Forms/Exceptions/FileContentTypeRequiredException.php, src/Ignition/SolutionProviders/OAuthDisabled.php, src/Ignition/SolutionProviders/UsingOldClass.php, src/Ignition/Solutions/EnableOAuth.php, src/Ignition/Solutions/UpdateClassReference.php, src/Modifiers/ModifierNotFoundException.php, src/Providers/IgnitionServiceProvider.php, src/View/Antlers/Language/Runtime/RuntimeParser.php, src/Widgets/WidgetNotFoundException.php, src/Yaml/ParseException.php
This PR is just cleaning up references to legacy classes.
Spatie\Ignition to Spatie\ErrorSolutions
There are no functional changes.
Ideally we would also rename the Statamic\Ignition namespace to Statamic\ErrorSolutions but that's a breaking change. We can do it in v6.
=> [5.x] Adjust legacy ignition classes

src/Console/Commands/StarterKitExport.php, src/StarterKits/Exporter.php, src/StarterKits/Installer.php, tests/StarterKits/ExportTest.php
This PR adds `--clear` option for `starter-kit:export` command.
We talked about whether or not to make this the default behaviour, but it gets complicated for various reasons...
- Say you intentionally have `.github` directory in your starter kit repo, but also different `.github` directory in your sandbox/demo app repo, you wouldn't want to add this to your `export_paths`, but you also wouldn't want `--clear` to clear this stuff.
- Or maybe you want to make changes to the stubbed composer.json, should `--clear` also clear that file?
- etc.
We could find ways to make this behaviour more magical, but we opted to go with a simple opt-in `--clear` option.
When explicitly exporting with this option, the starter kit dev _knows_ that it's going to clear everything out first, and then they can …
=> [5.x] Add `--clear` option for `starter-kit:export`

resources/js/components/entries/BaseCreateForm.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/publish/Container.vue, resources/views/entries/create.blade.php, resources/views/entries/edit.blade.php, src/Fieldtypes/Entries.php, src/Http/Controllers/CP/Collections/EntriesController.php, src/Http/Controllers/CP/Collections/ExtractsFromEntryFields.php
Continues from #10588.
This allows entries to base field conditions on "extra" values.
At the moment, that's just `depth`. For example, you could show a field if its depth in the structure is above 2.
```yaml
if:
depth: '> 2'
```
=> [5.x] Extra values for entry field conditions, including depth

src/Exceptions/Concerns/RendersHttpExceptions.php
In https://github.com/statamic/cms/pull/11025 I missed front end error rendering - they also need to respect the new config.
=> [5.x] Use layout config in errors too

src/Auth/Eloquent/User.php
This pull request fixes an error which would occur after a user's role had been deleted.
Fixes #11067.
=> [5.x] Fix error after deleting role when storing users in the database

routes/cp.php, src/Http/Controllers/CP/Collections/EditRedirectController.php, tests/CP/EditRedirectControllerTest.php
This is more of an invisible nicety that I think is really useful in Craft CMS.
Sometimes I have just the ID of a given entry and I want to get to the control panel edit screen with that information alone. I can simply go to `/admin/edit/{id}` and it will take me to the correct spot in the admin area. Now this is possible with Statamic.
- Given an entry that has an ID of `72edf157-4010-4ebc-9c8c-146181c12c4c` and is in the "Blog" collection
- If you go to `/admin/edit/72edf157-4010-4ebc-9c8c-146181c12c4c`
- You will be redirected (and prompted to sign in if not already) to `/admin/collections/blog/entries/72edf157-4010-4ebc-9c8c-146181c12c4c`
=> [5.x] Create edit/{id} route for control panel access

src/Fields/Blueprint.php
This pull request adds a `fullyQualifiedHandle` method to the `Blueprint` class as the format of the handle (eg. what you use when doing `Blueprint::find()`) is different depending on if it has a namespace or not, or if it's coming from an addon.
I initially added this method as part of #11066. However, even with no `->fresh()` method, I still feel like this would be a useful method to have if folks want to "refresh" blueprints themselves.
=> [5.x] Add `fullyQualifiedHandle` method to `Blueprint`

resources/js/components/fieldtypes/AssetFolderFieldtype.vue, resources/lang/en/fieldtypes.php, src/Fieldtypes/AssetFolder.php
Currently, the Asset Folders fieldtype relies on there being a `container` field in the same publish form.
This pull request adds the ability to specify the container as a config option on the fieldtype so it can be determined in the blueprint.
=> [5.x] Add "Container" option to Asset Folders fieldtype

src/Modifiers/CoreModifiers.php, tests/Modifiers/AmbersandListTest.php
- The `sentence_list` modifier accepts arrays and collections
- The `ampersand_list` modifier only accepts arrays
- Now it accepts both :)
- Very useful after plucking values from a query builder
=> [5.x] Accept collections in ampersand list modifier

resources/js/components/terms/BaseCreateForm.vue, resources/js/components/terms/CreateTermButton.vue, resources/views/taxonomies/show.blade.php, resources/views/terms/create.blade.php, src/Http/Controllers/CP/Taxonomies/TermsController.php, src/Taxonomies/Taxonomy.php, tests/Data/Taxonomies/TaxonomyTest.php
Allow customizing the label of the `Create Term` button. This already works for collections, just not for taxonomies. Mostly copy-and-paste from the implementation for entries.
```php
// lang/en/messages.php
return [
'tags_taxonomy_create_term' => 'New Tag'
];
```
=> [5.x] Allow customizing term create label

resources/js/components/blueprints/Builder.vue, resources/js/components/blueprints/TabContent.vue, resources/js/components/blueprints/Tabs.vue, resources/views/forms/blueprints/edit.blade.php, resources/views/usergroups/blueprints/edit.blade.php, resources/views/users/blueprints/edit.blade.php
This pull request hides the "Localizable" button on non-localizable blueprints, like users, groups and forms.
Fixes #11048.
=> [5.x] Hide "Localizable" button on non-localizable blueprints

src/Search/QueryBuilder.php
Would it be possible to split this logic out so transformResults could be called separately?
Im working on an update to Typesense to handle pagination on the API side (rather than getting all the results then paginating in Statamic), so I need to be able to transform inside my query builder paginate() function.
PR here if it helps make sense of what we need: https://github.com/statamic-rad-pack/typesense/pull/7
=> [5.x] Allow transformResults to be called separately from getBaseItems

resources/css/components/fieldtypes/button-group.css, resources/css/elements/buttons.css, resources/js/components/fieldtypes/ButtonGroupFieldtype.vue, src/Fieldtypes/ButtonGroup.php
This PR makes two small adjustments to the Button Group fieldtype:
1. Adds a `clearable` option to the config. When enabled, this works like the Select fieldtype but without a dedicated ✖ button. Instead, you can now just click the currently-selected option to deselect it. 
2. Previously, hovering anywhere to the right of grouped buttons (ie, in the blank, unused space after the group) would show a pointer cursor, as if there was an invisible button. Quick little CSS patch on the wrapper to use `cursor-default` instead.
Let me know if there are any edits I can help with, here!
=> [5.x] Enhancement: Make button groups clearable

src/Fields/Blueprint.php, src/Revisions/Revisable.php
This PR fixes an issue where after publishing a revision the `parent` set on the blueprint and field objects will still refer to the previous version of the entry.
This can cause issues during the `preProcess` calls fired by `PublishedEntriesController::extractFromFields` if you're using the parent. The issue we had is that we do something in `preProcess` that depends on the value of another field. We fetch the value of that field from the parent data, but if the parent is the previous version the value might be wrong. 
The reason updating the parent isn't done [just after clone](https://github.com/statamic/cms/blob/0d2403d69d467055e649815841ce401a4c2a210d/src/Entries/Entry.php#L682) (which would be the obvious place) is that the `save` calls further up in …
=> [5.x] Fix wrong blueprint parent after revision publish

resources/js/components/structures/PageEditor.vue, src/Http/Controllers/CP/Navigation/NavigationPagesController.php
A continuation of #11080 - this pull request provides `depth` as an extra value for field conditions when editing nav pages.
Closes  #11077.
=> [5.x] Extra values for nav field conditions, including depth

resources/views/assets/containers/blueprints/edit.blade.php
=> [5.x] Hide "Localizable" button in asset blueprints

src/Licensing/Outpost.php
This pull request prevents unnecessary requests from being made to the Outpost when the PHP version in the payload differs from the cached version.
For example: if you have a load balanced setup w/ multiple servers and you're rolling out PHP updates one at a time, your users might see the licensing banner if the Outpost's rate limiting kicks in.
Closes #11135.
=> [5.x] Prevent unnecessary requests to the Outpost when PHP version is different

src/Assets/AssetFolder.php, src/Http/Controllers/CP/Assets/FolderActionController.php, tests/Actions/DeleteAssetFolderTest.php, tests/Assets/AssetFolderTest.php
This prevents potential for path traversal when instantiating asset folders.
=> [5.x] Prevent asset folder path traversal

src/Fieldtypes/DictionaryFields.php, tests/Fieldtypes/DictionaryFieldsTest.php
This pull request fixes an issue with the `DictionaryFields` fieldtype, responsible for the configuration of Dictionary fields. 
When a dictionary _doesn't_ have any config fields, it'll be saved as `dictionary: artists`.
When a dictionary *does* have config fields, it'll be saved as an array, like:
```yaml
dictionary:
type: artists
category: rock
```
However, if a dictionary field was configured before any config fields were added, it would fail to be preprocessed correctly, due to just the dictionary select itself being processed, causing issues with some fieldtypes.
Fixes #11124.
=> [5.x] Fix issue when preprocessing dictionary config

tests/Feature/Assets/StoreAssetTest.php
There was a path traversal issue fixed in #10423 even when that wasn't the intention of the PR. A happy coincidence.
This PR adds test coverage for it.
=> [5.x] Add upload path traversal tests

src/Assets/Asset.php, tests/Assets/AssetContainerTest.php, tests/Assets/AssetFolderTest.php, tests/Assets/AssetTest.php
Continuation of #11136
Throws exceptions if you try setting `../` in the paths of assets too.
=> [5.x] More path traversal fixes

tests/Antlers/Runtime/ArithmeticTest.php, tests/Console/Commands/MakeDictionaryTest.php, tests/Extend/AddonTest.php, tests/Feature/GraphQL/Fieldtypes/DictionaryFieldtypeTest.php, tests/Feature/SlugTest.php, tests/Feature/Taxonomies/UpdateTermTest.php, tests/Feature/Users/UpdateUserTest.php, tests/Fieldtypes/ArrayTest.php, tests/Modifiers/ToJsonTest.php, tests/Modifiers/ToQsTest.php, tests/Modifiers/WhereInTest.php, tests/Routing/RouteBindingTest.php, tests/Validation/UniqueEntryValueTest.php, tests/Validation/UniqueTermValueTest.php, tests/Validation/UniqueUserValueTest.php
While working on #11114, I noticed that quite a few of our test classes have incorrect namespaces, leading to warnings when you run `composer dump-autoload`:
This PR fixes the namespaces for *most* of the classes mentioned in the above screenshots. I've ignored the ones coming from fixtures since they don't really need namespaces.
=> [5.x] Fix incorrect namespaces in tests

src/Fieldtypes/Assets/Assets.php
When configuring the `assets` field in the User Blueprint to use the user ID as the folder name, non-admin users encounter an error. This happens because the `first()` method can return `false` when no matching action is found, causing the subsequent call to `toArray()` to fail.
The issue arises from the following code:
```php
$action = Action::for($assetFolder, [
'container' => $container->handle(),
'folder' => $folder,
])->first(fn ($action) => get_class($action) === RenameAssetFolder::class)->toArray();
```
If no matching `RenameAssetFolder` action is found, `first()` returns `false`. The `toArray()` method is then called on this `false` value, leading to an error.
The fix ensures that the `first()` method's return value is properly handled using the null-safe operator `?->` before …
=> [5.x] Fix error when using user ID as folder name for avatar asset field in non-admin context

src/Console/Commands/Multisite.php
This pull request fixes an issue where the `php please multisite` command wasn't moving content directories correctly.
After some investigation, it looks like this was due to `Config::get('statamic.stache.stores')` returning an empty array, so the base directory was `/collection-handle`.
I haven't been able to track down exactly _when_ this started happening. It might have had something to do with the config merging changes in Laravel 11 but surely we would have had reports way before now if that was the case? 🤔
Anyways, this pull request fixes it by getting the directories from the Stache store class.
Fixes #11087.
=> [5.x] Fix multisite command not moving directories

resources/js/components/fieldtypes/Fieldtype.vue, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
This PR adds the `store` and `storeName` to field action payloads, so it's easy to access other fields:
```js
Statamic.$fieldActions.add('text-fieldtype', {
title: 'Example',
run: ({ store, storeName }) => {
const values = store.state.publish[storeName].values;
// ...
},
});
```
The reason it's aliased in the fieldtype mixin is that calling it `storeName` seems to cause errors in some fieldtypes, like slug. It also has a default value because some fieldtypes are used outside of a publish form, like radio in the SaveButtonOptions component, where no store name is provided.
=> [5.x] Include store in field action payload

src/Fieldtypes/Arr.php, tests/Fieldtypes/ArrayTest.php
This pull request fixes an issue with Keyed Array fields, where `null` values were being saved, instead of being filtered out, like they should be.
Fixes #11074.
Caused by #10467.
=> [5.x] Filter out empty values in keyed array field

src/StarterKits/Installer.php, tests/StarterKits/InstallTest.php
This PR adds a `default` config, to help with module installation flow when spamming the enter key, or when running non-interactively. More specifically...
- `default: true` will ensure it gets installed when spamming enter or running non-interactively
- `prompt: false` will skip the confirmation prompt altogether, forcing the module to be installed
- this is current behaviour, [as documented here](https://statamic.dev/starter-kits/creating-a-starter-kit#skipping-confirmation) for organizational purposes
- `default: antlers` will ensure the `antlers` modules gets installed when spamming enter or running non-interactively
- `skip_option: false` will disable the option to skip the prompt altogether
- if runing interactively, this forces the user to select an option
- if running …
=> [5.x] Add `default` config for select starter kit modules

src/Fields/Value.php, tests/Fields/ValueTest.php, tests/Tags/IterateTest.php
This replaces #10958.
This fixes an issue where you could not use the `foreach` tag to loop over a `group` fieldtype.
The underlying issue is that when you have a `Value` instance that evaluates to a `Values` instance (which is what the `group` fieldtype does), it wasn't properly iterable. `getIterator` expects a `Traversable` to be returned.
In the included test, the last dataset (value with values) is the one that would fail, and is fixed by this PR.
=> [5.x] Allow Values object and Group fieldtype to be iterated

src/Data/DataCollection.php
Fixes $searchQuery->orderBy().
The method_exists check a couple lines later doesn't pass anymore since we refactored to search `Result` classes.
Ideally this should be fixed with some sort of new interface, but this couple line fix was an easy win.
Fixes #11200
=> [5.x] Fix search query orderBy

src/Listeners/Concerns/GetsItemsContainingData.php
This PR updates the logic in the `GetsItemsContainingData` trait to return the global set localizations `values()` rather than a keyed collection. 
Without this change it was only returning one variables for each localization, as the flatMap was using the localization's key.
Closes https://github.com/statamic/cms/issues/11177
=> [5.x] Ensure updating references gets all global variables

src/Console/Commands/StaticWarm.php, tests/Console/Commands/StaticWarmTest.php
This adds an `--eco` option to the static warm command. In eco mode, only uncached URLs are visited. 
This is perfect for when you just want to 'fill in the gaps' in your cache after some URLs were invalidated, without visiting every single URL in your website. This avoids unnecessary server load.
Using this option will definitely lower your carbon footprint :innocent:
=> [5.x] Add an `--uncached` option to the static warm command

src/Console/Commands/FlatCamp.php, src/Console/Commands/StaticClear.php, tests/Console/PleaseTest.php
Currently, when you run `php please static:clear` with static caching disabled, it won't do anything but it'll say the static cache has been cleared, which is misleading if you've just disabled static caching, but still have files in `public/static` since you'll continue to be served the cached pages.
This pull request mirrors the `php please static:warm` command by showing a warning if you try to run the command while static caching is disabled.
=> [5.x] Throw an error when running `static:clear` when static caching is disabled

src/Providers/RouteServiceProvider.php, tests/API/APITest.php
This pull request fixes an error with the REST API when the CP route is empty, where attempting to view a single entry or term would result in an error.
This was happening because the `needsEntryBinding`/`needsTermBinding` methods were under the impression it was a CP route so they were enabling the CP route bindings, causing errors in our API controllers. 
Fixes #10842.
=> [5.x] Fix REST API errors when CP route is empty

src/Fieldtypes/Bard/LinkMark.php
Goes along with statamic/cms#11206
=> [5.x] Fix wrong url on the link mark node in bard fieldtype

src/Http/Requests/FrontendFormRequest.php
Alternative to #11194
Fixes #11179
=> [5.x] Fix localized error messages on forms when previous URL is incorrect

src/Providers/ExtensionServiceProvider.php
In the current version of Statamic the App extensions - such as custom Modifiers, Scopes, Tags, Fieldtypes etc. - only auto register if they are directly in their respective folders but not if they are in a subfolder.
e.g.
app/scope/MyScope.php               will register
app/scope/order/MyScope2.php   will not register.
For order/organisational purposes this change would be preferred.
This PR doesn’t solve the Problem that two classes with the same Name in different namespaces receive the same handle and therefore overwrite each other but since that problem already exists between plugins and the handle can be customized with “protected static $handle” I wasn’t sure this problem needed solving.
Targets branch 5.x
Tests:  I didn't find any test for the Serviceprovider and don't know the …
=> [5.x] Register App extensions also for Classes in Subfolders

src/Stache/Indexes/Index.php, tests/Data/Entries/EntryTest.php, tests/Stache/WorkerInfiniteLoopTest.php
This PR fixes an issue where stache indexing can cause an infinite loop when being executed by a worker. The new test `infinite_loops_are_prevented_when_running_workers` can be used to verify the issue in the `5.x` branch.
This was also addressed as part of https://github.com/statamic/cms/pull/10574 but that PR is yet to be reviewed and merged.
Fixes #11187.
=> [5.x] Fixed an issue where stache indexing can cause an infinite loop for workers

src/Console/Commands/Concerns/MigratesLegacyStarterKitConfig.php, src/Console/Commands/StarterKitExport.php, src/Console/Commands/StarterKitInit.php, src/Console/Commands/StarterKitInstall.php, src/Console/Commands/stubs/starter-kits/ServiceProvider.php.stub, src/Console/Commands/stubs/starter-kits/composer.json.stub, src/Providers/ConsoleServiceProvider.php, tests/StarterKits/InitTest.php
In #11119, we're removing scaffolding logic from `starter-kit:export`, in order to simplify the export.
This PR implements a complimentary `starter-kit:init` command to re-implement that scaffolding logic, but with better UX.
=> [5.x] Add new `starter-kit:init` command

src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Runtime/TemplateTest.php
This PR fixes #11218  by adding `no_results` to the automatic array variables that are added when looping.
The issue is ultimately caused by the cascading logic. Tags that output `no_results: true` don't output `no_results: false`, which causes Antlers to search until it finds a variable with the same name.
=> [5.x] Adds "no_results" to automatic array variables

resources/js/components/assets/Uploader.vue
The folder upload feature from #10583 has a little flaw: while dropping a bunch of files has always uploaded the files in sequence, dropping a folder will upload all contained files at once. With lots of nested files, this might overwhelm the server and lead to corrupted uploads.
This PR fixes that by only ever allowing a single concurrent upload.
I can imagine this being a config flag to allow e.g. 3 or 5 concurrent uploads if the system can handle it.
**Before**
**After**
=> [5.x] Fix asset upload concurrency on folder upload

src/Entries/Entry.php
We are using a custom title_format in an entry collection that relies on translations. Unfortunately, when saving an entry, Statamic appears to set `app()->locale()` to the full site locale (e.g., `de_DE`), while Laravel expects the "short" locale or language (e.g., `de`). As a result, the translation is not found, and the fallback translation is used instead.
I traced this issue to the [following line](https://github.com/statamic/cms/blob/d62cc13484aa28ec532f814669630f8c5c4a3915/src/Entries/Entry.php#L1011). Is there a specific reason for using `$this->withLocale($this->site()->locale(), ...)` instead of `$this->withLocale($site->lang(), ...)`? Using `$site->lang()` resolves the issue for us.
Could this be adjusted, or do you have any other suggestions for solving this issue?
I noticed …
=> [5.x] Fix collection title_format when using translations

resources/js/components/fieldtypes/bard/BardFieldtype.vue
Bard's view source button doesn't show when you have the toolbar set to floating.
It's also fairly useless in our opinion since it's not a true representation of the final html. Plus, it's not editable, and many people think it is.
We'll remove it completely in v6, but for now it's being moved into the field actions dropdown. This makes it usable regardless of your toolbar setting.
Resolves https://github.com/statamic/cms/discussions/11226
Related: #11227
=> [5.x] Move bard source button into field actions

resources/lang/en/fieldtypes.php, src/Fieldtypes/Table.php
This pull request adds "Max Columns" and "Max Rows" config options to the Table fieldtype. They're already used in the fieldtype's Vue component, they were just missing options in the UI.
Closes statamic/ideas#1276.
=> [5.x] Table Fieldtype: Add `max_columns` and `max_rows` options

src/Console/Commands/StaticWarm.php, tests/Console/Commands/StaticWarmTest.php
This PR adds some options to the static warm command  to limit the number of requests. It creates more control over what is warmed and what not. Great for when you just want to warm some important pages, in a CPU-friendly way.
**--include**
Takes a comma-separated list. For example `--include='/about,/contact,/blog/*'`
**--exclude**
Takes a comma-separated list. For example `--exclude='/contact,/news/*'`
**--max-depth**
For example with `--max-depth=1` it will visit pages like `/about` and `/products` but not `/products/cool-new-shoes-1` or `/any/other/path/that/is/too/deep`
=> [5.x] Add some options to the static warm command to limit the number of requests

resources/js/components/fieldtypes/assets/AssetRow.vue, resources/js/components/fieldtypes/assets/AssetTile.vue
This pull request prevents the "Set Alt" button from running the Replace Asset action prematurely. Without explicitly setting the `type` attribute on buttons, it'll automatically submit the `<form>` it's located in, which was the issue here.
Fixes #11260.
=> [5.x] Prevent "Set Alt" button from running Replace Asset action prematurely

src/Query/Scopes/Filters/Fields/Terms.php
This pull request fixes an issue when filtering by term fields on the entry listing, where if the selected term's slug is *part* of the slug of another term, the wrong results might have been returned.
For example: if you were filtering by a term with the slug of `ev`, it would query for entries where the term slug contained `ev`, meaning entries associated with other terms like `beverages` could be returned.
This PR addresses the issue by replacing the `like` condition with `->whereJsonContains()` which seems to return the correct results.
Fixes #11262.
=> [5.x] Fix term filter on entries listing

src/Modifiers/CoreModifiers.php, tests/Modifiers/EmbedUrlTest.php, tests/Modifiers/TrackableEmbedUrlTest.php
Youtube can attach new parameters when copying URLs, such as:
https://www.youtube.com/watch?v=xose4ruJXQ0&pp=ygUQaGFkZXN0b3duIGxvbmRvbg%3D%3D
The `embed_url` and `trackable_embed_url` modifiers were incorrectly outputting the URL:
https://www.youtube-nocookie.com/embed/xose4ruJXQ0&pp=ygUQaGFkZXN0b3duIGxvbmRvbg%3D%3D 
This is not a valid URL, and will not play. It is missing the query string question mark.
However, the Video fieldtype does correctly embed the video - so the author would believe the video would embed correctly.
This PR updates these two modifiers to check that if an ampersand exists in the URL (i.e. there is more than one query string property) then there is also a question mark.
With this PR in place, the embedded URL will be: …
=> [5.x] Update `embed_url` and `trackable_embed_url` modifiers to be valid with additional query strings

resources/js/components/structures/PageEditor.vue, src/Http/Controllers/CP/Navigation/NavigationTreeController.php
This pull request fixes an issue where hidden fields on nav pages were being persisted, even when `always_save` was `false`.
This was addressed in #5101 for the other publish forms (entries / terms / etc), so I've just implemented the `HasHiddenFields` mixin introduced in that PR.
Fixes #11249.
=> [5.x] Handle hidden fields on nav page edit form

src/StarterKits/Installer.php
If github oauth fails, then this error output never shows, because `removeStarterKit()` ends up erroring.
This PR just moves error output to the start of `rollbackWithError()`, to ensure it always outputs nicely, no matter what.
For example, https://github.com/studio1902/statamic-peak/issues/408 had an installation issue related to github oauth, but this wasn't obvious. Now the user should see this...
```
Composer could not authenticate with GitHub!
Please generate a personal access token at: https://github.com/settings/tokens/new
```
=> [5.x] Improve starter kit installer error handling

src/Providers/AddonServiceProvider.php
Fixes #11277
Caused by #11128
Related: https://github.com/studio1902/statamic-peak/issues/408
Root level items weren't being loaded on addons on Windows due to the directory check added in #11128.
The directory separators were different. e.g. It was comparing `C:\foo\bar` and `C:/foo/bar`.
This PR uses `Path::tidy()` to normalize the slashes in the reflected path. The `$addon->directory()` and `->autoload()` methods are already normalized.
=> [5.x] Fix autoload error on Windows

src/Providers/AddonServiceProvider.php, src/Providers/AppServiceProvider.php
Some addon's tests started failing due to the static property usage introduced in #11128.
The `shouldBootRootItems` would return false when it checked if the addon was already booted on subsequent tests, since within a test suite static properties stick around.
Technically you'd see the same issue in the browser if you were using Octane. For regular browser usage, there was no issue.
This PR fixes it by using collections resolved out of the container. They get shared across addons, but only for that lifecycle.
=> [5.x] Fix static properties in addon providers

src/Http/Controllers/CP/Assets/ThumbnailController.php
This pull request fixes an issue with the placeholder thumbnail images displayed when an image's dimentions are larger than the configured limits.
The `ThumbnailController` was redirecting to a file that doesn't exist in the `public/vendor/statamic/cp` directory. 
This file used to exist when we were using Laravel Mix, but when we switched to Vite in 4.0 (), the `dist.tar.zip` files we ship with Statamic releases stopped including SVGs.
This PR fixes the issue by returning the contents of the SVG directly from our controller, rather than redirecting to another URL.
Fixes #11228.
=> [5.x] Fix CP thumbnail placeholder

resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue, resources/js/components/inputs/relationship/CreateButton.vue, resources/js/components/inputs/relationship/InlinePublishForm.vue, resources/js/components/inputs/relationship/Item.vue, resources/js/components/inputs/relationship/RelationshipInput.vue, src/Fieldtypes/Relationship.php
This pull request adds a `$formStackSize` property to the `Relationship` fieldtype class, allowing developers to customize the size of the stack the inline publish form gets rendered in.
The property accepts three values: `narrow`, `half` and `full`.
```php
protected $formStackSize = 'narrow';
```
In my Simple Commerce addon, I have a relationship fieldtype with a single field. It doesn't make sense to take up 3/4ths of the screen with a stack with one input, so it would be nice to use the `narrow` option in this case.
=> [5.x] Add formStackSize option for inline publish form stacks

src/Console/Commands/StaticWarm.php, tests/Console/Commands/StaticWarmTest.php
Still working on keeping the static cache warm and the CPU cool.
This one adds a `--max-requests` option.  It limits the number of requests. Probably makes most sense in combination with the `--uncached` option. 
Using this option, you can warm the cache in smaller batches.
=> [5.x] Add `--max-requests` option to the static warm command

src/Console/Commands/StaticWarm.php, src/Console/Commands/StaticWarmUncachedJob.php, tests/Console/Commands/StaticWarmTest.php, tests/Console/Commands/StaticWarmUncachedJobTest.php
When using both the `--queue` and `--uncached` parameters:
By the time a queued job gets executed, the page was possibly already cached in the meantime. The dedicated `StaticWarmUncachedJob` checks again if the page is cached, and if so, it won't send the request.
=> [5.x] Static warm: recheck whether page is cached for queued requests

src/Providers/AddonServiceProvider.php, src/Providers/AppServiceProvider.php
Fixes #11284
Service providers that come before `statamic` alphabetically were trying to access a binding that wasn't bound yet, which caused the error.
This PR changes to methods that will lazily bind the collections.
=> [5.x] Fix addon service provider autoloading

resources/js/components/entries/PublishActions.vue
When firing an exception in a EntrySaving event (to create a toast) I noticed that PublishActions don't handle response the same way as PublishForms.
This PR brings the code inline - literally copy/pasting.
Guided by @duncanmcclean
=> [5.x] Improve error handling when using entry publish actions

src/Auth/File/User.php, tests/Auth/FileUserTest.php, tests/Auth/PermissibleContractTests.php
This pull request fixes an issue where it was possible to end up with duplicate roles/groups on flat-file users. It doesn't look like this issue affects database-driven users.
Fixes #11256.
=> [5.x] Prevent duplicate roles & groups

resources/views/extend/forms/fields.antlers.html, src/Forms/FieldsVariable.php, src/Forms/Tags.php, tests/Tags/Form/FormCreateTest.php
Currently in a `form:create` tag pair, you can loop over the `fields` to output predefined html for each field. However, you still have to add the label, instructions, errors, etc.
This PR allows you to use the `fields` var as a single tag and it will output an entire view for you.
```diff
-{{ fields }}
-  <div>
-    <label>{{ display }}</label>
-    {{ field }}
-  </div>
-{{ /fields }}
+{{ fields /}}
```
The view has basic tailwind based markup, just like the individual fields already do. You may override this view in the same way too by adding `resources/views/vendor/statamic/forms/fields.antlers.html`.
The view was already in the codebase but never used. Maybe the intention was to do exactly this but it never happened. This PR also tweaks the view a little sto improve padding and to …
=> [5.x] Allow form fields view to be rendered with single tag

tests/Markdown/MarkdownTest.php
Recently a change to the commonmark package causes a test failure due to removal of newlines. 
https://github.com/thephpleague/commonmark/releases/tag/2.6.1
This PR adjusts the test to remove newlines from the assertion. They don't matter.
=> [5.x] Fix markdown test

resources/js/components/fieldtypes/replicator/AddSetButton.vue
Minor UX improvement: Add new sets by clicking on the set button label – not only the plus button itself.
Doesn't need any docs I think.
=> [5.x] Make set button label clickable

src/Http/Controllers/GlideController.php, src/Imaging/GlideUrlBuilder.php, src/Imaging/ImageGenerator.php, src/Support/Str.php, tests/Imaging/GlideUrlBuilderTest.php
This PR implements the two custom implementations (mentioned [here](https://github.com/statamic/cms/issues/11176#issuecomment-2503190882)) for `base64_encode` and `base64_decode` in Glide. Sometimes the internal `base64_encode` produced URLs with undesired slashes, which then broke the routing for Glide.
Fixes: https://github.com/statamic/cms/issues/11176
=> [5.x] Add url friendly base64 en-/decoding for Glide

src/Fieldtypes/Assets/Assets.php
We are getting a ton of `Call to a member function path() on null` and it's coming from this code in `Assets.php`:
```
public function process($data)
{
$max_files = (int) $this->config('max_files');
$values = collect($data)->map(function ($id) {
return Asset::find($id)->path();
});
```
I'd like to know which asset is causing the issue, so let's throw a better exception.
=> [5.x] Throw better exception when asset isn't found

src/Fieldtypes/Bard/LinkMark.php
This PR fixes an `Undefined property: stdClass::$href` error when a bard link mark has no `href` attribute defined.
This can only occur if you've manually imported content and missed the `href`, but there's already a null check in place it so doesn't hurt to make it a little more forgiving.
=> [5.x] Fix bard undefined href error

src/ErrorSolutions/SolutionProviders/OAuthDisabled.php, src/ErrorSolutions/SolutionProviders/UsingOldClass.php, src/ErrorSolutions/Solutions/EnableComposerUpdateScripts.php, src/ErrorSolutions/Solutions/EnableOAuth.php, src/ErrorSolutions/Solutions/EnableStatamicPro.php, src/ErrorSolutions/Solutions/UpdateClassReference.php, src/ErrorSolutions/Value.php, src/Exceptions/ComposerJsonMissingPreUpdateCmdException.php, src/Exceptions/StatamicProRequiredException.php, src/Providers/IgnitionServiceProvider.php
This pull request renames the `Statamic\Ignition` namespace to `Statamic\ErrorSolutions`, as suggested in #11073.
=> [6.x] Rename Statamic\Ignition namespace to Statamic\ErrorSolutions

src/Contracts/Assets/AssetContainer.php
The `validationRules` method was added in #10227, however, we couldn't add it to the contract in that PR as it would have introduced a breaking change.
=> [6.x] Uncomment `validationRules` method in AssetContainer contract

CONTRIBUTING.md
This pull request fixes the bug report link in our Contribution Guide, as it allowed you to bypass our bug report issue template.
=> [5.x] Fix bug report link in Contribution Guide

resources/css/elements/buttons.css, resources/css/elements/forms.css, resources/css/vendors/vue-select.css
Seems like Safari 18.2 has issues when there is a background gradient in combination with borders. Full colored backgrounds work perfectly well as you can see in the picture below.
We can fix that by applying `background-clip: padding-box;` to the UI elements. I did that for the ones I noticed while browsing the cp.
Fixes: #11287
=> [5.x] Fix UI bugs in Safari 18.2

src/Providers/ExtensionServiceProvider.php
When deploying on Vercel I'm running into an issue with the addon cache not being writeable as its hard coded to boostrap/cache/addons.php
```
Exception:
The /var/task/user/bootstrap/cache directory must be present and writable.
at /var/task/user/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php:178
at Illuminate\Foundation\PackageManifest->write(array('statamic-rad-pack/shopify' => array('id' => 'statamic-rad-pack/shopify', 'slug' => null, 'editions' => array(), 'marketplaceId' => null, 'marketplaceSlug' => null, 'marketplaceUrl' => null, 'marketplaceSellerSlug' => null, 'latestVersion' => null, 'version' => '2.0.0-beta1', 'namespace' => 'StatamicRadPack\\Shopify', 'autoload' => 'src', 'provider' => 'StatamicRadPack\\Shopify\\ServiceProvider', 'name' => 'Shopify', …
```
=> [5.x] Allow addons cache path to be set by an environment variable

src/Http/Controllers/CP/Collections/ExtractsFromEntryFields.php, src/Structures/Page.php
This PR relates to #11080 
Sometimes it would be helpful to conditionally render a field when the page is part of a structure and has / has not children.
```
if:
children: 'not empty'
```
Or even something like this:
```
if:
children: 'contains c534de98-24c8-479b-b1a0-0e8945b76020'
```
By the way, this PR started with the need for a `has-children` field condition. But I switched to `children` because I think it's a bit more flexible.
=> [5.x] Page children as value for field conditions

src/Search/Comb/Comb.php, tests/Search/CombTest.php
This pull request fixes an error in the Comb search.
The search normally operates case insensitive. To ensure that this also works with UTF-8 characters (e.g. german umlauts), the regex patterns require the "u" modifier:
https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php
We had this problem with a german website. Lets say there is the word “Ökoland” indexed. A search for “Öko” returns the correct result. But a search for “öko” (lowercase) does not. This has now been resolved with the modifier.
=> [5.x] Fix case insensitive Comb search for UTF-8 characters

src/Fieldtypes/UserGroups.php
This pull request fixes an issue where the group name wasn't translatable in the user groups fieldtype.
=> [5.x] User Groups Fieldtype: Group name should be translatable

src/Data/DataCollection.php
This pull request fixes an issue when attempting to order search results by an origin value. 
Instead of calling `->get()` on the `$item`, it'll call the `->value()` method if it exists allowing it to fallback to the origin value if it's not set on the localized item. 
Fixes #11314.
=> [5.x] Fixed ordering search results by origin value

src/Query/Scopes/Filters/Fields/Bard.php, src/Query/Scopes/Filters/Fields/Grid.php, src/Query/Scopes/Filters/Fields/Replicator.php
This PR adds empty and not empty filter options for the replicator, bard and grid fieldtypes:
**Edit:**
I was about to add this to bard as well, and do another copy-paste, and then I realised these could just be added to textarea class that these three were already extending since it would work for text as well. But then I wasn't really sure if replicator extending textarea really makes sense in the first place? What do you think? Should they all use some kind of generic base class or just stick with textarea?
=> [5.x] Add empty/not empty filters for replicator, bard and grid

src/Stache/Repositories/TermRepository.php, tests/Data/Taxonomies/ViewsTest.php
This fixes an issue where if you visited `/term-url/any/number/of/segments` it would act like you're on `/term-url`. It should 404.
=> [5.x] Fix additional url segments matching taxonomy terms

resources/lang/en/dictionary-countries.php
This pull request fixes an issue with the name of "Curaçao" in the countries dictionary. Not sure how, but looks like the special character messed things up.
Replaces #11393.
=> [5.x] Fix "Curaçao" item in countries dictionary

resources/js/components/live-preview/LivePreview.vue
Right now, in Live Preview, the "Responsive" option is always the first and default option.
However, if most of your users are viewing your articles on mobile, you might want to change the order of the options so "Mobile" is at the top:
This pull request allows you to do that. Simply add a `Responsive` device to the `live-preview.devices` config option, and it'll work.
```diff
'devices' => [
'Laptop' => ['width' => 1440, 'height' => 900],
'Tablet' => ['width' => 1024, 'height' => 786],
'Mobile' => ['width' => 375, 'height' => 812],
+       'Responsive' => [],
],
```
The Live Preview will also default to whatever the first option in the devices list is.
=> [5.x] Live Preview: Allow changing the position of "Responsive" device option

.git-blame-ignore-revs
This adds `.git-blame-ignore-revs` with the sha of the commit for #11416.
Any revisions listed in this file will be ignored in GitHub within blames.
GitHub will use this automatically. Locally, you can use this by running `git config blame.ignoreRevsFile .git-blame-ignore-revs` (once). Code editors will typically respect this in their diff UIs if you have added that config. 
It's nice to not see "Apply Prettier" in the blame within a billion files.
More info: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
=> [6.x] Add git-blame-ignore-revs

src/Console/Commands/InstallEloquentDriver.php
Adds `--repositories` option to `statamic:install:eloquent-driver` command, allowing targeted repository migration via comma-separated list.
Key improvements:
- Supports selective repository migration without manual selection
- Validates and normalizes repository names
- Provides warning for invalid repository inputs
- Maintains existing multiselect and --all functionality
Example usage:
```bash
php artisan statamic:install:eloquent-driver --repositories=assets,entries,forms
```
=> [5.x] Select specific repositories for Eloquent Driver install command

src/Data/DataReferenceUpdater.php, tests/Listeners/UpdateAssetReferencesTest.php
While working on the UTC update script in #11409, I realised that the `DataReferenceUpdater` doesn't support the Group fieldtype. This PR adds support for it.
=> [5.x] Support the Group fieldtype in DataReferenceUpdater

src/Exceptions/Concerns/RendersHttpExceptions.php
Upgrading from Statamic 4 and Laravel 10 to Statamic 5 and  Laravel 11 I wanted to migrate this custom exception handler:
```php
public function render($request, \Throwable $e)
{
if ($e instanceof NotFoundHttpException) {
$eventsMount = Collection::findByHandle('events')->mount();
if (Str::before($request->path(), '/') === $eventsMount->slug()) {
return response()->redirectTo($eventsMount->url());
}
}
return parent::render($request, $e);
}
```
Following Laravel's [documentation](https://laravel.com/docs/11.x/errors#rendering-exceptions) I couldn't understand why it didn't work, until I dived into the exception and saw it implements a `render` method which takes over.
This PR introduces a static callback you can use to implement your own handling:
```php …
```
=> [5.x] Allow custom render callback for overridden exceptions

.prettierignore, resources/js/tests/FieldConditionsConverter.test.js, resources/js/tests/FieldConditionsParentResolver.test.js, resources/js/tests/FieldConditionsValidator.test.js, resources/js/tests/Frontend/FieldConditionsTest.test.js, resources/js/tests/Globals.test.js, resources/js/tests/Hooks.test.js, resources/js/tests/NormalizeInputOptions.test.js, resources/js/tests/PublishValues.test.js, resources/js/tests/Slug.test.js
In #11428 I noticed Prettier wasn't kicking in for JS tests. That's because I unintentionally excluded them in #11415. Only PHP tests should be excluded.
The only real change in this PR is in `.prettierignore`. The rest are just formatting changes done by running `npm run prettier:format`.
=> [6.x] Prettier JS tests

tests/TestCase.php
We were intermittently seeing test errors related to sites, but only when running certain tests with no cache state. For example, this would fail...
```
rm -rf vendor
composer update
phpunit --filter SubstitutesEntryForLivePreviewTest
```
...but only on the first run. That test would pass on subsequent runs, or when running the whole suite, because sites state had been built up already.
The way our `Sites` class works, it caches `$sites` as a property cache, and has some fallback logic as well. We intentionally set up a default sites.yaml in our `TestCase` class, so we should just be making sure that also gets set on the `Sites` cache.
=> [5.x] Fix test state issues around sites cache

.gitignore, package-lock.json, package.json, vite.config.js
This will generate a `bundle-stats.html` file when running `npm run build` to allow us to inspect our JS bundle.
I've been doing some optimizations in a few branches and keep finding myself installing this.
=> [6.x] Add rollup bundle visualizer

resources/js/components/assets/Editor/Editor.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/globals/PublishForm.vue, resources/js/components/structures/PageEditor.vue, resources/js/components/terms/PublishForm.vue, resources/js/components/user-groups/PublishForm.vue, resources/js/components/users/PublishForm.vue
Components that use the HasHiddenFields mixin now need a `store` property that references the Pinia store since #11446 
This fixes an error when saving publish forms.
=> [6.x] Fix hidden fields mixin store reference

resources/css/components/fieldtypes/assets.css, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
This PR fixes an issue where the `AssetsFieldtype` does not show the upload controls when the field does not have enough space to be shown.
It does so by flex-wrapping the content of the `.assets-fieldtype .assets-fieldtype-picker` selector:
https://github.com/user-attachments/assets/16f72ef0-69cb-49e1-9c24-a3c48ad6ac93
It also removes the extra top margin in the asset upload control
Before:
After:
Fixes #11436
=> [5.x] Fix issue with AssetsFieldtype upload controls hidden on @sm size

resources/js/components/fieldtypes/assets/AssetRow.vue
This PR modifies the layout logic in the `AssetsFieldtype` to only reserve space for the "Set alt" button when it's actually needed.
Currently, when "showSetAlt" is set to true and there is an alt text, the space for the "Set alt" Button is reserved but not used, leading to a shorter file name place.
When the file needs an alt text:
When the file does not need an alt text:
_(notice how the file name is cropped even when there is a lot of white space)_
As shown in the last screenshot, when needsAlt = false, the file name now uses the full available width :
Also works for files that doesdo not need an alt text:
The text var could also be simplified, but not sure if that was done so for some magic purpose or not ;-) :
Old: `{{ asset.values.alt ? "✅" : __("Set Alt") }}`
New: `{{ __("Set Alt") …
=> [5.x] Fixes empty asset alt <td> element in AssetsFieldtype

src/Tags/GetContent.php, tests/Tags/GetContentTagTest.php
Use an `OrderedQueryBuilder` in the `get_content` tag to make sure the order of results matches the order of the entry IDs that were passed in. Currently, the order is arbitrary.
Since the `OrderedQueryBuilder` only supports sorting by `id`, we can't apply this when urls are passed in. Happy to also make the necessary adjustments to the query builder class if that's something you're willing to support.
=> [5.x] Ensure consistent order of `get_content` results

src/Search/Comb/Comb.php
As written in the issue #11398, there are problem with the search_snippets when two or more words are searched.
The search_snippets array is populated only when the item found contains both words (even if they aren't on the same line). However, if the search result contains only one of the searched words, the search_snippets array remains empty.
This happens using the the native local driver, not algolia.
Fixes #11398.
=> [5.x] Fix search results missing search_snippets

.github/workflows/release.yml, .github/workflows/tests.yml
GitHub are [removing the `ubuntu-20.04` image](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/) from GitHub Actions. This pull request updates our workflows to use `ubuntu-latest` instead.
=> [5.x] Use `ubuntu-latest` in GitHub Actions workflows

src/Listeners/Concerns/GetsItemsContainingData.php
This pull request makes some performance improvements to the `GetsItemsContainingData` trait, responsible for gathering all content items (all entries, terms, globals and users). 
It's currently used within the asset & term reference updaters, however, it'll soon be used in the UTC dates update script (#11409).
Essentially, instead of loading all items into memory at once (which will cause issues with larger sites), we'll use Laravel's [Lazy Collections](https://laravel.com/docs/master/collections#lazy-collections) feature to ensure items can be looped through in a more efficient manner.
=> [5.x] Improve performance of the data reference updaters

src/Console/Commands/Multisite.php
This pull request adds a hook to the `php please multisite` command, allowing addon developers to run their own code when a site is being converted from a single site to a multisite.
For example:
```php
// ServiceProvider.php
public function bootAddon()
{
Multisite::hook('after', function () {
// Maybe move some files around...
// Update a config file or two...
$this->components->info('Done some multisite magic!');
});
}
```
~I'm not totally sold on the name of the hook (`end`). I'm sure we can come up with a better name.~ Named it `after`.
=> [5.x] Add hook into the `multisite` command

src/Structures/TreeBuilder.php, tests/Tags/StructureTagTest.php
This fix is possibly a breaking change, let me know if you want it to retarget main.
If you pass an invalid entry to nav:from then it currently treats it as if you have not passed anything to from, which feels like incorrect behaviour. Instead it should return nothing.
Closes https://github.com/statamic/cms/issues/11392
=> [5.x] If nav:from references an invalid entry, ensure nothing is returned

src/Revisions/RevisionRepository.php, tests/Revisions/RepositoryTest.php
The stache revision repository whereKey method currently returns a FileCollection by nature of how the revisions are found, but doesn't seem to use any of the methods. When you call ->toArray() on this it errors out.
This PR updates the return to be a normal collection, which allows it to behave as you would expect.
Closes https://github.com/statamic/cms/issues/11454
=> [5.x] Change revision whereKey to return a collection

src/Auth/UserTags.php, tests/Tags/User/UserTagsTest.php
This PR adds support for passing additional arguments to gates via the `{{ user:can }}`/`{{ user:cant }}` tags.
```php
Gate::define('view secret', function ($user, $secret) {
return $user->hasAccessToSecret($secret);
});
```
```antlers
{{ user:can do="view secret" secret="foo" }}
...
{{ /user:can }}
```
=> [5.x] Support arguments in user can/cant tags

src/Fields/Value.php, tests/Fields/ValueTest.php
Tricky behavior ran into by Erin - https://discord.com/channels/489818810157891584/489830535565148169/1333967156861468694
This won't directly solve what he was dealing with (as he had a custom class), but it will fix it for future devs checking if a property on a Value is empty.
Currently, if you have an object wrapped by a Value and then check the emptiness of a property on that object it returns true no matter what:
This is due to https://www.php.net/manual/en/function.empty.php#99959
> Calling non existing object property, `empty($object->prop)`, will trigger `__isset()`, the same way as `isset($object->prop)` does, but there is one difference. If `__isset()` returns `TRUE`, another call to `__get()` will be made and actual return value will be result of `empty()` and result of …
=> [5.x] Fix emptiness check on Value properties

src/Query/Scopes/Filters/Fields/Date.php, src/Query/Scopes/Filters/Fields/Entries.php, src/Query/Scopes/Filters/Fields/FieldtypeFilter.php, src/Query/Scopes/Filters/Fields/Number.php, src/Query/Scopes/Filters/Fields/Template.php, src/Query/Scopes/Filters/Fields/Terms.php, src/Query/Scopes/Filters/Fields/Textarea.php, src/Query/Scopes/Filters/Fields/User.php
Follow up to https://github.com/statamic/cms/pull/11354
This PR adds empty/not empty field filter options for all other field types, except toggle because I don't think that can be empty?
=> [5.x] Add empty/not empty field filters

src/GraphQL/TypeRegistrar.php, src/GraphQL/Types/FormType.php, src/GraphQL/Types/SectionType.php, tests/Feature/GraphQL/FormTest.php
This PR adds support for sections in GraphQL queries:
```
query MyQuery {
form(handle: "test") {
title
rules
honeypot
handle
sections {
instructions
display
fields {
instructions
type
display
handle
config
width
}
}
}
}
```
Closes https://github.com/statamic/cms/issues/8482
=> [5.x] Support Sections in form GraphQL queries

resources/js/components/field-actions/DropdownActions.vue, resources/js/components/field-actions/FieldAction.js, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue, resources/js/components/fieldtypes/relationship/RelationshipFieldtype.vue
This PR adds an Unlink/Remove All action to relationship and assets fields:
It also adds a new `dangerous` property to field actions.
Closes https://github.com/statamic/ideas/issues/1313
=> [5.x] Add Unlink All action to relationship fields

src/Http/Controllers/FrontendController.php, tests/Routing/RoutesTest.php
This PR adds support for optional `$view` parameter closure with `Statamic::route()`, so that you can dynamically render a view from a route segment.
For example, this works fine in Laravel...
```php
Route::get('/components/{component}', function ($component) {
return view($component);
});
```
So this should work with Statamic routes as well...
```php
Route::statamic('/components/{component}', function ($component) {
return view($component);
});
```
This PR makes it work like this...
- This was already supported, but we just want to make sure we don't regress here
- This wouldn't make sense. If you're returning `view($template, $data)` in Laravel, it's expected you'll pass your dynamic data directly into that 👍
- https://github.com/statamic/docs/pull/1614
References …
=> [5.x] Add support for `$view` parameter closure with `Statamic::route()`

src/Http/Controllers/FrontendController.php, tests/Routing/RoutesTest.php
This PR fixes a small regression introduced by #11452, which was merged but not yet tagged.
=> [5.x] Fix primitive type hint handling in Statamic routes

src/Assets/AssetContainerContents.php, tests/Assets/AssetFolderTest.php
Currently the asset container contents are generated and cached in the default cache store, which means if you clear the application cache it needs to rebuilt.  When you are using a driver such as S3 this can be quite slow and resource intensive.
This PR provides the option to specify a `asset_container_contents` cache store, similar to the approach used in https://github.com/statamic/cms/pull/9405
=> [5.x] Allow custom asset container contents cache store

src/Tags/Concerns/GetsQueryResults.php, tests/Tags/Collection/EntriesTest.php
https://github.com/statamic/cms/pull/10415 introduced a check to ensure that paginate and limit aren't used at the same time. However due to the `has` check a `null` limit value will pass as true even though it wouldn't be applied.
This becomes a problem when trying to pass variables through to tags where limit or paginate might be used:
```antlers
{{ collection:articles :paginate="paginate" :limit="limit" }}
```
```php
Statamic::tag('collection:articles', [
'paginate' => $paginate,
'limit' => $limit,
]);
```
I know you could filter the array or maybe use `void` in antlers, but it would be nice if you didn't have to worry about it. In this example there are conditions further up that ensure only one of those variables would be set.
The PR changes the check to use `int` so that a null …
=> [5.x] Fix cannot use paginate/limit error when one is null

src/Auth/CorePermissions.php, src/Auth/Permission.php, src/Fields/Blueprint.php, src/Fields/Field.php, src/Fields/Fieldtype.php, src/Fields/Tab.php
We were encountering an issue `placeholderLabel(): Argument #1 ($label) must be of type ?string, array given` that appeared when there is a localization file that is named like a global set. Similar issues can appear with fieldsets. They are related to the way laravel localization works when a translation file is named like a translation key, e.g. `__('search")` and `lang/en/search.php`. In this case the whole contents of a file are returned instead of a string.
The underlying issue was already encountered and had been fixed for some parts of statamic 4, so I applied the same fix to the relevant files. https://github.com/statamic/cms/pull/9525/files
=> [5.x] Fix issue with localization files named like handles

src/Assets/Attributes.php, tests/Assets/AttributesTest.php
This PR enables the correct output of video dimensions of videos that have rotated video streams. Currently, videos with rotated streams do not output proper dimensions, width and height are swapped.
Fixes #11480
=> [5.x] Fix handle dimensions of rotated videos

composer.json, src/Assets/Asset.php, src/Auth/File/User.php, src/Auth/Passwords/TokenRepository.php, src/Data/ExistsAsFile.php, src/Data/TracksLastModified.php, src/Entries/Entry.php, src/Forms/Submission.php, src/Http/Controllers/CP/SessionTimeoutController.php, src/Http/Middleware/Localize.php, src/Licensing/LicenseManager.php, src/Licensing/Outpost.php, src/Modifiers/CoreModifiers.php, src/Revisions/RevisionRepository.php, src/Stache/Stache.php, src/Support/FileCollection.php, src/Taxonomies/LocalizedTerm.php, src/Tokens/FileTokenRepository.php, tests/Assets/AssetTest.php, tests/Feature/Assets/StoreAssetTest.php, tests/Feature/Entries/EntryRevisionsTest.php, tests/Feature/Fieldtypes/FilesTest.php, tests/Feature/GraphQL/Fieldtypes/DateFieldtypeTest.php, tests/Modifiers/DaysAgoTest.php, tests/Modifiers/HoursAgoTest.php, tests/Modifiers/MinutesAgoTest.php, tests/Modifiers/MonthsAgoTest.php, tests/Modifiers/SecondsAgoTest.php, tests/Modifiers/WeeksAgoTest.php, tests/Modifiers/YearsAgoTest.php
This pull request adds support for Carbon 3, allowing us to support Laravel 12 when it's released.
While Statamic 5 is backwards compatible with Carbon 2, you might find that Carbon 3 is installed as a result of this update. If you'd rather stay with Carbon 2, you may require it using Composer:
```
composer require nesbot/carbon:^2
```
=> [5.x] Carbon 3

src/Console/Commands/InstallSsg.php
This pull request prevents the spatie/fork prompt from showing unless the required `pcntl` extension is available. 
Closes #11490.
=> [5.x] Only show spatie/fork prompt when pcntl extension is loaded

src/API/AbstractCacher.php, src/Git/Git.php, src/GraphQL/ResponseCache/DefaultCache.php, src/Http/Controllers/CP/SessionTimeoutController.php, src/Providers/CacheServiceProvider.php, src/StaticCaching/Cachers/AbstractCacher.php
If you use environment variables, they come through as strings. Carbon 2 didn't care and would deal with strings for you but Carbon 3 wants an integer.
Fixes #11492 which solves the API, but the same thing could happen in other places like the graphql api, static caching, etc.
=> [5.x] Fix carbon integer casting

src/Auth/Eloquent/RoleModel.php, src/Auth/Eloquent/UserGroupModel.php, src/StaticCaching/NoCache/DatabaseRegion.php
This pull request converts the `$casts` property on models to a method, now that Laravel 11 is the minimum version.
Related: https://github.com/statamic/eloquent-driver/pull/400
=> [6.x] Convert `$casts` property to method on Eloquent models

resources/lang/az.json, resources/lang/cs.json, resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/fa.json, resources/lang/fr.json, resources/lang/hu.json, translator
This pull request hopefully fixes #11489, where duplicate lines were added when running the `translator` command.
=> [5.x] Remove duplicate translation line from `translator` command

src/Tokens/Handlers/LivePreview.php, tests/Feature/Entries/AddsHeadersToLivePreviewTest.php
This fixes #11497 where Live Preview's Content Security Policy (CSP) does not include the port number in the frame-ancestors directive when determining allowed origins. 
This issue affects configurations where the control panel is served on a custom port (e.g., http://127.0.0.1:8000/ or http://localhost:8080/). Since CSP treats http://127.0.0.1/ and http://127.0.0.1:8000/ as distinct origins, the live preview fails to load within an iframe.
=> [5.x] Fix: Include port in CSP for Live Preview

composer.json, src/Http/Middleware/Localize.php, src/Modifiers/CoreModifiers.php, tests/Feature/GraphQL/Fieldtypes/DateFieldtypeTest.php, tests/Modifiers/DaysAgoTest.php, tests/Modifiers/HoursAgoTest.php, tests/Modifiers/MinutesAgoTest.php, tests/Modifiers/MonthsAgoTest.php, tests/Modifiers/SecondsAgoTest.php, tests/Modifiers/WeeksAgoTest.php
This pull request drops support for Carbon 2 in Statamic 6.
Carbon 3 introduced a change to the `->diffIn...()` methods, where they'll return floats instead of integers and past dates will return negative numbers.
This change will be reflected by Statamic's `months_ago`, `weeks_ago`, `days_ago`, `hours_ago`, `minutes_ago`, and `seconds_ago` modifiers
=> [6.x] Drop Carbon 2 support

resources/js/components/structures/Branch.vue
I must have broken it near the end of the Vue 3 PR. It works for the CP nav builder but not the collection or navigation UIs.
Turns this:
Back into this:
=> [6.x] Restore page tree branch styling

resources/js/components/entries/BaseCreateForm.vue, resources/js/components/entries/PublishForm.vue, resources/views/entries/create.blade.php, src/Entries/Collection.php, src/Http/Controllers/CP/Collections/EntriesController.php, src/Providers/ExtensionServiceProvider.php, src/Revisions/Revisable.php, src/UpdateScripts/RemoveParentField.php, tests/Feature/Entries/UpdateEntryTest.php, tests/UpdateScripts/RemoveParentFieldTest.php
This pull request removes the "Parent" field that Statamic adds to the blueprints of structured collections.
Most people use the tree view anyways, and the special parent field has been the cause of numerous bugs, so we've decided to get rid of it in Statamic 6.
=> [6.x] Remove "Parent" field from entries

resources/css/components/fieldtypes/bard.css
In dark mode, the active toolbar buttons of Bard are barely visible:
Compare that to light mode:
White text color for a nice "glowing" effect and less darker shade (600 instead of 800) for active buttons. For hover, I reduced that from 700 to 650 for a little more visibility, but not too much to steal the active button's show!
=> [5.x] Make active toolbar buttons of Bard more visible in dark mode

src/StarterKits/Exporter.php, tests/StarterKits/ExportTest.php
When running `starter-kit:export --clear`, the intention is to clear all previously exported files. We don't want to wipe their `.git` folder though, because that'll mess up their remotes, reflog, etc.
=> [5.x] Fix target `.git` repo handling when exporting starter kit with `--clear`

resources/lang/en/validation.php, src/Rules/Handle.php, tests/Rules/HandleTest.php
This pull request improves the validation message that gets thrown when a handle starts with a number, as the existing validation message only talks about the types of characters that can be used.
---
Related: #11503
=> [5.x] Improve validation message when handle starts with a number

resources/js/bootstrap/App.vue, resources/js/bootstrap/components.js, resources/js/bootstrap/fieldtypes.js, resources/js/bootstrap/statamic.js, resources/js/components/Echo.js, resources/js/components/Modal.vue, resources/js/components/Toasts.js, resources/js/components/collections/View.vue, resources/js/components/inputs/relationship/Selector.vue, resources/js/components/navigation/View.vue
- Making `NavBuilder` and `PageTree` async components allows `@he-tree/vue` to be code-split.
- Making `Modal` an async component and moving the css allows `vue-final-modal` to be split.
- Making the `TimeFieldtype` an async component allows `imask` to be split.
- Using dynamic imports in the `Toasts` class allows `@hoppscotch/vue-toasted` to be split.
- Using dynamic imports in the `Echo` class allows `laravel-echo` and `pusher` to be split.
The `$toast` API methods are now technically async. But you would never really chain methods, and having a slight delay in the toast appearing doesn't hurt anything.
Before this, the js file was `2,266.68 kB │ gzip: 607.05 kB`.
After these changes, the js file is `1,923.01 kB │ gzip: 509.28 kB`.
=> [6.x] More code splitting

src/Tags/Structure.php, tests/Tags/StructureTagTest.php
This PR adds support for `as` as a parameter on nav tags, so you can do things like
```
{{ nav:main as="navnav" }} 
{{ navnav | chunk(3) }}
chunk
{{ /navnav }}
{{ /nav:main }}
```
=> [5.x] Support `as` on nav tag

resources/js/components/fieldtypes/IconFieldtype.vue, routes/cp.php, src/Fieldtypes/Icon.php, src/Http/Controllers/CP/Fieldtypes/IconFieldtypeController.php
Fixes statamic/ideas#1310
As pointed out in the issue, the icon fieldtype would read all the svg files in the specified directory on the server and send it down in the metadata. It would do it for all icon fields even if they reuse the same icon directory. You end up with huge arrays being passed down as JSON, potentially multiple times, causing a large initial document size.
This PR avoids doing that work on the server. Instead, an AJAX request will be made to get the icons.
Additionally, if multiple fields configured with the same directory are on the page, only one request will be made. There are shared icon caches and loading states across the components.
It would be possible to make the requests happen only when interacting with the field for the first time, but that adds some …
=> [5.x] Icon fieldtype performance

src/Rules/AllowedFile.php
This PR updates the isAllowedExtension method in AllowedFile validation rule to handle a value that isn't an UploadedFile being passed to it.
I couldn't see where to put a test - happy to add one if you can point me in the right direction?
Closes https://github.com/statamic/cms/issues/11525
=> [5.x] Return validation error when AllowedFile is not an UploadedFile

resources/js/components/ElementContainer.vue, resources/js/components/GlobalSearch.vue, resources/js/components/data-list/FieldFilter.vue, resources/js/components/data-list/Search.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/fieldtypes/DictionaryFieldtype.vue, resources/js/components/fieldtypes/Fieldtype.vue, resources/js/components/fieldtypes/VideoFieldtype.vue, resources/js/components/fieldtypes/bard/BardFieldtype.vue, resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue, resources/js/components/globals/PublishForm.vue, resources/js/components/inputs/relationship/Selector.vue, resources/js/components/live-preview/LivePreview.vue, resources/js/components/publish/Container.vue, resources/js/components/slugs/Slug.js, resources/js/components/terms/PublishForm.vue, resources/js/components/user-groups/PublishForm.vue, resources/js/components/users/PublishForm.vue, resources/js/tests/FieldConditionsValidator.test.js, resources/js/tests/components/fieldtypes/TextFieldtype.test.js, resources/js/vite-plugin/index.js, vite.config.js
We were using `@` in parts of our JS as an alias to the root js directory to avoid needing relative paths.
This was fine in our own Vite build. However, when you are running Vite in an addon and you reference a Statamic file, the `@` will resolve to their own directory, not Statamic's. So we are using `@statamic` instead so `@` can remain appropriate for the user.
This introduces a second problem though: When an addon is using Vite, they won't have our `@statamic` alias defined so Vite will fail.
To address both these issues, I've included a Vite plugin that addons can reference. Now we can ask developers to use our plugin (similar to the Laravel plugin) and we will wire up the ugly bits for them automatically.
```diff
// vite.config.js
import { defineConfig } from 'vite';
import laravel …
```
=> [6.x] Add vite plugin and adjust aliases

resources/js/components/GlobalSiteSelector.vue, resources/js/components/SiteSelector.vue
This pull request fixes two-way bindings in the `GlobalSiteSelector` and `SiteSelector` components.
=> [6.x] Fix two-way bindings in site selector components

src/Auth/Protect/Protectors/Password/PasswordProtector.php, tests/Auth/Protect/PasswordProtectionTest.php
This pull request fixes an issue with password protection on 404 pages, where errors were occuring due to the URL having no "data".
Fixes #11541.
=> [5.x] Fix password protection on 404 pages

resources/js/components/blueprints/Section.vue, resources/js/components/blueprints/Tab.vue, resources/js/components/fieldtypes/IconFieldtype.vue, resources/js/components/publish/FieldMeta.vue
Fixes #11558, caused by #11523
Only the directory was being included in the cache keys. It wasn't taking into account the folder if provided.
Additionally, the icon fieldtypes used in the replicator section/tab editors weren't passing in the config which is needed to make the correct ajax request.
=> [5.x] Fix icon fieldtype

src/Fieldtypes/Date.php
Fixes #11553
This is already fixed in v6 but this backports it.
Context:
```
try {
return Carbon::createFromFormat($this->saveFormat(), $value);
} catch (InvalidFormatException|InvalidArgumentException $e) {
return Carbon::parse($value);
}
```
Sometimes `$value` is already a `Carbon` instance.
When you pass a Carbon instance to `createFromFormat`, you get an `InvalidFormatException`.
The `catch` will catch it, and pass the Carbon instance into `parse`, which just returns the instance back and logs the deprecation warning. We can avoid all that by just returning a Carbon instance early.
=> [5.x] Fix carbon deprecation warning

src/Forms/Submission.php, src/Http/Resources/CP/Submissions/ListedSubmission.php, tests/Forms/SubmissionTest.php
Form submission dates should also be UTC as per #11409
It also changes the id generation from `microtime` to Carbon so it can be tested. It's the exact same functionality though.
=> [6.x] UTC form submission dates 

tests/StaticCaching/InvalidateTest.php
=> [6.x] Fix invalidate test

resources/js/tests/components/fieldtypes/DateFieldtype.test.js, resources/js/tests/components/fieldtypes/DateIndexFieldtype.test.js
This adjusts the JS tests added in #11409 to test across multiple timezones.
The test uses date/times that would cause the day to change when converting from UTC to New York.
=> [6.x] Improve date timezone tests

src/Exceptions/ControlPanelExceptionHandler.php, src/Fieldtypes/Entries.php, src/Fieldtypes/Terms.php, src/Fieldtypes/UserGroups.php, src/Fieldtypes/UserRoles.php, src/Forms/Email.php, src/Forms/Exporters/Exporter.php, src/Forms/Fieldtype.php, src/Http/Controllers/CP/Collections/CollectionsController.php, src/Http/Controllers/CP/Forms/FormsController.php, src/Http/Controllers/CP/Preferences/Nav/RoleNavController.php, src/Http/Controllers/CP/Taxonomies/TaxonomiesController.php, src/Http/Controllers/CP/Users/RolesController.php, src/Query/Scopes/Filters/Fields.php, src/Query/Scopes/Filters/Site.php, src/Taxonomies/Taxonomy.php
- Fix #11577
- Applies the same fix from #11422 in more places
- Use the internal translation helper to avoid exceptions if translation keys return arrays
- Applicable if a blueprint/collection/taxonomy has the same title as an existing translation file
=> [5.x] Fix control panel crashes when titles share name with existing translation file

src/Auth/Eloquent/User.php
This pull request fixes an issue where the "Send Password Reset" action wasn't using the custom notification defined in the `User` model, whereas it would get used by the CP's forgot password feature.
Fixes #11554.
=> [5.x] Password reset action should use custom password reset notification 

resources/js/components/DateTime.vue
You don't need to import `defineProps`. You get this warning from Vite:
```
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
```
=> [6.x] Prevent defineProps import warning

src/Fields/Fieldtype.php, src/Fields/FieldtypeRepository.php, tests/Fields/FieldtypeRepositoryTest.php, tests/Fields/FieldtypeTest.php
Sometimes it might be necessary to disable certain fieldtypes for frontend forms - per discord conversion with Marco - https://discord.com/channels/489818810157891584/489818810157891586/1349028284142194699
This PR adds a new method to accomplish that on the FieldtypeRepository and Fieldtype classes: makeUnselectableInForms()
=> [5.x] Enable unselecting fieldtypes for forms

src/GraphQL/Types/NavPageInterface.php
This isn't the best fix, but when a nav blueprint has no fields defined it should return something to prevent the GraphQL schema erroring out.
I chose something unlikely (_) as the name, but maybe you have a better suggestion?
Closes https://github.com/statamic/cms/issues/10621
=> [5.x] When NavPageInterface has no blueprint fields return something

src/Mixins/Router.php, tests/Routing/RoutesTest.php
This pull request fixes an error when using implied route views, like this:
```php
Route::statamic('my-page'); // Implies 'my-page'
```
The error was happening because the provided `$view` was a `Stringable` object, rather than an actual string. I've replaced `Str::of(...)->ltrim(...)` with a simple `ltrim`. 
Fixes #11568.
=> [5.x] Fix implied route views

src/Data/StoresComputedFieldCallbacks.php, src/Data/StoresScopedComputedFieldCallbacks.php, src/Facades/Collection.php, src/Facades/User.php, tests/Auth/UserContractTests.php, tests/Data/Entries/EntryTest.php, tests/Data/StoresComputedFieldCallbacksTest.php, tests/Data/StoresScopedComputedFieldCallbacksTest.php
We have a number of computed properties for a specific collection and our AppServiceProvider is getting rather long with all the computed properties.
This PR helps solve this by allowing for an associative array to be passed as the 2nd parameter:
```php
Collection::computed('properties', [
'pdf_url' => fn ($entry, $value) => route('properties.pdf', $entry->id()),
'deletion_date' => fn ($entry, $value) => $this->generateDeletionDate($entry),
]);
```
Let me know if you'd like me to add tests
=> [5.x] Allow passing computed fields via an associative array

src/Assets/Asset.php, tests/Assets/AssetTest.php
Following on from https://github.com/statamic/cms/pull/11481 it might make sense to allow meta to also have its own cache store, so it doesn't need to get purged on every cache clear?
This is all coming from a discord conversation by the way - https://discord.com/channels/489818810157891584/1342431350145290251
=> [5.x] Allow a custom asset meta cache store to be specified

resources/js/components/assets/Editor/Editor.vue, resources/js/components/publish/Container.vue, resources/js/stores/publish-container.js
This pull request fixes an issue I spotted where state (specifically field values) was being persisted across assets. I assume this has something to do with the migration to Pinia.
To workaround this, I've made the publish container name unique, like we do for inline publish forms.
I've also fixed a typo in the `publish-container.js` file.
=> [6.x] Fix asset publish forms

src/Search/Commands/Update.php
*Note: This only applies if you have more than one index defined.*
When adding the `statamic:search:update` command to the Laravel scheduler, if you don't also explicitly define the indexes to update (e.g. with `--all`) like so:
```
Schedule::command('statamic:search:update')->daily();
```
Then the scheduler will throw the following error upon running this command:
```
In Update.php line 28: Call to a member function update() on null
```
With this error it's a bit cryptic to figure out what went wrong.
I've made this change based on my own assumption that scheduling the command like this, without an option, should by default run it as if it were run with `--all` (this is the default selected option after all when you manually run it).
=> [5.x] Change default value of update command selection

src/Auth/Eloquent/User.php, tests/Auth/Eloquent/EloquentUserTest.php
This PR updates eloquent-driven users to ensure any NULL values are not saved, bringing it inline with the same behaviour as file-driven users.
Related: https://github.com/statamic/eloquent-driver/pull/412
Closes: https://github.com/statamic/cms/issues/5977
=> [5.x] Prevent null data from being saved to eloquent users

src/Tags/Structure.php
You can add `include_parents="false"` to a `nav` tag to prevent `parent` keys being added.
Fixes #11595
=> [5.x] Ability to exclude parents from nav tag

config/revisions.php
It always frustrates me that revisions are in storage not content. Ideally I'd like the default to be changed but realise thats breaking.
As a move in the right direction, can the revisions path be .env configurable so at least we can change it on our installs more easily?
Please 🙏
=> [5.x] Allow revisions path to be configurable with an .env

resources/js/components/assets/Uploader.vue
As asset uploading isn't handled by axios, it doesn't run through the interceptor that renders the toasts.
This PR adds the same logic to the Uploader component.
Closes https://github.com/statamic/cms/issues/10626
=> [5.x] Ensure toasts fired in an AssetUploaded event are delivered to front end

src/Entries/Collection.php, src/Extend/HasTitle.php, src/Git/CommitCommand.php, src/Http/Controllers/CP/Auth/LoginController.php, src/Http/Controllers/CP/Fields/FieldsController.php, src/Http/Controllers/CP/Fields/FieldsetController.php
Another PR related to translation keys, I’ve already fixed this issue here https://github.com/statamic/cms/pull/11482 and have identified a few more places when testing fieldsets where it could also break.
=> [5.x] Fix issue with localication files named like fieldset handles

src/Providers/AddonServiceProvider.php
This pull request adds the `Query/Scopes` and `Query/Scopes/Filters` directories to the paths Statamic uses to autoload query scopes in addons.
The `php please make:scope` command creates query scopes & filters in the `src/Scopes` directory.
However, if you're following the same directory structure of Statamic Core in your addon, your scopes/filters might live in different folders. Here's an example from my addon:
=> [5.x] Autoload scopes from `Query/Scopes` and `Query/Scopes/Filters`

src/Modifiers/CoreModifiers.php, tests/Modifiers/FirstTest.php
Today I tried to grab the first item from a collection of assets in Antleres but the `first` modifier returned me a string. After a quick sanity check with Duncan, I propose the modifier should handle collection instances the same way it does with arrays.
=> [5.x] Handle collection instances in `first` modifier

package-lock.json, resources/js/components/collections/View.vue, resources/js/components/fieldtypes/ArrayFieldtype.vue, resources/js/components/fieldtypes/grid/Grid.vue, resources/js/components/fieldtypes/replicator/ManagesPreviewText.js, resources/js/components/fieldtypes/replicator/SetPicker.vue, resources/js/components/inputs/relationship/Selector.vue, resources/js/components/navigation/View.vue, resources/js/components/publish/Container.vue, resources/js/components/structures/PageEditor.vue, resources/js/components/structures/PageTree.vue
- Fixes replicator and bard
- Fixes infinite loop when using an array fieldtype
- Fix array fieldtype error due to v-if and v-for being on the same element.
- Fix grid row not getting correct values
- Fix dirty state warning showing almost everywhere
- Fix auto-selection in the relationship stack when max selections is 1.
- Fix page selection and editing in nav tree
- Fix auto-open page editor (when theres a required field) immediately closing.
- Fix warnings in nav page editor
- Run npm audit fix to get rid of js vulnerabilities
=> [6.x] Misc fixes

src/Http/Controllers/CP/StartPageController.php
A user can add their own Startpage after logging into the control panel. This user generated content is not properly escaped before a redirect is triggered on logging in.
A user might be able to set their start_page Preference Value for example to "test\npage" (a string with Line Break). This is usually prevented on frontend but not validated/sanitized on backend!
Upon redirection there is a 500 error:  
> Header may not contain more than a single header, new line detected {"userId":1,"exception":"[object] (ErrorException(code: 0): Header may not contain more than a single header, new line detected at
This small fix url-encodes the user's Preference so that the Header redirect value is url-safe. 
_(resubmitted from personal GitHub Account)_
=> [5.x] Escape start_page Preference to avoid invalid Redirect

src/Console/Commands/AssetsGeneratePresets.php
It would be helpful to add an option to the statamic:assets:generate-presets command to exclude certain asset containers from preset generation.
In our case, we had an asset container for storing assets uploaded through our forms. However, running this command generated presets for these assets, which was not desirable.
This PR is related to [Issue #1644](https://github.com/statamic/docs/issues/1644).
=> [5.x] Added option to exclude asset containers from generating presets

src/API/FilterAuthorizer.php, src/API/QueryScopeAuthorizer.php, src/Http/Controllers/API/ApiController.php, src/Http/Controllers/API/AssetsController.php, src/Http/Controllers/API/CollectionEntriesController.php, src/Http/Controllers/API/CollectionTreeController.php, src/Http/Controllers/API/TaxonomyTermEntriesController.php, src/Http/Controllers/API/TaxonomyTermsController.php, src/Http/Controllers/API/UsersController.php, tests/API/APITest.php
This PR adds support for using query scopes in the REST API.
The URL format follows the same approach as filters:
`https://mysite.com/api/collections/pages/entries?query_scope[my_scope]=value`
or, if you have multiple values
`https://mysite.com/api/collections/pages/entries?query_scope[my_scope][value_key]=value&query_scope[my_scope][another_value_key]=value2`
I've made a few changes to FilterAuthorizer to allow it to be easily extended by the new QueryScopeAuthorizer, seeing as they are basically doing the same thing with just a difference in the key being checked.
Closes https://github.com/statamic/cms/issues/3310
=> [5.x] Support query scopes in REST API

resources/js/components/fieldtypes/replicator/Replicator.vue
This PR fixes https://github.com/statamic/cms/issues/11619
Instead of a shallow copy, a deep copy of the (default) values is used when adding or duplicating an item in the replicator-set.
Unfortunately I do not know how to test this in an automated way.
When using statamic from [this](https://github.com/faltjo/statamic-cms/tree/fix-replicator-set-bug) branch, the problems are gone in the example repo: https://github.com/faltjo/replicator-set-bug
=> [5.x] Use deep copy of objects in replicator set

resources/js/components/entries/BaseCreateForm.vue, resources/js/components/terms/BaseCreateForm.vue, resources/views/entries/create.blade.php, resources/views/terms/create.blade.php, src/Http/Controllers/CP/Collections/EntriesController.php, src/Http/Controllers/CP/Taxonomies/TermsController.php
You can already jump to the blueprint to make changes from entry/term edit publish forms, this PR adds the same links to the create forms.
=> [5.x] Add Edit Blueprint links to create publish forms

.github/workflows/tests.yml
On `5.x`, the Windows tests are running against both Laravel 10 and 11:
https://github.com/statamic/cms/blob/8d477deaea868b7bf3c7ea0dbe95cb8acfa8e842/.github/workflows/tests.yml#L23-L31
However, right now on `master`, we're only running Windows tests against Laravel 11. This pull request adds Laravel 12 to the matrix. It also adjusts the PHP version they're run on to PHP 8.4.
=> [6.x] Run Windows tests against Laravel 12

src/Actions/DuplicateEntry.php, src/Entries/Entry.php
This pull request fixes an issue when duplicating entries in a multi-site where dates would be set on duplicated localizations, even though a date wasn't explicitly set on the localization it's duplicating.
Since #10282 was merged, `Entry::date()` falls back to the origin's date if the entry doesn't have its own date. 
However, this causes an issue when duplicating because it means all localizations will have an _explicit_ date set when they should be falling back to the origin's date, like the original entries do.
Fixes #11360.
=> [5.x] Fix dates in localizations when duplicating entries

composer.json, config/assets.php, src/Imaging/GlideManager.php, src/Imaging/ImageValidator.php, src/Providers/GlideServiceProvider.php, tests/Assets/AssetTest.php, tests/Imaging/ImageValidatorTest.php
This pull request updates Statamic to use the recently released [Glide 3](https://github.com/thephpleague/glide/releases/tag/3.0.0).
This PR also refactors our image file extension check, by checking against the image manipulation driver (GD / Imagick) instead of a static array of file extensions.
=> [6.x] Glide 3

resources/js/components/assets/Uploader.vue
Fixes #11641 by accounting for empty json responses after asset uploads. This restores error messages when uploading files that are larger than allowed by the server.
=> [5.x] Restore error message on asset upload server errors

src/Http/Controllers/CP/StartPageController.php, tests/CP/StartPageTest.php
This pull request reverts #11616, as it seems to have caused an issue with some folks who use slashes in their start page URLs, which is pretty common.
I've reverted the escaping introduced in #11616, and added some additional tests.
Fixes #11649.
=> [5.x] Revert "Escape start_page Preference to avoid invalid Redirect"

src/Facades/AssetContainer.php
This pull request fixes the `@see` docblock on the `AssetContainer` facade.
=> [5.x] Fix docblock in AssetContainer facade

resources/js/components/nav/ItemEditor.vue
This pull request fixes an issue with the icon field in the CP Nav Customizer. 
In #11618, a new `config` slot was made available from the `PublishFieldMeta` component. However, `config` is also a data property on the `ItemEditor` component, so when the icon was updated, the wrong bit of state was getting changed, causing things to break.
Fixes #11623.
=> [5.x] Fix icon selector in nav builder

src/Tags/Concerns/RendersForms.php, tests/Tags/Form/FormCreateAlpineTest.php, tests/Tags/Form/FormCreateCustomDriverTest.php, tests/Tags/Form/FormTestCase.php
Missed this in https://github.com/statamic/cms/pull/10976.
This PR allows you to use `{{ ... }}` braces around `show_field` in blade, [as documented](https://github.com/statamic/docs/pull/1606).
=> [6.x] Fix `show_field` escaping when using `form:create` and `form:fields` tags in blade

src/Listeners/UpdateAssetReferences.php
This pull request ensures that references to assets in content are updated correctly, fixing an issue where only the first instance of an asset was being updated.
This was caused by the introduction of returning `LazyCollections` from `->getItemsContainingData()` in #11442. It seems like `->map()` wasn't getting further than the first instance, whereas `->each()` works as expected.
Fixes #11662 
Fixes #11690
=> [5.x] Ensure asset references are updated correctly

src/Http/Controllers/CP/CpController.php
I stumbled across these methods the other day, which seem to be leftover from v2 when we had the concepts of themes and templates.
We don't seem to be using them anywhere, and I'm not sure if they even work, so it should be pretty safe to remove them.
=> [5.x] Remove `templates`/`themes` methods from `CpController`

src/Query/Builder.php, src/Query/EloquentQueryBuilder.php, tests/Data/Entries/EntryQueryBuilderTest.php
This pull request fixes an issue where the `->chunk()` method on our query builder ignores any user-defined limits and offsets.
This meant that the following query would give you 10 chunks of 5 entries, rather than 2 chunks of 5 entries:
```php
use Statamic\Facades\Entry;
Entry::query()
->where('collection', 'playground')
->limit(10)
->chunk(5, function ($entries) {
dump($entries);
});
```
This was [fixed in Laravel 12](https://github.com/laravel/framework/pull/52093), so I've copied over the fix (and the related test cases) in this PR. The Laravel PR has more context around the issue, and the fix.
Since this introduces a change in behaviour, this pull request is targeting the `master` branch.
Fixes #11698.
=> [6.x] Fix chunked queries not honoring user-defined limits and offsets

resources/views/widgets/collection.blade.php
Fix exceptions in case a string is translated that also exists as a translation file. Same as #11422 and #11578 but for the `collection` cp widget.
=> [5.x] Handle translation issues in collection widget

src/Fieldtypes/Date.php, tests/Fieldtypes/DateTest.php
fix https://github.com/statamic/cms/issues/11659
=> [5.x] Fix validation of date field nested in a replicator 

config/live_preview.php, src/Http/Responses/DataResponse.php
Force reloading JS modules in Live Preview seems to break Vue hydration when using async components, resulting in a blank website (in Live Preview), or hydration errors in the console.
This was introduced a few years ago, here: https://github.com/statamic/cms/pull/3524
This PR makes "Force Reload JS Modules in Live Preview" optional.
=> [5.x] Make Live Preview force reload JS modules optional

src/Tags/ParentTags.php
This PR addresses a 500 error that can be created if the tag is called on an entry without a parent. It also fixes the return type in a PHPDoc comment later in the tag class that is used by the function I edited as it expects an array (and the function clearly returns an array, not a string).
Original error:
```
Call to a member function value() on null
```
=> [5.x] Safer check on parent tag

config/static_caching.php, src/Console/Commands/NocacheMigration.php, src/Console/Commands/stubs/statamic_nocache_tables.php.stub, src/StaticCaching/NoCache/DatabaseRegion.php
Users cannot specify a separate database connection for the nocache_regions table without modifying Statamic core code. Sometimes, this table can get really big and you may not want to include it on frequent backups. You may also want to move this table specifically closer to the Statamic install to reduce latency.
This PR adds a configuration option to allow specifying a different database connection for the `nocache_regions` table.
This change is fully backward compatible as it defaults to the current behavior (using the default database connection) when no configuration is provided.
```php
// In .env file
STATAMIC_NOCACHE_DB_CONNECTION=nocache
// Or in config/statamic/static_caching.php
'nocache_db_connection' => 'nocache',
// In config/database.php
'nocache' => [
'driver' => 'mysql', …
```
=> [5.x] Allow custom nocache db connection

src/Http/Controllers/CP/Forms/FormsController.php
This pull request fixes an issue with appended form config fields when the user's locale differs from the application's locale.
For example: if you append fields to the existing "Fields" section, and a user is viewing the Control Panel in German, your appended fields would show but the existing fields wouldn't. 
```php
\Statamic\Facades\Form::appendConfigFields('*', 'Fields', [
'a' => ['type' => 'text', 'display' => 'First injected into fields section'],
'b' => ['type' => 'text', 'display' => 'Second injected into fields section'],
]);
```
This pull request fixes it by translating the section's `display` in the fields merging logic.
Fixes #11672.
=> [5.x] Fix appended form config fields when user locale differs from app locale

package-lock.json
Whenever we run `npm run dev`, we get the following warning:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
This PR is the result of running that command.
=> [5.x] Update caniuse-lite

src/StaticCaching/DefaultInvalidator.php, tests/StaticCaching/DefaultInvalidatorTest.php
This pull request fixes [failing tests](https://github.com/statamic/cms/actions/runs/14603158271) in the `DefaultInvalidator` test after `5.x` was merged into `master` yesterday.
=> [6.x] Fix `DefaultInvalidatorTest`

src/StaticCaching/Cachers/FileCacher.php
This improves compatibility with frameworks like Vue where Html gets replaced once it has booted.
Why do we need this?
When placing the nocache tag within Vue's scope (usually id="app") our nocache tags aren't actually being replaced anymore.
Why does this happen?
Vue Replaces the html with it's computed html from the virtualdom when booting.
This means the references to the elements we've saved are stale.
Now we update our mapping after the fetch has completed so we can correctly replace our data
=> [5.x] Update nocache map on response

src/Forms/Tags.php, src/Tags/Concerns/RendersForms.php, tests/Tags/Form/FormCreateTest.php
Adds support for `get`, `only`, and `except` params to `form:fields` tag.
This allows the dev to lean on all the nice dynamic form rendering stuff provided by the `form:create` tag, but gives them more control over pulling out specific fields form custom column-based layouts, etc.
References: https://github.com/statamic/docs/pull/1606
=> [6.x] Add `get`, `only`, and `except` params to `form:fields` tag

tests/Sites/SitesTest.php
This pull request ensures the role created in [`SitesTest@gets_authorized_sites`](https://github.com/statamic/cms/blob/573d366fe749ea1f6b847f1aafcbe1883d04e255/tests/Sites/SitesTest.php#L52) is cleaned up after running, to prevent it leaking into other tests.
Discovered while looking into failing tests in #11664.
=> [5.x] Cleanup roles after running `SitesTest@gets_authorized_sites`

src/Fieldtypes/Floatval.php, tests/Feature/GraphQL/Fieldtypes/FloatvalFieldtypeTest.php
If you have a Float field type in your blueprint and return values in GraphQL they currently come back as strings. They should really be floats as thats what the field type is there for.
=> [5.x] GraphQL should return float fieldtype values as floats

resources/js/components/users/ChangePassword.vue, resources/js/components/users/PublishForm.vue
The change password button at the top of the user publish form isn't visible since the Vue 3 upgrade. This fixes it.
=> [6.x] Fix change password popover

src/Http/Controllers/CP/Auth/LoginController.php, src/Http/Controllers/OAuthController.php, tests/Auth/ElevatedSessionTest.php
If you log in then immediately go and do something that requires an elevated session, it will still prompt you for your password.
This PR will elevate your session on initial login. You've just entered your password.
=> [6.x] Elevate session on login

resources/js/components/inputs/relationship/RelationshipInput.vue, src/Fieldtypes/Terms.php, src/Fieldtypes/Users.php, src/Http/Resources/CP/Entries/EntriesFieldtypeEntry.php
This pull request fixes an issue where the "Edit" button (and the edit link) would show on relationship fieldtypes, even when the logged in user is missing the relevant permissions.
Fixes #11718.
=> [5.x] Hide "Edit" button on relationship fieldtypes when user is missing permissions

src/Fieldtypes/Entries.php
Currently, when you view an entry where the first configured collection has been deleted, you'll get a `Call to a member function entryBlueprint() on null` error.
Unless you look at the code, the cause of this error isn't immediately obvious, so this PR ensures that a `CollectionNotFoundException` is thrown the collection can't be found.
Related: #11753
=> [5.x] Improve error handling in entries fieldtype

resources/js/components/fieldtypes/bard/BardFieldtype.vue
This PR fixes #11765
Instead of a shallow copy, a deep copy of the (default) values is used when adding or duplicating set defined for a bard field.
When using statamic from [this](https://github.com/faltjo/statamic-cms/tree/fix-bard-set-replicator-bug) branch, the problems are gone in the example repo: https://github.com/faltjo/fix-bard-field-set-bug
Note that this is very similar to https://github.com/statamic/cms/pull/11621
=> [5.x] Use deep copy of set's data in bard field

resources/js/components/fieldtypes/grid/ManagesRowMeta.js, resources/js/components/fieldtypes/replicator/ManagesPreviewText.js, resources/js/components/fieldtypes/replicator/ManagesSetMeta.js, resources/js/components/fieldtypes/replicator/Replicator.vue, resources/js/components/publish/Container.vue
In one of the 6.x changes (either upgrading to Vue 3, or switching to Pinia) when you try to add a new set to a Replicator, it wouldn't update the meta data and caused an error. This seemed to be because the preview text was updating within the meta at around the same moment. This is fixed by making the previews and the row's meta get updated in the same call.
---
Also, the set's previews were displaying incorrectly due to the following change in #11610. 
```diff
-const previews = this.previews.filter((value, handle) => {
+const previews = Object.entries(this.previews).filter(([handle, value]) => {
```
They were showing the handles and incorrect values. Now they just show correct values again.
---
Finally, there were some reactivity issues around meta data. For example, the initial …
=> [6.x] Fix some reactivity issues

src/Http/Controllers/CP/Taxonomies/TermsController.php
This pull request fixes an issue when creating terms when the taxonomy's default/first site is different from Statamic's default/first site.
Fixes #11733.
=> [5.x] Fix creating terms in non-default sites

src/Data/ContainsData.php
This pull request adds `increment` and `decrement` methods to the `ContainsData` trait, which is used pretty much everywhere.
So, instead of needing to do this:
```php
$entry->set('inventory', $entry->get('inventory') + 1);
```
You can now do this:
```php
$entry->increment('inventory');
```
Not related to an existing feature request, but something I thought might be useful last night while working on a personal project.
=> [5.x] Add `increment`/`decrement` methods to `ContainsData`

src/Assets/Asset.php, src/Auth/File/User.php, src/Auth/UserGroup.php, src/Entries/Entry.php, src/Forms/Form.php, src/Forms/Submission.php, src/Globals/Variables.php, src/Taxonomies/LocalizedTerm.php, src/Taxonomies/Term.php, tests/Assets/AssetTest.php, tests/Auth/FileUserTest.php, tests/Auth/UserGroupTest.php, tests/Data/Entries/EntryTest.php, tests/Data/Globals/VariablesTest.php, tests/Data/Taxonomies/TermTest.php, tests/Forms/FormTest.php, tests/Forms/SubmissionTest.php
The classes that use `ContainsData` and `ContainsSupplementalData` store their data as collection objects not plain arrays. Because of this when you clone an entry object the clone still points to the same `data` collection object, so if you set something on the clone it also gets set on the original (same for supplemental data).
This PR fixes that by cloning the internal data collections when the main objects are cloned.
It also clones the user group `roles`, and the localised term `term` (as that's required to clone the term `data`).
It also adds a couple of missing `$this->supplements = collect();` constructor lines.
=> [5.x] Clone internal data collections

src/Fieldtypes/Group.php
Null values should no longer be saved to content, but the group fieldtype is doing that.
This PR fixes it.
=> [5.x] Fix filtering group fieldtype null values

src/Fieldtypes/Assets/DimensionsRule.php, src/Fieldtypes/Assets/ImageRule.php, src/Fieldtypes/Assets/MimesRule.php, src/Fieldtypes/Assets/MimetypesRule.php, src/Fieldtypes/Assets/SizeBasedRule.php, src/GraphQL/Types/FormType.php, tests/Feature/GraphQL/FormTest.php
This PR ensures that the custom asset validation rules provided to GraphQL are returned as strings. Currently as they are class based they are returned as '{}'.
Closes https://github.com/statamic/cms/issues/7986
=> [5.x] Ensure asset validation rules are returned as strings to GraphQL

src/Console/Commands/StaticWarm.php, tests/Console/Commands/StaticWarmTest.php
This PR introduces a new `--headers` option to the `static:warm` command, allowing users to specify custom HTTP headers for requests made during cache warming, e.g. for:
- Pages requiring authentication or API tokens for access.
- Need to trigger static cache refreshes even when static files are being served, using custom server rules. Especially useful for zero-cache-downtime scenarios
Related docs here: https://github.com/statamic/docs/pull/1674
=> [5.x] Add --header option to static warm command

src/Query/EloquentQueryBuilder.php
This pull request partially fixes statamic/eloquent-driver#424, by ensuring that the value and operator are handled properly before being passed to the Eloquent Query Builder.
Currently, when you're storing entries in the database, attempting to query a column with a value matching an operator will result in an error:
```php
Entry::query()->where('site', 'is')->get();
```
```
InvalidArgumentException 
Illegal operator and value combination. 
at vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:945
```
The query works as expected when querying the model directly, or when using the Stache query builder. `is` simply becomes the value when a third argument hasn't been provided.
This fix goes alongside ... which adjusts how the `EloquentQueryBuilder::where()` method is called.
=> [5.x] Prepare value & operator before passing to Eloquent Query Builder

src/Assets/Asset.php, tests/Assets/AssetTest.php
This pull request adds a `moveQuietly` method to the `Asset` class, allowing developers to move assets without the unnecessary overhead of events.
Useful when moving assets on mass, where you don't want to update search indexes or clear the Glide cache when each asset is moved.
=> [5.x] Add `moveQuietly` method to `Asset` class

src/Facades/Blink.php, src/Facades/Blueprint.php, src/Facades/Collection.php, src/Facades/Entry.php, src/Facades/Fieldset.php, src/Facades/Form.php, src/Facades/FormSubmission.php, src/Facades/GlobalSet.php, src/Facades/GlobalVariables.php, src/Facades/Revision.php, src/Facades/Role.php, src/Facades/Search.php, src/Facades/StaticCache.php, src/Facades/Structure.php, src/Facades/Taxonomy.php, src/Facades/Term.php, src/Facades/User.php, src/Facades/UserGroup.php
Hi. Laravel Idea plugin for PhpStorm uses `@see` phpDocs for facades to determine the classes hidden under this facade. And many `@see` tags in your facades create some issues(https://github.com/laravel-idea/plugin/issues/1195), so I propose to change `@see` to `@link` for classes that are not under this facade, but just linked to the logic.
=> [5.x] Fix facade PhpDocs for better understanding by Laravel Idea

src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Runtime/PhpEnabledTest.php
This PR fixes #11222 by allowing developers to override any variable when using the `{{? ... ?}}` or `{{$ $}}` PHP tags. With the changes in this PR, the following will now be possible without having to explicitly assign the variable first:
```antlers
{{?
// This will now update $theVariableName without an explicit assignment.
array_unshift($theVariableName, 'The Value');
?}}
{{ theVariableName}} ... {{ /theVariableName }}
```
While this is technically a bug fix, I am targeting `6.x`+ as it is a significant behavior change that could impact existing projects.
=> [6.x] Allow PHP Tags in Antlers to Override any Variable

src/View/Antlers/Language/Runtime/GlobalRuntimeState.php, src/View/Antlers/Language/Runtime/NodeProcessor.php, tests/Antlers/Runtime/PhpEnabledTest.php
This PR corrects a null-reference error that can occur when PHP is disabled within user-supplied content. Currently, it will throw an exception related to an invalid property reference, instead of logging the error as intended.
=> [5.x] Corrects Antlers error logging with PHP nodes

src/Forms/DeleteTemporaryAttachments.php, tests/Forms/SendEmailsTest.php
This PR fixes an issue where submissions are being saved, even though the storing of them has been disabled. This only occurres when the form has a files field in it and happens when sending out the form emails.
fixes #10987
=> [5.x] Fix storing submissions of forms with 'files' fieldtypes even when disabled

src/Http/Controllers/CP/Users/UsersController.php
This pull request hides fields marked as "read only" and "computed" from the user creation wizard, as they're pretty useless.
=> [5.x] Hide read only and computed fields in user creation wizard

src/Fieldtypes/HasSelectOptions.php
Following on from https://github.com/statamic/cms/issues/11333 and the related PR https://github.com/statamic-rad-pack/runway/pull/654 this fix ensures that the `HasSelectOptions` field type trait correctly casts pre-processed values to an array even if they are collections.
This addresses issues caused both when extending a select fieldtype to utilise collections and issues caused by Runway changes where collection values are no longer being cast to arrays.
Fixes https://github.com/statamic/cms/issues/11333
Replaces https://github.com/statamic-rad-pack/runway/pull/654
=> [5.x] Fix values being wrapped in arrays causing multiple selected options 

src/StaticCaching/Middleware/Cache.php
We do not have a way to determine ourselves if something should be skipped or not.
One option would have been to add `X-Statamic-Draft` to the headers, but this seemed "dirty". A new header allows us to skip the cache conditionally: `X-Statamic-No-Static-Cache` and would work well for others as well - it's clear, to-the-point, and distinct.
Our use case: we do NOT want to cache 404 responses in some instances - so we want to add that header where applicable.
Considered also `X-Statamic-Skip-Static-Cache`, but opted for shorter version with "No" instead of "Skip". Also considered `X-Statamic-No-Cache`, but thought that might be confused with Nocache (a separate implementation).
=> [5.x] Static Cache Middleware - skip cache if new header is set

src/Fieldtypes/Entries.php
Right now, the "Allow Creating" option is only used in the stack selector mode, since you can't create options in the select/typeahead modes.
To avoid confusion, this pull request will hide the option in the blueprint builder _unless_ the stack selector mode is configured.
Closes #11789.
=> [5.x] Entries fieldtype: Only show "Allow Creating" option when using stack selector

resources/js/components/SessionExpiry.vue, resources/js/components/actions/ConfirmableAction.vue, resources/js/components/assets/Upload.vue, resources/js/components/collections/DeleteEntryConfirmation.vue, resources/js/components/collections/DeleteLocalizationConfirmation.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/field-actions/FieldActionModal.vue, resources/js/components/modals/ConfirmationModal.vue, resources/js/components/modals/ElevatedSessionModal.vue, resources/js/components/modals/KeyboardShortcutsModal.vue, resources/js/components/navigation/RemovePageConfirmation.vue, resources/js/components/two-factor/RecoveryCodesModal.vue, resources/js/components/two-factor/Setup.vue, resources/js/components/two-factor/TwoFactor.vue, resources/js/components/ui/Modal/Modal.vue, resources/js/components/ui/index.js
This pull request updates modals across our application to use the new `<Modal>` UI component.
In the process, I've also converted buttons/inputs/selects/etc in modals to use UI new versions of those components.
This PR also makes some changes to how a modal's open state is controlled.
Previously, modals would open after the user clicked the "trigger". This meant that there wasn't any way to open a modal programatically, or prevent it from closing (in the case of an in-progress AJAX request).
While the modal's open state can still be handled by the model itself, it can now also be opened & closed using `v-model` bindings:
```vue
<Modal>
<template #trigger>
<Button text="Open the modal" />
</template>
<p>...</p>
</Modal>
<script setup>
const modalOpen = ref(true);
function …
```
=> [6.x] Modals

src/Fields/Fieldset.php, tests/Fields/FieldsetTest.php
This pull request adds a `hasField` method to the `Fieldset` class, mirroring the `Blueprint@hasField` method. 
I was working with fieldsets earlier and I tried to call `->hasField()` only to realise that method currently only exists on the `Blueprint` class.
=> [5.x] Add `hasField` method to `Fieldset`

src/Entries/Entry.php, tests/Data/Entries/EntryTest.php
When using saveQuietly() and the automatically propagate entries setting in on a collection, the new entries are currently save()-d (loudly).
This PR ensures the save method used respects the one used on the initial entry.
=> [5.x] Ensure propagating entries respects saveQuietly

src/Providers/ViewServiceProvider.php, src/View/Blade/Concerns/CompilesNavs.php, tests/View/Blade/AntlersComponents/NavCompilerTest.php
This PR fixes #11806.
The current implementation of the `nav` compiler will create a temporary file and include that behind the scenes, which worked in supporting recursive children. However, this causes issues when importing classes or functions, as this information would be lost inside the hidden temporary file.
Additionally, because the current implementation triggers a Blade compilating in creating that temporary file, it can mess with the internal raw block state, causing placeholder strings like `@__raw_block_1__@` to appear in the output.
This PR addresses both issues by refactoring away the temporary file, and instead inlines the compiled navigation code in a function. Recursive navigation support is maintained by simply calling that compiled function instead of including a hidden …
=> [5.x] Fix issues with Blade nav tag compiler

src/Http/Controllers/CP/Users/UsersController.php
I noticed that the `user_roles` and `user_groups` fields in the user blueprint aren't displayed as `read_only` even if a user doesn't have the `assign roles` and `assign user groups` permissions. This PR fixes that. It's only a UI fix, as the `UsersController` already guards the fields from being updated without the appropriate permissions.
**Before:**
**After:**
I actually went a step further and decided to hide the fields instead of making them read-only. I think this is more appropriate. Users without permission to change their role and group shouldn't be able to see those fields at all. It's just confusing.
=> [5.x] Fix read-only state of roles and groups fields

src/View/Antlers/Language/Parser/ComponentCompiler.php, src/View/Antlers/Language/Runtime/RuntimeParser.php, tests/Antlers/Parser/ComponentTagsTest.php
This PR adds Antlers Component Tag syntax support to Antlers, allowing for templates like:
```antlers
<s:collection:pages>
{{ title }}
</s:collection:pages>
```
With params:
```antlers
<s:collection:pages as="pages">
{{ pages }}
{{ title }}
{{ /pages }}
</s:collection:pages>
```
This syntax is similar to what is already supported by the Blade integration, with the exception that parameters/attributes dynamic variables, syntax, etc. follows the _Antlers_ rules instead of Blade's. Docs PR to come! :)
=> [6.x] Adds Component Tag Syntax Support to Antlers

src/Data/HasOrigin.php, src/Exceptions/RecursiveAugmentationException.php, tests/Data/Entries/EntryTest.php
This PR adds recursive augmentation detection. The current scope of this detection is Entries, but will apply to anything that utilizes `HasOrigin`.
This recursive behavior can be re-created when attempting to reference augmented values within computed callbacks (see #11853). This PR does not fix the underlying issue here, but makes it easier to detect and debug.
=> [5.x] Detect recursion when augmenting Entries

src/Fields/Blueprint.php, tests/Fields/BlueprintTest.php
This PR fixes an oversight exposed by https://github.com/statamic/cms/pull/11867.
If you try to `ensureFieldHasConfig()` on a previously ensured field, that field's config is stored in a different place in the Blueprint object (ie. `$this->ensuredFields` instead of `$this->contents`), therefore the config needs to be updated accordingly.
This is causing some newer tests on our `master` branch to fail, which is how I found the issue.
=> [6.x] Fix ensure field has config

resources/css/elements/buttons.css, resources/js/components/entries/PublishForm.vue, resources/js/components/terms/PublishForm.vue
Overriding the browser's internal `min-width` for buttons, allowing them to shrink.
Fixes https://github.com/statamic/cms/issues/11847
=> [5.x] Fix Overflow buttons preview

src/Auth/Eloquent/UserGroup.php
When using a fresh Statamic installation configured with Eloquent for user management in a Laravel >=11 environment, an exception "DB class not found" is thrown after creating a user group. It appears this issue can be resolved by explicitly importing the DB facade via a use Illuminate\Support\Facades\DB; statement.
=> [5.x] Class "DB" not found issue

resources/js/components/actions/ConfirmableAction.vue, resources/js/components/assets/Editor/Editor.vue, resources/js/components/entries/PublishForm.vue, resources/js/components/field-actions/FieldActionModal.vue, resources/js/components/field-conditions/ShowField.js, resources/js/components/fieldtypes/RevealerFieldtype.vue, resources/js/components/globals/PublishForm.vue, resources/js/components/preferences/EditForm.vue, resources/js/components/publish/HasHiddenFields.js, resources/js/components/sites/EditForm.vue, resources/js/components/terms/PublishForm.vue, resources/js/components/ui/Publish/Container.vue, resources/js/components/ui/Publish/Field.vue, resources/js/components/ui/Publish/Form.vue, resources/js/components/ui/Publish/SavePipeline.js, resources/js/components/ui/Publish/Sections.vue, resources/js/components/users/PublishForm.vue, resources/js/stores/publish-container.js
- PublishContainer's Pinia store calculates the visibleFields.
- PublishContainer's `values` prop is changed to `modelValue` so you can do `v-model="values"`.
- The visible values should have been getting submitted to the server, but weren't. The nicest way we found to do that while avoiding two v-models was for the `Request` pipeline step to automatically grab the visibleValues from the store. The pipeline step now just accepts _extra_ data.
- Fix showField logic. In v5 it expected the dottedKey to only be passed when nested. In v6 is was always being passed. It makes sense for it to always be passed, so add some logic to only do the needed thing if the key had a dot.
- Use visibleValues in showField logic. This fixed an issue where if had a conditional field based on another conditional …
=> [6.x] Publish form adjustments

src/Fieldtypes/Group.php
This pull request fixes an issue where the Group fieldtype was incorrectly filtering out `false` values. It should only be filtering out `null` values.
Fixes #11926
Caused by #11788
=> [5.x] Prevent group fieldtype from filtering out `false` values

src/Console/Commands/StarterKitInstall.php, src/Search/Null/NullSearchables.php, tests/StarterKits/InstallTest.php
If you copy new content into an site via the filesystem _after_ your search index has already been generated, new entries won't show up in the CP search results until you run `php please search:update`.
To help the user, this PR adds optional prompt to update search index(es) immediately after installing a starter kit:
=> [5.x] Prompt to update search indexes when installing starter kits

src/CP/Navigation/CoreNav.php, src/CP/Navigation/NavItem.php, tests/CP/Navigation/ActiveNavItemTest.php
Likely during [this refactor](https://github.com/statamic/cms/pull/8880), we introduced a small regression around checking active state on nav items with implicit children via nested URLs.
For example, when you visit `/cp/updater/seo-pro`, it is not properly making the `Updates` nav item active. This PR fixes that.
=> [5.x] Fix active state for nav items with implicit children

.github/workflows/release.yml, .gitignore, composer.json, config/cp.php, package.json, src/Console/Commands/Install.php, src/Providers/AppServiceProvider.php, src/Statamic.php, vite.config.js
In Vue 3, Vue Devtools are disabled. This PR introduces an opt-in dev build so you can use Vue Devtools and see un-minified code, which is useful during development of custom CP Vue components.
Your app must have debug mode enabled:
```env
APP_DEBUG=true
```
And the dev build must either be published:
```
php artisan vendor:publish --tag=statamic-cp-dev
```
Or, be symlinked:
```
ln -s /path/to/vendor/statamic/cms/resources/dist-dev public/vendor/statamic/cp-dev
```
You should obviously not commit these or use this on production.
=> [6.x] Provide a dev asset build

src/Tags/Trans.php, tests/Tags/TransTagTest.php
We're currently building a larger site with dynamic user-supplied translations. Lots of them are missing and we needed a mechanism for displaying a fallback translation if the requested key does not exist. Thought this might be useful to have in the core tag :)
```antlers
{{ trans key="messages.does_not_exist" }}
Output: messages.does_not_exist
```
```antlers
{{ trans key="messages.does_not_exist" fallback="Literal fallback" }}
Output: Literal fallback
{{ trans key="messages.does_not_exist" fallback="messages.fallback_key" }}
Output: Fallback from existing key
```
=> [5.x] Add optional fallback for missing keys in `{{ trans }}` tag

src/Entries/Entry.php, src/Http/Controllers/API/ApiController.php, src/Providers/CacheServiceProvider.php, src/StarterKits/ExportableModule.php, src/StarterKits/Exporter.php, src/StarterKits/InstallableModule.php, src/StarterKits/Module.php, tests/StarterKits/ExportTest.php, tests/StarterKits/InstallTest.php
This pull request follows on from #11612, removing deprecated features from past versions. 
* Removed the `filterSortAndPaginate` method from the `ApiController`. Deprecated in https://github.com/statamic/cms/pull/10893
* Removed the `export_as` option from starter kits, in favour of the `export` option. Deprecated in #11119
* Removed our custom `statamic` cache store. Deprecated in #10362
* Removed the `addLocalization` method from the `Entry` class, in favour of the `makeLocalization` method. Deprecated in #8505
=> [6.x] Deprecations

src/Extend/Addon.php, src/Extend/Manifest.php, src/Marketplace/Client.php, src/Marketplace/Marketplace.php, tests/Extend/AddonTest.php
This pull request improves how Statamic generates addon manifests. 
Instead of sending API requests whenever the application is booted, API requests will now only be sent as Marketplace data is needed. 
We're now bundling all packages into a single API request, rather than separate requests for each package.
=> [5.x] Addon Manifest improvements

src/Console/Commands/AssetsCacheClear.php, src/Providers/ConsoleServiceProvider.php
I thought it might be nice to add `php please assets:clear-cache` for those of us who are using custom asset meta and container contents stores, giving a one-stop command to clear both caches.
=> [5.x] Add command to clear asset_meta and asset_container_contents caches

resources/js/components/blueprints/Section.vue, resources/js/components/blueprints/Sections.vue, resources/js/components/ui/Publish/Sections.vue, src/Fields/Section.php, src/Http/Controllers/CP/Fields/ManagesBlueprints.php
This PR resolves:
- https://github.com/statamic/ideas/issues/1033
Adds two toggles to the section editor:
And results in the following UI:
=> [6.x] Collapsible blueprint sections

resources/js/components/fieldtypes/LinkFieldtype.vue, resources/js/components/fieldtypes/assets/AssetsFieldtype.vue
Fixes #12013 
This PR adds a gap in between the text at the bottom of the Link field when choosing an Asset to link to.
Before:
After:
=> [5.x] Add missing gap in between text in Link Asset

src/Console/Commands/AssetsGeneratePresets.php
This PR fixes generate presets command stdout.
Running `sail artisan statamic:assets:generate-presets`
It adds an _errors_ line even if there's no error
```bash
Generating presets for Medias...
┌ Generating cp_thumbnail_small_portrait for picture.png... ┐
│ ████████████████████████████████████████████████████████████   │
└───────────────────────────────────────────────────── 1141/1141 ┘
[✔] 1141 images generated for 163 assets.
medium ................................................................ 163  
medium2x .............................................................. 163  
small ................................................................. 163  
small2x ............................................................... 163  
thumbnail …
```
=> [5.x] Fix assets:generate-presets command stdout

src/Fieldtypes/Toggle.php, tests/Fieldtypes/ToggleTest.php
This makes sure that any nulls are converted to false for any queries. See #11976
=> [5.x] Cast toggle fieldtype queryable value to boolean

resources/css/components/nav-main.css
This fixes #12023,  a regression introduced in https://github.com/statamic/cms/pull/12012.
=> [5.x] Fix nav padding, only apply to last <ul>

src/Stache/Stores/Store.php
Fixes https://github.com/statamic/cms/issues/11862
=> [5.x] Updated the Stache Store to not remove stache items that exist

src/Query/EloquentQueryBuilder.php
This PR adds support for pluck() on the base eloquent query builder to bring parity with the stache builder.
This allows you to do queries like:
```php
\Statamic\Facades\Entry::query()->pluck('title');
```
instead of 
```php
\Statamic\Facades\Entry::query()->get()->pluck('title');
```
=> [5.x] Support pluck() on eloquent query builder

src/Actions/Impersonate.php, src/Http/Controllers/CP/Users/UsersController.php, tests/Actions/ImpersonateTest.php, tests/Auth/ElevatedSessionTest.php, tests/ElevatesSessions.php, tests/Feature/Users/CreateUserTest.php, tests/Feature/Users/EditUserTest.php, tests/Feature/Users/StoreUserTest.php, tests/Feature/Users/UpdateUserTest.php, tests/TestCase.php
- When impersonating another user, clear the elevated session state. This will force the user to elevate their session where necessary.
- Require an elevated session when editing users.
=> [6.x] Elevated session updates

composer.json, src/Fieldtypes/Bard/LinkMark.php
This pull request updates `ueberdosis/tiptap-php` to `^2.0`. You can find [the changelog here](https://github.com/ueberdosis/tiptap-php/releases/tag/2.0.0).
The update only contains two breaking changes:
* Custom protocols (like our `statamic`, `entry` and `asset` ones) now need to be added to an allow list.
* https://github.com/ueberdosis/tiptap-php/pull/70
* Removes some wrapper logic around lists and `<p>` tags
* https://github.com/ueberdosis/tiptap-php/pull/71
Closes https://github.com/statamic/ideas/issues/1355.
=> [6.x] Update `ueberdosis/tiptap-php` to `^2.0`

resources/js/components/ui/Checkbox/Item.vue
The `ui-checkbox-item` element does not currently support tabindex.
This PR adds `tabindex` support, and places it on the visually apparent checkbox element.
Improves the visual appearance of checkbox focusing with tabindex in #12058.
=> [6.x] Add tabindex support to the ui-checkbox-item

resources/css/ui.css, resources/js/components/ui/Button/Button.vue
Related to #12071. We'd discussed this internally before and it was probably on the cards anyway.
This also removes the hard-coded dark mode classes in favor of the primary color.
=> [6.x] Change the primary button color from black to the defined primary color

resources/js/components/ui/Input/Input.vue
When you're working locally without https, the browser clipboard api doesn't work. The copy button would do nothing. 
See #12074
This PR will hide the button in that case.
This PR also does some necessary clean up to Input component.
- `hasPrependedIcon` and `hasAppendedIcon` are computeds which allows it to adapt to prop changes (and so we can use the `copyable` computed in it)
- `iconClasses` is a computed (like `inputClasses` already was) and performs `twMerge`. The large diff there is really due to indentation.
- `inputClasses` and `iconClasses` use `.value` because they now reference computeds
- Removed unnecessary `.value` usage from the template
=> [6.x] Input only shows copy button if supported

resources/js/components/assets/Browser/Browser.vue
Don't inadvertently affect the vertical padding now that we've correctly aligned buttons in PanelHeaders and make the headers the same height whether buttons are present or not
=> [6.x] Fix the assets toolbar-padding

resources/css/core/layout.css
Related to #12084
The sidebar width should be wide enough to accommodate badges without wrapping. This change accommodates duplicate IDs appearing with double digits
This is what happens currently:
I can think of 3 different solutions for this wrapping problem…
1. Change it to `flex-wrap: wrap;`, as below, (which I'm pretty sure we don't want)
2. Make the flex gap very slightly smaller
3. Make the width of the sidebar very slightly wider—literally going from `w-46` to `w-48` to account for a badge with double digits
I think (3) makes the most sense, since Duplicate IDs with a badge is the longest sidebar item we have, so that should see us through.
This is the sidebar with solution 3
=> [6.x] The sidebar width should be just wide enough to accommodate badges without wrapping

resources/js/components/inputs/relationship/CreateButton.vue
This pull request fixes various issues with the "Create" button in relationship fieldtypes:
* The dropdown was showing when there was only one creatable.
* When there's multiple creatables, the stack would open at the same time as the dropdown
Fixes #12103
=> [6.x] Fix "Create" button in relationship fieldtypes

resources/js/components/fieldtypes/replicator/Set.vue
=> [6.x] Fix badges in replicator set headers

resources/js/components/navigation/View.vue
This pull request fixes an issue where new nav items would show as "published" until you refresh the page, where they correctly show as a "draft". Fixes #12156.
This is happening because the `StatusIndicator`'s `status` prop defaults to `status` when no value is provided:
https://github.com/statamic/cms/blob/2ddc8c2b0b7fdbe327bb9bf8e53aa401e44dd617/resources/js/components/ui/StatusIndicator.vue#L9
New nav items only have `id`, `title`, `url` keys. Whereas, existing nav items have some additional keys, like `status` (which is `null` for URL items), `can_delete`, `children`, etc.
This PR fixes the issue by adding a `status` key to the object, but we could alternatively fix it by doing something like `page.status ?? null` here:
https://github.com/statamic/cms/blob/2ddc8c2b0b7fdbe327bb9bf8e53a …
=> [6.x] Fix default published state of new nav items

resources/js/components/ui/Field.vue
Fields are not currently being translated. 
In the `Publish/Field.vue`, the display is correctly enclosed with `__(config.display)` to translate the display label.
For instructions, this was missing.
This became an issue when using localisation strings in a package: they would not be translated, and would fallback to the localisation key being used. 
This PR translates the instructions before being passed to through `markdown`.
=> [6.x] Correctly translate instructions for a ui-field

resources/js/components/ui/Combobox.vue
Currently, the chevron icon is shown even when the dropdown isn't used (eg. in the case of the Taggable fieldtype where all options are added via the input).
This PR adds a condition to the icon so its only shown when there are actually options.
=> [6.x] Combobox: Hide chevron icon unless there are options to pick from

resources/js/components/ui/Listing/Listing.vue
This PR attempts to fix #12104, where the `Listing` component would error out when the URL contains non-listing query parameters.
For example: visiting `/cp/collections/pages?foo=bar` and using "List" view would result in a `TypeError`.
This PR fixes it by only setting listing parameters when those parameters actually exist in the `params` object (the URL's query params).
=> [6.x] Fix error on listings when query parse 

.github/workflows/release.yml
This fixes an issue where you would see an error when updating to 6.0.0-alpha.2.
```
In TarDownloader.php line 32:
Extraction from phar "/Users/jason/Sites/Throwaway/statamic5-to-6/vendor/composer/tmp-a8f0d63920d718d60b676de17c82051b.gz" failed: Cannot extract
".", internal error
```
The issue seemed to be with the tar command using `.` that it would include a `.` directory in the listing and that's where it errored out.
The new command avoids this listing.
In alpha 1 the tar contained paths like these:
- `js/package/ui.js`
- `js/package/package.json`
- `js/package/types/util/clone.d.ts`
This caused unwanted nested directories. #12120 attempted to fix it, but resulted in paths like these:
- `./`
- `./ui.js`
- `./package.json`
- `./types/util/clone.d.ts`
This PR results in paths like …
=> [6.x] Generate dist tar differently

resources/js/package/vite-plugin.js
There's currently an issue where components don't resolve correctly when running `vite`. But running `vite build` works fine.
This PR will automatically run `vite build --watch` and output a warning.
This is temporary until the issue is resolved. You will still need to use a symlink.
If you really want to run the server (maybe for debugging the hotfile etc) you can use an environment variable.
```
STATAMIC_FORCE_SERVE=1 vite
```
=> [6.x] Automatically run vite build watch

src/Http/Controllers/OAuthController.php
This PR repairs a possible *null* in parse_url() argument.
PHP Deprecated
parse_url(): Passing null to parameter # 1 ($url) of type string is deprecated
=> [5.x] Prevent null parse_url deprecation warning

config/cp.php, resources/css/ui.css, resources/js/components/ui/Checkbox/Item.vue, resources/js/components/ui/Radio/Item.vue, src/CP/Color.php
Now if you want to customize the accent color for your form inputs (e.g. checkboxes and radios), you can.
```php
// config/statamic/cp.php
'theme' => [
//...
'ui-accent' => Color::Blue[600],
'dark-ui-accent' => Color::Cyan[600],
//...
];
```
=> [6.x] UI accent color theme config

config/cp.php, resources/css/components/progress.css, resources/css/ui.css, src/CP/Color.php
Now if you want to customize the progress bar (shown at the top of the page on slower loading requests), you can:
```php
// config/statamic/cp.php
'theme' => [
//...
'progress-bar' => Color::Purple[400],
//...
];
```
=> [6.x] Configurable progress bar color

resources/css/ui.css, resources/js/components/ui/Switch.vue, src/CP/Color.php
This makes switches use the ui accent color by default.
With no customizations, the toggles are black (zinc-800) now to match the primary button color.
If you define `ui-accent`, checkboxes, radios, and now toggles will use this accent color.
```php
'theme' => [
'ui-accent' => \Statamic\CP\Color::Blue[600],
]
```
You can additionally set the `switch-bg` to make toggles different from the accent:
```php
'theme' => [
'ui-accent' => \Statamic\CP\Color::Blue[600],
'switch-bg' => \Statamic\CP\Color::Green[600],
]
```
In addition:
- This reverts 39037e1
- This switches (ha) the variable names to use `switch` instead of `toggle`, since `Switch` is the actual component name.
- This adds `--color-dark-switch-bg` which was being used in the component but never defined in the css.
=> [6.x] Switch (Toggle) accents

resources/css/components/fieldtypes/spacer.css
Closes #12205. The spacer field was collapsing because it was being set to `display: none;` rather than `visibility:hidden;`. This fixes that
=> [6.x] Fix spacer field from collapsing

resources/lang/en/messages.php, src/Preferences/CorePreferences.php
Even though we're trying to hit WCAG 2.2 everywhere, it's a huge task and strict compliance won't happen soon, so I've cleared up the messaging here and removed that glorious badge.
I've also been more explicit about what this toggle does, because I don't want our intentions to be misunderstood.
=> [6.x] Clearer WCAG 2.2 Messaging

resources/js/components/SessionExpiry.vue
We added `:dismissible="false"` to the session expiry modals in #12223, but we missed one. This PR adds it, even if it isn't _technically_ required as we're not listening to the `update:open` event.
=> [6.x] Add `:dismissible="false"` to other modal in `SessionExpiry.vue`

resources/js/components/ui/DatePicker/DatePicker.vue, resources/js/components/ui/DateRangePicker/DateRangePicker.vue
This pull request fixes a bug I introduced in #12127, where the `border-dashed` class was being applied, even without the field being read-only.
I _believe_ this was happening because the `read-only:` modifier only works on inputs, not divs. This PR fixes it by applying the class conditionally, based on JS.
=> [6.x] Date Fieldtype: Prevent dashed border showing in non-read-only state

resources/js/components/globals/PublishForm.vue
This PR removes unnecessary margin between the site selector and the "Save" button on the global set publish form. Spacing is applied automatically by the `ui-header` component.
=> [6.x] Remove unnecessary margin from globals publish form

resources/views/blueprints/index.blade.php
For localisation of addons, using a language key as a title to ensure it can be fully translated.
However, on the Blueprints view, under the 'additional' blueprints populated from `Blueprint::getRenderableAdditionalNamespaces()`, the titles are not translated, resulting in the key being shown instead.
This PR corrects this for v5.
=> [5.x] Translate additional blueprint titles

resources/js/components/inputs/relationship/Selector.vue
This pull request fixes two issues when selecting entries in the relationship selector:
* Clicking on an entry title should select the entry, not take you to the entry publish form.
* Clicking on branches in the tree view should select the entry
=> [6.x] Relationship selector tweaks

resources/js/components/Preference.js, resources/js/components/Theme.js
Currently, when you visit the login page (or another auth page), Statamic will make a network request to save the `theme` preference.`
However, since you're unauthenticated, the request fails:
This PR avoids saving the `theme` preference unless there's an authenticated user.
=> [6.x] Avoid saving theme preference when unauthenticated

resources/views/components/outside-logo.blade.php
This sets a default max-width of `75%` on the logo area, which is used for custom logos. `max-w-[300px]` used to be set on the container in v5, but now it's `max-w-[400px]` since the component itself is wider.
So this makes custom logo `max-width` a little more palatable, being slightly narrower than the card.
I've set this to a % value so it also works well on mobile.
=> [6.x] Login custom logo width

src/Auth/Permissions.php
This pull request "blinks" the return value of `Permissions@flattened()`, which improves CP performance significantly on some sites.
`Permissions@flattened()` was added in #11516. Performance issues were reported on [Discord](https://discord.com/channels/489818810157891584/1408132171452911696/1408504777079521370).
=> [6.x] Cache flattened permissions

src/Assets/Asset.php
We're currently exploring ways to build an asset index that tracks asset usage throughout the cms, to make updating references more performant in a system with a large amount of entries. In a lot of ways the current structure makes that very easy by overwriting/extending some parts of the `UpdateAssetReferences` subscriber.
However, when replacing an asset, the Asset class temporarily disables the Subscriber to not react to the `AssetDeleted` event, if the "delete old asset"-option is enabled. Unfortunately this doesn't affect my custom class, that I've bound in a service provider.
So, this PR simply changes these `enable()` and `disable()` calls to use the service container 😇 
If you have any other ideas/suggestions on how to solve this instead, I'm happy for any input.
=> [5.x] Make UpdateAssetReferences overwritable

resources/js/components/ui/Dropdown/Item.vue
This closes #12227, making the header dropdown background (e.g. Save & Publish, Edit Blueprint, etc.) the same as the combobox hover background.
=> [6.x] Combobox hover contrast

resources/js/components/ui/Combobox.vue
This closes #12221 and adds a tiny bit of visual distinction between dropdown items. This is most noticeable when preventing a _selected_ item and the rest of the items from colliding into each other.
I'm targeting the data attribute here that Reka renders because I'm not sure if it's possible to reach inside it.
This affects all comboboxes, but that's intentional.
=> [6.x] Combobox item separation

resources/js/components/field-conditions/ShowField.js, resources/js/components/field-conditions/Validator.js, resources/js/components/ui/Publish/Container.vue, resources/js/components/ui/Publish/Field.vue, resources/js/components/ui/Publish/Sections.vue, resources/js/components/ui/Publish/Tabs.vue, resources/js/tests/FieldConditionsValidator.test.js
This pull request makes the publish container available in custom field conditions. Field conditions can use any of the variables/functions [provided by the `Container` component](https://github.com/statamic/cms/blob/master/resources/js/components/ui/Publish/Container.vue#L206).
Example:
```js
Statamic.$conditions.add('test', function ({ container }) {
return container.site.value === 'en';
});
```
=> [6.x] Make `container` available in custom field conditions

resources/css/core/utilities.css, resources/css/elements/tables.css
This fixes table border-radius for Firefox, along with a hover state adjustment.
It also improves things for Safari.
This closes #12070
In Firefox’s implementation, tbody’s background and border properties aren’t rendered as a box, so border-radius has no visual effect.
Instead, I've styled the tds.
Similar to Firefox, in WebKit (Safari), any background, borders, or box-shadow applied to tbody are simply ignored — the browser paints only the table itself and its cells. Instead, our only option is to style the tds with borders instead of shadows. I've added an alternative shadow for browsers like Chrome to compensate for the new border.
=> [6.x] Table fixes for Safari and Firefox

resources/lang/de.json, resources/lang/de_CH.json
The entry count in German currently doesn't have a `:count` variable, but the original English one does. This fixes it so the entry count is displayed properly in German.
=> [6.x] Fix German entry count translation

resources/js/components/fieldtypes/bard/LinkToolbarButton.vue, resources/js/components/two-factor/TwoFactor.vue
This pull request removes the fixed widths from the 2FA and Bard Link popovers, in favour of a `min-width` & `width: min-content`. 
This fixes various issues where localized strings would cause the contents of the popover to overflow the "container".
Fixes #12308
Fixes #12310
=> [6.x] Popovers shouldn't use fixed widths, to account for localization

src/Fieldtypes/Checkboxes.php
The default "Value" heading doesn't make much sense, so I've added a `value_header` to the options field to make it `Label (Optional)`, like similar fieldtypes (button group, select, etc).
Closes #12341.
=> [6.x] Checkboxes fieldtype: Option value should be a "label"

resources/js/components/ui/Field.vue
This closes #12332. Ideally, extra actions should be in a separate container so their height does not affect anything to the left, but this was a more straightforward fix for now.
Before:
After:
=> [6.x] Make sure field actions do not inherit bottom margin

composer.json, tests/CP/StartPageTest.php, tests/Fieldtypes/ListTest.php, tests/Fieldtypes/TaggableTest.php, tests/Modifiers/ResolveTest.php, tests/Policies/AssetContainerPolicyTest.php, tests/Policies/AssetFolderPolicyTest.php
This pull request fixes the namespace of various tests and excludes fixtures from Composer's classmap, ensuring it doesn't try and autoload them.
These changes prevent Composer's warnings around PSR-4 autoloading:
=> [5.x] Prevent PSR-4 warnings

resources/lang/en/fieldtypes.php, src/Fieldtypes/Code.php
This pull request moves the "Line Style (dashed or solid)" string used in one of the Code Fieldtype's config options to `fieldtypes.php`, as the parenthesises seem to throw off the translator.
Fixes #12339.
=> [6.x] Fix translation in Code Fieldtype

resources/js/components/entries/PublishForm.vue, resources/js/components/ui/Publish/Localizations.vue
Closes #12336 
When using the ComboBox, only the locale handle is passed to the `localizationSelected()` function, so when it checks for properties like `localization.exists` then it breaks.
The update adds a quick check to see if only the handle (string) was passed to the function and if so, it finds the correct localization object from the list.
=> [6.x] Allow localization to be selected from ComboBox

resources/js/components/fieldtypes/markdown/MarkdownFieldtype.vue
This pull request inverts the default styles of the Tailwind Typography plugin in dark mode. 
It also fixes an issue where code in the code blocks isn't visible due to `code` being set to black in `base.css`. I've added an override in the Markdown Cheatsheet to ensure it's white.
Fixes #12307
=> [6.x] Invert text colour of Markdown Cheatsheet in dark mode

resources/js/components/command-palette/CommandPalette.vue
With my minimal knowledge, I have tried to make the two words translatable.
=> [6.x] Add translations in command palette

resources/css/core/layout.css
As mentioned in #12328, the sidebar position is on the wrong side when using RTL mode, included is a before and after screenshot:
**Before:**
<br/>
**After:**
=> [6.x] Adjust the sidebar position for RTL mode

resources/js/components/two-factor/Setup.vue, resources/js/components/ui/Field.vue
When you submit the two factor setup modal with an invalid code, a validation error is thrown, however it isn't being shown properly.
This PR fixes that by...
* Avoiding a variable conflict in `Setup.vue` where there are two `errors` defined
* Ensuring the `error` prop is reactive (eg. when the prop value changes, the error is actually reflected in the UI)
=> [6.x] Fix errors not showing on two factor setup modal

resources/js/components/assets/Editor/FocalPointEditor.vue
This pull request changes two things in the Focal Point Editor:
* Fixes the vertical spacing between buttons
* Fixes #12290
* Removes `<sup>` around percentages
*  Claude says the % signs shouldn't be <sup> symbols because they're not mathematic exponents.
* They represent percentage positions or coordinates, not mathematical powers. The % sign here indicates a percentage value, not a superscript notation. 
* Fixes #12289
=> [6.x] Focal Point Editor tweaks

resources/js/components/ui/Heading.vue, resources/js/components/ui/Input/GroupPrepend.vue, resources/js/components/ui/Label.vue
Currently, the `data-ui-subheading` that's inside `data-ui-panel-header` is a very similar color to its title above, which makes it hard to distinguish between the two.
To replicate this:
1. Edit a blueprint
2. Open up a Bard field
3. Scroll down to "Editor Settings" where you'll find an example of a `data-ui-subheading` sitting inside a `data-ui-panel-header`
My initial idea was to make the `data-ui-subheading` lighter, but considering the grey panel behind it, if it were made any lighter than its current `text-grey-600`, then it would not pass AA color contrast.
My second idea was to simply make the `data-ui-panel-header` title text darker, but I also think this isn't great because now it is too similar to the field titles inside the main white area.
Therefore, I think the best option …
=> [6.x] Improve the difference between the `data-ui-subheading` and the heading

resources/css/components/fieldtypes/table.css, resources/css/core/utilities.css, resources/css/elements/base.css
This closes #12318.
This commit:
- Brings back `.input-text` which is used in some array-like fields
- Tidies up `table.css`
- Adds some dark mode consideration for tables
Before:
After:
=> [6.x] Table styling

packages/ui/src/Context/Item.vue
This pull request adds `target` and `variant` props to the `Context/Item` UI component, copied from the `Dropdown/Item` component.
They're very similar components, but the classes and Reka primitive components are different.
Fixes #12450
=> [6.x] Add `target` and `variant` props to Context Item component

resources/js/components/inputs/relationship/RelationshipInput.vue
This pull request fixes an issue where validation errors weren't showing for relationship fieldtypes, due to `h-full` on the `RelationshipInput` component.
Partially fixes #12426
=> [6.x] Fix validation errors not showing for relationship fieldtypes

packages/ui/src/Textarea.vue
This pull request brings back the autosizing of textarea inputs, like we had in v5. 
Although, I'm not sure how this behaviour works alongside the `resize` prop, which enables the "dragger" thing in the bottom right corner.
Fixes #12432.
=> [6.x] Textareas should autosize

resources/views/licensing.blade.php
=> [6.x] Fix licensing table

packages/ui/src/EmptyState/Item.vue
This pull request adds the `cursor-pointer` class to create form items, ensuring the same cursor style is used on `<button>` elements as `<a>` elements.
=> [6.x] Add `cursor-pointer` to Create Form links

resources/css/components/fieldtypes/bard.css
At the moment the bard buttons setting is not responsive and overflows the container on smaller screens:
This PR makes it responsive:
https://github.com/user-attachments/assets/e5f9a05f-8c75-483d-be47-92dfec8f616c
Uses grid instead of flex so that the last row's buttons are aligned with the others while ensuring the buttons are still spread evenly when there's only one row. Dragging the buttons around the grid still seems to work fine.
=> [6.x] Make bard buttons setting responsive

resources/js/components/collections/Listing.vue
The Collection grid view was missing the `key` for each item in the grid.
This resulted in incorrect behaviour when deleting a Collection. The correct Collection is deleted, however the UI shows the entries of the deleted collection.
1. Install Statamic 6 alpha 7
2. Create a Collection (such as "C1")
3. Create an Entry in that Collection with a noticeable Title (i.e. "Entry 1")
4. Create a Collection that appears after C1 (such as "C2")
5. Create an Entry in that Collection with a noticeable Title (i.e. "Entry 2")
6. Go to the Collections view, and switch to Grid
7. Delete "C1" collection
C1 is deleted, and C2 takes the place of C1 in the UI. The entries shown under C2 are now those from C1.
The missing `key` attribute for the `v-for` loop causes this. 
This PR addresses this.
=> [6.x] Collection grid missing v-for key

resources/js/components/fieldtypes/FloatFieldtype.vue, src/Fieldtypes/Floatval.php
This pull request adds `prepend` and `append` options to the Float fieldtype, like the Integer fieldtype has.
=> [6.x] Add `prepend` and `append` options to Float fieldtype

resources/js/components/fieldtypes/grid/Grid.vue
In the Grid fieldtype, there is a `v-if` for the delete confirmation modal that had the condition:
`v-if="deletingRow"`
The `deletingRow` is the row index, zero-based.
This does not work for the first row: this condition fails when `deletingRow` is 0.
This PR updates the condition to explicitly look for when `deletingRow` is not `null`
=> [6.x] Correct Grid fieldtype deleting row condition

resources/js/components/ui/Publish/Tabs.vue
This pull request fixes an issue where the `actions` slot used for the "Visit URL" button, revisions, localisations wasn't showing on smaller screens.
This was because we were only rendering it when the sidebar was visible, which it isn't on mobile. This PR fixes it by rendering its contents below the publish form if there's no visible sidebar.
Fixes #12469
=> [6.x] Ensure publish form actions are visible on smaller screens

resources/js/components/inputs/relationship/Selector.vue
This pull request fixes some translations in the relationship selector. 
Similar to #12263
Fixes #12481
=> [6.x] Fix translations in relationship selector

resources/css/components/fieldtypes/table.css, resources/js/components/fieldtypes/ListFieldtype.vue
This pull request attempts to improve the List fieldtype in dark mode. Closes #12489
=> [6.x] Improve List fieldtype in dark mode

resources/js/components/GlobalSiteSelector.vue, resources/views/components/global-site-selector.blade.php
This pull request fixes the global site selector, where it wasn't possible to change site because the "pre Vue" version was positioned on top of the Vue component.
Caused by https://github.com/statamic/cms/issues/12454
Fixes #12496
=> [6.x] Fix global site selector

src/Http/Controllers/CP/Forms/FormSubmissionsController.php
This pull request fixes an issue with the form submission search query, where searching form submissions would return submissions from all forms, rather than just the current form.
This was happening due to the `->orWhere()` statements, which were effectively cancelling out the "where form = 'form_handle'` condition. 
Moving the search conditions into a nested `->where()` means they are evaluated as one, and can't negate other where statements on the query.
I was only able to replicate this issue on the Eloquent Driver, but the nested where can't do any harm.
Closes statamic/eloquent-driver#499
=> [5.x] Fix form submission search query

packages/ui/package.json
This pull request adds the necessary dependencies to the UI package's `package.json`, so we don't need to require them separately on the docs.
=> [6.x] Add dependencies to UI package

packages/ui/src/Checkbox/Item.vue
When using `ui-checkbox` on its own, you shouldn't need a `value` prop.
```<ui-checkbox v-model="toggleMe" />```
=> [6.x] Checkbox item component shouldnt have required value prop

src/Fields/Field.php
Fixes #11974.
When a user deletes an asset via the asset browser, it can lead to an asset field becoming null even though it is required by its blueprint. This creates a 500 error in the GraphQL endpoint and brings the entire page down.
This PR is a suggestion for a quick and easy fix by just making asset fields always nullable, regardless of whether they are set as `required` in their blueprint. Within the Control Panel, the field continues to be required, but as the asset deletion logic is able to squeeze a null into the asset field, its GraphQL type should be nullable.
=> [5.x] Make asset GraphQL type always nullable

resources/js/components/actions/ConfirmableAction.vue, resources/lang/ar.json, resources/lang/az.json, resources/lang/cs.json, resources/lang/da.json, resources/lang/de.json, resources/lang/de_CH.json, resources/lang/es.json, resources/lang/et.json, resources/lang/fa.json, resources/lang/fr.json, resources/lang/hu.json, resources/lang/id.json, resources/lang/it.json, resources/lang/ja.json, resources/lang/ms.json, resources/lang/nb.json, resources/lang/nl.json, resources/lang/pl.json, resources/lang/pt.json, resources/lang/pt_BR.json, resources/lang/ru.json, resources/lang/sl.json, resources/lang/sv.json, resources/lang/tr.json, resources/lang/uk.json, resources/lang/vi.json, resources/lang/zh_CN.json, resources/lang/zh_TW.json, src/Actions/SendPasswordReset.php
This should close #12536, making the modal look less repetitive—both visually and content-wise.
I did notice that it looks worse in dark mode because of some heavy shadowing but that's a separate "dark mode" issue that we'll tackle later
=> [6.x] Improve send password reset modal

resources/css/core/animation.css, resources/js/components/assets/AssetManager.vue, resources/js/components/assets/Browser/Browser.vue, resources/js/components/ui/Listing/Listing.vue, resources/views/assets/browse.blade.php, resources/views/components/docs-callout.blade.php
This closes #12466
- Removes the spinning loader icon
- Adds a skeleton for the Assets browser
- Very minor changes to transitions to improve the way this loads: adds 0.1s to the delay and adds a `.starting-style-delay` class, which is more effective at hiding the docs callout before the assets browser loads
=> [6.x] Improve Assets loading with skeleton

packages/ui/src/Panel/Panel.vue
For panel backgrounds, we're using a transparent background color so it sits between `gray-100` and `gray-200`.
While I would usually avoid doing this, the cp is pretty much grayscale, so I think this halfway shade is needed to help legibility—100 is too light, and 200 is too muddy.
Anyway, this is fine _but_ there is a side effect when certain things run _behind_ the panel. I'm particularly thinking of the "architectural lines" background here, but it could be anything, really.
Here is an example:
If we add a slight backdrop blur this effectively mitigates the transparency. A value of about `5px` is enough but I've set it to `10px` to be safe.
Now we can't see anything underneath the panel, but we keep our halfway-house shade of gray.
_P.s. I initially thought of making a custom opaque …
=> [6.x] Prevent panel transparency

resources/css/components/fieldtypes/bard.css, resources/css/components/fieldtypes/grid.css, resources/css/components/fieldtypes/table.css, resources/js/components/fieldtypes/bard/Set.vue, resources/js/components/fieldtypes/replicator/Set.vue
This fixes #12431.
- Primarily because of the `overflow: hidden;` on the `v-motion` container. This prevents `position: sticky;` from working. There are a few more "modern" ways of preventing overflow, `contain: paint;` being the most performant, so I went with that.
- The selectors needed to be changed a little—probably because of the new components
- I fixed sticky tables while I was here
- I added a bit of margin / negative margin to the subsequent element to stop the straight corners from bumping up to the rounded corners of the bottom of the container, like this:
(instead of this)
=> [6.x] Sticky toolbars

resources/js/components/inputs/relationship/RelationshipInput.vue, resources/lang/fr.json
Fixes #12523 by adding a margin after the "maximum items" instruction.
I considered adding a space to the end of the string but thought that would require every translation to add a space, and I can't imagine people's attention to detail is that great.
I also considered adding a space in the span but that's trimmed when output in the browser.
=> [6.x] Relationship fields fix space after colon

resources/js/components/actions/ConfirmableAction.vue, resources/js/components/modals/ConfirmationModal.vue, src/Actions/Action.php
This pull request allows action developers to render custom Vue components instead of our default confirmation text. It also allows developers to hide the "Run action" button in action modals.
* One use case for this is @ryanmitchell's cache tracker addon, where he wants to show a list of cache keys for a certain entry. 
* The custom component is used to list cache keys, and the "Run action" button is hidden because there's no real "action" behind it. 
* In this scenario, actions is the way of getting a dropdown item & modal for free on listings.
* Another use case for this might be refactoring the `fieldset-deleter` component.
* Currently, it's not action because we display a list of places the fieldset is being used. All imports need to be replaced before the developer can delete the …
=> [6.x] Ability to use custom components & hide "Run action" button in action modals

packages/ui/src/Header.vue
This removes the starting style transition (entry animation) from the header area, e.g. the name of the collection such as "Pages" on the name of the CP area like "Navigation"
I think it makes sense to keep entry animations for areas that frequently change structure; for example, the main panel area, but for the header area, it's almost _always_ the same structure on every page, so we don't need to transition it now that we have Inertia ⚡
=> [6.x] Remove header starting style

resources/css/components/fieldtypes/bard.css
This fixes the border-radius of the focus state when a Bard field is in floating toolbar mode
=> [6.x] Bard floating toolbar mode fix container focus state

resources/js/components/global-header/Logo.vue, src/Http/Middleware/CP/HandleInertiaRequests.php
This brings back the site name in the header that dropped off in #12610.
=> [6.x] Fix missing site name in header

resources/js/components/Toasts.js, src/CP/Toasts/Manager.php, src/Http/Middleware/CP/HandleInertiaRequests.php
Any toasts pushed with the facade will get shown for inertia requests.
e.g. `Toast::success('Nice.');`
If there's a redirect with a flash message, that'll also get shown for inertia requests.
e.g. `return back()->withSuccess('Nice.');`
=> [6.x] Inertia toast handling

resources/js/components/structures/PageEditor.vue
Probably a preference thing, but I agree with the issue creator:  "Submit" makes me think it's going to save the changes right away, but "Apply" makes me think it's going to be part of the next save.
Closes #12562
=> [6.x] Change wording of "Submit" button in nav page editor

packages/ui/src/Modal/Modal.vue, resources/js/components/collections/DeleteEntryConfirmation.vue, resources/js/components/navigation/RemovePageConfirmation.vue
This pull request fixes an issue where you could dismiss the deletion modals on the collection/nav trees, but it meant you couldn't re-open it.
This PR fixes it by introducing a `dismissable` event which we can listen to and emit a `cancel` event to the parent component (we emit the same event when you click the "Cancel" button).
Fixes #12565.
=> [6.x] Fix deletion modals on structure trees

resources/js/pages/layout/Outside.vue, src/Http/Middleware/CP/HandleAuthenticatedInertiaRequests.php
- Fixes #12690
- Fixes the "Create Form" button disappearing when you return to that page because `isPro` would not be in the props.
=> [6.x] Fix inertia pro logic
